
public class Test06 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Hxsm Rpfk", "Udna"),
            new Tretja.Oseba("Qhsn Oxoj", "Fdft"),
            new Tretja.Oseba("Advm Wqqc", "Fdft"),
            new Tretja.Oseba("Rgee Yzyo", "Vzyf"),
            new Tretja.Oseba("Gvvo Fwwd", "Udna"),
            new Tretja.Oseba("Kwip Cuet", "Pral"),
            new Tretja.Oseba("Oabd Xhjl", "Fdft"),
            new Tretja.Oseba("Apfz Meqh", "Vzyf"),
            new Tretja.Oseba("Zdpf Xygx", "Fdft"),
            new Tretja.Oseba("Yzch Wwkb", "Vzyf"),
            new Tretja.Oseba("Nlbb Ewhn", "Fdft"),
            new Tretja.Oseba("Anpt Ybmp", "Vzyf"),
            new Tretja.Oseba("Uhi Jelb", "Pral"),
            new Tretja.Oseba("Bjlc Poq", "Vzyf"),
            new Tretja.Oseba("Npzm Ftrx", "Fdft"),
            new Tretja.Oseba("Nvfq Cxme", "Vzyf"),
            new Tretja.Oseba("Hyrd Jkwq", "Fdft"),
            new Tretja.Oseba("Flvg Qvdt", "Vzyf"),
            new Tretja.Oseba("Rzdr Zrvr", "Vzyf"),
            new Tretja.Oseba("Ksba Arxh", "Vzyf"),
            new Tretja.Oseba("Igfe Hsyj", "Udna"),
            new Tretja.Oseba("Iupk Feqh", "Udna"),
            new Tretja.Oseba("Yrlg Tqco", "Udna"),
            new Tretja.Oseba("Tls Vkkd", "Pral"),
            new Tretja.Oseba("Egew Gckq", "Fdft"),
            new Tretja.Oseba("Htke Nynk", "Fdft"),
            new Tretja.Oseba("Kdbo Kynr", "Vzyf"),
            new Tretja.Oseba("Oxsu Lqqi", "Vzyf"),
            new Tretja.Oseba("Tke Dyde", "Fdft"),
            new Tretja.Oseba("Jldc Htdf", "Fdft"),
            new Tretja.Oseba("Prqd Khhd", "Udna"),
            new Tretja.Oseba("Ylfm Mopm", "Pral"),
            new Tretja.Oseba("Rmlz Kqog", "Udna"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Arah", "Vzyf"),
            new Tretja.Cilj("Vpje", "Vzyf"),
            new Tretja.Cilj("Geip", "Pral"),
            new Tretja.Cilj("Cje", "Fdft"),
            new Tretja.Cilj("Mmpo", "Vzyf"),
            new Tretja.Cilj("Asuj", "Udna"),
            new Tretja.Cilj("Vduo", "Vzyf"),
            new Tretja.Cilj("Xthw", "Pral"),
            new Tretja.Cilj("Krdl", "Pral"),
            new Tretja.Cilj("Semd", "Vzyf"),
            new Tretja.Cilj("Qxqp", "Udna"),
            new Tretja.Cilj("Qizo", "Vzyf"),
            new Tretja.Cilj("Alyi", "Pral"),
            new Tretja.Cilj("Tana", "Fdft"),
            new Tretja.Cilj("Ahgz", "Vzyf"),
            new Tretja.Cilj("Rsqn", "Udna"),
            new Tretja.Cilj("Kzuh", "Fdft"),
            new Tretja.Cilj("Eikc", "Fdft"),
            new Tretja.Cilj("Axyb", "Vzyf"),
            new Tretja.Cilj("Wsni", "Pral"),
            new Tretja.Cilj("Rqdl", "Udna"),
            new Tretja.Cilj("Bczb", "Udna"),
            new Tretja.Cilj("Rgoa", "Fdft"),
            new Tretja.Cilj("Xczz", "Pral"),
            new Tretja.Cilj("Zsto", "Udna"),
            new Tretja.Cilj("Nyiy", "Udna"),
            new Tretja.Cilj("Rrui", "Vzyf"),
            new Tretja.Cilj("Msrz", "Fdft"),
            new Tretja.Cilj("Rgfs", "Pral"),
            new Tretja.Cilj("Yogf", "Fdft"),
            new Tretja.Cilj("Lhcc", "Pral"),
            new Tretja.Cilj("Ckln", "Fdft"),
            new Tretja.Cilj("Yzjg", "Fdft"),
            new Tretja.Cilj("Kegn", "Pral"),
            new Tretja.Cilj("Qosu", "Vzyf"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[29], cilji[24], 2006),
            new Tretja.Nocitev(osebe[29], cilji[24], 2016),
            new Tretja.Nocitev(osebe[18], cilji[4], 2003),
            new Tretja.Nocitev(osebe[22], cilji[17], 2005),
            new Tretja.Nocitev(osebe[30], cilji[15], 2009),
            new Tretja.Nocitev(osebe[0], cilji[2], 2002),
            new Tretja.Nocitev(osebe[32], cilji[19], 2000),
            new Tretja.Nocitev(osebe[16], cilji[28], 2012),
            new Tretja.Nocitev(osebe[30], cilji[15], 2015),
            new Tretja.Nocitev(osebe[30], cilji[15], 2016),
            new Tretja.Nocitev(osebe[17], cilji[25], 2015),
            new Tretja.Nocitev(osebe[11], cilji[19], 2017),
            new Tretja.Nocitev(osebe[30], cilji[15], 2006),
            new Tretja.Nocitev(osebe[23], cilji[22], 2002),
            new Tretja.Nocitev(osebe[17], cilji[25], 2001),
            new Tretja.Nocitev(osebe[24], cilji[2], 2001),
            new Tretja.Nocitev(osebe[32], cilji[20], 2009),
            new Tretja.Nocitev(osebe[17], cilji[25], 2005),
            new Tretja.Nocitev(osebe[14], cilji[19], 2000),
            new Tretja.Nocitev(osebe[12], cilji[17], 2009),
            new Tretja.Nocitev(osebe[32], cilji[19], 2011),
            new Tretja.Nocitev(osebe[22], cilji[4], 2009),
            new Tretja.Nocitev(osebe[26], cilji[18], 2004),
            new Tretja.Nocitev(osebe[30], cilji[15], 2007),
            new Tretja.Nocitev(osebe[17], cilji[25], 2007),
            new Tretja.Nocitev(osebe[0], cilji[4], 2007),
            new Tretja.Nocitev(osebe[3], cilji[21], 2007),
            new Tretja.Nocitev(osebe[13], cilji[13], 2002),
            new Tretja.Nocitev(osebe[18], cilji[4], 2020),
            new Tretja.Nocitev(osebe[6], cilji[1], 2009),
            new Tretja.Nocitev(osebe[31], cilji[14], 2013),
            new Tretja.Nocitev(osebe[14], cilji[1], 2014),
            new Tretja.Nocitev(osebe[13], cilji[30], 2017),
            new Tretja.Nocitev(osebe[25], cilji[3], 2005),
            new Tretja.Nocitev(osebe[8], cilji[6], 2004),
            new Tretja.Nocitev(osebe[17], cilji[25], 2013),
            new Tretja.Nocitev(osebe[7], cilji[15], 2019),
            new Tretja.Nocitev(osebe[31], cilji[14], 2001),
            new Tretja.Nocitev(osebe[4], cilji[25], 2010),
            new Tretja.Nocitev(osebe[0], cilji[22], 2019),
            new Tretja.Nocitev(osebe[6], cilji[1], 2009),
            new Tretja.Nocitev(osebe[26], cilji[18], 2002),
            new Tretja.Nocitev(osebe[16], cilji[25], 2012),
            new Tretja.Nocitev(osebe[11], cilji[0], 2000),
            new Tretja.Nocitev(osebe[32], cilji[30], 2013),
            new Tretja.Nocitev(osebe[31], cilji[14], 2002),
            new Tretja.Nocitev(osebe[17], cilji[25], 2012),
            new Tretja.Nocitev(osebe[22], cilji[0], 2014),
            new Tretja.Nocitev(osebe[31], cilji[14], 2010),
            new Tretja.Nocitev(osebe[24], cilji[26], 2016),
            new Tretja.Nocitev(osebe[13], cilji[1], 2013),
            new Tretja.Nocitev(osebe[27], cilji[29], 2000),
            new Tretja.Nocitev(osebe[31], cilji[14], 2012),
            new Tretja.Nocitev(osebe[32], cilji[23], 2017),
            new Tretja.Nocitev(osebe[1], cilji[24], 2003),
            new Tretja.Nocitev(osebe[16], cilji[27], 2016),
            new Tretja.Nocitev(osebe[4], cilji[25], 2020),
            new Tretja.Nocitev(osebe[2], cilji[14], 2016),
            new Tretja.Nocitev(osebe[29], cilji[24], 2003),
            new Tretja.Nocitev(osebe[29], cilji[24], 2018),
            new Tretja.Nocitev(osebe[6], cilji[1], 2006),
            new Tretja.Nocitev(osebe[25], cilji[10], 2009),
            new Tretja.Nocitev(osebe[23], cilji[15], 2005),
            new Tretja.Nocitev(osebe[10], cilji[5], 2002),
            new Tretja.Nocitev(osebe[9], cilji[21], 2002),
            new Tretja.Nocitev(osebe[18], cilji[4], 2000),
            new Tretja.Nocitev(osebe[17], cilji[25], 2020),
            new Tretja.Nocitev(osebe[12], cilji[16], 2016),
            new Tretja.Nocitev(osebe[16], cilji[14], 2004),
            new Tretja.Nocitev(osebe[15], cilji[11], 2002),
            new Tretja.Nocitev(osebe[32], cilji[24], 2004),
            new Tretja.Nocitev(osebe[31], cilji[14], 2010),
            new Tretja.Nocitev(osebe[18], cilji[4], 2011),
            new Tretja.Nocitev(osebe[16], cilji[5], 2014),
            new Tretja.Nocitev(osebe[1], cilji[24], 2007),
            new Tretja.Nocitev(osebe[8], cilji[21], 2008),
            new Tretja.Nocitev(osebe[32], cilji[34], 2003),
            new Tretja.Nocitev(osebe[5], cilji[20], 2011),
            new Tretja.Nocitev(osebe[26], cilji[18], 2010),
            new Tretja.Nocitev(osebe[32], cilji[25], 2006),
            new Tretja.Nocitev(osebe[12], cilji[6], 2019),
            new Tretja.Nocitev(osebe[1], cilji[24], 2013),
            new Tretja.Nocitev(osebe[31], cilji[14], 2017),
            new Tretja.Nocitev(osebe[19], cilji[19], 2000),
            new Tretja.Nocitev(osebe[6], cilji[1], 2005),
            new Tretja.Nocitev(osebe[5], cilji[20], 2005),
            new Tretja.Nocitev(osebe[9], cilji[21], 2016),
            new Tretja.Nocitev(osebe[30], cilji[15], 2013),
            new Tretja.Nocitev(osebe[11], cilji[6], 2008),
            new Tretja.Nocitev(osebe[25], cilji[18], 2013),
            new Tretja.Nocitev(osebe[19], cilji[17], 2018),
            new Tretja.Nocitev(osebe[30], cilji[15], 2008),
            new Tretja.Nocitev(osebe[31], cilji[14], 2000),
            new Tretja.Nocitev(osebe[8], cilji[26], 2019),
            new Tretja.Nocitev(osebe[31], cilji[14], 2006),
            new Tretja.Nocitev(osebe[23], cilji[12], 2007),
            new Tretja.Nocitev(osebe[27], cilji[5], 2003),
            new Tretja.Nocitev(osebe[0], cilji[27], 2019),
            new Tretja.Nocitev(osebe[23], cilji[31], 2009),
            new Tretja.Nocitev(osebe[11], cilji[26], 2000),
            new Tretja.Nocitev(osebe[5], cilji[20], 2019),
            new Tretja.Nocitev(osebe[19], cilji[14], 2019),
            new Tretja.Nocitev(osebe[23], cilji[12], 2001),
            new Tretja.Nocitev(osebe[27], cilji[18], 2007),
            new Tretja.Nocitev(osebe[1], cilji[24], 2020),
            new Tretja.Nocitev(osebe[27], cilji[34], 2016),
            new Tretja.Nocitev(osebe[26], cilji[18], 2011),
            new Tretja.Nocitev(osebe[16], cilji[5], 2014),
            new Tretja.Nocitev(osebe[26], cilji[18], 2014),
            new Tretja.Nocitev(osebe[6], cilji[1], 2008),
            new Tretja.Nocitev(osebe[27], cilji[12], 2001),
            new Tretja.Nocitev(osebe[5], cilji[20], 2009),
            new Tretja.Nocitev(osebe[27], cilji[33], 2007),
            new Tretja.Nocitev(osebe[26], cilji[18], 2016),
            new Tretja.Nocitev(osebe[10], cilji[5], 2017),
            new Tretja.Nocitev(osebe[21], cilji[19], 2007),
            new Tretja.Nocitev(osebe[23], cilji[23], 2018),
            new Tretja.Nocitev(osebe[27], cilji[25], 2000),
            new Tretja.Nocitev(osebe[25], cilji[18], 2020),
            new Tretja.Nocitev(osebe[19], cilji[12], 2006),
            new Tretja.Nocitev(osebe[26], cilji[18], 2009),
            new Tretja.Nocitev(osebe[21], cilji[20], 2019),
            new Tretja.Nocitev(osebe[2], cilji[14], 2020),
            new Tretja.Nocitev(osebe[21], cilji[33], 2014),
            new Tretja.Nocitev(osebe[27], cilji[34], 2012),
            new Tretja.Nocitev(osebe[23], cilji[1], 2007),
            new Tretja.Nocitev(osebe[16], cilji[30], 2014),
            new Tretja.Nocitev(osebe[17], cilji[25], 2020),
            new Tretja.Nocitev(osebe[11], cilji[0], 2020),
            new Tretja.Nocitev(osebe[7], cilji[30], 2016),
            new Tretja.Nocitev(osebe[24], cilji[19], 2003),
            new Tretja.Nocitev(osebe[7], cilji[5], 2019),
            new Tretja.Nocitev(osebe[19], cilji[16], 2003),
            new Tretja.Nocitev(osebe[30], cilji[15], 2016),
            new Tretja.Nocitev(osebe[15], cilji[11], 2020),
            new Tretja.Nocitev(osebe[2], cilji[14], 2009),
            new Tretja.Nocitev(osebe[30], cilji[15], 2011),
            new Tretja.Nocitev(osebe[4], cilji[25], 2017),
            new Tretja.Nocitev(osebe[9], cilji[21], 2017),
            new Tretja.Nocitev(osebe[30], cilji[15], 2014),
            new Tretja.Nocitev(osebe[30], cilji[15], 2000),
            new Tretja.Nocitev(osebe[30], cilji[15], 2003),
            new Tretja.Nocitev(osebe[11], cilji[28], 2016),
            new Tretja.Nocitev(osebe[31], cilji[14], 2002),
            new Tretja.Nocitev(osebe[32], cilji[21], 2018),
            new Tretja.Nocitev(osebe[31], cilji[14], 2020),
            new Tretja.Nocitev(osebe[14], cilji[9], 2007),
            new Tretja.Nocitev(osebe[29], cilji[24], 2006),
            new Tretja.Nocitev(osebe[7], cilji[33], 2009),
            new Tretja.Nocitev(osebe[31], cilji[14], 2003),
            new Tretja.Nocitev(osebe[18], cilji[4], 2017),
            new Tretja.Nocitev(osebe[21], cilji[28], 2004),
            new Tretja.Nocitev(osebe[18], cilji[4], 2005),
            new Tretja.Nocitev(osebe[29], cilji[24], 2013),
            new Tretja.Nocitev(osebe[10], cilji[5], 2016),
            new Tretja.Nocitev(osebe[8], cilji[16], 2007),
            new Tretja.Nocitev(osebe[4], cilji[25], 2002),
            new Tretja.Nocitev(osebe[23], cilji[0], 2000),
            new Tretja.Nocitev(osebe[7], cilji[14], 2001),
            new Tretja.Nocitev(osebe[7], cilji[19], 2004),
            new Tretja.Nocitev(osebe[25], cilji[23], 2011),
            new Tretja.Nocitev(osebe[13], cilji[21], 2000),
            new Tretja.Nocitev(osebe[28], cilji[24], 2004),
            new Tretja.Nocitev(osebe[13], cilji[32], 2000),
            new Tretja.Nocitev(osebe[0], cilji[10], 2006),
            new Tretja.Nocitev(osebe[18], cilji[4], 2012),
            new Tretja.Nocitev(osebe[30], cilji[15], 2011),
            new Tretja.Nocitev(osebe[2], cilji[14], 2014),
            new Tretja.Nocitev(osebe[18], cilji[4], 2018),
            new Tretja.Nocitev(osebe[20], cilji[23], 2002),
            new Tretja.Nocitev(osebe[17], cilji[25], 2004),
            new Tretja.Nocitev(osebe[6], cilji[1], 2003),
            new Tretja.Nocitev(osebe[24], cilji[3], 2012),
            new Tretja.Nocitev(osebe[2], cilji[14], 2014),
            new Tretja.Nocitev(osebe[24], cilji[20], 2000),
            new Tretja.Nocitev(osebe[19], cilji[26], 2019),
            new Tretja.Nocitev(osebe[22], cilji[3], 2006),
            new Tretja.Nocitev(osebe[22], cilji[14], 2007),
            new Tretja.Nocitev(osebe[2], cilji[14], 2000),
            new Tretja.Nocitev(osebe[27], cilji[3], 2008),
            new Tretja.Nocitev(osebe[5], cilji[20], 2018),
            new Tretja.Nocitev(osebe[30], cilji[15], 2014),
            new Tretja.Nocitev(osebe[26], cilji[18], 2004),
            new Tretja.Nocitev(osebe[4], cilji[25], 2014),
            new Tretja.Nocitev(osebe[4], cilji[25], 2016),
            new Tretja.Nocitev(osebe[22], cilji[3], 2002),
            new Tretja.Nocitev(osebe[19], cilji[10], 2015),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2007, 2018);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
