
public class Test02 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Yfqc Hets", "Ilaf"),
            new Tretja.Oseba("Dodo Jjq", "Mwwy"),
            new Tretja.Oseba("Mlru Talb", "Jdau"),
            new Tretja.Oseba("Epfy Oayc", "Jdau"),
            new Tretja.Oseba("Zwdw Gylq", "Jkrg"),
            new Tretja.Oseba("Jiag Mjcb", "Jdau"),
            new Tretja.Oseba("Uigy Fzls", "Mwwy"),
            new Tretja.Oseba("Olac Oekb", "Jkrg"),
            new Tretja.Oseba("Fcxu Lqwd", "Ilaf"),
            new Tretja.Oseba("Womw Ihnc", "Mwwy"),
            new Tretja.Oseba("Jajg Bofx", "Jdau"),
            new Tretja.Oseba("Hezk Vhe", "Jkrg"),
            new Tretja.Oseba("Czaa Txub", "Jdau"),
            new Tretja.Oseba("Cqvx Xulo", "Jkrg"),
            new Tretja.Oseba("Sede Cevi", "Jkrg"),
            new Tretja.Oseba("Jdoo Osnh", "Jkrg"),
            new Tretja.Oseba("Ncxd Vrop", "Jkrg"),
            new Tretja.Oseba("Cxmx Ezyo", "Jkrg"),
            new Tretja.Oseba("Lplj Ovtp", "Mwwy"),
            new Tretja.Oseba("Pdid Sbuc", "Mwwy"),
            new Tretja.Oseba("Cwd Lzhz", "Jdau"),
            new Tretja.Oseba("Eexj Kvah", "Jdau"),
            new Tretja.Oseba("Rmpi Sszq", "Jkrg"),
            new Tretja.Oseba("Anma Wqeo", "Mwwy"),
            new Tretja.Oseba("Ffxq Mgyx", "Mwwy"),
            new Tretja.Oseba("Nvix Qgog", "Jkrg"),
            new Tretja.Oseba("Zfg Cpzk", "Mwwy"),
            new Tretja.Oseba("Axqh Wjry", "Jdau"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Qdil", "Jkrg"),
            new Tretja.Cilj("Aqcp", "Jdau"),
            new Tretja.Cilj("Dqft", "Ilaf"),
            new Tretja.Cilj("Czmy", "Mwwy"),
            new Tretja.Cilj("Hrxa", "Jkrg"),
            new Tretja.Cilj("Plox", "Mwwy"),
            new Tretja.Cilj("Azps", "Jkrg"),
            new Tretja.Cilj("Jqia", "Jdau"),
            new Tretja.Cilj("Jqef", "Ilaf"),
            new Tretja.Cilj("Oyux", "Jdau"),
            new Tretja.Cilj("Hdjl", "Mwwy"),
            new Tretja.Cilj("Lxug", "Jdau"),
            new Tretja.Cilj("Ldqd", "Mwwy"),
            new Tretja.Cilj("Bdrw", "Jdau"),
            new Tretja.Cilj("Nudi", "Ilaf"),
            new Tretja.Cilj("Jcxr", "Ilaf"),
            new Tretja.Cilj("Qjdg", "Jdau"),
            new Tretja.Cilj("Iokn", "Jkrg"),
            new Tretja.Cilj("Urpe", "Jkrg"),
            new Tretja.Cilj("Ulei", "Jdau"),
            new Tretja.Cilj("Nfdk", "Mwwy"),
            new Tretja.Cilj("Ibrm", "Ilaf"),
            new Tretja.Cilj("Jelm", "Ilaf"),
            new Tretja.Cilj("Chwm", "Mwwy"),
            new Tretja.Cilj("Uqqd", "Ilaf"),
            new Tretja.Cilj("Jeao", "Jkrg"),
            new Tretja.Cilj("Qffy", "Ilaf"),
            new Tretja.Cilj("Jjuh", "Mwwy"),
            new Tretja.Cilj("Jlyu", "Jkrg"),
            new Tretja.Cilj("Ziin", "Ilaf"),
            new Tretja.Cilj("Auqt", "Jdau"),
            new Tretja.Cilj("Uhxc", "Jkrg"),
            new Tretja.Cilj("Mcwe", "Jkrg"),
            new Tretja.Cilj("Rzry", "Mwwy"),
            new Tretja.Cilj("Tqwv", "Ilaf"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[14], cilji[20], 2001),
            new Tretja.Nocitev(osebe[22], cilji[22], 2004),
            new Tretja.Nocitev(osebe[6], cilji[28], 2018),
            new Tretja.Nocitev(osebe[21], cilji[0], 2019),
            new Tretja.Nocitev(osebe[18], cilji[7], 2008),
            new Tretja.Nocitev(osebe[27], cilji[0], 2004),
            new Tretja.Nocitev(osebe[4], cilji[15], 2016),
            new Tretja.Nocitev(osebe[15], cilji[21], 2019),
            new Tretja.Nocitev(osebe[0], cilji[0], 2005),
            new Tretja.Nocitev(osebe[24], cilji[18], 2003),
            new Tretja.Nocitev(osebe[1], cilji[12], 2007),
            new Tretja.Nocitev(osebe[23], cilji[14], 2009),
            new Tretja.Nocitev(osebe[21], cilji[9], 2006),
            new Tretja.Nocitev(osebe[26], cilji[5], 2017),
            new Tretja.Nocitev(osebe[21], cilji[3], 2012),
            new Tretja.Nocitev(osebe[0], cilji[0], 2017),
            new Tretja.Nocitev(osebe[18], cilji[7], 2014),
            new Tretja.Nocitev(osebe[27], cilji[0], 2000),
            new Tretja.Nocitev(osebe[6], cilji[28], 2002),
            new Tretja.Nocitev(osebe[23], cilji[12], 2013),
            new Tretja.Nocitev(osebe[15], cilji[21], 2006),
            new Tretja.Nocitev(osebe[3], cilji[4], 2001),
            new Tretja.Nocitev(osebe[10], cilji[23], 2017),
            new Tretja.Nocitev(osebe[6], cilji[28], 2013),
            new Tretja.Nocitev(osebe[10], cilji[23], 2017),
            new Tretja.Nocitev(osebe[25], cilji[27], 2014),
            new Tretja.Nocitev(osebe[19], cilji[2], 2006),
            new Tretja.Nocitev(osebe[27], cilji[0], 2013),
            new Tretja.Nocitev(osebe[12], cilji[15], 2015),
            new Tretja.Nocitev(osebe[27], cilji[0], 2006),
            new Tretja.Nocitev(osebe[25], cilji[26], 2015),
            new Tretja.Nocitev(osebe[0], cilji[0], 2008),
            new Tretja.Nocitev(osebe[5], cilji[28], 2001),
            new Tretja.Nocitev(osebe[5], cilji[28], 2012),
            new Tretja.Nocitev(osebe[4], cilji[21], 2019),
            new Tretja.Nocitev(osebe[1], cilji[12], 2002),
            new Tretja.Nocitev(osebe[27], cilji[0], 2019),
            new Tretja.Nocitev(osebe[27], cilji[0], 2002),
            new Tretja.Nocitev(osebe[10], cilji[23], 2001),
            new Tretja.Nocitev(osebe[0], cilji[0], 2006),
            new Tretja.Nocitev(osebe[4], cilji[28], 2007),
            new Tretja.Nocitev(osebe[26], cilji[31], 2017),
            new Tretja.Nocitev(osebe[7], cilji[13], 2016),
            new Tretja.Nocitev(osebe[12], cilji[15], 2006),
            new Tretja.Nocitev(osebe[19], cilji[5], 2019),
            new Tretja.Nocitev(osebe[19], cilji[25], 2000),
            new Tretja.Nocitev(osebe[1], cilji[12], 2003),
            new Tretja.Nocitev(osebe[5], cilji[28], 2020),
            new Tretja.Nocitev(osebe[12], cilji[15], 2005),
            new Tretja.Nocitev(osebe[24], cilji[8], 2000),
            new Tretja.Nocitev(osebe[12], cilji[15], 2009),
            new Tretja.Nocitev(osebe[12], cilji[15], 2008),
            new Tretja.Nocitev(osebe[12], cilji[15], 2005),
            new Tretja.Nocitev(osebe[13], cilji[24], 2016),
            new Tretja.Nocitev(osebe[0], cilji[0], 2014),
            new Tretja.Nocitev(osebe[10], cilji[23], 2008),
            new Tretja.Nocitev(osebe[16], cilji[23], 2006),
            new Tretja.Nocitev(osebe[4], cilji[19], 2001),
            new Tretja.Nocitev(osebe[13], cilji[24], 2015),
            new Tretja.Nocitev(osebe[10], cilji[23], 2015),
            new Tretja.Nocitev(osebe[15], cilji[21], 2006),
            new Tretja.Nocitev(osebe[21], cilji[13], 2010),
            new Tretja.Nocitev(osebe[23], cilji[7], 2019),
            new Tretja.Nocitev(osebe[19], cilji[34], 2011),
            new Tretja.Nocitev(osebe[16], cilji[2], 2013),
            new Tretja.Nocitev(osebe[26], cilji[18], 2008),
            new Tretja.Nocitev(osebe[13], cilji[24], 2018),
            new Tretja.Nocitev(osebe[14], cilji[5], 2005),
            new Tretja.Nocitev(osebe[16], cilji[30], 2019),
            new Tretja.Nocitev(osebe[6], cilji[28], 2008),
            new Tretja.Nocitev(osebe[22], cilji[22], 2016),
            new Tretja.Nocitev(osebe[9], cilji[5], 2001),
            new Tretja.Nocitev(osebe[16], cilji[20], 2000),
            new Tretja.Nocitev(osebe[5], cilji[28], 2010),
            new Tretja.Nocitev(osebe[21], cilji[7], 2015),
            new Tretja.Nocitev(osebe[27], cilji[0], 2017),
            new Tretja.Nocitev(osebe[17], cilji[29], 2019),
            new Tretja.Nocitev(osebe[12], cilji[15], 2015),
            new Tretja.Nocitev(osebe[27], cilji[0], 2014),
            new Tretja.Nocitev(osebe[25], cilji[5], 2010),
            new Tretja.Nocitev(osebe[6], cilji[28], 2019),
            new Tretja.Nocitev(osebe[7], cilji[28], 2009),
            new Tretja.Nocitev(osebe[5], cilji[28], 2006),
            new Tretja.Nocitev(osebe[15], cilji[21], 2010),
            new Tretja.Nocitev(osebe[1], cilji[12], 2001),
            new Tretja.Nocitev(osebe[5], cilji[28], 2011),
            new Tretja.Nocitev(osebe[11], cilji[32], 2018),
            new Tretja.Nocitev(osebe[24], cilji[4], 2005),
            new Tretja.Nocitev(osebe[18], cilji[7], 2002),
            new Tretja.Nocitev(osebe[25], cilji[14], 2007),
            new Tretja.Nocitev(osebe[13], cilji[24], 2002),
            new Tretja.Nocitev(osebe[16], cilji[14], 2001),
            new Tretja.Nocitev(osebe[23], cilji[15], 2006),
            new Tretja.Nocitev(osebe[2], cilji[21], 2008),
            new Tretja.Nocitev(osebe[19], cilji[20], 2013),
            new Tretja.Nocitev(osebe[7], cilji[18], 2003),
            new Tretja.Nocitev(osebe[21], cilji[4], 2000),
            new Tretja.Nocitev(osebe[10], cilji[23], 2000),
            new Tretja.Nocitev(osebe[23], cilji[4], 2000),
            new Tretja.Nocitev(osebe[1], cilji[12], 2004),
            new Tretja.Nocitev(osebe[15], cilji[21], 2016),
            new Tretja.Nocitev(osebe[7], cilji[22], 2019),
            new Tretja.Nocitev(osebe[7], cilji[29], 2009),
            new Tretja.Nocitev(osebe[17], cilji[9], 2017),
            new Tretja.Nocitev(osebe[16], cilji[14], 2012),
            new Tretja.Nocitev(osebe[27], cilji[0], 2020),
            new Tretja.Nocitev(osebe[5], cilji[28], 2001),
            new Tretja.Nocitev(osebe[14], cilji[2], 2000),
            new Tretja.Nocitev(osebe[4], cilji[0], 2001),
            new Tretja.Nocitev(osebe[22], cilji[22], 2013),
            new Tretja.Nocitev(osebe[8], cilji[23], 2007),
            new Tretja.Nocitev(osebe[17], cilji[22], 2002),
            new Tretja.Nocitev(osebe[22], cilji[22], 2007),
            new Tretja.Nocitev(osebe[8], cilji[23], 2007),
            new Tretja.Nocitev(osebe[27], cilji[0], 2020),
            new Tretja.Nocitev(osebe[27], cilji[0], 2013),
            new Tretja.Nocitev(osebe[26], cilji[28], 2020),
            new Tretja.Nocitev(osebe[17], cilji[31], 2002),
            new Tretja.Nocitev(osebe[5], cilji[28], 2020),
            new Tretja.Nocitev(osebe[16], cilji[16], 2013),
            new Tretja.Nocitev(osebe[14], cilji[20], 2012),
            new Tretja.Nocitev(osebe[7], cilji[22], 2007),
            new Tretja.Nocitev(osebe[14], cilji[11], 2019),
            new Tretja.Nocitev(osebe[3], cilji[4], 2012),
            new Tretja.Nocitev(osebe[19], cilji[6], 2014),
            new Tretja.Nocitev(osebe[12], cilji[15], 2009),
            new Tretja.Nocitev(osebe[4], cilji[28], 2000),
            new Tretja.Nocitev(osebe[25], cilji[4], 2020),
            new Tretja.Nocitev(osebe[26], cilji[14], 2003),
            new Tretja.Nocitev(osebe[20], cilji[20], 2017),
            new Tretja.Nocitev(osebe[10], cilji[23], 2012),
            new Tretja.Nocitev(osebe[17], cilji[17], 2008),
            new Tretja.Nocitev(osebe[3], cilji[4], 2018),
            new Tretja.Nocitev(osebe[16], cilji[18], 2003),
            new Tretja.Nocitev(osebe[15], cilji[21], 2007),
            new Tretja.Nocitev(osebe[17], cilji[31], 2011),
            new Tretja.Nocitev(osebe[27], cilji[0], 2012),
            new Tretja.Nocitev(osebe[3], cilji[4], 2003),
            new Tretja.Nocitev(osebe[0], cilji[0], 2002),
            new Tretja.Nocitev(osebe[25], cilji[17], 2005),
            new Tretja.Nocitev(osebe[20], cilji[13], 2006),
            new Tretja.Nocitev(osebe[6], cilji[28], 2014),
            new Tretja.Nocitev(osebe[12], cilji[15], 2002),
            new Tretja.Nocitev(osebe[17], cilji[1], 2010),
            new Tretja.Nocitev(osebe[26], cilji[6], 2002),
            new Tretja.Nocitev(osebe[17], cilji[15], 2008),
            new Tretja.Nocitev(osebe[23], cilji[33], 2020),
            new Tretja.Nocitev(osebe[18], cilji[7], 2010),
            new Tretja.Nocitev(osebe[27], cilji[0], 2020),
            new Tretja.Nocitev(osebe[22], cilji[22], 2013),
            new Tretja.Nocitev(osebe[13], cilji[24], 2013),
            new Tretja.Nocitev(osebe[14], cilji[15], 2004),
            new Tretja.Nocitev(osebe[5], cilji[28], 2015),
            new Tretja.Nocitev(osebe[11], cilji[32], 2005),
            new Tretja.Nocitev(osebe[19], cilji[27], 2015),
            new Tretja.Nocitev(osebe[15], cilji[21], 2015),
            new Tretja.Nocitev(osebe[16], cilji[17], 2005),
            new Tretja.Nocitev(osebe[3], cilji[4], 2012),
            new Tretja.Nocitev(osebe[26], cilji[34], 2004),
            new Tretja.Nocitev(osebe[20], cilji[19], 2012),
            new Tretja.Nocitev(osebe[0], cilji[0], 2004),
            new Tretja.Nocitev(osebe[17], cilji[4], 2015),
            new Tretja.Nocitev(osebe[27], cilji[0], 2019),
            new Tretja.Nocitev(osebe[9], cilji[25], 2009),
            new Tretja.Nocitev(osebe[24], cilji[26], 2015),
            new Tretja.Nocitev(osebe[21], cilji[18], 2000),
            new Tretja.Nocitev(osebe[10], cilji[23], 2000),
            new Tretja.Nocitev(osebe[4], cilji[18], 2003),
            new Tretja.Nocitev(osebe[14], cilji[5], 2013),
            new Tretja.Nocitev(osebe[8], cilji[23], 2015),
            new Tretja.Nocitev(osebe[1], cilji[12], 2015),
            new Tretja.Nocitev(osebe[2], cilji[2], 2016),
            new Tretja.Nocitev(osebe[0], cilji[0], 2004),
            new Tretja.Nocitev(osebe[7], cilji[34], 2018),
            new Tretja.Nocitev(osebe[22], cilji[22], 2002),
            new Tretja.Nocitev(osebe[14], cilji[19], 2000),
            new Tretja.Nocitev(osebe[11], cilji[32], 2015),
            new Tretja.Nocitev(osebe[7], cilji[24], 2011),
            new Tretja.Nocitev(osebe[9], cilji[2], 2013),
            new Tretja.Nocitev(osebe[23], cilji[21], 2020),
            new Tretja.Nocitev(osebe[23], cilji[33], 2005),
            new Tretja.Nocitev(osebe[12], cilji[15], 2010),
            new Tretja.Nocitev(osebe[3], cilji[4], 2011),
            new Tretja.Nocitev(osebe[14], cilji[1], 2011),
            new Tretja.Nocitev(osebe[21], cilji[29], 2003),
            new Tretja.Nocitev(osebe[26], cilji[22], 2009),
            new Tretja.Nocitev(osebe[6], cilji[28], 2013),
            new Tretja.Nocitev(osebe[26], cilji[25], 2014),
            new Tretja.Nocitev(osebe[19], cilji[14], 2006),
            new Tretja.Nocitev(osebe[16], cilji[5], 2004),
            new Tretja.Nocitev(osebe[23], cilji[26], 2015),
            new Tretja.Nocitev(osebe[13], cilji[24], 2006),
            new Tretja.Nocitev(osebe[15], cilji[21], 2006),
            new Tretja.Nocitev(osebe[19], cilji[16], 2018),
            new Tretja.Nocitev(osebe[25], cilji[25], 2001),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
