
import java.util.*;

public class Test46 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr22 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr23 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr24 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr25 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr26 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr27 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr28 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr29 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr30 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr31 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr32 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr33 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr34 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr35 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr36 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr37 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr38 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr39 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr40 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr41 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr42 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr43 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr44 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr45 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr46 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr47 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr48 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr49 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr50 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr51 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr52 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr53 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr54 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr55 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr56 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr57 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr58 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr59 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr60 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr61 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr62 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr63 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr64 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr65 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr66 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr67 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr68 = new Tretja.Sprejemnik(odd03);

        odd06.oddaj('H');
        odd08.oddaj('t');
        odd15.oddaj('D');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd13.oddaj('R');
        System.out.println(spr15.koliko());
        odd11.oddaj('N');
        odd07.oddaj('k');
        odd01.oddaj('b');
        odd15.oddaj('Q');
        odd03.oddaj('u');
        odd10.oddaj('s');
        odd15.oddaj('Q');
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd06.oddaj('C');
        odd04.oddaj('a');
        odd15.oddaj('H');
        System.out.println(spr33.koliko());
        odd09.oddaj('R');
        System.out.println("<" + spr59.odZadnjic() + ">");
        odd08.oddaj('f');
        odd07.oddaj('J');
        odd15.oddaj('J');
        System.out.println(spr51.koliko());
        odd07.oddaj('R');
        odd05.oddaj('V');
        System.out.println("<" + spr52.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd08.oddaj('j');
        odd03.oddaj('A');
        odd02.oddaj('U');
        System.out.println(spr25.koliko());
        odd10.oddaj('n');
        odd00.oddaj('T');
        odd14.oddaj('K');
        odd03.oddaj('U');
        System.out.println("<" + spr62.odZadnjic() + ">");
        odd00.oddaj('N');
        System.out.println(spr44.koliko());
        odd04.oddaj('F');
        odd08.oddaj('z');
        System.out.println(spr61.koliko());
        odd08.oddaj('R');
        System.out.println(spr07.koliko());
        odd14.oddaj('q');
        odd13.oddaj('L');
        odd02.oddaj('O');
        odd01.oddaj('g');
        odd14.oddaj('i');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println(spr67.koliko());
        System.out.println(spr47.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr38.koliko());
        odd05.oddaj('h');
        odd00.oddaj('U');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd06.oddaj('f');
        System.out.println(spr21.koliko());
        odd04.oddaj('Y');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd03.oddaj('F');
        odd00.oddaj('K');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr45.koliko());
        odd02.oddaj('p');
        odd12.oddaj('S');
        System.out.println("<" + spr27.odZadnjic() + ">");
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd15.oddaj('l');
        odd08.oddaj('x');
        odd13.oddaj('V');
        odd12.oddaj('r');
        System.out.println(spr31.koliko());
        odd15.oddaj('A');
        System.out.println(spr30.koliko());
        odd09.oddaj('u');
        odd08.oddaj('d');
        odd00.oddaj('y');
        odd04.oddaj('Y');
        odd06.oddaj('M');
        odd04.oddaj('X');
        odd13.oddaj('m');
        System.out.println("<" + spr66.odZadnjic() + ">");
        System.out.println(spr51.koliko());
        odd05.oddaj('P');
        System.out.println(spr65.koliko());
        System.out.println(spr40.koliko());
        odd00.oddaj('N');
        odd08.oddaj('g');
        odd11.oddaj('u');
        System.out.println("<" + spr57.odZadnjic() + ">");
        odd11.oddaj('W');
        odd12.oddaj('n');
        System.out.println("<" + spr22.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr33.odZadnjic() + ">");
        odd06.oddaj('Q');
        System.out.println(spr03.koliko());
        odd13.oddaj('v');
        odd12.oddaj('K');
        odd14.oddaj('c');
        odd12.oddaj('K');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd15.oddaj('W');
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd14.oddaj('e');
        odd01.oddaj('x');
        odd03.oddaj('y');
        odd08.oddaj('t');
        odd05.oddaj('P');
        odd08.oddaj('J');
        odd04.oddaj('y');
        odd07.oddaj('N');
        odd01.oddaj('o');
        odd01.oddaj('I');
        odd04.oddaj('h');
        odd13.oddaj('c');
        odd10.oddaj('Z');
        System.out.println(spr45.koliko());
        odd01.oddaj('m');
        odd03.oddaj('K');
        odd02.oddaj('J');
        System.out.println(spr49.koliko());
        odd13.oddaj('c');
        System.out.println(spr07.koliko());
        odd07.oddaj('q');
        odd12.oddaj('Q');
        System.out.println("<" + spr32.odZadnjic() + ">");
        odd13.oddaj('C');
        odd10.oddaj('O');
        odd13.oddaj('o');
        odd10.oddaj('Q');
        odd01.oddaj('T');
        System.out.println("<" + spr53.odZadnjic() + ">");
        System.out.println(spr27.koliko());
        odd13.oddaj('o');
        System.out.println(spr37.koliko());
        System.out.println(spr02.koliko());
        System.out.println("<" + spr52.odZadnjic() + ">");
        odd03.oddaj('u');
        odd10.oddaj('N');
        System.out.println(spr56.koliko());
        odd09.oddaj('t');
        odd06.oddaj('q');
        odd00.oddaj('E');
        System.out.println(spr25.koliko());
        odd10.oddaj('m');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd13.oddaj('V');
        odd10.oddaj('T');
        odd11.oddaj('v');
        System.out.println(spr17.koliko());
        odd08.oddaj('H');
        System.out.println(spr10.koliko());
        odd13.oddaj('W');
        odd15.oddaj('H');
        System.out.println(spr58.koliko());
        odd12.oddaj('x');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd04.oddaj('G');
        odd03.oddaj('B');
        System.out.println(spr19.koliko());
        odd06.oddaj('C');
        odd15.oddaj('f');
        odd13.oddaj('z');
        odd09.oddaj('n');
        odd12.oddaj('p');
        odd10.oddaj('b');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd03.oddaj('Y');
        odd13.oddaj('H');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('K');
        odd05.oddaj('d');
        System.out.println(spr55.koliko());
        System.out.println(spr65.koliko());
        System.out.println(spr61.koliko());
        System.out.println("<" + spr47.odZadnjic() + ">");
        System.out.println(spr66.koliko());
        odd14.oddaj('K');
        odd01.oddaj('J');
        odd15.oddaj('G');
        System.out.println(spr45.koliko());
        odd04.oddaj('m');
        odd06.oddaj('t');
        odd14.oddaj('V');
        odd15.oddaj('X');
        System.out.println("<" + spr68.odZadnjic() + ">");
        odd04.oddaj('W');
        System.out.println(spr19.koliko());
        odd13.oddaj('z');
        odd08.oddaj('k');
        odd01.oddaj('A');
        odd06.oddaj('Q');
        odd10.oddaj('y');
        odd11.oddaj('v');
        odd08.oddaj('P');
        odd14.oddaj('T');
        System.out.println(spr46.koliko());
        odd15.oddaj('k');
        odd03.oddaj('K');
        odd08.oddaj('I');
        System.out.println("<" + spr45.odZadnjic() + ">");
        odd10.oddaj('W');
        odd15.oddaj('K');
        odd00.oddaj('d');
        System.out.println("<" + spr33.odZadnjic() + ">");
        odd15.oddaj('z');
        odd05.oddaj('I');
        odd03.oddaj('t');
        odd06.oddaj('E');
        odd02.oddaj('R');
        odd09.oddaj('p');
        odd14.oddaj('S');
        odd06.oddaj('J');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd02.oddaj('l');
        System.out.println(spr07.koliko());
        odd10.oddaj('v');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('C');
        odd00.oddaj('s');
        odd10.oddaj('l');
        odd14.oddaj('X');
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd06.oddaj('p');
        odd14.oddaj('z');
        odd02.oddaj('F');
        odd13.oddaj('I');
        odd15.oddaj('n');
        odd13.oddaj('v');
        odd13.oddaj('x');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd15.oddaj('G');
        odd06.oddaj('u');
        odd05.oddaj('N');
        odd02.oddaj('k');
        odd08.oddaj('b');
        odd11.oddaj('a');
        odd12.oddaj('g');
        odd12.oddaj('L');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd11.oddaj('R');
        odd11.oddaj('m');
        System.out.println(spr60.koliko());
        System.out.println("<" + spr50.odZadnjic() + ">");
        odd00.oddaj('K');
        odd13.oddaj('T');
        odd02.oddaj('X');
        odd04.oddaj('Q');
        odd02.oddaj('Y');
        odd07.oddaj('I');
        odd04.oddaj('V');
        odd00.oddaj('u');
        odd01.oddaj('Z');
        System.out.println(spr30.koliko());
        odd13.oddaj('R');
        odd15.oddaj('l');
        System.out.println(spr07.koliko());
        odd02.oddaj('E');
        System.out.println(spr15.koliko());
        odd00.oddaj('g');
        odd03.oddaj('I');
        odd03.oddaj('u');
        System.out.println(spr63.koliko());
        System.out.println(spr57.koliko());
        odd00.oddaj('F');
        System.out.println("<" + spr22.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        odd15.oddaj('l');
        odd06.oddaj('S');
        odd00.oddaj('A');
        odd07.oddaj('R');
        odd10.oddaj('O');
        System.out.println(spr51.koliko());
        odd15.oddaj('n');
        odd14.oddaj('L');
        odd09.oddaj('R');
        odd09.oddaj('y');
        odd12.oddaj('a');
        System.out.println(spr40.koliko());
        odd03.oddaj('r');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd02.oddaj('y');
        System.out.println("<" + spr56.odZadnjic() + ">");
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd02.oddaj('G');
        System.out.println(spr62.koliko());
        odd04.oddaj('J');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd10.oddaj('w');
        System.out.println(spr18.koliko());
        System.out.println(spr11.koliko());
        odd04.oddaj('e');
        odd04.oddaj('A');
        System.out.println(spr56.koliko());
        odd10.oddaj('u');
        System.out.println(spr22.koliko());
        odd12.oddaj('A');
        odd01.oddaj('y');
        odd15.oddaj('D');
        odd15.oddaj('D');
        odd05.oddaj('R');
        odd14.oddaj('y');
        System.out.println(spr09.koliko());
        odd15.oddaj('o');
        System.out.println(spr03.koliko());
        odd00.oddaj('q');
        odd00.oddaj('Y');
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd13.oddaj('O');
        System.out.println("<" + spr34.odZadnjic() + ">");
        odd02.oddaj('P');
        odd03.oddaj('F');
        odd08.oddaj('X');
        odd04.oddaj('b');
        odd14.oddaj('I');
        odd03.oddaj('v');
        odd10.oddaj('t');
        odd14.oddaj('i');
        odd02.oddaj('C');
        odd07.oddaj('N');
        System.out.println(spr32.koliko());
        odd06.oddaj('R');
        odd07.oddaj('A');
        odd06.oddaj('W');
        System.out.println(spr68.koliko());
        System.out.println("<" + spr64.odZadnjic() + ">");
        odd14.oddaj('b');
        odd00.oddaj('o');
        odd08.oddaj('y');
        odd04.oddaj('i');
        odd12.oddaj('y');
        System.out.println("<" + spr53.odZadnjic() + ">");
        odd13.oddaj('R');
        odd13.oddaj('K');
        System.out.println(spr19.koliko());
        odd15.oddaj('C');
        System.out.println("<" + spr34.odZadnjic() + ">");
        odd02.oddaj('G');
        System.out.println(spr45.koliko());
        odd14.oddaj('e');
        odd06.oddaj('o');
        odd04.oddaj('b');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr36.odZadnjic() + ">");
        odd02.oddaj('O');
        odd00.oddaj('J');
        odd14.oddaj('T');
        System.out.println("<" + spr67.odZadnjic() + ">");
        System.out.println(spr38.koliko());
        odd04.oddaj('W');
        odd09.oddaj('n');
        odd11.oddaj('g');
        System.out.println(spr58.koliko());
        System.out.println("<" + spr32.odZadnjic() + ">");
        odd14.oddaj('a');
        System.out.println(spr60.koliko());
        odd13.oddaj('J');
        odd05.oddaj('v');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr25.koliko());
        odd07.oddaj('B');
        System.out.println(spr59.koliko());
        odd09.oddaj('B');
        odd13.oddaj('j');
        odd11.oddaj('t');
        odd14.oddaj('j');
        odd01.oddaj('L');
        System.out.println(spr20.koliko());
        System.out.println("<" + spr30.odZadnjic() + ">");
        System.out.println(spr66.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd13.oddaj('X');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd05.oddaj('F');
        odd13.oddaj('I');
        System.out.println(spr23.koliko());
        odd09.oddaj('R');
        System.out.println(spr02.koliko());
        odd06.oddaj('y');
        odd05.oddaj('x');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd05.oddaj('E');
        System.out.println("<" + spr64.odZadnjic() + ">");
        odd02.oddaj('K');
        odd05.oddaj('F');
        odd15.oddaj('Y');
        odd05.oddaj('w');
        odd01.oddaj('x');
        odd00.oddaj('f');
        odd07.oddaj('T');
        odd06.oddaj('B');
        odd00.oddaj('h');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd02.oddaj('a');
        odd01.oddaj('Z');
        odd13.oddaj('M');
        System.out.println("<" + spr26.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('q');
        System.out.println(spr21.koliko());
        odd03.oddaj('D');
        odd15.oddaj('P');
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd15.oddaj('z');
        odd14.oddaj('S');
        odd02.oddaj('t');
        System.out.println("<" + spr44.odZadnjic() + ">");
        odd00.oddaj('f');
        System.out.println(spr57.koliko());
        System.out.println("<" + spr33.odZadnjic() + ">");
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd11.oddaj('m');
        odd06.oddaj('o');
        odd03.oddaj('V');
        odd05.oddaj('Z');
        System.out.println("<" + spr54.odZadnjic() + ">");
        odd10.oddaj('q');
        odd11.oddaj('S');
        odd02.oddaj('K');
        odd14.oddaj('H');
        odd15.oddaj('a');
        odd02.oddaj('Z');
        odd02.oddaj('S');
        odd05.oddaj('J');
        System.out.println(spr02.koliko());
        odd04.oddaj('M');
        System.out.println("<" + spr23.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        odd10.oddaj('p');
        odd03.oddaj('m');
        System.out.println("<" + spr68.odZadnjic() + ">");
        odd00.oddaj('U');
        odd10.oddaj('d');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd11.oddaj('L');
        System.out.println(spr20.koliko());
        odd12.oddaj('O');
        odd14.oddaj('l');
        odd14.oddaj('w');
        odd11.oddaj('O');
        System.out.println("<" + spr65.odZadnjic() + ">");
        odd07.oddaj('F');
        odd03.oddaj('H');
        odd10.oddaj('y');
        odd07.oddaj('k');
        odd11.oddaj('X');
        System.out.println("<" + spr40.odZadnjic() + ">");
        odd01.oddaj('A');
        odd14.oddaj('p');
        odd00.oddaj('H');
        System.out.println(spr03.koliko());
        odd13.oddaj('k');
        System.out.println("<" + spr36.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd13.oddaj('q');
        System.out.println("<" + spr47.odZadnjic() + ">");
        System.out.println(spr64.koliko());
        odd15.oddaj('u');
        odd03.oddaj('J');
        odd03.oddaj('b');
        System.out.println("<" + spr33.odZadnjic() + ">");
        System.out.println("<" + spr51.odZadnjic() + ">");
        odd00.oddaj('s');
        odd06.oddaj('y');
        System.out.println(spr03.koliko());
        odd10.oddaj('U');
        odd10.oddaj('l');
        odd09.oddaj('r');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd12.oddaj('I');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd07.oddaj('f');
        System.out.println("<" + spr67.odZadnjic() + ">");
        odd03.oddaj('o');
        odd01.oddaj('e');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd02.oddaj('o');
        odd11.oddaj('J');
        odd00.oddaj('j');
        odd04.oddaj('E');
        odd15.oddaj('N');
        System.out.println("<" + spr47.odZadnjic() + ">");
        System.out.println("<" + spr67.odZadnjic() + ">");
        odd07.oddaj('e');
        odd15.oddaj('R');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd02.oddaj('V');
        odd05.oddaj('R');
        odd13.oddaj('o');
        odd09.oddaj('w');
        odd00.oddaj('h');
        odd09.oddaj('i');
        odd13.oddaj('A');
        odd10.oddaj('F');
        odd00.oddaj('P');
        odd06.oddaj('X');
        odd04.oddaj('M');
        System.out.println(spr17.koliko());
        odd00.oddaj('M');
        odd06.oddaj('H');
        odd05.oddaj('W');
        odd12.oddaj('z');
        odd15.oddaj('L');
        odd11.oddaj('o');
        odd14.oddaj('A');
        odd08.oddaj('w');
        odd09.oddaj('b');
        System.out.println(spr35.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd13.oddaj('h');
        odd11.oddaj('a');
        System.out.println(spr26.koliko());
        odd12.oddaj('e');
        odd14.oddaj('h');
        odd07.oddaj('c');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd11.oddaj('m');
        odd10.oddaj('e');
        odd07.oddaj('Z');
        odd15.oddaj('q');
        odd14.oddaj('t');
        System.out.println(spr24.koliko());
        odd03.oddaj('z');
        System.out.println("<" + spr46.odZadnjic() + ">");
        System.out.println(spr44.koliko());
        odd11.oddaj('N');
        odd08.oddaj('v');
        odd07.oddaj('k');
        odd08.oddaj('X');
        odd06.oddaj('t');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd14.oddaj('M');
        odd05.oddaj('a');
        odd09.oddaj('Q');
        odd12.oddaj('h');
        odd03.oddaj('T');
        System.out.println(spr25.koliko());
        System.out.println("<" + spr46.odZadnjic() + ">");
        odd02.oddaj('i');
        odd13.oddaj('K');
        odd08.oddaj('v');
        odd06.oddaj('u');
        odd06.oddaj('J');
        odd04.oddaj('S');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd15.oddaj('l');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd14.oddaj('N');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('B');
        odd03.oddaj('o');
        odd14.oddaj('K');
        System.out.println(spr33.koliko());
        odd03.oddaj('M');
        odd14.oddaj('y');
        System.out.println(spr58.koliko());
        odd09.oddaj('A');
        odd13.oddaj('m');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd13.oddaj('f');
        odd12.oddaj('y');
        odd09.oddaj('z');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd14.oddaj('b');
        System.out.println(spr61.koliko());
        odd07.oddaj('k');
        System.out.println(spr66.koliko());
        odd01.oddaj('d');
        odd03.oddaj('Y');
        System.out.println("<" + spr49.odZadnjic() + ">");
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd07.oddaj('f');
        odd13.oddaj('S');
        odd11.oddaj('C');
        odd08.oddaj('D');
        odd14.oddaj('j');
        odd03.oddaj('p');
        odd08.oddaj('b');
        odd13.oddaj('s');
        odd00.oddaj('C');
        System.out.println("<" + spr47.odZadnjic() + ">");
        odd03.oddaj('Q');
        odd08.oddaj('c');
        odd02.oddaj('l');
        System.out.println(spr26.koliko());
        odd14.oddaj('k');
        odd05.oddaj('a');
        System.out.println(spr63.koliko());
        odd01.oddaj('L');
        odd09.oddaj('q');
        odd00.oddaj('h');
        odd00.oddaj('t');
        odd12.oddaj('q');
        System.out.println(spr05.koliko());
        odd01.oddaj('C');
        odd14.oddaj('p');
        odd06.oddaj('c');
        odd08.oddaj('n');
        System.out.println("<" + spr66.odZadnjic() + ">");
        odd09.oddaj('r');
        odd11.oddaj('p');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd11.oddaj('D');
        odd08.oddaj('h');
        odd01.oddaj('f');
        odd00.oddaj('S');
        odd05.oddaj('q');
        System.out.println(spr50.koliko());
        System.out.println(spr54.koliko());
        odd00.oddaj('X');
        System.out.println("<" + spr51.odZadnjic() + ">");
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd10.oddaj('K');
        System.out.println(spr49.koliko());
        odd08.oddaj('I');
        odd06.oddaj('z');
        odd13.oddaj('S');
        odd11.oddaj('P');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd06.oddaj('S');
        odd10.oddaj('O');
        System.out.println(spr10.koliko());
        odd05.oddaj('P');
        System.out.println("<" + spr67.odZadnjic() + ">");
        odd00.oddaj('D');
        odd15.oddaj('y');
        System.out.println(spr16.koliko());
        System.out.println(spr49.koliko());
        odd05.oddaj('S');
        System.out.println("<" + spr59.odZadnjic() + ">");
        odd03.oddaj('O');
        odd15.oddaj('A');
        odd00.oddaj('H');
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd06.oddaj('E');
        System.out.println(spr01.koliko());
        odd03.oddaj('A');
        odd11.oddaj('G');
        System.out.println("<" + spr64.odZadnjic() + ">");
        System.out.println(spr57.koliko());
        odd10.oddaj('T');
        odd11.oddaj('c');
        System.out.println(spr65.koliko());
        odd04.oddaj('c');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd04.oddaj('c');
        odd04.oddaj('T');
        odd05.oddaj('r');
        System.out.println("<" + spr58.odZadnjic() + ">");
        System.out.println("<" + spr53.odZadnjic() + ">");
        odd15.oddaj('y');
        odd00.oddaj('Z');
        odd12.oddaj('x');
        odd08.oddaj('W');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd07.oddaj('O');
        odd12.oddaj('d');
        odd04.oddaj('E');
        odd07.oddaj('R');
        System.out.println("<" + spr43.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd15.oddaj('D');
        odd08.oddaj('E');
        odd06.oddaj('F');
        odd01.oddaj('V');
        odd04.oddaj('v');
        odd10.oddaj('S');
        odd12.oddaj('K');
        odd14.oddaj('O');
        odd10.oddaj('p');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd15.oddaj('o');
        odd01.oddaj('h');
        odd13.oddaj('f');
        odd02.oddaj('j');
        odd05.oddaj('V');
        odd08.oddaj('F');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd14.oddaj('X');
        odd03.oddaj('K');
        odd11.oddaj('n');
        odd15.oddaj('m');
        odd10.oddaj('J');
        odd08.oddaj('U');
        odd01.oddaj('s');
        odd03.oddaj('i');
        odd01.oddaj('j');
        odd08.oddaj('V');
        System.out.println(spr20.koliko());
        System.out.println(spr48.koliko());
        odd04.oddaj('z');
        odd09.oddaj('l');
        odd12.oddaj('I');
        odd12.oddaj('Q');
        odd13.oddaj('k');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr33.koliko());
        odd04.oddaj('d');
        System.out.println(spr61.koliko());
        odd04.oddaj('G');
        odd06.oddaj('Z');
        System.out.println("<" + spr49.odZadnjic() + ">");
        System.out.println("<" + spr52.odZadnjic() + ">");
        odd06.oddaj('e');
        odd11.oddaj('y');
        odd13.oddaj('B');
        System.out.println(spr41.koliko());
        odd04.oddaj('S');
        odd01.oddaj('a');
        odd03.oddaj('j');
        odd13.oddaj('Y');
        odd06.oddaj('F');
        odd02.oddaj('B');
        odd14.oddaj('B');
        odd03.oddaj('b');
        odd02.oddaj('Y');
        odd02.oddaj('p');
        System.out.println(spr35.koliko());
        odd14.oddaj('K');
        odd04.oddaj('q');
        odd13.oddaj('v');
        System.out.println(spr62.koliko());
        odd15.oddaj('i');
        odd06.oddaj('l');
        System.out.println(spr00.koliko());
        odd06.oddaj('W');
        odd15.oddaj('F');
        System.out.println("<" + spr51.odZadnjic() + ">");
        odd03.oddaj('Q');
        odd04.oddaj('c');
        odd02.oddaj('f');
        odd08.oddaj('U');
        odd06.oddaj('N');
        odd08.oddaj('O');
        odd00.oddaj('M');
        odd10.oddaj('K');
        odd04.oddaj('K');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd08.oddaj('f');
        System.out.println(spr48.koliko());
        odd15.oddaj('f');
        System.out.println(spr58.koliko());
        System.out.println(spr39.koliko());
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd12.oddaj('c');
        System.out.println(spr49.koliko());
        System.out.println(spr24.koliko());
        odd05.oddaj('A');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd03.oddaj('l');
        System.out.println("<" + spr43.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('s');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd01.oddaj('N');
        odd00.oddaj('v');
        odd11.oddaj('u');
        odd00.oddaj('W');
        odd11.oddaj('m');
        System.out.println("<" + spr46.odZadnjic() + ">");
        System.out.println("<" + spr36.odZadnjic() + ">");
        odd07.oddaj('A');
        System.out.println(spr11.koliko());
        odd05.oddaj('v');
        odd01.oddaj('W');
        odd10.oddaj('e');
        odd13.oddaj('B');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd13.oddaj('G');
        odd14.oddaj('r');
    }
}
