
import java.util.*;

public class Test50 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd16 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd17 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd18 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr22 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr23 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr24 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr25 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr26 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr27 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr28 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr29 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr30 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr31 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr32 = new Tretja.Sprejemnik(odd17);
        Tretja.Sprejemnik spr33 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr34 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr35 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr36 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr37 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr38 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr39 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr40 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr41 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr42 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr43 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr44 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr45 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr46 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr47 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr48 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr49 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr50 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr51 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr52 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr53 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr54 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr55 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr56 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr57 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr58 = new Tretja.Sprejemnik(odd17);
        Tretja.Sprejemnik spr59 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr60 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr61 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr62 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr63 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr64 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr65 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr66 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr67 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr68 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr69 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr70 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr71 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr72 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr73 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr74 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr75 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr76 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr77 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr78 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr79 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr80 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr81 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr82 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr83 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr84 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr85 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr86 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr87 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr88 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr89 = new Tretja.Sprejemnik(odd10);

        odd12.oddaj('y');
        odd15.oddaj('H');
        odd13.oddaj('q');
        System.out.println("<" + spr79.odZadnjic() + ">");
        odd07.oddaj('s');
        odd01.oddaj('m');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd09.oddaj('m');
        odd14.oddaj('U');
        odd14.oddaj('u');
        odd04.oddaj('F');
        odd08.oddaj('I');
        odd08.oddaj('P');
        odd15.oddaj('j');
        odd08.oddaj('u');
        odd08.oddaj('c');
        odd00.oddaj('R');
        odd06.oddaj('w');
        odd14.oddaj('e');
        odd02.oddaj('c');
        odd11.oddaj('c');
        odd03.oddaj('j');
        odd08.oddaj('v');
        odd02.oddaj('u');
        odd17.oddaj('t');
        System.out.println(spr18.koliko());
        odd12.oddaj('H');
        odd12.oddaj('J');
        odd06.oddaj('i');
        odd18.oddaj('T');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr88.odZadnjic() + ">");
        odd05.oddaj('b');
        odd12.oddaj('U');
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd10.oddaj('a');
        odd09.oddaj('f');
        System.out.println("<" + spr87.odZadnjic() + ">");
        odd15.oddaj('e');
        odd16.oddaj('B');
        odd14.oddaj('A');
        odd00.oddaj('v');
        System.out.println(spr46.koliko());
        odd06.oddaj('N');
        odd13.oddaj('S');
        System.out.println("<" + spr89.odZadnjic() + ">");
        odd06.oddaj('p');
        odd18.oddaj('l');
        odd00.oddaj('l');
        System.out.println("<" + spr36.odZadnjic() + ">");
        odd07.oddaj('K');
        odd07.oddaj('c');
        System.out.println("<" + spr45.odZadnjic() + ">");
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd15.oddaj('J');
        odd04.oddaj('Z');
        odd07.oddaj('h');
        odd12.oddaj('U');
        System.out.println(spr49.koliko());
        odd03.oddaj('S');
        odd09.oddaj('u');
        odd05.oddaj('t');
        System.out.println(spr36.koliko());
        odd06.oddaj('V');
        odd10.oddaj('g');
        odd07.oddaj('J');
        odd12.oddaj('T');
        odd00.oddaj('K');
        odd16.oddaj('c');
        odd12.oddaj('E');
        odd17.oddaj('J');
        odd00.oddaj('U');
        odd03.oddaj('e');
        odd16.oddaj('G');
        odd03.oddaj('P');
        odd10.oddaj('x');
        System.out.println("<" + spr51.odZadnjic() + ">");
        odd09.oddaj('b');
        odd07.oddaj('h');
        odd00.oddaj('R');
        odd05.oddaj('y');
        odd02.oddaj('N');
        odd10.oddaj('d');
        System.out.println(spr43.koliko());
        odd16.oddaj('C');
        odd10.oddaj('W');
        odd02.oddaj('L');
        System.out.println("<" + spr85.odZadnjic() + ">");
        odd15.oddaj('T');
        odd05.oddaj('v');
        System.out.println("<" + spr54.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd17.oddaj('v');
        odd05.oddaj('F');
        odd13.oddaj('w');
        odd00.oddaj('p');
        odd15.oddaj('A');
        odd11.oddaj('n');
        odd03.oddaj('a');
        odd07.oddaj('F');
        odd18.oddaj('M');
        odd05.oddaj('N');
        odd11.oddaj('p');
        odd08.oddaj('g');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd01.oddaj('z');
        odd17.oddaj('Y');
        odd02.oddaj('u');
        odd09.oddaj('P');
        System.out.println("<" + spr71.odZadnjic() + ">");
        odd15.oddaj('V');
        odd11.oddaj('g');
        odd02.oddaj('r');
        odd14.oddaj('T');
        System.out.println(spr40.koliko());
        odd15.oddaj('Y');
        System.out.println(spr45.koliko());
        System.out.println(spr41.koliko());
        odd09.oddaj('o');
        odd00.oddaj('y');
        odd07.oddaj('r');
        odd18.oddaj('N');
        odd12.oddaj('Z');
        odd09.oddaj('R');
        odd07.oddaj('f');
        odd04.oddaj('I');
        System.out.println(spr40.koliko());
        odd18.oddaj('k');
        odd18.oddaj('s');
        odd00.oddaj('s');
        odd01.oddaj('f');
        odd03.oddaj('g');
        odd12.oddaj('u');
        odd09.oddaj('q');
        odd01.oddaj('v');
        odd03.oddaj('G');
        odd14.oddaj('z');
        odd14.oddaj('i');
        System.out.println(spr16.koliko());
        odd13.oddaj('e');
        odd01.oddaj('j');
        odd09.oddaj('J');
        System.out.println("<" + spr58.odZadnjic() + ">");
        odd07.oddaj('c');
        odd04.oddaj('Q');
        odd18.oddaj('h');
        odd10.oddaj('t');
        odd10.oddaj('J');
        System.out.println("<" + spr30.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd12.oddaj('F');
        odd18.oddaj('C');
        odd04.oddaj('U');
        odd13.oddaj('M');
        odd05.oddaj('O');
        odd18.oddaj('z');
        System.out.println(spr45.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd09.oddaj('Q');
        odd04.oddaj('t');
        odd00.oddaj('w');
        odd17.oddaj('p');
        odd10.oddaj('Z');
        odd10.oddaj('l');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd05.oddaj('k');
        odd11.oddaj('a');
        odd05.oddaj('d');
        odd05.oddaj('B');
        odd04.oddaj('L');
        odd18.oddaj('L');
        odd01.oddaj('q');
        odd11.oddaj('P');
        odd09.oddaj('k');
        odd01.oddaj('F');
        odd05.oddaj('Y');
        odd10.oddaj('p');
        odd17.oddaj('c');
        odd14.oddaj('A');
        odd16.oddaj('p');
        odd08.oddaj('V');
        System.out.println(spr62.koliko());
        System.out.println("<" + spr61.odZadnjic() + ">");
        odd00.oddaj('t');
        odd01.oddaj('W');
        odd08.oddaj('m');
        odd17.oddaj('F');
        odd04.oddaj('S');
        odd02.oddaj('L');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd15.oddaj('J');
        odd03.oddaj('l');
        odd04.oddaj('O');
        odd16.oddaj('Y');
        odd14.oddaj('s');
        odd07.oddaj('I');
        odd08.oddaj('N');
        odd08.oddaj('s');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('M');
        odd11.oddaj('b');
        odd04.oddaj('S');
        odd17.oddaj('d');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr29.odZadnjic() + ">");
        System.out.println("<" + spr33.odZadnjic() + ">");
        System.out.println("<" + spr81.odZadnjic() + ">");
        odd09.oddaj('G');
        odd14.oddaj('N');
        System.out.println(spr25.koliko());
        odd03.oddaj('d');
        odd01.oddaj('L');
        odd01.oddaj('o');
        odd09.oddaj('y');
        odd17.oddaj('T');
        System.out.println(spr08.koliko());
        odd11.oddaj('H');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd11.oddaj('l');
        odd09.oddaj('L');
        System.out.println("<" + spr42.odZadnjic() + ">");
        odd08.oddaj('n');
        odd04.oddaj('C');
        odd05.oddaj('f');
        odd16.oddaj('U');
        odd13.oddaj('z');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd18.oddaj('N');
        System.out.println("<" + spr66.odZadnjic() + ">");
        odd16.oddaj('L');
        System.out.println(spr58.koliko());
        odd16.oddaj('k');
        odd05.oddaj('W');
        odd03.oddaj('T');
        odd18.oddaj('P');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd06.oddaj('F');
        odd14.oddaj('d');
        odd18.oddaj('y');
        System.out.println(spr34.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('e');
        System.out.println("<" + spr49.odZadnjic() + ">");
        odd17.oddaj('Z');
        System.out.println(spr76.koliko());
        odd12.oddaj('Q');
        odd02.oddaj('q');
        odd10.oddaj('l');
        odd14.oddaj('E');
        odd07.oddaj('S');
        odd09.oddaj('e');
        System.out.println("<" + spr53.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('s');
        odd13.oddaj('Q');
        odd13.oddaj('Q');
        odd00.oddaj('R');
        odd00.oddaj('z');
        odd02.oddaj('Y');
        System.out.println(spr75.koliko());
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd08.oddaj('S');
        odd07.oddaj('o');
        odd03.oddaj('y');
        odd06.oddaj('u');
        odd02.oddaj('a');
        System.out.println("<" + spr84.odZadnjic() + ">");
        odd11.oddaj('z');
        odd01.oddaj('G');
        odd08.oddaj('e');
        odd02.oddaj('x');
        odd17.oddaj('Z');
        System.out.println(spr64.koliko());
        odd12.oddaj('F');
        odd05.oddaj('m');
        System.out.println("<" + spr70.odZadnjic() + ">");
        odd11.oddaj('v');
        System.out.println("<" + spr36.odZadnjic() + ">");
        odd07.oddaj('o');
        odd08.oddaj('w');
        odd16.oddaj('W');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd08.oddaj('V');
        odd08.oddaj('q');
        System.out.println(spr63.koliko());
        odd07.oddaj('d');
        odd18.oddaj('P');
        System.out.println(spr28.koliko());
        System.out.println("<" + spr50.odZadnjic() + ">");
        odd03.oddaj('C');
        System.out.println(spr22.koliko());
        System.out.println(spr60.koliko());
        odd07.oddaj('D');
        System.out.println("<" + spr41.odZadnjic() + ">");
        System.out.println(spr34.koliko());
        odd12.oddaj('X');
        odd13.oddaj('P');
        odd04.oddaj('N');
        odd00.oddaj('q');
        odd02.oddaj('Y');
        odd11.oddaj('J');
        odd05.oddaj('H');
        odd14.oddaj('a');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('k');
        odd17.oddaj('D');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println(spr75.koliko());
        odd00.oddaj('x');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd05.oddaj('M');
        System.out.println(spr21.koliko());
        odd06.oddaj('p');
        odd01.oddaj('B');
        odd11.oddaj('V');
        System.out.println(spr69.koliko());
        odd18.oddaj('q');
        odd18.oddaj('F');
        System.out.println("<" + spr86.odZadnjic() + ">");
        System.out.println(spr46.koliko());
        odd12.oddaj('O');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd14.oddaj('O');
        System.out.println(spr36.koliko());
        odd10.oddaj('Y');
        odd03.oddaj('c');
        odd11.oddaj('A');
        odd06.oddaj('L');
        odd17.oddaj('A');
        odd11.oddaj('V');
        System.out.println(spr65.koliko());
        odd10.oddaj('g');
        odd10.oddaj('w');
        odd11.oddaj('Z');
        odd00.oddaj('q');
        odd04.oddaj('Z');
        odd11.oddaj('V');
        odd08.oddaj('W');
        odd03.oddaj('B');
        odd04.oddaj('G');
        odd02.oddaj('s');
        odd02.oddaj('x');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd14.oddaj('C');
        odd16.oddaj('v');
        odd13.oddaj('o');
        odd02.oddaj('m');
        odd09.oddaj('G');
        System.out.println("<" + spr70.odZadnjic() + ">");
        odd01.oddaj('a');
        odd03.oddaj('U');
        odd07.oddaj('t');
        odd03.oddaj('Y');
        odd05.oddaj('K');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        System.out.println(spr87.koliko());
        odd00.oddaj('O');
        odd09.oddaj('k');
        System.out.println(spr53.koliko());
        odd11.oddaj('b');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd15.oddaj('e');
        odd00.oddaj('r');
        odd09.oddaj('K');
        odd10.oddaj('J');
        odd13.oddaj('B');
        odd02.oddaj('K');
        odd10.oddaj('v');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println(spr48.koliko());
        odd10.oddaj('f');
        odd10.oddaj('u');
        odd07.oddaj('j');
        odd01.oddaj('J');
        odd17.oddaj('w');
        odd05.oddaj('f');
        odd13.oddaj('V');
        odd01.oddaj('Q');
        System.out.println(spr06.koliko());
        odd18.oddaj('J');
        odd14.oddaj('f');
        System.out.println(spr38.koliko());
        odd16.oddaj('x');
        odd14.oddaj('e');
        System.out.println(spr61.koliko());
        odd03.oddaj('L');
        odd11.oddaj('m');
        odd04.oddaj('Z');
        System.out.println(spr57.koliko());
        System.out.println("<" + spr47.odZadnjic() + ">");
        odd04.oddaj('T');
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd06.oddaj('w');
        odd10.oddaj('r');
        odd09.oddaj('z');
        odd13.oddaj('Z');
        System.out.println(spr86.koliko());
        System.out.println(spr17.koliko());
        odd04.oddaj('F');
        System.out.println("<" + spr70.odZadnjic() + ">");
        odd10.oddaj('s');
        System.out.println("<" + spr54.odZadnjic() + ">");
        odd15.oddaj('F');
        odd12.oddaj('Q');
        System.out.println("<" + spr77.odZadnjic() + ">");
        odd15.oddaj('F');
        odd17.oddaj('w');
        odd07.oddaj('Z');
        System.out.println("<" + spr84.odZadnjic() + ">");
        odd06.oddaj('k');
        odd11.oddaj('E');
        odd10.oddaj('w');
        odd03.oddaj('T');
        odd03.oddaj('e');
        odd09.oddaj('Y');
        odd15.oddaj('h');
        odd13.oddaj('L');
        odd16.oddaj('M');
        odd04.oddaj('W');
        odd04.oddaj('S');
        odd12.oddaj('U');
        System.out.println(spr60.koliko());
        odd15.oddaj('B');
        odd00.oddaj('s');
        odd05.oddaj('S');
        odd13.oddaj('P');
        odd06.oddaj('E');
        System.out.println("<" + spr44.odZadnjic() + ">");
        odd02.oddaj('n');
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd12.oddaj('m');
        odd00.oddaj('G');
        odd00.oddaj('G');
        odd04.oddaj('i');
        System.out.println(spr05.koliko());
        odd12.oddaj('e');
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd05.oddaj('L');
        odd18.oddaj('E');
        odd01.oddaj('O');
        odd04.oddaj('C');
        odd10.oddaj('N');
        System.out.println(spr46.koliko());
        odd05.oddaj('q');
        odd02.oddaj('q');
        odd01.oddaj('b');
        odd07.oddaj('Y');
        odd03.oddaj('z');
        odd11.oddaj('w');
        odd11.oddaj('F');
        odd17.oddaj('C');
        odd05.oddaj('v');
        odd15.oddaj('d');
        odd04.oddaj('O');
        odd02.oddaj('j');
        odd13.oddaj('c');
        odd09.oddaj('x');
        System.out.println(spr24.koliko());
        odd18.oddaj('t');
        odd04.oddaj('E');
        odd12.oddaj('i');
        System.out.println(spr84.koliko());
        odd09.oddaj('q');
        odd09.oddaj('o');
        odd12.oddaj('P');
        odd15.oddaj('L');
        odd02.oddaj('Z');
        odd15.oddaj('K');
        odd12.oddaj('P');
        odd07.oddaj('A');
        odd06.oddaj('m');
        odd13.oddaj('g');
        odd13.oddaj('b');
        odd07.oddaj('t');
        odd11.oddaj('U');
        odd09.oddaj('Q');
        odd00.oddaj('f');
        odd04.oddaj('F');
        odd10.oddaj('h');
        System.out.println(spr32.koliko());
        System.out.println(spr69.koliko());
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd07.oddaj('v');
        odd10.oddaj('Q');
        odd13.oddaj('N');
        odd09.oddaj('M');
        odd10.oddaj('S');
        odd04.oddaj('P');
        odd12.oddaj('l');
        odd09.oddaj('n');
        odd03.oddaj('v');
        odd18.oddaj('f');
        odd11.oddaj('V');
        System.out.println(spr77.koliko());
        odd16.oddaj('t');
        System.out.println("<" + spr60.odZadnjic() + ">");
        odd01.oddaj('b');
        odd01.oddaj('C');
        odd03.oddaj('H');
        System.out.println(spr02.koliko());
        odd00.oddaj('C');
        odd15.oddaj('M');
        System.out.println(spr88.koliko());
        odd10.oddaj('s');
        System.out.println(spr63.koliko());
        odd16.oddaj('Y');
        odd13.oddaj('b');
        odd14.oddaj('w');
        odd11.oddaj('Z');
        odd07.oddaj('r');
        odd15.oddaj('P');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('I');
        odd15.oddaj('q');
        odd08.oddaj('m');
        odd09.oddaj('O');
        odd07.oddaj('V');
        System.out.println(spr17.koliko());
        odd15.oddaj('M');
        odd06.oddaj('e');
        odd14.oddaj('z');
        odd15.oddaj('L');
        odd05.oddaj('A');
        odd01.oddaj('A');
        odd16.oddaj('W');
        System.out.println(spr30.koliko());
        odd17.oddaj('i');
        odd10.oddaj('J');
        odd14.oddaj('G');
        System.out.println(spr54.koliko());
        odd12.oddaj('h');
        odd03.oddaj('k');
        odd03.oddaj('U');
        odd09.oddaj('k');
        odd01.oddaj('t');
        odd18.oddaj('p');
        System.out.println(spr24.koliko());
        odd11.oddaj('c');
        odd10.oddaj('q');
        System.out.println(spr89.koliko());
        System.out.println(spr08.koliko());
        System.out.println(spr57.koliko());
        odd06.oddaj('b');
        odd05.oddaj('X');
        odd04.oddaj('R');
        odd12.oddaj('L');
        odd08.oddaj('q');
        odd03.oddaj('g');
        System.out.println(spr17.koliko());
        odd08.oddaj('K');
        odd16.oddaj('w');
        odd04.oddaj('g');
        odd00.oddaj('e');
        System.out.println("<" + spr69.odZadnjic() + ">");
        odd12.oddaj('F');
        odd18.oddaj('M');
        odd15.oddaj('j');
        odd08.oddaj('U');
        System.out.println(spr43.koliko());
        odd03.oddaj('E');
        odd16.oddaj('n');
        odd12.oddaj('q');
        System.out.println(spr80.koliko());
        odd06.oddaj('M');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd03.oddaj('r');
        System.out.println("<" + spr61.odZadnjic() + ">");
        odd13.oddaj('J');
        odd13.oddaj('y');
        odd18.oddaj('n');
        odd00.oddaj('h');
        odd09.oddaj('I');
        odd01.oddaj('A');
        odd16.oddaj('h');
        System.out.println(spr22.koliko());
        odd08.oddaj('U');
        odd16.oddaj('L');
        odd13.oddaj('q');
        odd17.oddaj('v');
        odd06.oddaj('w');
        odd00.oddaj('x');
        odd07.oddaj('T');
        odd03.oddaj('I');
        odd06.oddaj('p');
        odd03.oddaj('G');
        odd09.oddaj('p');
        odd10.oddaj('e');
        System.out.println("<" + spr68.odZadnjic() + ">");
        odd14.oddaj('T');
        odd07.oddaj('T');
        System.out.println(spr25.koliko());
        odd18.oddaj('V');
        odd09.oddaj('v');
        odd05.oddaj('z');
        odd14.oddaj('A');
        odd18.oddaj('U');
        System.out.println(spr21.koliko());
        System.out.println(spr51.koliko());
        odd14.oddaj('X');
        odd17.oddaj('p');
        odd12.oddaj('M');
        odd13.oddaj('h');
        odd10.oddaj('q');
        odd01.oddaj('t');
        System.out.println("<" + spr70.odZadnjic() + ">");
        odd12.oddaj('r');
        odd13.oddaj('q');
        odd18.oddaj('x');
        odd12.oddaj('h');
        odd04.oddaj('d');
        odd16.oddaj('K');
        System.out.println("<" + spr87.odZadnjic() + ">");
        odd02.oddaj('A');
        odd15.oddaj('J');
        System.out.println(spr39.koliko());
        System.out.println("<" + spr77.odZadnjic() + ">");
        odd04.oddaj('b');
        System.out.println("<" + spr60.odZadnjic() + ">");
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd06.oddaj('G');
        odd01.oddaj('x');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd02.oddaj('P');
        odd18.oddaj('i');
        odd11.oddaj('f');
        odd13.oddaj('H');
        odd03.oddaj('x');
        odd07.oddaj('v');
        odd16.oddaj('h');
        System.out.println("<" + spr45.odZadnjic() + ">");
        System.out.println(spr31.koliko());
        odd00.oddaj('R');
        odd07.oddaj('S');
        odd02.oddaj('G');
        System.out.println("<" + spr58.odZadnjic() + ">");
        odd12.oddaj('H');
        odd16.oddaj('r');
        System.out.println(spr47.koliko());
        odd08.oddaj('x');
        odd01.oddaj('Z');
        odd11.oddaj('w');
        odd03.oddaj('s');
        odd00.oddaj('e');
        odd11.oddaj('p');
        System.out.println(spr40.koliko());
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd16.oddaj('N');
        System.out.println("<" + spr74.odZadnjic() + ">");
        odd00.oddaj('y');
        odd04.oddaj('L');
        odd09.oddaj('X');
        System.out.println(spr44.koliko());
        odd03.oddaj('l');
        System.out.println("<" + spr69.odZadnjic() + ">");
        odd17.oddaj('x');
        odd09.oddaj('x');
        odd04.oddaj('m');
        odd03.oddaj('v');
        System.out.println("<" + spr73.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd15.oddaj('H');
        System.out.println(spr02.koliko());
        odd18.oddaj('e');
        odd12.oddaj('C');
        System.out.println("<" + spr46.odZadnjic() + ">");
        System.out.println("<" + spr62.odZadnjic() + ">");
        System.out.println(spr54.koliko());
        odd13.oddaj('o');
        odd05.oddaj('J');
        odd01.oddaj('T');
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd00.oddaj('E');
        odd03.oddaj('r');
        odd12.oddaj('A');
        odd17.oddaj('U');
        odd15.oddaj('C');
        System.out.println(spr10.koliko());
        odd17.oddaj('F');
        odd12.oddaj('h');
        odd11.oddaj('u');
        System.out.println(spr44.koliko());
        System.out.println("<" + spr39.odZadnjic() + ">");
        odd06.oddaj('A');
        odd14.oddaj('q');
        odd14.oddaj('L');
        odd02.oddaj('t');
        System.out.println(spr03.koliko());
        odd07.oddaj('x');
        System.out.println(spr72.koliko());
        System.out.println(spr11.koliko());
        odd00.oddaj('L');
        System.out.println(spr81.koliko());
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd07.oddaj('y');
        System.out.println(spr27.koliko());
    }
}
