
import java.util.*;

public class Test33 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd16 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd17 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd18 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd19 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd17);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd16);
        Tretja.Sprejemnik spr22 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr23 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr24 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr25 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr26 = new Tretja.Sprejemnik(odd14);
        Tretja.Sprejemnik spr27 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr28 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr29 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr30 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr31 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr32 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr33 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr34 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr35 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr36 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr37 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr38 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr39 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr40 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr41 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr42 = new Tretja.Sprejemnik(odd18);
        Tretja.Sprejemnik spr43 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr44 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr45 = new Tretja.Sprejemnik(odd17);
        Tretja.Sprejemnik spr46 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr47 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr48 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr49 = new Tretja.Sprejemnik(odd15);
        Tretja.Sprejemnik spr50 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr51 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr52 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr53 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr54 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr55 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr56 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr57 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr58 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr59 = new Tretja.Sprejemnik(odd17);
        Tretja.Sprejemnik spr60 = new Tretja.Sprejemnik(odd05);

        odd09.oddaj('Z');
        odd07.oddaj('H');
        odd02.oddaj('N');
        odd04.oddaj('K');
        odd05.oddaj('x');
        odd00.oddaj('I');
        odd09.oddaj('e');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd19.oddaj('F');
        odd01.oddaj('F');
        odd15.oddaj('S');
        odd13.oddaj('I');
        odd19.oddaj('J');
        System.out.println("<" + spr52.odZadnjic() + ">");
        odd17.oddaj('H');
        odd01.oddaj('S');
        odd16.oddaj('J');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('l');
        odd16.oddaj('M');
        System.out.println("<" + spr46.odZadnjic() + ">");
        System.out.println(spr49.koliko());
        odd06.oddaj('i');
        odd10.oddaj('d');
        odd00.oddaj('z');
        odd07.oddaj('H');
        odd00.oddaj('m');
        odd09.oddaj('u');
        odd00.oddaj('x');
        System.out.println("<" + spr45.odZadnjic() + ">");
        odd03.oddaj('f');
        odd07.oddaj('B');
        odd01.oddaj('j');
        odd04.oddaj('V');
        odd13.oddaj('Q');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd10.oddaj('k');
        odd14.oddaj('W');
        odd16.oddaj('o');
        odd03.oddaj('c');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('C');
        odd01.oddaj('B');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd18.oddaj('g');
        odd16.oddaj('L');
        System.out.println(spr10.koliko());
        odd06.oddaj('O');
        odd16.oddaj('a');
        System.out.println(spr21.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd13.oddaj('i');
        odd05.oddaj('t');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd13.oddaj('f');
        odd19.oddaj('r');
        System.out.println(spr19.koliko());
        System.out.println(spr32.koliko());
        odd16.oddaj('O');
        odd07.oddaj('i');
        odd03.oddaj('l');
        System.out.println(spr07.koliko());
        odd14.oddaj('M');
        odd04.oddaj('S');
        odd12.oddaj('a');
        odd11.oddaj('F');
        odd19.oddaj('N');
        odd17.oddaj('B');
        odd08.oddaj('p');
        odd06.oddaj('T');
        odd17.oddaj('J');
        odd03.oddaj('A');
        odd04.oddaj('y');
        odd10.oddaj('L');
        System.out.println(spr54.koliko());
        odd18.oddaj('p');
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd07.oddaj('J');
        odd10.oddaj('v');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('I');
        odd02.oddaj('Y');
        odd10.oddaj('E');
        odd08.oddaj('h');
        System.out.println(spr42.koliko());
        odd00.oddaj('T');
        odd06.oddaj('a');
        odd10.oddaj('y');
        odd16.oddaj('h');
        odd13.oddaj('o');
        odd18.oddaj('c');
        odd00.oddaj('c');
        odd14.oddaj('W');
        System.out.println(spr41.koliko());
        odd16.oddaj('F');
        odd11.oddaj('P');
        System.out.println("<" + spr40.odZadnjic() + ">");
        odd07.oddaj('R');
        odd01.oddaj('v');
        System.out.println("<" + spr39.odZadnjic() + ">");
        odd04.oddaj('S');
        odd13.oddaj('X');
        System.out.println(spr39.koliko());
        odd01.oddaj('J');
        odd08.oddaj('W');
        odd11.oddaj('J');
        odd14.oddaj('L');
        odd00.oddaj('F');
        System.out.println("<" + spr58.odZadnjic() + ">");
        odd07.oddaj('U');
        odd18.oddaj('C');
        odd10.oddaj('Y');
        odd19.oddaj('c');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd19.oddaj('Q');
        odd13.oddaj('I');
        odd13.oddaj('k');
        odd15.oddaj('w');
        odd12.oddaj('V');
        odd06.oddaj('t');
        System.out.println("<" + spr33.odZadnjic() + ">");
        odd07.oddaj('b');
        odd00.oddaj('u');
        System.out.println(spr03.koliko());
        odd01.oddaj('z');
        odd13.oddaj('G');
        odd11.oddaj('F');
        odd14.oddaj('r');
        odd14.oddaj('F');
        odd08.oddaj('j');
        odd04.oddaj('x');
        odd13.oddaj('Z');
        odd19.oddaj('Y');
        odd08.oddaj('T');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd05.oddaj('k');
        odd13.oddaj('C');
        odd11.oddaj('g');
        odd09.oddaj('X');
        odd11.oddaj('m');
        odd12.oddaj('b');
        odd01.oddaj('L');
        odd03.oddaj('x');
        odd03.oddaj('t');
        odd11.oddaj('g');
        odd01.oddaj('P');
        odd10.oddaj('u');
        odd09.oddaj('W');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd12.oddaj('t');
        System.out.println(spr32.koliko());
        odd10.oddaj('L');
        odd16.oddaj('N');
        odd03.oddaj('B');
        odd17.oddaj('I');
        odd16.oddaj('f');
        odd18.oddaj('y');
        odd10.oddaj('h');
        odd03.oddaj('g');
        odd03.oddaj('N');
        odd18.oddaj('o');
        odd05.oddaj('A');
        odd09.oddaj('v');
        odd10.oddaj('n');
        odd03.oddaj('t');
        odd14.oddaj('p');
        odd03.oddaj('D');
        odd19.oddaj('E');
        odd18.oddaj('v');
        System.out.println(spr15.koliko());
        odd15.oddaj('U');
        odd05.oddaj('u');
        odd19.oddaj('h');
        odd14.oddaj('f');
        odd06.oddaj('Z');
        odd15.oddaj('j');
        odd07.oddaj('v');
        odd14.oddaj('g');
        odd02.oddaj('P');
        odd05.oddaj('x');
        odd00.oddaj('h');
        odd04.oddaj('b');
        odd05.oddaj('s');
        odd16.oddaj('M');
        odd08.oddaj('F');
        odd06.oddaj('P');
        System.out.println(spr49.koliko());
        odd15.oddaj('x');
        odd16.oddaj('S');
        odd11.oddaj('i');
        odd11.oddaj('I');
        odd17.oddaj('U');
        odd12.oddaj('I');
        System.out.println("<" + spr50.odZadnjic() + ">");
        odd00.oddaj('v');
        System.out.println("<" + spr60.odZadnjic() + ">");
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd03.oddaj('t');
        odd11.oddaj('o');
        odd19.oddaj('G');
        odd07.oddaj('O');
        odd03.oddaj('J');
        odd19.oddaj('H');
        odd03.oddaj('d');
        odd11.oddaj('c');
        System.out.println(spr34.koliko());
        odd15.oddaj('n');
        odd08.oddaj('U');
        odd03.oddaj('V');
        odd02.oddaj('q');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println(spr36.koliko());
        odd14.oddaj('L');
        odd09.oddaj('L');
        System.out.println(spr44.koliko());
        System.out.println(spr59.koliko());
        odd15.oddaj('D');
        odd16.oddaj('A');
        System.out.println("<" + spr57.odZadnjic() + ">");
        odd09.oddaj('F');
        odd09.oddaj('B');
        odd09.oddaj('F');
        odd12.oddaj('O');
        odd18.oddaj('I');
        odd03.oddaj('B');
        System.out.println(spr09.koliko());
        odd01.oddaj('d');
        odd11.oddaj('P');
        odd13.oddaj('x');
        odd08.oddaj('y');
        odd11.oddaj('w');
        odd14.oddaj('m');
        odd18.oddaj('i');
        odd00.oddaj('f');
        odd05.oddaj('H');
        odd13.oddaj('O');
        odd13.oddaj('U');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd03.oddaj('i');
        odd12.oddaj('D');
        odd12.oddaj('u');
        System.out.println(spr50.koliko());
        odd09.oddaj('w');
        odd15.oddaj('c');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('N');
        System.out.println(spr12.koliko());
        odd04.oddaj('R');
        odd15.oddaj('X');
        System.out.println(spr37.koliko());
        System.out.println("<" + spr52.odZadnjic() + ">");
        odd15.oddaj('s');
        odd14.oddaj('H');
        odd15.oddaj('P');
        odd19.oddaj('d');
        odd12.oddaj('m');
        odd17.oddaj('a');
        odd10.oddaj('w');
        odd05.oddaj('I');
        System.out.println(spr22.koliko());
        odd19.oddaj('k');
        odd06.oddaj('q');
        odd12.oddaj('V');
        odd12.oddaj('B');
        odd17.oddaj('a');
        System.out.println("<" + spr56.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr51.koliko());
        odd17.oddaj('w');
        System.out.println("<" + spr47.odZadnjic() + ">");
        odd18.oddaj('D');
        odd09.oddaj('y');
        odd09.oddaj('I');
        odd05.oddaj('d');
        System.out.println(spr27.koliko());
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd11.oddaj('G');
        odd19.oddaj('A');
        odd15.oddaj('k');
        odd01.oddaj('Z');
        odd12.oddaj('n');
        odd03.oddaj('N');
        odd12.oddaj('C');
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd09.oddaj('H');
        odd19.oddaj('G');
        odd03.oddaj('m');
        odd19.oddaj('p');
        odd05.oddaj('N');
        odd12.oddaj('W');
        odd19.oddaj('u');
        System.out.println(spr00.koliko());
        odd05.oddaj('Q');
        odd16.oddaj('X');
        odd05.oddaj('R');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('e');
        System.out.println(spr54.koliko());
        System.out.println(spr24.koliko());
        odd07.oddaj('S');
        odd16.oddaj('a');
        System.out.println(spr34.koliko());
        odd05.oddaj('k');
        odd19.oddaj('n');
        odd04.oddaj('K');
        odd05.oddaj('H');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr46.koliko());
        odd10.oddaj('E');
        odd03.oddaj('N');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd01.oddaj('E');
        odd17.oddaj('a');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr33.odZadnjic() + ">");
        odd15.oddaj('A');
        odd05.oddaj('Q');
        odd15.oddaj('f');
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd06.oddaj('L');
        odd05.oddaj('E');
        System.out.println(spr17.koliko());
        odd15.oddaj('p');
        System.out.println(spr56.koliko());
        System.out.println(spr21.koliko());
        odd16.oddaj('N');
        odd05.oddaj('I');
        odd05.oddaj('g');
        odd15.oddaj('M');
        odd00.oddaj('l');
        odd02.oddaj('I');
        odd06.oddaj('E');
        odd13.oddaj('x');
        odd19.oddaj('c');
        odd12.oddaj('B');
        odd15.oddaj('g');
        odd07.oddaj('N');
        odd16.oddaj('y');
        odd06.oddaj('z');
        System.out.println(spr28.koliko());
        odd19.oddaj('E');
        odd18.oddaj('P');
        System.out.println(spr35.koliko());
        odd05.oddaj('P');
        System.out.println(spr46.koliko());
        odd11.oddaj('a');
        odd15.oddaj('t');
        odd01.oddaj('Y');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd01.oddaj('O');
        odd03.oddaj('H');
        odd00.oddaj('F');
        odd19.oddaj('L');
        System.out.println(spr34.koliko());
        odd12.oddaj('v');
        odd05.oddaj('j');
        odd19.oddaj('Q');
        odd03.oddaj('q');
        odd07.oddaj('t');
        odd10.oddaj('g');
        System.out.println(spr54.koliko());
        odd13.oddaj('d');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd07.oddaj('e');
        odd18.oddaj('y');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd10.oddaj('d');
        odd16.oddaj('m');
        odd08.oddaj('i');
        System.out.println(spr31.koliko());
        odd01.oddaj('Y');
        odd16.oddaj('a');
        System.out.println("<" + spr53.odZadnjic() + ">");
        odd09.oddaj('A');
        odd09.oddaj('U');
        odd01.oddaj('t');
        odd08.oddaj('u');
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println("<" + spr58.odZadnjic() + ">");
        odd13.oddaj('r');
        odd10.oddaj('Q');
        odd18.oddaj('T');
        odd01.oddaj('B');
        odd02.oddaj('q');
        odd17.oddaj('u');
        odd03.oddaj('P');
        odd00.oddaj('g');
        odd04.oddaj('j');
        odd03.oddaj('u');
        odd02.oddaj('e');
        odd08.oddaj('q');
        odd03.oddaj('A');
        odd04.oddaj('B');
        odd13.oddaj('L');
        odd19.oddaj('d');
        odd04.oddaj('t');
        System.out.println(spr55.koliko());
        odd10.oddaj('C');
        odd16.oddaj('a');
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd12.oddaj('E');
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd08.oddaj('f');
        odd15.oddaj('y');
        odd04.oddaj('o');
        odd00.oddaj('k');
        System.out.println(spr41.koliko());
        odd05.oddaj('a');
        odd01.oddaj('c');
        odd02.oddaj('u');
        odd19.oddaj('F');
        odd18.oddaj('l');
        odd04.oddaj('J');
        System.out.println(spr10.koliko());
        odd08.oddaj('n');
        odd15.oddaj('K');
        odd10.oddaj('N');
        odd07.oddaj('I');
        odd07.oddaj('P');
        odd19.oddaj('V');
        odd13.oddaj('C');
        odd12.oddaj('w');
        odd00.oddaj('D');
        odd14.oddaj('Z');
        odd10.oddaj('h');
        odd00.oddaj('P');
        odd15.oddaj('U');
        odd05.oddaj('Y');
        odd15.oddaj('H');
        odd00.oddaj('x');
        odd15.oddaj('P');
        odd11.oddaj('l');
        odd04.oddaj('T');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('T');
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd16.oddaj('G');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd17.oddaj('L');
        odd02.oddaj('H');
        odd11.oddaj('d');
        odd05.oddaj('p');
        System.out.println(spr45.koliko());
        odd06.oddaj('z');
        odd05.oddaj('Q');
        odd07.oddaj('z');
        odd14.oddaj('q');
        odd18.oddaj('W');
        odd14.oddaj('h');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd14.oddaj('h');
        odd11.oddaj('c');
        System.out.println(spr05.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('i');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd05.oddaj('x');
        odd15.oddaj('H');
        odd18.oddaj('E');
        odd04.oddaj('s');
        odd01.oddaj('W');
        odd18.oddaj('a');
        odd09.oddaj('s');
        odd15.oddaj('F');
        odd18.oddaj('u');
        odd06.oddaj('R');
        odd03.oddaj('o');
        odd14.oddaj('L');
        odd10.oddaj('b');
        odd17.oddaj('Y');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println(spr44.koliko());
        odd17.oddaj('P');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd11.oddaj('A');
        System.out.println(spr50.koliko());
        odd01.oddaj('d');
        odd04.oddaj('I');
        System.out.println(spr29.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd04.oddaj('V');
        odd04.oddaj('w');
        odd07.oddaj('B');
        odd15.oddaj('d');
        odd12.oddaj('N');
        odd12.oddaj('y');
        odd19.oddaj('W');
        odd01.oddaj('T');
        System.out.println(spr57.koliko());
        odd09.oddaj('j');
        odd14.oddaj('G');
        odd15.oddaj('Y');
        odd07.oddaj('k');
        odd04.oddaj('t');
        odd01.oddaj('a');
        odd04.oddaj('F');
        odd17.oddaj('e');
        odd11.oddaj('S');
        odd05.oddaj('o');
        odd14.oddaj('g');
        odd19.oddaj('p');
        odd06.oddaj('R');
        odd01.oddaj('a');
        odd10.oddaj('i');
        odd19.oddaj('e');
        odd00.oddaj('v');
        System.out.println(spr10.koliko());
        odd15.oddaj('Q');
        odd02.oddaj('A');
        odd01.oddaj('l');
        odd14.oddaj('r');
        odd16.oddaj('h');
        odd17.oddaj('m');
        odd16.oddaj('D');
        System.out.println(spr33.koliko());
        odd04.oddaj('Z');
        System.out.println(spr03.koliko());
        odd07.oddaj('N');
        odd14.oddaj('g');
        odd01.oddaj('J');
        odd18.oddaj('r');
        odd13.oddaj('h');
        odd01.oddaj('g');
        System.out.println(spr21.koliko());
        odd04.oddaj('S');
        odd02.oddaj('j');
        System.out.println(spr19.koliko());
        odd00.oddaj('E');
        odd07.oddaj('w');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd09.oddaj('t');
        odd00.oddaj('W');
        odd15.oddaj('d');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd05.oddaj('v');
        odd04.oddaj('g');
        odd13.oddaj('n');
        odd18.oddaj('e');
        odd09.oddaj('j');
        odd09.oddaj('a');
        odd07.oddaj('j');
        odd16.oddaj('Z');
        System.out.println(spr46.koliko());
        odd17.oddaj('O');
        odd01.oddaj('H');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr57.koliko());
        odd02.oddaj('G');
        odd01.oddaj('p');
        odd05.oddaj('h');
        odd03.oddaj('W');
        odd17.oddaj('d');
        odd10.oddaj('I');
        odd00.oddaj('V');
        odd03.oddaj('U');
        System.out.println("<" + spr55.odZadnjic() + ">");
        odd13.oddaj('D');
        odd18.oddaj('R');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd02.oddaj('r');
        odd01.oddaj('b');
        odd04.oddaj('H');
        System.out.println("<" + spr41.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        odd07.oddaj('e');
        odd08.oddaj('S');
        System.out.println(spr43.koliko());
        odd09.oddaj('j');
        odd14.oddaj('H');
        System.out.println(spr17.koliko());
        odd16.oddaj('n');
        odd08.oddaj('L');
        System.out.println(spr45.koliko());
        odd17.oddaj('C');
        odd12.oddaj('Z');
        odd09.oddaj('M');
        odd19.oddaj('X');
        odd10.oddaj('q');
        odd16.oddaj('F');
        System.out.println(spr11.koliko());
        odd00.oddaj('l');
        odd14.oddaj('d');
        System.out.println(spr42.koliko());
        odd11.oddaj('f');
        odd00.oddaj('F');
        System.out.println(spr02.koliko());
        odd17.oddaj('s');
        System.out.println(spr48.koliko());
        odd19.oddaj('T');
        odd19.oddaj('q');
        System.out.println(spr09.koliko());
        odd09.oddaj('c');
        odd07.oddaj('S');
        odd05.oddaj('o');
        System.out.println(spr19.koliko());
        odd14.oddaj('S');
        odd06.oddaj('j');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd10.oddaj('O');
        odd10.oddaj('u');
        odd15.oddaj('I');
        odd08.oddaj('K');
        System.out.println(spr12.koliko());
        odd04.oddaj('I');
        odd05.oddaj('Z');
        odd01.oddaj('T');
        System.out.println(spr43.koliko());
        odd05.oddaj('i');
        odd14.oddaj('w');
        odd04.oddaj('V');
        System.out.println("<" + spr26.odZadnjic() + ">");
        System.out.println(spr46.koliko());
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd18.oddaj('q');
        odd18.oddaj('A');
        odd09.oddaj('L');
        System.out.println(spr27.koliko());
        odd14.oddaj('p');
        odd01.oddaj('l');
        odd16.oddaj('H');
        odd15.oddaj('Y');
        System.out.println("<" + spr54.odZadnjic() + ">");
        odd18.oddaj('i');
        odd19.oddaj('D');
        odd04.oddaj('S');
        odd19.oddaj('A');
        System.out.println(spr29.koliko());
        odd07.oddaj('y');
        odd16.oddaj('a');
        System.out.println(spr03.koliko());
        odd09.oddaj('L');
        odd18.oddaj('h');
        odd18.oddaj('m');
        odd10.oddaj('G');
        odd09.oddaj('U');
        System.out.println(spr09.koliko());
        odd17.oddaj('l');
        odd19.oddaj('h');
        odd05.oddaj('a');
        odd10.oddaj('W');
        odd08.oddaj('S');
        System.out.println(spr46.koliko());
        System.out.println("<" + spr60.odZadnjic() + ">");
        odd02.oddaj('Q');
        odd19.oddaj('P');
        odd04.oddaj('a');
        odd17.oddaj('s');
        odd19.oddaj('I');
        System.out.println(spr25.koliko());
        odd03.oddaj('k');
        odd17.oddaj('i');
        odd08.oddaj('I');
        odd15.oddaj('A');
        odd14.oddaj('W');
        odd01.oddaj('a');
        odd13.oddaj('U');
        odd13.oddaj('Y');
        odd15.oddaj('a');
        odd16.oddaj('u');
        odd14.oddaj('f');
        odd15.oddaj('g');
        odd03.oddaj('A');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('h');
        odd04.oddaj('E');
        odd01.oddaj('o');
        odd12.oddaj('I');
        odd16.oddaj('e');
        odd13.oddaj('B');
        odd10.oddaj('u');
        odd00.oddaj('b');
        System.out.println(spr48.koliko());
        odd08.oddaj('a');
        odd08.oddaj('V');
        odd03.oddaj('F');
        odd10.oddaj('e');
        odd08.oddaj('g');
        odd05.oddaj('f');
        odd15.oddaj('N');
        odd10.oddaj('T');
        odd06.oddaj('k');
        System.out.println(spr20.koliko());
        odd02.oddaj('U');
        System.out.println("<" + spr50.odZadnjic() + ">");
        odd18.oddaj('d');
        odd02.oddaj('R');
        odd19.oddaj('U');
        odd16.oddaj('e');
        odd14.oddaj('j');
        odd00.oddaj('Y');
        odd19.oddaj('x');
        odd13.oddaj('i');
        odd15.oddaj('b');
        odd12.oddaj('V');
        odd13.oddaj('P');
        odd17.oddaj('Z');
        odd07.oddaj('a');
        odd15.oddaj('G');
        odd00.oddaj('V');
        odd04.oddaj('H');
        System.out.println(spr42.koliko());
        odd02.oddaj('i');
        odd16.oddaj('M');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr23.koliko());
        System.out.println(spr55.koliko());
        odd07.oddaj('I');
        odd00.oddaj('l');
        odd06.oddaj('T');
        odd16.oddaj('W');
        odd16.oddaj('M');
        odd18.oddaj('Z');
        odd07.oddaj('H');
        odd16.oddaj('U');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('D');
        System.out.println(spr26.koliko());
        odd00.oddaj('O');
        odd14.oddaj('W');
        odd09.oddaj('U');
        odd00.oddaj('D');
        odd07.oddaj('X');
        odd09.oddaj('E');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd19.oddaj('Z');
        odd14.oddaj('x');
        odd10.oddaj('O');
        odd05.oddaj('G');
        odd02.oddaj('o');
        odd03.oddaj('i');
        odd10.oddaj('k');
        odd06.oddaj('H');
        odd15.oddaj('f');
        odd08.oddaj('R');
        odd02.oddaj('A');
        System.out.println("<" + spr53.odZadnjic() + ">");
        odd04.oddaj('P');
        System.out.println(spr58.koliko());
        odd17.oddaj('x');
        odd08.oddaj('s');
        System.out.println("<" + spr35.odZadnjic() + ">");
        odd10.oddaj('X');
        odd02.oddaj('Y');
        odd03.oddaj('f');
        odd04.oddaj('A');
        odd07.oddaj('q');
        odd04.oddaj('C');
        odd17.oddaj('S');
        odd14.oddaj('X');
        odd14.oddaj('Q');
        odd15.oddaj('p');
        odd09.oddaj('j');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd05.oddaj('l');
        odd03.oddaj('m');
        odd04.oddaj('y');
        odd13.oddaj('z');
        odd14.oddaj('X');
        odd16.oddaj('s');
        System.out.println(spr03.koliko());
        odd07.oddaj('D');
        odd06.oddaj('A');
    }
}
