
import java.util.*;

public class Test26 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);

        odd02.oddaj('g');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('e');
        odd03.oddaj('g');
        odd07.oddaj('W');
        odd08.oddaj('f');
        odd07.oddaj('X');
        odd04.oddaj('N');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('S');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd09.oddaj('X');
        odd03.oddaj('Z');
        System.out.println(spr09.koliko());
        odd07.oddaj('X');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('n');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('G');
        odd05.oddaj('H');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd08.oddaj('r');
        odd02.oddaj('n');
        odd07.oddaj('U');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd03.oddaj('c');
        System.out.println(spr08.koliko());
        odd01.oddaj('p');
        System.out.println(spr01.koliko());
        odd05.oddaj('f');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('W');
        System.out.println(spr03.koliko());
        odd07.oddaj('J');
        odd03.oddaj('l');
        odd03.oddaj('d');
        odd06.oddaj('g');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('X');
        odd03.oddaj('W');
        odd02.oddaj('K');
        odd09.oddaj('x');
        odd07.oddaj('i');
        odd08.oddaj('j');
        odd06.oddaj('j');
        odd01.oddaj('m');
        odd01.oddaj('e');
        odd02.oddaj('j');
        System.out.println(spr05.koliko());
        odd04.oddaj('o');
        odd01.oddaj('H');
        odd08.oddaj('R');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('j');
        odd09.oddaj('H');
        odd05.oddaj('z');
        odd01.oddaj('X');
        odd01.oddaj('F');
        odd02.oddaj('G');
        odd07.oddaj('C');
        odd00.oddaj('f');
        System.out.println(spr02.koliko());
        odd02.oddaj('R');
        odd06.oddaj('j');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        System.out.println(spr05.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd09.oddaj('K');
        odd02.oddaj('F');
        odd04.oddaj('F');
        odd06.oddaj('c');
        odd08.oddaj('n');
        odd00.oddaj('j');
        odd04.oddaj('W');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('Y');
        odd06.oddaj('G');
        odd06.oddaj('A');
        odd02.oddaj('J');
        odd06.oddaj('Q');
        odd03.oddaj('g');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('s');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd09.oddaj('O');
        System.out.println(spr09.koliko());
        odd00.oddaj('U');
        System.out.println(spr00.koliko());
        odd09.oddaj('F');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd01.oddaj('A');
        System.out.println(spr02.koliko());
        System.out.println(spr01.koliko());
        odd00.oddaj('x');
        odd09.oddaj('X');
        System.out.println(spr00.koliko());
        odd06.oddaj('A');
        odd02.oddaj('K');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd05.oddaj('H');
        System.out.println(spr08.koliko());
        System.out.println(spr02.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd05.oddaj('z');
        System.out.println(spr05.koliko());
        odd01.oddaj('p');
        System.out.println(spr01.koliko());
        odd08.oddaj('C');
        System.out.println(spr08.koliko());
        odd02.oddaj('o');
        odd08.oddaj('H');
        odd01.oddaj('m');
        odd04.oddaj('Q');
        odd07.oddaj('u');
        odd08.oddaj('y');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('f');
        odd08.oddaj('T');
        odd08.oddaj('p');
        odd01.oddaj('e');
        odd06.oddaj('v');
        odd08.oddaj('V');
        odd05.oddaj('M');
        odd05.oddaj('V');
        odd01.oddaj('D');
        System.out.println(spr04.koliko());
        odd09.oddaj('F');
        odd07.oddaj('z');
        odd03.oddaj('a');
        odd07.oddaj('h');
        System.out.println(spr06.koliko());
        odd01.oddaj('D');
        System.out.println(spr03.koliko());
        odd09.oddaj('s');
        odd00.oddaj('f');
        odd07.oddaj('B');
        odd07.oddaj('W');
        odd04.oddaj('X');
        System.out.println(spr07.koliko());
        odd00.oddaj('E');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd01.oddaj('R');
        System.out.println(spr09.koliko());
        odd04.oddaj('F');
        odd04.oddaj('i');
        odd09.oddaj('E');
        odd09.oddaj('k');
        odd02.oddaj('f');
        odd02.oddaj('K');
        System.out.println(spr05.koliko());
        odd04.oddaj('y');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('F');
        odd02.oddaj('T');
        odd07.oddaj('D');
        odd04.oddaj('v');
        System.out.println(spr08.koliko());
        odd09.oddaj('C');
        odd00.oddaj('j');
        odd01.oddaj('S');
        odd06.oddaj('D');
        odd01.oddaj('O');
        odd08.oddaj('a');
        odd06.oddaj('z');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('B');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd09.oddaj('P');
        odd00.oddaj('s');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('v');
        odd08.oddaj('O');
        odd05.oddaj('R');
        odd04.oddaj('o');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr04.koliko());
        odd00.oddaj('P');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('o');
        odd03.oddaj('M');
        odd05.oddaj('v');
        odd01.oddaj('Z');
        odd02.oddaj('g');
        odd06.oddaj('g');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd08.oddaj('h');
        odd03.oddaj('S');
        odd01.oddaj('e');
        odd06.oddaj('b');
        odd03.oddaj('F');
        odd05.oddaj('S');
        odd07.oddaj('k');
        odd04.oddaj('w');
        odd03.oddaj('w');
        odd08.oddaj('O');
        odd00.oddaj('L');
        System.out.println(spr03.koliko());
        odd03.oddaj('E');
        System.out.println(spr01.koliko());
        odd00.oddaj('G');
        System.out.println(spr00.koliko());
        odd00.oddaj('P');
        odd00.oddaj('U');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd06.oddaj('V');
        odd08.oddaj('N');
        odd00.oddaj('Q');
        System.out.println(spr00.koliko());
        odd06.oddaj('s');
        odd09.oddaj('w');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd03.oddaj('K');
        odd01.oddaj('v');
        odd06.oddaj('f');
        odd01.oddaj('c');
        odd01.oddaj('h');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd05.oddaj('A');
        odd00.oddaj('D');
        odd03.oddaj('z');
        System.out.println(spr02.koliko());
        odd04.oddaj('S');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd00.oddaj('H');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('W');
        odd03.oddaj('l');
        odd07.oddaj('J');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd08.oddaj('O');
        odd00.oddaj('S');
        odd04.oddaj('r');
        odd08.oddaj('Q');
        odd03.oddaj('w');
        System.out.println(spr08.koliko());
        odd00.oddaj('v');
        odd05.oddaj('v');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('F');
        System.out.println(spr05.koliko());
        odd00.oddaj('y');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('w');
        odd00.oddaj('b');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('A');
        System.out.println(spr00.koliko());
        odd02.oddaj('F');
        odd07.oddaj('Q');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd05.oddaj('x');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('U');
        odd05.oddaj('V');
        odd07.oddaj('k');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('O');
        odd01.oddaj('f');
        System.out.println(spr01.koliko());
        odd00.oddaj('v');
        odd08.oddaj('r');
        odd04.oddaj('U');
        System.out.println(spr00.koliko());
        odd04.oddaj('z');
        System.out.println(spr04.koliko());
        odd00.oddaj('r');
        odd05.oddaj('R');
        odd03.oddaj('x');
        odd08.oddaj('P');
        odd07.oddaj('D');
        odd04.oddaj('F');
        odd01.oddaj('p');
        odd06.oddaj('S');
        odd00.oddaj('p');
        odd03.oddaj('o');
        System.out.println(spr00.koliko());
        odd07.oddaj('Y');
        System.out.println(spr01.koliko());
        odd03.oddaj('W');
        odd04.oddaj('f');
        odd00.oddaj('I');
        odd05.oddaj('x');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('F');
        odd00.oddaj('R');
        System.out.println(spr05.koliko());
        odd00.oddaj('E');
        System.out.println(spr03.koliko());
        odd00.oddaj('G');
        odd02.oddaj('P');
        odd09.oddaj('c');
        odd06.oddaj('i');
        odd04.oddaj('A');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('i');
        odd09.oddaj('K');
        System.out.println(spr00.koliko());
        odd02.oddaj('Y');
        odd03.oddaj('Y');
        odd06.oddaj('n');
        odd09.oddaj('g');
        odd01.oddaj('D');
        odd06.oddaj('p');
        odd03.oddaj('m');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd09.oddaj('e');
        odd01.oddaj('i');
        odd08.oddaj('n');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('v');
        odd08.oddaj('I');
        odd09.oddaj('u');
        odd03.oddaj('j');
        odd08.oddaj('t');
        System.out.println(spr02.koliko());
        odd02.oddaj('X');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('c');
        odd07.oddaj('S');
        System.out.println(spr08.koliko());
        System.out.println(spr06.koliko());
        odd04.oddaj('K');
        odd02.oddaj('U');
        odd00.oddaj('i');
        System.out.println(spr09.koliko());
        odd06.oddaj('X');
        odd04.oddaj('L');
        odd08.oddaj('C');
        odd00.oddaj('z');
        odd02.oddaj('C');
        System.out.println(spr04.koliko());
        System.out.println(spr08.koliko());
        odd07.oddaj('E');
        System.out.println(spr02.koliko());
        odd08.oddaj('f');
        odd00.oddaj('e');
        odd09.oddaj('u');
        System.out.println(spr06.koliko());
        odd04.oddaj('j');
        System.out.println(spr07.koliko());
        System.out.println(spr00.koliko());
        odd00.oddaj('q');
        odd05.oddaj('y');
        odd08.oddaj('u');
        odd01.oddaj('u');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd04.oddaj('r');
        odd00.oddaj('J');
        odd00.oddaj('Y');
        odd05.oddaj('F');
        odd02.oddaj('x');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('Z');
        odd06.oddaj('a');
        odd06.oddaj('e');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('U');
        odd00.oddaj('n');
        System.out.println(spr02.koliko());
        odd01.oddaj('W');
        System.out.println(spr01.koliko());
        odd01.oddaj('t');
        odd07.oddaj('W');
        odd07.oddaj('S');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd07.oddaj('T');
        odd02.oddaj('G');
        odd07.oddaj('P');
        System.out.println(spr06.koliko());
        odd07.oddaj('L');
        odd07.oddaj('B');
        odd09.oddaj('y');
        odd04.oddaj('A');
        odd07.oddaj('x');
        odd02.oddaj('x');
        odd08.oddaj('k');
        odd08.oddaj('L');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd08.oddaj('D');
        odd09.oddaj('M');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        System.out.println(spr08.koliko());
        odd06.oddaj('M');
        System.out.println(spr01.koliko());
        odd08.oddaj('V');
        odd05.oddaj('q');
        System.out.println(spr07.koliko());
        odd00.oddaj('X');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd08.oddaj('Y');
        odd01.oddaj('G');
        odd01.oddaj('i');
        odd08.oddaj('R');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('R');
        odd01.oddaj('g');
        odd02.oddaj('E');
        odd09.oddaj('v');
        odd08.oddaj('F');
        odd01.oddaj('t');
        odd03.oddaj('A');
        odd09.oddaj('m');
        odd05.oddaj('d');
        odd09.oddaj('j');
        odd04.oddaj('r');
        System.out.println(spr09.koliko());
        odd09.oddaj('h');
        odd05.oddaj('x');
        System.out.println(spr08.koliko());
        System.out.println(spr06.koliko());
        odd03.oddaj('C');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('C');
        odd05.oddaj('Q');
        odd06.oddaj('C');
        odd03.oddaj('d');
        odd09.oddaj('H');
        odd00.oddaj('b');
        odd08.oddaj('F');
        odd02.oddaj('G');
        odd08.oddaj('o');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('g');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd06.oddaj('D');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd06.oddaj('x');
        odd02.oddaj('v');
        odd07.oddaj('f');
        System.out.println(spr00.koliko());
        System.out.println(spr01.koliko());
        odd05.oddaj('k');
        odd05.oddaj('z');
        odd06.oddaj('d');
        odd03.oddaj('r');
        odd05.oddaj('U');
        odd08.oddaj('D');
        odd02.oddaj('u');
        odd08.oddaj('r');
        odd00.oddaj('H');
        odd02.oddaj('P');
        odd06.oddaj('c');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd00.oddaj('t');
        odd08.oddaj('j');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('N');
        odd08.oddaj('o');
        odd02.oddaj('D');
        odd07.oddaj('z');
        odd01.oddaj('v');
        odd03.oddaj('I');
        odd00.oddaj('n');
        odd08.oddaj('N');
        odd08.oddaj('B');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('R');
        odd04.oddaj('H');
        System.out.println(spr04.koliko());
        odd09.oddaj('r');
        odd04.oddaj('S');
        odd07.oddaj('X');
        odd03.oddaj('r');
        System.out.println(spr07.koliko());
        System.out.println(spr05.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('q');
        odd02.oddaj('f');
        System.out.println(spr02.koliko());
        odd08.oddaj('b');
        System.out.println(spr08.koliko());
        odd02.oddaj('N');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('R');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd02.oddaj('u');
        odd08.oddaj('c');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd08.oddaj('R');
        odd02.oddaj('F');
        odd06.oddaj('l');
        odd04.oddaj('u');
        odd07.oddaj('H');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd09.oddaj('w');
        odd04.oddaj('k');
        odd09.oddaj('d');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('G');
        odd07.oddaj('A');
        odd02.oddaj('d');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd00.oddaj('l');
        odd06.oddaj('Q');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd09.oddaj('U');
        odd03.oddaj('u');
        odd05.oddaj('J');
        System.out.println(spr09.koliko());
        odd04.oddaj('y');
        odd01.oddaj('O');
        odd07.oddaj('J');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('R');
        odd04.oddaj('P');
        System.out.println(spr01.koliko());
        odd01.oddaj('U');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('E');
        odd08.oddaj('J');
        odd08.oddaj('i');
        odd07.oddaj('O');
        odd04.oddaj('U');
        System.out.println(spr05.koliko());
        System.out.println(spr07.koliko());
        odd07.oddaj('V');
        odd08.oddaj('y');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('k');
        odd08.oddaj('Z');
        odd09.oddaj('a');
        odd00.oddaj('H');
        System.out.println(spr08.koliko());
        odd08.oddaj('J');
        odd00.oddaj('u');
        System.out.println(spr00.koliko());
        odd03.oddaj('C');
        odd05.oddaj('I');
        odd05.oddaj('O');
        odd07.oddaj('x');
        System.out.println(spr08.koliko());
        System.out.println(spr04.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('M');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd06.oddaj('w');
        System.out.println(spr06.koliko());
        odd02.oddaj('u');
        System.out.println(spr02.koliko());
        odd07.oddaj('l');
        odd04.oddaj('f');
        odd01.oddaj('v');
        System.out.println(spr07.koliko());
        odd05.oddaj('W');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('i');
        odd05.oddaj('E');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('w');
        odd06.oddaj('K');
        odd08.oddaj('U');
        odd05.oddaj('s');
        odd06.oddaj('O');
        odd03.oddaj('a');
        odd05.oddaj('C');
        odd09.oddaj('v');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('I');
        odd01.oddaj('o');
        odd04.oddaj('F');
        System.out.println(spr03.koliko());
        System.out.println(spr04.koliko());
        odd00.oddaj('F');
        odd07.oddaj('X');
        System.out.println(spr01.koliko());
        odd03.oddaj('p');
        System.out.println(spr00.koliko());
        odd02.oddaj('X');
        odd04.oddaj('q');
        System.out.println(spr02.koliko());
        odd02.oddaj('B');
        odd06.oddaj('P');
        System.out.println(spr02.koliko());
        odd04.oddaj('a');
        odd08.oddaj('s');
        odd06.oddaj('U');
        odd03.oddaj('K');
        System.out.println(spr04.koliko());
        System.out.println(spr05.koliko());
        odd08.oddaj('i');
        odd05.oddaj('z');
        odd07.oddaj('L');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd09.oddaj('V');
        System.out.println(spr08.koliko());
        System.out.println(spr09.koliko());
        odd09.oddaj('y');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('w');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd08.oddaj('n');
        odd05.oddaj('r');
        System.out.println(spr08.koliko());
        odd09.oddaj('O');
        odd09.oddaj('M');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd09.oddaj('V');
        odd00.oddaj('n');
        odd01.oddaj('g');
        odd00.oddaj('y');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('j');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('Y');
        odd02.oddaj('m');
        odd08.oddaj('Q');
        odd00.oddaj('A');
        System.out.println(spr07.koliko());
        odd07.oddaj('I');
        System.out.println(spr00.koliko());
        System.out.println(spr08.koliko());
        odd08.oddaj('x');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('G');
        odd06.oddaj('w');
        System.out.println(spr08.koliko());
        odd06.oddaj('e');
        odd02.oddaj('G');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('S');
        odd09.oddaj('D');
        odd01.oddaj('R');
        odd01.oddaj('l');
        odd05.oddaj('F');
        odd02.oddaj('f');
        System.out.println(spr05.koliko());
        odd04.oddaj('L');
        odd06.oddaj('r');
        System.out.println(spr06.koliko());
        odd07.oddaj('D');
        System.out.println(spr01.koliko());
        System.out.println(spr09.koliko());
        odd02.oddaj('H');
        odd08.oddaj('i');
        System.out.println(spr04.koliko());
        odd00.oddaj('N');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd06.oddaj('I');
        odd00.oddaj('u');
        odd09.oddaj('i');
        odd03.oddaj('e');
        System.out.println(spr00.koliko());
        System.out.println(spr08.koliko());
        odd01.oddaj('V');
        odd07.oddaj('Q');
        odd02.oddaj('R');
        odd08.oddaj('X');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd06.oddaj('r');
        odd07.oddaj('B');
        odd00.oddaj('s');
        odd05.oddaj('l');
        odd07.oddaj('u');
        odd00.oddaj('j');
        System.out.println(spr07.koliko());
        odd02.oddaj('k');
        odd00.oddaj('q');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('l');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('f');
        System.out.println(spr09.koliko());
        System.out.println(spr00.koliko());
        odd05.oddaj('f');
        System.out.println(spr06.koliko());
        System.out.println(spr05.koliko());
        System.out.println(spr02.koliko());
        odd01.oddaj('V');
        System.out.println(spr03.koliko());
        System.out.println(spr01.koliko());
        odd07.oddaj('u');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd08.oddaj('A');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd02.oddaj('L');
        odd06.oddaj('F');
        odd01.oddaj('G');
        odd02.oddaj('l');
        odd09.oddaj('L');
        System.out.println(spr02.koliko());
        odd06.oddaj('i');
        odd09.oddaj('B');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('y');
        odd06.oddaj('u');
        odd06.oddaj('b');
        odd00.oddaj('x');
        odd06.oddaj('q');
        odd03.oddaj('n');
        odd07.oddaj('R');
        odd08.oddaj('F');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd03.oddaj('l');
        odd08.oddaj('i');
        System.out.println(spr00.koliko());
        odd03.oddaj('V');
        odd07.oddaj('G');
        odd00.oddaj('a');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd08.oddaj('E');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('s');
        System.out.println(spr08.koliko());
        odd09.oddaj('B');
        odd09.oddaj('g');
        odd03.oddaj('T');
        odd04.oddaj('e');
        odd02.oddaj('K');
        System.out.println(spr02.koliko());
        System.out.println(spr09.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('h');
        System.out.println(spr04.koliko());
        odd03.oddaj('j');
        System.out.println(spr06.koliko());
        odd00.oddaj('t');
        odd07.oddaj('w');
        System.out.println(spr07.koliko());
        odd02.oddaj('X');
        odd09.oddaj('p');
        odd00.oddaj('D');
        System.out.println(spr09.koliko());
        odd08.oddaj('M');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('R');
        odd05.oddaj('m');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd09.oddaj('O');
        odd07.oddaj('b');
        System.out.println(spr05.koliko());
        odd03.oddaj('E');
        odd09.oddaj('e');
        odd02.oddaj('e');
        odd01.oddaj('J');
        System.out.println(spr07.koliko());
        System.out.println(spr03.koliko());
        odd07.oddaj('P');
        odd06.oddaj('R');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd09.oddaj('h');
        odd00.oddaj('N');
        odd08.oddaj('C');
        odd00.oddaj('M');
        System.out.println(spr00.koliko());
        odd07.oddaj('u');
        odd04.oddaj('Q');
        System.out.println(spr07.koliko());
        odd03.oddaj('C');
        odd03.oddaj('b');
        System.out.println(spr09.koliko());
        odd01.oddaj('M');
        odd00.oddaj('n');
        odd04.oddaj('k');
        odd07.oddaj('n');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('w');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('D');
        odd00.oddaj('H');
        odd02.oddaj('m');
        System.out.println(spr00.koliko());
        System.out.println(spr04.koliko());
        System.out.println(spr01.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('K');
        odd00.oddaj('J');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd08.oddaj('f');
        odd01.oddaj('u');
        System.out.println(spr05.koliko());
        odd05.oddaj('O');
        odd02.oddaj('W');
        odd07.oddaj('v');
        odd00.oddaj('g');
        System.out.println(spr02.koliko());
        odd08.oddaj('P');
        odd00.oddaj('M');
        odd01.oddaj('f');
        odd04.oddaj('b');
        System.out.println(spr07.koliko());
        System.out.println(spr04.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd07.oddaj('m');
        System.out.println(spr07.koliko());
        odd04.oddaj('q');
        odd00.oddaj('t');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd06.oddaj('T');
        odd09.oddaj('W');
        odd04.oddaj('E');
        odd00.oddaj('l');
        System.out.println(spr06.koliko());
        System.out.println(spr04.koliko());
        odd01.oddaj('o');
        odd01.oddaj('l');
        odd04.oddaj('b');
        odd05.oddaj('O');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('x');
        odd09.oddaj('K');
        odd02.oddaj('e');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('Z');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('R');
        System.out.println(spr02.koliko());
        odd08.oddaj('A');
        odd02.oddaj('i');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('f');
        odd05.oddaj('f');
        odd09.oddaj('L');
        odd06.oddaj('z');
        odd08.oddaj('b');
        odd06.oddaj('S');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd04.oddaj('g');
        odd02.oddaj('L');
        odd01.oddaj('T');
        odd08.oddaj('w');
        odd02.oddaj('C');
        System.out.println(spr01.koliko());
        odd00.oddaj('R');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('B');
        System.out.println(spr05.koliko());
        odd00.oddaj('v');
        odd01.oddaj('l');
        System.out.println(spr00.koliko());
        odd00.oddaj('b');
        odd07.oddaj('U');
        odd06.oddaj('U');
        odd03.oddaj('U');
        odd01.oddaj('t');
        odd07.oddaj('L');
        odd08.oddaj('p');
        odd00.oddaj('Q');
        odd06.oddaj('n');
        odd01.oddaj('P');
        odd00.oddaj('y');
        odd06.oddaj('X');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('B');
        odd01.oddaj('a');
        System.out.println(spr07.koliko());
        odd05.oddaj('r');
        odd06.oddaj('W');
        odd00.oddaj('v');
        odd05.oddaj('U');
        odd00.oddaj('w');
        odd02.oddaj('n');
        odd06.oddaj('F');
        odd03.oddaj('G');
        odd05.oddaj('E');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd03.oddaj('t');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('r');
        odd06.oddaj('I');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('Q');
        System.out.println(spr00.koliko());
        odd05.oddaj('D');
        odd04.oddaj('P');
        odd09.oddaj('a');
        odd02.oddaj('U');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd09.oddaj('b');
        odd04.oddaj('E');
        odd08.oddaj('n');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('l');
        odd00.oddaj('P');
        odd00.oddaj('o');
        odd05.oddaj('L');
        odd05.oddaj('u');
        odd00.oddaj('Y');
        System.out.println(spr05.koliko());
        odd07.oddaj('n');
        odd00.oddaj('P');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('H');
        odd08.oddaj('P');
        odd07.oddaj('j');
        odd04.oddaj('d');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd09.oddaj('Z');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
    }
}
