
import java.util.*;

public class Test28 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd12);
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd13);
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd14);
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd15);
        Tretja.Oddajnik odd16 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd16);

        odd04.oddaj('J');
        odd08.oddaj('v');
        odd13.oddaj('J');
        odd10.oddaj('Q');
        odd13.oddaj('C');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd01.oddaj('h');
        odd13.oddaj('v');
        System.out.println(spr08.koliko());
        odd12.oddaj('Z');
        odd13.oddaj('z');
        odd08.oddaj('q');
        odd05.oddaj('P');
        odd15.oddaj('W');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('R');
        odd04.oddaj('e');
        odd13.oddaj('S');
        odd16.oddaj('i');
        odd04.oddaj('U');
        odd05.oddaj('E');
        System.out.println(spr01.koliko());
        System.out.println(spr07.koliko());
        odd04.oddaj('C');
        odd09.oddaj('f');
        odd00.oddaj('b');
        odd08.oddaj('Q');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd11.oddaj('d');
        odd02.oddaj('U');
        odd14.oddaj('W');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd08.oddaj('N');
        System.out.println(spr08.koliko());
        odd06.oddaj('x');
        odd07.oddaj('Z');
        odd13.oddaj('e');
        System.out.println(spr06.koliko());
        System.out.println(spr12.koliko());
        odd02.oddaj('H');
        odd04.oddaj('j');
        odd16.oddaj('i');
        System.out.println(spr05.koliko());
        odd13.oddaj('i');
        odd14.oddaj('Q');
        odd00.oddaj('B');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd01.oddaj('y');
        odd15.oddaj('f');
        odd05.oddaj('m');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('B');
        odd13.oddaj('X');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('A');
        odd06.oddaj('c');
        odd08.oddaj('T');
        odd02.oddaj('M');
        odd14.oddaj('D');
        odd01.oddaj('K');
        System.out.println(spr02.koliko());
        odd13.oddaj('W');
        odd05.oddaj('Z');
        odd02.oddaj('q');
        odd15.oddaj('a');
        odd16.oddaj('g');
        odd08.oddaj('p');
        odd03.oddaj('d');
        odd09.oddaj('y');
        odd03.oddaj('w');
        odd05.oddaj('N');
        odd02.oddaj('L');
        odd15.oddaj('j');
        odd09.oddaj('v');
        odd02.oddaj('b');
        odd11.oddaj('V');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr08.koliko());
        odd07.oddaj('Y');
        odd04.oddaj('e');
        odd03.oddaj('K');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('N');
        odd05.oddaj('k');
        System.out.println(spr11.koliko());
        odd02.oddaj('s');
        odd14.oddaj('p');
        odd02.oddaj('z');
        odd16.oddaj('o');
        odd01.oddaj('J');
        odd09.oddaj('R');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd13.oddaj('G');
        odd08.oddaj('F');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('i');
        odd10.oddaj('X');
        odd12.oddaj('h');
        odd07.oddaj('j');
        odd07.oddaj('U');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd14.oddaj('f');
        odd08.oddaj('j');
        odd11.oddaj('X');
        System.out.println(spr16.koliko());
        odd09.oddaj('B');
        odd10.oddaj('z');
        odd12.oddaj('z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd13.oddaj('U');
        odd13.oddaj('m');
        odd04.oddaj('p');
        odd06.oddaj('W');
        odd09.oddaj('j');
        odd12.oddaj('L');
        odd05.oddaj('R');
        odd11.oddaj('H');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd04.oddaj('R');
        odd13.oddaj('y');
        odd12.oddaj('K');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd08.oddaj('Q');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        odd01.oddaj('j');
        odd05.oddaj('w');
        odd03.oddaj('t');
        odd10.oddaj('F');
        odd10.oddaj('l');
        odd04.oddaj('U');
        odd06.oddaj('C');
        odd14.oddaj('w');
        odd04.oddaj('C');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        odd10.oddaj('S');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd02.oddaj('E');
        odd02.oddaj('c');
        odd12.oddaj('o');
        odd01.oddaj('z');
        odd08.oddaj('W');
        odd02.oddaj('C');
        odd00.oddaj('q');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd13.oddaj('w');
        System.out.println(spr01.koliko());
        odd15.oddaj('Y');
        odd15.oddaj('v');
        odd02.oddaj('L');
        odd13.oddaj('H');
        odd12.oddaj('I');
        odd11.oddaj('u');
        System.out.println(spr06.koliko());
        odd05.oddaj('x');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd06.oddaj('K');
        System.out.println(spr00.koliko());
        odd05.oddaj('X');
        odd08.oddaj('H');
        odd01.oddaj('l');
        System.out.println(spr10.koliko());
        odd00.oddaj('r');
        odd12.oddaj('M');
        odd09.oddaj('Q');
        odd16.oddaj('X');
        odd15.oddaj('F');
        odd11.oddaj('f');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd13.oddaj('v');
        System.out.println(spr01.koliko());
        System.out.println(spr00.koliko());
        odd00.oddaj('N');
        odd08.oddaj('t');
        odd09.oddaj('X');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        odd12.oddaj('e');
        odd01.oddaj('F');
        odd07.oddaj('e');
        odd10.oddaj('q');
        odd10.oddaj('N');
        odd11.oddaj('D');
        odd01.oddaj('f');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd13.oddaj('f');
        odd03.oddaj('C');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd10.oddaj('A');
        odd11.oddaj('w');
        odd12.oddaj('E');
        odd16.oddaj('V');
        System.out.println(spr07.koliko());
        odd02.oddaj('Q');
        odd05.oddaj('Q');
        odd04.oddaj('Z');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd05.oddaj('Y');
        odd03.oddaj('m');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('r');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd16.oddaj('N');
        odd04.oddaj('r');
        odd08.oddaj('p');
        odd15.oddaj('b');
        odd04.oddaj('p');
        odd02.oddaj('o');
        odd02.oddaj('u');
        odd11.oddaj('e');
        System.out.println(spr01.koliko());
        odd11.oddaj('J');
        odd04.oddaj('T');
        odd12.oddaj('F');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        odd07.oddaj('a');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('o');
        odd15.oddaj('o');
        odd02.oddaj('T');
        odd03.oddaj('P');
        odd02.oddaj('r');
        odd13.oddaj('r');
        System.out.println(spr10.koliko());
        odd06.oddaj('R');
        odd08.oddaj('P');
        odd09.oddaj('o');
        odd04.oddaj('W');
        odd13.oddaj('N');
        odd00.oddaj('k');
        odd03.oddaj('q');
        odd16.oddaj('I');
        odd15.oddaj('K');
        odd03.oddaj('z');
        odd11.oddaj('o');
        odd09.oddaj('C');
        System.out.println(spr11.koliko());
        odd03.oddaj('K');
        odd02.oddaj('L');
        odd12.oddaj('I');
        System.out.println(spr16.koliko());
        odd10.oddaj('C');
        odd04.oddaj('v');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('o');
        odd13.oddaj('I');
        odd03.oddaj('C');
        odd03.oddaj('r');
        odd14.oddaj('L');
        odd01.oddaj('t');
        odd01.oddaj('i');
        odd00.oddaj('b');
        odd00.oddaj('G');
        odd12.oddaj('e');
        odd11.oddaj('D');
        odd02.oddaj('r');
        System.out.println(spr01.koliko());
        odd03.oddaj('u');
        odd13.oddaj('M');
        odd09.oddaj('a');
        odd04.oddaj('B');
        odd02.oddaj('Y');
        odd12.oddaj('v');
        odd09.oddaj('F');
        odd00.oddaj('k');
        odd08.oddaj('D');
        odd16.oddaj('R');
        odd12.oddaj('M');
        odd10.oddaj('z');
        odd09.oddaj('o');
        odd15.oddaj('U');
        odd11.oddaj('o');
        odd04.oddaj('U');
        odd01.oddaj('Z');
        odd06.oddaj('d');
        odd03.oddaj('A');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd15.oddaj('L');
        odd15.oddaj('Y');
        odd13.oddaj('w');
        System.out.println(spr12.koliko());
        odd10.oddaj('s');
        odd13.oddaj('Q');
        odd07.oddaj('j');
        System.out.println(spr14.koliko());
        odd16.oddaj('s');
        System.out.println(spr01.koliko());
        System.out.println(spr07.koliko());
        System.out.println(spr15.koliko());
        odd03.oddaj('U');
        odd01.oddaj('s');
        odd01.oddaj('E');
        odd03.oddaj('L');
        odd00.oddaj('S');
        System.out.println(spr16.koliko());
        odd09.oddaj('L');
        System.out.println(spr06.koliko());
        odd00.oddaj('r');
        odd11.oddaj('a');
        System.out.println(spr11.koliko());
        System.out.println(spr03.koliko());
        odd08.oddaj('A');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('q');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd05.oddaj('E');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd04.oddaj('D');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd06.oddaj('r');
        odd12.oddaj('y');
        System.out.println(spr06.koliko());
        odd15.oddaj('f');
        odd06.oddaj('P');
        odd14.oddaj('C');
        odd13.oddaj('N');
        odd09.oddaj('j');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd02.oddaj('L');
        odd10.oddaj('G');
        odd12.oddaj('T');
        odd12.oddaj('o');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd08.oddaj('N');
        odd07.oddaj('k');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd14.oddaj('e');
        odd04.oddaj('m');
        odd10.oddaj('t');
        odd06.oddaj('n');
        odd01.oddaj('J');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd11.oddaj('L');
        odd03.oddaj('D');
        odd08.oddaj('k');
        odd10.oddaj('H');
        odd02.oddaj('Z');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd15.oddaj('u');
        System.out.println(spr07.koliko());
        odd02.oddaj('X');
        odd16.oddaj('l');
        odd07.oddaj('x');
        odd06.oddaj('l');
        odd00.oddaj('s');
        odd10.oddaj('D');
        odd10.oddaj('u');
        odd01.oddaj('F');
        odd05.oddaj('P');
        odd12.oddaj('f');
        odd02.oddaj('K');
        odd01.oddaj('M');
        odd14.oddaj('H');
        System.out.println(spr12.koliko());
        System.out.println(spr04.koliko());
        odd06.oddaj('i');
        odd16.oddaj('R');
        odd16.oddaj('M');
        odd11.oddaj('i');
        odd12.oddaj('I');
        odd10.oddaj('J');
        System.out.println(spr14.koliko());
        odd10.oddaj('M');
        odd08.oddaj('p');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd09.oddaj('r');
        System.out.println(spr08.koliko());
        odd03.oddaj('o');
        odd14.oddaj('g');
        System.out.println(spr07.koliko());
        odd04.oddaj('F');
        System.out.println(spr16.koliko());
        odd13.oddaj('s');
        odd01.oddaj('b');
        odd06.oddaj('K');
        odd01.oddaj('K');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd06.oddaj('J');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd07.oddaj('Q');
        odd04.oddaj('E');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd13.oddaj('H');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd13.oddaj('T');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd11.oddaj('e');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd15.oddaj('U');
        odd14.oddaj('F');
        odd06.oddaj('L');
        odd16.oddaj('U');
        odd16.oddaj('i');
        odd09.oddaj('z');
        odd00.oddaj('c');
        odd06.oddaj('e');
        odd14.oddaj('p');
        odd06.oddaj('F');
        odd11.oddaj('d');
        odd01.oddaj('f');
        System.out.println(spr12.koliko());
        odd13.oddaj('A');
        odd13.oddaj('I');
        odd10.oddaj('i');
        System.out.println(spr06.koliko());
        odd07.oddaj('U');
        odd11.oddaj('u');
        odd09.oddaj('x');
        odd01.oddaj('e');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('T');
        odd11.oddaj('T');
        odd12.oddaj('Q');
        odd07.oddaj('l');
        odd05.oddaj('Z');
        odd07.oddaj('f');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd10.oddaj('s');
        odd01.oddaj('E');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd14.oddaj('H');
        odd01.oddaj('w');
        odd03.oddaj('b');
        odd02.oddaj('c');
        System.out.println(spr04.koliko());
        odd15.oddaj('R');
        odd01.oddaj('I');
        odd04.oddaj('v');
        odd04.oddaj('S');
        odd02.oddaj('R');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd08.oddaj('P');
        odd06.oddaj('S');
        odd11.oddaj('O');
        odd11.oddaj('A');
        odd12.oddaj('C');
        odd06.oddaj('V');
        odd16.oddaj('Y');
        odd04.oddaj('b');
        odd13.oddaj('L');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd04.oddaj('f');
        System.out.println(spr07.koliko());
        odd05.oddaj('q');
        odd04.oddaj('d');
        odd07.oddaj('I');
        odd15.oddaj('y');
        odd01.oddaj('m');
        odd12.oddaj('E');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd12.oddaj('Y');
        odd10.oddaj('E');
        odd14.oddaj('K');
        odd15.oddaj('w');
        odd16.oddaj('h');
        odd10.oddaj('r');
        odd05.oddaj('O');
        odd06.oddaj('A');
        odd03.oddaj('c');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd12.oddaj('X');
        odd07.oddaj('A');
        odd14.oddaj('l');
        System.out.println(spr08.koliko());
        odd06.oddaj('L');
        odd00.oddaj('k');
        odd08.oddaj('P');
        odd04.oddaj('h');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('m');
        odd02.oddaj('H');
        odd07.oddaj('V');
        odd07.oddaj('b');
        odd12.oddaj('O');
        odd10.oddaj('k');
        odd11.oddaj('v');
        odd14.oddaj('D');
        odd04.oddaj('Q');
        odd05.oddaj('z');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd12.oddaj('N');
        odd11.oddaj('S');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd02.oddaj('M');
        odd15.oddaj('H');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd13.oddaj('Y');
        System.out.println(spr07.koliko());
        odd07.oddaj('p');
        odd03.oddaj('u');
        odd00.oddaj('I');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd01.oddaj('M');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd13.oddaj('B');
        odd11.oddaj('o');
        odd09.oddaj('u');
        odd08.oddaj('b');
        odd08.oddaj('U');
        odd02.oddaj('K');
        odd00.oddaj('m');
        System.out.println(spr09.koliko());
        odd16.oddaj('T');
        odd12.oddaj('J');
        odd14.oddaj('a');
        odd10.oddaj('b');
        odd08.oddaj('F');
        System.out.println(spr00.koliko());
        odd16.oddaj('e');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr16.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('r');
        odd02.oddaj('V');
        odd16.oddaj('C');
        odd10.oddaj('j');
        odd01.oddaj('H');
        odd14.oddaj('H');
        odd08.oddaj('b');
        odd11.oddaj('K');
        odd01.oddaj('C');
        odd09.oddaj('m');
        odd06.oddaj('g');
        odd02.oddaj('o');
        odd05.oddaj('h');
        odd08.oddaj('E');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd00.oddaj('X');
        odd01.oddaj('w');
        odd02.oddaj('u');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd12.oddaj('j');
        odd14.oddaj('T');
        odd13.oddaj('d');
        odd11.oddaj('a');
        odd14.oddaj('W');
        odd00.oddaj('J');
        odd07.oddaj('J');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd15.oddaj('L');
        odd06.oddaj('S');
        odd06.oddaj('p');
        odd07.oddaj('i');
        System.out.println(spr07.koliko());
        odd09.oddaj('r');
        odd01.oddaj('d');
        odd10.oddaj('c');
        odd07.oddaj('A');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd04.oddaj('S');
        odd07.oddaj('y');
        odd13.oddaj('L');
        odd15.oddaj('u');
        odd11.oddaj('j');
        odd04.oddaj('e');
        odd02.oddaj('p');
        odd05.oddaj('E');
        odd16.oddaj('z');
        odd06.oddaj('h');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd04.oddaj('d');
        odd01.oddaj('Z');
        odd01.oddaj('d');
        odd04.oddaj('x');
        odd09.oddaj('Y');
        odd06.oddaj('Z');
        System.out.println(spr05.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd00.oddaj('P');
        odd12.oddaj('d');
        odd14.oddaj('e');
        odd01.oddaj('O');
        odd04.oddaj('K');
        odd14.oddaj('C');
        odd01.oddaj('B');
        System.out.println(spr08.koliko());
        odd10.oddaj('v');
        odd08.oddaj('u');
        odd14.oddaj('c');
        odd00.oddaj('V');
        odd15.oddaj('v');
        System.out.println(spr00.koliko());
        System.out.println(spr01.koliko());
        odd11.oddaj('s');
        odd15.oddaj('H');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd12.oddaj('t');
        odd03.oddaj('l');
        odd06.oddaj('O');
        odd12.oddaj('Q');
        odd11.oddaj('I');
        odd08.oddaj('W');
        odd03.oddaj('e');
        System.out.println(spr11.koliko());
        odd04.oddaj('i');
        odd10.oddaj('o');
        odd02.oddaj('K');
        odd11.oddaj('a');
        odd05.oddaj('Y');
        odd04.oddaj('G');
        odd02.oddaj('v');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd05.oddaj('x');
        odd10.oddaj('D');
        odd07.oddaj('K');
        odd05.oddaj('W');
        odd16.oddaj('j');
        odd11.oddaj('P');
        System.out.println(spr09.koliko());
        odd10.oddaj('J');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd09.oddaj('R');
        odd04.oddaj('I');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        odd05.oddaj('T');
        odd09.oddaj('X');
        odd02.oddaj('S');
        odd09.oddaj('l');
        odd04.oddaj('Y');
        System.out.println(spr13.koliko());
        odd06.oddaj('k');
        odd01.oddaj('D');
        odd07.oddaj('p');
        odd01.oddaj('i');
        odd12.oddaj('p');
        odd04.oddaj('R');
        odd06.oddaj('g');
        odd09.oddaj('M');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd09.oddaj('G');
        odd00.oddaj('n');
        odd03.oddaj('j');
        odd10.oddaj('A');
        odd12.oddaj('o');
        System.out.println(spr09.koliko());
        odd08.oddaj('n');
        odd08.oddaj('U');
        System.out.println(spr10.koliko());
        System.out.println(spr08.koliko());
        odd00.oddaj('S');
        odd01.oddaj('i');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd10.oddaj('M');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd12.oddaj('g');
        odd07.oddaj('r');
        odd15.oddaj('t');
        odd02.oddaj('X');
        odd09.oddaj('y');
        odd12.oddaj('V');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd11.oddaj('q');
        odd14.oddaj('t');
        System.out.println(spr00.koliko());
        odd08.oddaj('y');
        odd07.oddaj('Y');
        odd09.oddaj('f');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('k');
        odd08.oddaj('T');
        odd04.oddaj('x');
        odd13.oddaj('l');
        odd14.oddaj('q');
        odd09.oddaj('n');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd13.oddaj('N');
        odd00.oddaj('c');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd04.oddaj('A');
        odd06.oddaj('b');
        odd02.oddaj('T');
        odd13.oddaj('w');
        odd15.oddaj('R');
        odd10.oddaj('U');
        odd07.oddaj('P');
        odd12.oddaj('j');
        odd11.oddaj('k');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd08.oddaj('H');
        odd12.oddaj('Z');
        System.out.println(spr04.koliko());
        odd08.oddaj('e');
        odd02.oddaj('K');
        odd16.oddaj('L');
        odd02.oddaj('t');
        odd13.oddaj('Y');
        odd06.oddaj('S');
        odd01.oddaj('q');
        odd05.oddaj('u');
        odd01.oddaj('Z');
        odd12.oddaj('f');
        odd15.oddaj('w');
        odd09.oddaj('h');
        odd09.oddaj('k');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd05.oddaj('g');
        System.out.println(spr15.koliko());
        odd01.oddaj('Z');
        odd02.oddaj('e');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd06.oddaj('m');
        odd01.oddaj('x');
        odd08.oddaj('c');
        odd16.oddaj('u');
        odd00.oddaj('b');
        odd13.oddaj('b');
        odd08.oddaj('X');
        odd00.oddaj('w');
        odd15.oddaj('p');
        odd15.oddaj('G');
        odd05.oddaj('v');
        odd15.oddaj('l');
        System.out.println(spr14.koliko());
        odd06.oddaj('k');
        odd01.oddaj('V');
        odd14.oddaj('V');
        System.out.println(spr02.koliko());
        odd15.oddaj('I');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('r');
        odd13.oddaj('X');
        odd05.oddaj('b');
        odd14.oddaj('J');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd00.oddaj('v');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd07.oddaj('I');
        odd04.oddaj('T');
        System.out.println(spr09.koliko());
        odd06.oddaj('S');
        System.out.println(spr15.koliko());
        odd02.oddaj('L');
        odd02.oddaj('r');
        odd06.oddaj('r');
        odd13.oddaj('o');
        odd14.oddaj('V');
        System.out.println(spr11.koliko());
        odd05.oddaj('t');
        odd06.oddaj('f');
        odd11.oddaj('i');
        odd01.oddaj('S');
        odd07.oddaj('k');
        odd06.oddaj('G');
        System.out.println(spr13.koliko());
        odd10.oddaj('A');
        odd13.oddaj('e');
        odd10.oddaj('L');
        odd08.oddaj('b');
        odd14.oddaj('d');
        odd16.oddaj('n');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd13.oddaj('t');
        odd03.oddaj('K');
        odd08.oddaj('I');
        odd13.oddaj('p');
        odd12.oddaj('Y');
        odd01.oddaj('b');
        odd10.oddaj('b');
        odd09.oddaj('r');
        odd04.oddaj('Q');
        odd10.oddaj('G');
        odd01.oddaj('d');
        odd15.oddaj('z');
        odd16.oddaj('q');
        odd00.oddaj('B');
        odd03.oddaj('V');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd02.oddaj('k');
        odd15.oddaj('u');
        odd05.oddaj('B');
        odd12.oddaj('d');
        odd15.oddaj('f');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd02.oddaj('V');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd05.oddaj('i');
        odd02.oddaj('r');
        odd16.oddaj('w');
        System.out.println(spr16.koliko());
        odd09.oddaj('Q');
        odd13.oddaj('l');
        odd04.oddaj('L');
        odd04.oddaj('H');
        odd03.oddaj('O');
        odd06.oddaj('P');
        odd14.oddaj('P');
        odd11.oddaj('z');
        odd04.oddaj('T');
        odd12.oddaj('n');
        odd02.oddaj('r');
        odd15.oddaj('Q');
        odd10.oddaj('L');
        odd11.oddaj('N');
        odd15.oddaj('f');
        odd13.oddaj('f');
        System.out.println(spr13.koliko());
        odd10.oddaj('s');
        odd14.oddaj('o');
        System.out.println(spr09.koliko());
        odd04.oddaj('r');
        odd12.oddaj('C');
        odd13.oddaj('x');
        odd14.oddaj('c');
        System.out.println(spr10.koliko());
        System.out.println(spr04.koliko());
        odd03.oddaj('O');
        odd10.oddaj('i');
        odd14.oddaj('E');
        odd10.oddaj('I');
        odd08.oddaj('D');
        odd06.oddaj('Z');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd15.oddaj('N');
    }
}
