
import java.util.*;

public class Test47 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd06);

        odd01.oddaj('c');
        odd09.oddaj('V');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd07.oddaj('e');
        System.out.println(spr14.koliko());
        odd01.oddaj('J');
        odd06.oddaj('s');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd07.oddaj('K');
        odd02.oddaj('M');
        odd07.oddaj('K');
        System.out.println(spr05.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd00.oddaj('E');
        odd05.oddaj('v');
        System.out.println(spr02.koliko());
        odd05.oddaj('h');
        odd00.oddaj('e');
        odd08.oddaj('Y');
        odd08.oddaj('R');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd03.oddaj('n');
        odd07.oddaj('g');
        odd01.oddaj('g');
        System.out.println(spr16.koliko());
        odd04.oddaj('N');
        System.out.println(spr02.koliko());
        odd09.oddaj('t');
        odd08.oddaj('i');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd08.oddaj('C');
        odd06.oddaj('G');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('j');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd09.oddaj('O');
        System.out.println(spr20.koliko());
        odd09.oddaj('A');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd05.oddaj('c');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd04.oddaj('l');
        System.out.println(spr00.koliko());
        odd04.oddaj('u');
        odd08.oddaj('U');
        odd00.oddaj('Q');
        System.out.println(spr09.koliko());
        odd09.oddaj('S');
        odd01.oddaj('R');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd01.oddaj('K');
        odd00.oddaj('a');
        odd04.oddaj('m');
        odd05.oddaj('K');
        odd03.oddaj('A');
        odd05.oddaj('B');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('e');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd00.oddaj('e');
        odd06.oddaj('A');
        odd06.oddaj('r');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('D');
        System.out.println(spr14.koliko());
        odd07.oddaj('p');
        odd01.oddaj('r');
        odd04.oddaj('O');
        odd06.oddaj('p');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        odd02.oddaj('W');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd04.oddaj('L');
        odd01.oddaj('X');
        odd08.oddaj('P');
        odd05.oddaj('e');
        odd02.oddaj('u');
        odd08.oddaj('u');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd08.oddaj('I');
        odd08.oddaj('y');
        odd02.oddaj('x');
        System.out.println(spr00.koliko());
        odd01.oddaj('J');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd09.oddaj('Z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('v');
        odd02.oddaj('M');
        odd07.oddaj('P');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('U');
        odd09.oddaj('c');
        odd01.oddaj('g');
        System.out.println(spr20.koliko());
        odd07.oddaj('m');
        odd01.oddaj('D');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        odd08.oddaj('n');
        odd06.oddaj('o');
        odd07.oddaj('p');
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd09.oddaj('n');
        odd04.oddaj('c');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('Q');
        odd09.oddaj('j');
        odd06.oddaj('b');
        odd02.oddaj('D');
        odd00.oddaj('S');
        odd07.oddaj('F');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd06.oddaj('J');
        odd04.oddaj('J');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd06.oddaj('V');
        odd03.oddaj('V');
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('g');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('O');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd01.oddaj('k');
        odd09.oddaj('k');
        odd05.oddaj('t');
        odd04.oddaj('s');
        System.out.println(spr04.koliko());
        odd00.oddaj('l');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd07.oddaj('Q');
        odd08.oddaj('q');
        odd09.oddaj('M');
        odd08.oddaj('Q');
        System.out.println(spr07.koliko());
        odd01.oddaj('c');
        odd04.oddaj('u');
        odd03.oddaj('M');
        odd03.oddaj('U');
        odd06.oddaj('H');
        odd03.oddaj('E');
        odd03.oddaj('a');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd03.oddaj('t');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd05.oddaj('n');
        odd09.oddaj('y');
        odd09.oddaj('R');
        odd02.oddaj('L');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd00.oddaj('m');
        odd04.oddaj('d');
        odd09.oddaj('e');
        odd06.oddaj('g');
        odd09.oddaj('O');
        odd03.oddaj('O');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('E');
        odd07.oddaj('R');
        System.out.println(spr03.koliko());
        odd04.oddaj('P');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd09.oddaj('x');
        odd03.oddaj('J');
        odd05.oddaj('o');
        odd08.oddaj('L');
        odd09.oddaj('S');
        System.out.println(spr10.koliko());
        odd05.oddaj('a');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('G');
        odd08.oddaj('V');
        odd02.oddaj('P');
        odd00.oddaj('I');
        odd00.oddaj('s');
        odd06.oddaj('V');
        odd02.oddaj('H');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd01.oddaj('H');
        odd00.oddaj('S');
        odd01.oddaj('J');
        odd00.oddaj('p');
        System.out.println(spr08.koliko());
        odd04.oddaj('j');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd05.oddaj('h');
        System.out.println(spr19.koliko());
        odd05.oddaj('u');
        odd07.oddaj('E');
        System.out.println(spr07.koliko());
        odd04.oddaj('M');
        odd04.oddaj('y');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd03.oddaj('z');
        odd03.oddaj('H');
        odd08.oddaj('J');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd01.oddaj('h');
        System.out.println(spr07.koliko());
        odd07.oddaj('A');
        odd05.oddaj('Y');
        odd03.oddaj('f');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('E');
        odd09.oddaj('Y');
        odd09.oddaj('O');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr19.koliko());
        odd07.oddaj('d');
        odd01.oddaj('a');
        odd02.oddaj('p');
        System.out.println(spr02.koliko());
        odd03.oddaj('c');
        System.out.println(spr00.koliko());
        System.out.println(spr12.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd07.oddaj('y');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd02.oddaj('b');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        odd05.oddaj('y');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd09.oddaj('X');
        System.out.println(spr04.koliko());
        odd03.oddaj('L');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd08.oddaj('A');
        System.out.println(spr01.koliko());
        System.out.println(spr05.koliko());
        odd08.oddaj('P');
        odd04.oddaj('U');
        odd00.oddaj('V');
        odd03.oddaj('n');
        System.out.println(spr19.koliko());
        odd09.oddaj('U');
        odd00.oddaj('o');
        odd04.oddaj('q');
        odd05.oddaj('c');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd09.oddaj('p');
        odd02.oddaj('f');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd02.oddaj('f');
        odd02.oddaj('k');
        odd02.oddaj('s');
        odd05.oddaj('Q');
        odd05.oddaj('h');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('X');
        odd01.oddaj('n');
        odd03.oddaj('H');
        System.out.println(spr04.koliko());
        System.out.println(spr00.koliko());
        odd03.oddaj('f');
        odd09.oddaj('E');
        odd01.oddaj('r');
        odd06.oddaj('K');
        odd03.oddaj('i');
        odd07.oddaj('w');
        odd02.oddaj('i');
        odd02.oddaj('q');
        odd07.oddaj('W');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd04.oddaj('B');
        odd04.oddaj('G');
        odd08.oddaj('Z');
        odd05.oddaj('P');
        odd07.oddaj('N');
        odd01.oddaj('c');
        System.out.println(spr20.koliko());
        System.out.println(spr10.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd08.oddaj('x');
        odd01.oddaj('v');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd08.oddaj('w');
        odd00.oddaj('u');
        odd05.oddaj('V');
        odd04.oddaj('I');
        odd01.oddaj('e');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('p');
        odd03.oddaj('N');
        odd04.oddaj('Y');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd05.oddaj('Q');
        odd05.oddaj('N');
        odd08.oddaj('v');
        odd08.oddaj('A');
        odd04.oddaj('x');
        System.out.println(spr09.koliko());
        odd05.oddaj('S');
        odd08.oddaj('A');
        odd06.oddaj('s');
        System.out.println(spr11.koliko());
        odd00.oddaj('l');
        odd05.oddaj('q');
        odd06.oddaj('f');
        odd07.oddaj('B');
        odd09.oddaj('L');
        System.out.println(spr10.koliko());
        odd07.oddaj('m');
        odd05.oddaj('u');
        odd03.oddaj('q');
        odd02.oddaj('R');
        odd08.oddaj('J');
        odd04.oddaj('Y');
        odd01.oddaj('l');
        odd08.oddaj('v');
        odd04.oddaj('R');
        odd02.oddaj('B');
        odd09.oddaj('V');
        System.out.println(spr15.koliko());
        System.out.println(spr00.koliko());
        odd02.oddaj('I');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('t');
        odd01.oddaj('o');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd07.oddaj('r');
        odd01.oddaj('N');
        odd02.oddaj('H');
        System.out.println(spr09.koliko());
        odd09.oddaj('b');
        odd04.oddaj('U');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd05.oddaj('U');
        odd02.oddaj('X');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd09.oddaj('q');
        odd02.oddaj('E');
        odd06.oddaj('D');
        odd06.oddaj('z');
        odd03.oddaj('j');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd04.oddaj('C');
        System.out.println(spr02.koliko());
        odd03.oddaj('b');
        odd00.oddaj('o');
        odd08.oddaj('O');
        odd06.oddaj('l');
        odd09.oddaj('q');
        odd04.oddaj('j');
        odd04.oddaj('K');
        odd06.oddaj('T');
        odd07.oddaj('n');
        System.out.println(spr02.koliko());
        odd02.oddaj('O');
        odd04.oddaj('Y');
        odd00.oddaj('O');
        odd03.oddaj('q');
        System.out.println(spr13.koliko());
        odd01.oddaj('F');
        odd07.oddaj('k');
        System.out.println(spr14.koliko());
        System.out.println(spr03.koliko());
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd04.oddaj('a');
        odd00.oddaj('C');
        odd07.oddaj('f');
        odd00.oddaj('V');
        odd05.oddaj('i');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('e');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd04.oddaj('P');
        System.out.println(spr18.koliko());
        System.out.println(spr11.koliko());
        odd01.oddaj('s');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd04.oddaj('r');
        odd07.oddaj('C');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd03.oddaj('i');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('f');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('v');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd09.oddaj('g');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr19.koliko());
        odd06.oddaj('A');
        odd01.oddaj('R');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd08.oddaj('C');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr20.koliko());
        odd03.oddaj('o');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd09.oddaj('S');
        odd06.oddaj('q');
        odd00.oddaj('G');
        odd00.oddaj('y');
        System.out.println(spr09.koliko());
        odd05.oddaj('N');
        odd03.oddaj('v');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('Y');
        odd06.oddaj('d');
        odd06.oddaj('Q');
        odd09.oddaj('j');
        odd05.oddaj('D');
        odd08.oddaj('K');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('i');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd08.oddaj('j');
        odd05.oddaj('W');
        odd00.oddaj('c');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd05.oddaj('R');
        odd07.oddaj('K');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd07.oddaj('a');
        System.out.println(spr15.koliko());
        odd01.oddaj('m');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr19.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd09.oddaj('P');
        odd05.oddaj('E');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd08.oddaj('E');
        odd06.oddaj('z');
        odd09.oddaj('Y');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('y');
        odd05.oddaj('Z');
        odd09.oddaj('j');
        odd03.oddaj('b');
        odd06.oddaj('w');
        odd06.oddaj('L');
        odd05.oddaj('v');
        odd01.oddaj('U');
        odd06.oddaj('X');
        odd00.oddaj('C');
        System.out.println(spr14.koliko());
        System.out.println(spr20.koliko());
        odd05.oddaj('y');
        odd07.oddaj('l');
        System.out.println(spr10.koliko());
        odd00.oddaj('d');
        System.out.println(spr17.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('E');
        System.out.println(spr06.koliko());
        odd06.oddaj('R');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('T');
        odd06.oddaj('s');
        odd07.oddaj('t');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        System.out.println(spr00.koliko());
        odd00.oddaj('g');
        odd08.oddaj('f');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd05.oddaj('z');
        odd09.oddaj('d');
        odd09.oddaj('Y');
        odd01.oddaj('d');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd00.oddaj('x');
        odd08.oddaj('X');
        System.out.println(spr04.koliko());
        odd02.oddaj('x');
        System.out.println(spr10.koliko());
        odd03.oddaj('e');
        odd00.oddaj('U');
        odd01.oddaj('W');
        odd08.oddaj('i');
        odd06.oddaj('g');
        odd03.oddaj('F');
        odd02.oddaj('e');
        odd03.oddaj('Z');
        odd09.oddaj('I');
        System.out.println(spr08.koliko());
        odd08.oddaj('y');
        System.out.println(spr07.koliko());
        odd02.oddaj('E');
        System.out.println(spr01.koliko());
        System.out.println(spr09.koliko());
        odd09.oddaj('d');
        odd02.oddaj('N');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd03.oddaj('k');
        odd08.oddaj('A');
        odd08.oddaj('v');
        odd08.oddaj('t');
        odd09.oddaj('M');
        System.out.println(spr17.koliko());
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd04.oddaj('J');
        odd03.oddaj('w');
        odd02.oddaj('X');
        odd03.oddaj('e');
        odd08.oddaj('d');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        odd05.oddaj('h');
        odd04.oddaj('i');
        odd08.oddaj('R');
        odd08.oddaj('K');
        odd04.oddaj('J');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd00.oddaj('s');
        odd03.oddaj('c');
        odd04.oddaj('R');
        odd03.oddaj('a');
        odd07.oddaj('Q');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('e');
        odd00.oddaj('z');
        odd04.oddaj('a');
        System.out.println(spr20.koliko());
        odd06.oddaj('F');
        odd05.oddaj('H');
        odd06.oddaj('b');
        odd02.oddaj('k');
        odd07.oddaj('L');
        odd06.oddaj('l');
        odd06.oddaj('b');
        odd03.oddaj('q');
        odd01.oddaj('d');
        odd04.oddaj('x');
        odd01.oddaj('y');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd04.oddaj('B');
        System.out.println(spr15.koliko());
        odd01.oddaj('G');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd02.oddaj('O');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd09.oddaj('o');
        odd04.oddaj('K');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd09.oddaj('A');
        odd04.oddaj('K');
        odd09.oddaj('f');
        odd08.oddaj('P');
        odd01.oddaj('N');
        odd05.oddaj('Y');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd08.oddaj('h');
        odd03.oddaj('M');
        odd01.oddaj('L');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('R');
        odd00.oddaj('a');
        odd07.oddaj('Y');
        odd03.oddaj('V');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('x');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd00.oddaj('D');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('w');
        System.out.println(spr09.koliko());
        odd05.oddaj('h');
        System.out.println(spr03.koliko());
        odd02.oddaj('c');
        odd03.oddaj('a');
        System.out.println(spr14.koliko());
        odd06.oddaj('E');
        odd02.oddaj('R');
        System.out.println(spr01.koliko());
        odd02.oddaj('j');
        odd01.oddaj('O');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('M');
        System.out.println(spr00.koliko());
        odd00.oddaj('v');
        System.out.println(spr12.koliko());
        System.out.println(spr19.koliko());
        odd09.oddaj('P');
        odd09.oddaj('S');
        System.out.println(spr17.koliko());
        odd08.oddaj('N');
        odd08.oddaj('H');
        odd08.oddaj('i');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd03.oddaj('w');
        odd02.oddaj('p');
        System.out.println(spr18.koliko());
        odd04.oddaj('z');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd03.oddaj('f');
        odd02.oddaj('m');
        odd09.oddaj('b');
        odd00.oddaj('l');
        odd04.oddaj('J');
        odd03.oddaj('V');
        odd06.oddaj('P');
        odd04.oddaj('p');
        odd08.oddaj('Z');
        odd03.oddaj('E');
        odd00.oddaj('B');
        odd03.oddaj('G');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd03.oddaj('x');
        odd00.oddaj('o');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('R');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        odd03.oddaj('f');
        odd07.oddaj('X');
        odd07.oddaj('s');
        System.out.println(spr10.koliko());
        odd08.oddaj('i');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('B');
        odd09.oddaj('p');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd08.oddaj('x');
        System.out.println("<" + spr19.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        System.out.println(spr07.koliko());
        odd02.oddaj('j');
        odd02.oddaj('L');
        odd05.oddaj('o');
        odd07.oddaj('B');
        odd06.oddaj('N');
        System.out.println(spr06.koliko());
        System.out.println(spr12.koliko());
        odd09.oddaj('S');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd05.oddaj('l');
        odd00.oddaj('X');
        odd09.oddaj('E');
        odd00.oddaj('h');
        odd03.oddaj('l');
        odd04.oddaj('M');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd00.oddaj('b');
        odd02.oddaj('N');
        System.out.println(spr00.koliko());
        odd08.oddaj('A');
        odd01.oddaj('k');
        odd02.oddaj('x');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd04.oddaj('s');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd01.oddaj('N');
        odd03.oddaj('x');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd00.oddaj('p');
        odd02.oddaj('L');
        System.out.println(spr09.koliko());
        odd00.oddaj('m');
        odd06.oddaj('X');
        odd02.oddaj('n');
        odd01.oddaj('B');
        odd04.oddaj('T');
        System.out.println(spr03.koliko());
        odd06.oddaj('h');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        System.out.println(spr09.koliko());
        odd07.oddaj('P');
        odd04.oddaj('E');
        odd06.oddaj('M');
        odd01.oddaj('c');
        odd03.oddaj('P');
        odd05.oddaj('C');
        odd00.oddaj('x');
        odd04.oddaj('Y');
        odd01.oddaj('q');
        odd00.oddaj('x');
        System.out.println(spr10.koliko());
        odd00.oddaj('q');
        odd06.oddaj('d');
        System.out.println(spr16.koliko());
        odd08.oddaj('N');
        odd08.oddaj('t');
        System.out.println(spr02.koliko());
        odd07.oddaj('c');
        odd04.oddaj('O');
        odd09.oddaj('t');
        odd06.oddaj('k');
        odd02.oddaj('E');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        System.out.println(spr19.koliko());
        odd03.oddaj('d');
        odd05.oddaj('G');
        odd04.oddaj('z');
        odd05.oddaj('p');
        odd08.oddaj('I');
        odd07.oddaj('C');
        odd08.oddaj('s');
        System.out.println(spr03.koliko());
        odd07.oddaj('s');
        odd00.oddaj('m');
        odd09.oddaj('E');
        odd04.oddaj('y');
        System.out.println(spr13.koliko());
        odd06.oddaj('y');
        odd00.oddaj('G');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd02.oddaj('r');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd08.oddaj('U');
        odd05.oddaj('k');
        System.out.println(spr05.koliko());
        odd04.oddaj('Q');
        odd09.oddaj('u');
        System.out.println(spr04.koliko());
        odd07.oddaj('j');
        odd02.oddaj('p');
        System.out.println(spr02.koliko());
        odd05.oddaj('K');
        odd08.oddaj('D');
        System.out.println(spr18.koliko());
        odd04.oddaj('d');
        System.out.println(spr19.koliko());
        System.out.println(spr01.koliko());
        odd00.oddaj('y');
        odd06.oddaj('x');
        System.out.println(spr20.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd03.oddaj('e');
        System.out.println(spr12.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('Y');
        System.out.println(spr01.koliko());
        System.out.println(spr00.koliko());
        odd01.oddaj('b');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('k');
        odd08.oddaj('y');
        odd01.oddaj('s');
        odd04.oddaj('a');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd06.oddaj('Z');
        odd04.oddaj('c');
        odd03.oddaj('e');
        odd03.oddaj('J');
        System.out.println(spr07.koliko());
        System.out.println(spr13.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('H');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd02.oddaj('r');
        System.out.println(spr05.koliko());
        System.out.println(spr17.koliko());
        odd08.oddaj('o');
        odd02.oddaj('b');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd06.oddaj('w');
        odd07.oddaj('q');
        System.out.println(spr08.koliko());
        System.out.println(spr15.koliko());
        odd04.oddaj('N');
        odd09.oddaj('Z');
        odd03.oddaj('D');
        odd05.oddaj('J');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd09.oddaj('d');
        odd05.oddaj('Q');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('J');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd00.oddaj('q');
        odd07.oddaj('q');
        odd02.oddaj('p');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('R');
        odd09.oddaj('x');
        System.out.println(spr18.koliko());
        odd03.oddaj('a');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('P');
    }
}
