
import java.util.*;

public class Test37 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd13);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd05);

        odd04.oddaj('K');
        odd05.oddaj('W');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('P');
        odd08.oddaj('T');
        odd12.oddaj('r');
        odd04.oddaj('x');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd07.oddaj('C');
        odd10.oddaj('H');
        odd08.oddaj('P');
        odd10.oddaj('W');
        odd04.oddaj('d');
        odd07.oddaj('p');
        odd08.oddaj('Y');
        odd04.oddaj('x');
        odd12.oddaj('e');
        odd02.oddaj('H');
        odd01.oddaj('Z');
        odd10.oddaj('E');
        odd03.oddaj('y');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd09.oddaj('H');
        odd13.oddaj('T');
        odd03.oddaj('x');
        odd06.oddaj('m');
        odd10.oddaj('Q');
        odd03.oddaj('Q');
        odd07.oddaj('f');
        odd12.oddaj('L');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('l');
        odd01.oddaj('k');
        odd05.oddaj('X');
        System.out.println(spr04.koliko());
        odd08.oddaj('y');
        odd01.oddaj('Q');
        odd03.oddaj('g');
        System.out.println(spr11.koliko());
        System.out.println(spr02.koliko());
        odd04.oddaj('H');
        odd13.oddaj('X');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('Q');
        odd09.oddaj('U');
        System.out.println(spr04.koliko());
        odd05.oddaj('S');
        odd06.oddaj('s');
        odd05.oddaj('P');
        odd01.oddaj('H');
        odd11.oddaj('p');
        odd04.oddaj('L');
        System.out.println(spr11.koliko());
        odd00.oddaj('F');
        System.out.println(spr03.koliko());
        odd01.oddaj('i');
        System.out.println(spr12.koliko());
        odd08.oddaj('Q');
        odd00.oddaj('F');
        odd12.oddaj('t');
        odd08.oddaj('b');
        odd00.oddaj('q');
        odd04.oddaj('t');
        odd01.oddaj('i');
        odd03.oddaj('c');
        odd01.oddaj('w');
        odd02.oddaj('A');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd00.oddaj('W');
        odd01.oddaj('Z');
        System.out.println(spr12.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('A');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('Y');
        odd00.oddaj('k');
        odd05.oddaj('V');
        odd04.oddaj('I');
        odd05.oddaj('G');
        System.out.println(spr06.koliko());
        odd09.oddaj('B');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd05.oddaj('y');
        odd04.oddaj('Z');
        System.out.println(spr05.koliko());
        odd04.oddaj('q');
        odd13.oddaj('G');
        odd01.oddaj('z');
        odd04.oddaj('O');
        System.out.println(spr11.koliko());
        odd07.oddaj('H');
        odd05.oddaj('H');
        odd04.oddaj('o');
        odd13.oddaj('t');
        odd12.oddaj('E');
        odd03.oddaj('A');
        odd04.oddaj('n');
        odd07.oddaj('a');
        odd09.oddaj('C');
        odd03.oddaj('o');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd10.oddaj('K');
        odd09.oddaj('T');
        odd00.oddaj('P');
        odd01.oddaj('Y');
        odd07.oddaj('U');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd11.oddaj('o');
        odd01.oddaj('q');
        odd08.oddaj('Q');
        odd02.oddaj('c');
        System.out.println(spr02.koliko());
        odd01.oddaj('R');
        odd12.oddaj('K');
        odd12.oddaj('e');
        System.out.println(spr04.koliko());
        odd04.oddaj('Z');
        odd05.oddaj('y');
        odd10.oddaj('A');
        odd08.oddaj('Z');
        odd03.oddaj('v');
        System.out.println(spr14.koliko());
        odd00.oddaj('t');
        odd02.oddaj('i');
        odd02.oddaj('V');
        odd00.oddaj('H');
        odd13.oddaj('B');
        System.out.println(spr01.koliko());
        odd05.oddaj('q');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd09.oddaj('L');
        odd09.oddaj('R');
        odd02.oddaj('E');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd08.oddaj('d');
        odd09.oddaj('Z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('Z');
        odd04.oddaj('g');
        odd05.oddaj('X');
        odd05.oddaj('i');
        System.out.println(spr03.koliko());
        odd00.oddaj('w');
        odd10.oddaj('J');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd11.oddaj('k');
        System.out.println(spr02.koliko());
        odd06.oddaj('V');
        odd06.oddaj('A');
        odd10.oddaj('v');
        odd07.oddaj('D');
        odd00.oddaj('H');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd11.oddaj('E');
        odd05.oddaj('p');
        odd09.oddaj('j');
        odd08.oddaj('Z');
        odd11.oddaj('X');
        odd06.oddaj('C');
        odd03.oddaj('l');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd06.oddaj('f');
        odd03.oddaj('q');
        odd00.oddaj('b');
        odd00.oddaj('o');
        odd02.oddaj('b');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('l');
        odd00.oddaj('y');
        System.out.println(spr04.koliko());
        System.out.println(spr13.koliko());
        odd13.oddaj('X');
        odd08.oddaj('T');
        odd09.oddaj('r');
        odd06.oddaj('T');
        odd12.oddaj('m');
        System.out.println(spr14.koliko());
        odd01.oddaj('Z');
        odd11.oddaj('A');
        odd12.oddaj('s');
        odd06.oddaj('n');
        odd08.oddaj('A');
        odd06.oddaj('n');
        odd05.oddaj('x');
        odd10.oddaj('P');
        odd09.oddaj('B');
        odd13.oddaj('F');
        odd01.oddaj('T');
        odd02.oddaj('w');
        System.out.println(spr08.koliko());
        odd03.oddaj('R');
        odd11.oddaj('W');
        odd13.oddaj('e');
        System.out.println(spr04.koliko());
        odd00.oddaj('d');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('d');
        odd10.oddaj('t');
        odd13.oddaj('Y');
        odd08.oddaj('A');
        odd05.oddaj('r');
        odd11.oddaj('m');
        odd13.oddaj('G');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd00.oddaj('E');
        odd00.oddaj('l');
        odd12.oddaj('i');
        odd08.oddaj('w');
        odd04.oddaj('C');
        odd01.oddaj('x');
        System.out.println(spr04.koliko());
        odd01.oddaj('U');
        odd08.oddaj('l');
        odd00.oddaj('l');
        odd03.oddaj('y');
        System.out.println(spr13.koliko());
        System.out.println(spr02.koliko());
        System.out.println(spr06.koliko());
        odd05.oddaj('F');
        odd05.oddaj('p');
        odd03.oddaj('O');
        odd03.oddaj('i');
        odd08.oddaj('s');
        odd10.oddaj('s');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('c');
        odd03.oddaj('s');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('s');
        odd12.oddaj('w');
        odd11.oddaj('y');
        System.out.println(spr12.koliko());
        odd00.oddaj('h');
        odd08.oddaj('A');
        odd10.oddaj('C');
        odd03.oddaj('o');
        odd03.oddaj('L');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd12.oddaj('t');
        System.out.println(spr10.koliko());
        odd10.oddaj('E');
        odd04.oddaj('R');
        odd09.oddaj('B');
        System.out.println(spr05.koliko());
        odd03.oddaj('U');
        odd00.oddaj('R');
        odd08.oddaj('u');
        odd07.oddaj('j');
        odd13.oddaj('k');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd12.oddaj('s');
        odd06.oddaj('d');
        odd10.oddaj('h');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd05.oddaj('m');
        odd07.oddaj('S');
        odd08.oddaj('L');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd05.oddaj('A');
        odd07.oddaj('e');
        odd02.oddaj('H');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('z');
        odd11.oddaj('P');
        odd09.oddaj('o');
        System.out.println(spr09.koliko());
        odd05.oddaj('r');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        odd06.oddaj('M');
        odd08.oddaj('Y');
        odd01.oddaj('n');
        odd03.oddaj('k');
        odd09.oddaj('H');
        odd12.oddaj('l');
        odd12.oddaj('U');
        odd05.oddaj('b');
        odd10.oddaj('O');
        odd12.oddaj('f');
        odd12.oddaj('b');
        odd03.oddaj('s');
        odd08.oddaj('R');
        odd02.oddaj('D');
        odd04.oddaj('M');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd12.oddaj('f');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd06.oddaj('v');
        odd06.oddaj('B');
        odd08.oddaj('X');
        odd02.oddaj('n');
        odd07.oddaj('V');
        odd06.oddaj('L');
        odd09.oddaj('p');
        odd07.oddaj('h');
        odd05.oddaj('C');
        odd05.oddaj('L');
        odd11.oddaj('j');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd07.oddaj('Q');
        odd06.oddaj('j');
        System.out.println(spr03.koliko());
        odd05.oddaj('M');
        odd10.oddaj('n');
        odd12.oddaj('j');
        odd01.oddaj('f');
        odd04.oddaj('A');
        odd12.oddaj('b');
        odd06.oddaj('L');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd12.oddaj('E');
        odd11.oddaj('v');
        System.out.println(spr12.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd10.oddaj('B');
        odd06.oddaj('P');
        odd04.oddaj('U');
        odd08.oddaj('M');
        System.out.println(spr13.koliko());
        odd05.oddaj('w');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd11.oddaj('u');
        odd00.oddaj('Q');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd02.oddaj('J');
        odd07.oddaj('q');
        odd07.oddaj('E');
        odd10.oddaj('e');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd00.oddaj('X');
        odd10.oddaj('X');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('H');
        System.out.println(spr03.koliko());
        odd11.oddaj('w');
        odd13.oddaj('l');
        odd12.oddaj('r');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd07.oddaj('h');
        System.out.println(spr12.koliko());
        odd11.oddaj('f');
        odd11.oddaj('d');
        odd06.oddaj('a');
        System.out.println(spr02.koliko());
        System.out.println(spr04.koliko());
        odd11.oddaj('z');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('o');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd13.oddaj('d');
        odd09.oddaj('A');
        odd12.oddaj('T');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd11.oddaj('z');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd07.oddaj('N');
        odd13.oddaj('B');
        odd07.oddaj('G');
        odd12.oddaj('M');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('I');
        odd12.oddaj('l');
        odd09.oddaj('F');
        odd03.oddaj('q');
        odd12.oddaj('q');
        odd05.oddaj('J');
        System.out.println(spr14.koliko());
        odd13.oddaj('k');
        odd07.oddaj('r');
        odd02.oddaj('h');
        odd11.oddaj('k');
        odd11.oddaj('A');
        odd10.oddaj('D');
        odd06.oddaj('V');
        odd05.oddaj('q');
        odd04.oddaj('w');
        odd06.oddaj('Y');
        odd06.oddaj('M');
        odd01.oddaj('h');
        odd13.oddaj('u');
        System.out.println(spr06.koliko());
        odd01.oddaj('X');
        odd05.oddaj('g');
        System.out.println(spr08.koliko());
        odd10.oddaj('b');
        odd02.oddaj('U');
        odd06.oddaj('H');
        odd11.oddaj('t');
        System.out.println(spr10.koliko());
        odd02.oddaj('s');
        odd10.oddaj('u');
        odd06.oddaj('L');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('x');
        odd09.oddaj('b');
        odd12.oddaj('U');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd12.oddaj('s');
        odd01.oddaj('b');
        System.out.println(spr02.koliko());
        odd04.oddaj('K');
        odd05.oddaj('F');
        odd11.oddaj('l');
        odd01.oddaj('S');
        odd06.oddaj('t');
        odd13.oddaj('e');
        odd06.oddaj('s');
        odd02.oddaj('E');
        odd11.oddaj('V');
        odd09.oddaj('O');
        odd12.oddaj('S');
        odd11.oddaj('f');
        odd11.oddaj('C');
        odd08.oddaj('P');
        odd09.oddaj('U');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd08.oddaj('D');
        odd12.oddaj('E');
        odd01.oddaj('M');
        odd06.oddaj('R');
        odd07.oddaj('P');
        odd04.oddaj('C');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd01.oddaj('v');
        odd09.oddaj('w');
        odd10.oddaj('j');
        odd02.oddaj('d');
        odd05.oddaj('d');
        odd10.oddaj('I');
        odd01.oddaj('a');
        odd08.oddaj('C');
        odd11.oddaj('p');
        odd01.oddaj('H');
        odd01.oddaj('Y');
        System.out.println(spr01.koliko());
        odd00.oddaj('Y');
        odd08.oddaj('u');
        odd01.oddaj('i');
        odd08.oddaj('T');
        odd03.oddaj('t');
        odd01.oddaj('h');
        odd11.oddaj('y');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd09.oddaj('A');
        System.out.println(spr05.koliko());
        System.out.println(spr11.koliko());
        odd06.oddaj('A');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd08.oddaj('r');
        odd06.oddaj('o');
        odd13.oddaj('e');
        odd06.oddaj('B');
        odd03.oddaj('A');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('V');
        odd02.oddaj('M');
        odd11.oddaj('h');
        odd11.oddaj('a');
        odd06.oddaj('w');
        odd11.oddaj('J');
        odd12.oddaj('e');
        odd08.oddaj('r');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('T');
        System.out.println(spr05.koliko());
        odd10.oddaj('Q');
        odd02.oddaj('u');
        odd03.oddaj('Y');
        odd02.oddaj('S');
        odd11.oddaj('U');
        odd05.oddaj('e');
        odd10.oddaj('c');
        odd06.oddaj('N');
        odd10.oddaj('O');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd12.oddaj('U');
        odd06.oddaj('C');
        odd03.oddaj('F');
        odd12.oddaj('j');
        odd13.oddaj('J');
        odd11.oddaj('E');
        odd13.oddaj('s');
        odd09.oddaj('P');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd08.oddaj('F');
        odd03.oddaj('q');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('X');
        odd07.oddaj('P');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd01.oddaj('G');
        odd10.oddaj('q');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('y');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd05.oddaj('T');
        System.out.println(spr06.koliko());
        odd09.oddaj('v');
        odd06.oddaj('B');
        odd01.oddaj('h');
        System.out.println(spr13.koliko());
        System.out.println(spr05.koliko());
        odd00.oddaj('w');
        odd00.oddaj('o');
        odd03.oddaj('X');
        odd09.oddaj('n');
        System.out.println(spr11.koliko());
        odd13.oddaj('s');
        odd10.oddaj('z');
        odd03.oddaj('R');
        odd10.oddaj('T');
        odd05.oddaj('u');
        odd05.oddaj('R');
        odd00.oddaj('W');
        odd07.oddaj('I');
        System.out.println(spr00.koliko());
        odd09.oddaj('k');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('p');
        odd13.oddaj('l');
        odd08.oddaj('c');
        odd12.oddaj('r');
        System.out.println(spr02.koliko());
        odd04.oddaj('M');
        odd02.oddaj('l');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('F');
        odd12.oddaj('s');
        odd00.oddaj('L');
        odd01.oddaj('p');
        odd13.oddaj('X');
        odd12.oddaj('L');
        odd00.oddaj('a');
        odd04.oddaj('n');
        odd02.oddaj('A');
        odd01.oddaj('q');
        odd03.oddaj('F');
        odd06.oddaj('V');
        odd13.oddaj('e');
        odd05.oddaj('z');
        odd07.oddaj('p');
        odd08.oddaj('F');
        odd13.oddaj('T');
        odd00.oddaj('M');
        odd11.oddaj('M');
        odd04.oddaj('Z');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd12.oddaj('R');
        System.out.println(spr08.koliko());
        System.out.println(spr01.koliko());
        odd07.oddaj('P');
        System.out.println(spr05.koliko());
        odd07.oddaj('k');
        odd07.oddaj('f');
        System.out.println(spr07.koliko());
        odd06.oddaj('E');
        odd03.oddaj('e');
        odd06.oddaj('J');
        odd07.oddaj('Y');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd12.oddaj('j');
        odd12.oddaj('f');
        odd12.oddaj('K');
        System.out.println(spr03.koliko());
        odd10.oddaj('m');
        System.out.println(spr04.koliko());
        odd02.oddaj('q');
        odd10.oddaj('j');
        odd01.oddaj('R');
        odd01.oddaj('g');
        odd09.oddaj('v');
        odd02.oddaj('W');
        odd05.oddaj('o');
        odd03.oddaj('Y');
        odd05.oddaj('g');
        odd12.oddaj('t');
        odd12.oddaj('z');
        odd10.oddaj('W');
        odd03.oddaj('T');
        odd12.oddaj('V');
        odd12.oddaj('o');
        odd00.oddaj('u');
        System.out.println(spr13.koliko());
        odd09.oddaj('b');
        odd12.oddaj('T');
        odd06.oddaj('T');
        System.out.println(spr07.koliko());
        odd10.oddaj('J');
        odd10.oddaj('J');
        odd09.oddaj('Q');
        odd03.oddaj('l');
        odd01.oddaj('O');
        odd05.oddaj('I');
        odd10.oddaj('g');
        odd03.oddaj('T');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('O');
        odd02.oddaj('F');
        odd02.oddaj('o');
        System.out.println(spr14.koliko());
        odd07.oddaj('r');
        System.out.println(spr06.koliko());
        odd06.oddaj('T');
        odd05.oddaj('e');
        System.out.println(spr05.koliko());
        odd13.oddaj('g');
        odd12.oddaj('N');
        odd09.oddaj('U');
        odd02.oddaj('y');
        odd04.oddaj('c');
        odd03.oddaj('E');
        odd01.oddaj('k');
        odd13.oddaj('X');
        odd03.oddaj('C');
        odd00.oddaj('e');
        System.out.println(spr02.koliko());
        odd07.oddaj('w');
        odd07.oddaj('x');
        odd13.oddaj('U');
        System.out.println(spr07.koliko());
        odd05.oddaj('l');
        System.out.println(spr11.koliko());
        odd03.oddaj('C');
        odd09.oddaj('R');
        odd02.oddaj('i');
        odd04.oddaj('A');
        odd00.oddaj('n');
        odd07.oddaj('h');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('r');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd13.oddaj('M');
        odd03.oddaj('n');
        odd06.oddaj('D');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd05.oddaj('t');
        odd13.oddaj('P');
        odd08.oddaj('F');
        odd03.oddaj('G');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd11.oddaj('Y');
        odd03.oddaj('w');
    }
}
