
import java.util.*;

public class Test29 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);

        odd01.oddaj('C');
        odd04.oddaj('j');
        odd03.oddaj('i');
        odd00.oddaj('s');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd03.oddaj('k');
        odd01.oddaj('A');
        System.out.println(spr03.koliko());
        odd01.oddaj('m');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('C');
        System.out.println(spr02.koliko());
        odd00.oddaj('c');
        odd04.oddaj('O');
        odd04.oddaj('P');
        odd01.oddaj('q');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('C');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('b');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('P');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd02.oddaj('b');
        odd01.oddaj('g');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd03.oddaj('E');
        odd04.oddaj('E');
        odd03.oddaj('F');
        odd00.oddaj('z');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd00.oddaj('m');
        odd02.oddaj('x');
        odd02.oddaj('D');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('r');
        odd01.oddaj('j');
        odd02.oddaj('U');
        System.out.println(spr01.koliko());
        odd02.oddaj('Y');
        odd03.oddaj('u');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('k');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('d');
        System.out.println(spr01.koliko());
        odd02.oddaj('c');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('R');
        odd00.oddaj('B');
        odd01.oddaj('G');
        System.out.println(spr02.koliko());
        System.out.println(spr00.koliko());
        odd03.oddaj('k');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('u');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('S');
        odd04.oddaj('b');
        odd03.oddaj('t');
        odd03.oddaj('O');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('m');
        System.out.println(spr04.koliko());
        System.out.println(spr03.koliko());
        odd03.oddaj('h');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('h');
        odd02.oddaj('D');
        odd04.oddaj('w');
        odd01.oddaj('F');
        odd03.oddaj('V');
        odd01.oddaj('G');
        odd04.oddaj('d');
        odd02.oddaj('q');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('n');
        System.out.println(spr04.koliko());
        odd01.oddaj('z');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd04.oddaj('D');
        odd00.oddaj('N');
        odd02.oddaj('l');
        odd01.oddaj('V');
        odd04.oddaj('A');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('X');
        System.out.println(spr02.koliko());
        odd03.oddaj('Q');
        odd04.oddaj('K');
        odd00.oddaj('p');
        System.out.println(spr04.koliko());
        odd02.oddaj('q');
        odd02.oddaj('R');
        odd01.oddaj('m');
        odd00.oddaj('G');
        odd04.oddaj('M');
        odd00.oddaj('Q');
        System.out.println(spr00.koliko());
        odd03.oddaj('y');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('p');
        odd02.oddaj('Q');
        odd01.oddaj('N');
        odd00.oddaj('o');
        odd01.oddaj('r');
        odd00.oddaj('y');
        System.out.println(spr01.koliko());
        odd04.oddaj('J');
        odd04.oddaj('H');
        odd00.oddaj('r');
        odd03.oddaj('q');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd00.oddaj('l');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('x');
        System.out.println(spr00.koliko());
        odd02.oddaj('v');
        odd04.oddaj('c');
        odd02.oddaj('X');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('Q');
        System.out.println(spr00.koliko());
        odd00.oddaj('a');
        System.out.println(spr00.koliko());
        odd04.oddaj('T');
        odd00.oddaj('x');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('o');
        odd03.oddaj('N');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd00.oddaj('q');
        System.out.println(spr00.koliko());
        odd01.oddaj('P');
        System.out.println(spr01.koliko());
        odd02.oddaj('N');
        odd04.oddaj('R');
        odd01.oddaj('n');
        odd03.oddaj('w');
        System.out.println(spr01.koliko());
        odd01.oddaj('C');
        odd04.oddaj('m');
        odd02.oddaj('V');
        System.out.println(spr02.koliko());
        System.out.println(spr03.koliko());
        odd02.oddaj('Y');
        odd04.oddaj('m');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('O');
        odd00.oddaj('S');
        odd00.oddaj('Q');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('E');
        odd01.oddaj('f');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('f');
        System.out.println(spr01.koliko());
        odd04.oddaj('d');
        System.out.println(spr04.koliko());
        odd01.oddaj('m');
        odd00.oddaj('o');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('l');
        odd00.oddaj('N');
        System.out.println(spr03.koliko());
        odd00.oddaj('Y');
        System.out.println(spr00.koliko());
        odd02.oddaj('B');
        System.out.println(spr02.koliko());
        odd03.oddaj('S');
        odd04.oddaj('T');
        odd04.oddaj('I');
        odd01.oddaj('n');
        odd02.oddaj('J');
        odd00.oddaj('k');
        odd04.oddaj('I');
        System.out.println(spr03.koliko());
        System.out.println(spr02.koliko());
        odd00.oddaj('b');
        System.out.println(spr00.koliko());
        odd00.oddaj('x');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('w');
        odd01.oddaj('s');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('O');
        System.out.println(spr02.koliko());
        odd00.oddaj('D');
        odd04.oddaj('V');
        odd00.oddaj('U');
        odd03.oddaj('J');
        odd01.oddaj('s');
        odd01.oddaj('Z');
        odd00.oddaj('e');
        System.out.println(spr00.koliko());
        System.out.println(spr01.koliko());
        odd00.oddaj('Y');
        odd04.oddaj('u');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd02.oddaj('x');
        System.out.println(spr03.koliko());
        System.out.println(spr02.koliko());
        odd02.oddaj('w');
        odd00.oddaj('y');
        odd03.oddaj('t');
        odd00.oddaj('B');
        odd04.oddaj('r');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('H');
        odd00.oddaj('N');
        odd00.oddaj('H');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('I');
        System.out.println(spr02.koliko());
        odd03.oddaj('M');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('e');
        odd03.oddaj('M');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('i');
        odd01.oddaj('H');
        odd02.oddaj('c');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('I');
        odd00.oddaj('H');
        System.out.println(spr00.koliko());
        odd04.oddaj('z');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('L');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('k');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('W');
        odd04.oddaj('n');
        odd00.oddaj('a');
        odd02.oddaj('Q');
        odd04.oddaj('j');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd03.oddaj('o');
        odd02.oddaj('S');
        System.out.println(spr03.koliko());
        odd01.oddaj('q');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('l');
        odd03.oddaj('g');
        odd04.oddaj('I');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('P');
        odd04.oddaj('S');
        System.out.println(spr01.koliko());
        System.out.println(spr03.koliko());
        System.out.println(spr04.koliko());
        odd04.oddaj('a');
        odd04.oddaj('p');
        odd01.oddaj('R');
        odd04.oddaj('B');
        odd04.oddaj('u');
        System.out.println(spr01.koliko());
        odd03.oddaj('b');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd02.oddaj('t');
        odd04.oddaj('P');
        odd00.oddaj('Q');
        odd00.oddaj('Z');
        odd03.oddaj('g');
        odd00.oddaj('v');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd01.oddaj('G');
        odd02.oddaj('X');
        odd01.oddaj('c');
        odd03.oddaj('a');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('F');
        odd03.oddaj('V');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('o');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('o');
        odd01.oddaj('Z');
        odd03.oddaj('t');
        System.out.println(spr01.koliko());
        odd01.oddaj('V');
        System.out.println(spr02.koliko());
        odd00.oddaj('H');
        System.out.println(spr00.koliko());
        odd02.oddaj('k');
        odd04.oddaj('M');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('j');
        odd00.oddaj('e');
        odd01.oddaj('G');
        odd01.oddaj('M');
        odd01.oddaj('R');
        System.out.println(spr01.koliko());
        odd01.oddaj('T');
        odd00.oddaj('t');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('U');
        System.out.println(spr00.koliko());
        odd02.oddaj('z');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('t');
        odd02.oddaj('f');
        odd03.oddaj('F');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd04.oddaj('K');
        System.out.println(spr04.koliko());
        odd01.oddaj('H');
        System.out.println(spr01.koliko());
        odd03.oddaj('R');
        System.out.println(spr03.koliko());
        odd02.oddaj('S');
        odd00.oddaj('J');
        odd01.oddaj('v');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('a');
        odd04.oddaj('Y');
        odd03.oddaj('X');
        odd04.oddaj('S');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('u');
        odd03.oddaj('V');
        odd04.oddaj('v');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('A');
        odd02.oddaj('U');
        System.out.println(spr01.koliko());
        odd00.oddaj('I');
        odd00.oddaj('Z');
        odd01.oddaj('I');
        odd01.oddaj('B');
        odd01.oddaj('t');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('F');
        odd02.oddaj('K');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd04.oddaj('t');
        odd01.oddaj('D');
        odd01.oddaj('R');
        System.out.println(spr01.koliko());
        odd03.oddaj('K');
        odd01.oddaj('S');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('u');
        odd01.oddaj('s');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd04.oddaj('j');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('l');
        odd01.oddaj('S');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('z');
        System.out.println(spr04.koliko());
        odd04.oddaj('u');
        odd00.oddaj('A');
        odd03.oddaj('G');
        odd01.oddaj('w');
        odd02.oddaj('g');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('A');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd01.oddaj('T');
        odd02.oddaj('A');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('O');
        System.out.println(spr02.koliko());
        odd03.oddaj('h');
        odd01.oddaj('F');
        odd03.oddaj('a');
        odd04.oddaj('q');
        odd01.oddaj('Z');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('b');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('i');
        System.out.println(spr02.koliko());
        odd01.oddaj('N');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('b');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('d');
        odd01.oddaj('Z');
        System.out.println(spr01.koliko());
        odd00.oddaj('i');
        odd02.oddaj('f');
        System.out.println(spr02.koliko());
        System.out.println(spr00.koliko());
        odd02.oddaj('P');
        odd01.oddaj('V');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('j');
        odd04.oddaj('C');
        odd01.oddaj('h');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('c');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('u');
        odd02.oddaj('Q');
        System.out.println(spr00.koliko());
        odd02.oddaj('O');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd03.oddaj('j');
        odd03.oddaj('s');
        odd01.oddaj('p');
        odd03.oddaj('c');
        odd02.oddaj('F');
        odd01.oddaj('j');
        odd01.oddaj('B');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('y');
        odd02.oddaj('D');
        odd01.oddaj('Q');
        System.out.println(spr02.koliko());
        System.out.println(spr01.koliko());
        odd04.oddaj('v');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd01.oddaj('j');
        System.out.println(spr01.koliko());
        odd02.oddaj('r');
        odd03.oddaj('t');
        odd04.oddaj('A');
        odd03.oddaj('y');
        odd00.oddaj('K');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('i');
        System.out.println(spr02.koliko());
        System.out.println(spr03.koliko());
        odd02.oddaj('X');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('i');
        odd00.oddaj('i');
        odd03.oddaj('h');
        odd00.oddaj('M');
        odd01.oddaj('v');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('t');
        odd03.oddaj('X');
        odd01.oddaj('O');
        System.out.println(spr02.koliko());
        odd01.oddaj('q');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('G');
        odd00.oddaj('D');
        odd01.oddaj('n');
        odd01.oddaj('f');
        odd01.oddaj('D');
        odd04.oddaj('j');
        odd02.oddaj('U');
        System.out.println(spr02.koliko());
        odd03.oddaj('J');
        odd04.oddaj('h');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('x');
        odd03.oddaj('g');
        odd03.oddaj('E');
        odd00.oddaj('X');
        odd01.oddaj('V');
        System.out.println(spr04.koliko());
        odd00.oddaj('w');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('G');
        odd03.oddaj('U');
        odd04.oddaj('z');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd03.oddaj('x');
        odd04.oddaj('T');
        odd02.oddaj('z');
        odd01.oddaj('R');
        odd00.oddaj('k');
        odd04.oddaj('t');
        odd01.oddaj('o');
        odd03.oddaj('U');
        odd02.oddaj('X');
        odd03.oddaj('Q');
        odd00.oddaj('n');
        System.out.println(spr04.koliko());
        odd02.oddaj('e');
        odd04.oddaj('E');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('t');
        odd02.oddaj('Q');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd00.oddaj('X');
        odd03.oddaj('N');
        System.out.println(spr04.koliko());
        odd02.oddaj('R');
        odd00.oddaj('y');
        odd04.oddaj('d');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('l');
        odd01.oddaj('m');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('s');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('L');
        odd02.oddaj('f');
        odd02.oddaj('b');
        odd00.oddaj('m');
        odd00.oddaj('O');
        odd03.oddaj('k');
        System.out.println(spr02.koliko());
        System.out.println(spr00.koliko());
        odd04.oddaj('x');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('U');
        odd00.oddaj('i');
        odd04.oddaj('m');
        odd03.oddaj('O');
        System.out.println(spr01.koliko());
        odd02.oddaj('F');
        odd01.oddaj('N');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd02.oddaj('W');
        odd01.oddaj('D');
        System.out.println(spr04.koliko());
        odd03.oddaj('H');
    }
}
