
import java.util.*;

public class Test38 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr22 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr23 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr24 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr25 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr26 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr27 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr28 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr29 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr30 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr31 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr32 = new Tretja.Sprejemnik(odd03);

        odd06.oddaj('W');
        odd01.oddaj('G');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr27.koliko());
        odd04.oddaj('f');
        odd03.oddaj('o');
        odd00.oddaj('h');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('s');
        odd06.oddaj('l');
        odd01.oddaj('w');
        System.out.println(spr23.koliko());
        odd05.oddaj('H');
        odd04.oddaj('I');
        odd01.oddaj('X');
        odd06.oddaj('l');
        odd06.oddaj('M');
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd07.oddaj('h');
        odd03.oddaj('G');
        odd02.oddaj('N');
        odd01.oddaj('z');
        odd00.oddaj('B');
        odd01.oddaj('U');
        odd03.oddaj('d');
        System.out.println(spr22.koliko());
        odd00.oddaj('T');
        odd07.oddaj('u');
        odd05.oddaj('v');
        odd04.oddaj('d');
        odd04.oddaj('k');
        System.out.println(spr06.koliko());
        odd08.oddaj('M');
        odd02.oddaj('t');
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd02.oddaj('a');
        System.out.println(spr26.koliko());
        odd02.oddaj('Q');
        odd00.oddaj('d');
        odd03.oddaj('X');
        System.out.println(spr24.koliko());
        odd02.oddaj('j');
        odd04.oddaj('D');
        odd02.oddaj('X');
        System.out.println(spr26.koliko());
        odd00.oddaj('t');
        odd02.oddaj('x');
        odd00.oddaj('B');
        odd03.oddaj('y');
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd08.oddaj('W');
        odd01.oddaj('E');
        odd01.oddaj('g');
        odd03.oddaj('y');
        System.out.println(spr04.koliko());
        odd04.oddaj('V');
        System.out.println(spr11.koliko());
        odd01.oddaj('z');
        odd01.oddaj('C');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd04.oddaj('D');
        System.out.println("<" + spr21.odZadnjic() + ">");
        System.out.println(spr26.koliko());
        System.out.println(spr30.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd01.oddaj('f');
        odd02.oddaj('X');
        odd03.oddaj('q');
        odd05.oddaj('Q');
        System.out.println(spr31.koliko());
        System.out.println(spr07.koliko());
        odd02.oddaj('S');
        System.out.println(spr14.koliko());
        odd08.oddaj('P');
        odd08.oddaj('T');
        odd04.oddaj('T');
        odd06.oddaj('H');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd05.oddaj('J');
        odd02.oddaj('T');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd02.oddaj('g');
        odd08.oddaj('x');
        System.out.println(spr17.koliko());
        odd00.oddaj('t');
        odd00.oddaj('k');
        odd00.oddaj('I');
        odd00.oddaj('A');
        odd07.oddaj('x');
        odd07.oddaj('H');
        odd00.oddaj('B');
        System.out.println(spr27.koliko());
        odd05.oddaj('Q');
        odd05.oddaj('p');
        odd00.oddaj('d');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('n');
        odd08.oddaj('y');
        odd08.oddaj('b');
        odd05.oddaj('h');
        odd05.oddaj('Z');
        odd01.oddaj('t');
        System.out.println(spr25.koliko());
        System.out.println(spr24.koliko());
        odd04.oddaj('f');
        odd02.oddaj('T');
        odd08.oddaj('p');
        System.out.println("<" + spr27.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd02.oddaj('M');
        odd02.oddaj('v');
        odd06.oddaj('K');
        odd04.oddaj('Y');
        odd08.oddaj('y');
        odd02.oddaj('B');
        odd07.oddaj('x');
        odd08.oddaj('S');
        odd04.oddaj('U');
        odd01.oddaj('I');
        odd04.oddaj('G');
        System.out.println("<" + spr24.odZadnjic() + ">");
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd05.oddaj('n');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('U');
        odd08.oddaj('k');
        System.out.println("<" + spr23.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd00.oddaj('b');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('s');
        odd03.oddaj('X');
        odd06.oddaj('u');
        System.out.println(spr11.koliko());
        odd06.oddaj('w');
        odd06.oddaj('g');
        odd01.oddaj('V');
        odd06.oddaj('v');
        odd07.oddaj('S');
        odd08.oddaj('D');
        odd06.oddaj('K');
        odd07.oddaj('b');
        odd02.oddaj('x');
        System.out.println(spr19.koliko());
        odd02.oddaj('k');
        odd08.oddaj('h');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('j');
        odd07.oddaj('z');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('I');
        odd00.oddaj('a');
        odd08.oddaj('K');
        odd02.oddaj('v');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd00.oddaj('C');
        odd04.oddaj('i');
        odd02.oddaj('W');
        odd00.oddaj('k');
        odd05.oddaj('y');
        odd00.oddaj('h');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('T');
        odd05.oddaj('D');
        odd04.oddaj('X');
        System.out.println(spr13.koliko());
        System.out.println(spr11.koliko());
        odd08.oddaj('y');
        odd07.oddaj('Q');
        odd07.oddaj('b');
        odd04.oddaj('i');
        odd02.oddaj('D');
        odd01.oddaj('d');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('K');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd04.oddaj('e');
        odd00.oddaj('b');
        odd03.oddaj('H');
        odd07.oddaj('E');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd04.oddaj('b');
        odd00.oddaj('B');
        odd07.oddaj('p');
        odd07.oddaj('Z');
        odd06.oddaj('p');
        odd08.oddaj('B');
        odd00.oddaj('o');
        odd06.oddaj('k');
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd00.oddaj('N');
        odd05.oddaj('y');
        odd01.oddaj('P');
        odd02.oddaj('L');
        odd07.oddaj('y');
        odd01.oddaj('n');
        odd00.oddaj('o');
        odd05.oddaj('R');
        System.out.println(spr25.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd06.oddaj('T');
        odd01.oddaj('Z');
        odd02.oddaj('A');
        odd06.oddaj('Z');
        odd05.oddaj('b');
        odd08.oddaj('d');
        odd07.oddaj('W');
        odd05.oddaj('L');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('Q');
        odd05.oddaj('f');
        odd00.oddaj('t');
        odd00.oddaj('N');
        odd04.oddaj('c');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd03.oddaj('W');
        odd03.oddaj('k');
        System.out.println(spr17.koliko());
        odd05.oddaj('H');
        odd04.oddaj('U');
        odd01.oddaj('D');
        odd04.oddaj('d');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd03.oddaj('O');
        odd03.oddaj('q');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd08.oddaj('a');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd02.oddaj('f');
        odd08.oddaj('z');
        odd02.oddaj('X');
        odd03.oddaj('C');
        odd00.oddaj('s');
        odd04.oddaj('N');
        odd04.oddaj('g');
        odd05.oddaj('T');
        odd00.oddaj('K');
        odd06.oddaj('b');
        odd05.oddaj('N');
        odd05.oddaj('y');
        odd07.oddaj('V');
        System.out.println(spr04.koliko());
        odd02.oddaj('x');
        odd01.oddaj('B');
        odd03.oddaj('D');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('l');
        odd02.oddaj('R');
        System.out.println(spr16.koliko());
        odd01.oddaj('q');
        odd00.oddaj('q');
        odd02.oddaj('O');
        odd07.oddaj('w');
        odd05.oddaj('o');
        odd06.oddaj('t');
        odd01.oddaj('K');
        odd00.oddaj('q');
        odd06.oddaj('H');
        System.out.println(spr07.koliko());
        odd02.oddaj('z');
        odd02.oddaj('G');
        odd06.oddaj('L');
        odd07.oddaj('g');
        odd08.oddaj('W');
        odd00.oddaj('T');
        odd08.oddaj('K');
        odd02.oddaj('H');
        odd00.oddaj('s');
        odd00.oddaj('a');
        System.out.println("<" + spr23.odZadnjic() + ">");
        System.out.println("<" + spr27.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd02.oddaj('l');
        odd01.oddaj('x');
        odd02.oddaj('q');
        odd01.oddaj('j');
        odd01.oddaj('r');
        odd07.oddaj('B');
        odd01.oddaj('y');
        odd02.oddaj('v');
        System.out.println(spr31.koliko());
        odd00.oddaj('P');
        System.out.println(spr15.koliko());
        System.out.println(spr16.koliko());
        odd07.oddaj('Q');
        odd06.oddaj('g');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd06.oddaj('A');
        odd01.oddaj('c');
        odd03.oddaj('K');
        odd06.oddaj('U');
        odd00.oddaj('C');
        odd07.oddaj('q');
        System.out.println(spr16.koliko());
        odd07.oddaj('E');
        odd01.oddaj('o');
        odd07.oddaj('k');
        odd01.oddaj('X');
        odd01.oddaj('l');
        odd06.oddaj('Z');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd07.oddaj('E');
        odd03.oddaj('J');
        odd07.oddaj('u');
        odd00.oddaj('y');
        odd02.oddaj('p');
        odd03.oddaj('N');
        odd02.oddaj('a');
        odd05.oddaj('m');
        odd03.oddaj('Q');
        odd03.oddaj('k');
        odd06.oddaj('i');
        odd00.oddaj('M');
        System.out.println(spr18.koliko());
        odd01.oddaj('L');
        odd06.oddaj('H');
        odd08.oddaj('n');
        odd01.oddaj('w');
        odd04.oddaj('K');
        System.out.println(spr14.koliko());
        odd04.oddaj('Q');
        System.out.println(spr13.koliko());
        odd08.oddaj('F');
        odd03.oddaj('c');
        odd01.oddaj('Y');
        odd07.oddaj('w');
        odd00.oddaj('i');
        odd05.oddaj('y');
        odd08.oddaj('k');
        System.out.println(spr21.koliko());
        System.out.println(spr25.koliko());
        odd06.oddaj('d');
        odd05.oddaj('S');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('z');
        System.out.println(spr24.koliko());
        odd06.oddaj('p');
        System.out.println(spr27.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        odd04.oddaj('v');
        odd01.oddaj('Q');
        System.out.println(spr20.koliko());
        odd07.oddaj('e');
        odd01.oddaj('S');
        System.out.println(spr24.koliko());
        odd03.oddaj('p');
        odd02.oddaj('L');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd01.oddaj('r');
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd06.oddaj('v');
        odd02.oddaj('m');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd04.oddaj('k');
        odd04.oddaj('R');
        odd06.oddaj('S');
        odd03.oddaj('L');
        odd07.oddaj('S');
        odd08.oddaj('i');
        odd08.oddaj('D');
        odd06.oddaj('b');
        System.out.println(spr30.koliko());
        System.out.println(spr07.koliko());
        System.out.println("<" + spr27.odZadnjic() + ">");
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd02.oddaj('f');
        System.out.println(spr24.koliko());
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd06.oddaj('Q');
        System.out.println("<" + spr22.odZadnjic() + ">");
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd03.oddaj('p');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd08.oddaj('G');
        System.out.println(spr08.koliko());
        odd02.oddaj('k');
        odd08.oddaj('H');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('r');
        odd05.oddaj('X');
        odd08.oddaj('r');
        odd06.oddaj('P');
        odd00.oddaj('h');
        odd06.oddaj('c');
        System.out.println(spr08.koliko());
        odd01.oddaj('r');
        odd03.oddaj('x');
        odd01.oddaj('x');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd05.oddaj('Y');
        odd07.oddaj('Z');
        odd07.oddaj('M');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('u');
        odd05.oddaj('a');
        odd04.oddaj('i');
        odd04.oddaj('M');
        odd04.oddaj('a');
        odd05.oddaj('y');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd08.oddaj('i');
        odd01.oddaj('a');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd00.oddaj('H');
        odd01.oddaj('y');
        System.out.println(spr29.koliko());
        System.out.println(spr21.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('X');
        odd01.oddaj('N');
        odd03.oddaj('u');
        odd02.oddaj('Q');
        odd03.oddaj('L');
        System.out.println(spr13.koliko());
        odd06.oddaj('P');
        odd03.oddaj('B');
        odd04.oddaj('B');
        odd08.oddaj('o');
        odd07.oddaj('q');
        odd00.oddaj('A');
        System.out.println(spr27.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('e');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('o');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('u');
        odd03.oddaj('v');
        System.out.println("<" + spr21.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd08.oddaj('G');
        odd03.oddaj('b');
        System.out.println(spr24.koliko());
        System.out.println(spr30.koliko());
        odd05.oddaj('c');
        odd01.oddaj('A');
        odd03.oddaj('N');
        System.out.println(spr08.koliko());
        odd04.oddaj('G');
        System.out.println(spr09.koliko());
        odd04.oddaj('O');
        odd08.oddaj('Q');
        odd01.oddaj('S');
        odd03.oddaj('y');
        System.out.println(spr23.koliko());
        System.out.println(spr02.koliko());
        System.out.println(spr13.koliko());
        odd02.oddaj('Z');
        odd02.oddaj('w');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('d');
        odd07.oddaj('e');
        odd02.oddaj('o');
        odd04.oddaj('p');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('D');
        System.out.println("<" + spr32.odZadnjic() + ">");
        odd05.oddaj('t');
        odd02.oddaj('c');
        odd00.oddaj('d');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd03.oddaj('G');
        odd05.oddaj('t');
        System.out.println("<" + spr26.odZadnjic() + ">");
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd07.oddaj('Y');
        odd02.oddaj('g');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd00.oddaj('T');
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd00.oddaj('h');
        System.out.println(spr24.koliko());
        odd01.oddaj('v');
        odd05.oddaj('K');
        odd08.oddaj('I');
        odd07.oddaj('E');
        odd08.oddaj('z');
        odd02.oddaj('b');
        odd04.oddaj('u');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('c');
        odd07.oddaj('C');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd03.oddaj('j');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr32.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd00.oddaj('o');
        System.out.println(spr00.koliko());
        odd07.oddaj('D');
        odd04.oddaj('S');
        odd00.oddaj('C');
        odd04.oddaj('g');
        odd02.oddaj('n');
        odd06.oddaj('f');
        odd01.oddaj('L');
        odd00.oddaj('l');
        odd08.oddaj('q');
        odd05.oddaj('v');
        odd03.oddaj('F');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd06.oddaj('A');
        odd08.oddaj('i');
        odd07.oddaj('E');
        odd05.oddaj('e');
        odd04.oddaj('X');
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd03.oddaj('L');
        odd04.oddaj('P');
        System.out.println(spr17.koliko());
        odd06.oddaj('E');
        odd03.oddaj('z');
        odd07.oddaj('S');
        odd08.oddaj('w');
        System.out.println(spr09.koliko());
        odd06.oddaj('J');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd07.oddaj('W');
        odd06.oddaj('q');
        odd02.oddaj('e');
        odd02.oddaj('n');
        odd08.oddaj('p');
        odd01.oddaj('d');
        odd05.oddaj('H');
        System.out.println(spr04.koliko());
        odd08.oddaj('w');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd07.oddaj('d');
        odd01.oddaj('L');
        System.out.println(spr00.koliko());
        odd07.oddaj('k');
        odd01.oddaj('R');
        odd04.oddaj('e');
        odd06.oddaj('w');
        odd03.oddaj('U');
        odd00.oddaj('J');
        odd07.oddaj('M');
        System.out.println(spr01.koliko());
        odd00.oddaj('c');
        odd01.oddaj('a');
        System.out.println(spr15.koliko());
        odd00.oddaj('h');
        odd02.oddaj('o');
        odd05.oddaj('W');
        System.out.println(spr11.koliko());
        System.out.println(spr05.koliko());
        odd00.oddaj('Y');
        System.out.println(spr18.koliko());
        System.out.println(spr29.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('o');
        odd04.oddaj('s');
        odd06.oddaj('w');
        odd05.oddaj('g');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd01.oddaj('j');
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd06.oddaj('M');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd06.oddaj('v');
        odd04.oddaj('c');
        System.out.println("<" + spr25.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('Q');
        odd00.oddaj('d');
        odd01.oddaj('o');
        odd06.oddaj('p');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd07.oddaj('M');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('P');
        odd05.oddaj('o');
        odd01.oddaj('Q');
        odd02.oddaj('C');
        odd05.oddaj('b');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd05.oddaj('a');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd07.oddaj('b');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd01.oddaj('h');
        odd02.oddaj('F');
        odd03.oddaj('J');
        odd00.oddaj('P');
        odd08.oddaj('F');
        odd06.oddaj('X');
        odd04.oddaj('K');
        odd08.oddaj('N');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd06.oddaj('T');
        odd00.oddaj('b');
        odd03.oddaj('Y');
        odd02.oddaj('j');
        odd02.oddaj('m');
        odd01.oddaj('y');
        System.out.println(spr15.koliko());
        odd06.oddaj('e');
        odd05.oddaj('f');
        odd02.oddaj('j');
        System.out.println("<" + spr26.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd07.oddaj('M');
        odd01.oddaj('R');
        odd02.oddaj('T');
        System.out.println(spr09.koliko());
        odd07.oddaj('x');
        odd03.oddaj('M');
        odd02.oddaj('z');
        odd01.oddaj('e');
        System.out.println(spr29.koliko());
        odd08.oddaj('p');
        odd07.oddaj('U');
        odd05.oddaj('Z');
        odd00.oddaj('b');
        odd05.oddaj('C');
        odd06.oddaj('I');
        odd01.oddaj('U');
        odd03.oddaj('m');
        System.out.println(spr18.koliko());
        odd02.oddaj('k');
        System.out.println(spr28.koliko());
        System.out.println(spr15.koliko());
        odd02.oddaj('m');
        odd05.oddaj('l');
        System.out.println(spr25.koliko());
        odd03.oddaj('M');
        odd03.oddaj('S');
        odd07.oddaj('x');
        odd07.oddaj('c');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd00.oddaj('S');
        odd02.oddaj('T');
        odd07.oddaj('C');
        odd01.oddaj('y');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd04.oddaj('v');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr30.koliko());
        odd03.oddaj('b');
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd00.oddaj('a');
        odd06.oddaj('n');
        odd00.oddaj('k');
        System.out.println(spr03.koliko());
        odd05.oddaj('i');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('u');
        odd04.oddaj('U');
        odd01.oddaj('T');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('T');
        odd03.oddaj('p');
        odd02.oddaj('s');
        odd02.oddaj('P');
        odd08.oddaj('I');
        odd08.oddaj('s');
        odd01.oddaj('K');
        odd00.oddaj('q');
        odd05.oddaj('H');
        odd07.oddaj('d');
        odd06.oddaj('o');
        odd04.oddaj('d');
        odd05.oddaj('E');
        System.out.println(spr27.koliko());
        odd04.oddaj('e');
        System.out.println(spr25.koliko());
        odd07.oddaj('x');
        odd05.oddaj('V');
        odd00.oddaj('w');
        System.out.println(spr26.koliko());
        odd06.oddaj('F');
        System.out.println("<" + spr04.odZadnjic() + ">");
    }
}
