
import java.util.*;

public class Test21 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);

        odd01.oddaj('A');
        System.out.println(spr01.koliko());
        odd03.oddaj('c');
        odd06.oddaj('c');
        odd02.oddaj('t');
        odd04.oddaj('n');
        odd06.oddaj('x');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('J');
        odd11.oddaj('u');
        odd02.oddaj('g');
        System.out.println(spr11.koliko());
        odd09.oddaj('k');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('b');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd11.oddaj('u');
        System.out.println(spr11.koliko());
        odd00.oddaj('j');
        odd07.oddaj('w');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd07.oddaj('p');
        odd02.oddaj('Z');
        odd10.oddaj('C');
        System.out.println(spr10.koliko());
        odd08.oddaj('g');
        odd06.oddaj('v');
        System.out.println(spr07.koliko());
        odd04.oddaj('E');
        odd05.oddaj('t');
        odd09.oddaj('z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('s');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('m');
        odd04.oddaj('l');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd06.oddaj('J');
        odd00.oddaj('h');
        odd00.oddaj('w');
        odd10.oddaj('Q');
        odd09.oddaj('G');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd07.oddaj('h');
        odd07.oddaj('b');
        odd07.oddaj('w');
        odd07.oddaj('F');
        odd02.oddaj('W');
        odd08.oddaj('c');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('v');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd10.oddaj('l');
        odd07.oddaj('Z');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd08.oddaj('z');
        System.out.println(spr09.koliko());
        System.out.println(spr10.koliko());
        odd09.oddaj('z');
        odd02.oddaj('F');
        odd01.oddaj('U');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('d');
        odd03.oddaj('k');
        odd10.oddaj('J');
        odd06.oddaj('f');
        odd11.oddaj('G');
        odd00.oddaj('l');
        odd05.oddaj('l');
        odd04.oddaj('D');
        odd01.oddaj('P');
        odd09.oddaj('H');
        System.out.println(spr11.koliko());
        System.out.println(spr10.koliko());
        odd05.oddaj('w');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd01.oddaj('K');
        odd04.oddaj('w');
        odd03.oddaj('r');
        System.out.println(spr03.koliko());
        odd08.oddaj('x');
        odd04.oddaj('Z');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd00.oddaj('l');
        System.out.println(spr07.koliko());
        odd10.oddaj('P');
        odd07.oddaj('E');
        odd05.oddaj('Y');
        odd10.oddaj('a');
        odd02.oddaj('Z');
        System.out.println(spr01.koliko());
        System.out.println(spr02.koliko());
        odd06.oddaj('Q');
        odd03.oddaj('i');
        odd08.oddaj('R');
        odd09.oddaj('A');
        odd02.oddaj('x');
        System.out.println(spr09.koliko());
        odd03.oddaj('u');
        odd09.oddaj('A');
        odd08.oddaj('y');
        odd04.oddaj('z');
        odd08.oddaj('A');
        System.out.println(spr09.koliko());
        odd06.oddaj('E');
        System.out.println(spr00.koliko());
        odd10.oddaj('J');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        System.out.println(spr03.koliko());
        odd02.oddaj('F');
        odd02.oddaj('m');
        System.out.println(spr08.koliko());
        odd10.oddaj('s');
        System.out.println(spr02.koliko());
        odd05.oddaj('m');
        odd02.oddaj('D');
        odd07.oddaj('s');
        odd04.oddaj('c');
        System.out.println(spr06.koliko());
        odd11.oddaj('J');
        odd04.oddaj('q');
        odd09.oddaj('r');
        odd07.oddaj('Y');
        System.out.println(spr07.koliko());
        odd10.oddaj('W');
        odd02.oddaj('O');
        odd06.oddaj('o');
        odd01.oddaj('h');
        odd10.oddaj('x');
        System.out.println(spr09.koliko());
        odd04.oddaj('x');
        System.out.println(spr05.koliko());
        odd02.oddaj('m');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd05.oddaj('z');
        odd00.oddaj('L');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd08.oddaj('Q');
        odd10.oddaj('N');
        odd06.oddaj('d');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('h');
        odd04.oddaj('b');
        System.out.println(spr11.koliko());
        odd00.oddaj('n');
        odd04.oddaj('p');
        odd07.oddaj('q');
        odd01.oddaj('z');
        odd05.oddaj('b');
        odd10.oddaj('J');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd00.oddaj('F');
        System.out.println(spr06.koliko());
        odd10.oddaj('v');
        System.out.println(spr10.koliko());
        System.out.println(spr00.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('l');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd08.oddaj('j');
        odd00.oddaj('p');
        System.out.println(spr00.koliko());
        System.out.println(spr09.koliko());
        odd09.oddaj('T');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd07.oddaj('j');
        odd10.oddaj('Y');
        odd05.oddaj('H');
        odd09.oddaj('q');
        odd03.oddaj('Y');
        odd08.oddaj('t');
        odd01.oddaj('n');
        odd01.oddaj('S');
        odd09.oddaj('b');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('T');
        odd11.oddaj('V');
        odd08.oddaj('H');
        odd09.oddaj('l');
        System.out.println(spr11.koliko());
        odd01.oddaj('W');
        odd06.oddaj('Q');
        odd08.oddaj('g');
        odd02.oddaj('P');
        odd06.oddaj('z');
        odd09.oddaj('T');
        odd09.oddaj('c');
        odd05.oddaj('y');
        odd04.oddaj('r');
        System.out.println(spr04.koliko());
        odd01.oddaj('A');
        odd01.oddaj('q');
        odd01.oddaj('v');
        odd08.oddaj('u');
        odd08.oddaj('H');
        odd09.oddaj('m');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('t');
        System.out.println(spr03.koliko());
        odd00.oddaj('D');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd02.oddaj('s');
        odd09.oddaj('O');
        odd03.oddaj('g');
        odd00.oddaj('J');
        odd05.oddaj('k');
        System.out.println(spr00.koliko());
        System.out.println(spr09.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd07.oddaj('J');
        odd01.oddaj('X');
        odd04.oddaj('C');
        odd10.oddaj('y');
        odd09.oddaj('R');
        System.out.println(spr01.koliko());
        odd10.oddaj('K');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd03.oddaj('b');
        odd09.oddaj('T');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd04.oddaj('E');
        odd01.oddaj('g');
        odd07.oddaj('L');
        System.out.println(spr04.koliko());
        odd07.oddaj('L');
        odd04.oddaj('O');
        odd09.oddaj('I');
        odd01.oddaj('z');
        odd05.oddaj('K');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('X');
        odd04.oddaj('d');
        odd07.oddaj('j');
        odd02.oddaj('Y');
        System.out.println(spr05.koliko());
        odd07.oddaj('g');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('b');
        odd02.oddaj('h');
        odd01.oddaj('W');
        odd08.oddaj('l');
        odd04.oddaj('t');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('l');
        odd01.oddaj('U');
        odd04.oddaj('D');
        odd00.oddaj('S');
        odd04.oddaj('n');
        System.out.println(spr04.koliko());
        odd07.oddaj('b');
        odd00.oddaj('f');
        odd01.oddaj('N');
        odd04.oddaj('m');
        odd02.oddaj('a');
        odd08.oddaj('P');
        odd11.oddaj('r');
        odd02.oddaj('Y');
        odd04.oddaj('P');
        odd11.oddaj('D');
        odd07.oddaj('M');
        odd08.oddaj('q');
        odd02.oddaj('c');
        odd10.oddaj('V');
        odd03.oddaj('r');
        odd01.oddaj('i');
        odd05.oddaj('k');
        odd05.oddaj('z');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('B');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        System.out.println(spr04.koliko());
        odd04.oddaj('H');
        odd01.oddaj('y');
        odd01.oddaj('t');
        odd11.oddaj('s');
        System.out.println(spr02.koliko());
        odd01.oddaj('B');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd10.oddaj('z');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd00.oddaj('U');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('O');
        odd11.oddaj('H');
        System.out.println(spr08.koliko());
        odd11.oddaj('L');
        odd07.oddaj('J');
        odd01.oddaj('o');
        odd01.oddaj('S');
        System.out.println(spr07.koliko());
        odd03.oddaj('D');
        odd05.oddaj('e');
        odd08.oddaj('f');
        System.out.println(spr05.koliko());
        odd11.oddaj('X');
        odd09.oddaj('n');
        odd04.oddaj('U');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd11.oddaj('X');
        System.out.println(spr01.koliko());
        odd09.oddaj('l');
        odd01.oddaj('a');
        odd08.oddaj('G');
        odd09.oddaj('L');
        odd03.oddaj('S');
        odd05.oddaj('b');
        odd02.oddaj('r');
        System.out.println(spr08.koliko());
        odd03.oddaj('g');
        System.out.println(spr10.koliko());
        odd04.oddaj('h');
        System.out.println(spr05.koliko());
        odd02.oddaj('q');
        odd00.oddaj('M');
        odd06.oddaj('A');
        System.out.println(spr01.koliko());
        System.out.println(spr00.koliko());
        System.out.println(spr03.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd04.oddaj('C');
        odd02.oddaj('G');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('h');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('P');
        odd03.oddaj('Z');
        odd09.oddaj('d');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd08.oddaj('D');
        System.out.println(spr00.koliko());
        odd11.oddaj('x');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('z');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        odd05.oddaj('L');
        odd02.oddaj('L');
        System.out.println(spr05.koliko());
        System.out.println(spr08.koliko());
        odd09.oddaj('z');
        System.out.println(spr09.koliko());
        odd08.oddaj('t');
        odd11.oddaj('o');
        odd08.oddaj('w');
        odd10.oddaj('g');
        odd00.oddaj('Q');
        odd05.oddaj('R');
        odd05.oddaj('L');
        odd05.oddaj('I');
        odd05.oddaj('R');
        odd03.oddaj('Z');
        odd04.oddaj('p');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd10.oddaj('G');
        odd08.oddaj('I');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd11.oddaj('M');
        odd00.oddaj('M');
        odd01.oddaj('t');
        System.out.println(spr03.koliko());
        odd01.oddaj('s');
        odd07.oddaj('k');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('N');
        odd11.oddaj('Q');
        odd04.oddaj('V');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd04.oddaj('I');
        odd09.oddaj('B');
        odd05.oddaj('H');
        odd10.oddaj('J');
        odd10.oddaj('M');
        odd08.oddaj('V');
        System.out.println(spr05.koliko());
        odd01.oddaj('k');
        odd05.oddaj('u');
        odd00.oddaj('G');
        odd07.oddaj('S');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('V');
        odd08.oddaj('N');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('x');
        odd01.oddaj('f');
        odd01.oddaj('j');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('z');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd07.oddaj('x');
        odd10.oddaj('e');
        odd06.oddaj('D');
        odd02.oddaj('m');
        odd05.oddaj('X');
        odd02.oddaj('A');
        odd01.oddaj('X');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd07.oddaj('I');
        odd04.oddaj('k');
        odd01.oddaj('C');
        odd02.oddaj('H');
        System.out.println(spr05.koliko());
        System.out.println(spr00.koliko());
        System.out.println(spr08.koliko());
        odd02.oddaj('k');
        odd01.oddaj('J');
        odd09.oddaj('u');
        odd11.oddaj('t');
        odd01.oddaj('h');
        odd08.oddaj('r');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd06.oddaj('K');
        odd06.oddaj('V');
        odd03.oddaj('X');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        System.out.println(spr11.koliko());
        odd05.oddaj('v');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('c');
        odd00.oddaj('l');
        odd11.oddaj('v');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd08.oddaj('a');
        odd08.oddaj('i');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('V');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd09.oddaj('s');
        odd07.oddaj('J');
        odd07.oddaj('a');
        odd05.oddaj('Y');
        odd05.oddaj('E');
        odd08.oddaj('V');
        odd03.oddaj('n');
        odd07.oddaj('X');
        odd06.oddaj('e');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd10.oddaj('H');
        System.out.println(spr10.koliko());
        odd00.oddaj('A');
        odd10.oddaj('z');
        odd01.oddaj('s');
        odd07.oddaj('d');
        odd06.oddaj('a');
        odd03.oddaj('C');
        odd00.oddaj('J');
        odd03.oddaj('e');
        odd02.oddaj('s');
        odd09.oddaj('f');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('D');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd01.oddaj('Q');
        odd09.oddaj('Q');
        odd00.oddaj('P');
        odd08.oddaj('K');
        System.out.println(spr06.koliko());
        odd01.oddaj('e');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('v');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd08.oddaj('r');
        System.out.println(spr08.koliko());
        System.out.println(spr04.koliko());
        odd06.oddaj('t');
        odd03.oddaj('H');
        System.out.println(spr05.koliko());
        odd06.oddaj('w');
        odd04.oddaj('h');
        odd01.oddaj('O');
        odd07.oddaj('T');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('b');
        System.out.println(spr02.koliko());
        System.out.println(spr03.koliko());
        odd08.oddaj('J');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('s');
        odd01.oddaj('U');
        odd02.oddaj('G');
        odd09.oddaj('C');
        odd00.oddaj('S');
        odd10.oddaj('Z');
        odd09.oddaj('T');
        odd02.oddaj('D');
        odd02.oddaj('U');
        odd02.oddaj('P');
        odd06.oddaj('K');
        odd09.oddaj('r');
        odd08.oddaj('e');
        odd09.oddaj('Q');
        odd02.oddaj('u');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd07.oddaj('O');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('z');
        System.out.println(spr00.koliko());
        System.out.println(spr09.koliko());
        odd09.oddaj('M');
        odd05.oddaj('D');
        odd07.oddaj('W');
        odd09.oddaj('k');
        odd07.oddaj('O');
        odd02.oddaj('B');
        odd09.oddaj('k');
        odd08.oddaj('M');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd10.oddaj('J');
        odd04.oddaj('n');
        odd06.oddaj('m');
        odd02.oddaj('q');
        odd06.oddaj('J');
        odd08.oddaj('E');
        odd10.oddaj('n');
        odd02.oddaj('O');
        odd02.oddaj('X');
        odd00.oddaj('B');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('Y');
        odd11.oddaj('x');
        System.out.println(spr11.koliko());
        odd08.oddaj('g');
        odd01.oddaj('K');
        System.out.println(spr04.koliko());
        System.out.println(spr00.koliko());
        odd01.oddaj('U');
        odd08.oddaj('C');
        odd08.oddaj('c');
        odd00.oddaj('I');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('R');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd04.oddaj('h');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd09.oddaj('t');
        odd02.oddaj('y');
        System.out.println(spr00.koliko());
        odd10.oddaj('b');
        odd00.oddaj('T');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd03.oddaj('w');
        odd04.oddaj('L');
        odd04.oddaj('j');
        odd11.oddaj('l');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('i');
        odd01.oddaj('L');
        odd09.oddaj('p');
        System.out.println(spr03.koliko());
        odd09.oddaj('B');
        odd02.oddaj('p');
        odd06.oddaj('j');
        odd07.oddaj('N');
        System.out.println(spr11.koliko());
        odd10.oddaj('U');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd07.oddaj('I');
        odd07.oddaj('M');
        odd10.oddaj('D');
        System.out.println(spr07.koliko());
        System.out.println(spr02.koliko());
        System.out.println(spr10.koliko());
        odd00.oddaj('p');
        odd09.oddaj('a');
        odd10.oddaj('F');
        odd07.oddaj('n');
        odd06.oddaj('E');
        odd06.oddaj('X');
        odd05.oddaj('q');
        odd03.oddaj('z');
        odd09.oddaj('t');
        odd07.oddaj('X');
        odd05.oddaj('Z');
        odd03.oddaj('y');
        odd04.oddaj('F');
        odd00.oddaj('g');
        odd10.oddaj('U');
        odd02.oddaj('L');
        odd08.oddaj('Q');
        odd06.oddaj('M');
        System.out.println(spr04.koliko());
        odd01.oddaj('m');
        System.out.println(spr02.koliko());
        System.out.println(spr06.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd10.oddaj('f');
        System.out.println(spr10.koliko());
    }
}
