
import java.util.*;

public class Test30 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd12);
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd13);
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd14);
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd15);

        odd03.oddaj('g');
        odd09.oddaj('P');
        System.out.println(spr09.koliko());
        odd09.oddaj('J');
        System.out.println(spr09.koliko());
        odd14.oddaj('O');
        System.out.println(spr03.koliko());
        System.out.println(spr14.koliko());
        odd04.oddaj('B');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd08.oddaj('R');
        odd15.oddaj('Y');
        System.out.println(spr15.koliko());
        odd06.oddaj('v');
        odd10.oddaj('y');
        odd15.oddaj('s');
        odd04.oddaj('w');
        odd06.oddaj('K');
        System.out.println(spr06.koliko());
        odd15.oddaj('r');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd10.oddaj('q');
        odd01.oddaj('O');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('w');
        odd00.oddaj('a');
        odd04.oddaj('B');
        odd05.oddaj('M');
        odd14.oddaj('K');
        odd01.oddaj('V');
        odd02.oddaj('o');
        odd00.oddaj('H');
        System.out.println(spr15.koliko());
        System.out.println(spr01.koliko());
        odd07.oddaj('K');
        odd15.oddaj('E');
        odd02.oddaj('M');
        odd01.oddaj('g');
        odd10.oddaj('O');
        System.out.println(spr15.koliko());
        odd04.oddaj('E');
        odd07.oddaj('g');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('j');
        odd05.oddaj('P');
        System.out.println(spr02.koliko());
        odd02.oddaj('b');
        odd09.oddaj('K');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd07.oddaj('V');
        odd14.oddaj('I');
        odd13.oddaj('e');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd13.oddaj('z');
        odd15.oddaj('E');
        System.out.println(spr10.koliko());
        odd15.oddaj('L');
        odd04.oddaj('h');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd06.oddaj('B');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd02.oddaj('h');
        odd05.oddaj('A');
        System.out.println(spr07.koliko());
        odd04.oddaj('o');
        odd03.oddaj('H');
        odd15.oddaj('g');
        odd01.oddaj('w');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('k');
        odd12.oddaj('S');
        System.out.println(spr15.koliko());
        odd00.oddaj('r');
        System.out.println(spr01.koliko());
        odd03.oddaj('G');
        odd03.oddaj('K');
        System.out.println(spr04.koliko());
        odd00.oddaj('P');
        odd04.oddaj('O');
        System.out.println(spr04.koliko());
        System.out.println(spr06.koliko());
        odd06.oddaj('E');
        odd11.oddaj('U');
        System.out.println(spr02.koliko());
        odd01.oddaj('M');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd10.oddaj('t');
        odd01.oddaj('n');
        odd11.oddaj('i');
        odd04.oddaj('X');
        odd11.oddaj('E');
        odd03.oddaj('Z');
        odd11.oddaj('c');
        odd08.oddaj('e');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd14.oddaj('q');
        System.out.println(spr05.koliko());
        odd03.oddaj('F');
        odd06.oddaj('l');
        odd05.oddaj('v');
        odd00.oddaj('S');
        odd15.oddaj('Y');
        odd09.oddaj('Y');
        odd10.oddaj('e');
        System.out.println(spr15.koliko());
        odd05.oddaj('A');
        odd11.oddaj('N');
        odd14.oddaj('S');
        odd07.oddaj('o');
        System.out.println(spr05.koliko());
        System.out.println(spr07.koliko());
        odd04.oddaj('v');
        odd15.oddaj('S');
        odd08.oddaj('X');
        odd04.oddaj('h');
        odd05.oddaj('J');
        odd01.oddaj('X');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('N');
        odd09.oddaj('Y');
        odd02.oddaj('F');
        odd11.oddaj('c');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd10.oddaj('C');
        odd00.oddaj('p');
        System.out.println(spr03.koliko());
        odd01.oddaj('N');
        odd15.oddaj('B');
        odd10.oddaj('H');
        odd10.oddaj('m');
        odd15.oddaj('H');
        odd08.oddaj('m');
        System.out.println(spr04.koliko());
        odd02.oddaj('n');
        odd00.oddaj('F');
        System.out.println(spr05.koliko());
        odd12.oddaj('h');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd04.oddaj('m');
        odd15.oddaj('I');
        odd10.oddaj('R');
        odd11.oddaj('e');
        odd12.oddaj('I');
        System.out.println(spr08.koliko());
        odd03.oddaj('t');
        odd10.oddaj('Z');
        odd04.oddaj('Q');
        System.out.println(spr03.koliko());
        odd02.oddaj('A');
        odd00.oddaj('x');
        System.out.println(spr09.koliko());
        odd14.oddaj('H');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('f');
        odd08.oddaj('m');
        odd15.oddaj('G');
        odd12.oddaj('j');
        odd11.oddaj('e');
        odd10.oddaj('G');
        odd15.oddaj('v');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd03.oddaj('y');
        System.out.println(spr07.koliko());
        odd04.oddaj('a');
        System.out.println(spr15.koliko());
        odd04.oddaj('v');
        odd04.oddaj('N');
        System.out.println(spr06.koliko());
        odd03.oddaj('S');
        System.out.println(spr02.koliko());
        odd11.oddaj('S');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('t');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('e');
        odd06.oddaj('R');
        odd00.oddaj('F');
        odd03.oddaj('x');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('K');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd09.oddaj('v');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd05.oddaj('K');
        odd14.oddaj('g');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd03.oddaj('n');
        odd03.oddaj('H');
        odd09.oddaj('F');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('w');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd03.oddaj('g');
        odd13.oddaj('R');
        odd06.oddaj('b');
        System.out.println(spr03.koliko());
        odd07.oddaj('j');
        System.out.println(spr07.koliko());
        odd15.oddaj('x');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd04.oddaj('O');
        odd01.oddaj('I');
        odd05.oddaj('k');
        odd05.oddaj('Y');
        odd04.oddaj('D');
        odd05.oddaj('L');
        System.out.println(spr13.koliko());
        odd13.oddaj('O');
        odd02.oddaj('G');
        System.out.println(spr04.koliko());
        odd08.oddaj('b');
        System.out.println(spr09.koliko());
        System.out.println(spr06.koliko());
        odd00.oddaj('b');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd08.oddaj('Z');
        odd11.oddaj('V');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('J');
        odd03.oddaj('z');
        odd04.oddaj('z');
        odd15.oddaj('Y');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd11.oddaj('G');
        odd09.oddaj('Z');
        odd14.oddaj('E');
        odd13.oddaj('T');
        odd08.oddaj('f');
        System.out.println(spr07.koliko());
        odd13.oddaj('h');
        odd01.oddaj('S');
        odd14.oddaj('l');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd07.oddaj('U');
        odd08.oddaj('L');
        odd00.oddaj('j');
        System.out.println(spr14.koliko());
        odd09.oddaj('G');
        odd09.oddaj('C');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('R');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd03.oddaj('O');
        odd09.oddaj('v');
        odd11.oddaj('p');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd13.oddaj('Y');
        odd04.oddaj('g');
        odd00.oddaj('r');
        odd06.oddaj('x');
        odd07.oddaj('p');
        odd07.oddaj('y');
        System.out.println(spr00.koliko());
        odd01.oddaj('Y');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd14.oddaj('G');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd15.oddaj('v');
        odd04.oddaj('X');
        System.out.println(spr15.koliko());
        odd07.oddaj('M');
        odd14.oddaj('a');
        odd06.oddaj('j');
        System.out.println(spr14.koliko());
        odd15.oddaj('Z');
        odd06.oddaj('a');
        System.out.println(spr07.koliko());
        odd05.oddaj('a');
        odd00.oddaj('A');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd10.oddaj('i');
        odd03.oddaj('J');
        System.out.println(spr04.koliko());
        odd15.oddaj('G');
        odd14.oddaj('l');
        odd12.oddaj('N');
        System.out.println(spr09.koliko());
        odd08.oddaj('n');
        odd03.oddaj('r');
        System.out.println(spr06.koliko());
        System.out.println(spr15.koliko());
        odd10.oddaj('p');
        System.out.println(spr10.koliko());
        System.out.println(spr03.koliko());
        odd08.oddaj('g');
        odd10.oddaj('S');
        odd07.oddaj('v');
        odd03.oddaj('e');
        odd00.oddaj('u');
        odd04.oddaj('a');
        odd04.oddaj('R');
        odd02.oddaj('h');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('S');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd10.oddaj('M');
        System.out.println(spr07.koliko());
        System.out.println(spr08.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd12.oddaj('f');
        odd11.oddaj('s');
        odd15.oddaj('W');
        odd14.oddaj('E');
        odd05.oddaj('W');
        odd08.oddaj('y');
        odd07.oddaj('o');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd15.oddaj('R');
        odd10.oddaj('m');
        odd05.oddaj('y');
        odd08.oddaj('V');
        odd00.oddaj('d');
        odd08.oddaj('j');
        odd08.oddaj('k');
        odd08.oddaj('g');
        System.out.println(spr05.koliko());
        odd02.oddaj('U');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd14.oddaj('P');
        odd09.oddaj('Z');
        odd04.oddaj('X');
        odd08.oddaj('m');
        odd08.oddaj('J');
        odd12.oddaj('Y');
        odd12.oddaj('o');
        System.out.println(spr07.koliko());
        odd14.oddaj('n');
        odd01.oddaj('t');
        System.out.println(spr15.koliko());
        odd01.oddaj('L');
        odd05.oddaj('B');
        System.out.println(spr04.koliko());
        odd15.oddaj('J');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('E');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('A');
        odd05.oddaj('v');
        odd10.oddaj('V');
        odd08.oddaj('S');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd11.oddaj('v');
        odd01.oddaj('h');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd13.oddaj('m');
        System.out.println(spr10.koliko());
        odd08.oddaj('k');
        odd08.oddaj('Z');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd02.oddaj('X');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('Q');
        odd07.oddaj('u');
        odd09.oddaj('k');
        odd10.oddaj('Y');
        odd03.oddaj('y');
        odd14.oddaj('i');
        System.out.println(spr14.koliko());
        odd04.oddaj('H');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd12.oddaj('P');
        odd07.oddaj('D');
        odd04.oddaj('g');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd09.oddaj('W');
        odd13.oddaj('w');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd13.oddaj('R');
        odd09.oddaj('R');
        odd06.oddaj('w');
        odd13.oddaj('c');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd09.oddaj('M');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('d');
        System.out.println(spr00.koliko());
        odd09.oddaj('i');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('M');
        odd01.oddaj('S');
        odd13.oddaj('z');
        odd14.oddaj('l');
        odd13.oddaj('b');
        odd10.oddaj('R');
        odd13.oddaj('l');
        odd09.oddaj('e');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd14.oddaj('G');
        odd00.oddaj('d');
        System.out.println(spr01.koliko());
        odd09.oddaj('R');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd04.oddaj('J');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('G');
        odd01.oddaj('n');
        odd10.oddaj('j');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('c');
        odd15.oddaj('I');
        odd08.oddaj('A');
        odd10.oddaj('K');
        odd03.oddaj('x');
        odd13.oddaj('x');
        System.out.println(spr04.koliko());
        odd04.oddaj('h');
        odd12.oddaj('B');
        odd01.oddaj('f');
        odd09.oddaj('h');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd14.oddaj('B');
        odd01.oddaj('Z');
        odd06.oddaj('H');
        odd03.oddaj('A');
        odd04.oddaj('U');
        System.out.println(spr03.koliko());
        odd09.oddaj('I');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd13.oddaj('R');
        System.out.println(spr01.koliko());
        odd07.oddaj('U');
        odd06.oddaj('s');
        odd06.oddaj('A');
        odd05.oddaj('u');
        odd06.oddaj('k');
        odd08.oddaj('J');
        odd13.oddaj('v');
        odd14.oddaj('f');
        odd05.oddaj('G');
        System.out.println(spr10.koliko());
        System.out.println(spr13.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd14.oddaj('l');
        odd07.oddaj('R');
        System.out.println(spr08.koliko());
        odd09.oddaj('y');
        System.out.println(spr09.koliko());
        System.out.println(spr14.koliko());
        odd15.oddaj('v');
    }
}
