
import java.util.*;

public class Test18 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);

        odd09.oddaj('F');
        odd02.oddaj('O');
        odd00.oddaj('O');
        odd08.oddaj('C');
        odd11.oddaj('H');
        System.out.println(spr00.koliko());
        odd04.oddaj('O');
        odd07.oddaj('r');
        System.out.println(spr02.koliko());
        System.out.println(spr08.koliko());
        odd07.oddaj('m');
        odd01.oddaj('T');
        odd04.oddaj('Z');
        odd10.oddaj('y');
        System.out.println(spr04.koliko());
        odd02.oddaj('k');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd05.oddaj('i');
        odd02.oddaj('u');
        odd00.oddaj('u');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('D');
        odd10.oddaj('Z');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd01.oddaj('x');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd03.oddaj('B');
        odd04.oddaj('J');
        System.out.println(spr03.koliko());
        System.out.println(spr11.koliko());
        odd07.oddaj('d');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr07.koliko());
        odd04.oddaj('R');
        System.out.println(spr04.koliko());
        odd10.oddaj('D');
        odd04.oddaj('B');
        odd01.oddaj('o');
        odd05.oddaj('M');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd11.oddaj('n');
        System.out.println(spr01.koliko());
        odd11.oddaj('q');
        odd11.oddaj('R');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd11.oddaj('d');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd03.oddaj('X');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('K');
        odd07.oddaj('K');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd10.oddaj('C');
        odd00.oddaj('Q');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd10.oddaj('B');
        System.out.println(spr10.koliko());
        odd07.oddaj('u');
        odd07.oddaj('l');
        odd11.oddaj('v');
        System.out.println(spr07.koliko());
        odd07.oddaj('P');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        odd01.oddaj('A');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('j');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('y');
        System.out.println(spr02.koliko());
        odd07.oddaj('l');
        odd09.oddaj('z');
        odd02.oddaj('f');
        odd07.oddaj('l');
        odd10.oddaj('k');
        odd08.oddaj('B');
        odd01.oddaj('u');
        odd02.oddaj('k');
        System.out.println(spr10.koliko());
        odd08.oddaj('h');
        odd10.oddaj('o');
        odd05.oddaj('w');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('O');
        odd08.oddaj('P');
        odd00.oddaj('j');
        odd10.oddaj('I');
        odd05.oddaj('X');
        odd03.oddaj('O');
        odd02.oddaj('f');
        odd00.oddaj('Q');
        odd04.oddaj('R');
        odd10.oddaj('n');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('H');
        odd00.oddaj('U');
        System.out.println(spr04.koliko());
        odd01.oddaj('a');
        odd11.oddaj('R');
        odd03.oddaj('S');
        System.out.println(spr07.koliko());
        odd05.oddaj('t');
        odd04.oddaj('m');
        System.out.println(spr08.koliko());
        System.out.println(spr10.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd04.oddaj('F');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd06.oddaj('p');
        odd07.oddaj('e');
        odd10.oddaj('e');
        odd10.oddaj('j');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd03.oddaj('z');
        odd03.oddaj('H');
        odd06.oddaj('x');
        odd00.oddaj('Y');
        System.out.println(spr00.koliko());
        odd07.oddaj('f');
        odd10.oddaj('z');
        odd11.oddaj('D');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd05.oddaj('P');
        odd09.oddaj('x');
        odd11.oddaj('X');
        odd07.oddaj('m');
        odd10.oddaj('A');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd03.oddaj('K');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('G');
        odd11.oddaj('x');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd11.oddaj('I');
        odd09.oddaj('N');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd01.oddaj('f');
        System.out.println(spr05.koliko());
        odd05.oddaj('N');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd10.oddaj('Y');
        odd06.oddaj('r');
        odd08.oddaj('H');
        System.out.println(spr09.koliko());
        odd02.oddaj('K');
        odd05.oddaj('N');
        odd03.oddaj('t');
        System.out.println(spr01.koliko());
        odd01.oddaj('j');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('W');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd11.oddaj('a');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd00.oddaj('l');
        odd06.oddaj('B');
        odd04.oddaj('B');
        odd05.oddaj('T');
        System.out.println(spr03.koliko());
        odd06.oddaj('e');
        odd00.oddaj('T');
        System.out.println(spr00.koliko());
        odd02.oddaj('b');
        System.out.println(spr08.koliko());
        odd03.oddaj('r');
        System.out.println(spr01.koliko());
        odd06.oddaj('I');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('g');
        odd03.oddaj('q');
        odd09.oddaj('u');
        odd08.oddaj('K');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd09.oddaj('P');
        odd07.oddaj('x');
        odd02.oddaj('y');
        odd04.oddaj('A');
        odd00.oddaj('W');
        odd06.oddaj('i');
        odd07.oddaj('d');
        odd10.oddaj('n');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd09.oddaj('e');
        odd06.oddaj('g');
        odd04.oddaj('S');
        odd01.oddaj('c');
        odd09.oddaj('g');
        System.out.println(spr06.koliko());
        odd06.oddaj('o');
        odd04.oddaj('c');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd00.oddaj('P');
        odd02.oddaj('t');
        System.out.println(spr02.koliko());
        odd05.oddaj('W');
        System.out.println(spr07.koliko());
        odd03.oddaj('g');
        odd02.oddaj('x');
        System.out.println(spr02.koliko());
        odd08.oddaj('M');
        odd05.oddaj('H');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('F');
        System.out.println(spr01.koliko());
        odd10.oddaj('C');
        odd00.oddaj('O');
        odd00.oddaj('x');
        System.out.println(spr03.koliko());
        System.out.println(spr09.koliko());
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd08.oddaj('w');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('z');
        System.out.println(spr08.koliko());
        odd07.oddaj('y');
        odd02.oddaj('n');
        odd08.oddaj('a');
        odd10.oddaj('j');
        odd03.oddaj('C');
        odd05.oddaj('c');
        System.out.println(spr08.koliko());
        odd01.oddaj('b');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd00.oddaj('z');
        odd05.oddaj('d');
        System.out.println(spr07.koliko());
        System.out.println(spr05.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd11.oddaj('a');
        System.out.println(spr01.koliko());
        odd01.oddaj('j');
        odd07.oddaj('n');
        odd08.oddaj('a');
        System.out.println(spr08.koliko());
        odd01.oddaj('X');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd00.oddaj('Z');
        odd04.oddaj('n');
        odd06.oddaj('x');
        odd03.oddaj('j');
        odd10.oddaj('z');
        odd09.oddaj('I');
        odd06.oddaj('y');
        odd07.oddaj('s');
        odd11.oddaj('p');
        odd05.oddaj('B');
        odd08.oddaj('p');
        odd04.oddaj('p');
        System.out.println(spr00.koliko());
        System.out.println(spr04.koliko());
        odd11.oddaj('j');
        odd07.oddaj('x');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd08.oddaj('A');
        odd11.oddaj('A');
        odd00.oddaj('z');
        odd06.oddaj('c');
        odd10.oddaj('R');
        odd04.oddaj('W');
        odd02.oddaj('z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd06.oddaj('a');
        odd11.oddaj('Q');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd09.oddaj('M');
        odd04.oddaj('J');
        odd02.oddaj('d');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        System.out.println(spr11.koliko());
        odd03.oddaj('m');
        odd10.oddaj('L');
        odd02.oddaj('S');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd09.oddaj('E');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('h');
        odd08.oddaj('r');
        odd07.oddaj('C');
        odd00.oddaj('E');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('g');
        odd04.oddaj('I');
        odd02.oddaj('h');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd07.oddaj('k');
        odd08.oddaj('A');
        odd11.oddaj('Y');
        odd05.oddaj('q');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('a');
        odd03.oddaj('z');
        System.out.println(spr01.koliko());
        odd07.oddaj('q');
        System.out.println(spr05.koliko());
        odd08.oddaj('D');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('H');
        System.out.println(spr10.koliko());
        odd09.oddaj('Q');
        odd11.oddaj('F');
        System.out.println(spr07.koliko());
        odd10.oddaj('J');
        odd06.oddaj('B');
        odd02.oddaj('P');
        odd06.oddaj('U');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd08.oddaj('c');
        System.out.println(spr00.koliko());
        odd09.oddaj('N');
        System.out.println(spr11.koliko());
        odd00.oddaj('Z');
        System.out.println(spr03.koliko());
        odd10.oddaj('D');
        odd08.oddaj('g');
        odd11.oddaj('Y');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd03.oddaj('x');
        odd05.oddaj('A');
        odd04.oddaj('r');
        odd03.oddaj('Q');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd08.oddaj('S');
        odd02.oddaj('G');
        odd00.oddaj('d');
        odd07.oddaj('j');
        odd08.oddaj('b');
        odd10.oddaj('N');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('g');
        odd02.oddaj('s');
        odd06.oddaj('h');
        odd06.oddaj('g');
        System.out.println(spr09.koliko());
        System.out.println(spr08.koliko());
        odd02.oddaj('Y');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd06.oddaj('s');
        odd08.oddaj('F');
        odd04.oddaj('X');
        odd04.oddaj('d');
        odd09.oddaj('H');
        odd09.oddaj('S');
        odd09.oddaj('e');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd11.oddaj('L');
        odd05.oddaj('V');
        odd06.oddaj('H');
        System.out.println(spr04.koliko());
        odd01.oddaj('Z');
        System.out.println(spr09.koliko());
        System.out.println(spr03.koliko());
        System.out.println(spr06.koliko());
        odd03.oddaj('T');
        System.out.println(spr01.koliko());
        odd10.oddaj('a');
        odd01.oddaj('M');
        odd10.oddaj('V');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd08.oddaj('y');
        odd05.oddaj('C');
        System.out.println(spr08.koliko());
        odd05.oddaj('r');
        odd11.oddaj('C');
        odd06.oddaj('F');
        odd10.oddaj('j');
        System.out.println(spr10.koliko());
        odd04.oddaj('S');
        odd11.oddaj('y');
        odd04.oddaj('d');
        odd00.oddaj('H');
        System.out.println(spr00.koliko());
        odd02.oddaj('O');
        System.out.println(spr04.koliko());
        odd03.oddaj('d');
        odd06.oddaj('i');
        System.out.println(spr06.koliko());
        odd00.oddaj('A');
        odd11.oddaj('y');
        odd07.oddaj('O');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd09.oddaj('B');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd07.oddaj('I');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('U');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd02.oddaj('t');
        odd02.oddaj('C');
        odd07.oddaj('z');
        odd08.oddaj('j');
        odd04.oddaj('a');
        System.out.println(spr04.koliko());
        odd04.oddaj('o');
        odd11.oddaj('z');
        odd08.oddaj('D');
        System.out.println(spr11.koliko());
        odd01.oddaj('a');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        System.out.println(spr04.koliko());
        odd08.oddaj('J');
        odd01.oddaj('S');
        odd01.oddaj('c');
        odd10.oddaj('E');
        System.out.println(spr09.koliko());
        System.out.println(spr01.koliko());
        odd06.oddaj('n');
        odd07.oddaj('g');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd05.oddaj('J');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('u');
        odd08.oddaj('R');
        odd02.oddaj('I');
        odd00.oddaj('j');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd08.oddaj('n');
        odd09.oddaj('k');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('H');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('X');
        odd06.oddaj('s');
        odd06.oddaj('p');
        odd00.oddaj('a');
        odd01.oddaj('Q');
        odd10.oddaj('y');
        System.out.println(spr10.koliko());
        odd07.oddaj('p');
        System.out.println(spr06.koliko());
        odd01.oddaj('G');
        odd02.oddaj('M');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd03.oddaj('i');
        odd03.oddaj('m');
        odd07.oddaj('C');
        odd01.oddaj('V');
        odd08.oddaj('b');
        odd08.oddaj('p');
        System.out.println(spr02.koliko());
        odd00.oddaj('u');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('I');
        System.out.println(spr10.koliko());
        odd04.oddaj('n');
        System.out.println(spr07.koliko());
        odd02.oddaj('A');
        System.out.println(spr08.koliko());
        odd02.oddaj('E');
        odd07.oddaj('z');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd06.oddaj('E');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('Y');
        System.out.println(spr05.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('L');
        odd02.oddaj('C');
        odd03.oddaj('I');
        odd00.oddaj('q');
        System.out.println(spr07.koliko());
        odd07.oddaj('Q');
        odd09.oddaj('V');
        odd01.oddaj('w');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('A');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd07.oddaj('L');
        odd06.oddaj('e');
        System.out.println(spr03.koliko());
        odd01.oddaj('w');
        odd08.oddaj('O');
        odd02.oddaj('Z');
        odd02.oddaj('l');
        odd10.oddaj('c');
        odd07.oddaj('D');
        odd08.oddaj('x');
        odd00.oddaj('D');
        odd06.oddaj('w');
        odd06.oddaj('Y');
        odd07.oddaj('c');
        odd07.oddaj('T');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('R');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd06.oddaj('E');
        odd00.oddaj('Z');
        System.out.println(spr06.koliko());
        odd04.oddaj('T');
        odd08.oddaj('U');
        odd10.oddaj('T');
        System.out.println(spr10.koliko());
        odd09.oddaj('t');
        odd11.oddaj('X');
        odd03.oddaj('k');
        odd04.oddaj('B');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('Z');
        odd11.oddaj('k');
        odd00.oddaj('r');
        odd11.oddaj('p');
        odd03.oddaj('j');
        odd09.oddaj('y');
        odd06.oddaj('g');
        odd01.oddaj('C');
        odd03.oddaj('y');
        odd00.oddaj('Q');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('H');
        System.out.println(spr11.koliko());
        odd01.oddaj('A');
        odd08.oddaj('T');
        System.out.println(spr04.koliko());
        odd04.oddaj('y');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('u');
        odd09.oddaj('X');
        odd07.oddaj('j');
        odd08.oddaj('F');
        odd10.oddaj('G');
        odd07.oddaj('l');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd01.oddaj('F');
        odd09.oddaj('T');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd07.oddaj('b');
        odd10.oddaj('i');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd07.oddaj('F');
        System.out.println(spr07.koliko());
        odd05.oddaj('z');
        System.out.println(spr05.koliko());
        odd07.oddaj('c');
        System.out.println(spr07.koliko());
        odd01.oddaj('c');
        odd09.oddaj('M');
        odd03.oddaj('U');
        odd04.oddaj('j');
        System.out.println(spr04.koliko());
        odd08.oddaj('x');
        odd11.oddaj('O');
        odd07.oddaj('u');
        odd08.oddaj('a');
        odd07.oddaj('b');
        odd05.oddaj('p');
        odd06.oddaj('J');
        odd04.oddaj('Y');
        odd10.oddaj('B');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd03.oddaj('e');
        odd04.oddaj('G');
        odd04.oddaj('u');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd07.oddaj('Q');
        System.out.println(spr06.koliko());
        odd02.oddaj('p');
        System.out.println(spr02.koliko());
        odd09.oddaj('b');
        odd09.oddaj('B');
        odd04.oddaj('S');
        System.out.println(spr11.koliko());
        odd04.oddaj('H');
        odd01.oddaj('U');
        odd02.oddaj('L');
        odd01.oddaj('G');
        System.out.println(spr04.koliko());
        odd08.oddaj('E');
        odd00.oddaj('u');
        odd07.oddaj('s');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('J');
        odd05.oddaj('W');
        System.out.println(spr09.koliko());
        odd07.oddaj('S');
        odd05.oddaj('S');
        odd03.oddaj('Z');
        odd01.oddaj('W');
        odd01.oddaj('F');
        odd10.oddaj('P');
        odd01.oddaj('U');
        System.out.println(spr08.koliko());
        odd07.oddaj('e');
        odd07.oddaj('B');
        odd01.oddaj('j');
        odd00.oddaj('F');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd08.oddaj('i');
        odd09.oddaj('u');
        odd04.oddaj('E');
        odd11.oddaj('G');
        odd02.oddaj('q');
        odd03.oddaj('M');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd11.oddaj('J');
        System.out.println(spr04.koliko());
        odd06.oddaj('c');
        System.out.println(spr02.koliko());
        odd08.oddaj('J');
        odd00.oddaj('v');
        odd09.oddaj('Y');
        System.out.println(spr09.koliko());
        odd02.oddaj('g');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('Y');
        odd05.oddaj('C');
        odd09.oddaj('s');
        odd05.oddaj('v');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('o');
        odd08.oddaj('t');
        odd05.oddaj('k');
        odd05.oddaj('e');
        odd00.oddaj('V');
        odd10.oddaj('E');
        odd00.oddaj('X');
        odd09.oddaj('X');
        odd08.oddaj('c');
        odd11.oddaj('U');
        odd08.oddaj('Y');
        System.out.println(spr08.koliko());
        odd01.oddaj('z');
        odd03.oddaj('B');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('G');
        odd02.oddaj('s');
        odd03.oddaj('C');
        odd09.oddaj('X');
        odd10.oddaj('L');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('Z');
        odd01.oddaj('Z');
        odd06.oddaj('s');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('N');
        odd02.oddaj('M');
        System.out.println(spr01.koliko());
        odd05.oddaj('T');
        odd10.oddaj('S');
        odd05.oddaj('G');
        System.out.println(spr10.koliko());
        odd00.oddaj('U');
        System.out.println(spr05.koliko());
        odd03.oddaj('h');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd11.oddaj('G');
        odd04.oddaj('G');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd05.oddaj('U');
        odd02.oddaj('M');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr04.koliko());
        odd08.oddaj('a');
        System.out.println(spr02.koliko());
        System.out.println(spr00.koliko());
        odd10.oddaj('s');
        System.out.println(spr11.koliko());
        System.out.println(spr10.koliko());
        odd08.oddaj('f');
        odd07.oddaj('c');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd08.oddaj('g');
        odd08.oddaj('x');
        odd02.oddaj('o');
        odd08.oddaj('e');
        odd03.oddaj('a');
        odd01.oddaj('A');
        odd09.oddaj('G');
        odd03.oddaj('b');
        System.out.println(spr07.koliko());
        odd08.oddaj('I');
        odd02.oddaj('p');
        odd07.oddaj('L');
        odd07.oddaj('p');
        System.out.println(spr03.koliko());
        System.out.println(spr07.koliko());
        odd04.oddaj('B');
        odd06.oddaj('D');
        System.out.println(spr02.koliko());
        System.out.println(spr08.koliko());
        odd03.oddaj('l');
        odd05.oddaj('x');
        odd09.oddaj('k');
        odd03.oddaj('N');
        odd07.oddaj('T');
        odd10.oddaj('S');
        odd03.oddaj('R');
        odd07.oddaj('K');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd04.oddaj('h');
        odd09.oddaj('u');
        odd06.oddaj('h');
        System.out.println(spr06.koliko());
        odd08.oddaj('e');
        System.out.println(spr05.koliko());
        odd06.oddaj('r');
        odd05.oddaj('K');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd02.oddaj('H');
        odd05.oddaj('T');
        odd02.oddaj('b');
        odd11.oddaj('I');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('j');
        odd00.oddaj('y');
        System.out.println(spr10.koliko());
        odd03.oddaj('h');
        odd08.oddaj('M');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('i');
        odd09.oddaj('n');
        odd08.oddaj('e');
        odd10.oddaj('P');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('O');
        odd00.oddaj('h');
        odd03.oddaj('Q');
        odd03.oddaj('T');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd11.oddaj('g');
        odd04.oddaj('d');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd08.oddaj('q');
        odd06.oddaj('G');
        System.out.println(spr04.koliko());
        System.out.println(spr06.koliko());
        odd00.oddaj('I');
        odd04.oddaj('K');
        odd02.oddaj('q');
        odd01.oddaj('A');
        System.out.println(spr04.koliko());
        System.out.println(spr02.koliko());
    }
}
