
import java.util.*;

public class Test19 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd12);
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd13);

        odd01.oddaj('h');
        odd12.oddaj('V');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd10.oddaj('g');
        odd08.oddaj('e');
        odd04.oddaj('M');
        odd11.oddaj('M');
        odd05.oddaj('b');
        odd00.oddaj('f');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd01.oddaj('y');
        odd13.oddaj('F');
        odd00.oddaj('T');
        odd11.oddaj('k');
        odd00.oddaj('P');
        odd09.oddaj('Y');
        System.out.println(spr05.koliko());
        odd01.oddaj('q');
        odd00.oddaj('p');
        odd09.oddaj('F');
        odd01.oddaj('F');
        odd06.oddaj('e');
        odd00.oddaj('B');
        odd09.oddaj('C');
        System.out.println(spr00.koliko());
        System.out.println(spr08.koliko());
        odd01.oddaj('c');
        odd01.oddaj('Z');
        odd13.oddaj('s');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd12.oddaj('R');
        odd08.oddaj('o');
        odd08.oddaj('n');
        odd04.oddaj('j');
        odd09.oddaj('j');
        odd09.oddaj('G');
        odd00.oddaj('U');
        odd05.oddaj('C');
        odd00.oddaj('s');
        odd10.oddaj('u');
        odd10.oddaj('q');
        odd02.oddaj('T');
        System.out.println(spr08.koliko());
        odd12.oddaj('l');
        odd07.oddaj('J');
        odd04.oddaj('Q');
        odd13.oddaj('W');
        odd08.oddaj('W');
        odd11.oddaj('m');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd00.oddaj('Y');
        odd09.oddaj('v');
        odd12.oddaj('n');
        System.out.println(spr11.koliko());
        odd10.oddaj('d');
        odd07.oddaj('z');
        odd01.oddaj('m');
        odd00.oddaj('B');
        odd02.oddaj('v');
        odd09.oddaj('J');
        odd04.oddaj('u');
        odd06.oddaj('o');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd09.oddaj('r');
        odd08.oddaj('N');
        odd02.oddaj('w');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd12.oddaj('c');
        odd10.oddaj('T');
        odd00.oddaj('g');
        odd02.oddaj('x');
        odd05.oddaj('f');
        odd08.oddaj('y');
        odd12.oddaj('s');
        odd09.oddaj('c');
        odd13.oddaj('r');
        odd03.oddaj('G');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('N');
        odd03.oddaj('p');
        odd00.oddaj('I');
        odd03.oddaj('k');
        odd05.oddaj('m');
        odd09.oddaj('V');
        odd12.oddaj('x');
        odd04.oddaj('F');
        odd03.oddaj('f');
        odd11.oddaj('j');
        odd06.oddaj('k');
        System.out.println(spr08.koliko());
        odd05.oddaj('O');
        odd05.oddaj('W');
        odd06.oddaj('N');
        odd02.oddaj('o');
        odd04.oddaj('a');
        odd08.oddaj('t');
        odd03.oddaj('h');
        System.out.println(spr01.koliko());
        odd12.oddaj('U');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('S');
        odd00.oddaj('u');
        odd08.oddaj('Z');
        odd04.oddaj('y');
        odd01.oddaj('s');
        odd03.oddaj('s');
        System.out.println(spr03.koliko());
        odd04.oddaj('o');
        odd12.oddaj('r');
        System.out.println(spr00.koliko());
        odd01.oddaj('C');
        odd09.oddaj('a');
        odd01.oddaj('s');
        odd11.oddaj('d');
        odd05.oddaj('E');
        odd10.oddaj('I');
        odd00.oddaj('d');
        odd08.oddaj('V');
        odd02.oddaj('x');
        odd09.oddaj('T');
        odd09.oddaj('u');
        odd00.oddaj('K');
        odd09.oddaj('b');
        odd05.oddaj('I');
        odd06.oddaj('T');
        odd04.oddaj('E');
        odd10.oddaj('k');
        odd09.oddaj('M');
        odd09.oddaj('S');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd02.oddaj('Y');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd12.oddaj('Z');
        odd04.oddaj('U');
        odd00.oddaj('y');
        odd05.oddaj('n');
        odd11.oddaj('Z');
        odd02.oddaj('h');
        odd09.oddaj('I');
        odd08.oddaj('l');
        odd06.oddaj('C');
        odd13.oddaj('l');
        odd06.oddaj('G');
        odd10.oddaj('m');
        odd01.oddaj('w');
        odd13.oddaj('o');
        odd07.oddaj('E');
        odd10.oddaj('s');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd12.oddaj('K');
        odd12.oddaj('e');
        odd08.oddaj('A');
        odd05.oddaj('Y');
        odd05.oddaj('F');
        odd03.oddaj('m');
        odd12.oddaj('h');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd13.oddaj('B');
        odd04.oddaj('b');
        odd07.oddaj('L');
        odd12.oddaj('N');
        odd02.oddaj('K');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd01.oddaj('s');
        odd04.oddaj('I');
        odd07.oddaj('L');
        odd08.oddaj('z');
        odd12.oddaj('s');
        odd02.oddaj('X');
        odd11.oddaj('H');
        odd07.oddaj('L');
        System.out.println(spr12.koliko());
        System.out.println(spr11.koliko());
        odd12.oddaj('b');
        odd00.oddaj('M');
        odd06.oddaj('C');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('x');
        odd11.oddaj('i');
        odd01.oddaj('h');
        System.out.println(spr07.koliko());
        odd09.oddaj('O');
        odd12.oddaj('v');
        odd06.oddaj('M');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd07.oddaj('h');
        odd02.oddaj('q');
        odd01.oddaj('Q');
        odd05.oddaj('T');
        odd10.oddaj('j');
        odd13.oddaj('C');
        odd10.oddaj('d');
        odd12.oddaj('X');
        odd12.oddaj('W');
        odd10.oddaj('e');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('f');
        odd03.oddaj('h');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd07.oddaj('J');
        odd09.oddaj('Q');
        odd09.oddaj('p');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd02.oddaj('S');
        odd07.oddaj('b');
        odd11.oddaj('I');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd03.oddaj('E');
        odd12.oddaj('C');
        odd12.oddaj('L');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd13.oddaj('t');
        odd07.oddaj('F');
        odd01.oddaj('y');
        odd05.oddaj('e');
        odd06.oddaj('W');
        odd07.oddaj('T');
        odd12.oddaj('E');
        odd04.oddaj('m');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd10.oddaj('Y');
        odd08.oddaj('v');
        odd06.oddaj('N');
        odd11.oddaj('o');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('R');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd01.oddaj('t');
        odd08.oddaj('W');
        odd11.oddaj('I');
        odd08.oddaj('g');
        odd13.oddaj('n');
        odd08.oddaj('x');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd09.oddaj('A');
        odd00.oddaj('Y');
        odd08.oddaj('r');
        odd06.oddaj('t');
        odd05.oddaj('y');
        System.out.println(spr09.koliko());
        odd12.oddaj('W');
        odd11.oddaj('U');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd10.oddaj('o');
        odd07.oddaj('Q');
        odd07.oddaj('y');
        System.out.println(spr08.koliko());
        odd13.oddaj('x');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd10.oddaj('z');
        odd06.oddaj('g');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd07.oddaj('J');
        odd13.oddaj('B');
        odd03.oddaj('V');
        odd06.oddaj('h');
        odd01.oddaj('W');
        odd12.oddaj('z');
        odd01.oddaj('Y');
        odd12.oddaj('z');
        odd06.oddaj('S');
        odd02.oddaj('I');
        System.out.println(spr05.koliko());
        odd13.oddaj('A');
        odd09.oddaj('A');
        odd01.oddaj('l');
        System.out.println(spr09.koliko());
        odd12.oddaj('h');
        System.out.println(spr13.koliko());
        odd11.oddaj('M');
        odd03.oddaj('e');
        System.out.println(spr06.koliko());
        odd01.oddaj('M');
        odd03.oddaj('J');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('S');
        System.out.println(spr12.koliko());
        odd10.oddaj('r');
        odd00.oddaj('n');
        odd01.oddaj('k');
        odd09.oddaj('l');
        odd06.oddaj('E');
        odd03.oddaj('j');
        odd06.oddaj('H');
        odd06.oddaj('p');
        System.out.println(spr02.koliko());
        odd03.oddaj('W');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd09.oddaj('Y');
        odd08.oddaj('Y');
        odd11.oddaj('q');
        odd05.oddaj('L');
        odd10.oddaj('z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd11.oddaj('y');
        odd00.oddaj('K');
        System.out.println(spr09.koliko());
        odd04.oddaj('Q');
        odd12.oddaj('x');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('w');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        odd10.oddaj('b');
        odd03.oddaj('S');
        odd11.oddaj('F');
        System.out.println(spr12.koliko());
        odd08.oddaj('Q');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd05.oddaj('t');
        odd01.oddaj('J');
        odd05.oddaj('Y');
        System.out.println(spr03.koliko());
        odd03.oddaj('t');
        System.out.println(spr05.koliko());
        System.out.println(spr01.koliko());
        odd11.oddaj('a');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd06.oddaj('q');
        odd00.oddaj('Y');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('G');
        odd10.oddaj('W');
        odd08.oddaj('E');
        odd11.oddaj('B');
        odd08.oddaj('n');
        odd09.oddaj('r');
        odd05.oddaj('J');
        odd09.oddaj('r');
        odd06.oddaj('C');
        odd02.oddaj('Y');
        odd03.oddaj('G');
        odd01.oddaj('m');
        System.out.println(spr00.koliko());
        odd02.oddaj('p');
        System.out.println(spr08.koliko());
        odd01.oddaj('R');
        odd13.oddaj('o');
        odd01.oddaj('P');
        odd10.oddaj('R');
        odd12.oddaj('I');
        System.out.println(spr12.koliko());
        odd06.oddaj('q');
        odd13.oddaj('r');
        System.out.println(spr06.koliko());
        odd12.oddaj('h');
        odd04.oddaj('S');
        odd05.oddaj('h');
        odd00.oddaj('S');
        odd09.oddaj('B');
        odd09.oddaj('d');
        odd12.oddaj('x');
        odd02.oddaj('p');
        odd01.oddaj('y');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd00.oddaj('u');
        odd02.oddaj('b');
        odd01.oddaj('h');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println(spr11.koliko());
        odd05.oddaj('U');
        odd08.oddaj('K');
        odd09.oddaj('g');
        odd09.oddaj('f');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd01.oddaj('V');
        System.out.println(spr12.koliko());
        odd05.oddaj('g');
        odd00.oddaj('q');
        odd12.oddaj('q');
        odd13.oddaj('f');
        odd08.oddaj('U');
        odd05.oddaj('G');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd07.oddaj('L');
        odd10.oddaj('c');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('M');
        odd11.oddaj('Y');
        odd07.oddaj('z');
        odd02.oddaj('f');
        odd03.oddaj('g');
        odd11.oddaj('A');
        odd03.oddaj('t');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd00.oddaj('H');
        odd08.oddaj('r');
        System.out.println(spr08.koliko());
        odd08.oddaj('Z');
        odd01.oddaj('Q');
        odd01.oddaj('O');
        System.out.println(spr08.koliko());
        odd05.oddaj('N');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('G');
        odd11.oddaj('D');
        odd06.oddaj('i');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd09.oddaj('k');
        odd00.oddaj('H');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('J');
        odd06.oddaj('f');
        odd06.oddaj('o');
        odd11.oddaj('C');
        System.out.println(spr09.koliko());
        System.out.println(spr05.koliko());
        System.out.println(spr07.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd02.oddaj('X');
        System.out.println(spr03.koliko());
        odd00.oddaj('b');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd11.oddaj('u');
        odd03.oddaj('R');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('l');
        odd10.oddaj('t');
        odd09.oddaj('j');
        odd05.oddaj('S');
        odd08.oddaj('N');
        System.out.println(spr09.koliko());
        odd04.oddaj('j');
        odd05.oddaj('v');
        odd13.oddaj('b');
        odd12.oddaj('p');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd05.oddaj('f');
        odd10.oddaj('k');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd03.oddaj('Y');
        System.out.println(spr11.koliko());
        odd02.oddaj('C');
        odd03.oddaj('V');
        odd04.oddaj('E');
        odd07.oddaj('J');
        odd10.oddaj('Z');
        System.out.println(spr03.koliko());
        odd05.oddaj('F');
        odd13.oddaj('O');
        odd08.oddaj('S');
        odd11.oddaj('E');
        System.out.println(spr08.koliko());
        odd08.oddaj('n');
        odd05.oddaj('I');
        odd11.oddaj('U');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd12.oddaj('V');
        odd04.oddaj('c');
        odd08.oddaj('M');
        odd02.oddaj('x');
        odd03.oddaj('Z');
        odd11.oddaj('I');
        odd03.oddaj('Y');
        odd08.oddaj('u');
        odd03.oddaj('y');
        odd03.oddaj('F');
        odd11.oddaj('R');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd00.oddaj('W');
        odd07.oddaj('d');
        odd13.oddaj('q');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        System.out.println(spr04.koliko());
        odd13.oddaj('d');
        odd13.oddaj('p');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('T');
        odd08.oddaj('n');
        odd06.oddaj('F');
        odd04.oddaj('d');
        odd00.oddaj('H');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd07.oddaj('b');
        odd06.oddaj('C');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('R');
        System.out.println(spr03.koliko());
        odd12.oddaj('T');
        odd07.oddaj('l');
        odd04.oddaj('C');
        odd11.oddaj('c');
        odd11.oddaj('H');
        System.out.println(spr02.koliko());
        odd03.oddaj('t');
        odd12.oddaj('M');
        System.out.println(spr13.koliko());
        odd03.oddaj('c');
        odd00.oddaj('J');
        odd11.oddaj('q');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('l');
        odd00.oddaj('p');
        odd04.oddaj('T');
        System.out.println(spr11.koliko());
        odd07.oddaj('b');
        odd08.oddaj('h');
        odd00.oddaj('I');
        odd07.oddaj('H');
        odd02.oddaj('Q');
        odd05.oddaj('y');
        odd07.oddaj('k');
        odd02.oddaj('u');
        System.out.println(spr08.koliko());
        odd09.oddaj('C');
        odd04.oddaj('I');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd12.oddaj('Y');
        System.out.println(spr04.koliko());
        odd10.oddaj('h');
        System.out.println(spr10.koliko());
        System.out.println(spr02.koliko());
        odd13.oddaj('f');
        odd09.oddaj('D');
        odd01.oddaj('Q');
        System.out.println(spr07.koliko());
        odd13.oddaj('Y');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd08.oddaj('S');
        System.out.println(spr12.koliko());
        odd03.oddaj('L');
        odd11.oddaj('y');
        odd12.oddaj('Q');
        odd04.oddaj('R');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd13.oddaj('g');
        odd05.oddaj('z');
        odd06.oddaj('P');
        odd09.oddaj('z');
        odd06.oddaj('y');
        odd05.oddaj('T');
        odd00.oddaj('G');
        System.out.println(spr00.koliko());
        odd06.oddaj('w');
        odd12.oddaj('O');
        odd04.oddaj('K');
        odd08.oddaj('T');
        odd13.oddaj('g');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd03.oddaj('M');
        odd06.oddaj('W');
        odd10.oddaj('g');
        odd07.oddaj('C');
        odd09.oddaj('b');
        odd11.oddaj('H');
        odd12.oddaj('c');
        odd08.oddaj('l');
        odd08.oddaj('k');
        System.out.println(spr03.koliko());
        odd05.oddaj('K');
        odd04.oddaj('a');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('J');
        System.out.println(spr05.koliko());
        odd10.oddaj('G');
        odd07.oddaj('G');
        odd10.oddaj('W');
        odd12.oddaj('P');
        odd04.oddaj('w');
        odd01.oddaj('P');
        odd00.oddaj('u');
        odd11.oddaj('p');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd13.oddaj('u');
        odd01.oddaj('W');
        odd04.oddaj('r');
        odd10.oddaj('a');
        odd03.oddaj('M');
        odd03.oddaj('g');
        odd06.oddaj('r');
        odd08.oddaj('k');
        odd01.oddaj('c');
        odd00.oddaj('G');
        System.out.println(spr01.koliko());
        odd09.oddaj('D');
        odd13.oddaj('u');
        odd04.oddaj('m');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd12.oddaj('U');
        odd02.oddaj('Z');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd07.oddaj('q');
        odd07.oddaj('v');
        odd02.oddaj('z');
        odd01.oddaj('R');
        odd03.oddaj('m');
        odd05.oddaj('q');
        odd13.oddaj('z');
        odd06.oddaj('V');
        odd04.oddaj('R');
        odd10.oddaj('j');
        odd10.oddaj('H');
        odd00.oddaj('R');
        odd05.oddaj('e');
        odd07.oddaj('Y');
        odd00.oddaj('z');
        System.out.println(spr05.koliko());
        odd13.oddaj('A');
        odd02.oddaj('p');
        System.out.println(spr07.koliko());
        odd13.oddaj('A');
        odd10.oddaj('F');
        odd06.oddaj('L');
        odd05.oddaj('Y');
        odd07.oddaj('S');
        odd05.oddaj('r');
        odd02.oddaj('H');
        odd07.oddaj('Q');
        odd02.oddaj('Q');
        odd07.oddaj('A');
        odd00.oddaj('J');
        odd02.oddaj('t');
        System.out.println(spr00.koliko());
        odd11.oddaj('O');
        odd12.oddaj('I');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('g');
        odd06.oddaj('B');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd09.oddaj('M');
        odd02.oddaj('C');
        odd01.oddaj('A');
        odd02.oddaj('i');
        odd02.oddaj('K');
        odd04.oddaj('Z');
        odd12.oddaj('v');
        odd11.oddaj('K');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('k');
        odd11.oddaj('p');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd00.oddaj('e');
        System.out.println(spr00.koliko());
        odd13.oddaj('A');
        odd02.oddaj('j');
        odd10.oddaj('T');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd11.oddaj('U');
        odd05.oddaj('I');
        odd10.oddaj('j');
        odd06.oddaj('X');
        odd00.oddaj('p');
        System.out.println(spr13.koliko());
        odd10.oddaj('q');
        odd09.oddaj('a');
        odd08.oddaj('e');
        odd01.oddaj('X');
        odd13.oddaj('d');
        odd04.oddaj('d');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd09.oddaj('V');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr08.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd05.oddaj('t');
        odd07.oddaj('g');
        odd09.oddaj('V');
        odd07.oddaj('L');
        odd09.oddaj('U');
        odd08.oddaj('e');
        odd13.oddaj('e');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd05.oddaj('u');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd13.oddaj('j');
        System.out.println(spr10.koliko());
        odd05.oddaj('F');
        odd05.oddaj('L');
        odd01.oddaj('X');
        odd11.oddaj('e');
        odd03.oddaj('q');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('L');
        odd03.oddaj('C');
        odd12.oddaj('P');
        odd07.oddaj('W');
        odd00.oddaj('q');
        odd09.oddaj('W');
        odd02.oddaj('G');
        odd05.oddaj('L');
        System.out.println(spr07.koliko());
        odd11.oddaj('C');
        odd06.oddaj('x');
        System.out.println(spr11.koliko());
        odd05.oddaj('w');
        System.out.println(spr13.koliko());
        odd04.oddaj('S');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd02.oddaj('A');
        odd12.oddaj('X');
        odd08.oddaj('X');
        odd07.oddaj('C');
        odd05.oddaj('B');
        odd00.oddaj('A');
        odd07.oddaj('E');
        odd13.oddaj('B');
        odd11.oddaj('o');
        odd02.oddaj('G');
        odd03.oddaj('G');
        odd13.oddaj('R');
        odd09.oddaj('v');
        System.out.println(spr04.koliko());
        odd03.oddaj('m');
        odd02.oddaj('t');
        odd01.oddaj('n');
        odd09.oddaj('p');
        odd13.oddaj('l');
        odd04.oddaj('P');
        odd05.oddaj('v');
        odd02.oddaj('S');
        odd06.oddaj('O');
        odd06.oddaj('z');
        odd05.oddaj('Q');
        odd06.oddaj('U');
        System.out.println(spr09.koliko());
        odd00.oddaj('x');
        odd05.oddaj('l');
        odd03.oddaj('r');
        odd11.oddaj('a');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd11.oddaj('u');
        odd10.oddaj('t');
        odd03.oddaj('j');
        System.out.println(spr10.koliko());
        System.out.println(spr12.koliko());
        System.out.println(spr02.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd00.oddaj('D');
        odd09.oddaj('O');
        odd03.oddaj('h');
        System.out.println(spr00.koliko());
        odd02.oddaj('F');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd04.oddaj('I');
        odd10.oddaj('n');
        odd05.oddaj('r');
        odd00.oddaj('H');
        odd07.oddaj('y');
        odd11.oddaj('v');
        odd10.oddaj('B');
        odd07.oddaj('T');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('Z');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd01.oddaj('g');
        odd06.oddaj('G');
        odd06.oddaj('A');
        odd02.oddaj('Q');
        odd01.oddaj('s');
        odd00.oddaj('x');
        odd08.oddaj('O');
        System.out.println(spr06.koliko());
        odd04.oddaj('v');
        System.out.println(spr10.koliko());
        odd04.oddaj('D');
        odd08.oddaj('o');
        odd10.oddaj('J');
        odd07.oddaj('z');
        odd12.oddaj('S');
        odd07.oddaj('u');
        odd03.oddaj('S');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd10.oddaj('r');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('E');
        odd04.oddaj('i');
        odd05.oddaj('g');
        odd12.oddaj('R');
        odd10.oddaj('C');
        odd10.oddaj('B');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd10.oddaj('c');
        odd04.oddaj('l');
        odd11.oddaj('K');
        System.out.println(spr04.koliko());
        odd05.oddaj('l');
        odd01.oddaj('Q');
        odd07.oddaj('e');
        odd13.oddaj('B');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        System.out.println(spr08.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('y');
        odd05.oddaj('e');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd12.oddaj('t');
        odd09.oddaj('I');
        odd04.oddaj('J');
        odd00.oddaj('I');
        odd03.oddaj('m');
        odd03.oddaj('M');
        System.out.println(spr10.koliko());
        odd06.oddaj('p');
        odd00.oddaj('Z');
        odd04.oddaj('f');
        odd00.oddaj('w');
        odd00.oddaj('W');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd12.oddaj('i');
        odd07.oddaj('E');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd11.oddaj('N');
        odd09.oddaj('G');
        odd01.oddaj('l');
        System.out.println(spr06.koliko());
        odd08.oddaj('y');
        odd07.oddaj('I');
        odd03.oddaj('n');
        odd03.oddaj('V');
        odd07.oddaj('C');
        odd09.oddaj('t');
        odd03.oddaj('Y');
        odd10.oddaj('h');
        odd00.oddaj('O');
        odd00.oddaj('F');
        odd09.oddaj('u');
        odd08.oddaj('i');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('E');
        odd05.oddaj('M');
        odd10.oddaj('d');
        odd08.oddaj('e');
        odd02.oddaj('U');
        odd11.oddaj('M');
        odd10.oddaj('P');
        odd00.oddaj('U');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd09.oddaj('z');
        odd01.oddaj('T');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('s');
        odd07.oddaj('U');
        odd12.oddaj('v');
        odd03.oddaj('c');
        odd12.oddaj('m');
        odd03.oddaj('v');
        odd10.oddaj('G');
        odd07.oddaj('r');
        odd05.oddaj('W');
        odd03.oddaj('q');
        System.out.println(spr09.koliko());
        odd11.oddaj('Z');
        odd10.oddaj('f');
        odd01.oddaj('T');
        odd06.oddaj('u');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd11.oddaj('d');
        odd02.oddaj('k');
        odd10.oddaj('E');
        odd03.oddaj('W');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd13.oddaj('k');
        odd12.oddaj('T');
        odd08.oddaj('e');
        odd11.oddaj('l');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd00.oddaj('y');
        odd06.oddaj('S');
        odd01.oddaj('w');
        System.out.println(spr01.koliko());
        System.out.println(spr10.koliko());
        odd08.oddaj('i');
        odd08.oddaj('a');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('Z');
        odd00.oddaj('h');
        odd06.oddaj('d');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd10.oddaj('f');
        odd10.oddaj('r');
        odd08.oddaj('k');
        odd07.oddaj('P');
        odd10.oddaj('n');
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd09.oddaj('A');
        odd10.oddaj('o');
        System.out.println(spr10.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('R');
        odd12.oddaj('U');
        odd08.oddaj('e');
        odd13.oddaj('O');
        odd09.oddaj('m');
        odd13.oddaj('c');
        odd01.oddaj('g');
        System.out.println(spr08.koliko());
        odd08.oddaj('z');
        odd03.oddaj('y');
        odd13.oddaj('C');
        odd06.oddaj('H');
        odd12.oddaj('O');
        odd03.oddaj('V');
        odd07.oddaj('T');
        odd10.oddaj('a');
        odd09.oddaj('n');
        odd11.oddaj('I');
    }
}
