
import java.util.*;

public class Test25 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd12);
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd13);
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd14);
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd15);
        Tretja.Oddajnik odd16 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd16);
        Tretja.Oddajnik odd17 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd17);
        Tretja.Oddajnik odd18 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd18);

        odd11.oddaj('h');
        odd17.oddaj('p');
        odd17.oddaj('w');
        odd00.oddaj('z');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd09.oddaj('o');
        odd08.oddaj('p');
        odd09.oddaj('T');
        odd08.oddaj('A');
        odd16.oddaj('A');
        odd08.oddaj('C');
        System.out.println(spr08.koliko());
        System.out.println(spr16.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd15.oddaj('o');
        odd18.oddaj('s');
        odd02.oddaj('U');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd17.oddaj('l');
        odd13.oddaj('i');
        odd13.oddaj('Y');
        odd10.oddaj('g');
        System.out.println(spr09.koliko());
        odd03.oddaj('e');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd16.oddaj('K');
        odd12.oddaj('M');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd03.oddaj('T');
        odd17.oddaj('M');
        System.out.println(spr15.koliko());
        odd16.oddaj('L');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd09.oddaj('S');
        System.out.println(spr09.koliko());
        odd16.oddaj('C');
        odd01.oddaj('s');
        odd11.oddaj('v');
        odd05.oddaj('I');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('p');
        odd10.oddaj('a');
        System.out.println(spr11.koliko());
        odd00.oddaj('s');
        odd08.oddaj('T');
        odd00.oddaj('O');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd01.oddaj('z');
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd12.oddaj('N');
        odd18.oddaj('P');
        odd08.oddaj('Z');
        odd09.oddaj('a');
        System.out.println(spr08.koliko());
        odd09.oddaj('q');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        odd17.oddaj('E');
        System.out.println(spr09.koliko());
        odd03.oddaj('L');
        System.out.println(spr18.koliko());
        System.out.println(spr01.koliko());
        odd05.oddaj('l');
        odd08.oddaj('S');
        odd07.oddaj('Z');
        odd06.oddaj('k');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd06.oddaj('E');
        odd16.oddaj('t');
        odd12.oddaj('Y');
        System.out.println(spr17.koliko());
        odd15.oddaj('O');
        odd04.oddaj('F');
        odd05.oddaj('L');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd00.oddaj('w');
        odd13.oddaj('a');
        System.out.println(spr07.koliko());
        odd09.oddaj('n');
        odd15.oddaj('M');
        odd12.oddaj('Z');
        odd08.oddaj('S');
        odd08.oddaj('D');
        odd05.oddaj('V');
        System.out.println(spr12.koliko());
        odd06.oddaj('p');
        odd11.oddaj('K');
        odd03.oddaj('j');
        odd01.oddaj('R');
        odd14.oddaj('D');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('U');
        odd01.oddaj('J');
        odd00.oddaj('A');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        System.out.println(spr09.koliko());
        odd04.oddaj('x');
        odd11.oddaj('n');
        odd04.oddaj('H');
        odd09.oddaj('I');
        odd04.oddaj('k');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd00.oddaj('L');
        odd17.oddaj('v');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('r');
        odd17.oddaj('I');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd00.oddaj('V');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('R');
        odd12.oddaj('k');
        odd16.oddaj('a');
        System.out.println(spr11.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd18.oddaj('T');
        odd05.oddaj('a');
        odd05.oddaj('c');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd03.oddaj('l');
        System.out.println(spr18.koliko());
        odd00.oddaj('N');
        odd12.oddaj('A');
        System.out.println(spr01.koliko());
        odd08.oddaj('V');
        System.out.println(spr03.koliko());
        System.out.println(spr08.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd07.oddaj('t');
        System.out.println(spr07.koliko());
        odd05.oddaj('R');
        odd10.oddaj('p');
        odd04.oddaj('F');
        odd03.oddaj('w');
        odd16.oddaj('X');
        odd05.oddaj('K');
        odd10.oddaj('P');
        odd18.oddaj('w');
        System.out.println(spr10.koliko());
        odd07.oddaj('q');
        odd09.oddaj('h');
        odd09.oddaj('H');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd01.oddaj('E');
        odd16.oddaj('d');
        odd11.oddaj('H');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd04.oddaj('Q');
        odd14.oddaj('G');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd13.oddaj('f');
        System.out.println(spr16.koliko());
        System.out.println(spr13.koliko());
        System.out.println(spr05.koliko());
        odd15.oddaj('x');
        odd00.oddaj('c');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd02.oddaj('L');
        odd09.oddaj('D');
        odd06.oddaj('L');
        odd00.oddaj('D');
        odd05.oddaj('q');
        odd04.oddaj('O');
        odd08.oddaj('n');
        System.out.println(spr15.koliko());
        System.out.println(spr14.koliko());
        odd09.oddaj('U');
        odd04.oddaj('g');
        odd15.oddaj('q');
        odd00.oddaj('P');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd05.oddaj('D');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd08.oddaj('d');
        odd07.oddaj('N');
        odd07.oddaj('o');
        odd02.oddaj('A');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd11.oddaj('g');
        odd09.oddaj('H');
        odd10.oddaj('q');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd15.oddaj('z');
        odd01.oddaj('E');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd18.oddaj('F');
        odd14.oddaj('N');
        odd16.oddaj('g');
        System.out.println(spr11.koliko());
        System.out.println(spr15.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd13.oddaj('r');
        odd04.oddaj('q');
        odd15.oddaj('A');
        odd14.oddaj('j');
        System.out.println(spr16.koliko());
        System.out.println(spr13.koliko());
        odd10.oddaj('h');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        odd00.oddaj('g');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd10.oddaj('g');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd15.oddaj('G');
        odd18.oddaj('I');
        odd09.oddaj('P');
        odd07.oddaj('w');
        odd11.oddaj('r');
        odd03.oddaj('U');
        odd02.oddaj('P');
        System.out.println(spr18.koliko());
        System.out.println(spr03.koliko());
        odd02.oddaj('v');
        odd01.oddaj('b');
        odd14.oddaj('B');
        odd14.oddaj('d');
        System.out.println(spr07.koliko());
        odd03.oddaj('Q');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd13.oddaj('o');
        odd15.oddaj('W');
        odd17.oddaj('F');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd16.oddaj('m');
        odd18.oddaj('I');
        System.out.println(spr11.koliko());
        odd07.oddaj('z');
        odd02.oddaj('W');
        odd10.oddaj('K');
        odd12.oddaj('W');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd18.oddaj('H');
        odd00.oddaj('v');
        odd11.oddaj('V');
        odd12.oddaj('t');
        odd06.oddaj('v');
        odd14.oddaj('E');
        System.out.println(spr02.koliko());
        System.out.println(spr00.koliko());
        odd13.oddaj('n');
        odd13.oddaj('o');
        odd15.oddaj('l');
        odd02.oddaj('z');
        odd05.oddaj('K');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd00.oddaj('q');
        odd11.oddaj('d');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        odd10.oddaj('k');
        odd01.oddaj('q');
        odd16.oddaj('p');
        odd01.oddaj('I');
        odd18.oddaj('A');
        odd18.oddaj('M');
        System.out.println(spr00.koliko());
        odd07.oddaj('t');
        odd17.oddaj('r');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd06.oddaj('L');
        System.out.println(spr02.koliko());
        odd09.oddaj('Z');
        odd18.oddaj('O');
        System.out.println(spr16.koliko());
        odd04.oddaj('K');
        odd02.oddaj('k');
        odd03.oddaj('I');
        System.out.println(spr09.koliko());
        System.out.println(spr02.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd11.oddaj('x');
        odd14.oddaj('t');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd03.oddaj('M');
        System.out.println(spr11.koliko());
        odd06.oddaj('p');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        System.out.println(spr10.koliko());
        odd12.oddaj('M');
        odd16.oddaj('e');
        odd05.oddaj('K');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd12.oddaj('e');
        odd13.oddaj('g');
        odd03.oddaj('L');
        odd08.oddaj('E');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd13.oddaj('g');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('y');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd01.oddaj('a');
        odd17.oddaj('v');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd10.oddaj('e');
        System.out.println(spr01.koliko());
        odd01.oddaj('v');
        System.out.println(spr12.koliko());
        odd05.oddaj('O');
        odd16.oddaj('U');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        odd16.oddaj('s');
        odd15.oddaj('P');
        odd06.oddaj('v');
        System.out.println(spr08.koliko());
        odd06.oddaj('f');
        odd16.oddaj('D');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd16.oddaj('J');
        odd01.oddaj('D');
        System.out.println(spr17.koliko());
        System.out.println(spr16.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd14.oddaj('Y');
        odd02.oddaj('V');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd04.oddaj('F');
        odd03.oddaj('I');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('R');
        odd13.oddaj('Z');
        odd03.oddaj('c');
        odd09.oddaj('M');
        odd09.oddaj('l');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd07.oddaj('q');
        odd17.oddaj('r');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd14.oddaj('Y');
        System.out.println(spr09.koliko());
        System.out.println(spr13.koliko());
        System.out.println(spr17.koliko());
        odd08.oddaj('h');
        odd05.oddaj('u');
        odd04.oddaj('u');
        System.out.println(spr14.koliko());
        odd11.oddaj('J');
        odd07.oddaj('A');
        odd02.oddaj('b');
        System.out.println(spr07.koliko());
        odd13.oddaj('H');
        odd18.oddaj('S');
        System.out.println(spr08.koliko());
        odd12.oddaj('w');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd15.oddaj('k');
        System.out.println(spr18.koliko());
        odd04.oddaj('B');
        System.out.println(spr15.koliko());
        odd03.oddaj('g');
        odd12.oddaj('d');
        System.out.println(spr12.koliko());
        odd10.oddaj('Y');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd09.oddaj('M');
        odd10.oddaj('A');
        odd01.oddaj('n');
        odd02.oddaj('w');
        System.out.println(spr01.koliko());
        odd10.oddaj('p');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd13.oddaj('S');
        odd17.oddaj('Z');
        odd16.oddaj('V');
        System.out.println(spr03.koliko());
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('w');
        odd02.oddaj('u');
        odd03.oddaj('C');
        System.out.println(spr04.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd07.oddaj('P');
        odd10.oddaj('Y');
        System.out.println(spr02.koliko());
        odd00.oddaj('F');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd04.oddaj('B');
        odd16.oddaj('q');
        odd10.oddaj('J');
        odd13.oddaj('L');
        System.out.println(spr09.koliko());
        odd00.oddaj('X');
        System.out.println(spr00.koliko());
        odd13.oddaj('v');
        odd06.oddaj('E');
        odd08.oddaj('P');
        odd00.oddaj('W');
        odd13.oddaj('N');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd13.oddaj('d');
        odd08.oddaj('j');
        odd16.oddaj('A');
        System.out.println(spr00.koliko());
        System.out.println(spr08.koliko());
        odd05.oddaj('a');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd15.oddaj('V');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd06.oddaj('N');
        odd06.oddaj('d');
        System.out.println(spr04.koliko());
        odd02.oddaj('o');
        odd03.oddaj('D');
        odd06.oddaj('a');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('H');
        odd03.oddaj('k');
        odd16.oddaj('O');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd05.oddaj('L');
        System.out.println(spr06.koliko());
        odd16.oddaj('b');
        odd17.oddaj('p');
        odd09.oddaj('A');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd06.oddaj('U');
        System.out.println(spr07.koliko());
        odd15.oddaj('T');
        odd18.oddaj('n');
        odd16.oddaj('Y');
        odd05.oddaj('D');
        odd00.oddaj('j');
        System.out.println(spr05.koliko());
        odd15.oddaj('F');
        odd11.oddaj('A');
        odd01.oddaj('o');
        odd04.oddaj('R');
        odd10.oddaj('Y');
        System.out.println(spr03.koliko());
        odd16.oddaj('t');
        odd13.oddaj('X');
        odd15.oddaj('c');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd13.oddaj('p');
        System.out.println(spr11.koliko());
        System.out.println(spr00.koliko());
        System.out.println(spr16.koliko());
        System.out.println(spr02.koliko());
        odd10.oddaj('H');
        odd06.oddaj('G');
        odd14.oddaj('D');
        odd02.oddaj('I');
        System.out.println(spr01.koliko());
        odd10.oddaj('H');
        odd18.oddaj('r');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd13.oddaj('o');
        odd05.oddaj('x');
        odd13.oddaj('O');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd15.oddaj('N');
        System.out.println(spr02.koliko());
        odd12.oddaj('L');
        System.out.println(spr09.koliko());
        odd00.oddaj('v');
        odd06.oddaj('z');
        System.out.println(spr14.koliko());
        odd07.oddaj('d');
        System.out.println(spr00.koliko());
        System.out.println(spr10.koliko());
        System.out.println(spr18.koliko());
        System.out.println(spr07.koliko());
        odd11.oddaj('I');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd12.oddaj('e');
        odd16.oddaj('K');
        odd03.oddaj('z');
        odd00.oddaj('I');
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd11.oddaj('n');
        odd09.oddaj('v');
        odd12.oddaj('z');
        odd17.oddaj('U');
        System.out.println(spr00.koliko());
        odd01.oddaj('v');
        odd00.oddaj('z');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd12.oddaj('W');
        odd04.oddaj('r');
        odd16.oddaj('M');
        odd05.oddaj('l');
        odd13.oddaj('j');
        System.out.println(spr01.koliko());
        System.out.println(spr12.koliko());
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr09.koliko());
        odd10.oddaj('m');
        odd15.oddaj('i');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd12.oddaj('m');
        odd15.oddaj('m');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd08.oddaj('Y');
        odd00.oddaj('x');
        odd02.oddaj('h');
        odd14.oddaj('Y');
        odd05.oddaj('X');
        odd10.oddaj('L');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd06.oddaj('s');
        odd09.oddaj('k');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd06.oddaj('t');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd02.oddaj('s');
        odd11.oddaj('I');
        odd12.oddaj('d');
        odd06.oddaj('O');
        odd06.oddaj('c');
        System.out.println(spr17.koliko());
        System.out.println(spr02.koliko());
        odd09.oddaj('r');
        odd11.oddaj('B');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd11.oddaj('k');
        odd07.oddaj('D');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd09.oddaj('a');
        odd07.oddaj('R');
        odd17.oddaj('V');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd17.oddaj('E');
        odd01.oddaj('H');
        odd15.oddaj('e');
        System.out.println(spr12.koliko());
        System.out.println(spr04.koliko());
        odd07.oddaj('u');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd16.oddaj('S');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd02.oddaj('c');
        odd14.oddaj('O');
        odd16.oddaj('z');
        System.out.println(spr06.koliko());
        odd10.oddaj('f');
        odd00.oddaj('F');
        odd06.oddaj('g');
        System.out.println(spr02.koliko());
        odd12.oddaj('Z');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd14.oddaj('a');
        System.out.println(spr06.koliko());
        System.out.println(spr16.koliko());
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd08.oddaj('R');
        odd00.oddaj('F');
        odd08.oddaj('Y');
        odd15.oddaj('R');
        System.out.println(spr12.koliko());
        System.out.println(spr09.koliko());
        odd12.oddaj('L');
        odd01.oddaj('r');
        System.out.println(spr15.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd12.oddaj('y');
        odd04.oddaj('e');
        odd17.oddaj('B');
        odd14.oddaj('C');
        odd15.oddaj('f');
        System.out.println(spr04.koliko());
        System.out.println(spr15.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd01.oddaj('c');
        odd11.oddaj('i');
        odd03.oddaj('d');
        odd06.oddaj('h');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd03.oddaj('E');
        odd02.oddaj('k');
        odd12.oddaj('E');
        odd13.oddaj('u');
        System.out.println(spr01.koliko());
        odd01.oddaj('v');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('T');
        odd08.oddaj('T');
        odd18.oddaj('l');
        System.out.println(spr08.koliko());
        System.out.println(spr12.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd06.oddaj('A');
        odd14.oddaj('E');
        odd12.oddaj('v');
        odd17.oddaj('V');
        odd00.oddaj('D');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd09.oddaj('C');
        odd17.oddaj('P');
        odd13.oddaj('c');
        odd08.oddaj('N');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd08.oddaj('z');
        odd05.oddaj('i');
        System.out.println(spr17.koliko());
        odd00.oddaj('O');
        odd15.oddaj('w');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('R');
        odd16.oddaj('w');
        odd14.oddaj('n');
        odd16.oddaj('X');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd02.oddaj('f');
        System.out.println(spr12.koliko());
        odd11.oddaj('S');
        odd18.oddaj('g');
        odd17.oddaj('G');
        odd14.oddaj('m');
        odd15.oddaj('C');
        System.out.println(spr17.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd01.oddaj('I');
        System.out.println(spr08.koliko());
        odd01.oddaj('E');
        System.out.println(spr02.koliko());
        odd09.oddaj('y');
        System.out.println(spr14.koliko());
        odd14.oddaj('t');
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd09.oddaj('n');
        System.out.println(spr14.koliko());
    }
}
