
import java.util.*;

public class Test49 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd12);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd11);

        odd01.oddaj('p');
        odd00.oddaj('p');
        odd03.oddaj('e');
        System.out.println(spr03.koliko());
        odd03.oddaj('T');
        odd10.oddaj('D');
        odd06.oddaj('H');
        odd05.oddaj('x');
        odd08.oddaj('f');
        odd03.oddaj('r');
        odd05.oddaj('C');
        odd04.oddaj('W');
        odd04.oddaj('H');
        odd12.oddaj('c');
        odd07.oddaj('D');
        odd07.oddaj('O');
        odd07.oddaj('h');
        odd04.oddaj('A');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('N');
        odd12.oddaj('h');
        odd04.oddaj('K');
        odd06.oddaj('U');
        odd05.oddaj('B');
        odd07.oddaj('o');
        odd06.oddaj('k');
        odd08.oddaj('g');
        odd04.oddaj('S');
        odd10.oddaj('F');
        odd05.oddaj('p');
        System.out.println(spr13.koliko());
        odd06.oddaj('k');
        odd09.oddaj('s');
        odd06.oddaj('Y');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd12.oddaj('d');
        odd06.oddaj('N');
        odd00.oddaj('y');
        System.out.println("<" + spr07.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd02.oddaj('k');
        System.out.println(spr05.koliko());
        System.out.println(spr02.koliko());
        odd06.oddaj('U');
        odd01.oddaj('k');
        System.out.println("<" + spr18.odZadnjic() + ">");
        System.out.println(spr11.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd00.oddaj('y');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd05.oddaj('j');
        System.out.println(spr14.koliko());
        odd06.oddaj('M');
        odd08.oddaj('A');
        System.out.println("<" + spr12.odZadnjic() + ">");
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('u');
        System.out.println(spr20.koliko());
        odd12.oddaj('h');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd03.oddaj('N');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd00.oddaj('z');
        odd03.oddaj('z');
        odd06.oddaj('W');
        System.out.println(spr10.koliko());
        odd07.oddaj('S');
        odd01.oddaj('D');
        odd10.oddaj('V');
        odd04.oddaj('C');
        odd03.oddaj('s');
        odd05.oddaj('W');
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr13.koliko());
        odd04.oddaj('J');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd08.oddaj('L');
        odd06.oddaj('k');
        odd11.oddaj('L');
        odd00.oddaj('O');
        System.out.println(spr13.koliko());
        odd06.oddaj('D');
        odd00.oddaj('y');
        odd10.oddaj('i');
        odd05.oddaj('r');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd10.oddaj('U');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd07.oddaj('g');
        odd04.oddaj('p');
        odd01.oddaj('P');
        odd00.oddaj('z');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd02.oddaj('T');
        odd02.oddaj('D');
        odd07.oddaj('p');
        odd08.oddaj('t');
        System.out.println(spr05.koliko());
        odd00.oddaj('n');
        odd09.oddaj('l');
        odd08.oddaj('a');
        odd00.oddaj('V');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd05.oddaj('D');
        odd01.oddaj('F');
        odd02.oddaj('t');
        odd07.oddaj('L');
        System.out.println(spr16.koliko());
        odd11.oddaj('F');
        odd12.oddaj('U');
        odd07.oddaj('W');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd03.oddaj('C');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd11.oddaj('f');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd06.oddaj('K');
        System.out.println(spr14.koliko());
        odd00.oddaj('x');
        odd12.oddaj('c');
        odd12.oddaj('r');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd08.oddaj('N');
        odd08.oddaj('G');
        System.out.println(spr09.koliko());
        odd05.oddaj('u');
        odd05.oddaj('z');
        odd10.oddaj('d');
        odd07.oddaj('H');
        odd00.oddaj('W');
        odd11.oddaj('U');
        System.out.println(spr16.koliko());
        odd09.oddaj('L');
        System.out.println(spr12.koliko());
        odd02.oddaj('q');
        odd09.oddaj('p');
        odd03.oddaj('J');
        odd02.oddaj('X');
        odd02.oddaj('N');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd05.oddaj('V');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('W');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        odd06.oddaj('R');
        odd10.oddaj('u');
        odd01.oddaj('C');
        odd10.oddaj('z');
        System.out.println(spr00.koliko());
        odd07.oddaj('E');
        odd12.oddaj('K');
        odd04.oddaj('n');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd04.oddaj('m');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd06.oddaj('J');
        odd04.oddaj('E');
        System.out.println(spr20.koliko());
        odd11.oddaj('r');
        odd12.oddaj('W');
        System.out.println(spr05.koliko());
        System.out.println(spr20.koliko());
        odd03.oddaj('Q');
        odd11.oddaj('h');
        odd10.oddaj('t');
        odd02.oddaj('L');
        odd03.oddaj('Y');
        odd00.oddaj('l');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd06.oddaj('B');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd05.oddaj('b');
        odd10.oddaj('y');
        System.out.println(spr01.koliko());
        odd11.oddaj('u');
        odd04.oddaj('x');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd07.oddaj('n');
        odd03.oddaj('J');
        System.out.println(spr13.koliko());
        odd08.oddaj('l');
        odd08.oddaj('h');
        odd00.oddaj('I');
        odd03.oddaj('F');
        odd01.oddaj('J');
        odd11.oddaj('v');
        odd01.oddaj('c');
        odd01.oddaj('w');
        odd07.oddaj('j');
        odd12.oddaj('E');
        odd11.oddaj('A');
        System.out.println(spr07.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd04.oddaj('r');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('B');
        odd11.oddaj('y');
        System.out.println(spr19.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd06.oddaj('k');
        System.out.println(spr13.koliko());
        odd05.oddaj('B');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd06.oddaj('H');
        System.out.println(spr08.koliko());
        odd02.oddaj('t');
        odd00.oddaj('P');
        odd11.oddaj('W');
        odd11.oddaj('b');
        odd08.oddaj('f');
        odd05.oddaj('J');
        System.out.println(spr20.koliko());
        odd04.oddaj('T');
        odd01.oddaj('d');
        odd11.oddaj('A');
        odd08.oddaj('o');
        odd10.oddaj('H');
        System.out.println(spr17.koliko());
        odd05.oddaj('r');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd12.oddaj('D');
        odd00.oddaj('x');
        odd07.oddaj('T');
        System.out.println(spr03.koliko());
        System.out.println(spr08.koliko());
        System.out.println(spr18.koliko());
        odd01.oddaj('c');
        odd03.oddaj('I');
        odd00.oddaj('j');
        odd01.oddaj('m');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd10.oddaj('E');
        System.out.println(spr07.koliko());
        odd04.oddaj('o');
        odd01.oddaj('q');
        odd05.oddaj('D');
        odd12.oddaj('Z');
        System.out.println(spr21.koliko());
        odd01.oddaj('t');
        odd00.oddaj('d');
        odd08.oddaj('T');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd02.oddaj('K');
        System.out.println(spr09.koliko());
        odd07.oddaj('N');
        odd10.oddaj('i');
        odd02.oddaj('o');
        System.out.println(spr00.koliko());
        odd03.oddaj('C');
        odd09.oddaj('V');
        odd03.oddaj('p');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        odd12.oddaj('B');
        odd02.oddaj('U');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr15.koliko());
        System.out.println(spr10.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd10.oddaj('U');
        odd06.oddaj('T');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('n');
        System.out.println(spr11.koliko());
        odd08.oddaj('e');
        odd05.oddaj('X');
        odd00.oddaj('b');
        odd05.oddaj('V');
        System.out.println(spr13.koliko());
        odd12.oddaj('z');
        odd07.oddaj('V');
        odd10.oddaj('r');
        odd00.oddaj('F');
        odd11.oddaj('M');
        odd07.oddaj('O');
        odd02.oddaj('L');
        odd01.oddaj('g');
        odd00.oddaj('q');
        odd00.oddaj('w');
        odd07.oddaj('f');
        odd12.oddaj('s');
        System.out.println(spr14.koliko());
        odd04.oddaj('N');
        odd06.oddaj('p');
        odd11.oddaj('R');
        odd06.oddaj('d');
        odd04.oddaj('s');
        odd06.oddaj('i');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd08.oddaj('E');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd05.oddaj('H');
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd01.oddaj('G');
        odd10.oddaj('u');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd08.oddaj('z');
        odd12.oddaj('h');
        odd08.oddaj('r');
        odd03.oddaj('O');
        odd04.oddaj('p');
        odd00.oddaj('n');
        odd09.oddaj('j');
        System.out.println(spr17.koliko());
        odd12.oddaj('n');
        odd01.oddaj('r');
        odd11.oddaj('X');
        odd11.oddaj('X');
        System.out.println("<" + spr20.odZadnjic() + ">");
        odd01.oddaj('o');
        odd00.oddaj('j');
        odd09.oddaj('W');
        odd07.oddaj('r');
        odd10.oddaj('w');
        odd07.oddaj('q');
        odd05.oddaj('q');
        System.out.println(spr14.koliko());
        odd09.oddaj('s');
        odd10.oddaj('J');
        odd02.oddaj('D');
        odd12.oddaj('G');
        odd05.oddaj('g');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd02.oddaj('o');
        System.out.println(spr06.koliko());
        odd07.oddaj('b');
        odd01.oddaj('Y');
        odd07.oddaj('Q');
        odd02.oddaj('t');
        odd07.oddaj('z');
        System.out.println(spr08.koliko());
        System.out.println(spr07.koliko());
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('K');
        odd05.oddaj('f');
        odd05.oddaj('t');
        odd02.oddaj('y');
        odd08.oddaj('X');
        odd12.oddaj('D');
        odd07.oddaj('R');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd02.oddaj('H');
        odd03.oddaj('C');
        odd07.oddaj('v');
        odd05.oddaj('O');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd12.oddaj('l');
        odd10.oddaj('k');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd06.oddaj('p');
        odd06.oddaj('Q');
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd10.oddaj('C');
        odd01.oddaj('C');
        odd12.oddaj('m');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd10.oddaj('I');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd08.oddaj('n');
        System.out.println(spr18.koliko());
        odd05.oddaj('c');
        odd06.oddaj('I');
        odd04.oddaj('a');
        odd12.oddaj('Q');
        odd04.oddaj('H');
        odd12.oddaj('Q');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr19.odZadnjic() + ">");
        System.out.println(spr00.koliko());
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd12.oddaj('l');
        odd08.oddaj('N');
        System.out.println(spr01.koliko());
        System.out.println(spr05.koliko());
        odd03.oddaj('D');
        odd05.oddaj('V');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr17.koliko());
        odd09.oddaj('k');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd07.oddaj('D');
        odd09.oddaj('m');
        System.out.println(spr08.koliko());
        odd05.oddaj('r');
        odd09.oddaj('H');
        System.out.println(spr20.koliko());
        odd02.oddaj('t');
        odd09.oddaj('F');
        odd08.oddaj('B');
        odd05.oddaj('W');
        odd00.oddaj('m');
        odd06.oddaj('U');
        odd05.oddaj('n');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd02.oddaj('J');
        odd11.oddaj('J');
        odd12.oddaj('o');
        odd00.oddaj('w');
        odd03.oddaj('a');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('N');
        odd01.oddaj('p');
        odd03.oddaj('q');
        System.out.println(spr16.koliko());
        odd10.oddaj('y');
        odd09.oddaj('P');
        odd12.oddaj('E');
        odd11.oddaj('M');
        System.out.println(spr06.koliko());
        System.out.println(spr10.koliko());
        odd11.oddaj('c');
        odd10.oddaj('c');
        odd10.oddaj('w');
        System.out.println(spr20.koliko());
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd02.oddaj('d');
        odd00.oddaj('n');
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd04.oddaj('E');
        odd09.oddaj('p');
        odd10.oddaj('W');
        System.out.println(spr14.koliko());
        odd04.oddaj('A');
        odd01.oddaj('B');
        odd03.oddaj('J');
        odd09.oddaj('u');
        odd10.oddaj('U');
        odd07.oddaj('Z');
        odd12.oddaj('Z');
        System.out.println(spr19.koliko());
        odd11.oddaj('c');
        System.out.println(spr06.koliko());
        odd05.oddaj('K');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd00.oddaj('P');
        odd03.oddaj('P');
        System.out.println(spr15.koliko());
        odd02.oddaj('C');
        odd05.oddaj('v');
        odd01.oddaj('j');
        odd02.oddaj('b');
        odd12.oddaj('A');
        odd11.oddaj('t');
        odd06.oddaj('x');
        odd01.oddaj('t');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd09.oddaj('D');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd11.oddaj('O');
        System.out.println(spr13.koliko());
        odd00.oddaj('i');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd06.oddaj('D');
        odd12.oddaj('g');
        odd12.oddaj('k');
        odd06.oddaj('S');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd11.oddaj('F');
        odd12.oddaj('J');
        odd08.oddaj('g');
        odd03.oddaj('Y');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd10.oddaj('z');
        odd00.oddaj('C');
        odd12.oddaj('B');
        odd06.oddaj('f');
        System.out.println(spr17.koliko());
        odd04.oddaj('V');
        System.out.println(spr15.koliko());
        odd04.oddaj('N');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd07.oddaj('x');
        odd12.oddaj('s');
        odd10.oddaj('n');
        odd07.oddaj('R');
        odd10.oddaj('W');
        odd06.oddaj('G');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        odd12.oddaj('j');
        odd11.oddaj('Y');
        odd04.oddaj('a');
        odd04.oddaj('j');
        System.out.println(spr09.koliko());
        odd09.oddaj('X');
        odd10.oddaj('I');
        odd04.oddaj('F');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd05.oddaj('i');
        odd06.oddaj('c');
        odd11.oddaj('O');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd10.oddaj('f');
        odd05.oddaj('r');
        odd09.oddaj('M');
        odd07.oddaj('t');
        odd10.oddaj('d');
        odd02.oddaj('N');
        System.out.println(spr18.koliko());
        odd12.oddaj('f');
        odd02.oddaj('w');
        odd09.oddaj('W');
        odd01.oddaj('q');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd10.oddaj('V');
        System.out.println(spr02.koliko());
        System.out.println(spr03.koliko());
        odd12.oddaj('n');
        odd07.oddaj('P');
        odd03.oddaj('y');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd00.oddaj('v');
        odd11.oddaj('H');
        odd08.oddaj('Q');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd01.oddaj('L');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd08.oddaj('g');
        odd08.oddaj('p');
        odd08.oddaj('H');
        odd05.oddaj('z');
        odd00.oddaj('u');
        odd09.oddaj('p');
        odd11.oddaj('O');
        odd12.oddaj('P');
        System.out.println(spr06.koliko());
        odd00.oddaj('Z');
        System.out.println(spr16.koliko());
        odd05.oddaj('f');
    }
}
