
public class Test08 {

    public static void main(String[] args) {
        Filozof[] filozofi = new Filozof[10];
        filozofi[0] = new Filozof("A");
        filozofi[1] = new Filozof("B");
        filozofi[2] = new Filozof("C");
        filozofi[3] = new Filozof("D");
        filozofi[4] = new Filozof("E");
        filozofi[5] = new Filozof("F");
        filozofi[6] = new Filozof("G");
        filozofi[7] = new Filozof("H");
        filozofi[8] = new Filozof("I");
        filozofi[9] = new Filozof("J");

        filozofi[0].nastaviSoseda(filozofi[2], filozofi[1]);
        filozofi[1].nastaviSoseda(filozofi[0], filozofi[6]);
        filozofi[2].nastaviSoseda(filozofi[3], filozofi[0]);
        filozofi[3].nastaviSoseda(filozofi[5], filozofi[2]);
        filozofi[4].nastaviSoseda(filozofi[6], filozofi[9]);
        filozofi[5].nastaviSoseda(filozofi[8], filozofi[3]);
        filozofi[6].nastaviSoseda(filozofi[1], filozofi[4]);
        filozofi[7].nastaviSoseda(filozofi[9], filozofi[8]);
        filozofi[8].nastaviSoseda(filozofi[7], filozofi[5]);
        filozofi[9].nastaviSoseda(filozofi[4], filozofi[7]);

        filozofi[4].primiLevo();
        filozofi[6].primiDesno();
        filozofi[8].izpustiLevo();
        filozofi[8].izpustiLevo();
        filozofi[8].primiDesno();
        filozofi[5].izpustiDesno();
        filozofi[6].primiDesno();
        filozofi[7].primiLevo();
        filozofi[7].primiDesno();
        filozofi[6].primiLevo();
        filozofi[6].izpustiLevo();
        filozofi[8].primiDesno();
        filozofi[5].izpustiDesno();
        filozofi[2].primiLevo();
        filozofi[1].primiDesno();
        filozofi[6].izpustiLevo();
        filozofi[4].primiLevo();
        filozofi[6].primiLevo();
        filozofi[0].izpustiDesno();
        filozofi[7].primiLevo();
        filozofi[6].primiLevo();
        filozofi[8].primiLevo();
        filozofi[9].primiDesno();
        filozofi[7].primiLevo();
        filozofi[9].primiLevo();
        filozofi[8].primiDesno();
        filozofi[0].primiLevo();
        filozofi[2].primiLevo();
        filozofi[4].primiLevo();
        filozofi[4].primiLevo();
        filozofi[1].primiDesno();
        filozofi[8].primiDesno();
        filozofi[7].primiLevo();
        filozofi[9].primiDesno();
        filozofi[2].izpustiDesno();
        filozofi[8].primiDesno();
        filozofi[2].primiDesno();
        filozofi[7].primiLevo();
        filozofi[9].primiDesno();
        filozofi[9].primiDesno();
        filozofi[5].izpustiDesno();
        filozofi[2].izpustiLevo();
        filozofi[6].primiDesno();
        filozofi[6].izpustiLevo();
        filozofi[7].primiLevo();
        filozofi[3].primiLevo();
        filozofi[4].primiDesno();
        filozofi[4].primiLevo();
        filozofi[9].izpustiDesno();
        filozofi[0].primiLevo();
        filozofi[7].izpustiDesno();
        filozofi[8].primiLevo();
        filozofi[3].primiDesno();
        filozofi[8].primiDesno();
        filozofi[5].izpustiDesno();
        filozofi[7].primiDesno();
        filozofi[2].primiLevo();
        filozofi[7].primiDesno();
        filozofi[5].primiLevo();
        filozofi[0].primiDesno();
        filozofi[1].primiDesno();
        filozofi[2].primiLevo();
        filozofi[5].izpustiDesno();
        filozofi[2].primiDesno();
        filozofi[0].primiLevo();
        filozofi[8].izpustiDesno();
        filozofi[1].primiLevo();
        filozofi[2].izpustiDesno();
        filozofi[2].primiLevo();
        filozofi[4].izpustiDesno();
        filozofi[0].izpustiDesno();
        filozofi[0].izpustiDesno();
        filozofi[9].primiDesno();
        filozofi[3].primiLevo();
        filozofi[5].primiLevo();
        filozofi[9].primiDesno();
        filozofi[0].izpustiDesno();
        filozofi[2].primiDesno();
        filozofi[0].primiLevo();
        filozofi[2].primiLevo();
        filozofi[9].izpustiDesno();
        filozofi[9].primiLevo();
        filozofi[8].izpustiDesno();
        filozofi[8].primiDesno();
        filozofi[0].primiDesno();
        filozofi[7].primiDesno();
        filozofi[5].primiLevo();
        filozofi[1].primiLevo();
        filozofi[4].izpustiLevo();
        filozofi[5].primiDesno();
        filozofi[7].primiLevo();
        filozofi[6].primiLevo();
        filozofi[8].primiLevo();
        filozofi[7].primiDesno();
        filozofi[8].izpustiLevo();
        filozofi[3].primiDesno();
        filozofi[8].izpustiDesno();
        filozofi[9].primiLevo();
        filozofi[4].primiLevo();
        filozofi[5].primiDesno();
        filozofi[8].primiLevo();
        filozofi[1].izpustiLevo();
        filozofi[7].primiDesno();
        filozofi[9].izpustiDesno();
        filozofi[1].primiDesno();
        filozofi[8].izpustiLevo();
        filozofi[3].primiDesno();
        filozofi[5].primiDesno();
        filozofi[2].primiLevo();
        filozofi[6].izpustiDesno();
        filozofi[2].izpustiDesno();
        filozofi[8].primiLevo();
        filozofi[0].primiDesno();
        filozofi[2].primiDesno();
        filozofi[6].izpustiDesno();
        filozofi[9].primiLevo();
        filozofi[5].primiDesno();
        filozofi[7].primiLevo();
        filozofi[3].izpustiLevo();
        filozofi[2].izpustiLevo();
        filozofi[4].primiDesno();
        filozofi[3].primiLevo();
        filozofi[7].primiDesno();
        filozofi[6].izpustiLevo();
        filozofi[8].primiLevo();
        filozofi[2].primiDesno();
        filozofi[8].primiDesno();
        filozofi[0].primiDesno();
        filozofi[9].primiLevo();
        filozofi[7].primiLevo();
        filozofi[9].primiLevo();
        filozofi[1].primiDesno();
        filozofi[6].primiDesno();
        filozofi[8].izpustiLevo();
        filozofi[5].izpustiDesno();
        filozofi[4].primiDesno();
        filozofi[9].izpustiLevo();
        filozofi[2].izpustiDesno();
        filozofi[6].primiDesno();
        filozofi[4].izpustiLevo();
        filozofi[8].izpustiDesno();
        filozofi[0].primiDesno();
        filozofi[4].primiDesno();
        filozofi[5].primiDesno();
        filozofi[3].izpustiDesno();
        filozofi[1].primiLevo();
        filozofi[6].izpustiLevo();
        filozofi[3].izpustiDesno();
        filozofi[7].primiLevo();
        filozofi[4].primiDesno();
        filozofi[1].izpustiDesno();
        filozofi[1].primiLevo();
        filozofi[4].primiDesno();
        filozofi[2].primiDesno();
        filozofi[3].izpustiDesno();
        filozofi[3].primiLevo();
        filozofi[9].primiDesno();
        filozofi[5].primiDesno();
        filozofi[8].primiDesno();
        filozofi[2].primiDesno();
        filozofi[9].primiLevo();
        filozofi[7].primiDesno();
        filozofi[3].primiDesno();
        filozofi[7].primiLevo();
        filozofi[7].izpustiDesno();
        filozofi[5].primiDesno();
        filozofi[0].primiLevo();
        filozofi[5].izpustiDesno();
        filozofi[3].primiLevo();
        filozofi[1].primiDesno();
        filozofi[9].izpustiDesno();
        filozofi[3].izpustiDesno();
        filozofi[0].izpustiLevo();
        filozofi[1].izpustiLevo();
        filozofi[9].primiLevo();
        filozofi[7].primiDesno();
        filozofi[5].primiLevo();
        filozofi[9].izpustiLevo();
        filozofi[2].primiLevo();
        filozofi[9].primiLevo();
        filozofi[7].primiLevo();
        filozofi[5].primiLevo();
        filozofi[4].primiLevo();
        filozofi[8].primiDesno();
        filozofi[3].primiLevo();
        filozofi[4].primiDesno();
        filozofi[2].izpustiLevo();
        filozofi[8].izpustiDesno();
        filozofi[4].primiDesno();
        filozofi[7].primiDesno();
        filozofi[5].primiDesno();
        filozofi[0].primiDesno();
        filozofi[5].izpustiLevo();
        filozofi[9].primiLevo();
        filozofi[5].izpustiDesno();
        filozofi[6].primiDesno();
        filozofi[4].primiDesno();
        filozofi[3].primiDesno();
        filozofi[2].izpustiDesno();
        filozofi[8].primiLevo();

        for (int i = 0;  i < filozofi.length;  i++) {
            System.out.println(filozofi[i].kolikoPalicicDrzi());
        }
        System.out.println("---");

        System.out.println(Filozof.steviloJedcev(filozofi));
    }
}
