
import java.util.*;

public class Test05 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd00);
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd01);
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd02);
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd03);
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd04);
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd05);
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd06);
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd07);
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd08);
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd09);
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd10);
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd11);
        Tretja.Oddajnik odd12 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd12);
        Tretja.Oddajnik odd13 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd13);
        Tretja.Oddajnik odd14 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd14);
        Tretja.Oddajnik odd15 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd15);
        Tretja.Oddajnik odd16 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd16);
        Tretja.Oddajnik odd17 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd17);

        odd08.oddaj('Y');
        odd12.oddaj('F');
        System.out.println(spr12.koliko());
        odd15.oddaj('E');
        odd17.oddaj('m');
        odd05.oddaj('f');
        odd05.oddaj('h');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd14.oddaj('P');
        odd04.oddaj('E');
        odd13.oddaj('Z');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd16.oddaj('h');
        odd02.oddaj('S');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd02.oddaj('I');
        odd01.oddaj('z');
        System.out.println(spr04.koliko());
        odd11.oddaj('q');
        odd08.oddaj('m');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd17.oddaj('f');
        System.out.println(spr14.koliko());
        odd01.oddaj('t');
        odd11.oddaj('F');
        odd15.oddaj('r');
        odd07.oddaj('W');
        System.out.println(spr05.koliko());
        odd11.oddaj('F');
        odd16.oddaj('A');
        odd00.oddaj('v');
        odd13.oddaj('E');
        odd13.oddaj('S');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd09.oddaj('O');
        odd02.oddaj('A');
        odd03.oddaj('o');
        odd07.oddaj('V');
        odd06.oddaj('u');
        odd11.oddaj('K');
        odd05.oddaj('o');
        odd09.oddaj('r');
        odd16.oddaj('W');
        System.out.println(spr15.koliko());
        odd04.oddaj('F');
        odd14.oddaj('t');
        odd17.oddaj('p');
        odd07.oddaj('O');
        System.out.println(spr09.koliko());
        odd15.oddaj('M');
        odd01.oddaj('T');
        odd05.oddaj('Q');
        odd13.oddaj('p');
        odd13.oddaj('b');
        System.out.println(spr04.koliko());
        System.out.println(spr02.koliko());
        odd06.oddaj('g');
        odd16.oddaj('S');
        odd17.oddaj('h');
        System.out.println(spr13.koliko());
        odd15.oddaj('t');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd02.oddaj('H');
        odd13.oddaj('L');
        odd15.oddaj('y');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd12.oddaj('K');
        odd13.oddaj('w');
        odd10.oddaj('k');
        odd15.oddaj('F');
        odd12.oddaj('G');
        odd07.oddaj('n');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd14.oddaj('d');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd08.oddaj('W');
        System.out.println(spr08.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd14.oddaj('u');
        odd02.oddaj('m');
        odd01.oddaj('R');
        odd01.oddaj('i');
        odd11.oddaj('S');
        odd00.oddaj('J');
        odd01.oddaj('N');
        odd12.oddaj('T');
        odd14.oddaj('R');
        System.out.println("<" + spr05.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        System.out.println(spr12.koliko());
        odd16.oddaj('R');
        System.out.println(spr02.koliko());
        System.out.println(spr16.koliko());
        System.out.println(spr06.koliko());
        odd14.oddaj('k');
        odd10.oddaj('D');
        odd06.oddaj('M');
        System.out.println(spr06.koliko());
        odd10.oddaj('N');
        System.out.println(spr10.koliko());
        odd15.oddaj('W');
        odd05.oddaj('g');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd00.oddaj('b');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd14.oddaj('l');
        odd14.oddaj('r');
        odd07.oddaj('v');
        odd13.oddaj('s');
        System.out.println(spr13.koliko());
        System.out.println(spr05.koliko());
        odd17.oddaj('w');
        odd00.oddaj('R');
        odd05.oddaj('T');
        odd14.oddaj('R');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd14.oddaj('Z');
        odd10.oddaj('g');
        odd16.oddaj('m');
        odd02.oddaj('k');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd14.oddaj('W');
        odd01.oddaj('q');
        odd07.oddaj('r');
        odd07.oddaj('m');
        odd13.oddaj('F');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd02.oddaj('m');
        odd05.oddaj('c');
        odd02.oddaj('J');
        odd07.oddaj('z');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr05.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd08.oddaj('K');
        odd06.oddaj('p');
        System.out.println(spr17.koliko());
        odd07.oddaj('e');
        odd17.oddaj('Z');
        odd02.oddaj('z');
        odd12.oddaj('H');
        odd11.oddaj('g');
        odd02.oddaj('t');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd10.oddaj('u');
        odd12.oddaj('s');
        odd09.oddaj('y');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd15.oddaj('Y');
        odd11.oddaj('d');
        System.out.println(spr17.koliko());
        odd04.oddaj('k');
        odd16.oddaj('P');
        odd08.oddaj('z');
        odd13.oddaj('s');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println(spr16.koliko());
        odd12.oddaj('a');
        odd01.oddaj('p');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('B');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('f');
        System.out.println("<" + spr01.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd09.oddaj('N');
        odd12.oddaj('W');
        odd07.oddaj('P');
        odd00.oddaj('r');
        odd10.oddaj('W');
        odd15.oddaj('L');
        odd15.oddaj('K');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr10.koliko());
        odd06.oddaj('l');
        odd17.oddaj('Z');
        odd08.oddaj('W');
        odd10.oddaj('T');
        odd09.oddaj('w');
        odd10.oddaj('U');
        odd15.oddaj('p');
        odd01.oddaj('s');
        odd02.oddaj('E');
        odd15.oddaj('a');
        odd05.oddaj('g');
        odd15.oddaj('p');
        odd12.oddaj('U');
        odd11.oddaj('I');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('U');
        odd13.oddaj('R');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd09.oddaj('Q');
        odd09.oddaj('v');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd13.oddaj('D');
        odd07.oddaj('v');
        odd05.oddaj('s');
        odd11.oddaj('D');
        odd03.oddaj('j');
        odd10.oddaj('w');
        odd14.oddaj('S');
        System.out.println(spr01.koliko());
        odd05.oddaj('o');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd04.oddaj('u');
        System.out.println(spr09.koliko());
        System.out.println(spr03.koliko());
        odd04.oddaj('u');
        odd04.oddaj('O');
        System.out.println(spr13.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd00.oddaj('N');
        odd12.oddaj('V');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd04.oddaj('Q');
        odd09.oddaj('d');
        odd11.oddaj('I');
        odd12.oddaj('X');
        odd07.oddaj('G');
        odd13.oddaj('p');
        odd00.oddaj('w');
        odd01.oddaj('A');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd15.oddaj('M');
        odd09.oddaj('r');
        System.out.println(spr09.koliko());
        System.out.println(spr08.koliko());
        odd10.oddaj('Y');
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd16.oddaj('A');
        odd00.oddaj('a');
        odd12.oddaj('W');
        System.out.println("<" + spr14.odZadnjic() + ">");
        System.out.println(spr02.koliko());
        odd15.oddaj('G');
        odd14.oddaj('J');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd14.oddaj('v');
        odd04.oddaj('B');
        odd07.oddaj('q');
        odd09.oddaj('s');
        odd01.oddaj('p');
        odd10.oddaj('T');
        odd17.oddaj('f');
        odd06.oddaj('P');
        odd08.oddaj('x');
        odd03.oddaj('q');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd14.oddaj('C');
        System.out.println(spr00.koliko());
        odd16.oddaj('p');
        odd00.oddaj('j');
        odd00.oddaj('a');
        odd02.oddaj('B');
        odd03.oddaj('N');
        odd02.oddaj('O');
        odd02.oddaj('N');
        odd07.oddaj('O');
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd03.oddaj('R');
        odd14.oddaj('q');
        odd06.oddaj('R');
        odd01.oddaj('C');
        odd07.oddaj('o');
        odd05.oddaj('W');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd04.oddaj('D');
        odd00.oddaj('j');
        odd03.oddaj('H');
        odd00.oddaj('a');
        odd04.oddaj('L');
        odd07.oddaj('j');
        odd00.oddaj('R');
        odd04.oddaj('W');
        odd16.oddaj('o');
        odd09.oddaj('I');
        odd12.oddaj('G');
        odd01.oddaj('r');
        odd09.oddaj('I');
        odd05.oddaj('Z');
        odd01.oddaj('o');
        odd13.oddaj('a');
        odd10.oddaj('L');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd03.oddaj('t');
        odd09.oddaj('Y');
        odd12.oddaj('X');
        System.out.println(spr01.koliko());
        odd00.oddaj('P');
        odd11.oddaj('S');
        odd11.oddaj('e');
        System.out.println(spr15.koliko());
        odd01.oddaj('N');
        odd08.oddaj('v');
        odd09.oddaj('D');
        odd17.oddaj('i');
        odd11.oddaj('v');
        odd07.oddaj('t');
        odd16.oddaj('L');
        odd06.oddaj('z');
        odd05.oddaj('B');
        odd17.oddaj('u');
        System.out.println(spr07.koliko());
        odd11.oddaj('X');
        System.out.println(spr06.koliko());
        odd08.oddaj('V');
        odd12.oddaj('K');
        odd09.oddaj('a');
        System.out.println(spr13.koliko());
        odd07.oddaj('X');
        odd00.oddaj('v');
        odd15.oddaj('J');
        odd03.oddaj('r');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd08.oddaj('F');
        odd08.oddaj('G');
        odd07.oddaj('U');
        odd03.oddaj('Q');
        System.out.println(spr00.koliko());
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd17.oddaj('E');
        odd03.oddaj('j');
        odd14.oddaj('y');
        odd12.oddaj('p');
        odd14.oddaj('P');
        odd11.oddaj('B');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        System.out.println(spr07.koliko());
        odd02.oddaj('D');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd12.oddaj('r');
        odd14.oddaj('C');
        System.out.println("<" + spr15.odZadnjic() + ">");
        System.out.println(spr04.koliko());
        System.out.println(spr14.koliko());
        odd07.oddaj('I');
        odd15.oddaj('e');
        odd16.oddaj('g');
        odd03.oddaj('j');
        odd16.oddaj('Q');
        odd03.oddaj('p');
        odd04.oddaj('M');
        odd00.oddaj('A');
        odd01.oddaj('V');
        odd08.oddaj('J');
        odd16.oddaj('J');
        odd16.oddaj('z');
        System.out.println(spr11.koliko());
        odd08.oddaj('X');
        odd07.oddaj('F');
        odd03.oddaj('V');
        odd08.oddaj('D');
        odd00.oddaj('B');
        odd01.oddaj('N');
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd00.oddaj('y');
        odd16.oddaj('V');
        odd16.oddaj('Z');
        odd10.oddaj('g');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd04.oddaj('a');
        odd13.oddaj('Q');
        odd01.oddaj('q');
        odd00.oddaj('j');
        odd14.oddaj('l');
        System.out.println(spr15.koliko());
        odd06.oddaj('L');
        odd06.oddaj('O');
        System.out.println(spr02.koliko());
        System.out.println("<" + spr00.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd10.oddaj('d');
        odd01.oddaj('u');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd16.oddaj('d');
        odd05.oddaj('m');
        odd05.oddaj('v');
        odd11.oddaj('v');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd07.oddaj('J');
        System.out.println(spr12.koliko());
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd09.oddaj('Q');
        odd15.oddaj('r');
        odd15.oddaj('C');
        odd06.oddaj('L');
        System.out.println(spr06.koliko());
        odd14.oddaj('H');
        odd02.oddaj('W');
        odd17.oddaj('H');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd03.oddaj('O');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd00.oddaj('x');
        odd03.oddaj('f');
        odd01.oddaj('m');
        odd05.oddaj('S');
        odd05.oddaj('Q');
        odd08.oddaj('i');
        odd13.oddaj('t');
        System.out.println(spr15.koliko());
        odd15.oddaj('k');
        odd14.oddaj('J');
        odd04.oddaj('I');
        odd11.oddaj('v');
        odd00.oddaj('A');
        odd02.oddaj('M');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd08.oddaj('F');
        odd06.oddaj('j');
        odd06.oddaj('C');
        odd05.oddaj('u');
        System.out.println(spr02.koliko());
        odd17.oddaj('v');
        System.out.println(spr04.koliko());
        odd13.oddaj('V');
        System.out.println(spr09.koliko());
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd05.oddaj('O');
        odd04.oddaj('S');
        odd06.oddaj('u');
        odd11.oddaj('H');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('d');
        System.out.println(spr05.koliko());
        odd09.oddaj('K');
        odd14.oddaj('A');
        odd17.oddaj('J');
        odd17.oddaj('f');
        System.out.println(spr16.koliko());
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd07.oddaj('t');
        odd07.oddaj('v');
        odd08.oddaj('Q');
        System.out.println(spr07.koliko());
        odd15.oddaj('w');
        odd00.oddaj('V');
        odd07.oddaj('B');
        odd01.oddaj('y');
        odd14.oddaj('L');
        odd11.oddaj('y');
        odd11.oddaj('F');
        System.out.println(spr11.koliko());
        odd17.oddaj('v');
        odd16.oddaj('l');
        odd08.oddaj('d');
        odd04.oddaj('e');
        odd15.oddaj('u');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd07.oddaj('b');
        odd01.oddaj('k');
        odd17.oddaj('E');
        odd03.oddaj('p');
        odd16.oddaj('k');
        odd17.oddaj('V');
        odd13.oddaj('w');
        odd14.oddaj('h');
        odd16.oddaj('q');
        odd07.oddaj('W');
        odd16.oddaj('S');
        odd13.oddaj('k');
        odd10.oddaj('u');
        odd13.oddaj('f');
        System.out.println(spr17.koliko());
        odd08.oddaj('u');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd16.oddaj('t');
        odd17.oddaj('D');
        odd00.oddaj('C');
        odd17.oddaj('X');
        odd17.oddaj('g');
        System.out.println(spr13.koliko());
        odd13.oddaj('j');
        odd16.oddaj('S');
        odd06.oddaj('v');
        odd16.oddaj('d');
        odd10.oddaj('e');
        odd08.oddaj('h');
        odd09.oddaj('P');
        odd03.oddaj('V');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd11.oddaj('t');
        odd16.oddaj('p');
        System.out.println(spr08.koliko());
        odd06.oddaj('c');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd01.oddaj('A');
        System.out.println(spr11.koliko());
        odd03.oddaj('a');
        odd16.oddaj('O');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr03.koliko());
        odd12.oddaj('K');
        System.out.println(spr07.koliko());
        odd03.oddaj('w');
        odd10.oddaj('u');
        odd08.oddaj('y');
        System.out.println(spr13.koliko());
        odd10.oddaj('V');
        odd05.oddaj('w');
        odd02.oddaj('d');
        odd10.oddaj('n');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd06.oddaj('X');
        odd10.oddaj('M');
        odd06.oddaj('y');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd06.oddaj('k');
        System.out.println(spr01.koliko());
        odd05.oddaj('r');
        odd06.oddaj('Q');
        odd05.oddaj('D');
        odd11.oddaj('e');
        odd11.oddaj('e');
        odd08.oddaj('l');
        odd16.oddaj('S');
        System.out.println(spr17.koliko());
        odd03.oddaj('R');
        odd04.oddaj('I');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd17.oddaj('C');
        odd03.oddaj('V');
        odd10.oddaj('N');
        odd09.oddaj('r');
        odd11.oddaj('U');
        odd11.oddaj('V');
        System.out.println("<" + spr10.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd14.oddaj('S');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('h');
        System.out.println(spr14.koliko());
        System.out.println(spr09.koliko());
        odd09.oddaj('i');
        odd09.oddaj('X');
        odd10.oddaj('f');
        odd05.oddaj('w');
        System.out.println(spr01.koliko());
        System.out.println(spr08.koliko());
    }
}
