
import java.util.*;

public class Test10 {

    public static void main(String[] args) {
        Tretja.Oddajnik odd00 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd01 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd02 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd03 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd04 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd05 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd06 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd07 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd08 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd09 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd10 = new Tretja.Oddajnik();
        Tretja.Oddajnik odd11 = new Tretja.Oddajnik();
        Tretja.Sprejemnik spr00 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr01 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr02 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr03 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr04 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr05 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr06 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr07 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr08 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr09 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr10 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr11 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr12 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr13 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr14 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr15 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr16 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr17 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr18 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr19 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr20 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr21 = new Tretja.Sprejemnik(odd03);
        Tretja.Sprejemnik spr22 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr23 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr24 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr25 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr26 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr27 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr28 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr29 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr30 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr31 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr32 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr33 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr34 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr35 = new Tretja.Sprejemnik(odd05);
        Tretja.Sprejemnik spr36 = new Tretja.Sprejemnik(odd10);
        Tretja.Sprejemnik spr37 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr38 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr39 = new Tretja.Sprejemnik(odd00);
        Tretja.Sprejemnik spr40 = new Tretja.Sprejemnik(odd09);
        Tretja.Sprejemnik spr41 = new Tretja.Sprejemnik(odd08);
        Tretja.Sprejemnik spr42 = new Tretja.Sprejemnik(odd11);
        Tretja.Sprejemnik spr43 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr44 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr45 = new Tretja.Sprejemnik(odd04);
        Tretja.Sprejemnik spr46 = new Tretja.Sprejemnik(odd02);
        Tretja.Sprejemnik spr47 = new Tretja.Sprejemnik(odd06);
        Tretja.Sprejemnik spr48 = new Tretja.Sprejemnik(odd01);
        Tretja.Sprejemnik spr49 = new Tretja.Sprejemnik(odd07);
        Tretja.Sprejemnik spr50 = new Tretja.Sprejemnik(odd04);

        odd01.oddaj('E');
        odd02.oddaj('z');
        odd10.oddaj('U');
        odd06.oddaj('S');
        System.out.println("<" + spr34.odZadnjic() + ">");
        odd05.oddaj('A');
        odd04.oddaj('W');
        odd09.oddaj('o');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd06.oddaj('q');
        System.out.println("<" + spr37.odZadnjic() + ">");
        System.out.println(spr30.koliko());
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd10.oddaj('K');
        odd11.oddaj('L');
        odd03.oddaj('q');
        odd11.oddaj('K');
        odd04.oddaj('F');
        System.out.println(spr24.koliko());
        System.out.println(spr31.koliko());
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr22.koliko());
        odd01.oddaj('p');
        odd08.oddaj('I');
        System.out.println("<" + spr10.odZadnjic() + ">");
        odd00.oddaj('P');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd09.oddaj('Z');
        odd04.oddaj('X');
        odd10.oddaj('V');
        odd11.oddaj('T');
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd02.oddaj('X');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd01.oddaj('Y');
        odd06.oddaj('e');
        System.out.println("<" + spr08.odZadnjic() + ">");
        System.out.println(spr43.koliko());
        System.out.println(spr50.koliko());
        odd06.oddaj('I');
        odd08.oddaj('c');
        odd08.oddaj('a');
        odd11.oddaj('P');
        odd08.oddaj('w');
        odd01.oddaj('y');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd05.oddaj('f');
        odd05.oddaj('a');
        System.out.println("<" + spr38.odZadnjic() + ">");
        odd06.oddaj('G');
        odd00.oddaj('M');
        System.out.println("<" + spr27.odZadnjic() + ">");
        System.out.println(spr01.koliko());
        odd11.oddaj('m');
        odd10.oddaj('x');
        odd11.oddaj('J');
        odd02.oddaj('I');
        System.out.println(spr34.koliko());
        odd08.oddaj('N');
        System.out.println(spr21.koliko());
        System.out.println(spr10.koliko());
        odd03.oddaj('y');
        odd08.oddaj('d');
        odd06.oddaj('N');
        odd00.oddaj('R');
        odd00.oddaj('G');
        odd10.oddaj('B');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd08.oddaj('v');
        odd00.oddaj('K');
        odd00.oddaj('E');
        System.out.println(spr33.koliko());
        odd10.oddaj('U');
        odd00.oddaj('R');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd06.oddaj('B');
        System.out.println("<" + spr42.odZadnjic() + ">");
        System.out.println("<" + spr29.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr48.odZadnjic() + ">");
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd02.oddaj('h');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd09.oddaj('c');
        odd03.oddaj('w');
        System.out.println("<" + spr34.odZadnjic() + ">");
        odd02.oddaj('C');
        odd00.oddaj('g');
        odd00.oddaj('a');
        odd10.oddaj('P');
        System.out.println(spr47.koliko());
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd05.oddaj('a');
        odd00.oddaj('d');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd08.oddaj('E');
        System.out.println(spr09.koliko());
        odd04.oddaj('T');
        odd06.oddaj('W');
        System.out.println("<" + spr33.odZadnjic() + ">");
        odd04.oddaj('R');
        odd01.oddaj('p');
        odd00.oddaj('n');
        System.out.println(spr12.koliko());
        odd02.oddaj('z');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd02.oddaj('h');
        System.out.println("<" + spr34.odZadnjic() + ">");
        odd05.oddaj('T');
        odd05.oddaj('H');
        odd10.oddaj('j');
        System.out.println(spr04.koliko());
        odd00.oddaj('S');
        System.out.println("<" + spr24.odZadnjic() + ">");
        System.out.println(spr18.koliko());
        odd05.oddaj('q');
        System.out.println(spr14.koliko());
        odd06.oddaj('O');
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println(spr29.koliko());
        odd06.oddaj('k');
        odd04.oddaj('n');
        odd05.oddaj('c');
        odd11.oddaj('E');
        odd03.oddaj('K');
        System.out.println(spr26.koliko());
        System.out.println("<" + spr50.odZadnjic() + ">");
        System.out.println(spr34.koliko());
        odd09.oddaj('Y');
        odd09.oddaj('Q');
        odd00.oddaj('d');
        odd09.oddaj('r');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd01.oddaj('i');
        odd05.oddaj('M');
        odd06.oddaj('D');
        System.out.println(spr41.koliko());
        odd05.oddaj('b');
        odd10.oddaj('l');
        System.out.println("<" + spr43.odZadnjic() + ">");
        System.out.println(spr25.koliko());
        odd04.oddaj('L');
        odd08.oddaj('G');
        odd02.oddaj('O');
        System.out.println(spr25.koliko());
        odd01.oddaj('m');
        odd03.oddaj('x');
        odd11.oddaj('t');
        odd09.oddaj('b');
        System.out.println(spr22.koliko());
        odd07.oddaj('H');
        odd00.oddaj('e');
        odd03.oddaj('x');
        odd11.oddaj('p');
        System.out.println("<" + spr31.odZadnjic() + ">");
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr15.odZadnjic() + ">");
        odd10.oddaj('j');
        odd00.oddaj('Z');
        odd00.oddaj('c');
        odd06.oddaj('g');
        odd08.oddaj('Z');
        odd09.oddaj('U');
        odd02.oddaj('S');
        odd00.oddaj('s');
        odd03.oddaj('R');
        odd08.oddaj('V');
        odd05.oddaj('E');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println(spr06.koliko());
        odd07.oddaj('p');
        System.out.println(spr47.koliko());
        odd09.oddaj('Q');
        System.out.println(spr44.koliko());
        odd00.oddaj('p');
        odd04.oddaj('z');
        System.out.println(spr48.koliko());
        System.out.println(spr29.koliko());
        System.out.println(spr07.koliko());
        odd10.oddaj('S');
        odd01.oddaj('P');
        odd07.oddaj('X');
        System.out.println(spr31.koliko());
        System.out.println("<" + spr38.odZadnjic() + ">");
        System.out.println(spr34.koliko());
        odd11.oddaj('I');
        odd01.oddaj('U');
        System.out.println("<" + spr35.odZadnjic() + ">");
        odd08.oddaj('s');
        odd04.oddaj('l');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd09.oddaj('g');
        odd04.oddaj('g');
        odd04.oddaj('x');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd08.oddaj('p');
        odd04.oddaj('h');
        odd08.oddaj('g');
        System.out.println(spr32.koliko());
        odd11.oddaj('Y');
        System.out.println(spr49.koliko());
        odd07.oddaj('K');
        odd02.oddaj('z');
        odd02.oddaj('C');
        odd07.oddaj('m');
        odd07.oddaj('Y');
        odd11.oddaj('h');
        odd07.oddaj('l');
        odd03.oddaj('n');
        odd02.oddaj('A');
        odd08.oddaj('I');
        System.out.println(spr21.koliko());
        odd02.oddaj('D');
        System.out.println(spr49.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd05.oddaj('N');
        odd09.oddaj('d');
        odd10.oddaj('f');
        odd10.oddaj('A');
        odd00.oddaj('B');
        odd08.oddaj('Z');
        odd00.oddaj('t');
        odd11.oddaj('i');
        odd09.oddaj('U');
        odd06.oddaj('j');
        System.out.println(spr31.koliko());
        odd02.oddaj('I');
        odd10.oddaj('C');
        odd09.oddaj('n');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd03.oddaj('j');
        odd09.oddaj('u');
        odd08.oddaj('H');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd02.oddaj('F');
        odd11.oddaj('n');
        System.out.println(spr41.koliko());
        System.out.println("<" + spr23.odZadnjic() + ">");
        odd06.oddaj('L');
        System.out.println("<" + spr44.odZadnjic() + ">");
        odd11.oddaj('j');
        System.out.println(spr20.koliko());
        odd04.oddaj('h');
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd02.oddaj('M');
        odd11.oddaj('g');
        odd04.oddaj('J');
        odd04.oddaj('R');
        odd03.oddaj('w');
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd07.oddaj('r');
        System.out.println("<" + spr17.odZadnjic() + ">");
        odd09.oddaj('W');
        odd11.oddaj('W');
        odd03.oddaj('O');
        odd02.oddaj('c');
        odd07.oddaj('H');
        System.out.println("<" + spr29.odZadnjic() + ">");
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd11.oddaj('T');
        odd08.oddaj('A');
        System.out.println("<" + spr02.odZadnjic() + ">");
        odd06.oddaj('y');
        odd01.oddaj('c');
        odd02.oddaj('w');
        odd11.oddaj('y');
        System.out.println(spr38.koliko());
        odd01.oddaj('R');
        odd07.oddaj('T');
        odd11.oddaj('t');
        odd10.oddaj('V');
        odd11.oddaj('J');
        odd02.oddaj('J');
        odd00.oddaj('h');
        odd03.oddaj('c');
        odd05.oddaj('x');
        odd11.oddaj('Y');
        odd04.oddaj('M');
        odd08.oddaj('J');
        odd00.oddaj('J');
        odd01.oddaj('s');
        odd03.oddaj('d');
        odd08.oddaj('t');
        odd10.oddaj('d');
        odd05.oddaj('G');
        odd09.oddaj('S');
        odd09.oddaj('a');
        odd03.oddaj('G');
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd05.oddaj('u');
        System.out.println(spr15.koliko());
        odd09.oddaj('g');
        System.out.println("<" + spr43.odZadnjic() + ">");
        System.out.println(spr19.koliko());
        System.out.println("<" + spr29.odZadnjic() + ">");
        odd06.oddaj('m');
        System.out.println(spr03.koliko());
        odd06.oddaj('r');
        odd00.oddaj('u');
        odd07.oddaj('z');
        odd11.oddaj('w');
        odd10.oddaj('r');
        odd02.oddaj('l');
        odd10.oddaj('J');
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd02.oddaj('I');
        odd07.oddaj('s');
        odd06.oddaj('z');
        odd02.oddaj('Z');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd07.oddaj('A');
        odd11.oddaj('V');
        System.out.println(spr14.koliko());
        System.out.println(spr08.koliko());
        odd03.oddaj('d');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println("<" + spr24.odZadnjic() + ">");
        System.out.println(spr26.koliko());
        odd06.oddaj('c');
        odd07.oddaj('E');
        System.out.println(spr28.koliko());
        odd09.oddaj('z');
        System.out.println(spr05.koliko());
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd11.oddaj('N');
        odd11.oddaj('D');
        System.out.println(spr33.koliko());
        odd01.oddaj('z');
        odd07.oddaj('f');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd02.oddaj('t');
        odd05.oddaj('a');
        odd02.oddaj('m');
        System.out.println(spr29.koliko());
        odd11.oddaj('p');
        System.out.println(spr04.koliko());
        System.out.println(spr46.koliko());
        odd06.oddaj('f');
        odd07.oddaj('b');
        System.out.println(spr47.koliko());
        System.out.println(spr44.koliko());
        odd07.oddaj('N');
        odd10.oddaj('Z');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd07.oddaj('h');
        odd08.oddaj('C');
        odd02.oddaj('M');
        odd02.oddaj('r');
        odd04.oddaj('S');
        System.out.println("<" + spr38.odZadnjic() + ">");
        odd10.oddaj('g');
        odd00.oddaj('f');
        odd08.oddaj('L');
        odd06.oddaj('X');
        odd05.oddaj('k');
        odd00.oddaj('D');
        odd04.oddaj('b');
        odd08.oddaj('S');
        odd09.oddaj('D');
        odd04.oddaj('o');
        odd04.oddaj('J');
        odd07.oddaj('p');
        odd11.oddaj('p');
        System.out.println(spr44.koliko());
        odd03.oddaj('Q');
        odd11.oddaj('c');
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd06.oddaj('C');
        odd04.oddaj('c');
        System.out.println(spr34.koliko());
        odd03.oddaj('H');
        odd09.oddaj('j');
        odd04.oddaj('f');
        odd10.oddaj('D');
        System.out.println(spr20.koliko());
        odd04.oddaj('s');
        System.out.println(spr41.koliko());
        odd11.oddaj('K');
        odd00.oddaj('e');
        System.out.println(spr11.koliko());
        odd05.oddaj('H');
        odd11.oddaj('M');
        odd00.oddaj('R');
        odd01.oddaj('T');
        odd03.oddaj('R');
        odd11.oddaj('l');
        odd05.oddaj('A');
        odd09.oddaj('Q');
        odd08.oddaj('L');
        System.out.println(spr28.koliko());
        odd10.oddaj('l');
        odd04.oddaj('z');
        System.out.println("<" + spr42.odZadnjic() + ">");
        odd05.oddaj('F');
        odd06.oddaj('Q');
        odd06.oddaj('k');
        System.out.println(spr01.koliko());
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd03.oddaj('Q');
        odd10.oddaj('s');
        System.out.println(spr06.koliko());
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd05.oddaj('x');
        odd02.oddaj('S');
        odd01.oddaj('k');
        System.out.println(spr05.koliko());
        odd03.oddaj('h');
        odd06.oddaj('y');
        odd01.oddaj('K');
        odd04.oddaj('i');
        System.out.println(spr32.koliko());
        odd07.oddaj('S');
        odd00.oddaj('i');
        odd05.oddaj('E');
        System.out.println(spr12.koliko());
        odd04.oddaj('Q');
        odd08.oddaj('v');
        odd02.oddaj('x');
        odd01.oddaj('U');
        odd01.oddaj('S');
        odd05.oddaj('C');
        System.out.println("<" + spr49.odZadnjic() + ">");
        System.out.println(spr44.koliko());
        odd04.oddaj('T');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd08.oddaj('k');
        System.out.println("<" + spr06.odZadnjic() + ">");
        odd07.oddaj('X');
        System.out.println(spr18.koliko());
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd03.oddaj('z');
        odd03.oddaj('S');
        odd11.oddaj('I');
        odd01.oddaj('Q');
        System.out.println("<" + spr11.odZadnjic() + ">");
        odd08.oddaj('b');
        System.out.println(spr10.koliko());
        odd09.oddaj('o');
        odd00.oddaj('t');
        odd09.oddaj('G');
        odd02.oddaj('J');
        System.out.println("<" + spr27.odZadnjic() + ">");
        odd06.oddaj('c');
        odd07.oddaj('H');
        System.out.println("<" + spr07.odZadnjic() + ">");
        odd02.oddaj('n');
        odd11.oddaj('N');
        odd08.oddaj('q');
        odd09.oddaj('w');
        odd10.oddaj('M');
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd10.oddaj('m');
        odd01.oddaj('r');
        System.out.println("<" + spr30.odZadnjic() + ">");
        System.out.println(spr37.koliko());
        odd03.oddaj('Q');
        odd02.oddaj('A');
        odd06.oddaj('h');
        odd08.oddaj('F');
        odd04.oddaj('X');
        System.out.println(spr07.koliko());
        odd02.oddaj('W');
        odd08.oddaj('K');
        odd08.oddaj('k');
        System.out.println("<" + spr36.odZadnjic() + ">");
        System.out.println("<" + spr38.odZadnjic() + ">");
        System.out.println(spr34.koliko());
        System.out.println(spr15.koliko());
        odd11.oddaj('f');
        odd04.oddaj('B');
        odd02.oddaj('L');
        System.out.println(spr12.koliko());
        System.out.println(spr16.koliko());
        odd09.oddaj('r');
        System.out.println("<" + spr44.odZadnjic() + ">");
        odd11.oddaj('Z');
        odd08.oddaj('i');
        System.out.println("<" + spr19.odZadnjic() + ">");
        odd02.oddaj('U');
        odd04.oddaj('U');
        odd07.oddaj('T');
        odd04.oddaj('F');
        System.out.println("<" + spr49.odZadnjic() + ">");
        System.out.println("<" + spr40.odZadnjic() + ">");
        System.out.println("<" + spr31.odZadnjic() + ">");
        odd10.oddaj('f');
        odd03.oddaj('f');
        System.out.println("<" + spr02.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd01.oddaj('a');
        System.out.println(spr20.koliko());
        odd04.oddaj('g');
        odd04.oddaj('g');
        System.out.println("<" + spr05.odZadnjic() + ">");
        odd11.oddaj('U');
        odd11.oddaj('Z');
        odd04.oddaj('d');
        odd11.oddaj('U');
        odd10.oddaj('x');
        odd02.oddaj('e');
        odd02.oddaj('W');
        odd08.oddaj('G');
        System.out.println(spr09.koliko());
        odd07.oddaj('g');
        odd04.oddaj('M');
        odd02.oddaj('Y');
        odd01.oddaj('b');
        odd01.oddaj('M');
        System.out.println(spr10.koliko());
        odd02.oddaj('e');
        System.out.println(spr17.koliko());
        odd04.oddaj('O');
        odd05.oddaj('E');
        System.out.println(spr41.koliko());
        odd09.oddaj('f');
        odd07.oddaj('M');
        odd10.oddaj('q');
        odd03.oddaj('D');
        System.out.println(spr19.koliko());
        System.out.println(spr43.koliko());
        System.out.println(spr26.koliko());
        odd07.oddaj('D');
        odd10.oddaj('H');
        odd02.oddaj('k');
        odd03.oddaj('o');
        System.out.println(spr30.koliko());
        odd05.oddaj('x');
        System.out.println(spr28.koliko());
        System.out.println("<" + spr04.odZadnjic() + ">");
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd10.oddaj('L');
        System.out.println(spr02.koliko());
        odd00.oddaj('f');
        System.out.println(spr24.koliko());
        odd09.oddaj('t');
        odd01.oddaj('O');
        odd06.oddaj('U');
        System.out.println(spr15.koliko());
        odd04.oddaj('a');
        odd06.oddaj('p');
        odd08.oddaj('h');
        System.out.println(spr45.koliko());
        odd07.oddaj('j');
        System.out.println("<" + spr09.odZadnjic() + ">");
        odd01.oddaj('F');
        odd01.oddaj('O');
        odd00.oddaj('q');
        odd06.oddaj('s');
        odd10.oddaj('f');
        System.out.println(spr31.koliko());
        odd11.oddaj('Y');
        odd07.oddaj('f');
        odd09.oddaj('Z');
        odd06.oddaj('H');
        System.out.println(spr34.koliko());
        odd08.oddaj('p');
        System.out.println(spr02.koliko());
        odd10.oddaj('O');
        System.out.println("<" + spr04.odZadnjic() + ">");
        odd03.oddaj('f');
        odd09.oddaj('H');
        odd01.oddaj('S');
        System.out.println("<" + spr50.odZadnjic() + ">");
        System.out.println(spr30.koliko());
        System.out.println("<" + spr32.odZadnjic() + ">");
        System.out.println(spr25.koliko());
        odd00.oddaj('C');
        odd08.oddaj('n');
        odd07.oddaj('y');
        odd11.oddaj('R');
        odd06.oddaj('Y');
        odd06.oddaj('z');
        odd01.oddaj('I');
        odd07.oddaj('X');
        odd11.oddaj('U');
        odd10.oddaj('w');
        odd05.oddaj('c');
        odd09.oddaj('d');
        System.out.println(spr04.koliko());
        odd10.oddaj('e');
        odd05.oddaj('d');
        System.out.println("<" + spr39.odZadnjic() + ">");
        odd07.oddaj('h');
        odd04.oddaj('P');
        odd10.oddaj('R');
        odd06.oddaj('B');
        odd03.oddaj('p');
        System.out.println(spr20.koliko());
        System.out.println("<" + spr13.odZadnjic() + ">");
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd10.oddaj('W');
        odd04.oddaj('H');
        odd11.oddaj('K');
        odd02.oddaj('e');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd05.oddaj('l');
        odd07.oddaj('D');
        odd01.oddaj('P');
        odd04.oddaj('j');
        System.out.println(spr17.koliko());
        System.out.println(spr28.koliko());
        odd08.oddaj('i');
        System.out.println("<" + spr43.odZadnjic() + ">");
        odd07.oddaj('Y');
        odd01.oddaj('R');
        odd04.oddaj('H');
        odd06.oddaj('d');
        System.out.println(spr27.koliko());
        odd01.oddaj('I');
        odd11.oddaj('M');
        System.out.println(spr10.koliko());
        odd02.oddaj('v');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd02.oddaj('o');
        System.out.println(spr15.koliko());
        odd00.oddaj('V');
        System.out.println("<" + spr34.odZadnjic() + ">");
        System.out.println(spr14.koliko());
        odd09.oddaj('V');
        odd01.oddaj('Z');
        System.out.println("<" + spr41.odZadnjic() + ">");
        odd11.oddaj('X');
        odd08.oddaj('l');
        odd05.oddaj('U');
        odd03.oddaj('u');
        System.out.println(spr12.koliko());
        odd09.oddaj('h');
        System.out.println(spr32.koliko());
        odd00.oddaj('o');
        odd10.oddaj('R');
        System.out.println("<" + spr34.odZadnjic() + ">");
        System.out.println(spr19.koliko());
        odd08.oddaj('U');
        odd05.oddaj('O');
        odd00.oddaj('V');
        odd03.oddaj('p');
        odd09.oddaj('v');
        odd03.oddaj('N');
        odd03.oddaj('B');
        odd02.oddaj('Y');
        odd04.oddaj('c');
        odd07.oddaj('j');
        System.out.println(spr02.koliko());
        odd08.oddaj('b');
        System.out.println(spr41.koliko());
        odd08.oddaj('c');
        odd07.oddaj('R');
        System.out.println(spr44.koliko());
        odd10.oddaj('W');
        odd01.oddaj('G');
        System.out.println(spr42.koliko());
        System.out.println(spr01.koliko());
        odd02.oddaj('R');
        System.out.println(spr29.koliko());
        odd04.oddaj('Q');
        odd05.oddaj('o');
        odd03.oddaj('L');
        odd10.oddaj('F');
        odd01.oddaj('b');
        System.out.println(spr13.koliko());
        odd09.oddaj('z');
        odd07.oddaj('V');
        System.out.println(spr24.koliko());
        odd08.oddaj('A');
        odd03.oddaj('o');
        System.out.println(spr26.koliko());
        odd04.oddaj('f');
        System.out.println("<" + spr03.odZadnjic() + ">");
        odd03.oddaj('W');
        odd09.oddaj('I');
        odd03.oddaj('t');
        System.out.println(spr20.koliko());
        odd04.oddaj('d');
        odd11.oddaj('P');
        odd04.oddaj('s');
        System.out.println(spr46.koliko());
        odd00.oddaj('T');
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd00.oddaj('t');
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println("<" + spr25.odZadnjic() + ">");
        odd10.oddaj('F');
        System.out.println("<" + spr50.odZadnjic() + ">");
        odd09.oddaj('s');
        odd08.oddaj('l');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println(spr47.koliko());
        System.out.println("<" + spr22.odZadnjic() + ">");
        System.out.println(spr41.koliko());
        odd02.oddaj('h');
        odd07.oddaj('K');
        System.out.println("<" + spr48.odZadnjic() + ">");
        System.out.println("<" + spr36.odZadnjic() + ">");
        odd00.oddaj('v');
        System.out.println(spr18.koliko());
        odd10.oddaj('X');
        System.out.println("<" + spr35.odZadnjic() + ">");
        odd05.oddaj('e');
        odd06.oddaj('D');
        System.out.println("<" + spr32.odZadnjic() + ">");
        odd03.oddaj('L');
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd02.oddaj('L');
        System.out.println(spr49.koliko());
        odd06.oddaj('f');
        odd03.oddaj('X');
        odd03.oddaj('J');
        odd11.oddaj('Y');
        odd08.oddaj('Q');
        System.out.println(spr16.koliko());
        System.out.println(spr44.koliko());
        odd02.oddaj('Q');
        odd09.oddaj('z');
        odd07.oddaj('v');
        odd10.oddaj('D');
        odd10.oddaj('h');
        System.out.println(spr46.koliko());
        System.out.println(spr23.koliko());
        System.out.println(spr06.koliko());
        odd04.oddaj('y');
        odd02.oddaj('C');
        odd09.oddaj('k');
        System.out.println(spr14.koliko());
        System.out.println("<" + spr08.odZadnjic() + ">");
        odd02.oddaj('F');
        System.out.println("<" + spr16.odZadnjic() + ">");
        System.out.println(spr27.koliko());
        odd11.oddaj('l');
        System.out.println(spr35.koliko());
        odd00.oddaj('X');
        odd10.oddaj('I');
        System.out.println("<" + spr25.odZadnjic() + ">");
        System.out.println(spr42.koliko());
        System.out.println(spr50.koliko());
        System.out.println(spr16.koliko());
        odd09.oddaj('a');
        odd01.oddaj('X');
        odd07.oddaj('j');
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd10.oddaj('C');
        odd06.oddaj('E');
        odd11.oddaj('J');
        odd08.oddaj('k');
        odd03.oddaj('I');
        odd11.oddaj('J');
        odd00.oddaj('s');
        System.out.println(spr19.koliko());
        System.out.println(spr34.koliko());
        odd10.oddaj('I');
        odd03.oddaj('u');
        odd10.oddaj('F');
        odd00.oddaj('h');
        odd02.oddaj('I');
        System.out.println("<" + spr00.odZadnjic() + ">");
        odd11.oddaj('b');
        odd00.oddaj('M');
        odd11.oddaj('C');
        System.out.println(spr17.koliko());
        odd04.oddaj('h');
        odd04.oddaj('r');
        odd04.oddaj('I');
        System.out.println(spr33.koliko());
        System.out.println("<" + spr48.odZadnjic() + ">");
        odd01.oddaj('p');
        System.out.println("<" + spr37.odZadnjic() + ">");
        odd03.oddaj('G');
        System.out.println("<" + spr20.odZadnjic() + ">");
        System.out.println("<" + spr46.odZadnjic() + ">");
        System.out.println("<" + spr14.odZadnjic() + ">");
        odd07.oddaj('C');
        odd11.oddaj('n');
        odd01.oddaj('f');
        odd07.oddaj('U');
        System.out.println("<" + spr50.odZadnjic() + ">");
        System.out.println(spr21.koliko());
        odd05.oddaj('q');
        System.out.println(spr47.koliko());
        System.out.println(spr41.koliko());
        odd01.oddaj('g');
        odd05.oddaj('O');
        odd08.oddaj('B');
        System.out.println(spr06.koliko());
        System.out.println(spr32.koliko());
        System.out.println("<" + spr18.odZadnjic() + ">");
        odd03.oddaj('e');
        odd06.oddaj('R');
        odd03.oddaj('w');
        System.out.println("<" + spr26.odZadnjic() + ">");
        System.out.println("<" + spr22.odZadnjic() + ">");
        odd07.oddaj('P');
        odd01.oddaj('a');
        odd04.oddaj('j');
        odd05.oddaj('B');
        System.out.println(spr10.koliko());
        System.out.println(spr02.koliko());
        odd01.oddaj('x');
        odd11.oddaj('A');
        odd08.oddaj('V');
        System.out.println(spr43.koliko());
        odd06.oddaj('I');
        System.out.println(spr15.koliko());
        odd01.oddaj('H');
        odd08.oddaj('E');
        System.out.println(spr19.koliko());
        System.out.println(spr41.koliko());
        System.out.println(spr25.koliko());
        odd00.oddaj('Y');
        odd07.oddaj('P');
        odd10.oddaj('R');
        odd08.oddaj('T');
        odd01.oddaj('v');
        System.out.println("<" + spr13.odZadnjic() + ">");
        odd03.oddaj('n');
        odd05.oddaj('V');
        System.out.println("<" + spr06.odZadnjic() + ">");
        System.out.println("<" + spr30.odZadnjic() + ">");
        odd06.oddaj('J');
        System.out.println("<" + spr47.odZadnjic() + ">");
        System.out.println(spr49.koliko());
        System.out.println("<" + spr28.odZadnjic() + ">");
        System.out.println("<" + spr33.odZadnjic() + ">");
        System.out.println(spr12.koliko());
        odd07.oddaj('s');
        odd11.oddaj('n');
        odd04.oddaj('F');
        odd01.oddaj('M');
        odd07.oddaj('I');
        System.out.println("<" + spr21.odZadnjic() + ">");
        odd05.oddaj('s');
        System.out.println(spr19.koliko());
        odd06.oddaj('n');
        odd06.oddaj('Y');
        odd01.oddaj('K');
        odd06.oddaj('F');
        odd02.oddaj('s');
        odd06.oddaj('Z');
        odd02.oddaj('v');
        System.out.println("<" + spr12.odZadnjic() + ">");
        odd02.oddaj('W');
        odd00.oddaj('u');
        System.out.println(spr46.koliko());
        System.out.println(spr05.koliko());
        System.out.println("<" + spr11.odZadnjic() + ">");
        System.out.println("<" + spr16.odZadnjic() + ">");
        odd03.oddaj('B');
        odd00.oddaj('b');
        odd05.oddaj('t');
        odd09.oddaj('j');
        odd09.oddaj('Y');
        System.out.println(spr50.koliko());
        odd01.oddaj('A');
        odd03.oddaj('o');
        odd09.oddaj('Z');
        odd03.oddaj('S');
        System.out.println(spr18.koliko());
        odd01.oddaj('i');
        odd08.oddaj('X');
        odd01.oddaj('f');
        System.out.println(spr49.koliko());
        System.out.println(spr04.koliko());
        System.out.println(spr07.koliko());
        System.out.println(spr24.koliko());
        odd01.oddaj('o');
        odd02.oddaj('K');
        odd04.oddaj('j');
        System.out.println(spr28.koliko());
        odd01.oddaj('Z');
        System.out.println("<" + spr26.odZadnjic() + ">");
        odd06.oddaj('Z');
        odd01.oddaj('W');
        odd11.oddaj('s');
        odd01.oddaj('z');
        odd01.oddaj('T');
        odd01.oddaj('x');
        odd04.oddaj('S');
        System.out.println(spr04.koliko());
        System.out.println(spr48.koliko());
        System.out.println("<" + spr01.odZadnjic() + ">");
        odd03.oddaj('n');
        odd10.oddaj('f');
        System.out.println("<" + spr47.odZadnjic() + ">");
        odd01.oddaj('a');
        odd01.oddaj('K');
        odd00.oddaj('J');
        System.out.println(spr12.koliko());
        odd07.oddaj('q');
        System.out.println("<" + spr24.odZadnjic() + ">");
        odd09.oddaj('L');
        odd07.oddaj('m');
        odd08.oddaj('e');
        odd01.oddaj('v');
        odd10.oddaj('i');
        System.out.println("<" + spr28.odZadnjic() + ">");
        odd07.oddaj('q');
        odd08.oddaj('j');
        odd05.oddaj('J');
        System.out.println(spr10.koliko());
        System.out.println(spr34.koliko());
        odd08.oddaj('a');
        odd01.oddaj('u');
        odd09.oddaj('r');
        System.out.println(spr36.koliko());
        System.out.println(spr28.koliko());
        System.out.println(spr19.koliko());
        odd04.oddaj('q');
        odd11.oddaj('T');
        System.out.println(spr43.koliko());
        odd02.oddaj('o');
        System.out.println("<" + spr45.odZadnjic() + ">");
        odd06.oddaj('d');
        System.out.println(spr01.koliko());
        odd05.oddaj('R');
    }
}
