
public class Test04 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_sahKU");
        t.prejmi(new Tretja.Docent(), "doc_NcV1w");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_8JEWx");
        t.prejmi(new Tretja.Docent(), "doc_CSP4o");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_xGjhu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_MuidK");
        t.prejmi(new Tretja.Docent(), "doc_7nGRJ");
        t.prejmi(new Tretja.Docent(), "doc_GsuGY");
        t.prejmi(new Tretja.Asistent(), "as_cmHEQ");
        t.prejmi(new Tretja.Docent(), "doc_89LoM");
        t.prejmi(new Tretja.Docent(), "doc_xECvI");
        t.prejmi(new Tretja.Profesor(), "prof_Yz6ao");
        t.prejmi(new Tretja.Profesor(), "prof_ZP8RW");
        t.prejmi(new Tretja.Profesor(), "prof_HGar8");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_9vrg4");
        t.prejmi(new Tretja.Asistent(), "as_xPBVv");
        t.prejmi(new Tretja.Asistent(), "as_ZjRpv");
        t.prejmi(new Tretja.Asistent(), "as_ZTtnk");
        t.prejmi(new Tretja.Profesor(), "prof_eUzho");
        t.prejmi(new Tretja.Profesor(), "prof_j8buX");
        t.prejmi(new Tretja.Docent(), "doc_iMOW9");
        t.prejmi(new Tretja.Asistent(), "as_AUOXk");
        t.prejmi(new Tretja.Asistent(), "as_peidp");
        t.prejmi(new Tretja.Profesor(), "prof_4Ix0Y");
        t.prejmi(new Tretja.Asistent(), "as_tfFKP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_gszZM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_p0dvI");
        t.prejmi(new Tretja.Profesor(), "prof_PAI3D");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_syo9w");
        t.prejmi(new Tretja.Asistent(), "as_ltf1d");
        t.prejmi(new Tretja.Docent(), "doc_sw6TY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_wj72L");
        t.prejmi(new Tretja.Profesor(), "prof_ATYNO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ExXwz");
        t.prejmi(new Tretja.Profesor(), "prof_QuHcd");
        t.prejmi(new Tretja.Asistent(), "as_XIiVn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_BbOcV");
        t.prejmi(new Tretja.Asistent(), "as_CR2Tu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Rq4sb");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_bcRrV");
        t.prejmi(new Tretja.Asistent(), "as_uQ3IL");
        t.prejmi(new Tretja.Profesor(), "prof_A6n2q");
        t.prejmi(new Tretja.Asistent(), "as_OrMwE");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Su3pQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_PQ5Au");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_mHeNi");
        t.prejmi(new Tretja.Docent(), "doc_gPsF1");
        t.prejmi(new Tretja.Asistent(), "as_WnF4n");
        t.prejmi(new Tretja.Docent(), "doc_bD8Mj");
        t.prejmi(new Tretja.Asistent(), "as_LkrFW");
        t.prejmi(new Tretja.Profesor(), "prof_1PyaR");
        t.prejmi(new Tretja.Profesor(), "prof_tPJFD");
        t.prejmi(new Tretja.Docent(), "doc_pAdg6");
        t.prejmi(new Tretja.Asistent(), "as_T3UOq");
        t.prejmi(new Tretja.Asistent(), "as_9NWCt");
        t.prejmi(new Tretja.Profesor(), "prof_sSJjO");
        t.prejmi(new Tretja.Profesor(), "prof_8qRSi");
        t.prejmi(new Tretja.Asistent(), "as_kRSgh");
        t.prejmi(new Tretja.Docent(), "doc_ALvqt");
        t.prejmi(new Tretja.Docent(), "doc_F6pBM");
        t.prejmi(new Tretja.Profesor(), "prof_xMnEx");
        t.prejmi(new Tretja.Asistent(), "as_SiDwN");
        t.prejmi(new Tretja.Docent(), "doc_CZio4");
        t.prejmi(new Tretja.Profesor(), "prof_OY5oz");
        t.prejmi(new Tretja.Docent(), "doc_nmVlF");
        t.prejmi(new Tretja.Profesor(), "prof_du0fi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Pd2e1");
        t.prejmi(new Tretja.Asistent(), "as_UKNSZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_JCqXX");
        t.prejmi(new Tretja.Asistent(), "as_hkQQ5");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_etSUM");
        t.prejmi(new Tretja.Profesor(), "prof_7Szob");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_hJWBU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_WLmHH");
        t.prejmi(new Tretja.Profesor(), "prof_EI6RP");
        t.prejmi(new Tretja.Docent(), "doc_6Z0gc");
        t.prejmi(new Tretja.Asistent(), "as_ebwlK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_9WGYO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_XtXhb");
        t.prejmi(new Tretja.Profesor(), "prof_f2pDk");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_EcoHG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_q8R5d");
        t.prejmi(new Tretja.Docent(), "doc_rObKj");
        t.prejmi(new Tretja.Asistent(), "as_3Z6RQ");
        t.prejmi(new Tretja.Asistent(), "as_H719v");
        t.prejmi(new Tretja.Profesor(), "prof_9PpaW");
        t.prejmi(new Tretja.Docent(), "doc_h90Xz");
        t.prejmi(new Tretja.Profesor(), "prof_wZElA");
        t.prejmi(new Tretja.Profesor(), "prof_G6X3L");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_GoWej");
        t.prejmi(new Tretja.Asistent(), "as_HVz7U");
        t.prejmi(new Tretja.Docent(), "doc_mVU9M");
        t.prejmi(new Tretja.Profesor(), "prof_PFiUy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_OwizQ");
        t.prejmi(new Tretja.Profesor(), "prof_sK7qA");
        t.prejmi(new Tretja.Docent(), "doc_xsrtG");
        t.prejmi(new Tretja.Docent(), "doc_fJWqY");
        t.prejmi(new Tretja.Asistent(), "as_74qcT");
        t.prejmi(new Tretja.Docent(), "doc_QoyDu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_T6kmb");
        t.prejmi(new Tretja.Docent(), "doc_scZjp");
        t.prejmi(new Tretja.Profesor(), "prof_1yLRf");
        t.prejmi(new Tretja.Asistent(), "as_1yISX");
        t.prejmi(new Tretja.Docent(), "doc_j37pV");
        t.prejmi(new Tretja.Docent(), "doc_8fTFo");
        t.prejmi(new Tretja.Profesor(), "prof_QNCka");
        t.prejmi(new Tretja.Asistent(), "as_Krzw8");
        t.prejmi(new Tretja.Docent(), "doc_dt3ef");
        t.prejmi(new Tretja.Asistent(), "as_vzE7m");
        t.prejmi(new Tretja.Profesor(), "prof_SQomF");
        t.prejmi(new Tretja.Profesor(), "prof_1pbhP");
        t.prejmi(new Tretja.Asistent(), "as_zdIJP");
        t.prejmi(new Tretja.Docent(), "doc_JuYbf");
        t.prejmi(new Tretja.Profesor(), "prof_NpsW3");
        t.prejmi(new Tretja.Docent(), "doc_G9oKS");
        t.prejmi(new Tretja.Docent(), "doc_mmklh");
        t.prejmi(new Tretja.Docent(), "doc_EpnzF");
        t.prejmi(new Tretja.Docent(), "doc_WkGCP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_4zQsP");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_WOb4O");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_eeyD3");
        t.prejmi(new Tretja.Profesor(), "prof_b5oXD");
        t.prejmi(new Tretja.Docent(), "doc_bucre");
        t.prejmi(new Tretja.Docent(), "doc_pV1kx");
        t.prejmi(new Tretja.Docent(), "doc_okRFo");
        t.prejmi(new Tretja.Docent(), "doc_EvPPr");
        t.prejmi(new Tretja.Docent(), "doc_t9prJ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_s5emP");
        t.prejmi(new Tretja.Docent(), "doc_C66yO");
        t.prejmi(new Tretja.Profesor(), "prof_w4wjt");
        t.prejmi(new Tretja.Docent(), "doc_0mYaD");
        t.prejmi(new Tretja.Docent(), "doc_L5ae0");
        t.prejmi(new Tretja.Asistent(), "as_kPp8b");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_22i2m");
        t.prejmi(new Tretja.Docent(), "doc_BBVLF");
        t.prejmi(new Tretja.Profesor(), "prof_0YjZe");
        t.prejmi(new Tretja.Profesor(), "prof_o0RSL");
        t.prejmi(new Tretja.Asistent(), "as_Rqbiq");
        t.prejmi(new Tretja.Asistent(), "as_O7iFL");
        t.prejmi(new Tretja.Profesor(), "prof_dv9V0");
        t.prejmi(new Tretja.Asistent(), "as_bPlsd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_MJKGV");
        t.prejmi(new Tretja.Profesor(), "prof_lyO1p");
        t.prejmi(new Tretja.Asistent(), "as_2dZXN");
        t.prejmi(new Tretja.Docent(), "doc_LbVGo");
        t.prejmi(new Tretja.Docent(), "doc_fP9jF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_44u8W");
        t.prejmi(new Tretja.Asistent(), "as_cLTTV");
        t.prejmi(new Tretja.Asistent(), "as_70Aqz");
        t.prejmi(new Tretja.Docent(), "doc_gPuHu");
        t.prejmi(new Tretja.Docent(), "doc_YqulE");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_DteDk");
        t.prejmi(new Tretja.Profesor(), "prof_GNtCQ");
        t.prejmi(new Tretja.Docent(), "doc_xSjdW");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Bhgcc");
        t.prejmi(new Tretja.Docent(), "doc_JtMm6");
        t.prejmi(new Tretja.Profesor(), "prof_sfNLy");
        t.prejmi(new Tretja.Docent(), "doc_8leDb");
        t.prejmi(new Tretja.Docent(), "doc_UpP8V");
        t.prejmi(new Tretja.Asistent(), "as_9lGJL");
        t.prejmi(new Tretja.Asistent(), "as_4FTOq");
        t.prejmi(new Tretja.Asistent(), "as_9kNDZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_hUqx4");
        t.prejmi(new Tretja.Profesor(), "prof_QtpOw");
        t.prejmi(new Tretja.Profesor(), "prof_LGSVR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_IsvmL");
        t.prejmi(new Tretja.Docent(), "doc_bKKRo");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_PhLKE");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Hi0dG");
        t.prejmi(new Tretja.Docent(), "doc_cWCWj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_xQhMJ");
        t.prejmi(new Tretja.Profesor(), "prof_Qn7i1");
        t.prejmi(new Tretja.Asistent(), "as_WuJSi");
        t.prejmi(new Tretja.Docent(), "doc_VWAy0");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_SINCB");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_tx213");
        t.prejmi(new Tretja.Profesor(), "prof_dAOaC");
        t.prejmi(new Tretja.Docent(), "doc_hLtNI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_z8Pmu");
        t.prejmi(new Tretja.Docent(), "doc_hNNQg");
        t.prejmi(new Tretja.Docent(), "doc_UojXI");
        t.prejmi(new Tretja.Profesor(), "prof_wU8KI");
        t.prejmi(new Tretja.Asistent(), "as_ivIG5");
        t.prejmi(new Tretja.Profesor(), "prof_opotf");
        t.prejmi(new Tretja.Docent(), "doc_S6N7B");
        t.prejmi(new Tretja.Asistent(), "as_H8CMt");
        t.prejmi(new Tretja.Docent(), "doc_eCzgY");
        t.prejmi(new Tretja.Profesor(), "prof_usrVS");
        t.prejmi(new Tretja.Profesor(), "prof_GicDG");
        t.prejmi(new Tretja.Asistent(), "as_sOooW");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_h7CgY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_eNNY1");
        t.prejmi(new Tretja.Profesor(), "prof_XTjf4");
        t.prejmi(new Tretja.Asistent(), "as_eJWIl");
        t.prejmi(new Tretja.Asistent(), "as_ApZH1");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_IaGKb");
        t.prejmi(new Tretja.Docent(), "doc_7aJ2C");
        t.prejmi(new Tretja.Profesor(), "prof_B8G1h");
        t.prejmi(new Tretja.Profesor(), "prof_OI0rL");
        t.prejmi(new Tretja.Docent(), "doc_JIIi7");
        t.prejmi(new Tretja.Asistent(), "as_gGzSN");
        t.prejmi(new Tretja.Profesor(), "prof_ePcnC");
        t.prejmi(new Tretja.Docent(), "doc_lv7PB");
        t.prejmi(new Tretja.Docent(), "doc_T74SR");
        t.prejmi(new Tretja.Docent(), "doc_ooF69");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_KcaTf");
        t.prejmi(new Tretja.Docent(), "doc_ddXvp");
        t.prejmi(new Tretja.Docent(), "doc_NbMXa");
        t.prejmi(new Tretja.Profesor(), "prof_LK9bx");
        t.prejmi(new Tretja.Asistent(), "as_4kS0b");
        t.prejmi(new Tretja.Profesor(), "prof_Q1lUs");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_CnhGO");
        t.prejmi(new Tretja.Profesor(), "prof_RXNSb");
        t.prejmi(new Tretja.Profesor(), "prof_8Xxve");
        t.prejmi(new Tretja.Asistent(), "as_2mB4p");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_5FhNZ");
        t.prejmi(new Tretja.Docent(), "doc_xwXJg");
        t.prejmi(new Tretja.Docent(), "doc_SmStQ");
        t.prejmi(new Tretja.Profesor(), "prof_IGLeU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_VsexY");
        t.prejmi(new Tretja.Docent(), "doc_rI0F2");
        t.prejmi(new Tretja.Profesor(), "prof_bkg6m");
        t.prejmi(new Tretja.Asistent(), "as_cu2sy");
        t.prejmi(new Tretja.Asistent(), "as_IziDd");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_epZI1");
        t.prejmi(new Tretja.Profesor(), "prof_5I5Vb");
        t.prejmi(new Tretja.Asistent(), "as_7DoF2");
        t.prejmi(new Tretja.Asistent(), "as_dUD6G");
        t.prejmi(new Tretja.Asistent(), "as_7yhP0");
        t.prejmi(new Tretja.Asistent(), "as_IAmcd");
        t.prejmi(new Tretja.Asistent(), "as_W6ba4");
        t.prejmi(new Tretja.Profesor(), "prof_kkB0A");
        t.prejmi(new Tretja.Profesor(), "prof_fjNF7");
        t.prejmi(new Tretja.Profesor(), "prof_R7Xl6");
        t.prejmi(new Tretja.Asistent(), "as_uVDNr");
        t.prejmi(new Tretja.Profesor(), "prof_Muusj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_BjoIC");
        t.prejmi(new Tretja.Asistent(), "as_NMH8b");
        t.prejmi(new Tretja.Profesor(), "prof_KEYKl");
        t.prejmi(new Tretja.Profesor(), "prof_aXlSj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_IrpSj");
        t.prejmi(new Tretja.Profesor(), "prof_ZoEoc");
        t.prejmi(new Tretja.Profesor(), "prof_Lpwep");
        t.prejmi(new Tretja.Profesor(), "prof_K69Ps");
        t.prejmi(new Tretja.Asistent(), "as_P6y1s");
        t.prejmi(new Tretja.Profesor(), "prof_UrFAY");
        t.prejmi(new Tretja.Profesor(), "prof_ud05B");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_me1Ge");
        t.prejmi(new Tretja.Profesor(), "prof_LyMXP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_zn875");
        t.prejmi(new Tretja.Profesor(), "prof_Q1nBw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_urwIN");
        t.prejmi(new Tretja.Docent(), "doc_k6MZ4");
        t.prejmi(new Tretja.Docent(), "doc_N0N34");
        t.prejmi(new Tretja.Docent(), "doc_j5XWV");
        t.prejmi(new Tretja.Asistent(), "as_EmL67");
        t.prejmi(new Tretja.Profesor(), "prof_sCmcF");
        t.prejmi(new Tretja.Profesor(), "prof_51qeu");
        t.prejmi(new Tretja.Asistent(), "as_rk0g4");
        t.prejmi(new Tretja.Profesor(), "prof_Snfa1");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_WAgqU");
        t.prejmi(new Tretja.Asistent(), "as_OV3js");
        t.prejmi(new Tretja.Docent(), "doc_wCQxp");
        t.prejmi(new Tretja.Docent(), "doc_enbYO");
        t.prejmi(new Tretja.Docent(), "doc_uBMga");
        t.prejmi(new Tretja.Docent(), "doc_EiuLj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_T3mKC");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_xTacg");
        t.prejmi(new Tretja.Asistent(), "as_xnWiP");
        t.prejmi(new Tretja.Profesor(), "prof_SoKcR");
        t.prejmi(new Tretja.Docent(), "doc_vIyXH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Teezt");
        t.prejmi(new Tretja.Docent(), "doc_J2K5k");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_gYdhL");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_hptnm");
        t.prejmi(new Tretja.Profesor(), "prof_7TrZu");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_BHFna");
        t.prejmi(new Tretja.Docent(), "doc_hrXct");
        t.prejmi(new Tretja.Asistent(), "as_I7wtk");
        t.prejmi(new Tretja.Asistent(), "as_1dsVj");
        t.prejmi(new Tretja.Docent(), "doc_fNx0L");
        t.prejmi(new Tretja.Asistent(), "as_zmqZn");
        t.prejmi(new Tretja.Asistent(), "as_4qKYn");
        t.prejmi(new Tretja.Asistent(), "as_Ra2ck");
        t.prejmi(new Tretja.Profesor(), "prof_6FQWR");
        t.prejmi(new Tretja.Asistent(), "as_yGIv7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_uUFlo");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Jwb9b");
        t.prejmi(new Tretja.Profesor(), "prof_o80eO");
        t.prejmi(new Tretja.Asistent(), "as_T6jTF");
        t.prejmi(new Tretja.Docent(), "doc_U6wvC");
        t.prejmi(new Tretja.Asistent(), "as_EnJ0U");
        t.prejmi(new Tretja.Profesor(), "prof_xoh9M");
        t.prejmi(new Tretja.Asistent(), "as_VmWnu");
        t.prejmi(new Tretja.Asistent(), "as_LRC5V");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_mT4om");
        t.prejmi(new Tretja.Docent(), "doc_Ut44y");
        t.prejmi(new Tretja.Asistent(), "as_x7zqX");
        t.prejmi(new Tretja.Profesor(), "prof_lCHRV");
        t.prejmi(new Tretja.Profesor(), "prof_YIAbn");
        t.prejmi(new Tretja.Asistent(), "as_KGMIJ");
        t.prejmi(new Tretja.Profesor(), "prof_tV22a");
        t.prejmi(new Tretja.Profesor(), "prof_ob1n7");
        t.prejmi(new Tretja.Profesor(), "prof_DaUuM");
        t.prejmi(new Tretja.Profesor(), "prof_DFF6D");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_46xRc");
        t.prejmi(new Tretja.Profesor(), "prof_CQKQe");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_V6L1C");
        t.prejmi(new Tretja.Docent(), "doc_1PyGN");
        t.prejmi(new Tretja.Asistent(), "as_Ms0y2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_TVQkP");
        t.prejmi(new Tretja.Profesor(), "prof_ehdXQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_PmHfk");
        t.prejmi(new Tretja.Docent(), "doc_aR90L");
        t.prejmi(new Tretja.Docent(), "doc_aXKjG");
        t.prejmi(new Tretja.Profesor(), "prof_5mrl7");
        t.prejmi(new Tretja.Asistent(), "as_19Nww");
        t.prejmi(new Tretja.Profesor(), "prof_RYsQw");
        t.prejmi(new Tretja.Asistent(), "as_sgQYb");
        t.prejmi(new Tretja.Asistent(), "as_dwgrf");
        t.prejmi(new Tretja.Asistent(), "as_ZOI0z");
        t.prejmi(new Tretja.Profesor(), "prof_txbUh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_IKPHB");
        t.prejmi(new Tretja.Asistent(), "as_tALF0");
        t.prejmi(new Tretja.Profesor(), "prof_CacAG");
        t.prejmi(new Tretja.Profesor(), "prof_tLZqI");
        t.prejmi(new Tretja.Docent(), "doc_W0L92");
        t.prejmi(new Tretja.Docent(), "doc_M0Lzm");
        t.prejmi(new Tretja.Asistent(), "as_i80y5");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_dve6h");
        t.prejmi(new Tretja.Profesor(), "prof_rismO");
        t.prejmi(new Tretja.Docent(), "doc_c7567");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_2Uudd");
        t.prejmi(new Tretja.Asistent(), "as_NrlSm");
        t.prejmi(new Tretja.Asistent(), "as_BSvEi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_4pUYL");
        t.prejmi(new Tretja.Asistent(), "as_LextN");
        t.prejmi(new Tretja.Docent(), "doc_0XTPo");
        t.prejmi(new Tretja.Asistent(), "as_1UyFM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_lCDAZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_2ZP9K");
        t.prejmi(new Tretja.Profesor(), "prof_Kngxk");
        t.prejmi(new Tretja.Profesor(), "prof_roLal");
        t.prejmi(new Tretja.Profesor(), "prof_fVW3W");
        t.prejmi(new Tretja.Docent(), "doc_0u7sV");
        t.prejmi(new Tretja.Asistent(), "as_vV9td");
        t.prejmi(new Tretja.Asistent(), "as_6ecVv");
        t.prejmi(new Tretja.Docent(), "doc_dhfgb");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_iwHc5");
        t.prejmi(new Tretja.Profesor(), "prof_8bPCT");
        t.prejmi(new Tretja.Profesor(), "prof_5r09g");
        t.prejmi(new Tretja.Profesor(), "prof_zG5qY");
        t.prejmi(new Tretja.Docent(), "doc_DRT8q");
        t.prejmi(new Tretja.Docent(), "doc_1c4vs");
        t.prejmi(new Tretja.Docent(), "doc_pQsfL");
        t.prejmi(new Tretja.Profesor(), "prof_HUQAL");
        t.prejmi(new Tretja.Asistent(), "as_948Ha");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_27fkQ");
        t.prejmi(new Tretja.Docent(), "doc_ZQfVm");
        t.prejmi(new Tretja.Profesor(), "prof_xUvZ0");
        t.prejmi(new Tretja.Profesor(), "prof_W0wJB");
        t.prejmi(new Tretja.Asistent(), "as_0fi2t");
        t.prejmi(new Tretja.Asistent(), "as_4ur1L");
        t.prejmi(new Tretja.Docent(), "doc_6qXtg");
        t.prejmi(new Tretja.Profesor(), "prof_WANfH");
        t.prejmi(new Tretja.Profesor(), "prof_57dhH");
        t.prejmi(new Tretja.Asistent(), "as_mo8gB");
        t.prejmi(new Tretja.Asistent(), "as_zbYJo");
        t.prejmi(new Tretja.Profesor(), "prof_GxCLP");
        t.prejmi(new Tretja.Docent(), "doc_twDzz");
        t.prejmi(new Tretja.Docent(), "doc_LwxVd");
        t.prejmi(new Tretja.Asistent(), "as_jgEBS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_IzRrB");
        t.prejmi(new Tretja.Docent(), "doc_qAUVO");
        t.prejmi(new Tretja.Profesor(), "prof_yDRDb");
        t.prejmi(new Tretja.Asistent(), "as_iXmnJ");
        t.prejmi(new Tretja.Profesor(), "prof_BgBln");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_jtQcZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_bv7OK");
        t.prejmi(new Tretja.Profesor(), "prof_1ov3L");
        t.prejmi(new Tretja.Profesor(), "prof_QjLR3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_ey4YV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_D19KR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_tVUiO");
        t.prejmi(new Tretja.Asistent(), "as_Ztc28");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JqF3z");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_q6sTG");
        t.prejmi(new Tretja.Asistent(), "as_CAdE8");
        t.prejmi(new Tretja.Profesor(), "prof_2gw5F");
        t.prejmi(new Tretja.Docent(), "doc_pepEV");
        t.prejmi(new Tretja.Docent(), "doc_Tpq9f");
        t.prejmi(new Tretja.Asistent(), "as_2zUnH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_rQ93N");
        t.prejmi(new Tretja.Docent(), "doc_eFNgn");
        t.prejmi(new Tretja.Asistent(), "as_1N2Dy");
        t.prejmi(new Tretja.Docent(), "doc_oTn7T");
        t.prejmi(new Tretja.Docent(), "doc_MmYiJ");
        t.prejmi(new Tretja.Asistent(), "as_vzrta");
        t.prejmi(new Tretja.Docent(), "doc_AlGRw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_d8sDq");
        t.prejmi(new Tretja.Docent(), "doc_HfkPf");
        t.prejmi(new Tretja.Profesor(), "prof_aoUAZ");
        t.prejmi(new Tretja.Profesor(), "prof_ZaF9a");
        t.prejmi(new Tretja.Docent(), "doc_Y1VQg");
        t.prejmi(new Tretja.Profesor(), "prof_DDFPr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_bQ8vc");
        t.prejmi(new Tretja.Profesor(), "prof_b7L6M");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_63la5");
        t.prejmi(new Tretja.Profesor(), "prof_NzdXU");
        t.prejmi(new Tretja.Profesor(), "prof_AvwHA");
        t.prejmi(new Tretja.Docent(), "doc_5jnaA");
        t.prejmi(new Tretja.Asistent(), "as_9zcOn");
        t.prejmi(new Tretja.Profesor(), "prof_HgpFO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_xAzrJ");
        t.prejmi(new Tretja.Docent(), "doc_ZvEFQ");
        t.prejmi(new Tretja.Docent(), "doc_wKwlY");
        t.prejmi(new Tretja.Profesor(), "prof_4DQsw");
        t.prejmi(new Tretja.Asistent(), "as_gjco1");
        t.prejmi(new Tretja.Asistent(), "as_VCpYZ");
        t.prejmi(new Tretja.Asistent(), "as_W2XvR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Pkr0h");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1XlSI");
        t.prejmi(new Tretja.Asistent(), "as_dEMf8");
        t.prejmi(new Tretja.Docent(), "doc_zZ0NA");
        t.prejmi(new Tretja.Asistent(), "as_8PTJP");
        t.prejmi(new Tretja.Profesor(), "prof_kXQs3");
        t.prejmi(new Tretja.Asistent(), "as_bTf2g");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_lrPtt");
        t.prejmi(new Tretja.Profesor(), "prof_IbCPm");
        t.prejmi(new Tretja.Profesor(), "prof_EmHTd");
        t.prejmi(new Tretja.Profesor(), "prof_5sbCr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_DzApq");
        t.prejmi(new Tretja.Asistent(), "as_Il51V");
        t.prejmi(new Tretja.Docent(), "doc_Wt1wK");
        t.prejmi(new Tretja.Docent(), "doc_jaO9Y");
        t.prejmi(new Tretja.Asistent(), "as_ncgMI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Boh3w");
        t.prejmi(new Tretja.Docent(), "doc_tPQqh");
        t.prejmi(new Tretja.Docent(), "doc_miW9e");
        t.prejmi(new Tretja.Asistent(), "as_2Flt5");
        t.prejmi(new Tretja.Asistent(), "as_wrJ4O");
        t.prejmi(new Tretja.Profesor(), "prof_iFeQA");
        t.prejmi(new Tretja.Docent(), "doc_W7Crq");
        t.prejmi(new Tretja.Profesor(), "prof_GfwXD");
        t.prejmi(new Tretja.Docent(), "doc_Z0uHa");
        t.prejmi(new Tretja.Asistent(), "as_RqyEx");
        t.prejmi(new Tretja.Asistent(), "as_AHgE0");
        t.prejmi(new Tretja.Asistent(), "as_5zydQ");
        t.prejmi(new Tretja.Asistent(), "as_sLHzw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_hHopW");
        t.prejmi(new Tretja.Profesor(), "prof_iRw3D");
        t.prejmi(new Tretja.Asistent(), "as_LCDii");
        t.prejmi(new Tretja.Profesor(), "prof_pgWAp");
        t.prejmi(new Tretja.Asistent(), "as_XUbve");
        t.prejmi(new Tretja.Asistent(), "as_VnVO7");
        t.prejmi(new Tretja.Docent(), "doc_ICSm2");
        t.prejmi(new Tretja.Profesor(), "prof_yXUNu");
        t.prejmi(new Tretja.Profesor(), "prof_VkWI8");
        t.prejmi(new Tretja.Profesor(), "prof_M5uCt");
        t.prejmi(new Tretja.Profesor(), "prof_5cbys");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_12U6z");
        t.prejmi(new Tretja.Profesor(), "prof_TJRHF");
        t.prejmi(new Tretja.Docent(), "doc_8pnMb");
        t.prejmi(new Tretja.Profesor(), "prof_mbTOr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Svwu8");
        t.prejmi(new Tretja.Asistent(), "as_mQFLE");
        t.prejmi(new Tretja.Docent(), "doc_ECj0k");
        t.prejmi(new Tretja.Asistent(), "as_mLUgX");
        t.prejmi(new Tretja.Docent(), "doc_WMwJu");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_f963G");
        t.prejmi(new Tretja.Profesor(), "prof_MX5Bf");
        t.prejmi(new Tretja.Docent(), "doc_5LDGh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_rCgrI");
        t.prejmi(new Tretja.Docent(), "doc_ONtSz");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_G2FsL");
        t.prejmi(new Tretja.Profesor(), "prof_eamwF");
        t.prejmi(new Tretja.Profesor(), "prof_p9lF2");
    }
}
