
public class Test10 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_2poYu");
        t.prejmi(new Tretja.Profesor(), "prof_gqtUs");
        t.prejmi(new Tretja.Asistent(), "as_SDypi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MiVOR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_KX9rL");
        t.prejmi(new Tretja.Profesor(), "prof_KCthV");
        t.prejmi(new Tretja.Docent(), "doc_2vWUF");
        t.prejmi(new Tretja.Profesor(), "prof_tYxGP");
        t.prejmi(new Tretja.Asistent(), "as_BOcrC");
        t.prejmi(new Tretja.Asistent(), "as_MGHVj");
        t.prejmi(new Tretja.Asistent(), "as_d83nF");
        t.prejmi(new Tretja.Asistent(), "as_jBO7W");
        t.prejmi(new Tretja.Asistent(), "as_Mertc");
        t.prejmi(new Tretja.Docent(), "doc_iqxKi");
        t.prejmi(new Tretja.Profesor(), "prof_YwytZ");
        t.prejmi(new Tretja.Profesor(), "prof_aVSMh");
        t.prejmi(new Tretja.Profesor(), "prof_GQ77H");
        t.prejmi(new Tretja.Docent(), "doc_DGBfo");
        t.prejmi(new Tretja.Asistent(), "as_sS4fs");
        t.prejmi(new Tretja.Docent(), "doc_zeuPu");
        t.prejmi(new Tretja.Profesor(), "prof_84QcV");
        t.prejmi(new Tretja.Profesor(), "prof_l6G2A");
        t.prejmi(new Tretja.Profesor(), "prof_xJf6H");
        t.prejmi(new Tretja.Docent(), "doc_IanIb");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_KProE");
        t.prejmi(new Tretja.Asistent(), "as_eHokK");
        t.prejmi(new Tretja.Asistent(), "as_ffSnA");
        t.prejmi(new Tretja.Docent(), "doc_mzrND");
        t.prejmi(new Tretja.Profesor(), "prof_EyscQ");
        t.prejmi(new Tretja.Docent(), "doc_CRlcU");
        t.prejmi(new Tretja.Asistent(), "as_vr4ng");
        t.prejmi(new Tretja.Asistent(), "as_WZ3By");
        t.prejmi(new Tretja.Asistent(), "as_kg2oO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JIIF9");
        t.prejmi(new Tretja.Asistent(), "as_gio03");
        t.prejmi(new Tretja.Asistent(), "as_5lKmW");
        t.prejmi(new Tretja.Asistent(), "as_a9duf");
        t.prejmi(new Tretja.Docent(), "doc_Fsgjj");
        t.prejmi(new Tretja.Asistent(), "as_DAwqn");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_xHF5t");
        t.prejmi(new Tretja.Profesor(), "prof_ZsLj1");
        t.prejmi(new Tretja.Asistent(), "as_ulIDX");
        t.prejmi(new Tretja.Asistent(), "as_L3URx");
        t.prejmi(new Tretja.Docent(), "doc_yD0CN");
        t.prejmi(new Tretja.Profesor(), "prof_VFms2");
        t.prejmi(new Tretja.Asistent(), "as_Mhb6p");
        t.prejmi(new Tretja.Profesor(), "prof_ETduI");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_iye4U");
        t.prejmi(new Tretja.Docent(), "doc_LgEF7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Ec4qE");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TxTJC");
        t.prejmi(new Tretja.Asistent(), "as_gvh0C");
        t.prejmi(new Tretja.Docent(), "doc_OH8N7");
        t.prejmi(new Tretja.Docent(), "doc_aByaS");
        t.prejmi(new Tretja.Docent(), "doc_Mk1OV");
        t.prejmi(new Tretja.Asistent(), "as_Urkft");
        t.prejmi(new Tretja.Profesor(), "prof_vpgez");
        t.prejmi(new Tretja.Asistent(), "as_69ZjT");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_M82oc");
        t.prejmi(new Tretja.Docent(), "doc_MFKZn");
        t.prejmi(new Tretja.Docent(), "doc_lkm9X");
        t.prejmi(new Tretja.Docent(), "doc_ZWNFN");
        t.prejmi(new Tretja.Asistent(), "as_T5nED");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_e4qwR");
        t.prejmi(new Tretja.Docent(), "doc_p75zh");
        t.prejmi(new Tretja.Asistent(), "as_e8mf6");
        t.prejmi(new Tretja.Profesor(), "prof_hLSlT");
        t.prejmi(new Tretja.Profesor(), "prof_EeL4r");
        t.prejmi(new Tretja.Profesor(), "prof_TzcFQ");
        t.prejmi(new Tretja.Asistent(), "as_HXaWD");
        t.prejmi(new Tretja.Profesor(), "prof_PUlFM");
        t.prejmi(new Tretja.Asistent(), "as_USTkD");
        t.prejmi(new Tretja.Docent(), "doc_h5Td3");
        t.prejmi(new Tretja.Asistent(), "as_yNHEH");
        t.prejmi(new Tretja.Profesor(), "prof_3flMj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2spy1");
        t.prejmi(new Tretja.Docent(), "doc_KLvO4");
        t.prejmi(new Tretja.Asistent(), "as_VRIbx");
        t.prejmi(new Tretja.Docent(), "doc_KTxlP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_RR40k");
        t.prejmi(new Tretja.Profesor(), "prof_CdWIg");
        t.prejmi(new Tretja.Docent(), "doc_fFQLH");
        t.prejmi(new Tretja.Asistent(), "as_8eJEr");
        t.prejmi(new Tretja.Profesor(), "prof_AaTrT");
        t.prejmi(new Tretja.Docent(), "doc_AqBsP");
        t.prejmi(new Tretja.Asistent(), "as_qtA9u");
        t.prejmi(new Tretja.Profesor(), "prof_Nj4QT");
        t.prejmi(new Tretja.Docent(), "doc_p89ZG");
        t.prejmi(new Tretja.Docent(), "doc_3K7TG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9aPFp");
        t.prejmi(new Tretja.Profesor(), "prof_38KNJ");
        t.prejmi(new Tretja.Profesor(), "prof_MbQUp");
        t.prejmi(new Tretja.Asistent(), "as_uP7qS");
        t.prejmi(new Tretja.Profesor(), "prof_O1HFV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SQip8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_bDR1J");
        t.prejmi(new Tretja.Asistent(), "as_eXYOB");
        t.prejmi(new Tretja.Asistent(), "as_7vKlf");
        t.prejmi(new Tretja.Docent(), "doc_XbQwY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ar1Am");
        t.prejmi(new Tretja.Asistent(), "as_oeDGA");
        t.prejmi(new Tretja.Asistent(), "as_QHg25");
        t.prejmi(new Tretja.Profesor(), "prof_aKA9x");
        t.prejmi(new Tretja.Asistent(), "as_UzUJ7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_H4PgV");
        t.prejmi(new Tretja.Docent(), "doc_mpiVK");
        t.prejmi(new Tretja.Docent(), "doc_eXFNX");
        t.prejmi(new Tretja.Profesor(), "prof_0LJgA");
        t.prejmi(new Tretja.Profesor(), "prof_kaWFL");
        t.prejmi(new Tretja.Profesor(), "prof_8Id6k");
        t.prejmi(new Tretja.Profesor(), "prof_YdddI");
        t.prejmi(new Tretja.Asistent(), "as_k4ijH");
        t.prejmi(new Tretja.Profesor(), "prof_EwQt7");
        t.prejmi(new Tretja.Docent(), "doc_W1qeP");
        t.prejmi(new Tretja.Docent(), "doc_dV7r3");
        t.prejmi(new Tretja.Profesor(), "prof_XnOVp");
        t.prejmi(new Tretja.Asistent(), "as_kVwLr");
        t.prejmi(new Tretja.Profesor(), "prof_pfwGu");
        t.prejmi(new Tretja.Asistent(), "as_YXP6p");
        t.prejmi(new Tretja.Asistent(), "as_WPkqH");
        t.prejmi(new Tretja.Profesor(), "prof_slTpS");
        t.prejmi(new Tretja.Profesor(), "prof_tKnpT");
        t.prejmi(new Tretja.Asistent(), "as_AYpGL");
        t.prejmi(new Tretja.Docent(), "doc_GAScY");
        t.prejmi(new Tretja.Asistent(), "as_T58fW");
        t.prejmi(new Tretja.Docent(), "doc_ZY8UV");
        t.prejmi(new Tretja.Profesor(), "prof_DYLyl");
        t.prejmi(new Tretja.Asistent(), "as_ul3YH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_yl9Ov");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_yeqaI");
        t.prejmi(new Tretja.Profesor(), "prof_Hj8ol");
        t.prejmi(new Tretja.Profesor(), "prof_cHA5F");
        t.prejmi(new Tretja.Docent(), "doc_LHoik");
        t.prejmi(new Tretja.Docent(), "doc_xdbJL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Qi4GT");
        t.prejmi(new Tretja.Docent(), "doc_YrfIy");
        t.prejmi(new Tretja.Asistent(), "as_KB5JT");
        t.prejmi(new Tretja.Profesor(), "prof_yeQ3l");
        t.prejmi(new Tretja.Asistent(), "as_h9KA9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_WQJ5R");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_7Sl9U");
        t.prejmi(new Tretja.Docent(), "doc_tJBdQ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bMadd");
        t.prejmi(new Tretja.Profesor(), "prof_3dWAd");
        t.prejmi(new Tretja.Docent(), "doc_CwmO2");
        t.prejmi(new Tretja.Profesor(), "prof_ggACb");
        t.prejmi(new Tretja.Profesor(), "prof_PuIXJ");
        t.prejmi(new Tretja.Asistent(), "as_uOoVd");
        t.prejmi(new Tretja.Docent(), "doc_osFO8");
        t.prejmi(new Tretja.Profesor(), "prof_3cndr");
        t.prejmi(new Tretja.Profesor(), "prof_jMiSl");
        t.prejmi(new Tretja.Docent(), "doc_WPNoL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5TZYo");
        t.prejmi(new Tretja.Docent(), "doc_YPp4X");
        t.prejmi(new Tretja.Asistent(), "as_ZRjtN");
        t.prejmi(new Tretja.Asistent(), "as_yhhEg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_DOWK8");
        t.prejmi(new Tretja.Docent(), "doc_UpCNW");
        t.prejmi(new Tretja.Profesor(), "prof_82I6n");
        t.prejmi(new Tretja.Profesor(), "prof_nMJtE");
        t.prejmi(new Tretja.Docent(), "doc_mebqy");
        t.prejmi(new Tretja.Profesor(), "prof_dr50O");
        t.prejmi(new Tretja.Docent(), "doc_icJOG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ndqUl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bajnR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rNbyF");
        t.prejmi(new Tretja.Asistent(), "as_wughN");
        t.prejmi(new Tretja.Profesor(), "prof_JDfYZ");
        t.prejmi(new Tretja.Docent(), "doc_ncKGs");
        t.prejmi(new Tretja.Profesor(), "prof_ARg49");
        t.prejmi(new Tretja.Profesor(), "prof_duE99");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_I8dx8");
        t.prejmi(new Tretja.Profesor(), "prof_3MD49");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Ac5gU");
        t.prejmi(new Tretja.Asistent(), "as_iaSvt");
        t.prejmi(new Tretja.Profesor(), "prof_P4zUY");
        t.prejmi(new Tretja.Profesor(), "prof_E7a3b");
        t.prejmi(new Tretja.Docent(), "doc_7UH39");
        t.prejmi(new Tretja.Profesor(), "prof_aTJ9L");
        t.prejmi(new Tretja.Asistent(), "as_0waHw");
        t.prejmi(new Tretja.Docent(), "doc_r7y0l");
        t.prejmi(new Tretja.Docent(), "doc_MvANG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GzOsz");
        t.prejmi(new Tretja.Asistent(), "as_nhqFl");
        t.prejmi(new Tretja.Docent(), "doc_lLDzP");
        t.prejmi(new Tretja.Docent(), "doc_KSfFx");
        t.prejmi(new Tretja.Docent(), "doc_qr3io");
        t.prejmi(new Tretja.Docent(), "doc_6l80x");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SJqIN");
        t.prejmi(new Tretja.Docent(), "doc_LgEQE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7ZKvk");
        t.prejmi(new Tretja.Asistent(), "as_RkWZr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9frn4");
        t.prejmi(new Tretja.Profesor(), "prof_kh0Fa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_vWe5N");
        t.prejmi(new Tretja.Profesor(), "prof_20F7W");
        t.prejmi(new Tretja.Docent(), "doc_y4z75");
        t.prejmi(new Tretja.Profesor(), "prof_bHsGw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_lUtcB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Myyj1");
        t.prejmi(new Tretja.Docent(), "doc_LKgRZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5pBI6");
        t.prejmi(new Tretja.Profesor(), "prof_4BlSb");
        t.prejmi(new Tretja.Docent(), "doc_IzEOL");
        t.prejmi(new Tretja.Asistent(), "as_yQHhc");
        t.prejmi(new Tretja.Profesor(), "prof_Ak5rv");
        t.prejmi(new Tretja.Docent(), "doc_5XTmN");
        t.prejmi(new Tretja.Asistent(), "as_Fsyud");
        t.prejmi(new Tretja.Asistent(), "as_TgkNj");
        t.prejmi(new Tretja.Profesor(), "prof_dyvi0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vPMUa");
        t.prejmi(new Tretja.Docent(), "doc_obcK3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1mOp5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6BN23");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_emkQd");
        t.prejmi(new Tretja.Asistent(), "as_qGgdW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_miU28");
        t.prejmi(new Tretja.Profesor(), "prof_P0QYq");
        t.prejmi(new Tretja.Asistent(), "as_cQidH");
        t.prejmi(new Tretja.Docent(), "doc_7Gjx2");
        t.prejmi(new Tretja.Profesor(), "prof_QOwKC");
        t.prejmi(new Tretja.Profesor(), "prof_IJvib");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_WHWFf");
        t.prejmi(new Tretja.Profesor(), "prof_ZnX9j");
        t.prejmi(new Tretja.Docent(), "doc_uEoXC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MwwTO");
        t.prejmi(new Tretja.Asistent(), "as_rFjzI");
        t.prejmi(new Tretja.Docent(), "doc_XmlQz");
        t.prejmi(new Tretja.Profesor(), "prof_erivM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_UF50k");
        t.prejmi(new Tretja.Profesor(), "prof_lYEoX");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vb04M");
        t.prejmi(new Tretja.Asistent(), "as_1ja3u");
        t.prejmi(new Tretja.Profesor(), "prof_E7Zn2");
        t.prejmi(new Tretja.Docent(), "doc_we1Ih");
        t.prejmi(new Tretja.Docent(), "doc_Lojhd");
        t.prejmi(new Tretja.Docent(), "doc_L14vy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_BiEMa");
        t.prejmi(new Tretja.Profesor(), "prof_emdYy");
        t.prejmi(new Tretja.Profesor(), "prof_v5ZeC");
        t.prejmi(new Tretja.Asistent(), "as_VKUtQ");
        t.prejmi(new Tretja.Asistent(), "as_7OYek");
        t.prejmi(new Tretja.Asistent(), "as_T1lmp");
        t.prejmi(new Tretja.Docent(), "doc_d3xiU");
        t.prejmi(new Tretja.Asistent(), "as_SUXx3");
        t.prejmi(new Tretja.Docent(), "doc_8sMRq");
        t.prejmi(new Tretja.Docent(), "doc_DThah");
        t.prejmi(new Tretja.Profesor(), "prof_H5YbY");
        t.prejmi(new Tretja.Asistent(), "as_QbW4f");
        t.prejmi(new Tretja.Docent(), "doc_77hfK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_DeFxX");
        t.prejmi(new Tretja.Profesor(), "prof_x88OR");
        t.prejmi(new Tretja.Profesor(), "prof_d76us");
        t.prejmi(new Tretja.Asistent(), "as_HtAAx");
        t.prejmi(new Tretja.Docent(), "doc_JWpWM");
        t.prejmi(new Tretja.Asistent(), "as_hu4gd");
        t.prejmi(new Tretja.Asistent(), "as_RapO2");
        t.prejmi(new Tretja.Profesor(), "prof_l60AI");
        t.prejmi(new Tretja.Docent(), "doc_yok5C");
        t.prejmi(new Tretja.Profesor(), "prof_F94u4");
        t.prejmi(new Tretja.Profesor(), "prof_oLNtA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QR4aE");
        t.prejmi(new Tretja.Profesor(), "prof_rKzOK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ey4js");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_XW5dm");
        t.prejmi(new Tretja.Asistent(), "as_qh3o5");
        t.prejmi(new Tretja.Asistent(), "as_I28LI");
        t.prejmi(new Tretja.Profesor(), "prof_dHaDE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_FflaD");
        t.prejmi(new Tretja.Profesor(), "prof_RQsSp");
        t.prejmi(new Tretja.Docent(), "doc_wj442");
        t.prejmi(new Tretja.Asistent(), "as_BjyAd");
        t.prejmi(new Tretja.Docent(), "doc_mjdSi");
        t.prejmi(new Tretja.Docent(), "doc_Ozm4T");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TO7dT");
        t.prejmi(new Tretja.Docent(), "doc_dcoOi");
        t.prejmi(new Tretja.Docent(), "doc_pv143");
        t.prejmi(new Tretja.Asistent(), "as_cLO86");
        t.prejmi(new Tretja.Docent(), "doc_PjTx2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_farAx");
        t.prejmi(new Tretja.Profesor(), "prof_zOY6h");
        t.prejmi(new Tretja.Asistent(), "as_NEC6T");
        t.prejmi(new Tretja.Asistent(), "as_yoxIc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0xuYz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xAkkv");
        t.prejmi(new Tretja.Profesor(), "prof_TgpBA");
        t.prejmi(new Tretja.Asistent(), "as_XEEc3");
        t.prejmi(new Tretja.Asistent(), "as_MWlN4");
        t.prejmi(new Tretja.Profesor(), "prof_LZXzy");
        t.prejmi(new Tretja.Docent(), "doc_871RO");
        t.prejmi(new Tretja.Docent(), "doc_wOlnK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_p7aOA");
        t.prejmi(new Tretja.Asistent(), "as_zVSJE");
        t.prejmi(new Tretja.Asistent(), "as_IXiUl");
        t.prejmi(new Tretja.Docent(), "doc_6buG5");
        t.prejmi(new Tretja.Profesor(), "prof_UVH0e");
        t.prejmi(new Tretja.Profesor(), "prof_MhZxH");
        t.prejmi(new Tretja.Asistent(), "as_omqtp");
        t.prejmi(new Tretja.Profesor(), "prof_AliiA");
        t.prejmi(new Tretja.Asistent(), "as_8LEtI");
        t.prejmi(new Tretja.Asistent(), "as_mXzC3");
        t.prejmi(new Tretja.Docent(), "doc_Na2Vj");
        t.prejmi(new Tretja.Asistent(), "as_uBIRQ");
        t.prejmi(new Tretja.Profesor(), "prof_EymUP");
        t.prejmi(new Tretja.Profesor(), "prof_AtYzh");
        t.prejmi(new Tretja.Profesor(), "prof_x83ua");
        t.prejmi(new Tretja.Asistent(), "as_yvizj");
        t.prejmi(new Tretja.Asistent(), "as_df5ps");
        t.prejmi(new Tretja.Asistent(), "as_jaRhP");
        t.prejmi(new Tretja.Asistent(), "as_wU3w4");
        t.prejmi(new Tretja.Asistent(), "as_xDMYN");
        t.prejmi(new Tretja.Profesor(), "prof_MKobM");
        t.prejmi(new Tretja.Asistent(), "as_8UPTF");
        t.prejmi(new Tretja.Asistent(), "as_9K5sH");
        t.prejmi(new Tretja.Docent(), "doc_nouP3");
        t.prejmi(new Tretja.Profesor(), "prof_WZs2S");
        t.prejmi(new Tretja.Profesor(), "prof_DxRrn");
        t.prejmi(new Tretja.Docent(), "doc_ahIHh");
        t.prejmi(new Tretja.Asistent(), "as_zUlo4");
        t.prejmi(new Tretja.Docent(), "doc_XBG6H");
        t.prejmi(new Tretja.Profesor(), "prof_uYY4Q");
        t.prejmi(new Tretja.Profesor(), "prof_MKae9");
        t.prejmi(new Tretja.Profesor(), "prof_oNRW6");
        t.prejmi(new Tretja.Asistent(), "as_Ro8hS");
        t.prejmi(new Tretja.Profesor(), "prof_c4gne");
        t.prejmi(new Tretja.Docent(), "doc_ySyU3");
        t.prejmi(new Tretja.Profesor(), "prof_dXcts");
        t.prejmi(new Tretja.Docent(), "doc_IhrSc");
        t.prejmi(new Tretja.Profesor(), "prof_sUZhZ");
        t.prejmi(new Tretja.Profesor(), "prof_yYG64");
        t.prejmi(new Tretja.Asistent(), "as_F5RAh");
        t.prejmi(new Tretja.Docent(), "doc_qqezB");
        t.prejmi(new Tretja.Profesor(), "prof_10lBP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rcXHZ");
        t.prejmi(new Tretja.Profesor(), "prof_C5rlu");
        t.prejmi(new Tretja.Docent(), "doc_7dKgS");
        t.prejmi(new Tretja.Asistent(), "as_diMTG");
        t.prejmi(new Tretja.Profesor(), "prof_8dBv6");
        t.prejmi(new Tretja.Docent(), "doc_uMGPR");
        t.prejmi(new Tretja.Asistent(), "as_hUPnl");
        t.prejmi(new Tretja.Profesor(), "prof_JkIBI");
        t.prejmi(new Tretja.Asistent(), "as_xeS1H");
        t.prejmi(new Tretja.Docent(), "doc_GyHM9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_tMCPd");
        t.prejmi(new Tretja.Asistent(), "as_D07p7");
        t.prejmi(new Tretja.Docent(), "doc_qk4wC");
        t.prejmi(new Tretja.Asistent(), "as_LsaQZ");
        t.prejmi(new Tretja.Asistent(), "as_Ww3a9");
        t.prejmi(new Tretja.Docent(), "doc_HpwWR");
        t.prejmi(new Tretja.Profesor(), "prof_ygLSu");
        t.prejmi(new Tretja.Asistent(), "as_QAcNW");
        t.prejmi(new Tretja.Docent(), "doc_Ymm7n");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_qJSVM");
        t.prejmi(new Tretja.Docent(), "doc_vj0NB");
        t.prejmi(new Tretja.Profesor(), "prof_xcj2Z");
        t.prejmi(new Tretja.Profesor(), "prof_WNnrj");
        t.prejmi(new Tretja.Docent(), "doc_igIkJ");
        t.prejmi(new Tretja.Asistent(), "as_SzY8Y");
        t.prejmi(new Tretja.Docent(), "doc_RmAlx");
        t.prejmi(new Tretja.Docent(), "doc_lhX85");
        t.prejmi(new Tretja.Asistent(), "as_HKX6m");
        t.prejmi(new Tretja.Asistent(), "as_3eaik");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_nvVKx");
        t.prejmi(new Tretja.Profesor(), "prof_ZoHF2");
        t.prejmi(new Tretja.Asistent(), "as_Vf7is");
        t.prejmi(new Tretja.Asistent(), "as_CbA1l");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_SP3rs");
        t.prejmi(new Tretja.Profesor(), "prof_3fPgZ");
        t.prejmi(new Tretja.Docent(), "doc_XlI7N");
        t.prejmi(new Tretja.Docent(), "doc_bakNc");
        t.prejmi(new Tretja.Profesor(), "prof_6LlAj");
        t.prejmi(new Tretja.Asistent(), "as_XFn23");
        t.prejmi(new Tretja.Asistent(), "as_6o4Ik");
        t.prejmi(new Tretja.Profesor(), "prof_EsgjB");
        t.prejmi(new Tretja.Asistent(), "as_oZ8XX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4seaU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_k0kwI");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_byVYH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_fiFm5");
        t.prejmi(new Tretja.Asistent(), "as_HbY9Y");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2WFhS");
        t.prejmi(new Tretja.Asistent(), "as_7I4Bb");
        t.prejmi(new Tretja.Docent(), "doc_COsZC");
        t.prejmi(new Tretja.Asistent(), "as_XSAWR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HPPVw");
        t.prejmi(new Tretja.Docent(), "doc_wXiyT");
        t.prejmi(new Tretja.Asistent(), "as_LanPA");
        t.prejmi(new Tretja.Asistent(), "as_2LxYA");
        t.prejmi(new Tretja.Docent(), "doc_PZIT1");
        t.prejmi(new Tretja.Profesor(), "prof_pgFlj");
        t.prejmi(new Tretja.Docent(), "doc_6DB6s");
        t.prejmi(new Tretja.Docent(), "doc_2oubm");
        t.prejmi(new Tretja.Profesor(), "prof_CscuR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_CTEYJ");
        t.prejmi(new Tretja.Asistent(), "as_LqUZ8");
        t.prejmi(new Tretja.Docent(), "doc_nTtH4");
        t.prejmi(new Tretja.Profesor(), "prof_OUCFU");
        t.prejmi(new Tretja.Asistent(), "as_P5cmx");
        t.prejmi(new Tretja.Asistent(), "as_5SsHO");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QB6Vx");
        t.prejmi(new Tretja.Docent(), "doc_8XD96");
        t.prejmi(new Tretja.Docent(), "doc_FrPAx");
        t.prejmi(new Tretja.Asistent(), "as_E9GgT");
        t.prejmi(new Tretja.Docent(), "doc_2BG1d");
        t.prejmi(new Tretja.Asistent(), "as_BYyy4");
        t.prejmi(new Tretja.Asistent(), "as_rD2YG");
        t.prejmi(new Tretja.Asistent(), "as_6Pl02");
        t.prejmi(new Tretja.Docent(), "doc_Ywh0C");
        t.prejmi(new Tretja.Profesor(), "prof_tIVxA");
        t.prejmi(new Tretja.Profesor(), "prof_p5gAW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_M54IM");
        t.prejmi(new Tretja.Profesor(), "prof_qmUMb");
        t.prejmi(new Tretja.Asistent(), "as_IpRci");
        t.prejmi(new Tretja.Asistent(), "as_3xMrL");
        t.prejmi(new Tretja.Profesor(), "prof_HjZMC");
        t.prejmi(new Tretja.Profesor(), "prof_OSsvI");
        t.prejmi(new Tretja.Profesor(), "prof_djKvl");
        t.prejmi(new Tretja.Asistent(), "as_wOKSx");
        t.prejmi(new Tretja.Profesor(), "prof_44Hgu");
        t.prejmi(new Tretja.Docent(), "doc_9D4zy");
        t.prejmi(new Tretja.Profesor(), "prof_RnhE7");
        t.prejmi(new Tretja.Asistent(), "as_z1b7X");
        t.prejmi(new Tretja.Profesor(), "prof_8ruXJ");
        t.prejmi(new Tretja.Docent(), "doc_gJ918");
        t.prejmi(new Tretja.Asistent(), "as_aD93k");
        t.prejmi(new Tretja.Profesor(), "prof_6TPaT");
        t.prejmi(new Tretja.Asistent(), "as_k5GyV");
        t.prejmi(new Tretja.Profesor(), "prof_XqQYE");
        t.prejmi(new Tretja.Docent(), "doc_TQXYA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_aN6T8");
        t.prejmi(new Tretja.Docent(), "doc_KyOx0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_AHBFS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uEksS");
        t.prejmi(new Tretja.Profesor(), "prof_leDaz");
        t.prejmi(new Tretja.Docent(), "doc_XAWud");
        t.prejmi(new Tretja.Asistent(), "as_tl9Ve");
        t.prejmi(new Tretja.Docent(), "doc_9frJh");
        t.prejmi(new Tretja.Asistent(), "as_56Dn6");
        t.prejmi(new Tretja.Profesor(), "prof_8pTjd");
        t.prejmi(new Tretja.Asistent(), "as_xdRsM");
        t.prejmi(new Tretja.Docent(), "doc_8GkdZ");
        t.prejmi(new Tretja.Asistent(), "as_BvmTZ");
        t.prejmi(new Tretja.Asistent(), "as_BRsUP");
        t.prejmi(new Tretja.Docent(), "doc_MqwhV");
        t.prejmi(new Tretja.Profesor(), "prof_mqppr");
        t.prejmi(new Tretja.Profesor(), "prof_imTLy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7Ix4W");
        t.prejmi(new Tretja.Docent(), "doc_bTm1C");
        t.prejmi(new Tretja.Profesor(), "prof_HcnOu");
        t.prejmi(new Tretja.Docent(), "doc_RzeB4");
        t.prejmi(new Tretja.Asistent(), "as_Fa8lX");
        t.prejmi(new Tretja.Docent(), "doc_ITvxD");
        t.prejmi(new Tretja.Docent(), "doc_ND161");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ucAB9");
        t.prejmi(new Tretja.Asistent(), "as_F9Ow8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VKA2w");
        t.prejmi(new Tretja.Asistent(), "as_HoBob");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xTzSU");
        t.prejmi(new Tretja.Docent(), "doc_gs4gD");
        t.prejmi(new Tretja.Docent(), "doc_N8KIs");
        t.prejmi(new Tretja.Docent(), "doc_hBx9p");
        t.prejmi(new Tretja.Profesor(), "prof_B2Kbg");
        t.prejmi(new Tretja.Asistent(), "as_S4Ams");
        t.prejmi(new Tretja.Asistent(), "as_YQ6sk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Btib5");
        t.prejmi(new Tretja.Profesor(), "prof_elYOW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hZMXe");
        t.prejmi(new Tretja.Docent(), "doc_8TIwi");
        t.prejmi(new Tretja.Profesor(), "prof_fhTlI");
        t.prejmi(new Tretja.Profesor(), "prof_pTNol");
        t.prejmi(new Tretja.Profesor(), "prof_CQqiO");
        t.prejmi(new Tretja.Docent(), "doc_Fy0FN");
        t.prejmi(new Tretja.Docent(), "doc_MZg7L");
        t.prejmi(new Tretja.Asistent(), "as_a7UJq");
        t.prejmi(new Tretja.Docent(), "doc_BaxM2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_761NC");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_tZWAp");
        t.prejmi(new Tretja.Docent(), "doc_HCs91");
        t.prejmi(new Tretja.Docent(), "doc_KbSXw");
        t.prejmi(new Tretja.Profesor(), "prof_oe7nT");
        t.prejmi(new Tretja.Asistent(), "as_mEfJX");
        t.prejmi(new Tretja.Asistent(), "as_YwpVR");
        t.prejmi(new Tretja.Profesor(), "prof_L1w5c");
        t.prejmi(new Tretja.Docent(), "doc_L7tK0");
        t.prejmi(new Tretja.Profesor(), "prof_D8Jwd");
        t.prejmi(new Tretja.Profesor(), "prof_lN7dt");
        t.prejmi(new Tretja.Docent(), "doc_lFDvi");
        t.prejmi(new Tretja.Asistent(), "as_MVvhz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Dwpnr");
        t.prejmi(new Tretja.Docent(), "doc_pBkdf");
        t.prejmi(new Tretja.Asistent(), "as_yWGC9");
        t.prejmi(new Tretja.Profesor(), "prof_3691i");
    }
}
