
public class Test03 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_EnmpJ");
        t.prejmi(new Tretja.Asistent(), "as_cQDuF");
        t.prejmi(new Tretja.Asistent(), "as_6CnC9");
        t.prejmi(new Tretja.Asistent(), "as_mFnIL");
        t.prejmi(new Tretja.Profesor(), "prof_7XbHE");
        t.prejmi(new Tretja.Profesor(), "prof_egEf7");
        t.prejmi(new Tretja.Docent(), "doc_N9ZnZ");
        t.prejmi(new Tretja.Docent(), "doc_HoZfF");
        t.prejmi(new Tretja.Docent(), "doc_ow25c");
        t.prejmi(new Tretja.Docent(), "doc_mkGQl");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_o7jR3");
        t.prejmi(new Tretja.Profesor(), "prof_vZSi6");
        t.prejmi(new Tretja.Docent(), "doc_8CXE3");
        t.prejmi(new Tretja.Profesor(), "prof_juLTN");
        t.prejmi(new Tretja.Asistent(), "as_PuS60");
        t.prejmi(new Tretja.Profesor(), "prof_G2SHp");
        t.prejmi(new Tretja.Profesor(), "prof_HyUZ7");
        t.prejmi(new Tretja.Profesor(), "prof_qNT37");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_JkH0b");
        t.prejmi(new Tretja.Profesor(), "prof_pV53Y");
        t.prejmi(new Tretja.Asistent(), "as_K3HpH");
        t.prejmi(new Tretja.Asistent(), "as_KslHs");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_C0KvM");
        t.prejmi(new Tretja.Docent(), "doc_VVKPL");
        t.prejmi(new Tretja.Profesor(), "prof_l5DN5");
        t.prejmi(new Tretja.Asistent(), "as_Ri2Ka");
        t.prejmi(new Tretja.Docent(), "doc_E6XlW");
        t.prejmi(new Tretja.Profesor(), "prof_n1Dkj");
        t.prejmi(new Tretja.Asistent(), "as_nnP5h");
        t.prejmi(new Tretja.Profesor(), "prof_3yDm0");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JQgHS");
        t.prejmi(new Tretja.Docent(), "doc_WCgHu");
        t.prejmi(new Tretja.Asistent(), "as_CQLr3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_T9MFw");
        t.prejmi(new Tretja.Profesor(), "prof_FNpFN");
        t.prejmi(new Tretja.Profesor(), "prof_rrsrp");
        t.prejmi(new Tretja.Docent(), "doc_91Eiz");
        t.prejmi(new Tretja.Docent(), "doc_nQcce");
        t.prejmi(new Tretja.Profesor(), "prof_fxYBk");
        t.prejmi(new Tretja.Profesor(), "prof_2k6a5");
        t.prejmi(new Tretja.Asistent(), "as_bYKV6");
        t.prejmi(new Tretja.Asistent(), "as_mUrnu");
        t.prejmi(new Tretja.Docent(), "doc_5De4p");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_60Dpy");
        t.prejmi(new Tretja.Profesor(), "prof_Cqx7M");
        t.prejmi(new Tretja.Asistent(), "as_4yJzG");
        t.prejmi(new Tretja.Asistent(), "as_Mzs07");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_RheOW");
        t.prejmi(new Tretja.Docent(), "doc_duo2K");
        t.prejmi(new Tretja.Profesor(), "prof_7LQ8d");
        t.prejmi(new Tretja.Asistent(), "as_KJ1yl");
        t.prejmi(new Tretja.Profesor(), "prof_1oG26");
        t.prejmi(new Tretja.Asistent(), "as_GB6Qn");
        t.prejmi(new Tretja.Asistent(), "as_uI4OH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_R9LAD");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_yT0vd");
        t.prejmi(new Tretja.Asistent(), "as_0bBQh");
        t.prejmi(new Tretja.Docent(), "doc_PlIQF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_06Zm7");
        t.prejmi(new Tretja.Docent(), "doc_ub4d2");
        t.prejmi(new Tretja.Profesor(), "prof_QNy76");
        t.prejmi(new Tretja.Asistent(), "as_401yy");
        t.prejmi(new Tretja.Asistent(), "as_cqaje");
        t.prejmi(new Tretja.Profesor(), "prof_iHpl6");
        t.prejmi(new Tretja.Profesor(), "prof_WXUAP");
        t.prejmi(new Tretja.Profesor(), "prof_spmx6");
        t.prejmi(new Tretja.Docent(), "doc_InR3S");
        t.prejmi(new Tretja.Profesor(), "prof_HtOsP");
        t.prejmi(new Tretja.Asistent(), "as_nqnKW");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_hT7Cp");
        t.prejmi(new Tretja.Profesor(), "prof_AbwNK");
        t.prejmi(new Tretja.Profesor(), "prof_biRJ1");
        t.prejmi(new Tretja.Profesor(), "prof_VG2UP");
        t.prejmi(new Tretja.Docent(), "doc_sPbqB");
        t.prejmi(new Tretja.Profesor(), "prof_lEmsr");
        t.prejmi(new Tretja.Docent(), "doc_oIfTK");
        t.prejmi(new Tretja.Asistent(), "as_6hRRj");
        t.prejmi(new Tretja.Asistent(), "as_oqcsz");
        t.prejmi(new Tretja.Docent(), "doc_XtMc2");
        t.prejmi(new Tretja.Docent(), "doc_rFr8Y");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_aB7EA");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Yi02m");
        t.prejmi(new Tretja.Asistent(), "as_f2Iuz");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_tmgXy");
        t.prejmi(new Tretja.Profesor(), "prof_vexoH");
        t.prejmi(new Tretja.Asistent(), "as_HhJwc");
        t.prejmi(new Tretja.Asistent(), "as_Nc88Z");
        t.prejmi(new Tretja.Profesor(), "prof_MsQwD");
        t.prejmi(new Tretja.Docent(), "doc_WQJy6");
        t.prejmi(new Tretja.Docent(), "doc_0fZdv");
        t.prejmi(new Tretja.Asistent(), "as_VfASo");
        t.prejmi(new Tretja.Asistent(), "as_ZheX5");
        t.prejmi(new Tretja.Asistent(), "as_f9NiN");
        t.prejmi(new Tretja.Profesor(), "prof_cdmVk");
        t.prejmi(new Tretja.Asistent(), "as_Ohr3K");
        t.prejmi(new Tretja.Profesor(), "prof_OiM3p");
        t.prejmi(new Tretja.Profesor(), "prof_H1PSv");
        t.prejmi(new Tretja.Profesor(), "prof_vNt8n");
        t.prejmi(new Tretja.Profesor(), "prof_v9vpW");
        t.prejmi(new Tretja.Profesor(), "prof_lLArP");
        t.prejmi(new Tretja.Docent(), "doc_tc2Yw");
        t.prejmi(new Tretja.Docent(), "doc_aK2At");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_cvFQX");
        t.prejmi(new Tretja.Docent(), "doc_3Il2h");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_5s7kw");
        t.prejmi(new Tretja.Profesor(), "prof_0ije2");
        t.prejmi(new Tretja.Profesor(), "prof_1qhua");
        t.prejmi(new Tretja.Asistent(), "as_qJvTy");
        t.prejmi(new Tretja.Asistent(), "as_0fQnD");
        t.prejmi(new Tretja.Profesor(), "prof_tGzHM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_K0OTv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_1nR0Q");
        t.prejmi(new Tretja.Docent(), "doc_KW8r6");
        t.prejmi(new Tretja.Profesor(), "prof_aE4Cp");
        t.prejmi(new Tretja.Profesor(), "prof_Les2h");
        t.prejmi(new Tretja.Asistent(), "as_zuZeb");
        t.prejmi(new Tretja.Asistent(), "as_QCyID");
        t.prejmi(new Tretja.Docent(), "doc_UuGTJ");
        t.prejmi(new Tretja.Asistent(), "as_c67Oi");
        t.prejmi(new Tretja.Profesor(), "prof_AeW5f");
        t.prejmi(new Tretja.Profesor(), "prof_W2Jfq");
        t.prejmi(new Tretja.Docent(), "doc_EVsym");
        t.prejmi(new Tretja.Profesor(), "prof_UmeIe");
        t.prejmi(new Tretja.Docent(), "doc_wPlUk");
        t.prejmi(new Tretja.Asistent(), "as_dGYVZ");
        t.prejmi(new Tretja.Profesor(), "prof_9KkoZ");
        t.prejmi(new Tretja.Asistent(), "as_zSymK");
        t.prejmi(new Tretja.Docent(), "doc_xaYTo");
        t.prejmi(new Tretja.Asistent(), "as_znpEm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_FmKFr");
        t.prejmi(new Tretja.Profesor(), "prof_WFSaZ");
        t.prejmi(new Tretja.Asistent(), "as_R9Nsz");
        t.prejmi(new Tretja.Asistent(), "as_jTeSY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_MuIEu");
        t.prejmi(new Tretja.Asistent(), "as_OYREX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_SlGGG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_qo5ZQ");
        t.prejmi(new Tretja.Profesor(), "prof_Lxuf2");
        t.prejmi(new Tretja.Asistent(), "as_WaupY");
        t.prejmi(new Tretja.Profesor(), "prof_38bK4");
        t.prejmi(new Tretja.Profesor(), "prof_eOIpo");
        t.prejmi(new Tretja.Docent(), "doc_daCnP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_4u0cp");
        t.prejmi(new Tretja.Profesor(), "prof_etIgS");
        t.prejmi(new Tretja.Asistent(), "as_ILVuJ");
        t.prejmi(new Tretja.Profesor(), "prof_u3M4H");
        t.prejmi(new Tretja.Docent(), "doc_HLuuf");
        t.prejmi(new Tretja.Asistent(), "as_4Akit");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_MGnvM");
        t.prejmi(new Tretja.Profesor(), "prof_iCAUs");
        t.prejmi(new Tretja.Docent(), "doc_81cUw");
        t.prejmi(new Tretja.Profesor(), "prof_UubdS");
        t.prejmi(new Tretja.Profesor(), "prof_We3Gi");
        t.prejmi(new Tretja.Profesor(), "prof_jb7UB");
        t.prejmi(new Tretja.Asistent(), "as_ohKGH");
        t.prejmi(new Tretja.Docent(), "doc_XfW8F");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_CyINz");
        t.prejmi(new Tretja.Profesor(), "prof_GcNUI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_dTlcE");
        t.prejmi(new Tretja.Asistent(), "as_oi0yQ");
        t.prejmi(new Tretja.Docent(), "doc_gkypY");
        t.prejmi(new Tretja.Profesor(), "prof_EQ0mC");
        t.prejmi(new Tretja.Profesor(), "prof_IVhFG");
        t.prejmi(new Tretja.Docent(), "doc_PnROU");
        t.prejmi(new Tretja.Asistent(), "as_lVuVL");
        t.prejmi(new Tretja.Asistent(), "as_e2R9O");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_e1g7o");
        t.prejmi(new Tretja.Docent(), "doc_cSaex");
        t.prejmi(new Tretja.Asistent(), "as_ONm6T");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_uS6PF");
        t.prejmi(new Tretja.Profesor(), "prof_8nmZC");
        t.prejmi(new Tretja.Asistent(), "as_GAh14");
        t.prejmi(new Tretja.Docent(), "doc_U28TW");
        t.prejmi(new Tretja.Docent(), "doc_YkoZj");
        t.prejmi(new Tretja.Docent(), "doc_88IKz");
        t.prejmi(new Tretja.Docent(), "doc_Rb6nh");
        t.prejmi(new Tretja.Docent(), "doc_J6jxT");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_dFGlV");
        t.prejmi(new Tretja.Asistent(), "as_GX2fi");
        t.prejmi(new Tretja.Docent(), "doc_XfFmG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_0ijMb");
        t.prejmi(new Tretja.Profesor(), "prof_lCsvr");
        t.prejmi(new Tretja.Profesor(), "prof_7e5Pn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_5dKi1");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_n5UKh");
        t.prejmi(new Tretja.Profesor(), "prof_RSAlh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_pSzGG");
        t.prejmi(new Tretja.Profesor(), "prof_5smgg");
        t.prejmi(new Tretja.Docent(), "doc_78A8X");
        t.prejmi(new Tretja.Profesor(), "prof_wg5OA");
        t.prejmi(new Tretja.Asistent(), "as_kKyK9");
        t.prejmi(new Tretja.Profesor(), "prof_gaUlR");
        t.prejmi(new Tretja.Asistent(), "as_1q9h3");
        t.prejmi(new Tretja.Asistent(), "as_u3XqH");
        t.prejmi(new Tretja.Profesor(), "prof_JC3T9");
        t.prejmi(new Tretja.Profesor(), "prof_JQwDZ");
        t.prejmi(new Tretja.Asistent(), "as_fXxYW");
        t.prejmi(new Tretja.Profesor(), "prof_pw41w");
        t.prejmi(new Tretja.Docent(), "doc_wYuZU");
        t.prejmi(new Tretja.Asistent(), "as_aMQnU");
        t.prejmi(new Tretja.Docent(), "doc_7I1P0");
        t.prejmi(new Tretja.Asistent(), "as_FR9NP");
        t.prejmi(new Tretja.Asistent(), "as_NdoDB");
        t.prejmi(new Tretja.Asistent(), "as_n7By7");
        t.prejmi(new Tretja.Asistent(), "as_t0XIG");
        t.prejmi(new Tretja.Profesor(), "prof_fjn30");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_lzHPx");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_o0hu0");
        t.prejmi(new Tretja.Docent(), "doc_6s17t");
        t.prejmi(new Tretja.Docent(), "doc_fGt1T");
        t.prejmi(new Tretja.Asistent(), "as_wP2Wn");
        t.prejmi(new Tretja.Docent(), "doc_77dwQ");
        t.prejmi(new Tretja.Profesor(), "prof_r8lgq");
        t.prejmi(new Tretja.Asistent(), "as_DUONa");
        t.prejmi(new Tretja.Asistent(), "as_z1yST");
        t.prejmi(new Tretja.Asistent(), "as_7FuAP");
        t.prejmi(new Tretja.Profesor(), "prof_EIp7h");
        t.prejmi(new Tretja.Asistent(), "as_RVkCZ");
        t.prejmi(new Tretja.Docent(), "doc_Ekd2B");
        t.prejmi(new Tretja.Profesor(), "prof_mqATn");
        t.prejmi(new Tretja.Asistent(), "as_FBzP6");
    }
}
