
import java.util.*;

public class Test02 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(6, 10, "bbaba"),
            new Cetrta.Prostor(5, 66, "abaaa"),
            new Cetrta.Prostor(7, 18, "abaaa"),
            new Cetrta.Prostor(7, 16, "bbbb"),
            new Cetrta.Prostor(5, 70, "bbaba"),
            new Cetrta.Prostor(7, 73, "bbbb"),
            new Cetrta.Prostor(5, 24, "bbbb"),
            new Cetrta.Prostor(3, 70, "abaaa"),
            new Cetrta.Prostor(6, 73, "bbbb"),
            new Cetrta.Prostor(4, 18, "bbaba"),
            new Cetrta.Prostor(4, 28, "bbaba"),
            new Cetrta.Prostor(6, 47, "abaaa"),
            new Cetrta.Prostor(2, 39, "bbbb"),
            new Cetrta.Prostor(4, 13, "abaaa"),
            new Cetrta.Prostor(2, 16, "bbaba"),
            new Cetrta.Prostor(3, 69, "bbbb"),
            new Cetrta.Prostor(2, 69, "abaaa"),
            new Cetrta.Prostor(2, 92, "abaaa"),
            new Cetrta.Prostor(6, 73, "bbaba"),
            new Cetrta.Prostor(7, 45, "abaaa"),
            new Cetrta.Prostor(3, 68, "abaaa"),
            new Cetrta.Prostor(5, 30, "bbaba"),
            new Cetrta.Prostor(6, 61, "abaaa"),
            new Cetrta.Prostor(5, 10, "bbbb"),
            new Cetrta.Prostor(4, 24, "bbbb"),
            new Cetrta.Prostor(2, 53, "bbaba"),
            new Cetrta.Prostor(1, 7, "bbbb"),
            new Cetrta.Prostor(3, 27, "bbbb"),
            new Cetrta.Prostor(3, 90, "bbaba"),
            new Cetrta.Prostor(1, 68, "abaaa"),
            new Cetrta.Prostor(3, 7, "abaaa"),
            new Cetrta.Prostor(6, 73, "bbbb"),
            new Cetrta.Prostor(6, 29, "bbaba"),
            new Cetrta.Prostor(3, 57, "bbaba"),
            new Cetrta.Prostor(6, 54, "abaaa"),
            new Cetrta.Prostor(3, 73, "bbaba"),
            new Cetrta.Prostor(7, 95, "abaaa"),
            new Cetrta.Prostor(5, 44, "bbaba"),
            new Cetrta.Prostor(4, 31, "bbbb"),
            new Cetrta.Prostor(7, 69, "bbaba"),
            new Cetrta.Prostor(7, 90, "bbaba"),
            new Cetrta.Prostor(7, 27, "bbbb"),
            new Cetrta.Prostor(6, 45, "abaaa"),
            new Cetrta.Prostor(3, 16, "bbaba"),
            new Cetrta.Prostor(5, 9, "bbbb"),
            new Cetrta.Prostor(7, 93, "bbbb"),
            new Cetrta.Prostor(7, 21, "bbbb"),
            new Cetrta.Prostor(1, 18, "bbbb"),
            new Cetrta.Prostor(1, 11, "abaaa"),
            new Cetrta.Prostor(5, 89, "abaaa"),
            new Cetrta.Prostor(6, 14, "bbaba"),
            new Cetrta.Prostor(5, 94, "bbbb"),
            new Cetrta.Prostor(1, 60, "abaaa"),
            new Cetrta.Prostor(5, 74, "abaaa"),
            new Cetrta.Prostor(1, 64, "bbbb"),
            new Cetrta.Prostor(1, 18, "abaaa"),
            new Cetrta.Prostor(5, 8, "bbbb"),
            new Cetrta.Prostor(6, 29, "abaaa"),
            new Cetrta.Prostor(6, 87, "bbbb"),
            new Cetrta.Prostor(4, 51, "abaaa"),
            new Cetrta.Prostor(6, 64, "bbaba"),
            new Cetrta.Prostor(4, 46, "bbbb"),
            new Cetrta.Prostor(2, 35, "bbbb"),
            new Cetrta.Prostor(6, 54, "abaaa"),
            new Cetrta.Prostor(5, 1, "bbbb"),
            new Cetrta.Prostor(6, 13, "abaaa"),
            new Cetrta.Prostor(4, 93, "bbaba"),
            new Cetrta.Prostor(4, 34, "abaaa"),
            new Cetrta.Prostor(5, 27, "bbaba"),
            new Cetrta.Prostor(4, 37, "abaaa"),
            new Cetrta.Prostor(3, 10, "bbbb"),
            new Cetrta.Prostor(5, 2, "bbaba"),
            new Cetrta.Prostor(4, 45, "bbbb"),
            new Cetrta.Prostor(2, 42, "bbbb"),
            new Cetrta.Prostor(7, 43, "abaaa"),
            new Cetrta.Prostor(3, 56, "bbaba"),
            new Cetrta.Prostor(5, 64, "bbaba"),
            new Cetrta.Prostor(2, 51, "bbbb"),
            new Cetrta.Prostor(3, 54, "bbbb"),
            new Cetrta.Prostor(6, 76, "abaaa"),
            new Cetrta.Prostor(4, 81, "abaaa"),
            new Cetrta.Prostor(4, 97, "abaaa"),
            new Cetrta.Prostor(4, 92, "bbbb"),
            new Cetrta.Prostor(2, 73, "bbbb"),
            new Cetrta.Prostor(4, 6, "abaaa"),
            new Cetrta.Prostor(3, 33, "bbaba"),
            new Cetrta.Prostor(5, 72, "bbbb"),
            new Cetrta.Prostor(7, 89, "bbbb"),
            new Cetrta.Prostor(2, 58, "abaaa"),
            new Cetrta.Prostor(4, 51, "abaaa"),
            new Cetrta.Prostor(2, 25, "abaaa"),
            new Cetrta.Prostor(1, 95, "bbaba"),
            new Cetrta.Prostor(7, 29, "bbaba"),
            new Cetrta.Prostor(2, 100, "abaaa"),
            new Cetrta.Prostor(1, 12, "abaaa"),
            new Cetrta.Prostor(6, 16, "bbbb")
        ));

        List<String> namembnosti = new ArrayList<>(Cetrta.namembnosti(prostori));
        namembnosti.sort(null);
        System.out.println(namembnosti);
    }
}
