
import java.util.*;

public class Test04 {

    public static void main(String[] args) {
        List<Cetrta.Prostor> prostori = new ArrayList<>(List.of(
            new Cetrta.Prostor(1, 39, "abaab"),
            new Cetrta.Prostor(3, 99, "ba"),
            new Cetrta.Prostor(1, 75, "bbbb"),
            new Cetrta.Prostor(2, 56, "ba"),
            new Cetrta.Prostor(2, 77, "ba"),
            new Cetrta.Prostor(2, 66, "bbbb"),
            new Cetrta.Prostor(4, 22, "abaa"),
            new Cetrta.Prostor(3, 31, "abaab"),
            new Cetrta.Prostor(1, 67, "abaab"),
            new Cetrta.Prostor(2, 64, "bbbb"),
            new Cetrta.Prostor(1, 5, "ba"),
            new Cetrta.Prostor(1, 42, "abaa"),
            new Cetrta.Prostor(3, 57, "ba"),
            new Cetrta.Prostor(4, 81, "abaab"),
            new Cetrta.Prostor(2, 63, "abaa"),
            new Cetrta.Prostor(3, 16, "ba"),
            new Cetrta.Prostor(4, 64, "ba"),
            new Cetrta.Prostor(1, 30, "bbbb"),
            new Cetrta.Prostor(1, 12, "abaab"),
            new Cetrta.Prostor(3, 54, "abaab"),
            new Cetrta.Prostor(1, 32, "abaa"),
            new Cetrta.Prostor(3, 72, "abaab"),
            new Cetrta.Prostor(3, 47, "ba"),
            new Cetrta.Prostor(2, 49, "bbbb"),
            new Cetrta.Prostor(4, 96, "abaa"),
            new Cetrta.Prostor(2, 16, "ba"),
            new Cetrta.Prostor(2, 62, "abaab"),
            new Cetrta.Prostor(1, 65, "abaab"),
            new Cetrta.Prostor(3, 3, "bbbb"),
            new Cetrta.Prostor(4, 65, "abaa"),
            new Cetrta.Prostor(4, 1, "bbbb"),
            new Cetrta.Prostor(4, 31, "abaab"),
            new Cetrta.Prostor(1, 1, "ba"),
            new Cetrta.Prostor(3, 38, "bbbb"),
            new Cetrta.Prostor(3, 78, "ba"),
            new Cetrta.Prostor(3, 1, "abaa"),
            new Cetrta.Prostor(3, 40, "abaab"),
            new Cetrta.Prostor(3, 11, "bbbb"),
            new Cetrta.Prostor(2, 59, "ba"),
            new Cetrta.Prostor(3, 90, "abaa"),
            new Cetrta.Prostor(1, 93, "abaab"),
            new Cetrta.Prostor(4, 89, "abaa"),
            new Cetrta.Prostor(2, 13, "ba"),
            new Cetrta.Prostor(3, 35, "ba"),
            new Cetrta.Prostor(1, 34, "ba"),
            new Cetrta.Prostor(4, 86, "abaa"),
            new Cetrta.Prostor(3, 96, "ba"),
            new Cetrta.Prostor(3, 87, "ba"),
            new Cetrta.Prostor(4, 10, "abaa"),
            new Cetrta.Prostor(4, 39, "abaa"),
            new Cetrta.Prostor(2, 26, "ba"),
            new Cetrta.Prostor(2, 21, "abaa"),
            new Cetrta.Prostor(1, 80, "bbbb"),
            new Cetrta.Prostor(1, 70, "abaab"),
            new Cetrta.Prostor(1, 11, "abaab"),
            new Cetrta.Prostor(3, 50, "ba"),
            new Cetrta.Prostor(3, 70, "abaa"),
            new Cetrta.Prostor(4, 91, "bbbb"),
            new Cetrta.Prostor(2, 80, "abaa"),
            new Cetrta.Prostor(4, 63, "ba"),
            new Cetrta.Prostor(1, 81, "ba"),
            new Cetrta.Prostor(3, 43, "bbbb"),
            new Cetrta.Prostor(4, 56, "bbbb"),
            new Cetrta.Prostor(2, 10, "abaab"),
            new Cetrta.Prostor(4, 36, "abaab"),
            new Cetrta.Prostor(4, 75, "abaa"),
            new Cetrta.Prostor(4, 92, "bbbb"),
            new Cetrta.Prostor(1, 14, "abaab"),
            new Cetrta.Prostor(2, 97, "abaab"),
            new Cetrta.Prostor(1, 74, "abaa"),
            new Cetrta.Prostor(1, 19, "bbbb"),
            new Cetrta.Prostor(1, 48, "ba"),
            new Cetrta.Prostor(3, 75, "abaa"),
            new Cetrta.Prostor(4, 32, "abaab"),
            new Cetrta.Prostor(4, 94, "ba"),
            new Cetrta.Prostor(4, 45, "abaab"),
            new Cetrta.Prostor(3, 51, "bbbb"),
            new Cetrta.Prostor(4, 93, "ba"),
            new Cetrta.Prostor(2, 68, "abaa"),
            new Cetrta.Prostor(4, 17, "ba"),
            new Cetrta.Prostor(4, 42, "bbbb"),
            new Cetrta.Prostor(3, 88, "abaa"),
            new Cetrta.Prostor(3, 37, "bbbb"),
            new Cetrta.Prostor(4, 23, "abaa"),
            new Cetrta.Prostor(2, 2, "abaab"),
            new Cetrta.Prostor(1, 53, "ba"),
            new Cetrta.Prostor(1, 44, "abaab"),
            new Cetrta.Prostor(2, 61, "abaa"),
            new Cetrta.Prostor(2, 86, "abaab"),
            new Cetrta.Prostor(4, 51, "ba"),
            new Cetrta.Prostor(4, 21, "abaab"),
            new Cetrta.Prostor(2, 14, "bbbb"),
            new Cetrta.Prostor(2, 23, "abaa"),
            new Cetrta.Prostor(1, 97, "bbbb"),
            new Cetrta.Prostor(3, 93, "bbbb"),
            new Cetrta.Prostor(1, 38, "ba"),
            new Cetrta.Prostor(1, 52, "ba"),
            new Cetrta.Prostor(4, 70, "ba"),
            new Cetrta.Prostor(2, 19, "ba"),
            new Cetrta.Prostor(3, 81, "ba")
        ));

        Cetrta.uredi(prostori);

        for (Cetrta.Prostor prostor: prostori) {
            System.out.println(prostor);
        }
    }
}
