
public class Test44 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Weqh Hiyx", "Ugts"),
            new Tretja.Oseba("Bbpc Tmco", "Razn"),
            new Tretja.Oseba("Mxxr Wtdv", "Ggoc"),
            new Tretja.Oseba("Jdga Kbag", "Rfpr"),
            new Tretja.Oseba("Iriz Amvg", "Knap"),
            new Tretja.Oseba("Bba Fcju", "Knap"),
            new Tretja.Oseba("Cmlr Qyup", "Ggoc"),
            new Tretja.Oseba("Uvst Cirv", "Razn"),
            new Tretja.Oseba("Cgoa Wbs", "Razn"),
            new Tretja.Oseba("Fcqi Dbke", "Rfpr"),
            new Tretja.Oseba("Elgo Vojq", "Razn"),
            new Tretja.Oseba("Nexy Qfjf", "Razn"),
            new Tretja.Oseba("Kcst Opmz", "Knap"),
            new Tretja.Oseba("Zfle Hwgv", "Knap"),
            new Tretja.Oseba("Brvj Rjse", "Rfpr"),
            new Tretja.Oseba("Ecok Qsmj", "Ugts"),
            new Tretja.Oseba("Jspd Iudv", "Ggoc"),
            new Tretja.Oseba("Gqad Jaqt", "Ggoc"),
            new Tretja.Oseba("Bzqf Myof", "Rfpr"),
            new Tretja.Oseba("Rpuf Afog", "Razn"),
            new Tretja.Oseba("Majl Lkmw", "Razn"),
            new Tretja.Oseba("Rtsz Zujm", "Rfpr"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Qkpz", "Ggoc"),
            new Tretja.Cilj("Uxaj", "Ggoc"),
            new Tretja.Cilj("Nscx", "Knap"),
            new Tretja.Cilj("Pabh", "Ggoc"),
            new Tretja.Cilj("Nger", "Rfpr"),
            new Tretja.Cilj("Malc", "Ugts"),
            new Tretja.Cilj("Ebwi", "Razn"),
            new Tretja.Cilj("Msbo", "Rfpr"),
            new Tretja.Cilj("Vgdx", "Rfpr"),
            new Tretja.Cilj("Atwe", "Ugts"),
            new Tretja.Cilj("Uwqe", "Knap"),
            new Tretja.Cilj("Lylu", "Ggoc"),
            new Tretja.Cilj("Zhhi", "Razn"),
            new Tretja.Cilj("Rzsi", "Ggoc"),
            new Tretja.Cilj("Vrlr", "Razn"),
            new Tretja.Cilj("Noko", "Knap"),
            new Tretja.Cilj("Skco", "Ggoc"),
            new Tretja.Cilj("Vbau", "Rfpr"),
            new Tretja.Cilj("Notf", "Knap"),
            new Tretja.Cilj("Iicl", "Ugts"),
            new Tretja.Cilj("Ncye", "Ugts"),
            new Tretja.Cilj("Hhyx", "Ggoc"),
            new Tretja.Cilj("Nyrj", "Rfpr"),
            new Tretja.Cilj("Ospq", "Rfpr"),
            new Tretja.Cilj("Sqpr", "Ggoc"),
            new Tretja.Cilj("Kqns", "Ugts"),
            new Tretja.Cilj("Osma", "Ggoc"),
            new Tretja.Cilj("Pehl", "Knap"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[20], cilji[18], 2019),
            new Tretja.Nocitev(osebe[18], cilji[11], 2000),
            new Tretja.Nocitev(osebe[0], cilji[7], 2012),
            new Tretja.Nocitev(osebe[12], cilji[7], 2005),
            new Tretja.Nocitev(osebe[20], cilji[18], 2003),
            new Tretja.Nocitev(osebe[10], cilji[13], 2019),
            new Tretja.Nocitev(osebe[0], cilji[20], 2004),
            new Tretja.Nocitev(osebe[6], cilji[22], 2001),
            new Tretja.Nocitev(osebe[14], cilji[25], 2018),
            new Tretja.Nocitev(osebe[18], cilji[22], 2018),
            new Tretja.Nocitev(osebe[12], cilji[21], 2006),
            new Tretja.Nocitev(osebe[4], cilji[8], 2014),
            new Tretja.Nocitev(osebe[1], cilji[22], 2019),
            new Tretja.Nocitev(osebe[15], cilji[22], 2008),
            new Tretja.Nocitev(osebe[14], cilji[25], 2013),
            new Tretja.Nocitev(osebe[18], cilji[21], 2010),
            new Tretja.Nocitev(osebe[8], cilji[6], 2007),
            new Tretja.Nocitev(osebe[6], cilji[7], 2009),
            new Tretja.Nocitev(osebe[15], cilji[10], 2016),
            new Tretja.Nocitev(osebe[17], cilji[5], 2010),
            new Tretja.Nocitev(osebe[14], cilji[25], 2015),
            new Tretja.Nocitev(osebe[19], cilji[7], 2015),
            new Tretja.Nocitev(osebe[2], cilji[17], 2001),
            new Tretja.Nocitev(osebe[5], cilji[20], 2013),
            new Tretja.Nocitev(osebe[13], cilji[14], 2007),
            new Tretja.Nocitev(osebe[11], cilji[3], 2008),
            new Tretja.Nocitev(osebe[9], cilji[17], 2002),
            new Tretja.Nocitev(osebe[5], cilji[20], 2004),
            new Tretja.Nocitev(osebe[17], cilji[16], 2006),
            new Tretja.Nocitev(osebe[21], cilji[9], 2002),
            new Tretja.Nocitev(osebe[14], cilji[25], 2019),
            new Tretja.Nocitev(osebe[5], cilji[20], 2016),
            new Tretja.Nocitev(osebe[9], cilji[17], 2012),
            new Tretja.Nocitev(osebe[17], cilji[3], 2006),
            new Tretja.Nocitev(osebe[2], cilji[17], 2012),
            new Tretja.Nocitev(osebe[6], cilji[22], 2006),
            new Tretja.Nocitev(osebe[13], cilji[14], 2012),
            new Tretja.Nocitev(osebe[16], cilji[18], 2005),
            new Tretja.Nocitev(osebe[1], cilji[22], 2009),
            new Tretja.Nocitev(osebe[10], cilji[13], 2010),
            new Tretja.Nocitev(osebe[9], cilji[17], 2009),
            new Tretja.Nocitev(osebe[15], cilji[10], 2011),
            new Tretja.Nocitev(osebe[0], cilji[27], 2010),
            new Tretja.Nocitev(osebe[16], cilji[18], 2010),
            new Tretja.Nocitev(osebe[6], cilji[8], 2010),
            new Tretja.Nocitev(osebe[16], cilji[18], 2006),
            new Tretja.Nocitev(osebe[18], cilji[9], 2000),
            new Tretja.Nocitev(osebe[1], cilji[22], 2007),
            new Tretja.Nocitev(osebe[2], cilji[17], 2020),
            new Tretja.Nocitev(osebe[12], cilji[21], 2002),
            new Tretja.Nocitev(osebe[6], cilji[25], 2005),
            new Tretja.Nocitev(osebe[19], cilji[17], 2010),
            new Tretja.Nocitev(osebe[4], cilji[13], 2000),
            new Tretja.Nocitev(osebe[9], cilji[17], 2005),
            new Tretja.Nocitev(osebe[4], cilji[18], 2001),
            new Tretja.Nocitev(osebe[2], cilji[17], 2004),
            new Tretja.Nocitev(osebe[13], cilji[14], 2001),
            new Tretja.Nocitev(osebe[18], cilji[9], 2004),
            new Tretja.Nocitev(osebe[4], cilji[6], 2015),
            new Tretja.Nocitev(osebe[10], cilji[13], 2011),
            new Tretja.Nocitev(osebe[4], cilji[24], 2007),
            new Tretja.Nocitev(osebe[6], cilji[16], 2000),
            new Tretja.Nocitev(osebe[12], cilji[4], 2020),
            new Tretja.Nocitev(osebe[7], cilji[21], 2018),
            new Tretja.Nocitev(osebe[15], cilji[9], 2017),
            new Tretja.Nocitev(osebe[5], cilji[20], 2016),
            new Tretja.Nocitev(osebe[1], cilji[22], 2005),
            new Tretja.Nocitev(osebe[8], cilji[6], 2008),
            new Tretja.Nocitev(osebe[18], cilji[2], 2005),
            new Tretja.Nocitev(osebe[6], cilji[7], 2009),
            new Tretja.Nocitev(osebe[11], cilji[4], 2014),
            new Tretja.Nocitev(osebe[14], cilji[25], 2019),
            new Tretja.Nocitev(osebe[13], cilji[14], 2018),
            new Tretja.Nocitev(osebe[9], cilji[17], 2003),
            new Tretja.Nocitev(osebe[15], cilji[8], 2008),
            new Tretja.Nocitev(osebe[19], cilji[17], 2018),
            new Tretja.Nocitev(osebe[10], cilji[13], 2004),
            new Tretja.Nocitev(osebe[20], cilji[18], 2019),
            new Tretja.Nocitev(osebe[9], cilji[17], 2005),
            new Tretja.Nocitev(osebe[5], cilji[20], 2009),
            new Tretja.Nocitev(osebe[9], cilji[17], 2015),
            new Tretja.Nocitev(osebe[12], cilji[17], 2011),
            new Tretja.Nocitev(osebe[3], cilji[6], 2002),
            new Tretja.Nocitev(osebe[15], cilji[11], 2003),
            new Tretja.Nocitev(osebe[12], cilji[15], 2004),
            new Tretja.Nocitev(osebe[9], cilji[17], 2000),
            new Tretja.Nocitev(osebe[0], cilji[17], 2011),
            new Tretja.Nocitev(osebe[14], cilji[25], 2014),
            new Tretja.Nocitev(osebe[19], cilji[10], 2016),
            new Tretja.Nocitev(osebe[1], cilji[22], 2020),
            new Tretja.Nocitev(osebe[14], cilji[25], 2009),
            new Tretja.Nocitev(osebe[20], cilji[18], 2019),
            new Tretja.Nocitev(osebe[19], cilji[11], 2010),
            new Tretja.Nocitev(osebe[20], cilji[18], 2013),
            new Tretja.Nocitev(osebe[17], cilji[0], 2010),
            new Tretja.Nocitev(osebe[21], cilji[22], 2019),
            new Tretja.Nocitev(osebe[15], cilji[22], 2017),
            new Tretja.Nocitev(osebe[8], cilji[6], 2000),
            new Tretja.Nocitev(osebe[5], cilji[20], 2017),
            new Tretja.Nocitev(osebe[8], cilji[6], 2016),
            new Tretja.Nocitev(osebe[13], cilji[14], 2006),
            new Tretja.Nocitev(osebe[4], cilji[3], 2014),
            new Tretja.Nocitev(osebe[11], cilji[23], 2010),
            new Tretja.Nocitev(osebe[11], cilji[3], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2014),
            new Tretja.Nocitev(osebe[13], cilji[14], 2005),
            new Tretja.Nocitev(osebe[3], cilji[25], 2005),
            new Tretja.Nocitev(osebe[6], cilji[17], 2004),
            new Tretja.Nocitev(osebe[3], cilji[8], 2020),
            new Tretja.Nocitev(osebe[0], cilji[25], 2005),
            new Tretja.Nocitev(osebe[16], cilji[18], 2005),
            new Tretja.Nocitev(osebe[11], cilji[13], 2012),
            new Tretja.Nocitev(osebe[10], cilji[13], 2020),
            new Tretja.Nocitev(osebe[0], cilji[3], 2007),
            new Tretja.Nocitev(osebe[8], cilji[6], 2015),
            new Tretja.Nocitev(osebe[12], cilji[19], 2013),
            new Tretja.Nocitev(osebe[21], cilji[13], 2016),
            new Tretja.Nocitev(osebe[20], cilji[18], 2016),
            new Tretja.Nocitev(osebe[13], cilji[14], 2017),
            new Tretja.Nocitev(osebe[1], cilji[22], 2017),
            new Tretja.Nocitev(osebe[7], cilji[21], 2014),
            new Tretja.Nocitev(osebe[19], cilji[8], 2016),
            new Tretja.Nocitev(osebe[15], cilji[19], 2014),
            new Tretja.Nocitev(osebe[21], cilji[10], 2008),
            new Tretja.Nocitev(osebe[14], cilji[25], 2004),
            new Tretja.Nocitev(osebe[3], cilji[18], 2004),
            new Tretja.Nocitev(osebe[6], cilji[5], 2018),
            new Tretja.Nocitev(osebe[2], cilji[17], 2016),
            new Tretja.Nocitev(osebe[6], cilji[24], 2014),
            new Tretja.Nocitev(osebe[14], cilji[25], 2001),
            new Tretja.Nocitev(osebe[0], cilji[9], 2019),
            new Tretja.Nocitev(osebe[16], cilji[18], 2005),
            new Tretja.Nocitev(osebe[4], cilji[23], 2004),
            new Tretja.Nocitev(osebe[4], cilji[11], 2015),
            new Tretja.Nocitev(osebe[4], cilji[4], 2020),
            new Tretja.Nocitev(osebe[17], cilji[13], 2012),
            new Tretja.Nocitev(osebe[11], cilji[20], 2015),
            new Tretja.Nocitev(osebe[9], cilji[17], 2010),
            new Tretja.Nocitev(osebe[12], cilji[17], 2002),
            new Tretja.Nocitev(osebe[2], cilji[17], 2003),
            new Tretja.Nocitev(osebe[10], cilji[13], 2012),
            new Tretja.Nocitev(osebe[11], cilji[14], 2005),
            new Tretja.Nocitev(osebe[14], cilji[25], 2006),
            new Tretja.Nocitev(osebe[3], cilji[10], 2003),
            new Tretja.Nocitev(osebe[4], cilji[4], 2003),
            new Tretja.Nocitev(osebe[17], cilji[2], 2014),
            new Tretja.Nocitev(osebe[0], cilji[23], 2005),
            new Tretja.Nocitev(osebe[9], cilji[17], 2004),
            new Tretja.Nocitev(osebe[10], cilji[13], 2000),
            new Tretja.Nocitev(osebe[19], cilji[10], 2003),
            new Tretja.Nocitev(osebe[8], cilji[6], 2014),
            new Tretja.Nocitev(osebe[13], cilji[14], 2004),
            new Tretja.Nocitev(osebe[4], cilji[25], 2016),
            new Tretja.Nocitev(osebe[0], cilji[7], 2016),
            new Tretja.Nocitev(osebe[19], cilji[19], 2017),
            new Tretja.Nocitev(osebe[1], cilji[22], 2008),
            new Tretja.Nocitev(osebe[19], cilji[24], 2003),
            new Tretja.Nocitev(osebe[5], cilji[20], 2020),
            new Tretja.Nocitev(osebe[2], cilji[17], 2015),
            new Tretja.Nocitev(osebe[8], cilji[6], 2000),
            new Tretja.Nocitev(osebe[16], cilji[18], 2014),
            new Tretja.Nocitev(osebe[21], cilji[24], 2017),
            new Tretja.Nocitev(osebe[15], cilji[20], 2010),
            new Tretja.Nocitev(osebe[11], cilji[24], 2003),
            new Tretja.Nocitev(osebe[4], cilji[23], 2014),
            new Tretja.Nocitev(osebe[13], cilji[14], 2012),
            new Tretja.Nocitev(osebe[6], cilji[19], 2005),
            new Tretja.Nocitev(osebe[18], cilji[21], 2004),
            new Tretja.Nocitev(osebe[18], cilji[22], 2000),
            new Tretja.Nocitev(osebe[19], cilji[20], 2000),
            new Tretja.Nocitev(osebe[9], cilji[17], 2018),
            new Tretja.Nocitev(osebe[18], cilji[14], 2007),
            new Tretja.Nocitev(osebe[17], cilji[12], 2003),
            new Tretja.Nocitev(osebe[10], cilji[13], 2011),
            new Tretja.Nocitev(osebe[19], cilji[25], 2012),
            new Tretja.Nocitev(osebe[11], cilji[8], 2004),
            new Tretja.Nocitev(osebe[14], cilji[25], 2018),
            new Tretja.Nocitev(osebe[14], cilji[25], 2014),
            new Tretja.Nocitev(osebe[3], cilji[24], 2008),
            new Tretja.Nocitev(osebe[14], cilji[25], 2019),
            new Tretja.Nocitev(osebe[13], cilji[14], 2009),
            new Tretja.Nocitev(osebe[1], cilji[22], 2003),
            new Tretja.Nocitev(osebe[5], cilji[20], 2011),
            new Tretja.Nocitev(osebe[17], cilji[9], 2007),
            new Tretja.Nocitev(osebe[0], cilji[2], 2012),
            new Tretja.Nocitev(osebe[20], cilji[18], 2019),
            new Tretja.Nocitev(osebe[11], cilji[8], 2010),
            new Tretja.Nocitev(osebe[7], cilji[21], 2014),
            new Tretja.Nocitev(osebe[21], cilji[2], 2005),
            new Tretja.Nocitev(osebe[16], cilji[18], 2011),
            new Tretja.Nocitev(osebe[13], cilji[14], 2016),
            new Tretja.Nocitev(osebe[2], cilji[17], 2011),
            new Tretja.Nocitev(osebe[7], cilji[21], 2015),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2001, 2013);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
