
public class Test01 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Dybb Wftf", "Wxgs"),
            new Tretja.Oseba("Ofql Vrap", "Wxgs"),
            new Tretja.Oseba("Vfxu Tshb", "Cdqv"),
            new Tretja.Oseba("Cuep Rhux", "Wxgs"),
            new Tretja.Oseba("Pgid Vpih", "Wxgs"),
            new Tretja.Oseba("Ghdi Nldg", "Cdqv"),
            new Tretja.Oseba("Sica Xqvs", "Cdqv"),
            new Tretja.Oseba("Hxks Wdhw", "Cdqv"),
            new Tretja.Oseba("Mprh Nonl", "Wxgs"),
            new Tretja.Oseba("Favi Gqwc", "Cdqv"),
            new Tretja.Oseba("Bxdw Mnc", "Cdqv"),
            new Tretja.Oseba("Vopf Qixz", "Wxgs"),
            new Tretja.Oseba("Qtko Ltay", "Wxgs"),
            new Tretja.Oseba("Np Hweh", "Cdqv"),
            new Tretja.Oseba("Kyoe Nztt", "Cdqv"),
            new Tretja.Oseba("Rwip Xtka", "Cdqv"),
            new Tretja.Oseba("Xebe Ulye", "Cdqv"),
            new Tretja.Oseba("Tlwl Jayq", "Cdqv"),
            new Tretja.Oseba("Gqu Gdqe", "Cdqv"),
            new Tretja.Oseba("Dcsl Rffp", "Wxgs"),
            new Tretja.Oseba("Oxhu Gqrh", "Cdqv"),
            new Tretja.Oseba("Pxhw Lsti", "Wxgs"),
            new Tretja.Oseba("Evyy Sbk", "Cdqv"),
            new Tretja.Oseba("Mydp Qrnk", "Wxgs"),
            new Tretja.Oseba("Tzbt Femk", "Cdqv"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Zswi", "Wxgs"),
            new Tretja.Cilj("Dhqs", "Cdqv"),
            new Tretja.Cilj("Iaxd", "Wxgs"),
            new Tretja.Cilj("Gtoo", "Cdqv"),
            new Tretja.Cilj("Dwso", "Cdqv"),
            new Tretja.Cilj("Docs", "Wxgs"),
            new Tretja.Cilj("Xkgx", "Cdqv"),
            new Tretja.Cilj("Wlwg", "Cdqv"),
            new Tretja.Cilj("Advs", "Wxgs"),
            new Tretja.Cilj("Lmt", "Wxgs"),
            new Tretja.Cilj("Hvke", "Wxgs"),
            new Tretja.Cilj("Yibw", "Wxgs"),
            new Tretja.Cilj("Foz", "Wxgs"),
            new Tretja.Cilj("Ikwk", "Wxgs"),
            new Tretja.Cilj("Pzvo", "Cdqv"),
            new Tretja.Cilj("Gxxv", "Wxgs"),
            new Tretja.Cilj("Jike", "Cdqv"),
            new Tretja.Cilj("Kfli", "Wxgs"),
            new Tretja.Cilj("Uamk", "Cdqv"),
            new Tretja.Cilj("Bvzv", "Cdqv"),
            new Tretja.Cilj("Oins", "Cdqv"),
            new Tretja.Cilj("Oorz", "Cdqv"),
            new Tretja.Cilj("Xdhl", "Cdqv"),
            new Tretja.Cilj("Eatk", "Cdqv"),
            new Tretja.Cilj("Kqwz", "Cdqv"),
            new Tretja.Cilj("Moyd", "Wxgs"),
            new Tretja.Cilj("Gfwh", "Cdqv"),
            new Tretja.Cilj("Xlsh", "Cdqv"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[21], cilji[7], 2012),
            new Tretja.Nocitev(osebe[0], cilji[23], 2020),
            new Tretja.Nocitev(osebe[10], cilji[16], 2012),
            new Tretja.Nocitev(osebe[3], cilji[3], 2009),
            new Tretja.Nocitev(osebe[15], cilji[25], 2005),
            new Tretja.Nocitev(osebe[17], cilji[3], 2013),
            new Tretja.Nocitev(osebe[20], cilji[15], 2009),
            new Tretja.Nocitev(osebe[19], cilji[17], 2005),
            new Tretja.Nocitev(osebe[21], cilji[7], 2019),
            new Tretja.Nocitev(osebe[0], cilji[23], 2014),
            new Tretja.Nocitev(osebe[11], cilji[12], 2002),
            new Tretja.Nocitev(osebe[14], cilji[18], 2006),
            new Tretja.Nocitev(osebe[21], cilji[7], 2020),
            new Tretja.Nocitev(osebe[16], cilji[19], 2006),
            new Tretja.Nocitev(osebe[6], cilji[0], 2015),
            new Tretja.Nocitev(osebe[1], cilji[0], 2013),
            new Tretja.Nocitev(osebe[15], cilji[25], 2020),
            new Tretja.Nocitev(osebe[20], cilji[15], 2017),
            new Tretja.Nocitev(osebe[22], cilji[25], 2008),
            new Tretja.Nocitev(osebe[18], cilji[22], 2019),
            new Tretja.Nocitev(osebe[6], cilji[0], 2010),
            new Tretja.Nocitev(osebe[13], cilji[8], 2009),
            new Tretja.Nocitev(osebe[20], cilji[15], 2019),
            new Tretja.Nocitev(osebe[1], cilji[0], 2017),
            new Tretja.Nocitev(osebe[6], cilji[0], 2013),
            new Tretja.Nocitev(osebe[8], cilji[2], 2011),
            new Tretja.Nocitev(osebe[7], cilji[22], 2010),
            new Tretja.Nocitev(osebe[10], cilji[5], 2011),
            new Tretja.Nocitev(osebe[3], cilji[24], 2015),
            new Tretja.Nocitev(osebe[22], cilji[25], 2016),
            new Tretja.Nocitev(osebe[4], cilji[9], 2015),
            new Tretja.Nocitev(osebe[8], cilji[2], 2009),
            new Tretja.Nocitev(osebe[11], cilji[26], 2018),
            new Tretja.Nocitev(osebe[13], cilji[6], 2007),
            new Tretja.Nocitev(osebe[15], cilji[25], 2007),
            new Tretja.Nocitev(osebe[7], cilji[7], 2014),
            new Tretja.Nocitev(osebe[14], cilji[27], 2015),
            new Tretja.Nocitev(osebe[9], cilji[27], 2011),
            new Tretja.Nocitev(osebe[13], cilji[10], 2002),
            new Tretja.Nocitev(osebe[6], cilji[0], 2000),
            new Tretja.Nocitev(osebe[18], cilji[17], 2005),
            new Tretja.Nocitev(osebe[23], cilji[11], 2003),
            new Tretja.Nocitev(osebe[4], cilji[9], 2018),
            new Tretja.Nocitev(osebe[14], cilji[2], 2008),
            new Tretja.Nocitev(osebe[4], cilji[9], 2010),
            new Tretja.Nocitev(osebe[11], cilji[7], 2018),
            new Tretja.Nocitev(osebe[24], cilji[15], 2003),
            new Tretja.Nocitev(osebe[6], cilji[0], 2001),
            new Tretja.Nocitev(osebe[17], cilji[3], 2013),
            new Tretja.Nocitev(osebe[21], cilji[7], 2004),
            new Tretja.Nocitev(osebe[13], cilji[0], 2016),
            new Tretja.Nocitev(osebe[12], cilji[25], 2008),
            new Tretja.Nocitev(osebe[16], cilji[6], 2006),
            new Tretja.Nocitev(osebe[10], cilji[14], 2004),
            new Tretja.Nocitev(osebe[11], cilji[7], 2013),
            new Tretja.Nocitev(osebe[23], cilji[11], 2006),
            new Tretja.Nocitev(osebe[0], cilji[23], 2003),
            new Tretja.Nocitev(osebe[17], cilji[3], 2016),
            new Tretja.Nocitev(osebe[12], cilji[4], 2006),
            new Tretja.Nocitev(osebe[7], cilji[7], 2000),
            new Tretja.Nocitev(osebe[4], cilji[9], 2011),
            new Tretja.Nocitev(osebe[9], cilji[11], 2010),
            new Tretja.Nocitev(osebe[5], cilji[18], 2015),
            new Tretja.Nocitev(osebe[24], cilji[6], 2020),
            new Tretja.Nocitev(osebe[17], cilji[3], 2020),
            new Tretja.Nocitev(osebe[1], cilji[0], 2001),
            new Tretja.Nocitev(osebe[6], cilji[0], 2020),
            new Tretja.Nocitev(osebe[21], cilji[7], 2013),
            new Tretja.Nocitev(osebe[3], cilji[27], 2004),
            new Tretja.Nocitev(osebe[3], cilji[13], 2014),
            new Tretja.Nocitev(osebe[23], cilji[11], 2003),
            new Tretja.Nocitev(osebe[3], cilji[16], 2015),
            new Tretja.Nocitev(osebe[21], cilji[7], 2013),
            new Tretja.Nocitev(osebe[24], cilji[18], 2000),
            new Tretja.Nocitev(osebe[4], cilji[9], 2004),
            new Tretja.Nocitev(osebe[11], cilji[27], 2019),
            new Tretja.Nocitev(osebe[3], cilji[19], 2015),
            new Tretja.Nocitev(osebe[12], cilji[16], 2004),
            new Tretja.Nocitev(osebe[20], cilji[15], 2010),
            new Tretja.Nocitev(osebe[24], cilji[24], 2008),
            new Tretja.Nocitev(osebe[7], cilji[11], 2017),
            new Tretja.Nocitev(osebe[13], cilji[27], 2009),
            new Tretja.Nocitev(osebe[24], cilji[5], 2018),
            new Tretja.Nocitev(osebe[10], cilji[10], 2014),
            new Tretja.Nocitev(osebe[1], cilji[0], 2016),
            new Tretja.Nocitev(osebe[13], cilji[2], 2016),
            new Tretja.Nocitev(osebe[21], cilji[7], 2001),
            new Tretja.Nocitev(osebe[9], cilji[11], 2007),
            new Tretja.Nocitev(osebe[10], cilji[27], 2011),
            new Tretja.Nocitev(osebe[23], cilji[11], 2003),
            new Tretja.Nocitev(osebe[4], cilji[9], 2014),
            new Tretja.Nocitev(osebe[15], cilji[25], 2001),
            new Tretja.Nocitev(osebe[20], cilji[15], 2020),
            new Tretja.Nocitev(osebe[15], cilji[25], 2017),
            new Tretja.Nocitev(osebe[4], cilji[9], 2002),
            new Tretja.Nocitev(osebe[20], cilji[15], 2007),
            new Tretja.Nocitev(osebe[4], cilji[9], 2003),
            new Tretja.Nocitev(osebe[11], cilji[13], 2001),
            new Tretja.Nocitev(osebe[18], cilji[14], 2013),
            new Tretja.Nocitev(osebe[16], cilji[7], 2005),
            new Tretja.Nocitev(osebe[7], cilji[15], 2005),
            new Tretja.Nocitev(osebe[10], cilji[13], 2002),
            new Tretja.Nocitev(osebe[6], cilji[0], 2007),
            new Tretja.Nocitev(osebe[16], cilji[17], 2005),
            new Tretja.Nocitev(osebe[1], cilji[0], 2019),
            new Tretja.Nocitev(osebe[23], cilji[11], 2016),
            new Tretja.Nocitev(osebe[18], cilji[21], 2000),
            new Tretja.Nocitev(osebe[5], cilji[18], 2000),
            new Tretja.Nocitev(osebe[24], cilji[24], 2003),
            new Tretja.Nocitev(osebe[22], cilji[20], 2002),
            new Tretja.Nocitev(osebe[23], cilji[11], 2003),
            new Tretja.Nocitev(osebe[3], cilji[5], 2011),
            new Tretja.Nocitev(osebe[4], cilji[9], 2000),
            new Tretja.Nocitev(osebe[12], cilji[18], 2006),
            new Tretja.Nocitev(osebe[6], cilji[0], 2020),
            new Tretja.Nocitev(osebe[7], cilji[21], 2009),
            new Tretja.Nocitev(osebe[1], cilji[0], 2016),
            new Tretja.Nocitev(osebe[13], cilji[8], 2006),
            new Tretja.Nocitev(osebe[18], cilji[13], 2009),
            new Tretja.Nocitev(osebe[11], cilji[11], 2016),
            new Tretja.Nocitev(osebe[2], cilji[23], 2003),
            new Tretja.Nocitev(osebe[13], cilji[4], 2011),
            new Tretja.Nocitev(osebe[20], cilji[15], 2002),
            new Tretja.Nocitev(osebe[4], cilji[9], 2001),
            new Tretja.Nocitev(osebe[12], cilji[25], 2020),
            new Tretja.Nocitev(osebe[19], cilji[17], 2016),
            new Tretja.Nocitev(osebe[7], cilji[20], 2012),
            new Tretja.Nocitev(osebe[9], cilji[26], 2009),
            new Tretja.Nocitev(osebe[16], cilji[8], 2011),
            new Tretja.Nocitev(osebe[2], cilji[7], 2015),
            new Tretja.Nocitev(osebe[2], cilji[5], 2009),
            new Tretja.Nocitev(osebe[0], cilji[23], 2009),
            new Tretja.Nocitev(osebe[3], cilji[11], 2009),
            new Tretja.Nocitev(osebe[20], cilji[15], 2010),
            new Tretja.Nocitev(osebe[5], cilji[18], 2009),
            new Tretja.Nocitev(osebe[18], cilji[3], 2006),
            new Tretja.Nocitev(osebe[14], cilji[17], 2001),
            new Tretja.Nocitev(osebe[16], cilji[11], 2008),
            new Tretja.Nocitev(osebe[24], cilji[0], 2002),
            new Tretja.Nocitev(osebe[23], cilji[11], 2008),
            new Tretja.Nocitev(osebe[11], cilji[17], 2007),
            new Tretja.Nocitev(osebe[16], cilji[26], 2015),
            new Tretja.Nocitev(osebe[14], cilji[15], 2003),
            new Tretja.Nocitev(osebe[6], cilji[0], 2005),
            new Tretja.Nocitev(osebe[10], cilji[19], 2001),
            new Tretja.Nocitev(osebe[7], cilji[19], 2008),
            new Tretja.Nocitev(osebe[14], cilji[4], 2003),
            new Tretja.Nocitev(osebe[0], cilji[23], 2012),
            new Tretja.Nocitev(osebe[16], cilji[17], 2017),
            new Tretja.Nocitev(osebe[21], cilji[7], 2014),
            new Tretja.Nocitev(osebe[1], cilji[0], 2015),
            new Tretja.Nocitev(osebe[1], cilji[0], 2008),
            new Tretja.Nocitev(osebe[5], cilji[18], 2013),
            new Tretja.Nocitev(osebe[14], cilji[6], 2005),
            new Tretja.Nocitev(osebe[21], cilji[7], 2018),
            new Tretja.Nocitev(osebe[20], cilji[15], 2001),
            new Tretja.Nocitev(osebe[2], cilji[12], 2015),
            new Tretja.Nocitev(osebe[20], cilji[15], 2016),
            new Tretja.Nocitev(osebe[9], cilji[17], 2010),
            new Tretja.Nocitev(osebe[22], cilji[27], 2015),
            new Tretja.Nocitev(osebe[19], cilji[17], 2009),
            new Tretja.Nocitev(osebe[21], cilji[7], 2016),
            new Tretja.Nocitev(osebe[6], cilji[0], 2000),
            new Tretja.Nocitev(osebe[22], cilji[5], 2014),
            new Tretja.Nocitev(osebe[0], cilji[23], 2009),
            new Tretja.Nocitev(osebe[2], cilji[1], 2017),
            new Tretja.Nocitev(osebe[3], cilji[24], 2019),
            new Tretja.Nocitev(osebe[6], cilji[0], 2002),
            new Tretja.Nocitev(osebe[15], cilji[25], 2001),
            new Tretja.Nocitev(osebe[2], cilji[14], 2006),
            new Tretja.Nocitev(osebe[13], cilji[3], 2014),
            new Tretja.Nocitev(osebe[0], cilji[23], 2012),
            new Tretja.Nocitev(osebe[6], cilji[0], 2015),
            new Tretja.Nocitev(osebe[16], cilji[10], 2002),
            new Tretja.Nocitev(osebe[3], cilji[15], 2008),
            new Tretja.Nocitev(osebe[16], cilji[27], 2018),
            new Tretja.Nocitev(osebe[22], cilji[27], 2019),
            new Tretja.Nocitev(osebe[21], cilji[7], 2000),
            new Tretja.Nocitev(osebe[17], cilji[3], 2018),
            new Tretja.Nocitev(osebe[10], cilji[13], 2004),
            new Tretja.Nocitev(osebe[19], cilji[17], 2015),
            new Tretja.Nocitev(osebe[14], cilji[13], 2009),
            new Tretja.Nocitev(osebe[24], cilji[10], 2017),
            new Tretja.Nocitev(osebe[7], cilji[18], 2006),
            new Tretja.Nocitev(osebe[3], cilji[1], 2020),
            new Tretja.Nocitev(osebe[14], cilji[2], 2013),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
