
public class Test27 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Ubos Lace", "Pboc"),
            new Tretja.Oseba("Cmji Veri", "Pboc"),
            new Tretja.Oseba("Qcdn Cbds", "Sarq"),
            new Tretja.Oseba("Trko Rwxg", "Sarq"),
            new Tretja.Oseba("Ezag Fekl", "Tzmi"),
            new Tretja.Oseba("Iaao Kwad", "Tzmi"),
            new Tretja.Oseba("Iyyb Nyvt", "Pboc"),
            new Tretja.Oseba("Gbrj Ayny", "Tzmi"),
            new Tretja.Oseba("Zhry Somy", "Tzmi"),
            new Tretja.Oseba("Tzuo Dhma", "Tzmi"),
            new Tretja.Oseba("Hgzs Nltw", "Tzmi"),
            new Tretja.Oseba("Vpsu Rnzw", "Pboc"),
            new Tretja.Oseba("Gfco Qnrh", "Pboc"),
            new Tretja.Oseba("Biod Fwys", "Pboc"),
            new Tretja.Oseba("Rhpp Fogx", "Tzmi"),
            new Tretja.Oseba("Cqsp Blac", "Tzmi"),
            new Tretja.Oseba("Oyij Xhcm", "Pboc"),
            new Tretja.Oseba("Drlz Jjmi", "Sarq"),
            new Tretja.Oseba("Ymkh Yrqz", "Sarq"),
            new Tretja.Oseba("Eclb Csbb", "Sarq"),
            new Tretja.Oseba("Prtd Qosr", "Sarq"),
            new Tretja.Oseba("Hpey Jrq", "Tzmi"),
            new Tretja.Oseba("Zabl Gvnh", "Pboc"),
            new Tretja.Oseba("Sxqb Rzhs", "Pboc"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Laao", "Pboc"),
            new Tretja.Cilj("Zjpu", "Tzmi"),
            new Tretja.Cilj("Ncgl", "Sarq"),
            new Tretja.Cilj("Ccgt", "Pboc"),
            new Tretja.Cilj("Cyjk", "Tzmi"),
            new Tretja.Cilj("Niwo", "Tzmi"),
            new Tretja.Cilj("Zyag", "Pboc"),
            new Tretja.Cilj("Gtgr", "Tzmi"),
            new Tretja.Cilj("Kgxw", "Pboc"),
            new Tretja.Cilj("Dhql", "Pboc"),
            new Tretja.Cilj("Zrlm", "Tzmi"),
            new Tretja.Cilj("Bvlt", "Pboc"),
            new Tretja.Cilj("Lxue", "Tzmi"),
            new Tretja.Cilj("Jetd", "Pboc"),
            new Tretja.Cilj("Qana", "Tzmi"),
            new Tretja.Cilj("Vtwq", "Tzmi"),
            new Tretja.Cilj("Elry", "Sarq"),
            new Tretja.Cilj("Biul", "Pboc"),
            new Tretja.Cilj("Iuck", "Pboc"),
            new Tretja.Cilj("Fxvh", "Sarq"),
            new Tretja.Cilj("Glar", "Tzmi"),
            new Tretja.Cilj("Jjas", "Sarq"),
            new Tretja.Cilj("Dawa", "Pboc"),
            new Tretja.Cilj("Qvvf", "Sarq"),
            new Tretja.Cilj("Lnvm", "Sarq"),
            new Tretja.Cilj("Eoqa", "Sarq"),
            new Tretja.Cilj("Ludh", "Sarq"),
            new Tretja.Cilj("Bppb", "Tzmi"),
            new Tretja.Cilj("Jziu", "Pboc"),
            new Tretja.Cilj("Xzlu", "Tzmi"),
            new Tretja.Cilj("Pmsx", "Tzmi"),
            new Tretja.Cilj("Vnad", "Pboc"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[0], cilji[0], 2017),
            new Tretja.Nocitev(osebe[18], cilji[15], 2012),
            new Tretja.Nocitev(osebe[6], cilji[5], 2007),
            new Tretja.Nocitev(osebe[3], cilji[28], 2012),
            new Tretja.Nocitev(osebe[9], cilji[14], 2012),
            new Tretja.Nocitev(osebe[5], cilji[19], 2011),
            new Tretja.Nocitev(osebe[17], cilji[2], 2008),
            new Tretja.Nocitev(osebe[7], cilji[16], 2007),
            new Tretja.Nocitev(osebe[13], cilji[3], 2011),
            new Tretja.Nocitev(osebe[12], cilji[19], 2010),
            new Tretja.Nocitev(osebe[19], cilji[24], 2001),
            new Tretja.Nocitev(osebe[15], cilji[28], 2014),
            new Tretja.Nocitev(osebe[10], cilji[28], 2004),
            new Tretja.Nocitev(osebe[15], cilji[28], 2006),
            new Tretja.Nocitev(osebe[18], cilji[12], 2020),
            new Tretja.Nocitev(osebe[10], cilji[28], 2002),
            new Tretja.Nocitev(osebe[12], cilji[19], 2001),
            new Tretja.Nocitev(osebe[2], cilji[30], 2008),
            new Tretja.Nocitev(osebe[20], cilji[29], 2009),
            new Tretja.Nocitev(osebe[9], cilji[14], 2018),
            new Tretja.Nocitev(osebe[12], cilji[19], 2008),
            new Tretja.Nocitev(osebe[10], cilji[28], 2007),
            new Tretja.Nocitev(osebe[16], cilji[15], 2002),
            new Tretja.Nocitev(osebe[17], cilji[2], 2009),
            new Tretja.Nocitev(osebe[13], cilji[3], 2009),
            new Tretja.Nocitev(osebe[18], cilji[4], 2007),
            new Tretja.Nocitev(osebe[9], cilji[30], 2010),
            new Tretja.Nocitev(osebe[5], cilji[19], 2020),
            new Tretja.Nocitev(osebe[9], cilji[11], 2009),
            new Tretja.Nocitev(osebe[16], cilji[15], 2003),
            new Tretja.Nocitev(osebe[18], cilji[13], 2018),
            new Tretja.Nocitev(osebe[1], cilji[15], 2019),
            new Tretja.Nocitev(osebe[5], cilji[19], 2011),
            new Tretja.Nocitev(osebe[7], cilji[16], 2007),
            new Tretja.Nocitev(osebe[0], cilji[12], 2006),
            new Tretja.Nocitev(osebe[4], cilji[5], 2005),
            new Tretja.Nocitev(osebe[5], cilji[19], 2012),
            new Tretja.Nocitev(osebe[3], cilji[31], 2004),
            new Tretja.Nocitev(osebe[1], cilji[21], 2016),
            new Tretja.Nocitev(osebe[3], cilji[7], 2002),
            new Tretja.Nocitev(osebe[19], cilji[24], 2015),
            new Tretja.Nocitev(osebe[12], cilji[19], 2000),
            new Tretja.Nocitev(osebe[8], cilji[19], 2009),
            new Tretja.Nocitev(osebe[0], cilji[29], 2020),
            new Tretja.Nocitev(osebe[10], cilji[28], 2001),
            new Tretja.Nocitev(osebe[23], cilji[23], 2003),
            new Tretja.Nocitev(osebe[18], cilji[27], 2015),
            new Tretja.Nocitev(osebe[7], cilji[16], 2012),
            new Tretja.Nocitev(osebe[17], cilji[2], 2017),
            new Tretja.Nocitev(osebe[21], cilji[4], 2006),
            new Tretja.Nocitev(osebe[22], cilji[17], 2018),
            new Tretja.Nocitev(osebe[23], cilji[22], 2005),
            new Tretja.Nocitev(osebe[9], cilji[6], 2014),
            new Tretja.Nocitev(osebe[20], cilji[1], 2006),
            new Tretja.Nocitev(osebe[5], cilji[19], 2000),
            new Tretja.Nocitev(osebe[12], cilji[19], 2007),
            new Tretja.Nocitev(osebe[3], cilji[14], 2019),
            new Tretja.Nocitev(osebe[4], cilji[30], 2000),
            new Tretja.Nocitev(osebe[4], cilji[8], 2018),
            new Tretja.Nocitev(osebe[11], cilji[14], 2019),
            new Tretja.Nocitev(osebe[4], cilji[22], 2020),
            new Tretja.Nocitev(osebe[19], cilji[24], 2006),
            new Tretja.Nocitev(osebe[23], cilji[15], 2004),
            new Tretja.Nocitev(osebe[0], cilji[4], 2018),
            new Tretja.Nocitev(osebe[23], cilji[13], 2008),
            new Tretja.Nocitev(osebe[20], cilji[8], 2020),
            new Tretja.Nocitev(osebe[10], cilji[28], 2013),
            new Tretja.Nocitev(osebe[12], cilji[19], 2013),
            new Tretja.Nocitev(osebe[14], cilji[12], 2003),
            new Tretja.Nocitev(osebe[2], cilji[30], 2002),
            new Tretja.Nocitev(osebe[2], cilji[30], 2001),
            new Tretja.Nocitev(osebe[13], cilji[3], 2008),
            new Tretja.Nocitev(osebe[15], cilji[28], 2002),
            new Tretja.Nocitev(osebe[8], cilji[19], 2004),
            new Tretja.Nocitev(osebe[12], cilji[19], 2002),
            new Tretja.Nocitev(osebe[16], cilji[15], 2014),
            new Tretja.Nocitev(osebe[17], cilji[2], 2006),
            new Tretja.Nocitev(osebe[14], cilji[12], 2013),
            new Tretja.Nocitev(osebe[5], cilji[19], 2019),
            new Tretja.Nocitev(osebe[17], cilji[2], 2007),
            new Tretja.Nocitev(osebe[7], cilji[16], 2005),
            new Tretja.Nocitev(osebe[8], cilji[19], 2015),
            new Tretja.Nocitev(osebe[1], cilji[5], 2018),
            new Tretja.Nocitev(osebe[4], cilji[30], 2017),
            new Tretja.Nocitev(osebe[20], cilji[4], 2019),
            new Tretja.Nocitev(osebe[4], cilji[16], 2010),
            new Tretja.Nocitev(osebe[12], cilji[19], 2007),
            new Tretja.Nocitev(osebe[4], cilji[1], 2019),
            new Tretja.Nocitev(osebe[3], cilji[13], 2018),
            new Tretja.Nocitev(osebe[9], cilji[29], 2003),
            new Tretja.Nocitev(osebe[1], cilji[0], 2007),
            new Tretja.Nocitev(osebe[0], cilji[25], 2017),
            new Tretja.Nocitev(osebe[14], cilji[5], 2002),
            new Tretja.Nocitev(osebe[14], cilji[4], 2016),
            new Tretja.Nocitev(osebe[2], cilji[30], 2011),
            new Tretja.Nocitev(osebe[2], cilji[30], 2001),
            new Tretja.Nocitev(osebe[21], cilji[14], 2000),
            new Tretja.Nocitev(osebe[0], cilji[0], 2011),
            new Tretja.Nocitev(osebe[15], cilji[28], 2007),
            new Tretja.Nocitev(osebe[22], cilji[6], 2010),
            new Tretja.Nocitev(osebe[17], cilji[2], 2020),
            new Tretja.Nocitev(osebe[23], cilji[14], 2015),
            new Tretja.Nocitev(osebe[15], cilji[28], 2005),
            new Tretja.Nocitev(osebe[21], cilji[23], 2016),
            new Tretja.Nocitev(osebe[16], cilji[15], 2011),
            new Tretja.Nocitev(osebe[7], cilji[16], 2020),
            new Tretja.Nocitev(osebe[0], cilji[9], 2006),
            new Tretja.Nocitev(osebe[22], cilji[27], 2003),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
