
public class Test05 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Hifu Mlwq", "Xfae"),
            new Tretja.Oseba("Iksm Wmvb", "Chlk"),
            new Tretja.Oseba("Xyct Bbdu", "Xfae"),
            new Tretja.Oseba("Guik Tkhm", "Xfae"),
            new Tretja.Oseba("Uejq Sfho", "Xfae"),
            new Tretja.Oseba("Zit Hwtr", "Xfae"),
            new Tretja.Oseba("Onqx Pjxw", "Xfae"),
            new Tretja.Oseba("Smef Wbat", "Chlk"),
            new Tretja.Oseba("Vrte Vnam", "Xfae"),
            new Tretja.Oseba("Rvos Ogvt", "Xfae"),
            new Tretja.Oseba("Qhpx Uptd", "Xfae"),
            new Tretja.Oseba("Zvsr Mvms", "Xfae"),
            new Tretja.Oseba("Susb Zssl", "Xfae"),
            new Tretja.Oseba("Bbsy Nqtx", "Xfae"),
            new Tretja.Oseba("Vlha Khxf", "Xfae"),
            new Tretja.Oseba("Kyip Rkdt", "Chlk"),
            new Tretja.Oseba("Read Qojc", "Chlk"),
            new Tretja.Oseba("Zxot Jonw", "Xfae"),
            new Tretja.Oseba("Slvd Nllx", "Chlk"),
            new Tretja.Oseba("Igvk Okpf", "Chlk"),
            new Tretja.Oseba("Dzmr Xhfo", "Xfae"),
            new Tretja.Oseba("Vcqa Ctru", "Chlk"),
            new Tretja.Oseba("Wvpm Ndjl", "Xfae"),
            new Tretja.Oseba("Wlmz Cxyw", "Chlk"),
            new Tretja.Oseba("Puhs Ldby", "Chlk"),
            new Tretja.Oseba("Qfvy Fnji", "Chlk"),
            new Tretja.Oseba("Qgkd Mtja", "Chlk"),
            new Tretja.Oseba("Awxe Cbzb", "Chlk"),
            new Tretja.Oseba("Lwyn Yhli", "Xfae"),
            new Tretja.Oseba("Wwkx Jaql", "Xfae"),
            new Tretja.Oseba("Evqs Mgkb", "Chlk"),
            new Tretja.Oseba("Hlns Urjk", "Chlk"),
            new Tretja.Oseba("Ailu Ibuu", "Chlk"),
            new Tretja.Oseba("Empi Uspc", "Chlk"),
            new Tretja.Oseba("Rouv Tbkg", "Xfae"),
            new Tretja.Oseba("Vbwj Anio", "Xfae"),
            new Tretja.Oseba("Tjpf Jknk", "Xfae"),
            new Tretja.Oseba("Dpsi Tgeu", "Xfae"),
            new Tretja.Oseba("Rguj Cbqw", "Xfae"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Cqch", "Xfae"),
            new Tretja.Cilj("Sylj", "Xfae"),
            new Tretja.Cilj("Wekl", "Chlk"),
            new Tretja.Cilj("Rrkp", "Chlk"),
            new Tretja.Cilj("Ssyu", "Xfae"),
            new Tretja.Cilj("Qdio", "Chlk"),
            new Tretja.Cilj("Wtvc", "Chlk"),
            new Tretja.Cilj("Plux", "Chlk"),
            new Tretja.Cilj("Bpgo", "Xfae"),
            new Tretja.Cilj("Crzp", "Xfae"),
            new Tretja.Cilj("Jknn", "Chlk"),
            new Tretja.Cilj("Vqre", "Chlk"),
            new Tretja.Cilj("Atwk", "Chlk"),
            new Tretja.Cilj("Lphp", "Xfae"),
            new Tretja.Cilj("Zzwg", "Chlk"),
            new Tretja.Cilj("Yajt", "Xfae"),
            new Tretja.Cilj("Rxkv", "Chlk"),
            new Tretja.Cilj("Nfds", "Xfae"),
            new Tretja.Cilj("Mhrs", "Chlk"),
            new Tretja.Cilj("Artu", "Xfae"),
            new Tretja.Cilj("Msjh", "Xfae"),
            new Tretja.Cilj("Yemn", "Xfae"),
            new Tretja.Cilj("Asyd", "Xfae"),
            new Tretja.Cilj("Wkei", "Xfae"),
            new Tretja.Cilj("Ihzl", "Chlk"),
            new Tretja.Cilj("Owoc", "Xfae"),
            new Tretja.Cilj("Dbfz", "Xfae"),
            new Tretja.Cilj("Vwed", "Chlk"),
            new Tretja.Cilj("Nums", "Chlk"),
            new Tretja.Cilj("Bjov", "Chlk"),
            new Tretja.Cilj("Qkia", "Chlk"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[24], cilji[24], 2006),
            new Tretja.Nocitev(osebe[8], cilji[29], 2018),
            new Tretja.Nocitev(osebe[8], cilji[29], 2006),
            new Tretja.Nocitev(osebe[6], cilji[17], 2000),
            new Tretja.Nocitev(osebe[28], cilji[3], 2002),
            new Tretja.Nocitev(osebe[21], cilji[23], 2011),
            new Tretja.Nocitev(osebe[32], cilji[21], 2012),
            new Tretja.Nocitev(osebe[23], cilji[11], 2005),
            new Tretja.Nocitev(osebe[16], cilji[22], 2014),
            new Tretja.Nocitev(osebe[35], cilji[28], 2019),
            new Tretja.Nocitev(osebe[26], cilji[0], 2018),
            new Tretja.Nocitev(osebe[21], cilji[24], 2019),
            new Tretja.Nocitev(osebe[17], cilji[15], 2015),
            new Tretja.Nocitev(osebe[23], cilji[22], 2018),
            new Tretja.Nocitev(osebe[19], cilji[29], 2003),
            new Tretja.Nocitev(osebe[8], cilji[29], 2006),
            new Tretja.Nocitev(osebe[38], cilji[14], 2017),
            new Tretja.Nocitev(osebe[32], cilji[21], 2009),
            new Tretja.Nocitev(osebe[1], cilji[22], 2007),
            new Tretja.Nocitev(osebe[23], cilji[27], 2007),
            new Tretja.Nocitev(osebe[12], cilji[13], 2012),
            new Tretja.Nocitev(osebe[15], cilji[26], 2019),
            new Tretja.Nocitev(osebe[32], cilji[21], 2004),
            new Tretja.Nocitev(osebe[34], cilji[9], 2020),
            new Tretja.Nocitev(osebe[10], cilji[22], 2012),
            new Tretja.Nocitev(osebe[8], cilji[29], 2003),
            new Tretja.Nocitev(osebe[38], cilji[0], 2001),
            new Tretja.Nocitev(osebe[19], cilji[29], 2019),
            new Tretja.Nocitev(osebe[29], cilji[17], 2016),
            new Tretja.Nocitev(osebe[10], cilji[5], 2008),
            new Tretja.Nocitev(osebe[1], cilji[22], 2009),
            new Tretja.Nocitev(osebe[6], cilji[17], 2008),
            new Tretja.Nocitev(osebe[0], cilji[18], 2007),
            new Tretja.Nocitev(osebe[29], cilji[17], 2005),
            new Tretja.Nocitev(osebe[30], cilji[15], 2007),
            new Tretja.Nocitev(osebe[2], cilji[23], 2007),
            new Tretja.Nocitev(osebe[26], cilji[1], 2005),
            new Tretja.Nocitev(osebe[28], cilji[17], 2001),
            new Tretja.Nocitev(osebe[1], cilji[22], 2015),
            new Tretja.Nocitev(osebe[19], cilji[29], 2020),
            new Tretja.Nocitev(osebe[27], cilji[27], 2007),
            new Tretja.Nocitev(osebe[11], cilji[21], 2007),
            new Tretja.Nocitev(osebe[22], cilji[27], 2002),
            new Tretja.Nocitev(osebe[34], cilji[9], 2011),
            new Tretja.Nocitev(osebe[14], cilji[1], 2004),
            new Tretja.Nocitev(osebe[11], cilji[21], 2002),
            new Tretja.Nocitev(osebe[29], cilji[17], 2000),
            new Tretja.Nocitev(osebe[38], cilji[8], 2019),
            new Tretja.Nocitev(osebe[37], cilji[29], 2019),
            new Tretja.Nocitev(osebe[4], cilji[4], 2001),
            new Tretja.Nocitev(osebe[24], cilji[24], 2010),
            new Tretja.Nocitev(osebe[33], cilji[27], 2020),
            new Tretja.Nocitev(osebe[31], cilji[5], 2001),
            new Tretja.Nocitev(osebe[27], cilji[27], 2015),
            new Tretja.Nocitev(osebe[25], cilji[3], 2004),
            new Tretja.Nocitev(osebe[16], cilji[22], 2013),
            new Tretja.Nocitev(osebe[1], cilji[22], 2011),
            new Tretja.Nocitev(osebe[33], cilji[19], 2019),
            new Tretja.Nocitev(osebe[14], cilji[11], 2011),
            new Tretja.Nocitev(osebe[23], cilji[5], 2011),
            new Tretja.Nocitev(osebe[5], cilji[21], 2008),
            new Tretja.Nocitev(osebe[28], cilji[20], 2019),
            new Tretja.Nocitev(osebe[23], cilji[17], 2013),
            new Tretja.Nocitev(osebe[9], cilji[9], 2003),
            new Tretja.Nocitev(osebe[23], cilji[22], 2015),
            new Tretja.Nocitev(osebe[12], cilji[0], 2005),
            new Tretja.Nocitev(osebe[26], cilji[4], 2016),
            new Tretja.Nocitev(osebe[17], cilji[21], 2017),
            new Tretja.Nocitev(osebe[37], cilji[29], 2003),
            new Tretja.Nocitev(osebe[6], cilji[17], 2014),
            new Tretja.Nocitev(osebe[17], cilji[22], 2002),
            new Tretja.Nocitev(osebe[13], cilji[14], 2000),
            new Tretja.Nocitev(osebe[9], cilji[9], 2019),
            new Tretja.Nocitev(osebe[22], cilji[5], 2007),
            new Tretja.Nocitev(osebe[16], cilji[22], 2001),
            new Tretja.Nocitev(osebe[28], cilji[5], 2001),
            new Tretja.Nocitev(osebe[2], cilji[23], 2003),
            new Tretja.Nocitev(osebe[4], cilji[4], 2005),
            new Tretja.Nocitev(osebe[19], cilji[29], 2011),
            new Tretja.Nocitev(osebe[0], cilji[29], 2017),
            new Tretja.Nocitev(osebe[7], cilji[6], 2000),
            new Tretja.Nocitev(osebe[36], cilji[16], 2005),
            new Tretja.Nocitev(osebe[2], cilji[23], 2019),
            new Tretja.Nocitev(osebe[22], cilji[11], 2019),
            new Tretja.Nocitev(osebe[26], cilji[12], 2020),
            new Tretja.Nocitev(osebe[29], cilji[17], 2013),
            new Tretja.Nocitev(osebe[30], cilji[0], 2006),
            new Tretja.Nocitev(osebe[18], cilji[22], 2009),
            new Tretja.Nocitev(osebe[13], cilji[25], 2003),
            new Tretja.Nocitev(osebe[38], cilji[17], 2001),
            new Tretja.Nocitev(osebe[31], cilji[5], 2013),
            new Tretja.Nocitev(osebe[2], cilji[23], 2001),
            new Tretja.Nocitev(osebe[4], cilji[4], 2014),
            new Tretja.Nocitev(osebe[32], cilji[21], 2015),
            new Tretja.Nocitev(osebe[1], cilji[22], 2006),
            new Tretja.Nocitev(osebe[30], cilji[5], 2018),
            new Tretja.Nocitev(osebe[26], cilji[1], 2001),
            new Tretja.Nocitev(osebe[4], cilji[4], 2008),
            new Tretja.Nocitev(osebe[0], cilji[16], 2018),
            new Tretja.Nocitev(osebe[38], cilji[11], 2014),
            new Tretja.Nocitev(osebe[33], cilji[19], 2016),
            new Tretja.Nocitev(osebe[31], cilji[5], 2008),
            new Tretja.Nocitev(osebe[9], cilji[9], 2016),
            new Tretja.Nocitev(osebe[7], cilji[12], 2009),
            new Tretja.Nocitev(osebe[23], cilji[16], 2008),
            new Tretja.Nocitev(osebe[18], cilji[25], 2002),
            new Tretja.Nocitev(osebe[0], cilji[24], 2010),
            new Tretja.Nocitev(osebe[36], cilji[16], 2015),
            new Tretja.Nocitev(osebe[4], cilji[4], 2014),
            new Tretja.Nocitev(osebe[36], cilji[16], 2014),
            new Tretja.Nocitev(osebe[20], cilji[22], 2019),
            new Tretja.Nocitev(osebe[14], cilji[19], 2003),
            new Tretja.Nocitev(osebe[18], cilji[10], 2007),
            new Tretja.Nocitev(osebe[10], cilji[9], 2014),
            new Tretja.Nocitev(osebe[20], cilji[22], 2002),
            new Tretja.Nocitev(osebe[26], cilji[13], 2016),
            new Tretja.Nocitev(osebe[8], cilji[29], 2001),
            new Tretja.Nocitev(osebe[12], cilji[10], 2007),
            new Tretja.Nocitev(osebe[17], cilji[27], 2008),
            new Tretja.Nocitev(osebe[35], cilji[24], 2018),
            new Tretja.Nocitev(osebe[29], cilji[17], 2000),
            new Tretja.Nocitev(osebe[28], cilji[29], 2004),
            new Tretja.Nocitev(osebe[33], cilji[20], 2008),
            new Tretja.Nocitev(osebe[23], cilji[3], 2014),
            new Tretja.Nocitev(osebe[35], cilji[29], 2014),
            new Tretja.Nocitev(osebe[13], cilji[2], 2017),
            new Tretja.Nocitev(osebe[36], cilji[16], 2011),
            new Tretja.Nocitev(osebe[35], cilji[6], 2010),
            new Tretja.Nocitev(osebe[13], cilji[1], 2001),
            new Tretja.Nocitev(osebe[2], cilji[23], 2008),
            new Tretja.Nocitev(osebe[29], cilji[17], 2011),
            new Tretja.Nocitev(osebe[13], cilji[3], 2013),
            new Tretja.Nocitev(osebe[30], cilji[29], 2012),
            new Tretja.Nocitev(osebe[23], cilji[22], 2006),
            new Tretja.Nocitev(osebe[15], cilji[14], 2000),
            new Tretja.Nocitev(osebe[25], cilji[3], 2000),
            new Tretja.Nocitev(osebe[2], cilji[23], 2012),
            new Tretja.Nocitev(osebe[30], cilji[11], 2001),
            new Tretja.Nocitev(osebe[37], cilji[29], 2017),
            new Tretja.Nocitev(osebe[35], cilji[4], 2004),
            new Tretja.Nocitev(osebe[29], cilji[17], 2020),
            new Tretja.Nocitev(osebe[4], cilji[4], 2008),
            new Tretja.Nocitev(osebe[23], cilji[1], 2015),
            new Tretja.Nocitev(osebe[5], cilji[6], 2006),
            new Tretja.Nocitev(osebe[5], cilji[28], 2009),
            new Tretja.Nocitev(osebe[10], cilji[11], 2001),
            new Tretja.Nocitev(osebe[19], cilji[29], 2001),
            new Tretja.Nocitev(osebe[12], cilji[6], 2011),
            new Tretja.Nocitev(osebe[14], cilji[24], 2012),
            new Tretja.Nocitev(osebe[32], cilji[21], 2006),
            new Tretja.Nocitev(osebe[38], cilji[12], 2003),
            new Tretja.Nocitev(osebe[27], cilji[27], 2020),
            new Tretja.Nocitev(osebe[13], cilji[0], 2009),
            new Tretja.Nocitev(osebe[30], cilji[2], 2018),
            new Tretja.Nocitev(osebe[17], cilji[0], 2001),
            new Tretja.Nocitev(osebe[22], cilji[28], 2010),
            new Tretja.Nocitev(osebe[13], cilji[12], 2002),
            new Tretja.Nocitev(osebe[33], cilji[27], 2002),
            new Tretja.Nocitev(osebe[16], cilji[22], 2007),
            new Tretja.Nocitev(osebe[35], cilji[0], 2006),
            new Tretja.Nocitev(osebe[27], cilji[27], 2005),
            new Tretja.Nocitev(osebe[4], cilji[4], 2016),
            new Tretja.Nocitev(osebe[37], cilji[29], 2007),
            new Tretja.Nocitev(osebe[38], cilji[17], 2007),
            new Tretja.Nocitev(osebe[35], cilji[12], 2010),
            new Tretja.Nocitev(osebe[29], cilji[17], 2002),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
