
public class Test33 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Eaan Lwup", "Pwjz"),
            new Tretja.Oseba("Kupn Zdqj", "Bymo"),
            new Tretja.Oseba("Yaey Wywi", "Pwjz"),
            new Tretja.Oseba("Xsdn Fq", "Bymo"),
            new Tretja.Oseba("Fpfu Yhng", "Pwjz"),
            new Tretja.Oseba("Csgr Aaax", "Pwjz"),
            new Tretja.Oseba("Rdrv Nedy", "Bymo"),
            new Tretja.Oseba("Ngjv Ntwc", "Rihz"),
            new Tretja.Oseba("Zupq Uxdw", "Rihz"),
            new Tretja.Oseba("Cvgx Uwib", "Bymo"),
            new Tretja.Oseba("Xhpw Klhd", "Pwjz"),
            new Tretja.Oseba("Snyg Ismv", "Pwjz"),
            new Tretja.Oseba("Htlt Karc", "Bymo"),
            new Tretja.Oseba("Wtsy Exzg", "Rihz"),
            new Tretja.Oseba("Nxku Behb", "Rihz"),
            new Tretja.Oseba("Hqkg Eezq", "Rihz"),
            new Tretja.Oseba("Wnxe Hnmk", "Rihz"),
            new Tretja.Oseba("Zbbi Fqqj", "Pwjz"),
            new Tretja.Oseba("Qxda Klyw", "Bymo"),
            new Tretja.Oseba("Dhui Bxir", "Bymo"),
            new Tretja.Oseba("Hwse Smdh", "Rihz"),
            new Tretja.Oseba("Zgsb Ialp", "Bymo"),
            new Tretja.Oseba("Xevu Fjwp", "Bymo"),
            new Tretja.Oseba("Upys Dhnn", "Bymo"),
            new Tretja.Oseba("Odwy Xqqv", "Pwjz"),
            new Tretja.Oseba("Htri Wyfd", "Pwjz"),
            new Tretja.Oseba("Odh Fouu", "Pwjz"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Cmkn", "Bymo"),
            new Tretja.Cilj("Hlgz", "Rihz"),
            new Tretja.Cilj("Bluj", "Rihz"),
            new Tretja.Cilj("Ihty", "Pwjz"),
            new Tretja.Cilj("Nwam", "Bymo"),
            new Tretja.Cilj("Bsah", "Rihz"),
            new Tretja.Cilj("Ciqm", "Rihz"),
            new Tretja.Cilj("Ilyj", "Rihz"),
            new Tretja.Cilj("Psiu", "Pwjz"),
            new Tretja.Cilj("Xaui", "Bymo"),
            new Tretja.Cilj("Kaue", "Rihz"),
            new Tretja.Cilj("Urjg", "Rihz"),
            new Tretja.Cilj("Ueoh", "Rihz"),
            new Tretja.Cilj("Edvx", "Bymo"),
            new Tretja.Cilj("Xovd", "Rihz"),
            new Tretja.Cilj("Rjqp", "Rihz"),
            new Tretja.Cilj("Hxro", "Pwjz"),
            new Tretja.Cilj("Vygd", "Pwjz"),
            new Tretja.Cilj("Kdv", "Pwjz"),
            new Tretja.Cilj("Hlwg", "Rihz"),
            new Tretja.Cilj("Aebg", "Rihz"),
            new Tretja.Cilj("Bgba", "Bymo"),
            new Tretja.Cilj("Ejlq", "Rihz"),
            new Tretja.Cilj("Eaxg", "Pwjz"),
            new Tretja.Cilj("Rkjj", "Bymo"),
            new Tretja.Cilj("Aomd", "Bymo"),
            new Tretja.Cilj("Uqkz", "Pwjz"),
            new Tretja.Cilj("Uzye", "Rihz"),
            new Tretja.Cilj("Dsdz", "Rihz"),
            new Tretja.Cilj("Lbha", "Pwjz"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[3], cilji[16], 2007),
            new Tretja.Nocitev(osebe[6], cilji[7], 2006),
            new Tretja.Nocitev(osebe[13], cilji[0], 2016),
            new Tretja.Nocitev(osebe[0], cilji[4], 2010),
            new Tretja.Nocitev(osebe[0], cilji[6], 2006),
            new Tretja.Nocitev(osebe[25], cilji[14], 2000),
            new Tretja.Nocitev(osebe[1], cilji[4], 2005),
            new Tretja.Nocitev(osebe[17], cilji[6], 2013),
            new Tretja.Nocitev(osebe[8], cilji[27], 2014),
            new Tretja.Nocitev(osebe[12], cilji[18], 2016),
            new Tretja.Nocitev(osebe[7], cilji[27], 2004),
            new Tretja.Nocitev(osebe[11], cilji[0], 2016),
            new Tretja.Nocitev(osebe[3], cilji[16], 2003),
            new Tretja.Nocitev(osebe[1], cilji[17], 2012),
            new Tretja.Nocitev(osebe[7], cilji[12], 2011),
            new Tretja.Nocitev(osebe[19], cilji[2], 2018),
            new Tretja.Nocitev(osebe[7], cilji[2], 2004),
            new Tretja.Nocitev(osebe[9], cilji[1], 2007),
            new Tretja.Nocitev(osebe[11], cilji[2], 2020),
            new Tretja.Nocitev(osebe[6], cilji[7], 2013),
            new Tretja.Nocitev(osebe[20], cilji[28], 2002),
            new Tretja.Nocitev(osebe[13], cilji[0], 2017),
            new Tretja.Nocitev(osebe[23], cilji[27], 2020),
            new Tretja.Nocitev(osebe[16], cilji[28], 2000),
            new Tretja.Nocitev(osebe[11], cilji[10], 2020),
            new Tretja.Nocitev(osebe[22], cilji[10], 2015),
            new Tretja.Nocitev(osebe[1], cilji[23], 2008),
            new Tretja.Nocitev(osebe[10], cilji[13], 2002),
            new Tretja.Nocitev(osebe[25], cilji[14], 2011),
            new Tretja.Nocitev(osebe[21], cilji[14], 2009),
            new Tretja.Nocitev(osebe[11], cilji[11], 2011),
            new Tretja.Nocitev(osebe[0], cilji[11], 2016),
            new Tretja.Nocitev(osebe[26], cilji[2], 2003),
            new Tretja.Nocitev(osebe[14], cilji[24], 2003),
            new Tretja.Nocitev(osebe[2], cilji[15], 2018),
            new Tretja.Nocitev(osebe[3], cilji[16], 2019),
            new Tretja.Nocitev(osebe[4], cilji[27], 2013),
            new Tretja.Nocitev(osebe[15], cilji[8], 2009),
            new Tretja.Nocitev(osebe[10], cilji[13], 2001),
            new Tretja.Nocitev(osebe[2], cilji[15], 2012),
            new Tretja.Nocitev(osebe[26], cilji[2], 2006),
            new Tretja.Nocitev(osebe[5], cilji[26], 2004),
            new Tretja.Nocitev(osebe[17], cilji[1], 2008),
            new Tretja.Nocitev(osebe[13], cilji[0], 2002),
            new Tretja.Nocitev(osebe[21], cilji[14], 2000),
            new Tretja.Nocitev(osebe[9], cilji[25], 2009),
            new Tretja.Nocitev(osebe[4], cilji[16], 2002),
            new Tretja.Nocitev(osebe[2], cilji[15], 2011),
            new Tretja.Nocitev(osebe[20], cilji[8], 2000),
            new Tretja.Nocitev(osebe[25], cilji[14], 2007),
            new Tretja.Nocitev(osebe[23], cilji[28], 2002),
            new Tretja.Nocitev(osebe[14], cilji[24], 2016),
            new Tretja.Nocitev(osebe[1], cilji[6], 2017),
            new Tretja.Nocitev(osebe[12], cilji[7], 2009),
            new Tretja.Nocitev(osebe[4], cilji[16], 2016),
            new Tretja.Nocitev(osebe[20], cilji[11], 2000),
            new Tretja.Nocitev(osebe[0], cilji[2], 2013),
            new Tretja.Nocitev(osebe[18], cilji[11], 2001),
            new Tretja.Nocitev(osebe[23], cilji[29], 2000),
            new Tretja.Nocitev(osebe[4], cilji[16], 2015),
            new Tretja.Nocitev(osebe[12], cilji[23], 2009),
            new Tretja.Nocitev(osebe[1], cilji[29], 2016),
            new Tretja.Nocitev(osebe[16], cilji[16], 2012),
            new Tretja.Nocitev(osebe[22], cilji[2], 2013),
            new Tretja.Nocitev(osebe[19], cilji[2], 2010),
            new Tretja.Nocitev(osebe[10], cilji[13], 2008),
            new Tretja.Nocitev(osebe[4], cilji[5], 2006),
            new Tretja.Nocitev(osebe[9], cilji[22], 2002),
            new Tretja.Nocitev(osebe[7], cilji[13], 2000),
            new Tretja.Nocitev(osebe[0], cilji[8], 2017),
            new Tretja.Nocitev(osebe[12], cilji[28], 2009),
            new Tretja.Nocitev(osebe[12], cilji[25], 2002),
            new Tretja.Nocitev(osebe[19], cilji[2], 2004),
            new Tretja.Nocitev(osebe[0], cilji[15], 2001),
            new Tretja.Nocitev(osebe[7], cilji[24], 2020),
            new Tretja.Nocitev(osebe[0], cilji[18], 2009),
            new Tretja.Nocitev(osebe[2], cilji[15], 2016),
            new Tretja.Nocitev(osebe[15], cilji[23], 2000),
            new Tretja.Nocitev(osebe[23], cilji[11], 2004),
            new Tretja.Nocitev(osebe[16], cilji[18], 2016),
            new Tretja.Nocitev(osebe[5], cilji[26], 2004),
            new Tretja.Nocitev(osebe[14], cilji[24], 2007),
            new Tretja.Nocitev(osebe[17], cilji[17], 2007),
            new Tretja.Nocitev(osebe[14], cilji[24], 2011),
            new Tretja.Nocitev(osebe[20], cilji[1], 2003),
            new Tretja.Nocitev(osebe[10], cilji[13], 2010),
            new Tretja.Nocitev(osebe[17], cilji[5], 2007),
            new Tretja.Nocitev(osebe[17], cilji[15], 2013),
            new Tretja.Nocitev(osebe[21], cilji[14], 2004),
            new Tretja.Nocitev(osebe[10], cilji[13], 2018),
            new Tretja.Nocitev(osebe[13], cilji[0], 2017),
            new Tretja.Nocitev(osebe[13], cilji[0], 2015),
            new Tretja.Nocitev(osebe[7], cilji[29], 2011),
            new Tretja.Nocitev(osebe[11], cilji[11], 2001),
            new Tretja.Nocitev(osebe[24], cilji[22], 2002),
            new Tretja.Nocitev(osebe[3], cilji[16], 2011),
            new Tretja.Nocitev(osebe[20], cilji[14], 2000),
            new Tretja.Nocitev(osebe[22], cilji[22], 2009),
            new Tretja.Nocitev(osebe[9], cilji[1], 2009),
            new Tretja.Nocitev(osebe[9], cilji[25], 2013),
            new Tretja.Nocitev(osebe[19], cilji[2], 2011),
            new Tretja.Nocitev(osebe[8], cilji[27], 2000),
            new Tretja.Nocitev(osebe[16], cilji[15], 2007),
            new Tretja.Nocitev(osebe[4], cilji[16], 2013),
            new Tretja.Nocitev(osebe[7], cilji[26], 2019),
            new Tretja.Nocitev(osebe[3], cilji[16], 2005),
            new Tretja.Nocitev(osebe[20], cilji[2], 2002),
            new Tretja.Nocitev(osebe[16], cilji[11], 2000),
            new Tretja.Nocitev(osebe[20], cilji[13], 2008),
            new Tretja.Nocitev(osebe[2], cilji[15], 2004),
            new Tretja.Nocitev(osebe[8], cilji[27], 2019),
            new Tretja.Nocitev(osebe[4], cilji[2], 2001),
            new Tretja.Nocitev(osebe[21], cilji[14], 2020),
            new Tretja.Nocitev(osebe[12], cilji[1], 2007),
            new Tretja.Nocitev(osebe[22], cilji[6], 2015),
            new Tretja.Nocitev(osebe[15], cilji[13], 2010),
            new Tretja.Nocitev(osebe[2], cilji[15], 2014),
            new Tretja.Nocitev(osebe[10], cilji[13], 2014),
            new Tretja.Nocitev(osebe[22], cilji[28], 2012),
            new Tretja.Nocitev(osebe[15], cilji[1], 2018),
            new Tretja.Nocitev(osebe[5], cilji[26], 2002),
            new Tretja.Nocitev(osebe[7], cilji[5], 2002),
            new Tretja.Nocitev(osebe[15], cilji[23], 2008),
            new Tretja.Nocitev(osebe[18], cilji[11], 2016),
            new Tretja.Nocitev(osebe[14], cilji[24], 2006),
            new Tretja.Nocitev(osebe[24], cilji[15], 2020),
            new Tretja.Nocitev(osebe[25], cilji[14], 2015),
            new Tretja.Nocitev(osebe[3], cilji[16], 2017),
            new Tretja.Nocitev(osebe[9], cilji[19], 2008),
            new Tretja.Nocitev(osebe[5], cilji[26], 2012),
            new Tretja.Nocitev(osebe[23], cilji[9], 2003),
            new Tretja.Nocitev(osebe[19], cilji[2], 2013),
            new Tretja.Nocitev(osebe[23], cilji[15], 2008),
            new Tretja.Nocitev(osebe[1], cilji[7], 2017),
            new Tretja.Nocitev(osebe[14], cilji[24], 2010),
            new Tretja.Nocitev(osebe[18], cilji[11], 2018),
            new Tretja.Nocitev(osebe[1], cilji[24], 2012),
            new Tretja.Nocitev(osebe[12], cilji[4], 2016),
            new Tretja.Nocitev(osebe[26], cilji[2], 2008),
            new Tretja.Nocitev(osebe[20], cilji[7], 2011),
            new Tretja.Nocitev(osebe[17], cilji[0], 2011),
            new Tretja.Nocitev(osebe[9], cilji[15], 2004),
            new Tretja.Nocitev(osebe[11], cilji[25], 2003),
            new Tretja.Nocitev(osebe[25], cilji[14], 2015),
            new Tretja.Nocitev(osebe[15], cilji[19], 2013),
            new Tretja.Nocitev(osebe[18], cilji[11], 2005),
            new Tretja.Nocitev(osebe[20], cilji[14], 2000),
            new Tretja.Nocitev(osebe[24], cilji[10], 2003),
            new Tretja.Nocitev(osebe[3], cilji[16], 2010),
            new Tretja.Nocitev(osebe[13], cilji[0], 2011),
            new Tretja.Nocitev(osebe[18], cilji[11], 2008),
            new Tretja.Nocitev(osebe[17], cilji[27], 2000),
            new Tretja.Nocitev(osebe[25], cilji[14], 2009),
            new Tretja.Nocitev(osebe[23], cilji[11], 2018),
            new Tretja.Nocitev(osebe[17], cilji[19], 2000),
            new Tretja.Nocitev(osebe[12], cilji[17], 2014),
            new Tretja.Nocitev(osebe[19], cilji[2], 2015),
            new Tretja.Nocitev(osebe[10], cilji[13], 2020),
            new Tretja.Nocitev(osebe[4], cilji[23], 2014),
            new Tretja.Nocitev(osebe[1], cilji[28], 2009),
            new Tretja.Nocitev(osebe[1], cilji[24], 2004),
            new Tretja.Nocitev(osebe[5], cilji[26], 2000),
            new Tretja.Nocitev(osebe[18], cilji[11], 2004),
            new Tretja.Nocitev(osebe[19], cilji[2], 2009),
            new Tretja.Nocitev(osebe[21], cilji[14], 2000),
            new Tretja.Nocitev(osebe[5], cilji[26], 2005),
            new Tretja.Nocitev(osebe[12], cilji[10], 2017),
            new Tretja.Nocitev(osebe[14], cilji[24], 2017),
            new Tretja.Nocitev(osebe[2], cilji[15], 2016),
            new Tretja.Nocitev(osebe[9], cilji[2], 2016),
            new Tretja.Nocitev(osebe[18], cilji[11], 2010),
            new Tretja.Nocitev(osebe[8], cilji[27], 2019),
            new Tretja.Nocitev(osebe[6], cilji[7], 2008),
            new Tretja.Nocitev(osebe[1], cilji[29], 2017),
            new Tretja.Nocitev(osebe[2], cilji[15], 2012),
            new Tretja.Nocitev(osebe[20], cilji[25], 2012),
            new Tretja.Nocitev(osebe[22], cilji[29], 2020),
            new Tretja.Nocitev(osebe[5], cilji[26], 2010),
            new Tretja.Nocitev(osebe[26], cilji[2], 2002),
            new Tretja.Nocitev(osebe[7], cilji[28], 2008),
            new Tretja.Nocitev(osebe[17], cilji[8], 2006),
            new Tretja.Nocitev(osebe[21], cilji[14], 2017),
            new Tretja.Nocitev(osebe[25], cilji[14], 2008),
            new Tretja.Nocitev(osebe[4], cilji[17], 2013),
            new Tretja.Nocitev(osebe[15], cilji[28], 2018),
            new Tretja.Nocitev(osebe[11], cilji[4], 2009),
            new Tretja.Nocitev(osebe[0], cilji[0], 2012),
            new Tretja.Nocitev(osebe[26], cilji[2], 2014),
            new Tretja.Nocitev(osebe[8], cilji[27], 2002),
            new Tretja.Nocitev(osebe[19], cilji[2], 2019),
            new Tretja.Nocitev(osebe[10], cilji[13], 2013),
            new Tretja.Nocitev(osebe[3], cilji[16], 2011),
            new Tretja.Nocitev(osebe[26], cilji[2], 2005),
            new Tretja.Nocitev(osebe[17], cilji[26], 2000),
            new Tretja.Nocitev(osebe[14], cilji[24], 2017),
            new Tretja.Nocitev(osebe[11], cilji[27], 2000),
            new Tretja.Nocitev(osebe[0], cilji[9], 2018),
            new Tretja.Nocitev(osebe[9], cilji[23], 2015),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
