
public class Test36 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Dvlx Oarf", "Mshi"),
            new Tretja.Oseba("Mhnn Htxe", "Qofi"),
            new Tretja.Oseba("Oelh Yqsj", "Mshi"),
            new Tretja.Oseba("Jbvg Pwtz", "Bfom"),
            new Tretja.Oseba("Nfof Thfs", "Bfom"),
            new Tretja.Oseba("Ymeb Fqve", "Dccw"),
            new Tretja.Oseba("Ovgr Skhw", "Mshi"),
            new Tretja.Oseba("Unjm Oca", "Dccw"),
            new Tretja.Oseba("Jmbc Vruo", "Qofi"),
            new Tretja.Oseba("Ernu Fvz", "Mshi"),
            new Tretja.Oseba("Oram Lvji", "Mshi"),
            new Tretja.Oseba("Ladr Vbsb", "Mshi"),
            new Tretja.Oseba("Stbm Njse", "Dxb"),
            new Tretja.Oseba("Boft Zzpl", "Dxb"),
            new Tretja.Oseba("Qrfh Zkzz", "Qofi"),
            new Tretja.Oseba("Umak Juss", "Dxb"),
            new Tretja.Oseba("Ltlh Xnnv", "Dxb"),
            new Tretja.Oseba("Aymj Tsmi", "Bfom"),
            new Tretja.Oseba("Gbol Jowh", "Bfom"),
            new Tretja.Oseba("Lzfq Oprs", "Qofi"),
            new Tretja.Oseba("Gfhg Hnih", "Bfom"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Wdxo", "Dccw"),
            new Tretja.Cilj("Znlh", "Qofi"),
            new Tretja.Cilj("Rgcb", "Dccw"),
            new Tretja.Cilj("Gpab", "Dccw"),
            new Tretja.Cilj("Orfg", "Bfom"),
            new Tretja.Cilj("Ibkd", "Mshi"),
            new Tretja.Cilj("Athi", "Mshi"),
            new Tretja.Cilj("Mdgi", "Mshi"),
            new Tretja.Cilj("Hexq", "Bfom"),
            new Tretja.Cilj("Dsam", "Dxb"),
            new Tretja.Cilj("Nqlp", "Mshi"),
            new Tretja.Cilj("Uxsx", "Mshi"),
            new Tretja.Cilj("Hetw", "Mshi"),
            new Tretja.Cilj("Aytv", "Mshi"),
            new Tretja.Cilj("Sosn", "Bfom"),
            new Tretja.Cilj("Tdq", "Mshi"),
            new Tretja.Cilj("Oqbr", "Qofi"),
            new Tretja.Cilj("Lqkk", "Qofi"),
            new Tretja.Cilj("Bnpb", "Dxb"),
            new Tretja.Cilj("Qjmm", "Bfom"),
            new Tretja.Cilj("Xxso", "Mshi"),
            new Tretja.Cilj("Htwy", "Dccw"),
            new Tretja.Cilj("Hvex", "Bfom"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[20], cilji[4], 2016),
            new Tretja.Nocitev(osebe[15], cilji[10], 2017),
            new Tretja.Nocitev(osebe[7], cilji[7], 2001),
            new Tretja.Nocitev(osebe[12], cilji[1], 2019),
            new Tretja.Nocitev(osebe[8], cilji[2], 2005),
            new Tretja.Nocitev(osebe[1], cilji[11], 2018),
            new Tretja.Nocitev(osebe[15], cilji[12], 2016),
            new Tretja.Nocitev(osebe[4], cilji[12], 2005),
            new Tretja.Nocitev(osebe[0], cilji[17], 2013),
            new Tretja.Nocitev(osebe[20], cilji[16], 2011),
            new Tretja.Nocitev(osebe[7], cilji[7], 2020),
            new Tretja.Nocitev(osebe[10], cilji[14], 2011),
            new Tretja.Nocitev(osebe[17], cilji[7], 2009),
            new Tretja.Nocitev(osebe[0], cilji[17], 2000),
            new Tretja.Nocitev(osebe[12], cilji[7], 2010),
            new Tretja.Nocitev(osebe[14], cilji[5], 2005),
            new Tretja.Nocitev(osebe[19], cilji[18], 2017),
            new Tretja.Nocitev(osebe[8], cilji[2], 2017),
            new Tretja.Nocitev(osebe[17], cilji[8], 2000),
            new Tretja.Nocitev(osebe[18], cilji[5], 2010),
            new Tretja.Nocitev(osebe[11], cilji[8], 2018),
            new Tretja.Nocitev(osebe[16], cilji[14], 2011),
            new Tretja.Nocitev(osebe[4], cilji[12], 2008),
            new Tretja.Nocitev(osebe[5], cilji[0], 2017),
            new Tretja.Nocitev(osebe[1], cilji[7], 2007),
            new Tretja.Nocitev(osebe[13], cilji[8], 2004),
            new Tretja.Nocitev(osebe[7], cilji[7], 2007),
            new Tretja.Nocitev(osebe[9], cilji[0], 2007),
            new Tretja.Nocitev(osebe[17], cilji[12], 2003),
            new Tretja.Nocitev(osebe[10], cilji[14], 2002),
            new Tretja.Nocitev(osebe[13], cilji[8], 2011),
            new Tretja.Nocitev(osebe[8], cilji[2], 2020),
            new Tretja.Nocitev(osebe[11], cilji[7], 2011),
            new Tretja.Nocitev(osebe[6], cilji[13], 2000),
            new Tretja.Nocitev(osebe[7], cilji[7], 2010),
            new Tretja.Nocitev(osebe[14], cilji[5], 2018),
            new Tretja.Nocitev(osebe[10], cilji[14], 2007),
            new Tretja.Nocitev(osebe[10], cilji[14], 2006),
            new Tretja.Nocitev(osebe[4], cilji[12], 2015),
            new Tretja.Nocitev(osebe[7], cilji[7], 2016),
            new Tretja.Nocitev(osebe[11], cilji[22], 2005),
            new Tretja.Nocitev(osebe[8], cilji[2], 2011),
            new Tretja.Nocitev(osebe[14], cilji[10], 2011),
            new Tretja.Nocitev(osebe[20], cilji[18], 2017),
            new Tretja.Nocitev(osebe[9], cilji[14], 2007),
            new Tretja.Nocitev(osebe[20], cilji[12], 2011),
            new Tretja.Nocitev(osebe[18], cilji[5], 2011),
            new Tretja.Nocitev(osebe[8], cilji[2], 2011),
            new Tretja.Nocitev(osebe[6], cilji[13], 2003),
            new Tretja.Nocitev(osebe[8], cilji[2], 2000),
            new Tretja.Nocitev(osebe[20], cilji[20], 2009),
            new Tretja.Nocitev(osebe[5], cilji[10], 2001),
            new Tretja.Nocitev(osebe[17], cilji[9], 2006),
            new Tretja.Nocitev(osebe[15], cilji[21], 2005),
            new Tretja.Nocitev(osebe[1], cilji[7], 2008),
            new Tretja.Nocitev(osebe[17], cilji[4], 2001),
            new Tretja.Nocitev(osebe[0], cilji[17], 2015),
            new Tretja.Nocitev(osebe[14], cilji[1], 2011),
            new Tretja.Nocitev(osebe[3], cilji[9], 2014),
            new Tretja.Nocitev(osebe[0], cilji[17], 2008),
            new Tretja.Nocitev(osebe[10], cilji[14], 2017),
            new Tretja.Nocitev(osebe[7], cilji[7], 2001),
            new Tretja.Nocitev(osebe[3], cilji[5], 2017),
            new Tretja.Nocitev(osebe[3], cilji[7], 2017),
            new Tretja.Nocitev(osebe[17], cilji[13], 2006),
            new Tretja.Nocitev(osebe[19], cilji[18], 2005),
            new Tretja.Nocitev(osebe[19], cilji[18], 2015),
            new Tretja.Nocitev(osebe[16], cilji[14], 2020),
            new Tretja.Nocitev(osebe[15], cilji[11], 2004),
            new Tretja.Nocitev(osebe[0], cilji[17], 2004),
            new Tretja.Nocitev(osebe[12], cilji[7], 2003),
            new Tretja.Nocitev(osebe[11], cilji[15], 2016),
            new Tretja.Nocitev(osebe[19], cilji[18], 2003),
            new Tretja.Nocitev(osebe[1], cilji[7], 2016),
            new Tretja.Nocitev(osebe[3], cilji[4], 2009),
            new Tretja.Nocitev(osebe[9], cilji[11], 2017),
            new Tretja.Nocitev(osebe[14], cilji[20], 2020),
            new Tretja.Nocitev(osebe[0], cilji[17], 2007),
            new Tretja.Nocitev(osebe[9], cilji[14], 2004),
            new Tretja.Nocitev(osebe[19], cilji[18], 2003),
            new Tretja.Nocitev(osebe[20], cilji[7], 2013),
            new Tretja.Nocitev(osebe[2], cilji[18], 2015),
            new Tretja.Nocitev(osebe[8], cilji[2], 2002),
            new Tretja.Nocitev(osebe[20], cilji[10], 2001),
            new Tretja.Nocitev(osebe[9], cilji[0], 2018),
            new Tretja.Nocitev(osebe[13], cilji[19], 2009),
            new Tretja.Nocitev(osebe[18], cilji[5], 2013),
            new Tretja.Nocitev(osebe[2], cilji[18], 2015),
            new Tretja.Nocitev(osebe[4], cilji[12], 2006),
            new Tretja.Nocitev(osebe[6], cilji[13], 2012),
            new Tretja.Nocitev(osebe[1], cilji[22], 2006),
            new Tretja.Nocitev(osebe[12], cilji[16], 2008),
            new Tretja.Nocitev(osebe[15], cilji[15], 2004),
            new Tretja.Nocitev(osebe[3], cilji[19], 2013),
            new Tretja.Nocitev(osebe[0], cilji[17], 2002),
            new Tretja.Nocitev(osebe[10], cilji[14], 2016),
            new Tretja.Nocitev(osebe[3], cilji[9], 2012),
            new Tretja.Nocitev(osebe[13], cilji[4], 2016),
            new Tretja.Nocitev(osebe[7], cilji[7], 2012),
            new Tretja.Nocitev(osebe[6], cilji[13], 2007),
            new Tretja.Nocitev(osebe[1], cilji[10], 2003),
            new Tretja.Nocitev(osebe[4], cilji[12], 2003),
            new Tretja.Nocitev(osebe[0], cilji[17], 2018),
            new Tretja.Nocitev(osebe[12], cilji[4], 2011),
            new Tretja.Nocitev(osebe[12], cilji[9], 2006),
            new Tretja.Nocitev(osebe[10], cilji[14], 2000),
            new Tretja.Nocitev(osebe[6], cilji[13], 2020),
            new Tretja.Nocitev(osebe[13], cilji[13], 2012),
            new Tretja.Nocitev(osebe[11], cilji[18], 2001),
            new Tretja.Nocitev(osebe[13], cilji[3], 2014),
            new Tretja.Nocitev(osebe[6], cilji[13], 2003),
            new Tretja.Nocitev(osebe[0], cilji[17], 2013),
            new Tretja.Nocitev(osebe[18], cilji[5], 2014),
            new Tretja.Nocitev(osebe[19], cilji[18], 2003),
            new Tretja.Nocitev(osebe[9], cilji[9], 2016),
            new Tretja.Nocitev(osebe[20], cilji[9], 2012),
            new Tretja.Nocitev(osebe[0], cilji[17], 2014),
            new Tretja.Nocitev(osebe[6], cilji[13], 2013),
            new Tretja.Nocitev(osebe[6], cilji[13], 2008),
            new Tretja.Nocitev(osebe[9], cilji[4], 2006),
            new Tretja.Nocitev(osebe[1], cilji[7], 2016),
            new Tretja.Nocitev(osebe[1], cilji[13], 2007),
            new Tretja.Nocitev(osebe[20], cilji[3], 2001),
            new Tretja.Nocitev(osebe[3], cilji[20], 2002),
            new Tretja.Nocitev(osebe[6], cilji[13], 2013),
            new Tretja.Nocitev(osebe[16], cilji[14], 2019),
            new Tretja.Nocitev(osebe[2], cilji[18], 2010),
            new Tretja.Nocitev(osebe[16], cilji[14], 2002),
            new Tretja.Nocitev(osebe[19], cilji[18], 2001),
            new Tretja.Nocitev(osebe[1], cilji[18], 2001),
            new Tretja.Nocitev(osebe[17], cilji[0], 2020),
            new Tretja.Nocitev(osebe[3], cilji[15], 2018),
            new Tretja.Nocitev(osebe[13], cilji[15], 2020),
            new Tretja.Nocitev(osebe[20], cilji[6], 2003),
            new Tretja.Nocitev(osebe[4], cilji[12], 2007),
            new Tretja.Nocitev(osebe[6], cilji[13], 2005),
            new Tretja.Nocitev(osebe[10], cilji[14], 2014),
            new Tretja.Nocitev(osebe[2], cilji[18], 2005),
            new Tretja.Nocitev(osebe[15], cilji[3], 2008),
            new Tretja.Nocitev(osebe[4], cilji[12], 2003),
            new Tretja.Nocitev(osebe[0], cilji[17], 2017),
            new Tretja.Nocitev(osebe[13], cilji[12], 2010),
            new Tretja.Nocitev(osebe[4], cilji[12], 2007),
            new Tretja.Nocitev(osebe[10], cilji[14], 2002),
            new Tretja.Nocitev(osebe[6], cilji[13], 2018),
            new Tretja.Nocitev(osebe[0], cilji[17], 2018),
            new Tretja.Nocitev(osebe[4], cilji[12], 2015),
            new Tretja.Nocitev(osebe[6], cilji[13], 2008),
            new Tretja.Nocitev(osebe[7], cilji[7], 2017),
            new Tretja.Nocitev(osebe[2], cilji[18], 2009),
            new Tretja.Nocitev(osebe[17], cilji[9], 2015),
            new Tretja.Nocitev(osebe[20], cilji[12], 2020),
            new Tretja.Nocitev(osebe[0], cilji[17], 2016),
            new Tretja.Nocitev(osebe[7], cilji[7], 2015),
            new Tretja.Nocitev(osebe[13], cilji[20], 2004),
            new Tretja.Nocitev(osebe[2], cilji[18], 2000),
            new Tretja.Nocitev(osebe[15], cilji[2], 2008),
            new Tretja.Nocitev(osebe[17], cilji[6], 2019),
            new Tretja.Nocitev(osebe[14], cilji[13], 2018),
            new Tretja.Nocitev(osebe[5], cilji[5], 2002),
            new Tretja.Nocitev(osebe[19], cilji[18], 2005),
            new Tretja.Nocitev(osebe[12], cilji[7], 2020),
            new Tretja.Nocitev(osebe[7], cilji[7], 2003),
            new Tretja.Nocitev(osebe[10], cilji[14], 2001),
            new Tretja.Nocitev(osebe[15], cilji[15], 2012),
            new Tretja.Nocitev(osebe[13], cilji[10], 2002),
            new Tretja.Nocitev(osebe[7], cilji[7], 2000),
            new Tretja.Nocitev(osebe[16], cilji[14], 2012),
            new Tretja.Nocitev(osebe[6], cilji[13], 2013),
            new Tretja.Nocitev(osebe[7], cilji[7], 2001),
            new Tretja.Nocitev(osebe[8], cilji[2], 2004),
            new Tretja.Nocitev(osebe[10], cilji[14], 2000),
            new Tretja.Nocitev(osebe[9], cilji[17], 2018),
            new Tretja.Nocitev(osebe[13], cilji[5], 2001),
            new Tretja.Nocitev(osebe[18], cilji[5], 2019),
            new Tretja.Nocitev(osebe[0], cilji[17], 2014),
            new Tretja.Nocitev(osebe[2], cilji[18], 2020),
            new Tretja.Nocitev(osebe[8], cilji[2], 2005),
            new Tretja.Nocitev(osebe[10], cilji[14], 2020),
            new Tretja.Nocitev(osebe[3], cilji[19], 2000),
            new Tretja.Nocitev(osebe[16], cilji[14], 2011),
            new Tretja.Nocitev(osebe[10], cilji[14], 2015),
            new Tretja.Nocitev(osebe[16], cilji[14], 2018),
            new Tretja.Nocitev(osebe[15], cilji[8], 2020),
            new Tretja.Nocitev(osebe[2], cilji[18], 2016),
            new Tretja.Nocitev(osebe[20], cilji[3], 2000),
            new Tretja.Nocitev(osebe[3], cilji[0], 2009),
            new Tretja.Nocitev(osebe[3], cilji[11], 2019),
            new Tretja.Nocitev(osebe[10], cilji[14], 2006),
            new Tretja.Nocitev(osebe[2], cilji[18], 2010),
            new Tretja.Nocitev(osebe[4], cilji[12], 2011),
            new Tretja.Nocitev(osebe[2], cilji[18], 2000),
            new Tretja.Nocitev(osebe[15], cilji[11], 2017),
            new Tretja.Nocitev(osebe[10], cilji[14], 2005),
            new Tretja.Nocitev(osebe[15], cilji[11], 2000),
            new Tretja.Nocitev(osebe[16], cilji[14], 2020),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2002, 2005);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
