
public class Test48 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Taoj Lact", "Tqcp"),
            new Tretja.Oseba("Jeqy Dxgf", "Tqcp"),
            new Tretja.Oseba("Zsil Dppg", "Qshi"),
            new Tretja.Oseba("Xjnn Qxko", "Tqcp"),
            new Tretja.Oseba("Zsci Rzgu", "Cszn"),
            new Tretja.Oseba("Evjb Qeph", "Qshi"),
            new Tretja.Oseba("Yciw Tsfm", "Qshi"),
            new Tretja.Oseba("Tltx Bizg", "Tqcp"),
            new Tretja.Oseba("Juwd Wplc", "Cszn"),
            new Tretja.Oseba("Gnrh Yoec", "Cszn"),
            new Tretja.Oseba("Upyl Msry", "Qshi"),
            new Tretja.Oseba("Yirt Sfps", "Cszn"),
            new Tretja.Oseba("Hrak Dhry", "Cszn"),
            new Tretja.Oseba("Xyej Wogg", "Tqcp"),
            new Tretja.Oseba("Lnfl Sito", "Qshi"),
            new Tretja.Oseba("Ftpc Xoia", "Tqcp"),
            new Tretja.Oseba("Iwqh Xzbf", "Cszn"),
            new Tretja.Oseba("Krvr Rpeq", "Tqcp"),
            new Tretja.Oseba("Jxkw Iljq", "Qshi"),
            new Tretja.Oseba("Ebpd Oliv", "Tqcp"),
            new Tretja.Oseba("Llpe Pjta", "Cszn"),
            new Tretja.Oseba("Mrjf Ueag", "Qshi"),
            new Tretja.Oseba("Frov Vwis", "Qshi"),
            new Tretja.Oseba("Jrfh Xkvo", "Tqcp"),
            new Tretja.Oseba("Kwui Zsoe", "Qshi"),
            new Tretja.Oseba("Zgsf Dwfh", "Tqcp"),
            new Tretja.Oseba("Ifik Mcjl", "Qshi"),
            new Tretja.Oseba("Ltik Sxej", "Tqcp"),
            new Tretja.Oseba("Yloo Fmh", "Cszn"),
            new Tretja.Oseba("Zemp Efoe", "Cszn"),
            new Tretja.Oseba("Ijdn Jcar", "Cszn"),
            new Tretja.Oseba("Bjbx Vobu", "Qshi"),
            new Tretja.Oseba("Kygq Rxef", "Tqcp"),
            new Tretja.Oseba("Unnq Amly", "Qshi"),
            new Tretja.Oseba("Czut Htra", "Cszn"),
            new Tretja.Oseba("Zheh Mpqv", "Tqcp"),
            new Tretja.Oseba("Kstt Duhf", "Qshi"),
            new Tretja.Oseba("Phgi Gqzm", "Tqcp"),
            new Tretja.Oseba("Ekdl Exdc", "Cszn"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Wuzt", "Tqcp"),
            new Tretja.Cilj("Pjie", "Cszn"),
            new Tretja.Cilj("Qust", "Tqcp"),
            new Tretja.Cilj("Ieib", "Tqcp"),
            new Tretja.Cilj("Gcfz", "Cszn"),
            new Tretja.Cilj("Nwoa", "Tqcp"),
            new Tretja.Cilj("Ctls", "Tqcp"),
            new Tretja.Cilj("Qkjs", "Qshi"),
            new Tretja.Cilj("Pqar", "Cszn"),
            new Tretja.Cilj("Rquc", "Cszn"),
            new Tretja.Cilj("Rqlv", "Qshi"),
            new Tretja.Cilj("Smmt", "Tqcp"),
            new Tretja.Cilj("Enws", "Tqcp"),
            new Tretja.Cilj("Ilgu", "Qshi"),
            new Tretja.Cilj("Nkqs", "Cszn"),
            new Tretja.Cilj("Haho", "Cszn"),
            new Tretja.Cilj("Zren", "Qshi"),
            new Tretja.Cilj("Bbcm", "Cszn"),
            new Tretja.Cilj("Syuc", "Qshi"),
            new Tretja.Cilj("Sdje", "Qshi"),
            new Tretja.Cilj("Rzhl", "Tqcp"),
            new Tretja.Cilj("Vagd", "Tqcp"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[25], cilji[5], 2011),
            new Tretja.Nocitev(osebe[38], cilji[13], 2010),
            new Tretja.Nocitev(osebe[7], cilji[12], 2015),
            new Tretja.Nocitev(osebe[26], cilji[20], 2005),
            new Tretja.Nocitev(osebe[4], cilji[8], 2005),
            new Tretja.Nocitev(osebe[33], cilji[9], 2012),
            new Tretja.Nocitev(osebe[4], cilji[8], 2002),
            new Tretja.Nocitev(osebe[34], cilji[5], 2008),
            new Tretja.Nocitev(osebe[22], cilji[17], 2002),
            new Tretja.Nocitev(osebe[19], cilji[2], 2009),
            new Tretja.Nocitev(osebe[11], cilji[8], 2009),
            new Tretja.Nocitev(osebe[1], cilji[17], 2008),
            new Tretja.Nocitev(osebe[12], cilji[0], 2018),
            new Tretja.Nocitev(osebe[16], cilji[20], 2008),
            new Tretja.Nocitev(osebe[36], cilji[13], 2001),
            new Tretja.Nocitev(osebe[20], cilji[21], 2020),
            new Tretja.Nocitev(osebe[17], cilji[3], 2017),
            new Tretja.Nocitev(osebe[13], cilji[20], 2019),
            new Tretja.Nocitev(osebe[29], cilji[15], 2011),
            new Tretja.Nocitev(osebe[16], cilji[20], 2009),
            new Tretja.Nocitev(osebe[8], cilji[12], 2019),
            new Tretja.Nocitev(osebe[27], cilji[13], 2014),
            new Tretja.Nocitev(osebe[28], cilji[8], 2007),
            new Tretja.Nocitev(osebe[34], cilji[5], 2007),
            new Tretja.Nocitev(osebe[1], cilji[20], 2002),
            new Tretja.Nocitev(osebe[34], cilji[5], 2009),
            new Tretja.Nocitev(osebe[29], cilji[15], 2020),
            new Tretja.Nocitev(osebe[11], cilji[8], 2007),
            new Tretja.Nocitev(osebe[7], cilji[12], 2013),
            new Tretja.Nocitev(osebe[38], cilji[0], 2012),
            new Tretja.Nocitev(osebe[12], cilji[12], 2009),
            new Tretja.Nocitev(osebe[9], cilji[1], 2010),
            new Tretja.Nocitev(osebe[37], cilji[15], 2004),
            new Tretja.Nocitev(osebe[30], cilji[2], 2011),
            new Tretja.Nocitev(osebe[3], cilji[20], 2014),
            new Tretja.Nocitev(osebe[1], cilji[20], 2009),
            new Tretja.Nocitev(osebe[27], cilji[13], 2017),
            new Tretja.Nocitev(osebe[29], cilji[15], 2011),
            new Tretja.Nocitev(osebe[18], cilji[20], 2002),
            new Tretja.Nocitev(osebe[11], cilji[8], 2003),
            new Tretja.Nocitev(osebe[33], cilji[9], 2013),
            new Tretja.Nocitev(osebe[22], cilji[8], 2014),
            new Tretja.Nocitev(osebe[18], cilji[14], 2015),
            new Tretja.Nocitev(osebe[22], cilji[6], 2000),
            new Tretja.Nocitev(osebe[30], cilji[1], 2019),
            new Tretja.Nocitev(osebe[19], cilji[2], 2002),
            new Tretja.Nocitev(osebe[1], cilji[13], 2000),
            new Tretja.Nocitev(osebe[35], cilji[6], 2014),
            new Tretja.Nocitev(osebe[2], cilji[15], 2002),
            new Tretja.Nocitev(osebe[11], cilji[8], 2018),
            new Tretja.Nocitev(osebe[29], cilji[15], 2002),
            new Tretja.Nocitev(osebe[28], cilji[8], 2010),
            new Tretja.Nocitev(osebe[32], cilji[14], 2000),
            new Tretja.Nocitev(osebe[37], cilji[20], 2016),
            new Tretja.Nocitev(osebe[13], cilji[20], 2002),
            new Tretja.Nocitev(osebe[22], cilji[0], 2014),
            new Tretja.Nocitev(osebe[37], cilji[11], 2010),
            new Tretja.Nocitev(osebe[10], cilji[16], 2018),
            new Tretja.Nocitev(osebe[9], cilji[1], 2001),
            new Tretja.Nocitev(osebe[8], cilji[14], 2005),
            new Tretja.Nocitev(osebe[6], cilji[15], 2003),
            new Tretja.Nocitev(osebe[14], cilji[2], 2005),
            new Tretja.Nocitev(osebe[0], cilji[14], 2000),
            new Tretja.Nocitev(osebe[28], cilji[8], 2015),
            new Tretja.Nocitev(osebe[19], cilji[2], 2018),
            new Tretja.Nocitev(osebe[18], cilji[8], 2007),
            new Tretja.Nocitev(osebe[27], cilji[13], 2006),
            new Tretja.Nocitev(osebe[16], cilji[20], 2001),
            new Tretja.Nocitev(osebe[14], cilji[17], 2015),
            new Tretja.Nocitev(osebe[34], cilji[5], 2020),
            new Tretja.Nocitev(osebe[19], cilji[2], 2011),
            new Tretja.Nocitev(osebe[34], cilji[5], 2002),
            new Tretja.Nocitev(osebe[7], cilji[12], 2005),
            new Tretja.Nocitev(osebe[24], cilji[10], 2005),
            new Tretja.Nocitev(osebe[23], cilji[7], 2009),
            new Tretja.Nocitev(osebe[8], cilji[2], 2006),
            new Tretja.Nocitev(osebe[23], cilji[7], 2004),
            new Tretja.Nocitev(osebe[30], cilji[2], 2001),
            new Tretja.Nocitev(osebe[12], cilji[21], 2005),
            new Tretja.Nocitev(osebe[26], cilji[0], 2014),
            new Tretja.Nocitev(osebe[30], cilji[11], 2019),
            new Tretja.Nocitev(osebe[17], cilji[8], 2005),
            new Tretja.Nocitev(osebe[7], cilji[12], 2013),
            new Tretja.Nocitev(osebe[29], cilji[15], 2009),
            new Tretja.Nocitev(osebe[14], cilji[20], 2011),
            new Tretja.Nocitev(osebe[21], cilji[2], 2003),
            new Tretja.Nocitev(osebe[2], cilji[9], 2001),
            new Tretja.Nocitev(osebe[12], cilji[20], 2011),
            new Tretja.Nocitev(osebe[36], cilji[20], 2002),
            new Tretja.Nocitev(osebe[29], cilji[15], 2003),
            new Tretja.Nocitev(osebe[20], cilji[21], 2019),
            new Tretja.Nocitev(osebe[3], cilji[20], 2013),
            new Tretja.Nocitev(osebe[31], cilji[3], 2004),
            new Tretja.Nocitev(osebe[38], cilji[1], 2010),
            new Tretja.Nocitev(osebe[11], cilji[8], 2001),
            new Tretja.Nocitev(osebe[2], cilji[6], 2004),
            new Tretja.Nocitev(osebe[33], cilji[9], 2011),
            new Tretja.Nocitev(osebe[0], cilji[11], 2012),
            new Tretja.Nocitev(osebe[10], cilji[8], 2003),
            new Tretja.Nocitev(osebe[10], cilji[18], 2010),
            new Tretja.Nocitev(osebe[14], cilji[18], 2020),
            new Tretja.Nocitev(osebe[3], cilji[20], 2018),
            new Tretja.Nocitev(osebe[38], cilji[5], 2005),
            new Tretja.Nocitev(osebe[36], cilji[17], 2015),
            new Tretja.Nocitev(osebe[17], cilji[12], 2005),
            new Tretja.Nocitev(osebe[13], cilji[20], 2017),
            new Tretja.Nocitev(osebe[1], cilji[20], 2017),
            new Tretja.Nocitev(osebe[3], cilji[20], 2016),
            new Tretja.Nocitev(osebe[35], cilji[2], 2015),
            new Tretja.Nocitev(osebe[5], cilji[20], 2007),
            new Tretja.Nocitev(osebe[38], cilji[21], 2006),
            new Tretja.Nocitev(osebe[13], cilji[20], 2011),
            new Tretja.Nocitev(osebe[36], cilji[4], 2001),
            new Tretja.Nocitev(osebe[31], cilji[17], 2006),
            new Tretja.Nocitev(osebe[15], cilji[13], 2012),
            new Tretja.Nocitev(osebe[28], cilji[8], 2000),
            new Tretja.Nocitev(osebe[24], cilji[10], 2002),
            new Tretja.Nocitev(osebe[37], cilji[2], 2014),
            new Tretja.Nocitev(osebe[17], cilji[5], 2002),
            new Tretja.Nocitev(osebe[13], cilji[20], 2002),
            new Tretja.Nocitev(osebe[29], cilji[15], 2020),
            new Tretja.Nocitev(osebe[23], cilji[7], 2013),
            new Tretja.Nocitev(osebe[7], cilji[12], 2003),
            new Tretja.Nocitev(osebe[7], cilji[12], 2005),
            new Tretja.Nocitev(osebe[20], cilji[21], 2002),
            new Tretja.Nocitev(osebe[6], cilji[3], 2009),
            new Tretja.Nocitev(osebe[38], cilji[9], 2003),
            new Tretja.Nocitev(osebe[26], cilji[15], 2004),
            new Tretja.Nocitev(osebe[28], cilji[8], 2000),
            new Tretja.Nocitev(osebe[20], cilji[21], 2015),
            new Tretja.Nocitev(osebe[17], cilji[13], 2002),
            new Tretja.Nocitev(osebe[27], cilji[13], 2002),
            new Tretja.Nocitev(osebe[27], cilji[13], 2011),
            new Tretja.Nocitev(osebe[35], cilji[0], 2016),
            new Tretja.Nocitev(osebe[13], cilji[20], 2006),
            new Tretja.Nocitev(osebe[15], cilji[10], 2004),
            new Tretja.Nocitev(osebe[35], cilji[14], 2019),
            new Tretja.Nocitev(osebe[1], cilji[5], 2018),
            new Tretja.Nocitev(osebe[7], cilji[12], 2006),
            new Tretja.Nocitev(osebe[3], cilji[20], 2016),
            new Tretja.Nocitev(osebe[35], cilji[0], 2010),
            new Tretja.Nocitev(osebe[6], cilji[17], 2008),
            new Tretja.Nocitev(osebe[22], cilji[14], 2005),
            new Tretja.Nocitev(osebe[27], cilji[13], 2010),
            new Tretja.Nocitev(osebe[8], cilji[21], 2020),
            new Tretja.Nocitev(osebe[38], cilji[6], 2019),
            new Tretja.Nocitev(osebe[36], cilji[6], 2011),
            new Tretja.Nocitev(osebe[32], cilji[14], 2008),
            new Tretja.Nocitev(osebe[16], cilji[20], 2004),
            new Tretja.Nocitev(osebe[31], cilji[13], 2005),
            new Tretja.Nocitev(osebe[32], cilji[14], 2003),
            new Tretja.Nocitev(osebe[15], cilji[4], 2020),
            new Tretja.Nocitev(osebe[1], cilji[20], 2020),
            new Tretja.Nocitev(osebe[35], cilji[13], 2006),
            new Tretja.Nocitev(osebe[0], cilji[20], 2007),
            new Tretja.Nocitev(osebe[6], cilji[21], 2019),
            new Tretja.Nocitev(osebe[30], cilji[16], 2013),
            new Tretja.Nocitev(osebe[14], cilji[14], 2007),
            new Tretja.Nocitev(osebe[19], cilji[2], 2011),
            new Tretja.Nocitev(osebe[38], cilji[15], 2020),
            new Tretja.Nocitev(osebe[34], cilji[5], 2010),
            new Tretja.Nocitev(osebe[9], cilji[1], 2011),
            new Tretja.Nocitev(osebe[26], cilji[17], 2018),
            new Tretja.Nocitev(osebe[1], cilji[8], 2015),
            new Tretja.Nocitev(osebe[23], cilji[7], 2002),
            new Tretja.Nocitev(osebe[25], cilji[5], 2017),
            new Tretja.Nocitev(osebe[4], cilji[8], 2011),
            new Tretja.Nocitev(osebe[28], cilji[8], 2004),
            new Tretja.Nocitev(osebe[15], cilji[5], 2006),
            new Tretja.Nocitev(osebe[25], cilji[5], 2011),
            new Tretja.Nocitev(osebe[22], cilji[9], 2010),
            new Tretja.Nocitev(osebe[6], cilji[2], 2005),
            new Tretja.Nocitev(osebe[27], cilji[13], 2002),
            new Tretja.Nocitev(osebe[15], cilji[9], 2015),
            new Tretja.Nocitev(osebe[12], cilji[16], 2006),
            new Tretja.Nocitev(osebe[0], cilji[19], 2002),
            new Tretja.Nocitev(osebe[24], cilji[10], 2019),
            new Tretja.Nocitev(osebe[30], cilji[12], 2004),
            new Tretja.Nocitev(osebe[25], cilji[5], 2010),
            new Tretja.Nocitev(osebe[13], cilji[20], 2017),
            new Tretja.Nocitev(osebe[1], cilji[19], 2010),
            new Tretja.Nocitev(osebe[20], cilji[21], 2012),
            new Tretja.Nocitev(osebe[12], cilji[20], 2002),
            new Tretja.Nocitev(osebe[10], cilji[4], 2000),
            new Tretja.Nocitev(osebe[21], cilji[2], 2008),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2015, 2016);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
