
public class Test07 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Axjp Iyuw", "Edrv"),
            new Tretja.Oseba("Crsp Uvqi", "Sage"),
            new Tretja.Oseba("Knb Uaft", "Edrv"),
            new Tretja.Oseba("Eecp Tdbc", "Zppg"),
            new Tretja.Oseba("Wive Xtky", "Sage"),
            new Tretja.Oseba("Qdsy Ylmh", "Kwan"),
            new Tretja.Oseba("Oqeh Dhxt", "Sage"),
            new Tretja.Oseba("Raku Ryvy", "Zppg"),
            new Tretja.Oseba("Avlp Cxmk", "Edrv"),
            new Tretja.Oseba("Ekkd Fqkd", "Sage"),
            new Tretja.Oseba("Mdur Mmfl", "Zppg"),
            new Tretja.Oseba("Akuq Fbfw", "Zppg"),
            new Tretja.Oseba("Fusq Zrji", "Sage"),
            new Tretja.Oseba("Rkon Fiyu", "Zppg"),
            new Tretja.Oseba("Ogte Mgae", "Sage"),
            new Tretja.Oseba("Cev Ffaz", "Zppg"),
            new Tretja.Oseba("Ljjc Hshc", "Kwan"),
            new Tretja.Oseba("Ytdb Vtfe", "Zppg"),
            new Tretja.Oseba("Rkan Uihn", "Edrv"),
            new Tretja.Oseba("Nokd Ywct", "Kwan"),
            new Tretja.Oseba("Btkp Axda", "Edrv"),
            new Tretja.Oseba("Ozgc Vcvu", "Sage"),
            new Tretja.Oseba("Mbrf Nqxb", "Edrv"),
            new Tretja.Oseba("Qes Tevo", "Edrv"),
            new Tretja.Oseba("Uyda Nqte", "Zppg"),
            new Tretja.Oseba("Aojz Vqsl", "Kwan"),
            new Tretja.Oseba("Idtk Vwni", "Kwan"),
            new Tretja.Oseba("Htll Tmhy", "Zppg"),
            new Tretja.Oseba("Usi Sxxr", "Edrv"),
            new Tretja.Oseba("Pifh Msyy", "Edrv"),
            new Tretja.Oseba("Nite Knih", "Kwan"),
            new Tretja.Oseba("Fhsu Ueee", "Sage"),
            new Tretja.Oseba("Jrel Vbml", "Zppg"),
            new Tretja.Oseba("Lrwf Lmzg", "Zppg"),
            new Tretja.Oseba("Pbov Ppwc", "Kwan"),
            new Tretja.Oseba("Dszf Kkrc", "Zppg"),
            new Tretja.Oseba("Mgec Chti", "Zppg"),
            new Tretja.Oseba("Nklk Bqid", "Kwan"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Utqb", "Zppg"),
            new Tretja.Cilj("Ccif", "Edrv"),
            new Tretja.Cilj("Zvoa", "Sage"),
            new Tretja.Cilj("Swjp", "Edrv"),
            new Tretja.Cilj("Watp", "Edrv"),
            new Tretja.Cilj("Lfrr", "Sage"),
            new Tretja.Cilj("Ahpb", "Kwan"),
            new Tretja.Cilj("Nkkz", "Sage"),
            new Tretja.Cilj("Sgos", "Zppg"),
            new Tretja.Cilj("Mnrz", "Kwan"),
            new Tretja.Cilj("Tjwv", "Zppg"),
            new Tretja.Cilj("Xpd", "Zppg"),
            new Tretja.Cilj("Tatn", "Sage"),
            new Tretja.Cilj("Gssc", "Zppg"),
            new Tretja.Cilj("Kjaq", "Sage"),
            new Tretja.Cilj("Vrca", "Zppg"),
            new Tretja.Cilj("Pzel", "Sage"),
            new Tretja.Cilj("Nrqx", "Edrv"),
            new Tretja.Cilj("Yhzl", "Kwan"),
            new Tretja.Cilj("Htut", "Kwan"),
            new Tretja.Cilj("Jrz", "Zppg"),
            new Tretja.Cilj("Zipr", "Kwan"),
            new Tretja.Cilj("Eaao", "Sage"),
            new Tretja.Cilj("Qak", "Zppg"),
            new Tretja.Cilj("Wfmc", "Edrv"),
            new Tretja.Cilj("Nnmi", "Sage"),
            new Tretja.Cilj("Ajlt", "Edrv"),
            new Tretja.Cilj("Ikbf", "Zppg"),
            new Tretja.Cilj("Jruo", "Edrv"),
            new Tretja.Cilj("Wqwg", "Edrv"),
            new Tretja.Cilj("Uffs", "Edrv"),
            new Tretja.Cilj("Wiin", "Sage"),
            new Tretja.Cilj("Aupl", "Kwan"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[5], cilji[2], 2008),
            new Tretja.Nocitev(osebe[1], cilji[0], 2009),
            new Tretja.Nocitev(osebe[25], cilji[18], 2000),
            new Tretja.Nocitev(osebe[3], cilji[30], 2011),
            new Tretja.Nocitev(osebe[16], cilji[31], 2016),
            new Tretja.Nocitev(osebe[8], cilji[26], 2005),
            new Tretja.Nocitev(osebe[3], cilji[25], 2017),
            new Tretja.Nocitev(osebe[20], cilji[31], 2002),
            new Tretja.Nocitev(osebe[35], cilji[26], 2003),
            new Tretja.Nocitev(osebe[5], cilji[2], 2009),
            new Tretja.Nocitev(osebe[16], cilji[30], 2003),
            new Tretja.Nocitev(osebe[26], cilji[21], 2012),
            new Tretja.Nocitev(osebe[6], cilji[10], 2014),
            new Tretja.Nocitev(osebe[30], cilji[24], 2016),
            new Tretja.Nocitev(osebe[34], cilji[6], 2012),
            new Tretja.Nocitev(osebe[19], cilji[6], 2013),
            new Tretja.Nocitev(osebe[24], cilji[23], 2000),
            new Tretja.Nocitev(osebe[15], cilji[26], 2003),
            new Tretja.Nocitev(osebe[29], cilji[14], 2013),
            new Tretja.Nocitev(osebe[10], cilji[17], 2018),
            new Tretja.Nocitev(osebe[17], cilji[3], 2010),
            new Tretja.Nocitev(osebe[25], cilji[18], 2013),
            new Tretja.Nocitev(osebe[14], cilji[0], 2015),
            new Tretja.Nocitev(osebe[26], cilji[21], 2019),
            new Tretja.Nocitev(osebe[12], cilji[21], 2020),
            new Tretja.Nocitev(osebe[10], cilji[6], 2008),
            new Tretja.Nocitev(osebe[13], cilji[5], 2020),
            new Tretja.Nocitev(osebe[8], cilji[11], 2011),
            new Tretja.Nocitev(osebe[13], cilji[5], 2005),
            new Tretja.Nocitev(osebe[15], cilji[26], 2014),
            new Tretja.Nocitev(osebe[31], cilji[31], 2008),
            new Tretja.Nocitev(osebe[13], cilji[5], 2000),
            new Tretja.Nocitev(osebe[26], cilji[21], 2017),
            new Tretja.Nocitev(osebe[17], cilji[18], 2014),
            new Tretja.Nocitev(osebe[4], cilji[9], 2004),
            new Tretja.Nocitev(osebe[2], cilji[30], 2015),
            new Tretja.Nocitev(osebe[27], cilji[25], 2016),
            new Tretja.Nocitev(osebe[9], cilji[3], 2018),
            new Tretja.Nocitev(osebe[20], cilji[31], 2012),
            new Tretja.Nocitev(osebe[5], cilji[2], 2015),
            new Tretja.Nocitev(osebe[30], cilji[24], 2000),
            new Tretja.Nocitev(osebe[2], cilji[30], 2013),
            new Tretja.Nocitev(osebe[10], cilji[20], 2001),
            new Tretja.Nocitev(osebe[31], cilji[31], 2013),
            new Tretja.Nocitev(osebe[21], cilji[10], 2012),
            new Tretja.Nocitev(osebe[12], cilji[21], 2012),
            new Tretja.Nocitev(osebe[9], cilji[25], 2007),
            new Tretja.Nocitev(osebe[23], cilji[27], 2014),
            new Tretja.Nocitev(osebe[24], cilji[29], 2004),
            new Tretja.Nocitev(osebe[25], cilji[18], 2011),
            new Tretja.Nocitev(osebe[3], cilji[27], 2015),
            new Tretja.Nocitev(osebe[5], cilji[2], 2002),
            new Tretja.Nocitev(osebe[23], cilji[27], 2006),
            new Tretja.Nocitev(osebe[24], cilji[0], 2019),
            new Tretja.Nocitev(osebe[36], cilji[20], 2012),
            new Tretja.Nocitev(osebe[18], cilji[21], 2003),
            new Tretja.Nocitev(osebe[16], cilji[25], 2007),
            new Tretja.Nocitev(osebe[11], cilji[26], 2010),
            new Tretja.Nocitev(osebe[19], cilji[6], 2012),
            new Tretja.Nocitev(osebe[25], cilji[18], 2006),
            new Tretja.Nocitev(osebe[34], cilji[13], 2001),
            new Tretja.Nocitev(osebe[7], cilji[17], 2007),
            new Tretja.Nocitev(osebe[4], cilji[9], 2003),
            new Tretja.Nocitev(osebe[34], cilji[27], 2016),
            new Tretja.Nocitev(osebe[36], cilji[20], 2016),
            new Tretja.Nocitev(osebe[6], cilji[11], 2003),
            new Tretja.Nocitev(osebe[2], cilji[30], 2002),
            new Tretja.Nocitev(osebe[26], cilji[21], 2006),
            new Tretja.Nocitev(osebe[19], cilji[6], 2015),
            new Tretja.Nocitev(osebe[14], cilji[12], 2016),
            new Tretja.Nocitev(osebe[16], cilji[27], 2010),
            new Tretja.Nocitev(osebe[24], cilji[0], 2004),
            new Tretja.Nocitev(osebe[22], cilji[19], 2016),
            new Tretja.Nocitev(osebe[8], cilji[21], 2018),
            new Tretja.Nocitev(osebe[20], cilji[31], 2012),
            new Tretja.Nocitev(osebe[13], cilji[5], 2010),
            new Tretja.Nocitev(osebe[14], cilji[24], 2005),
            new Tretja.Nocitev(osebe[9], cilji[10], 2018),
            new Tretja.Nocitev(osebe[5], cilji[2], 2013),
            new Tretja.Nocitev(osebe[26], cilji[21], 2006),
            new Tretja.Nocitev(osebe[26], cilji[21], 2016),
            new Tretja.Nocitev(osebe[7], cilji[17], 2002),
            new Tretja.Nocitev(osebe[6], cilji[16], 2017),
            new Tretja.Nocitev(osebe[36], cilji[20], 2018),
            new Tretja.Nocitev(osebe[18], cilji[21], 2004),
            new Tretja.Nocitev(osebe[13], cilji[5], 2018),
            new Tretja.Nocitev(osebe[12], cilji[21], 2007),
            new Tretja.Nocitev(osebe[8], cilji[14], 2019),
            new Tretja.Nocitev(osebe[17], cilji[19], 2018),
            new Tretja.Nocitev(osebe[2], cilji[30], 2014),
            new Tretja.Nocitev(osebe[30], cilji[24], 2010),
            new Tretja.Nocitev(osebe[19], cilji[6], 2003),
            new Tretja.Nocitev(osebe[3], cilji[23], 2014),
            new Tretja.Nocitev(osebe[28], cilji[18], 2000),
            new Tretja.Nocitev(osebe[36], cilji[20], 2010),
            new Tretja.Nocitev(osebe[6], cilji[11], 2009),
            new Tretja.Nocitev(osebe[27], cilji[25], 2016),
            new Tretja.Nocitev(osebe[15], cilji[26], 2016),
            new Tretja.Nocitev(osebe[20], cilji[31], 2018),
            new Tretja.Nocitev(osebe[24], cilji[18], 2011),
            new Tretja.Nocitev(osebe[32], cilji[0], 2000),
            new Tretja.Nocitev(osebe[30], cilji[24], 2004),
            new Tretja.Nocitev(osebe[28], cilji[18], 2012),
            new Tretja.Nocitev(osebe[10], cilji[3], 2007),
            new Tretja.Nocitev(osebe[36], cilji[20], 2015),
            new Tretja.Nocitev(osebe[13], cilji[5], 2013),
            new Tretja.Nocitev(osebe[1], cilji[0], 2016),
            new Tretja.Nocitev(osebe[37], cilji[20], 2007),
            new Tretja.Nocitev(osebe[26], cilji[21], 2020),
            new Tretja.Nocitev(osebe[10], cilji[4], 2016),
            new Tretja.Nocitev(osebe[18], cilji[21], 2003),
            new Tretja.Nocitev(osebe[33], cilji[22], 2008),
            new Tretja.Nocitev(osebe[10], cilji[8], 2004),
            new Tretja.Nocitev(osebe[27], cilji[25], 2013),
            new Tretja.Nocitev(osebe[35], cilji[26], 2017),
            new Tretja.Nocitev(osebe[31], cilji[31], 2002),
            new Tretja.Nocitev(osebe[30], cilji[24], 2015),
            new Tretja.Nocitev(osebe[32], cilji[19], 2010),
            new Tretja.Nocitev(osebe[25], cilji[18], 2018),
            new Tretja.Nocitev(osebe[5], cilji[2], 2004),
            new Tretja.Nocitev(osebe[21], cilji[14], 2004),
            new Tretja.Nocitev(osebe[31], cilji[31], 2010),
            new Tretja.Nocitev(osebe[7], cilji[10], 2012),
            new Tretja.Nocitev(osebe[2], cilji[30], 2008),
            new Tretja.Nocitev(osebe[17], cilji[22], 2013),
            new Tretja.Nocitev(osebe[21], cilji[19], 2003),
            new Tretja.Nocitev(osebe[8], cilji[13], 2019),
            new Tretja.Nocitev(osebe[15], cilji[26], 2009),
            new Tretja.Nocitev(osebe[6], cilji[19], 2014),
            new Tretja.Nocitev(osebe[13], cilji[5], 2004),
            new Tretja.Nocitev(osebe[36], cilji[20], 2013),
            new Tretja.Nocitev(osebe[0], cilji[26], 2017),
            new Tretja.Nocitev(osebe[11], cilji[1], 2011),
            new Tretja.Nocitev(osebe[0], cilji[12], 2009),
            new Tretja.Nocitev(osebe[28], cilji[18], 2009),
            new Tretja.Nocitev(osebe[9], cilji[1], 2002),
            new Tretja.Nocitev(osebe[23], cilji[27], 2020),
            new Tretja.Nocitev(osebe[11], cilji[18], 2003),
            new Tretja.Nocitev(osebe[9], cilji[0], 2018),
            new Tretja.Nocitev(osebe[4], cilji[9], 2008),
            new Tretja.Nocitev(osebe[8], cilji[16], 2020),
            new Tretja.Nocitev(osebe[30], cilji[24], 2020),
            new Tretja.Nocitev(osebe[8], cilji[29], 2004),
            new Tretja.Nocitev(osebe[12], cilji[21], 2010),
            new Tretja.Nocitev(osebe[2], cilji[30], 2019),
            new Tretja.Nocitev(osebe[11], cilji[24], 2007),
            new Tretja.Nocitev(osebe[35], cilji[26], 2013),
            new Tretja.Nocitev(osebe[29], cilji[22], 2003),
            new Tretja.Nocitev(osebe[37], cilji[2], 2003),
            new Tretja.Nocitev(osebe[35], cilji[26], 2005),
            new Tretja.Nocitev(osebe[7], cilji[27], 2009),
            new Tretja.Nocitev(osebe[37], cilji[2], 2016),
            new Tretja.Nocitev(osebe[1], cilji[0], 2017),
            new Tretja.Nocitev(osebe[11], cilji[15], 2002),
            new Tretja.Nocitev(osebe[6], cilji[6], 2010),
            new Tretja.Nocitev(osebe[11], cilji[32], 2010),
            new Tretja.Nocitev(osebe[9], cilji[32], 2015),
            new Tretja.Nocitev(osebe[22], cilji[4], 2012),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
