
public class Test22 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Blxm Ckwt", "Vzln"),
            new Tretja.Oseba("Wenq Bvhd", "Jvjb"),
            new Tretja.Oseba("Issx Zukg", "Qnwx"),
            new Tretja.Oseba("Yktp Nkth", "Aimv"),
            new Tretja.Oseba("Ebxe Wnkq", "Vzln"),
            new Tretja.Oseba("Wpac Zcin", "Aimv"),
            new Tretja.Oseba("Sira Cfhh", "Qnwx"),
            new Tretja.Oseba("Oafo Hpwh", "Jvjb"),
            new Tretja.Oseba("Klda Wgdj", "Jvjb"),
            new Tretja.Oseba("Env Vcog", "Qnwx"),
            new Tretja.Oseba("Xbpi Kqfx", "Jvjb"),
            new Tretja.Oseba("Jzvf Roki", "Jvjb"),
            new Tretja.Oseba("Szas Zlq", "Vzln"),
            new Tretja.Oseba("Fjpb Bxvn", "Jvjb"),
            new Tretja.Oseba("Rsgs Vixx", "Qnwx"),
            new Tretja.Oseba("Bpjw Hszg", "Vzln"),
            new Tretja.Oseba("Glkx Fxtc", "Jvjb"),
            new Tretja.Oseba("Bczl Jwx", "Qnwx"),
            new Tretja.Oseba("Ulav Xypc", "Aimv"),
            new Tretja.Oseba("Urdm Esyh", "Vzln"),
            new Tretja.Oseba("Skfo Oazy", "Jvjb"),
            new Tretja.Oseba("Dkol Nkyb", "Qnwx"),
            new Tretja.Oseba("Oeya Etjj", "Jvjb"),
            new Tretja.Oseba("Savv Lswx", "Aimv"),
            new Tretja.Oseba("Vws Nwyl", "Jvjb"),
            new Tretja.Oseba("Wtcs Pucn", "Qnwx"),
            new Tretja.Oseba("Kzsb Lacd", "Aimv"),
            new Tretja.Oseba("Fhpg Kvfp", "Qnwx"),
            new Tretja.Oseba("Awmx Bvdg", "Jvjb"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Zvcy", "Jvjb"),
            new Tretja.Cilj("Yeuy", "Vzln"),
            new Tretja.Cilj("Dykb", "Qnwx"),
            new Tretja.Cilj("Gohn", "Qnwx"),
            new Tretja.Cilj("Tsnr", "Aimv"),
            new Tretja.Cilj("Tbgr", "Aimv"),
            new Tretja.Cilj("Mnlc", "Jvjb"),
            new Tretja.Cilj("Pqnr", "Vzln"),
            new Tretja.Cilj("Ajse", "Aimv"),
            new Tretja.Cilj("Czup", "Vzln"),
            new Tretja.Cilj("Cfue", "Aimv"),
            new Tretja.Cilj("Lylr", "Jvjb"),
            new Tretja.Cilj("Bvnp", "Vzln"),
            new Tretja.Cilj("Kcvj", "Vzln"),
            new Tretja.Cilj("Gpxk", "Jvjb"),
            new Tretja.Cilj("Mkbe", "Vzln"),
            new Tretja.Cilj("Clys", "Qnwx"),
            new Tretja.Cilj("Jjnc", "Aimv"),
            new Tretja.Cilj("Jtaz", "Qnwx"),
            new Tretja.Cilj("Unou", "Vzln"),
            new Tretja.Cilj("Eoxb", "Jvjb"),
            new Tretja.Cilj("Ngrs", "Jvjb"),
            new Tretja.Cilj("Hlba", "Qnwx"),
            new Tretja.Cilj("Ibqm", "Aimv"),
            new Tretja.Cilj("Dkyh", "Aimv"),
            new Tretja.Cilj("Wjml", "Qnwx"),
            new Tretja.Cilj("Rvxu", "Qnwx"),
            new Tretja.Cilj("Uplg", "Aimv"),
            new Tretja.Cilj("Izfp", "Jvjb"),
            new Tretja.Cilj("Kzlp", "Qnwx"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[6], cilji[5], 2007),
            new Tretja.Nocitev(osebe[5], cilji[4], 2003),
            new Tretja.Nocitev(osebe[9], cilji[5], 2005),
            new Tretja.Nocitev(osebe[15], cilji[1], 2010),
            new Tretja.Nocitev(osebe[10], cilji[6], 2003),
            new Tretja.Nocitev(osebe[3], cilji[15], 2011),
            new Tretja.Nocitev(osebe[13], cilji[14], 2005),
            new Tretja.Nocitev(osebe[2], cilji[18], 2018),
            new Tretja.Nocitev(osebe[23], cilji[14], 2003),
            new Tretja.Nocitev(osebe[4], cilji[26], 2011),
            new Tretja.Nocitev(osebe[9], cilji[0], 2006),
            new Tretja.Nocitev(osebe[5], cilji[7], 2010),
            new Tretja.Nocitev(osebe[0], cilji[6], 2007),
            new Tretja.Nocitev(osebe[12], cilji[13], 2000),
            new Tretja.Nocitev(osebe[27], cilji[4], 2009),
            new Tretja.Nocitev(osebe[5], cilji[5], 2003),
            new Tretja.Nocitev(osebe[4], cilji[20], 2006),
            new Tretja.Nocitev(osebe[13], cilji[14], 2001),
            new Tretja.Nocitev(osebe[25], cilji[6], 2007),
            new Tretja.Nocitev(osebe[12], cilji[13], 2019),
            new Tretja.Nocitev(osebe[6], cilji[15], 2012),
            new Tretja.Nocitev(osebe[25], cilji[6], 2003),
            new Tretja.Nocitev(osebe[9], cilji[16], 2011),
            new Tretja.Nocitev(osebe[11], cilji[22], 2011),
            new Tretja.Nocitev(osebe[21], cilji[27], 2009),
            new Tretja.Nocitev(osebe[6], cilji[19], 2007),
            new Tretja.Nocitev(osebe[4], cilji[22], 2019),
            new Tretja.Nocitev(osebe[24], cilji[6], 2004),
            new Tretja.Nocitev(osebe[14], cilji[2], 2017),
            new Tretja.Nocitev(osebe[16], cilji[25], 2014),
            new Tretja.Nocitev(osebe[26], cilji[14], 2006),
            new Tretja.Nocitev(osebe[25], cilji[6], 2004),
            new Tretja.Nocitev(osebe[12], cilji[13], 2011),
            new Tretja.Nocitev(osebe[23], cilji[14], 2016),
            new Tretja.Nocitev(osebe[27], cilji[4], 2019),
            new Tretja.Nocitev(osebe[2], cilji[0], 2014),
            new Tretja.Nocitev(osebe[20], cilji[28], 2018),
            new Tretja.Nocitev(osebe[11], cilji[22], 2008),
            new Tretja.Nocitev(osebe[16], cilji[7], 2001),
            new Tretja.Nocitev(osebe[13], cilji[14], 2013),
            new Tretja.Nocitev(osebe[10], cilji[6], 2018),
            new Tretja.Nocitev(osebe[25], cilji[6], 2017),
            new Tretja.Nocitev(osebe[23], cilji[14], 2008),
            new Tretja.Nocitev(osebe[20], cilji[28], 2005),
            new Tretja.Nocitev(osebe[23], cilji[14], 2009),
            new Tretja.Nocitev(osebe[17], cilji[22], 2020),
            new Tretja.Nocitev(osebe[18], cilji[26], 2020),
            new Tretja.Nocitev(osebe[2], cilji[24], 2020),
            new Tretja.Nocitev(osebe[2], cilji[12], 2004),
            new Tretja.Nocitev(osebe[14], cilji[2], 2018),
            new Tretja.Nocitev(osebe[17], cilji[22], 2015),
            new Tretja.Nocitev(osebe[5], cilji[27], 2014),
            new Tretja.Nocitev(osebe[5], cilji[27], 2019),
            new Tretja.Nocitev(osebe[20], cilji[28], 2008),
            new Tretja.Nocitev(osebe[10], cilji[6], 2013),
            new Tretja.Nocitev(osebe[2], cilji[23], 2000),
            new Tretja.Nocitev(osebe[11], cilji[22], 2008),
            new Tretja.Nocitev(osebe[17], cilji[22], 2013),
            new Tretja.Nocitev(osebe[17], cilji[22], 2011),
            new Tretja.Nocitev(osebe[25], cilji[6], 2003),
            new Tretja.Nocitev(osebe[17], cilji[22], 2013),
            new Tretja.Nocitev(osebe[24], cilji[6], 2008),
            new Tretja.Nocitev(osebe[20], cilji[28], 2001),
            new Tretja.Nocitev(osebe[16], cilji[24], 2009),
            new Tretja.Nocitev(osebe[11], cilji[22], 2008),
            new Tretja.Nocitev(osebe[9], cilji[18], 2012),
            new Tretja.Nocitev(osebe[9], cilji[20], 2012),
            new Tretja.Nocitev(osebe[11], cilji[22], 2012),
            new Tretja.Nocitev(osebe[24], cilji[6], 2007),
            new Tretja.Nocitev(osebe[18], cilji[5], 2005),
            new Tretja.Nocitev(osebe[13], cilji[14], 2014),
            new Tretja.Nocitev(osebe[17], cilji[22], 2015),
            new Tretja.Nocitev(osebe[9], cilji[3], 2007),
            new Tretja.Nocitev(osebe[0], cilji[15], 2000),
            new Tretja.Nocitev(osebe[14], cilji[2], 2006),
            new Tretja.Nocitev(osebe[3], cilji[15], 2003),
            new Tretja.Nocitev(osebe[3], cilji[15], 2012),
            new Tretja.Nocitev(osebe[8], cilji[13], 2002),
            new Tretja.Nocitev(osebe[12], cilji[13], 2015),
            new Tretja.Nocitev(osebe[1], cilji[20], 2007),
            new Tretja.Nocitev(osebe[20], cilji[28], 2008),
            new Tretja.Nocitev(osebe[17], cilji[22], 2017),
            new Tretja.Nocitev(osebe[17], cilji[22], 2000),
            new Tretja.Nocitev(osebe[15], cilji[17], 2020),
            new Tretja.Nocitev(osebe[9], cilji[9], 2017),
            new Tretja.Nocitev(osebe[28], cilji[3], 2014),
            new Tretja.Nocitev(osebe[0], cilji[17], 2004),
            new Tretja.Nocitev(osebe[17], cilji[22], 2011),
            new Tretja.Nocitev(osebe[16], cilji[18], 2007),
            new Tretja.Nocitev(osebe[2], cilji[10], 2002),
            new Tretja.Nocitev(osebe[24], cilji[6], 2013),
            new Tretja.Nocitev(osebe[3], cilji[15], 2012),
            new Tretja.Nocitev(osebe[16], cilji[18], 2008),
            new Tretja.Nocitev(osebe[20], cilji[28], 2013),
            new Tretja.Nocitev(osebe[11], cilji[22], 2006),
            new Tretja.Nocitev(osebe[27], cilji[4], 2010),
            new Tretja.Nocitev(osebe[21], cilji[27], 2004),
            new Tretja.Nocitev(osebe[9], cilji[22], 2011),
            new Tretja.Nocitev(osebe[5], cilji[14], 2020),
            new Tretja.Nocitev(osebe[16], cilji[11], 2018),
            new Tretja.Nocitev(osebe[9], cilji[5], 2012),
            new Tretja.Nocitev(osebe[6], cilji[26], 2002),
            new Tretja.Nocitev(osebe[12], cilji[13], 2015),
            new Tretja.Nocitev(osebe[8], cilji[14], 2010),
            new Tretja.Nocitev(osebe[27], cilji[4], 2017),
            new Tretja.Nocitev(osebe[16], cilji[23], 2004),
            new Tretja.Nocitev(osebe[9], cilji[21], 2009),
            new Tretja.Nocitev(osebe[17], cilji[22], 2009),
            new Tretja.Nocitev(osebe[7], cilji[16], 2016),
            new Tretja.Nocitev(osebe[7], cilji[12], 2018),
            new Tretja.Nocitev(osebe[21], cilji[27], 2015),
            new Tretja.Nocitev(osebe[27], cilji[4], 2011),
            new Tretja.Nocitev(osebe[14], cilji[2], 2016),
            new Tretja.Nocitev(osebe[16], cilji[24], 2003),
            new Tretja.Nocitev(osebe[0], cilji[4], 2004),
            new Tretja.Nocitev(osebe[11], cilji[22], 2016),
            new Tretja.Nocitev(osebe[28], cilji[3], 2019),
            new Tretja.Nocitev(osebe[11], cilji[22], 2009),
            new Tretja.Nocitev(osebe[11], cilji[22], 2009),
            new Tretja.Nocitev(osebe[28], cilji[3], 2002),
            new Tretja.Nocitev(osebe[27], cilji[4], 2009),
            new Tretja.Nocitev(osebe[12], cilji[13], 2019),
            new Tretja.Nocitev(osebe[20], cilji[28], 2011),
            new Tretja.Nocitev(osebe[25], cilji[6], 2003),
            new Tretja.Nocitev(osebe[10], cilji[6], 2014),
            new Tretja.Nocitev(osebe[2], cilji[24], 2020),
            new Tretja.Nocitev(osebe[13], cilji[14], 2017),
            new Tretja.Nocitev(osebe[17], cilji[22], 2020),
            new Tretja.Nocitev(osebe[23], cilji[14], 2005),
            new Tretja.Nocitev(osebe[3], cilji[15], 2010),
            new Tretja.Nocitev(osebe[5], cilji[15], 2002),
            new Tretja.Nocitev(osebe[10], cilji[6], 2010),
            new Tretja.Nocitev(osebe[15], cilji[8], 2014),
            new Tretja.Nocitev(osebe[23], cilji[14], 2018),
            new Tretja.Nocitev(osebe[12], cilji[13], 2005),
            new Tretja.Nocitev(osebe[23], cilji[14], 2005),
            new Tretja.Nocitev(osebe[21], cilji[27], 2000),
            new Tretja.Nocitev(osebe[24], cilji[6], 2010),
            new Tretja.Nocitev(osebe[9], cilji[0], 2017),
            new Tretja.Nocitev(osebe[14], cilji[2], 2005),
            new Tretja.Nocitev(osebe[25], cilji[6], 2014),
            new Tretja.Nocitev(osebe[8], cilji[8], 2016),
            new Tretja.Nocitev(osebe[10], cilji[6], 2013),
            new Tretja.Nocitev(osebe[25], cilji[6], 2000),
            new Tretja.Nocitev(osebe[6], cilji[2], 2013),
            new Tretja.Nocitev(osebe[13], cilji[14], 2005),
            new Tretja.Nocitev(osebe[3], cilji[15], 2007),
            new Tretja.Nocitev(osebe[17], cilji[22], 2007),
            new Tretja.Nocitev(osebe[10], cilji[6], 2004),
            new Tretja.Nocitev(osebe[6], cilji[25], 2010),
            new Tretja.Nocitev(osebe[21], cilji[27], 2004),
            new Tretja.Nocitev(osebe[27], cilji[4], 2013),
            new Tretja.Nocitev(osebe[25], cilji[6], 2012),
            new Tretja.Nocitev(osebe[7], cilji[17], 2019),
            new Tretja.Nocitev(osebe[19], cilji[25], 2020),
            new Tretja.Nocitev(osebe[21], cilji[27], 2015),
            new Tretja.Nocitev(osebe[25], cilji[6], 2011),
            new Tretja.Nocitev(osebe[19], cilji[26], 2009),
            new Tretja.Nocitev(osebe[14], cilji[2], 2016),
            new Tretja.Nocitev(osebe[11], cilji[22], 2014),
            new Tretja.Nocitev(osebe[25], cilji[6], 2019),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
