
public class Test50 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Cosx Yerq", "Inca"),
            new Tretja.Oseba("Dttu Jzgo", "Xywd"),
            new Tretja.Oseba("Bxmu Opnu", "Xywd"),
            new Tretja.Oseba("Eajk Mfbx", "Inca"),
            new Tretja.Oseba("Fktf Jjkj", "Xywd"),
            new Tretja.Oseba("Vei Vccq", "Slpl"),
            new Tretja.Oseba("Fyao Gemt", "Inca"),
            new Tretja.Oseba("Dsny Adss", "Inca"),
            new Tretja.Oseba("Jyfd Ebkn", "Xywd"),
            new Tretja.Oseba("Wzip Dldb", "Bzdk"),
            new Tretja.Oseba("Zwht Wdnq", "Xywd"),
            new Tretja.Oseba("Obse Vvpm", "Slpl"),
            new Tretja.Oseba("Wfwy Dehw", "Bzdk"),
            new Tretja.Oseba("Tiin Eukg", "Xywd"),
            new Tretja.Oseba("Yfbl Wt", "Inca"),
            new Tretja.Oseba("Jlev Bxba", "Slpl"),
            new Tretja.Oseba("Coox Nebq", "Zgvy"),
            new Tretja.Oseba("Duea Jrff", "Zgvy"),
            new Tretja.Oseba("Kakh Mxmy", "Bzdk"),
            new Tretja.Oseba("Cyjx Qbl", "Bzdk"),
            new Tretja.Oseba("Wmni Npqj", "Slpl"),
            new Tretja.Oseba("Mcjn Igpf", "Xywd"),
            new Tretja.Oseba("Bozw Tglg", "Zgvy"),
            new Tretja.Oseba("Cfps Jpwc", "Inca"),
            new Tretja.Oseba("Jqx Hrgb", "Slpl"),
            new Tretja.Oseba("Wswz Padp", "Zgvy"),
            new Tretja.Oseba("Golt Tbad", "Zgvy"),
            new Tretja.Oseba("Btsl Zkmo", "Bzdk"),
            new Tretja.Oseba("Oqal Ywwc", "Bzdk"),
            new Tretja.Oseba("Glfj Augl", "Xywd"),
            new Tretja.Oseba("Une Rvxb", "Bzdk"),
            new Tretja.Oseba("Smzo Mbux", "Zgvy"),
            new Tretja.Oseba("Virh Wkfa", "Slpl"),
            new Tretja.Oseba("Xkof Xuya", "Inca"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Pcax", "Xywd"),
            new Tretja.Cilj("Rdrw", "Inca"),
            new Tretja.Cilj("Sfzl", "Inca"),
            new Tretja.Cilj("Inyg", "Xywd"),
            new Tretja.Cilj("Euli", "Xywd"),
            new Tretja.Cilj("Dvbn", "Bzdk"),
            new Tretja.Cilj("Rkzc", "Bzdk"),
            new Tretja.Cilj("Veng", "Xywd"),
            new Tretja.Cilj("Mgzt", "Xywd"),
            new Tretja.Cilj("Bnmc", "Slpl"),
            new Tretja.Cilj("Driy", "Bzdk"),
            new Tretja.Cilj("Jeee", "Zgvy"),
            new Tretja.Cilj("Uhue", "Xywd"),
            new Tretja.Cilj("Lshy", "Zgvy"),
            new Tretja.Cilj("Yghk", "Bzdk"),
            new Tretja.Cilj("Yjrn", "Zgvy"),
            new Tretja.Cilj("Pshs", "Xywd"),
            new Tretja.Cilj("Ufji", "Slpl"),
            new Tretja.Cilj("Evqk", "Inca"),
            new Tretja.Cilj("Ppik", "Xywd"),
            new Tretja.Cilj("Ehgo", "Xywd"),
            new Tretja.Cilj("Rmbm", "Inca"),
            new Tretja.Cilj("Edzp", "Inca"),
            new Tretja.Cilj("Lzjp", "Zgvy"),
            new Tretja.Cilj("Whma", "Bzdk"),
            new Tretja.Cilj("Mjdv", "Bzdk"),
            new Tretja.Cilj("Klhd", "Slpl"),
            new Tretja.Cilj("Cfza", "Xywd"),
            new Tretja.Cilj("Mojf", "Inca"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[15], cilji[17], 2013),
            new Tretja.Nocitev(osebe[8], cilji[24], 2007),
            new Tretja.Nocitev(osebe[1], cilji[13], 2017),
            new Tretja.Nocitev(osebe[32], cilji[26], 2013),
            new Tretja.Nocitev(osebe[4], cilji[14], 2017),
            new Tretja.Nocitev(osebe[22], cilji[22], 2008),
            new Tretja.Nocitev(osebe[5], cilji[6], 2006),
            new Tretja.Nocitev(osebe[33], cilji[19], 2018),
            new Tretja.Nocitev(osebe[27], cilji[18], 2015),
            new Tretja.Nocitev(osebe[25], cilji[27], 2004),
            new Tretja.Nocitev(osebe[16], cilji[10], 2019),
            new Tretja.Nocitev(osebe[17], cilji[27], 2008),
            new Tretja.Nocitev(osebe[2], cilji[21], 2006),
            new Tretja.Nocitev(osebe[6], cilji[25], 2008),
            new Tretja.Nocitev(osebe[18], cilji[26], 2012),
            new Tretja.Nocitev(osebe[14], cilji[19], 2002),
            new Tretja.Nocitev(osebe[5], cilji[19], 2019),
            new Tretja.Nocitev(osebe[31], cilji[16], 2011),
            new Tretja.Nocitev(osebe[25], cilji[5], 2016),
            new Tretja.Nocitev(osebe[18], cilji[26], 2007),
            new Tretja.Nocitev(osebe[10], cilji[23], 2016),
            new Tretja.Nocitev(osebe[8], cilji[7], 2015),
            new Tretja.Nocitev(osebe[11], cilji[3], 2003),
            new Tretja.Nocitev(osebe[30], cilji[7], 2004),
            new Tretja.Nocitev(osebe[17], cilji[27], 2002),
            new Tretja.Nocitev(osebe[9], cilji[13], 2011),
            new Tretja.Nocitev(osebe[30], cilji[28], 2010),
            new Tretja.Nocitev(osebe[13], cilji[20], 2020),
            new Tretja.Nocitev(osebe[25], cilji[20], 2015),
            new Tretja.Nocitev(osebe[20], cilji[22], 2017),
            new Tretja.Nocitev(osebe[27], cilji[18], 2016),
            new Tretja.Nocitev(osebe[9], cilji[13], 2007),
            new Tretja.Nocitev(osebe[18], cilji[26], 2017),
            new Tretja.Nocitev(osebe[15], cilji[11], 2010),
            new Tretja.Nocitev(osebe[19], cilji[0], 2014),
            new Tretja.Nocitev(osebe[16], cilji[10], 2004),
            new Tretja.Nocitev(osebe[30], cilji[24], 2015),
            new Tretja.Nocitev(osebe[18], cilji[26], 2006),
            new Tretja.Nocitev(osebe[13], cilji[20], 2014),
            new Tretja.Nocitev(osebe[30], cilji[13], 2012),
            new Tretja.Nocitev(osebe[25], cilji[4], 2004),
            new Tretja.Nocitev(osebe[28], cilji[5], 2008),
            new Tretja.Nocitev(osebe[10], cilji[13], 2009),
            new Tretja.Nocitev(osebe[14], cilji[27], 2018),
            new Tretja.Nocitev(osebe[12], cilji[15], 2008),
            new Tretja.Nocitev(osebe[4], cilji[14], 2007),
            new Tretja.Nocitev(osebe[17], cilji[27], 2015),
            new Tretja.Nocitev(osebe[9], cilji[13], 2005),
            new Tretja.Nocitev(osebe[21], cilji[7], 2011),
            new Tretja.Nocitev(osebe[25], cilji[12], 2012),
            new Tretja.Nocitev(osebe[18], cilji[26], 2013),
            new Tretja.Nocitev(osebe[26], cilji[6], 2006),
            new Tretja.Nocitev(osebe[2], cilji[21], 2005),
            new Tretja.Nocitev(osebe[19], cilji[0], 2002),
            new Tretja.Nocitev(osebe[13], cilji[20], 2005),
            new Tretja.Nocitev(osebe[32], cilji[26], 2005),
            new Tretja.Nocitev(osebe[28], cilji[5], 2011),
            new Tretja.Nocitev(osebe[11], cilji[14], 2009),
            new Tretja.Nocitev(osebe[32], cilji[26], 2009),
            new Tretja.Nocitev(osebe[11], cilji[18], 2016),
            new Tretja.Nocitev(osebe[10], cilji[8], 2016),
            new Tretja.Nocitev(osebe[4], cilji[14], 2018),
            new Tretja.Nocitev(osebe[26], cilji[24], 2017),
            new Tretja.Nocitev(osebe[31], cilji[6], 2000),
            new Tretja.Nocitev(osebe[5], cilji[15], 2008),
            new Tretja.Nocitev(osebe[19], cilji[0], 2011),
            new Tretja.Nocitev(osebe[32], cilji[26], 2013),
            new Tretja.Nocitev(osebe[23], cilji[5], 2007),
            new Tretja.Nocitev(osebe[12], cilji[9], 2016),
            new Tretja.Nocitev(osebe[22], cilji[22], 2002),
            new Tretja.Nocitev(osebe[14], cilji[15], 2020),
            new Tretja.Nocitev(osebe[11], cilji[28], 2014),
            new Tretja.Nocitev(osebe[13], cilji[20], 2009),
            new Tretja.Nocitev(osebe[10], cilji[24], 2019),
            new Tretja.Nocitev(osebe[30], cilji[10], 2000),
            new Tretja.Nocitev(osebe[13], cilji[20], 2002),
            new Tretja.Nocitev(osebe[3], cilji[5], 2001),
            new Tretja.Nocitev(osebe[30], cilji[17], 2006),
            new Tretja.Nocitev(osebe[20], cilji[2], 2010),
            new Tretja.Nocitev(osebe[30], cilji[11], 2001),
            new Tretja.Nocitev(osebe[12], cilji[12], 2008),
            new Tretja.Nocitev(osebe[14], cilji[21], 2001),
            new Tretja.Nocitev(osebe[17], cilji[27], 2014),
            new Tretja.Nocitev(osebe[11], cilji[7], 2000),
            new Tretja.Nocitev(osebe[7], cilji[4], 2010),
            new Tretja.Nocitev(osebe[21], cilji[18], 2003),
            new Tretja.Nocitev(osebe[1], cilji[4], 2020),
            new Tretja.Nocitev(osebe[22], cilji[22], 2010),
            new Tretja.Nocitev(osebe[29], cilji[20], 2001),
            new Tretja.Nocitev(osebe[4], cilji[14], 2020),
            new Tretja.Nocitev(osebe[5], cilji[28], 2002),
            new Tretja.Nocitev(osebe[3], cilji[5], 2010),
            new Tretja.Nocitev(osebe[25], cilji[10], 2018),
            new Tretja.Nocitev(osebe[11], cilji[6], 2003),
            new Tretja.Nocitev(osebe[7], cilji[5], 2009),
            new Tretja.Nocitev(osebe[13], cilji[20], 2019),
            new Tretja.Nocitev(osebe[24], cilji[21], 2018),
            new Tretja.Nocitev(osebe[12], cilji[18], 2009),
            new Tretja.Nocitev(osebe[27], cilji[18], 2012),
            new Tretja.Nocitev(osebe[25], cilji[11], 2010),
            new Tretja.Nocitev(osebe[11], cilji[3], 2014),
            new Tretja.Nocitev(osebe[4], cilji[14], 2014),
            new Tretja.Nocitev(osebe[23], cilji[5], 2001),
            new Tretja.Nocitev(osebe[31], cilji[2], 2014),
            new Tretja.Nocitev(osebe[10], cilji[20], 2007),
            new Tretja.Nocitev(osebe[18], cilji[26], 2015),
            new Tretja.Nocitev(osebe[0], cilji[26], 2000),
            new Tretja.Nocitev(osebe[26], cilji[18], 2019),
            new Tretja.Nocitev(osebe[9], cilji[13], 2016),
            new Tretja.Nocitev(osebe[21], cilji[21], 2010),
            new Tretja.Nocitev(osebe[26], cilji[15], 2002),
            new Tretja.Nocitev(osebe[33], cilji[19], 2006),
            new Tretja.Nocitev(osebe[30], cilji[16], 2005),
            new Tretja.Nocitev(osebe[22], cilji[22], 2009),
            new Tretja.Nocitev(osebe[15], cilji[20], 2004),
            new Tretja.Nocitev(osebe[4], cilji[14], 2002),
            new Tretja.Nocitev(osebe[24], cilji[28], 2007),
            new Tretja.Nocitev(osebe[29], cilji[20], 2019),
            new Tretja.Nocitev(osebe[24], cilji[16], 2004),
            new Tretja.Nocitev(osebe[17], cilji[27], 2007),
            new Tretja.Nocitev(osebe[23], cilji[5], 2005),
            new Tretja.Nocitev(osebe[13], cilji[20], 2010),
            new Tretja.Nocitev(osebe[7], cilji[11], 2009),
            new Tretja.Nocitev(osebe[12], cilji[0], 2018),
            new Tretja.Nocitev(osebe[20], cilji[11], 2001),
            new Tretja.Nocitev(osebe[21], cilji[24], 2004),
            new Tretja.Nocitev(osebe[22], cilji[22], 2014),
            new Tretja.Nocitev(osebe[6], cilji[25], 2016),
            new Tretja.Nocitev(osebe[11], cilji[0], 2014),
            new Tretja.Nocitev(osebe[25], cilji[26], 2010),
            new Tretja.Nocitev(osebe[4], cilji[14], 2015),
            new Tretja.Nocitev(osebe[14], cilji[22], 2004),
            new Tretja.Nocitev(osebe[33], cilji[19], 2003),
            new Tretja.Nocitev(osebe[32], cilji[26], 2003),
            new Tretja.Nocitev(osebe[24], cilji[7], 2008),
            new Tretja.Nocitev(osebe[18], cilji[26], 2014),
            new Tretja.Nocitev(osebe[2], cilji[21], 2020),
            new Tretja.Nocitev(osebe[33], cilji[19], 2013),
            new Tretja.Nocitev(osebe[33], cilji[19], 2010),
            new Tretja.Nocitev(osebe[15], cilji[15], 2008),
            new Tretja.Nocitev(osebe[30], cilji[5], 2003),
            new Tretja.Nocitev(osebe[26], cilji[22], 2005),
            new Tretja.Nocitev(osebe[28], cilji[5], 2014),
            new Tretja.Nocitev(osebe[4], cilji[14], 2005),
            new Tretja.Nocitev(osebe[18], cilji[26], 2010),
            new Tretja.Nocitev(osebe[26], cilji[4], 2001),
            new Tretja.Nocitev(osebe[21], cilji[9], 2010),
            new Tretja.Nocitev(osebe[8], cilji[9], 2012),
            new Tretja.Nocitev(osebe[16], cilji[10], 2017),
            new Tretja.Nocitev(osebe[20], cilji[21], 2019),
            new Tretja.Nocitev(osebe[13], cilji[20], 2005),
            new Tretja.Nocitev(osebe[32], cilji[26], 2011),
            new Tretja.Nocitev(osebe[4], cilji[14], 2001),
            new Tretja.Nocitev(osebe[31], cilji[28], 2001),
            new Tretja.Nocitev(osebe[6], cilji[25], 2019),
            new Tretja.Nocitev(osebe[6], cilji[25], 2005),
            new Tretja.Nocitev(osebe[13], cilji[20], 2005),
            new Tretja.Nocitev(osebe[21], cilji[12], 2007),
            new Tretja.Nocitev(osebe[1], cilji[25], 2016),
            new Tretja.Nocitev(osebe[11], cilji[3], 2012),
            new Tretja.Nocitev(osebe[9], cilji[13], 2013),
            new Tretja.Nocitev(osebe[10], cilji[16], 2003),
            new Tretja.Nocitev(osebe[27], cilji[18], 2000),
            new Tretja.Nocitev(osebe[27], cilji[18], 2005),
            new Tretja.Nocitev(osebe[19], cilji[0], 2001),
            new Tretja.Nocitev(osebe[13], cilji[20], 2018),
            new Tretja.Nocitev(osebe[29], cilji[20], 2018),
            new Tretja.Nocitev(osebe[3], cilji[5], 2004),
            new Tretja.Nocitev(osebe[27], cilji[18], 2002),
            new Tretja.Nocitev(osebe[15], cilji[22], 2002),
            new Tretja.Nocitev(osebe[1], cilji[12], 2004),
            new Tretja.Nocitev(osebe[16], cilji[10], 2017),
            new Tretja.Nocitev(osebe[1], cilji[23], 2018),
            new Tretja.Nocitev(osebe[31], cilji[18], 2009),
            new Tretja.Nocitev(osebe[23], cilji[5], 2019),
            new Tretja.Nocitev(osebe[22], cilji[22], 2019),
            new Tretja.Nocitev(osebe[10], cilji[15], 2000),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2003, 2013);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
