
public class Test03 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Slvg Zwqf", "Zbwq"),
            new Tretja.Oseba("Uzbp Ddaw", "Zbwq"),
            new Tretja.Oseba("Hxuc Rrz", "Zbwq"),
            new Tretja.Oseba("Nigv Cmyt", "Zbwq"),
            new Tretja.Oseba("Cpya Scrf", "Nlrz"),
            new Tretja.Oseba("Ckon Xzts", "Zbwq"),
            new Tretja.Oseba("Njjd Spay", "Nlrz"),
            new Tretja.Oseba("Ykey Innz", "Nlrz"),
            new Tretja.Oseba("Rbtz Ncth", "Zbwq"),
            new Tretja.Oseba("Kbed Vjjv", "Zbwq"),
            new Tretja.Oseba("Kein Fxuy", "Nlrz"),
            new Tretja.Oseba("Zajf Mwkc", "Zbwq"),
            new Tretja.Oseba("Vwlm Dxbb", "Zbwq"),
            new Tretja.Oseba("Vagm Mogl", "Zbwq"),
            new Tretja.Oseba("Cpbq Xweh", "Zbwq"),
            new Tretja.Oseba("Eisn Taym", "Zbwq"),
            new Tretja.Oseba("Ftxh Hgnu", "Nlrz"),
            new Tretja.Oseba("Jtvo Srzt", "Zbwq"),
            new Tretja.Oseba("Nfwk Vuzg", "Nlrz"),
            new Tretja.Oseba("Eequ Uzxd", "Zbwq"),
            new Tretja.Oseba("Lviu Pziv", "Nlrz"),
            new Tretja.Oseba("Louu Hojk", "Zbwq"),
            new Tretja.Oseba("Crju Fzmw", "Nlrz"),
            new Tretja.Oseba("Azln Idrk", "Nlrz"),
            new Tretja.Oseba("Yvpb Nhqr", "Nlrz"),
            new Tretja.Oseba("Fcvp Kjqy", "Zbwq"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Cmpd", "Zbwq"),
            new Tretja.Cilj("Pewh", "Zbwq"),
            new Tretja.Cilj("Upqm", "Nlrz"),
            new Tretja.Cilj("Ewlk", "Zbwq"),
            new Tretja.Cilj("Cftm", "Nlrz"),
            new Tretja.Cilj("Luhi", "Nlrz"),
            new Tretja.Cilj("Wzng", "Nlrz"),
            new Tretja.Cilj("Udrx", "Zbwq"),
            new Tretja.Cilj("Fkjj", "Nlrz"),
            new Tretja.Cilj("Ubuf", "Zbwq"),
            new Tretja.Cilj("Fpyi", "Nlrz"),
            new Tretja.Cilj("Pfjw", "Nlrz"),
            new Tretja.Cilj("Rkbh", "Nlrz"),
            new Tretja.Cilj("Wxxp", "Zbwq"),
            new Tretja.Cilj("Hysu", "Zbwq"),
            new Tretja.Cilj("Yeul", "Nlrz"),
            new Tretja.Cilj("Cjnd", "Zbwq"),
            new Tretja.Cilj("Visy", "Nlrz"),
            new Tretja.Cilj("Jzlb", "Zbwq"),
            new Tretja.Cilj("Zuvy", "Nlrz"),
            new Tretja.Cilj("Hmok", "Nlrz"),
            new Tretja.Cilj("Bqzc", "Zbwq"),
            new Tretja.Cilj("Exrp", "Zbwq"),
            new Tretja.Cilj("Fwnx", "Zbwq"),
            new Tretja.Cilj("Rete", "Nlrz"),
            new Tretja.Cilj("Cgxr", "Zbwq"),
            new Tretja.Cilj("Xmkb", "Zbwq"),
            new Tretja.Cilj("Mvnl", "Zbwq"),
            new Tretja.Cilj("Fgzk", "Nlrz"),
            new Tretja.Cilj("Kavk", "Nlrz"),
            new Tretja.Cilj("Tkeq", "Zbwq"),
            new Tretja.Cilj("Cxgt", "Nlrz"),
            new Tretja.Cilj("Mvvy", "Zbwq"),
            new Tretja.Cilj("Vzah", "Nlrz"),
            new Tretja.Cilj("Ygrq", "Zbwq"),
            new Tretja.Cilj("Zdlp", "Zbwq"),
            new Tretja.Cilj("Sgff", "Nlrz"),
            new Tretja.Cilj("Ugbq", "Nlrz"),
            new Tretja.Cilj("Rvwg", "Nlrz"),
            new Tretja.Cilj("Cdih", "Zbwq"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[3], cilji[34], 2014),
            new Tretja.Nocitev(osebe[7], cilji[2], 2004),
            new Tretja.Nocitev(osebe[3], cilji[34], 2014),
            new Tretja.Nocitev(osebe[7], cilji[8], 2005),
            new Tretja.Nocitev(osebe[5], cilji[34], 2019),
            new Tretja.Nocitev(osebe[8], cilji[37], 2013),
            new Tretja.Nocitev(osebe[12], cilji[11], 2017),
            new Tretja.Nocitev(osebe[16], cilji[0], 2017),
            new Tretja.Nocitev(osebe[20], cilji[33], 2003),
            new Tretja.Nocitev(osebe[15], cilji[20], 2018),
            new Tretja.Nocitev(osebe[0], cilji[13], 2001),
            new Tretja.Nocitev(osebe[3], cilji[34], 2002),
            new Tretja.Nocitev(osebe[6], cilji[19], 2009),
            new Tretja.Nocitev(osebe[8], cilji[32], 2008),
            new Tretja.Nocitev(osebe[6], cilji[32], 2011),
            new Tretja.Nocitev(osebe[19], cilji[17], 2016),
            new Tretja.Nocitev(osebe[20], cilji[33], 2020),
            new Tretja.Nocitev(osebe[5], cilji[34], 2004),
            new Tretja.Nocitev(osebe[24], cilji[3], 2006),
            new Tretja.Nocitev(osebe[16], cilji[15], 2017),
            new Tretja.Nocitev(osebe[3], cilji[34], 2011),
            new Tretja.Nocitev(osebe[24], cilji[3], 2020),
            new Tretja.Nocitev(osebe[17], cilji[28], 2013),
            new Tretja.Nocitev(osebe[20], cilji[33], 2001),
            new Tretja.Nocitev(osebe[9], cilji[37], 2016),
            new Tretja.Nocitev(osebe[1], cilji[15], 2014),
            new Tretja.Nocitev(osebe[9], cilji[17], 2001),
            new Tretja.Nocitev(osebe[23], cilji[19], 2009),
            new Tretja.Nocitev(osebe[20], cilji[33], 2002),
            new Tretja.Nocitev(osebe[21], cilji[7], 2015),
            new Tretja.Nocitev(osebe[15], cilji[20], 2005),
            new Tretja.Nocitev(osebe[12], cilji[36], 2003),
            new Tretja.Nocitev(osebe[25], cilji[24], 2013),
            new Tretja.Nocitev(osebe[2], cilji[24], 2002),
            new Tretja.Nocitev(osebe[2], cilji[24], 2004),
            new Tretja.Nocitev(osebe[20], cilji[33], 2014),
            new Tretja.Nocitev(osebe[8], cilji[4], 2015),
            new Tretja.Nocitev(osebe[6], cilji[3], 2019),
            new Tretja.Nocitev(osebe[8], cilji[14], 2018),
            new Tretja.Nocitev(osebe[8], cilji[23], 2019),
            new Tretja.Nocitev(osebe[2], cilji[24], 2011),
            new Tretja.Nocitev(osebe[17], cilji[28], 2004),
            new Tretja.Nocitev(osebe[3], cilji[34], 2020),
            new Tretja.Nocitev(osebe[7], cilji[23], 2006),
            new Tretja.Nocitev(osebe[17], cilji[28], 2018),
            new Tretja.Nocitev(osebe[23], cilji[19], 2014),
            new Tretja.Nocitev(osebe[12], cilji[36], 2000),
            new Tretja.Nocitev(osebe[13], cilji[27], 2007),
            new Tretja.Nocitev(osebe[21], cilji[7], 2001),
            new Tretja.Nocitev(osebe[24], cilji[3], 2009),
            new Tretja.Nocitev(osebe[19], cilji[17], 2002),
            new Tretja.Nocitev(osebe[17], cilji[28], 2013),
            new Tretja.Nocitev(osebe[0], cilji[29], 2016),
            new Tretja.Nocitev(osebe[14], cilji[23], 2018),
            new Tretja.Nocitev(osebe[21], cilji[7], 2014),
            new Tretja.Nocitev(osebe[22], cilji[3], 2006),
            new Tretja.Nocitev(osebe[24], cilji[3], 2020),
            new Tretja.Nocitev(osebe[22], cilji[3], 2009),
            new Tretja.Nocitev(osebe[21], cilji[7], 2016),
            new Tretja.Nocitev(osebe[20], cilji[33], 2010),
            new Tretja.Nocitev(osebe[18], cilji[14], 2006),
            new Tretja.Nocitev(osebe[19], cilji[17], 2009),
            new Tretja.Nocitev(osebe[12], cilji[22], 2013),
            new Tretja.Nocitev(osebe[8], cilji[31], 2011),
            new Tretja.Nocitev(osebe[8], cilji[24], 2006),
            new Tretja.Nocitev(osebe[10], cilji[29], 2014),
            new Tretja.Nocitev(osebe[6], cilji[38], 2007),
            new Tretja.Nocitev(osebe[3], cilji[34], 2012),
            new Tretja.Nocitev(osebe[2], cilji[24], 2000),
            new Tretja.Nocitev(osebe[9], cilji[32], 2008),
            new Tretja.Nocitev(osebe[10], cilji[29], 2011),
            new Tretja.Nocitev(osebe[21], cilji[7], 2004),
            new Tretja.Nocitev(osebe[1], cilji[15], 2005),
            new Tretja.Nocitev(osebe[5], cilji[34], 2004),
            new Tretja.Nocitev(osebe[4], cilji[20], 2018),
            new Tretja.Nocitev(osebe[15], cilji[20], 2006),
            new Tretja.Nocitev(osebe[23], cilji[19], 2000),
            new Tretja.Nocitev(osebe[5], cilji[34], 2017),
            new Tretja.Nocitev(osebe[8], cilji[38], 2011),
            new Tretja.Nocitev(osebe[3], cilji[34], 2011),
            new Tretja.Nocitev(osebe[3], cilji[34], 2012),
            new Tretja.Nocitev(osebe[11], cilji[35], 2003),
            new Tretja.Nocitev(osebe[23], cilji[19], 2015),
            new Tretja.Nocitev(osebe[11], cilji[35], 2018),
            new Tretja.Nocitev(osebe[5], cilji[34], 2017),
            new Tretja.Nocitev(osebe[19], cilji[17], 2002),
            new Tretja.Nocitev(osebe[22], cilji[10], 2006),
            new Tretja.Nocitev(osebe[10], cilji[29], 2019),
            new Tretja.Nocitev(osebe[7], cilji[24], 2017),
            new Tretja.Nocitev(osebe[5], cilji[34], 2017),
            new Tretja.Nocitev(osebe[12], cilji[32], 2003),
            new Tretja.Nocitev(osebe[7], cilji[31], 2009),
            new Tretja.Nocitev(osebe[4], cilji[4], 2005),
            new Tretja.Nocitev(osebe[15], cilji[20], 2003),
            new Tretja.Nocitev(osebe[21], cilji[7], 2006),
            new Tretja.Nocitev(osebe[5], cilji[34], 2020),
            new Tretja.Nocitev(osebe[15], cilji[20], 2018),
            new Tretja.Nocitev(osebe[5], cilji[34], 2019),
            new Tretja.Nocitev(osebe[5], cilji[34], 2019),
            new Tretja.Nocitev(osebe[4], cilji[35], 2003),
            new Tretja.Nocitev(osebe[14], cilji[22], 2013),
            new Tretja.Nocitev(osebe[18], cilji[35], 2005),
            new Tretja.Nocitev(osebe[22], cilji[27], 2010),
            new Tretja.Nocitev(osebe[1], cilji[15], 2016),
            new Tretja.Nocitev(osebe[12], cilji[38], 2003),
            new Tretja.Nocitev(osebe[11], cilji[35], 2008),
            new Tretja.Nocitev(osebe[2], cilji[24], 2009),
            new Tretja.Nocitev(osebe[24], cilji[3], 2005),
            new Tretja.Nocitev(osebe[24], cilji[3], 2019),
            new Tretja.Nocitev(osebe[4], cilji[30], 2015),
            new Tretja.Nocitev(osebe[21], cilji[7], 2020),
            new Tretja.Nocitev(osebe[12], cilji[39], 2016),
            new Tretja.Nocitev(osebe[17], cilji[28], 2007),
            new Tretja.Nocitev(osebe[23], cilji[19], 2014),
            new Tretja.Nocitev(osebe[18], cilji[7], 2015),
            new Tretja.Nocitev(osebe[14], cilji[6], 2017),
            new Tretja.Nocitev(osebe[2], cilji[24], 2000),
            new Tretja.Nocitev(osebe[25], cilji[4], 2019),
            new Tretja.Nocitev(osebe[1], cilji[15], 2020),
            new Tretja.Nocitev(osebe[3], cilji[34], 2015),
            new Tretja.Nocitev(osebe[24], cilji[3], 2014),
            new Tretja.Nocitev(osebe[19], cilji[17], 2019),
            new Tretja.Nocitev(osebe[16], cilji[35], 2010),
            new Tretja.Nocitev(osebe[7], cilji[38], 2018),
            new Tretja.Nocitev(osebe[2], cilji[24], 2019),
            new Tretja.Nocitev(osebe[14], cilji[25], 2020),
            new Tretja.Nocitev(osebe[5], cilji[34], 2005),
            new Tretja.Nocitev(osebe[8], cilji[9], 2006),
            new Tretja.Nocitev(osebe[3], cilji[34], 2015),
            new Tretja.Nocitev(osebe[10], cilji[29], 2001),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
