
public class Test47 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Gmzf Duvr", "Fzsw"),
            new Tretja.Oseba("Npbj Ynfx", "Nfll"),
            new Tretja.Oseba("Jthy Ceqf", "Wewe"),
            new Tretja.Oseba("Hgau Ghmn", "Nfll"),
            new Tretja.Oseba("Dmsb Uruu", "Wewe"),
            new Tretja.Oseba("Eagm Odze", "Wewe"),
            new Tretja.Oseba("Betd Xgqj", "Fzsw"),
            new Tretja.Oseba("Ciur Nxlg", "Fzsw"),
            new Tretja.Oseba("Yrzh Ezrf", "Fzsw"),
            new Tretja.Oseba("Fctw Iazn", "Fzsw"),
            new Tretja.Oseba("Kzgc Wlpc", "Fzsw"),
            new Tretja.Oseba("Tjsj Pnes", "Fzsw"),
            new Tretja.Oseba("Scn Vpxl", "Fzsw"),
            new Tretja.Oseba("Nwjd Aadg", "Fzsw"),
            new Tretja.Oseba("Wtkb Rmiu", "Wewe"),
            new Tretja.Oseba("Mktb Wmgo", "Nfll"),
            new Tretja.Oseba("Pycy Fyl", "Fzsw"),
            new Tretja.Oseba("Tggl Hxbz", "Fzsw"),
            new Tretja.Oseba("Hjex Zndc", "Nfll"),
            new Tretja.Oseba("Zkac Uqev", "Fzsw"),
            new Tretja.Oseba("Raaw Lraq", "Wewe"),
            new Tretja.Oseba("Koma Oeeo", "Nfll"),
            new Tretja.Oseba("Gmfb Ktvp", "Fzsw"),
            new Tretja.Oseba("Kwnt Snig", "Wewe"),
            new Tretja.Oseba("Hpko Wtgo", "Nfll"),
            new Tretja.Oseba("Vgop Gbse", "Wewe"),
            new Tretja.Oseba("Tqnx Mzaj", "Wewe"),
            new Tretja.Oseba("Pnac Tthl", "Nfll"),
            new Tretja.Oseba("Oct Ezlu", "Fzsw"),
            new Tretja.Oseba("Krjf Lgvs", "Wewe"),
            new Tretja.Oseba("Wlss Afxt", "Fzsw"),
            new Tretja.Oseba("Dkrr Sibx", "Nfll"),
            new Tretja.Oseba("Hbwq Qgkw", "Fzsw"),
            new Tretja.Oseba("Vipj Olpi", "Nfll"),
            new Tretja.Oseba("Cqbz Dcqq", "Fzsw"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Urgd", "Wewe"),
            new Tretja.Cilj("Iusl", "Wewe"),
            new Tretja.Cilj("Ysjv", "Nfll"),
            new Tretja.Cilj("Qdod", "Nfll"),
            new Tretja.Cilj("Evl", "Wewe"),
            new Tretja.Cilj("Xjny", "Fzsw"),
            new Tretja.Cilj("Ljm", "Wewe"),
            new Tretja.Cilj("Twby", "Nfll"),
            new Tretja.Cilj("Lfgz", "Nfll"),
            new Tretja.Cilj("Mxie", "Fzsw"),
            new Tretja.Cilj("Ulki", "Fzsw"),
            new Tretja.Cilj("Giwa", "Wewe"),
            new Tretja.Cilj("Iqbz", "Fzsw"),
            new Tretja.Cilj("Mhlj", "Fzsw"),
            new Tretja.Cilj("Hdph", "Fzsw"),
            new Tretja.Cilj("Sylt", "Fzsw"),
            new Tretja.Cilj("Sqsg", "Wewe"),
            new Tretja.Cilj("Uzwc", "Fzsw"),
            new Tretja.Cilj("Idtr", "Fzsw"),
            new Tretja.Cilj("Hppl", "Fzsw"),
            new Tretja.Cilj("Wkxv", "Fzsw"),
            new Tretja.Cilj("Kvqw", "Wewe"),
            new Tretja.Cilj("Pvbf", "Nfll"),
            new Tretja.Cilj("Htfn", "Wewe"),
            new Tretja.Cilj("Cqhj", "Nfll"),
            new Tretja.Cilj("Mrjb", "Nfll"),
            new Tretja.Cilj("Zrri", "Fzsw"),
            new Tretja.Cilj("Cqal", "Nfll"),
            new Tretja.Cilj("Mpkv", "Nfll"),
            new Tretja.Cilj("Qyqw", "Fzsw"),
            new Tretja.Cilj("Zuun", "Fzsw"),
            new Tretja.Cilj("Ugqm", "Fzsw"),
            new Tretja.Cilj("Pmdo", "Nfll"),
            new Tretja.Cilj("Wvfp", "Wewe"),
            new Tretja.Cilj("Iuqj", "Fzsw"),
            new Tretja.Cilj("Aemc", "Wewe"),
            new Tretja.Cilj("Dkdi", "Fzsw"),
            new Tretja.Cilj("Reav", "Fzsw"),
            new Tretja.Cilj("Kjuf", "Fzsw"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[29], cilji[4], 2005),
            new Tretja.Nocitev(osebe[4], cilji[31], 2001),
            new Tretja.Nocitev(osebe[29], cilji[11], 2017),
            new Tretja.Nocitev(osebe[23], cilji[7], 2015),
            new Tretja.Nocitev(osebe[27], cilji[13], 2013),
            new Tretja.Nocitev(osebe[25], cilji[2], 2010),
            new Tretja.Nocitev(osebe[29], cilji[17], 2013),
            new Tretja.Nocitev(osebe[18], cilji[27], 2015),
            new Tretja.Nocitev(osebe[33], cilji[2], 2004),
            new Tretja.Nocitev(osebe[6], cilji[6], 2007),
            new Tretja.Nocitev(osebe[16], cilji[36], 2011),
            new Tretja.Nocitev(osebe[8], cilji[6], 2010),
            new Tretja.Nocitev(osebe[24], cilji[32], 2004),
            new Tretja.Nocitev(osebe[22], cilji[3], 2008),
            new Tretja.Nocitev(osebe[22], cilji[3], 2012),
            new Tretja.Nocitev(osebe[8], cilji[38], 2015),
            new Tretja.Nocitev(osebe[9], cilji[3], 2020),
            new Tretja.Nocitev(osebe[1], cilji[26], 2001),
            new Tretja.Nocitev(osebe[1], cilji[35], 2010),
            new Tretja.Nocitev(osebe[20], cilji[9], 2005),
            new Tretja.Nocitev(osebe[16], cilji[10], 2018),
            new Tretja.Nocitev(osebe[30], cilji[12], 2011),
            new Tretja.Nocitev(osebe[22], cilji[3], 2019),
            new Tretja.Nocitev(osebe[8], cilji[7], 2002),
            new Tretja.Nocitev(osebe[13], cilji[6], 2007),
            new Tretja.Nocitev(osebe[29], cilji[27], 2008),
            new Tretja.Nocitev(osebe[13], cilji[1], 2011),
            new Tretja.Nocitev(osebe[19], cilji[28], 2003),
            new Tretja.Nocitev(osebe[4], cilji[6], 2016),
            new Tretja.Nocitev(osebe[22], cilji[3], 2020),
            new Tretja.Nocitev(osebe[0], cilji[6], 2002),
            new Tretja.Nocitev(osebe[14], cilji[26], 2007),
            new Tretja.Nocitev(osebe[5], cilji[34], 2007),
            new Tretja.Nocitev(osebe[21], cilji[27], 2012),
            new Tretja.Nocitev(osebe[11], cilji[2], 2010),
            new Tretja.Nocitev(osebe[25], cilji[14], 2016),
            new Tretja.Nocitev(osebe[30], cilji[3], 2015),
            new Tretja.Nocitev(osebe[9], cilji[7], 2006),
            new Tretja.Nocitev(osebe[32], cilji[24], 2004),
            new Tretja.Nocitev(osebe[4], cilji[23], 2011),
            new Tretja.Nocitev(osebe[7], cilji[5], 2017),
            new Tretja.Nocitev(osebe[24], cilji[18], 2005),
            new Tretja.Nocitev(osebe[9], cilji[28], 2003),
            new Tretja.Nocitev(osebe[17], cilji[38], 2006),
            new Tretja.Nocitev(osebe[30], cilji[5], 2016),
            new Tretja.Nocitev(osebe[15], cilji[5], 2010),
            new Tretja.Nocitev(osebe[22], cilji[3], 2018),
            new Tretja.Nocitev(osebe[29], cilji[26], 2018),
            new Tretja.Nocitev(osebe[3], cilji[7], 2013),
            new Tretja.Nocitev(osebe[4], cilji[30], 2017),
            new Tretja.Nocitev(osebe[8], cilji[33], 2011),
            new Tretja.Nocitev(osebe[30], cilji[18], 2015),
            new Tretja.Nocitev(osebe[19], cilji[28], 2007),
            new Tretja.Nocitev(osebe[14], cilji[5], 2015),
            new Tretja.Nocitev(osebe[1], cilji[28], 2000),
            new Tretja.Nocitev(osebe[28], cilji[21], 2015),
            new Tretja.Nocitev(osebe[1], cilji[6], 2016),
            new Tretja.Nocitev(osebe[3], cilji[7], 2002),
            new Tretja.Nocitev(osebe[14], cilji[2], 2001),
            new Tretja.Nocitev(osebe[11], cilji[13], 2014),
            new Tretja.Nocitev(osebe[19], cilji[28], 2007),
            new Tretja.Nocitev(osebe[23], cilji[7], 2009),
            new Tretja.Nocitev(osebe[24], cilji[22], 2009),
            new Tretja.Nocitev(osebe[19], cilji[28], 2005),
            new Tretja.Nocitev(osebe[12], cilji[7], 2003),
            new Tretja.Nocitev(osebe[8], cilji[11], 2012),
            new Tretja.Nocitev(osebe[3], cilji[7], 2018),
            new Tretja.Nocitev(osebe[17], cilji[38], 2003),
            new Tretja.Nocitev(osebe[17], cilji[38], 2015),
            new Tretja.Nocitev(osebe[21], cilji[27], 2007),
            new Tretja.Nocitev(osebe[3], cilji[7], 2010),
            new Tretja.Nocitev(osebe[4], cilji[25], 2012),
            new Tretja.Nocitev(osebe[34], cilji[33], 2003),
            new Tretja.Nocitev(osebe[34], cilji[35], 2005),
            new Tretja.Nocitev(osebe[8], cilji[23], 2006),
            new Tretja.Nocitev(osebe[14], cilji[28], 2003),
            new Tretja.Nocitev(osebe[22], cilji[3], 2015),
            new Tretja.Nocitev(osebe[10], cilji[22], 2016),
            new Tretja.Nocitev(osebe[32], cilji[24], 2011),
            new Tretja.Nocitev(osebe[3], cilji[7], 2011),
            new Tretja.Nocitev(osebe[9], cilji[13], 2010),
            new Tretja.Nocitev(osebe[19], cilji[28], 2016),
            new Tretja.Nocitev(osebe[30], cilji[24], 2005),
            new Tretja.Nocitev(osebe[16], cilji[21], 2011),
            new Tretja.Nocitev(osebe[2], cilji[4], 2016),
            new Tretja.Nocitev(osebe[2], cilji[28], 2018),
            new Tretja.Nocitev(osebe[10], cilji[22], 2016),
            new Tretja.Nocitev(osebe[32], cilji[24], 2010),
            new Tretja.Nocitev(osebe[30], cilji[37], 2015),
            new Tretja.Nocitev(osebe[28], cilji[21], 2018),
            new Tretja.Nocitev(osebe[5], cilji[4], 2018),
            new Tretja.Nocitev(osebe[13], cilji[33], 2002),
            new Tretja.Nocitev(osebe[19], cilji[28], 2002),
            new Tretja.Nocitev(osebe[26], cilji[20], 2020),
            new Tretja.Nocitev(osebe[32], cilji[24], 2017),
            new Tretja.Nocitev(osebe[24], cilji[29], 2018),
            new Tretja.Nocitev(osebe[5], cilji[28], 2005),
            new Tretja.Nocitev(osebe[24], cilji[8], 2009),
            new Tretja.Nocitev(osebe[13], cilji[24], 2005),
            new Tretja.Nocitev(osebe[23], cilji[7], 2015),
            new Tretja.Nocitev(osebe[32], cilji[24], 2016),
            new Tretja.Nocitev(osebe[0], cilji[12], 2002),
            new Tretja.Nocitev(osebe[28], cilji[21], 2002),
            new Tretja.Nocitev(osebe[9], cilji[15], 2002),
            new Tretja.Nocitev(osebe[34], cilji[8], 2020),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2012, 2020);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
