
public class Test32 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Wgvi Xzii", "Kjtt"),
            new Tretja.Oseba("Aae Cthr", "Kjtt"),
            new Tretja.Oseba("Gru Jrzn", "Kjtt"),
            new Tretja.Oseba("Xsvr Ujqn", "Qgdz"),
            new Tretja.Oseba("Qwrg Qiwp", "Qgdz"),
            new Tretja.Oseba("Sdgu Jmzu", "Kjtt"),
            new Tretja.Oseba("Eiam Kqnw", "Kjtt"),
            new Tretja.Oseba("Bkwl Rpsi", "Kjtt"),
            new Tretja.Oseba("Rovh Azvd", "Qgdz"),
            new Tretja.Oseba("Efqc Ikky", "Kjtt"),
            new Tretja.Oseba("Abdt Gfxw", "Qgdz"),
            new Tretja.Oseba("Bxdq Tmjr", "Qgdz"),
            new Tretja.Oseba("Mxig Dmtl", "Qgdz"),
            new Tretja.Oseba("Hiwe Tcxf", "Qgdz"),
            new Tretja.Oseba("Jrhb Hzhz", "Qgdz"),
            new Tretja.Oseba("Qjhp Rpdx", "Kjtt"),
            new Tretja.Oseba("Kcbb Yqgt", "Kjtt"),
            new Tretja.Oseba("Bmce Nptl", "Kjtt"),
            new Tretja.Oseba("Qhkl Cva", "Kjtt"),
            new Tretja.Oseba("Fjgk Eoip", "Kjtt"),
            new Tretja.Oseba("Mxex Pdzy", "Qgdz"),
            new Tretja.Oseba("Sivw Xihz", "Qgdz"),
            new Tretja.Oseba("Jiep Gcyu", "Qgdz"),
            new Tretja.Oseba("Rufl Pgvp", "Qgdz"),
            new Tretja.Oseba("Glql Rza", "Kjtt"),
            new Tretja.Oseba("Otrg Ypsn", "Qgdz"),
            new Tretja.Oseba("Ella Tcaw", "Qgdz"),
            new Tretja.Oseba("Behe Nwyj", "Qgdz"),
            new Tretja.Oseba("Heub Gjme", "Kjtt"),
            new Tretja.Oseba("Xaid Srli", "Kjtt"),
            new Tretja.Oseba("Vzje Cfps", "Qgdz"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Zptn", "Kjtt"),
            new Tretja.Cilj("Jayb", "Qgdz"),
            new Tretja.Cilj("Qfsq", "Kjtt"),
            new Tretja.Cilj("Zoaj", "Kjtt"),
            new Tretja.Cilj("Absa", "Qgdz"),
            new Tretja.Cilj("Nukn", "Qgdz"),
            new Tretja.Cilj("Zikx", "Qgdz"),
            new Tretja.Cilj("Crku", "Kjtt"),
            new Tretja.Cilj("Muri", "Kjtt"),
            new Tretja.Cilj("Oyuh", "Qgdz"),
            new Tretja.Cilj("Kpfd", "Qgdz"),
            new Tretja.Cilj("Ftvj", "Qgdz"),
            new Tretja.Cilj("Vvio", "Qgdz"),
            new Tretja.Cilj("Elfr", "Qgdz"),
            new Tretja.Cilj("Ntqe", "Qgdz"),
            new Tretja.Cilj("Byex", "Qgdz"),
            new Tretja.Cilj("Xpnc", "Qgdz"),
            new Tretja.Cilj("Zdmh", "Qgdz"),
            new Tretja.Cilj("Mfco", "Qgdz"),
            new Tretja.Cilj("Zjio", "Qgdz"),
            new Tretja.Cilj("Wbip", "Qgdz"),
            new Tretja.Cilj("Upze", "Kjtt"),
            new Tretja.Cilj("Raha", "Kjtt"),
            new Tretja.Cilj("Ddel", "Kjtt"),
            new Tretja.Cilj("Bzxg", "Qgdz"),
            new Tretja.Cilj("Szfq", "Kjtt"),
            new Tretja.Cilj("Sqdu", "Qgdz"),
            new Tretja.Cilj("Vufr", "Kjtt"),
            new Tretja.Cilj("Quko", "Kjtt"),
            new Tretja.Cilj("Rrs", "Kjtt"),
            new Tretja.Cilj("Zgvt", "Kjtt"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[27], cilji[18], 2001),
            new Tretja.Nocitev(osebe[20], cilji[13], 2001),
            new Tretja.Nocitev(osebe[8], cilji[19], 2013),
            new Tretja.Nocitev(osebe[1], cilji[9], 2017),
            new Tretja.Nocitev(osebe[16], cilji[8], 2007),
            new Tretja.Nocitev(osebe[30], cilji[16], 2009),
            new Tretja.Nocitev(osebe[5], cilji[14], 2011),
            new Tretja.Nocitev(osebe[13], cilji[11], 2020),
            new Tretja.Nocitev(osebe[26], cilji[12], 2019),
            new Tretja.Nocitev(osebe[19], cilji[6], 2004),
            new Tretja.Nocitev(osebe[18], cilji[12], 2000),
            new Tretja.Nocitev(osebe[2], cilji[14], 2006),
            new Tretja.Nocitev(osebe[8], cilji[29], 2017),
            new Tretja.Nocitev(osebe[9], cilji[7], 2001),
            new Tretja.Nocitev(osebe[12], cilji[11], 2010),
            new Tretja.Nocitev(osebe[18], cilji[12], 2015),
            new Tretja.Nocitev(osebe[27], cilji[26], 2001),
            new Tretja.Nocitev(osebe[6], cilji[5], 2009),
            new Tretja.Nocitev(osebe[8], cilji[14], 2004),
            new Tretja.Nocitev(osebe[5], cilji[12], 2013),
            new Tretja.Nocitev(osebe[2], cilji[14], 2011),
            new Tretja.Nocitev(osebe[30], cilji[16], 2016),
            new Tretja.Nocitev(osebe[3], cilji[28], 2010),
            new Tretja.Nocitev(osebe[16], cilji[8], 2003),
            new Tretja.Nocitev(osebe[7], cilji[9], 2012),
            new Tretja.Nocitev(osebe[7], cilji[27], 2012),
            new Tretja.Nocitev(osebe[18], cilji[12], 2015),
            new Tretja.Nocitev(osebe[8], cilji[27], 2019),
            new Tretja.Nocitev(osebe[7], cilji[1], 2020),
            new Tretja.Nocitev(osebe[23], cilji[16], 2012),
            new Tretja.Nocitev(osebe[13], cilji[1], 2010),
            new Tretja.Nocitev(osebe[1], cilji[7], 2001),
            new Tretja.Nocitev(osebe[23], cilji[16], 2011),
            new Tretja.Nocitev(osebe[3], cilji[28], 2016),
            new Tretja.Nocitev(osebe[2], cilji[14], 2017),
            new Tretja.Nocitev(osebe[28], cilji[2], 2019),
            new Tretja.Nocitev(osebe[25], cilji[22], 2003),
            new Tretja.Nocitev(osebe[12], cilji[11], 2007),
            new Tretja.Nocitev(osebe[11], cilji[3], 2000),
            new Tretja.Nocitev(osebe[11], cilji[3], 2010),
            new Tretja.Nocitev(osebe[21], cilji[18], 2009),
            new Tretja.Nocitev(osebe[12], cilji[11], 2008),
            new Tretja.Nocitev(osebe[20], cilji[13], 2014),
            new Tretja.Nocitev(osebe[14], cilji[7], 2004),
            new Tretja.Nocitev(osebe[21], cilji[18], 2013),
            new Tretja.Nocitev(osebe[25], cilji[29], 2020),
            new Tretja.Nocitev(osebe[4], cilji[7], 2012),
            new Tretja.Nocitev(osebe[30], cilji[14], 2017),
            new Tretja.Nocitev(osebe[26], cilji[17], 2007),
            new Tretja.Nocitev(osebe[0], cilji[28], 2012),
            new Tretja.Nocitev(osebe[22], cilji[18], 2019),
            new Tretja.Nocitev(osebe[12], cilji[11], 2002),
            new Tretja.Nocitev(osebe[19], cilji[6], 2015),
            new Tretja.Nocitev(osebe[10], cilji[29], 2014),
            new Tretja.Nocitev(osebe[7], cilji[16], 2007),
            new Tretja.Nocitev(osebe[10], cilji[29], 2018),
            new Tretja.Nocitev(osebe[28], cilji[2], 2006),
            new Tretja.Nocitev(osebe[30], cilji[29], 2018),
            new Tretja.Nocitev(osebe[13], cilji[30], 2000),
            new Tretja.Nocitev(osebe[5], cilji[4], 2002),
            new Tretja.Nocitev(osebe[5], cilji[3], 2017),
            new Tretja.Nocitev(osebe[4], cilji[7], 2009),
            new Tretja.Nocitev(osebe[8], cilji[26], 2005),
            new Tretja.Nocitev(osebe[16], cilji[8], 2009),
            new Tretja.Nocitev(osebe[14], cilji[7], 2002),
            new Tretja.Nocitev(osebe[14], cilji[7], 2003),
            new Tretja.Nocitev(osebe[10], cilji[29], 2008),
            new Tretja.Nocitev(osebe[13], cilji[10], 2008),
            new Tretja.Nocitev(osebe[7], cilji[12], 2000),
            new Tretja.Nocitev(osebe[15], cilji[15], 2017),
            new Tretja.Nocitev(osebe[18], cilji[12], 2007),
            new Tretja.Nocitev(osebe[20], cilji[13], 2013),
            new Tretja.Nocitev(osebe[6], cilji[1], 2018),
            new Tretja.Nocitev(osebe[15], cilji[15], 2014),
            new Tretja.Nocitev(osebe[13], cilji[18], 2016),
            new Tretja.Nocitev(osebe[10], cilji[29], 2009),
            new Tretja.Nocitev(osebe[29], cilji[8], 2017),
            new Tretja.Nocitev(osebe[18], cilji[12], 2004),
            new Tretja.Nocitev(osebe[21], cilji[18], 2005),
            new Tretja.Nocitev(osebe[7], cilji[15], 2017),
            new Tretja.Nocitev(osebe[1], cilji[21], 2020),
            new Tretja.Nocitev(osebe[9], cilji[17], 2002),
            new Tretja.Nocitev(osebe[11], cilji[3], 2000),
            new Tretja.Nocitev(osebe[28], cilji[2], 2010),
            new Tretja.Nocitev(osebe[23], cilji[16], 2019),
            new Tretja.Nocitev(osebe[1], cilji[0], 2017),
            new Tretja.Nocitev(osebe[3], cilji[28], 2006),
            new Tretja.Nocitev(osebe[1], cilji[10], 2019),
            new Tretja.Nocitev(osebe[6], cilji[22], 2000),
            new Tretja.Nocitev(osebe[0], cilji[1], 2018),
            new Tretja.Nocitev(osebe[6], cilji[2], 2017),
            new Tretja.Nocitev(osebe[24], cilji[4], 2007),
            new Tretja.Nocitev(osebe[27], cilji[14], 2004),
            new Tretja.Nocitev(osebe[30], cilji[5], 2005),
            new Tretja.Nocitev(osebe[11], cilji[3], 2020),
            new Tretja.Nocitev(osebe[16], cilji[8], 2019),
            new Tretja.Nocitev(osebe[19], cilji[6], 2010),
            new Tretja.Nocitev(osebe[10], cilji[29], 2001),
            new Tretja.Nocitev(osebe[21], cilji[18], 2018),
            new Tretja.Nocitev(osebe[21], cilji[18], 2009),
            new Tretja.Nocitev(osebe[3], cilji[28], 2015),
            new Tretja.Nocitev(osebe[12], cilji[11], 2002),
            new Tretja.Nocitev(osebe[11], cilji[3], 2014),
            new Tretja.Nocitev(osebe[17], cilji[11], 2001),
            new Tretja.Nocitev(osebe[25], cilji[1], 2003),
            new Tretja.Nocitev(osebe[3], cilji[28], 2001),
            new Tretja.Nocitev(osebe[7], cilji[24], 2004),
            new Tretja.Nocitev(osebe[12], cilji[11], 2012),
            new Tretja.Nocitev(osebe[1], cilji[19], 2020),
            new Tretja.Nocitev(osebe[7], cilji[17], 2020),
            new Tretja.Nocitev(osebe[28], cilji[2], 2012),
            new Tretja.Nocitev(osebe[1], cilji[11], 2018),
            new Tretja.Nocitev(osebe[17], cilji[22], 2018),
            new Tretja.Nocitev(osebe[11], cilji[3], 2013),
            new Tretja.Nocitev(osebe[27], cilji[11], 2009),
            new Tretja.Nocitev(osebe[14], cilji[7], 2012),
            new Tretja.Nocitev(osebe[20], cilji[13], 2009),
            new Tretja.Nocitev(osebe[16], cilji[8], 2016),
            new Tretja.Nocitev(osebe[0], cilji[9], 2007),
            new Tretja.Nocitev(osebe[10], cilji[29], 2004),
            new Tretja.Nocitev(osebe[24], cilji[20], 2019),
            new Tretja.Nocitev(osebe[23], cilji[16], 2001),
            new Tretja.Nocitev(osebe[17], cilji[5], 2011),
            new Tretja.Nocitev(osebe[18], cilji[12], 2016),
            new Tretja.Nocitev(osebe[2], cilji[14], 2004),
            new Tretja.Nocitev(osebe[15], cilji[15], 2016),
            new Tretja.Nocitev(osebe[18], cilji[12], 2004),
            new Tretja.Nocitev(osebe[15], cilji[15], 2002),
            new Tretja.Nocitev(osebe[21], cilji[18], 2003),
            new Tretja.Nocitev(osebe[3], cilji[28], 2011),
            new Tretja.Nocitev(osebe[23], cilji[16], 2009),
            new Tretja.Nocitev(osebe[14], cilji[7], 2001),
            new Tretja.Nocitev(osebe[27], cilji[25], 2003),
            new Tretja.Nocitev(osebe[17], cilji[14], 2018),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
