
public class Test09 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Giga Zqeu", "Jjyx"),
            new Tretja.Oseba("Jixw Ujmr", "Xbmj"),
            new Tretja.Oseba("Hyjd Toci", "Jjyx"),
            new Tretja.Oseba("Kkvh Lzvb", "Esmn"),
            new Tretja.Oseba("Ojco Rlut", "Jjyx"),
            new Tretja.Oseba("Tghy Ggye", "Jjyx"),
            new Tretja.Oseba("Nyad Amde", "Esmn"),
            new Tretja.Oseba("Kuas Dsyd", "Jjyx"),
            new Tretja.Oseba("Hsiq Zeoh", "Jjyx"),
            new Tretja.Oseba("Qmm Lmxt", "Jjyx"),
            new Tretja.Oseba("Cika Arja", "Esmn"),
            new Tretja.Oseba("Obli Xfue", "Xbmj"),
            new Tretja.Oseba("Civq Lcyr", "Esmn"),
            new Tretja.Oseba("Ijtp Fupj", "Esmn"),
            new Tretja.Oseba("Enkm Pfuy", "Jjyx"),
            new Tretja.Oseba("Ehyw Edoi", "Jjyx"),
            new Tretja.Oseba("Qenj Yfmt", "Jjyx"),
            new Tretja.Oseba("Xmtp Mjbw", "Esmn"),
            new Tretja.Oseba("Jafx Sedl", "Xbmj"),
            new Tretja.Oseba("Fote Fkq", "Esmn"),
            new Tretja.Oseba("Qrin Tvnj", "Esmn"),
            new Tretja.Oseba("Nvvs Suhe", "Jjyx"),
            new Tretja.Oseba("Nxbz Sgut", "Xbmj"),
            new Tretja.Oseba("Ejjh Pqhi", "Jjyx"),
            new Tretja.Oseba("Zzzq Uuea", "Xbmj"),
            new Tretja.Oseba("Suus Spgz", "Esmn"),
            new Tretja.Oseba("Cekx Umqi", "Esmn"),
            new Tretja.Oseba("Uzht Frdp", "Xbmj"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Mpnk", "Esmn"),
            new Tretja.Cilj("Fcaq", "Esmn"),
            new Tretja.Cilj("Lejh", "Xbmj"),
            new Tretja.Cilj("Nllh", "Jjyx"),
            new Tretja.Cilj("Zoft", "Jjyx"),
            new Tretja.Cilj("Jpbx", "Esmn"),
            new Tretja.Cilj("Utxv", "Jjyx"),
            new Tretja.Cilj("Oibw", "Xbmj"),
            new Tretja.Cilj("Udqu", "Xbmj"),
            new Tretja.Cilj("Ileq", "Jjyx"),
            new Tretja.Cilj("Ts", "Jjyx"),
            new Tretja.Cilj("Wqyd", "Esmn"),
            new Tretja.Cilj("Phhb", "Jjyx"),
            new Tretja.Cilj("Rwwk", "Jjyx"),
            new Tretja.Cilj("Tcwo", "Xbmj"),
            new Tretja.Cilj("Fxhw", "Xbmj"),
            new Tretja.Cilj("Gdhq", "Xbmj"),
            new Tretja.Cilj("Icwp", "Xbmj"),
            new Tretja.Cilj("Uren", "Jjyx"),
            new Tretja.Cilj("Phnp", "Esmn"),
            new Tretja.Cilj("Onyl", "Jjyx"),
            new Tretja.Cilj("Eget", "Jjyx"),
            new Tretja.Cilj("Ctit", "Jjyx"),
            new Tretja.Cilj("Mwgy", "Jjyx"),
            new Tretja.Cilj("Gekp", "Xbmj"),
            new Tretja.Cilj("Szeu", "Xbmj"),
            new Tretja.Cilj("Imxq", "Esmn"),
            new Tretja.Cilj("Npix", "Xbmj"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[12], cilji[21], 2005),
            new Tretja.Nocitev(osebe[15], cilji[1], 2001),
            new Tretja.Nocitev(osebe[9], cilji[19], 2004),
            new Tretja.Nocitev(osebe[10], cilji[5], 2016),
            new Tretja.Nocitev(osebe[13], cilji[1], 2013),
            new Tretja.Nocitev(osebe[19], cilji[26], 2009),
            new Tretja.Nocitev(osebe[5], cilji[11], 2010),
            new Tretja.Nocitev(osebe[26], cilji[3], 2019),
            new Tretja.Nocitev(osebe[24], cilji[26], 2010),
            new Tretja.Nocitev(osebe[12], cilji[9], 2016),
            new Tretja.Nocitev(osebe[17], cilji[16], 2002),
            new Tretja.Nocitev(osebe[9], cilji[19], 2020),
            new Tretja.Nocitev(osebe[1], cilji[25], 2007),
            new Tretja.Nocitev(osebe[1], cilji[25], 2016),
            new Tretja.Nocitev(osebe[27], cilji[17], 2003),
            new Tretja.Nocitev(osebe[16], cilji[27], 2004),
            new Tretja.Nocitev(osebe[26], cilji[3], 2008),
            new Tretja.Nocitev(osebe[12], cilji[8], 2003),
            new Tretja.Nocitev(osebe[5], cilji[13], 2019),
            new Tretja.Nocitev(osebe[0], cilji[24], 2009),
            new Tretja.Nocitev(osebe[13], cilji[9], 2003),
            new Tretja.Nocitev(osebe[0], cilji[16], 2005),
            new Tretja.Nocitev(osebe[5], cilji[0], 2003),
            new Tretja.Nocitev(osebe[0], cilji[24], 2009),
            new Tretja.Nocitev(osebe[13], cilji[7], 2019),
            new Tretja.Nocitev(osebe[26], cilji[3], 2002),
            new Tretja.Nocitev(osebe[5], cilji[12], 2014),
            new Tretja.Nocitev(osebe[24], cilji[26], 2017),
            new Tretja.Nocitev(osebe[19], cilji[19], 2020),
            new Tretja.Nocitev(osebe[19], cilji[4], 2007),
            new Tretja.Nocitev(osebe[20], cilji[20], 2015),
            new Tretja.Nocitev(osebe[19], cilji[23], 2002),
            new Tretja.Nocitev(osebe[14], cilji[22], 2005),
            new Tretja.Nocitev(osebe[1], cilji[25], 2006),
            new Tretja.Nocitev(osebe[24], cilji[26], 2010),
            new Tretja.Nocitev(osebe[24], cilji[26], 2002),
            new Tretja.Nocitev(osebe[27], cilji[17], 2009),
            new Tretja.Nocitev(osebe[21], cilji[20], 2009),
            new Tretja.Nocitev(osebe[26], cilji[3], 2003),
            new Tretja.Nocitev(osebe[11], cilji[8], 2009),
            new Tretja.Nocitev(osebe[6], cilji[0], 2007),
            new Tretja.Nocitev(osebe[11], cilji[8], 2002),
            new Tretja.Nocitev(osebe[27], cilji[17], 2003),
            new Tretja.Nocitev(osebe[11], cilji[8], 2018),
            new Tretja.Nocitev(osebe[14], cilji[22], 2019),
            new Tretja.Nocitev(osebe[22], cilji[8], 2017),
            new Tretja.Nocitev(osebe[12], cilji[16], 2015),
            new Tretja.Nocitev(osebe[9], cilji[19], 2009),
            new Tretja.Nocitev(osebe[15], cilji[2], 2005),
            new Tretja.Nocitev(osebe[1], cilji[25], 2009),
            new Tretja.Nocitev(osebe[1], cilji[25], 2013),
            new Tretja.Nocitev(osebe[2], cilji[4], 2013),
            new Tretja.Nocitev(osebe[4], cilji[22], 2014),
            new Tretja.Nocitev(osebe[12], cilji[18], 2018),
            new Tretja.Nocitev(osebe[6], cilji[0], 2016),
            new Tretja.Nocitev(osebe[16], cilji[0], 2003),
            new Tretja.Nocitev(osebe[6], cilji[0], 2012),
            new Tretja.Nocitev(osebe[3], cilji[2], 2003),
            new Tretja.Nocitev(osebe[8], cilji[12], 2003),
            new Tretja.Nocitev(osebe[12], cilji[25], 2010),
            new Tretja.Nocitev(osebe[19], cilji[13], 2012),
            new Tretja.Nocitev(osebe[22], cilji[8], 2007),
            new Tretja.Nocitev(osebe[26], cilji[3], 2001),
            new Tretja.Nocitev(osebe[8], cilji[17], 2006),
            new Tretja.Nocitev(osebe[18], cilji[6], 2011),
            new Tretja.Nocitev(osebe[14], cilji[22], 2015),
            new Tretja.Nocitev(osebe[1], cilji[25], 2015),
            new Tretja.Nocitev(osebe[3], cilji[2], 2019),
            new Tretja.Nocitev(osebe[22], cilji[8], 2003),
            new Tretja.Nocitev(osebe[21], cilji[5], 2004),
            new Tretja.Nocitev(osebe[22], cilji[8], 2006),
            new Tretja.Nocitev(osebe[15], cilji[6], 2005),
            new Tretja.Nocitev(osebe[11], cilji[8], 2007),
            new Tretja.Nocitev(osebe[26], cilji[3], 2011),
            new Tretja.Nocitev(osebe[9], cilji[19], 2004),
            new Tretja.Nocitev(osebe[16], cilji[19], 2009),
            new Tretja.Nocitev(osebe[3], cilji[2], 2010),
            new Tretja.Nocitev(osebe[8], cilji[11], 2006),
            new Tretja.Nocitev(osebe[3], cilji[2], 2014),
            new Tretja.Nocitev(osebe[20], cilji[6], 2018),
            new Tretja.Nocitev(osebe[12], cilji[9], 2009),
            new Tretja.Nocitev(osebe[7], cilji[0], 2014),
            new Tretja.Nocitev(osebe[14], cilji[22], 2005),
            new Tretja.Nocitev(osebe[7], cilji[27], 2001),
            new Tretja.Nocitev(osebe[17], cilji[14], 2005),
            new Tretja.Nocitev(osebe[12], cilji[11], 2001),
            new Tretja.Nocitev(osebe[12], cilji[13], 2019),
            new Tretja.Nocitev(osebe[15], cilji[17], 2001),
            new Tretja.Nocitev(osebe[3], cilji[2], 2019),
            new Tretja.Nocitev(osebe[4], cilji[22], 2020),
            new Tretja.Nocitev(osebe[17], cilji[18], 2007),
            new Tretja.Nocitev(osebe[26], cilji[3], 2009),
            new Tretja.Nocitev(osebe[9], cilji[19], 2004),
            new Tretja.Nocitev(osebe[25], cilji[3], 2011),
            new Tretja.Nocitev(osebe[26], cilji[3], 2014),
            new Tretja.Nocitev(osebe[9], cilji[19], 2003),
            new Tretja.Nocitev(osebe[3], cilji[2], 2020),
            new Tretja.Nocitev(osebe[1], cilji[25], 2017),
            new Tretja.Nocitev(osebe[19], cilji[5], 2000),
            new Tretja.Nocitev(osebe[13], cilji[3], 2005),
            new Tretja.Nocitev(osebe[9], cilji[19], 2003),
            new Tretja.Nocitev(osebe[24], cilji[26], 2018),
            new Tretja.Nocitev(osebe[20], cilji[0], 2012),
            new Tretja.Nocitev(osebe[11], cilji[8], 2012),
            new Tretja.Nocitev(osebe[7], cilji[5], 2008),
            new Tretja.Nocitev(osebe[23], cilji[16], 2002),
            new Tretja.Nocitev(osebe[19], cilji[27], 2006),
            new Tretja.Nocitev(osebe[6], cilji[0], 2001),
            new Tretja.Nocitev(osebe[23], cilji[16], 2016),
            new Tretja.Nocitev(osebe[9], cilji[19], 2015),
            new Tretja.Nocitev(osebe[13], cilji[0], 2006),
            new Tretja.Nocitev(osebe[27], cilji[17], 2005),
            new Tretja.Nocitev(osebe[11], cilji[8], 2006),
            new Tretja.Nocitev(osebe[1], cilji[25], 2012),
            new Tretja.Nocitev(osebe[9], cilji[19], 2016),
            new Tretja.Nocitev(osebe[6], cilji[0], 2001),
            new Tretja.Nocitev(osebe[0], cilji[11], 2020),
            new Tretja.Nocitev(osebe[27], cilji[17], 2003),
            new Tretja.Nocitev(osebe[0], cilji[15], 2003),
            new Tretja.Nocitev(osebe[9], cilji[19], 2019),
            new Tretja.Nocitev(osebe[19], cilji[8], 2009),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
