
public class Test45 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Sefi Saso", "Olfj"),
            new Tretja.Oseba("Dlpr Eikj", "Ivhi"),
            new Tretja.Oseba("Dovp Uzel", "Pscb"),
            new Tretja.Oseba("Vxfn Rmrw", "Pscb"),
            new Tretja.Oseba("Oohz Kbjk", "Ynj"),
            new Tretja.Oseba("Alst Yrka", "Ynj"),
            new Tretja.Oseba("Hmez Uhv", "Olfj"),
            new Tretja.Oseba("Cvjy Imtl", "Qlgg"),
            new Tretja.Oseba("Dkpa Yhfl", "Ivhi"),
            new Tretja.Oseba("Hlje Ophy", "Ivhi"),
            new Tretja.Oseba("Yydy Dafx", "Olfj"),
            new Tretja.Oseba("Dkm Vajt", "Pscb"),
            new Tretja.Oseba("Csbr Jbcb", "Qlgg"),
            new Tretja.Oseba("Reka Nhtp", "Qlgg"),
            new Tretja.Oseba("Pugj Tbqf", "Ivhi"),
            new Tretja.Oseba("Abdt Ljjn", "Ivhi"),
            new Tretja.Oseba("Ibmr Oejq", "Qlgg"),
            new Tretja.Oseba("Rhbw Qgcl", "Ivhi"),
            new Tretja.Oseba("Syyl Olzq", "Qlgg"),
            new Tretja.Oseba("Ilbu Iyuq", "Ivhi"),
            new Tretja.Oseba("Kprz Lxnt", "Ynj"),
            new Tretja.Oseba("Cxj Dpux", "Ivhi"),
            new Tretja.Oseba("Dtqz Iuwj", "Qlgg"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Aymh", "Ivhi"),
            new Tretja.Cilj("Tytv", "Pscb"),
            new Tretja.Cilj("Ptnw", "Olfj"),
            new Tretja.Cilj("Pzjw", "Ynj"),
            new Tretja.Cilj("Lttz", "Pscb"),
            new Tretja.Cilj("Lgfi", "Qlgg"),
            new Tretja.Cilj("Bzkh", "Ynj"),
            new Tretja.Cilj("Clrl", "Olfj"),
            new Tretja.Cilj("Kqte", "Qlgg"),
            new Tretja.Cilj("Wit", "Olfj"),
            new Tretja.Cilj("Pnap", "Pscb"),
            new Tretja.Cilj("Wyld", "Ivhi"),
            new Tretja.Cilj("Hqcm", "Olfj"),
            new Tretja.Cilj("Tdou", "Ivhi"),
            new Tretja.Cilj("Doad", "Olfj"),
            new Tretja.Cilj("Mcn", "Olfj"),
            new Tretja.Cilj("Alpi", "Ivhi"),
            new Tretja.Cilj("Xwxl", "Qlgg"),
            new Tretja.Cilj("Xway", "Ynj"),
            new Tretja.Cilj("Tjej", "Ivhi"),
            new Tretja.Cilj("Svbj", "Ynj"),
            new Tretja.Cilj("Nqyl", "Qlgg"),
            new Tretja.Cilj("Chuc", "Olfj"),
            new Tretja.Cilj("Vudt", "Qlgg"),
            new Tretja.Cilj("Uogk", "Olfj"),
            new Tretja.Cilj("Cdsw", "Pscb"),
            new Tretja.Cilj("Mbvs", "Pscb"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[5], cilji[22], 2000),
            new Tretja.Nocitev(osebe[18], cilji[2], 2016),
            new Tretja.Nocitev(osebe[7], cilji[9], 2007),
            new Tretja.Nocitev(osebe[16], cilji[4], 2003),
            new Tretja.Nocitev(osebe[4], cilji[6], 2015),
            new Tretja.Nocitev(osebe[15], cilji[12], 2003),
            new Tretja.Nocitev(osebe[18], cilji[3], 2018),
            new Tretja.Nocitev(osebe[22], cilji[5], 2012),
            new Tretja.Nocitev(osebe[22], cilji[5], 2014),
            new Tretja.Nocitev(osebe[7], cilji[9], 2011),
            new Tretja.Nocitev(osebe[22], cilji[5], 2007),
            new Tretja.Nocitev(osebe[9], cilji[24], 2002),
            new Tretja.Nocitev(osebe[8], cilji[6], 2006),
            new Tretja.Nocitev(osebe[21], cilji[19], 2001),
            new Tretja.Nocitev(osebe[12], cilji[26], 2001),
            new Tretja.Nocitev(osebe[10], cilji[21], 2013),
            new Tretja.Nocitev(osebe[12], cilji[26], 2011),
            new Tretja.Nocitev(osebe[21], cilji[18], 2003),
            new Tretja.Nocitev(osebe[10], cilji[5], 2013),
            new Tretja.Nocitev(osebe[5], cilji[22], 2008),
            new Tretja.Nocitev(osebe[21], cilji[15], 2014),
            new Tretja.Nocitev(osebe[13], cilji[22], 2000),
            new Tretja.Nocitev(osebe[22], cilji[5], 2018),
            new Tretja.Nocitev(osebe[4], cilji[6], 2007),
            new Tretja.Nocitev(osebe[10], cilji[4], 2011),
            new Tretja.Nocitev(osebe[18], cilji[6], 2007),
            new Tretja.Nocitev(osebe[20], cilji[25], 2020),
            new Tretja.Nocitev(osebe[6], cilji[18], 2019),
            new Tretja.Nocitev(osebe[14], cilji[2], 2002),
            new Tretja.Nocitev(osebe[19], cilji[25], 2006),
            new Tretja.Nocitev(osebe[9], cilji[5], 2000),
            new Tretja.Nocitev(osebe[19], cilji[4], 2013),
            new Tretja.Nocitev(osebe[14], cilji[1], 2001),
            new Tretja.Nocitev(osebe[1], cilji[22], 2001),
            new Tretja.Nocitev(osebe[4], cilji[6], 2015),
            new Tretja.Nocitev(osebe[7], cilji[9], 2015),
            new Tretja.Nocitev(osebe[16], cilji[4], 2018),
            new Tretja.Nocitev(osebe[18], cilji[1], 2019),
            new Tretja.Nocitev(osebe[6], cilji[12], 2005),
            new Tretja.Nocitev(osebe[16], cilji[4], 2017),
            new Tretja.Nocitev(osebe[4], cilji[6], 2002),
            new Tretja.Nocitev(osebe[0], cilji[17], 2000),
            new Tretja.Nocitev(osebe[13], cilji[22], 2005),
            new Tretja.Nocitev(osebe[0], cilji[17], 2018),
            new Tretja.Nocitev(osebe[0], cilji[17], 2007),
            new Tretja.Nocitev(osebe[21], cilji[7], 2001),
            new Tretja.Nocitev(osebe[15], cilji[12], 2018),
            new Tretja.Nocitev(osebe[3], cilji[1], 2011),
            new Tretja.Nocitev(osebe[20], cilji[25], 2010),
            new Tretja.Nocitev(osebe[0], cilji[17], 2011),
            new Tretja.Nocitev(osebe[4], cilji[6], 2006),
            new Tretja.Nocitev(osebe[8], cilji[1], 2011),
            new Tretja.Nocitev(osebe[13], cilji[22], 2000),
            new Tretja.Nocitev(osebe[16], cilji[4], 2007),
            new Tretja.Nocitev(osebe[22], cilji[5], 2000),
            new Tretja.Nocitev(osebe[10], cilji[24], 2018),
            new Tretja.Nocitev(osebe[1], cilji[23], 2015),
            new Tretja.Nocitev(osebe[13], cilji[22], 2005),
            new Tretja.Nocitev(osebe[16], cilji[4], 2018),
            new Tretja.Nocitev(osebe[2], cilji[7], 2015),
            new Tretja.Nocitev(osebe[10], cilji[11], 2012),
            new Tretja.Nocitev(osebe[17], cilji[14], 2018),
            new Tretja.Nocitev(osebe[5], cilji[10], 2016),
            new Tretja.Nocitev(osebe[0], cilji[17], 2008),
            new Tretja.Nocitev(osebe[22], cilji[5], 2004),
            new Tretja.Nocitev(osebe[8], cilji[5], 2006),
            new Tretja.Nocitev(osebe[5], cilji[26], 2009),
            new Tretja.Nocitev(osebe[2], cilji[10], 2001),
            new Tretja.Nocitev(osebe[15], cilji[12], 2013),
            new Tretja.Nocitev(osebe[12], cilji[26], 2017),
            new Tretja.Nocitev(osebe[5], cilji[15], 2007),
            new Tretja.Nocitev(osebe[18], cilji[25], 2012),
            new Tretja.Nocitev(osebe[2], cilji[24], 2014),
            new Tretja.Nocitev(osebe[10], cilji[14], 2009),
            new Tretja.Nocitev(osebe[9], cilji[7], 2007),
            new Tretja.Nocitev(osebe[3], cilji[7], 2016),
            new Tretja.Nocitev(osebe[13], cilji[22], 2008),
            new Tretja.Nocitev(osebe[16], cilji[4], 2013),
            new Tretja.Nocitev(osebe[18], cilji[19], 2004),
            new Tretja.Nocitev(osebe[11], cilji[2], 2009),
            new Tretja.Nocitev(osebe[21], cilji[21], 2020),
            new Tretja.Nocitev(osebe[9], cilji[7], 2011),
            new Tretja.Nocitev(osebe[10], cilji[1], 2010),
            new Tretja.Nocitev(osebe[2], cilji[26], 2009),
            new Tretja.Nocitev(osebe[22], cilji[5], 2003),
            new Tretja.Nocitev(osebe[4], cilji[6], 2014),
            new Tretja.Nocitev(osebe[18], cilji[10], 2010),
            new Tretja.Nocitev(osebe[11], cilji[2], 2008),
            new Tretja.Nocitev(osebe[22], cilji[5], 2020),
            new Tretja.Nocitev(osebe[13], cilji[22], 2013),
            new Tretja.Nocitev(osebe[17], cilji[14], 2015),
            new Tretja.Nocitev(osebe[21], cilji[22], 2001),
            new Tretja.Nocitev(osebe[22], cilji[5], 2018),
            new Tretja.Nocitev(osebe[20], cilji[25], 2014),
            new Tretja.Nocitev(osebe[17], cilji[14], 2010),
            new Tretja.Nocitev(osebe[15], cilji[12], 2004),
            new Tretja.Nocitev(osebe[3], cilji[1], 2015),
            new Tretja.Nocitev(osebe[12], cilji[26], 2008),
            new Tretja.Nocitev(osebe[2], cilji[26], 2005),
            new Tretja.Nocitev(osebe[19], cilji[26], 2019),
            new Tretja.Nocitev(osebe[19], cilji[22], 2020),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2000, 2017);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
