
public class Test24 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Mwfa Ndqi", "Bpzb"),
            new Tretja.Oseba("Fgvl Uzof", "Wwm"),
            new Tretja.Oseba("Yqx Jsmt", "Bpzb"),
            new Tretja.Oseba("Oxdw Gkgt", "Wwm"),
            new Tretja.Oseba("Pfby Vynr", "Bpzb"),
            new Tretja.Oseba("Jlxn Lqbh", "Bpzb"),
            new Tretja.Oseba("Nwvr Xbiv", "Bpzb"),
            new Tretja.Oseba("Ydvh Dbmj", "Bpzb"),
            new Tretja.Oseba("Fkfd Gwmv", "Wwm"),
            new Tretja.Oseba("Xqfd Sgzn", "Bpzb"),
            new Tretja.Oseba("Ykon Wtzf", "Hidq"),
            new Tretja.Oseba("Wwuj Slax", "Wwm"),
            new Tretja.Oseba("Pfnw Ordv", "Bpzb"),
            new Tretja.Oseba("Nayy Gfic", "Otxr"),
            new Tretja.Oseba("Yty Ivnx", "Otxr"),
            new Tretja.Oseba("Aloj Hfyh", "Hidq"),
            new Tretja.Oseba("Yxqq Fdza", "Bpzb"),
            new Tretja.Oseba("Oyh Ebtu", "Hidq"),
            new Tretja.Oseba("Clkv Deuo", "Wwm"),
            new Tretja.Oseba("Vscf Nrpl", "Bpzb"),
            new Tretja.Oseba("Nzbj Lsvh", "Wwm"),
            new Tretja.Oseba("Focg Wxns", "Otxr"),
            new Tretja.Oseba("Lnld Lydb", "Hidq"),
            new Tretja.Oseba("Gxaq Slqc", "Wwm"),
            new Tretja.Oseba("Ymqq Mmdi", "Wwm"),
            new Tretja.Oseba("Fvni Zbbv", "Wwm"),
            new Tretja.Oseba("Roia Pyyg", "Bpzb"),
            new Tretja.Oseba("Wzge Fgvg", "Bpzb"),
            new Tretja.Oseba("Uqvx Gcei", "Otxr"),
            new Tretja.Oseba("Qduv Gdrs", "Otxr"),
            new Tretja.Oseba("Wpoq Gjjm", "Bpzb"),
            new Tretja.Oseba("Nucl Ariu", "Bpzb"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Xuhi", "Hidq"),
            new Tretja.Cilj("Wiat", "Hidq"),
            new Tretja.Cilj("Tcqp", "Otxr"),
            new Tretja.Cilj("Nuyp", "Wwm"),
            new Tretja.Cilj("Idux", "Bpzb"),
            new Tretja.Cilj("Adyi", "Otxr"),
            new Tretja.Cilj("Yigd", "Otxr"),
            new Tretja.Cilj("Qquq", "Wwm"),
            new Tretja.Cilj("Qhsz", "Hidq"),
            new Tretja.Cilj("Qwj", "Hidq"),
            new Tretja.Cilj("Ygxn", "Wwm"),
            new Tretja.Cilj("Hoin", "Hidq"),
            new Tretja.Cilj("Lywn", "Hidq"),
            new Tretja.Cilj("Bue", "Otxr"),
            new Tretja.Cilj("Mjtm", "Otxr"),
            new Tretja.Cilj("Zjxe", "Bpzb"),
            new Tretja.Cilj("Zkdy", "Hidq"),
            new Tretja.Cilj("Bodm", "Hidq"),
            new Tretja.Cilj("Jtjs", "Otxr"),
            new Tretja.Cilj("Bycf", "Hidq"),
            new Tretja.Cilj("Itsd", "Bpzb"),
            new Tretja.Cilj("Pxps", "Hidq"),
            new Tretja.Cilj("Qdbm", "Hidq"),
            new Tretja.Cilj("Uxwx", "Wwm"),
            new Tretja.Cilj("Pjaz", "Bpzb"),
            new Tretja.Cilj("Sacy", "Wwm"),
            new Tretja.Cilj("Lzts", "Wwm"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[9], cilji[5], 2008),
            new Tretja.Nocitev(osebe[22], cilji[20], 2001),
            new Tretja.Nocitev(osebe[4], cilji[5], 2011),
            new Tretja.Nocitev(osebe[29], cilji[14], 2006),
            new Tretja.Nocitev(osebe[29], cilji[14], 2015),
            new Tretja.Nocitev(osebe[19], cilji[7], 2008),
            new Tretja.Nocitev(osebe[12], cilji[8], 2015),
            new Tretja.Nocitev(osebe[14], cilji[16], 2008),
            new Tretja.Nocitev(osebe[11], cilji[19], 2008),
            new Tretja.Nocitev(osebe[13], cilji[0], 2017),
            new Tretja.Nocitev(osebe[17], cilji[3], 2009),
            new Tretja.Nocitev(osebe[11], cilji[1], 2019),
            new Tretja.Nocitev(osebe[10], cilji[15], 2001),
            new Tretja.Nocitev(osebe[8], cilji[13], 2012),
            new Tretja.Nocitev(osebe[10], cilji[20], 2008),
            new Tretja.Nocitev(osebe[5], cilji[20], 2011),
            new Tretja.Nocitev(osebe[3], cilji[7], 2010),
            new Tretja.Nocitev(osebe[18], cilji[20], 2014),
            new Tretja.Nocitev(osebe[3], cilji[1], 2017),
            new Tretja.Nocitev(osebe[28], cilji[6], 2007),
            new Tretja.Nocitev(osebe[1], cilji[22], 2007),
            new Tretja.Nocitev(osebe[13], cilji[10], 2017),
            new Tretja.Nocitev(osebe[23], cilji[7], 2010),
            new Tretja.Nocitev(osebe[3], cilji[0], 2006),
            new Tretja.Nocitev(osebe[0], cilji[22], 2015),
            new Tretja.Nocitev(osebe[4], cilji[5], 2005),
            new Tretja.Nocitev(osebe[23], cilji[23], 2001),
            new Tretja.Nocitev(osebe[16], cilji[25], 2003),
            new Tretja.Nocitev(osebe[1], cilji[8], 2013),
            new Tretja.Nocitev(osebe[0], cilji[22], 2000),
            new Tretja.Nocitev(osebe[14], cilji[19], 2002),
            new Tretja.Nocitev(osebe[11], cilji[24], 2004),
            new Tretja.Nocitev(osebe[23], cilji[10], 2013),
            new Tretja.Nocitev(osebe[19], cilji[24], 2004),
            new Tretja.Nocitev(osebe[14], cilji[4], 2010),
            new Tretja.Nocitev(osebe[8], cilji[13], 2001),
            new Tretja.Nocitev(osebe[30], cilji[9], 2011),
            new Tretja.Nocitev(osebe[27], cilji[12], 2010),
            new Tretja.Nocitev(osebe[5], cilji[20], 2012),
            new Tretja.Nocitev(osebe[6], cilji[7], 2019),
            new Tretja.Nocitev(osebe[16], cilji[20], 2015),
            new Tretja.Nocitev(osebe[13], cilji[0], 2000),
            new Tretja.Nocitev(osebe[24], cilji[0], 2005),
            new Tretja.Nocitev(osebe[25], cilji[11], 2008),
            new Tretja.Nocitev(osebe[19], cilji[5], 2004),
            new Tretja.Nocitev(osebe[25], cilji[11], 2012),
            new Tretja.Nocitev(osebe[4], cilji[5], 2016),
            new Tretja.Nocitev(osebe[29], cilji[14], 2001),
            new Tretja.Nocitev(osebe[21], cilji[13], 2005),
            new Tretja.Nocitev(osebe[31], cilji[9], 2005),
            new Tretja.Nocitev(osebe[2], cilji[24], 2004),
            new Tretja.Nocitev(osebe[19], cilji[11], 2012),
            new Tretja.Nocitev(osebe[11], cilji[9], 2012),
            new Tretja.Nocitev(osebe[21], cilji[18], 2004),
            new Tretja.Nocitev(osebe[21], cilji[15], 2015),
            new Tretja.Nocitev(osebe[20], cilji[5], 2017),
            new Tretja.Nocitev(osebe[28], cilji[14], 2000),
            new Tretja.Nocitev(osebe[31], cilji[5], 2006),
            new Tretja.Nocitev(osebe[14], cilji[21], 2003),
            new Tretja.Nocitev(osebe[3], cilji[14], 2012),
            new Tretja.Nocitev(osebe[2], cilji[10], 2005),
            new Tretja.Nocitev(osebe[18], cilji[24], 2018),
            new Tretja.Nocitev(osebe[29], cilji[14], 2005),
            new Tretja.Nocitev(osebe[30], cilji[9], 2002),
            new Tretja.Nocitev(osebe[8], cilji[13], 2010),
            new Tretja.Nocitev(osebe[21], cilji[26], 2006),
            new Tretja.Nocitev(osebe[18], cilji[20], 2012),
            new Tretja.Nocitev(osebe[22], cilji[20], 2013),
            new Tretja.Nocitev(osebe[31], cilji[3], 2000),
            new Tretja.Nocitev(osebe[2], cilji[1], 2007),
            new Tretja.Nocitev(osebe[16], cilji[18], 2004),
            new Tretja.Nocitev(osebe[21], cilji[17], 2012),
            new Tretja.Nocitev(osebe[2], cilji[15], 2009),
            new Tretja.Nocitev(osebe[11], cilji[12], 2014),
            new Tretja.Nocitev(osebe[17], cilji[6], 2002),
            new Tretja.Nocitev(osebe[30], cilji[9], 2006),
            new Tretja.Nocitev(osebe[8], cilji[13], 2000),
            new Tretja.Nocitev(osebe[6], cilji[7], 2003),
            new Tretja.Nocitev(osebe[30], cilji[9], 2006),
            new Tretja.Nocitev(osebe[6], cilji[7], 2012),
            new Tretja.Nocitev(osebe[22], cilji[20], 2003),
            new Tretja.Nocitev(osebe[15], cilji[3], 2016),
            new Tretja.Nocitev(osebe[17], cilji[6], 2014),
            new Tretja.Nocitev(osebe[30], cilji[9], 2002),
            new Tretja.Nocitev(osebe[15], cilji[10], 2012),
            new Tretja.Nocitev(osebe[9], cilji[5], 2006),
            new Tretja.Nocitev(osebe[29], cilji[14], 2002),
            new Tretja.Nocitev(osebe[3], cilji[8], 2019),
            new Tretja.Nocitev(osebe[27], cilji[12], 2020),
            new Tretja.Nocitev(osebe[12], cilji[8], 2015),
            new Tretja.Nocitev(osebe[11], cilji[12], 2002),
            new Tretja.Nocitev(osebe[17], cilji[5], 2015),
            new Tretja.Nocitev(osebe[24], cilji[0], 2009),
            new Tretja.Nocitev(osebe[8], cilji[13], 2011),
            new Tretja.Nocitev(osebe[0], cilji[22], 2013),
            new Tretja.Nocitev(osebe[4], cilji[5], 2006),
            new Tretja.Nocitev(osebe[17], cilji[5], 2009),
            new Tretja.Nocitev(osebe[15], cilji[24], 2012),
            new Tretja.Nocitev(osebe[5], cilji[20], 2012),
            new Tretja.Nocitev(osebe[18], cilji[4], 2006),
            new Tretja.Nocitev(osebe[17], cilji[21], 2016),
            new Tretja.Nocitev(osebe[20], cilji[5], 2019),
            new Tretja.Nocitev(osebe[10], cilji[10], 2004),
            new Tretja.Nocitev(osebe[22], cilji[20], 2017),
            new Tretja.Nocitev(osebe[13], cilji[6], 2009),
            new Tretja.Nocitev(osebe[6], cilji[7], 2017),
            new Tretja.Nocitev(osebe[19], cilji[18], 2008),
            new Tretja.Nocitev(osebe[15], cilji[12], 2003),
            new Tretja.Nocitev(osebe[2], cilji[1], 2010),
            new Tretja.Nocitev(osebe[21], cilji[12], 2007),
            new Tretja.Nocitev(osebe[2], cilji[23], 2006),
            new Tretja.Nocitev(osebe[27], cilji[12], 2013),
            new Tretja.Nocitev(osebe[20], cilji[5], 2000),
            new Tretja.Nocitev(osebe[12], cilji[8], 2009),
            new Tretja.Nocitev(osebe[0], cilji[22], 2003),
            new Tretja.Nocitev(osebe[9], cilji[5], 2020),
            new Tretja.Nocitev(osebe[7], cilji[15], 2009),
            new Tretja.Nocitev(osebe[1], cilji[7], 2020),
            new Tretja.Nocitev(osebe[14], cilji[9], 2011),
            new Tretja.Nocitev(osebe[24], cilji[0], 2003),
            new Tretja.Nocitev(osebe[26], cilji[11], 2009),
            new Tretja.Nocitev(osebe[11], cilji[20], 2019),
            new Tretja.Nocitev(osebe[30], cilji[9], 2006),
            new Tretja.Nocitev(osebe[22], cilji[20], 2018),
            new Tretja.Nocitev(osebe[13], cilji[18], 2006),
            new Tretja.Nocitev(osebe[27], cilji[12], 2005),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
