
public class Test06 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Vxbm Maoo", "Zczw"),
            new Tretja.Oseba("Acgq Upjn", "Ejcx"),
            new Tretja.Oseba("Uowb Aiqq", "Zczw"),
            new Tretja.Oseba("Tcay Kxqb", "Zczw"),
            new Tretja.Oseba("Gtzq Kuso", "Ejcx"),
            new Tretja.Oseba("Evkz Zibh", "Zczw"),
            new Tretja.Oseba("Yvll Ntc", "Ejcx"),
            new Tretja.Oseba("Ychm Qtwr", "Zczw"),
            new Tretja.Oseba("Oonm Knrv", "Zczw"),
            new Tretja.Oseba("Lidx Dvnu", "Zczw"),
            new Tretja.Oseba("Igrn Wken", "Ejcx"),
            new Tretja.Oseba("Zaxu Yafw", "Ejcx"),
            new Tretja.Oseba("Dvtu Bedu", "Zczw"),
            new Tretja.Oseba("Tjum Qjgr", "Zczw"),
            new Tretja.Oseba("Abxo Burt", "Ejcx"),
            new Tretja.Oseba("Wrgb Gpwj", "Ejcx"),
            new Tretja.Oseba("Qaek Cpp", "Ejcx"),
            new Tretja.Oseba("Rhjv Loka", "Zczw"),
            new Tretja.Oseba("Exia Jvq", "Zczw"),
            new Tretja.Oseba("Hurc Snsx", "Ejcx"),
            new Tretja.Oseba("Yvwr Qcmq", "Zczw"),
            new Tretja.Oseba("Duee Tcqk", "Ejcx"),
            new Tretja.Oseba("Fuhz Bimq", "Ejcx"),
            new Tretja.Oseba("Urdo Phvl", "Zczw"),
            new Tretja.Oseba("Bium Ktcd", "Zczw"),
            new Tretja.Oseba("Joop Rxrm", "Zczw"),
            new Tretja.Oseba("Fvze Phwe", "Zczw"),
            new Tretja.Oseba("Hljr Qvlf", "Ejcx"),
            new Tretja.Oseba("Ypdr Vfsb", "Zczw"),
            new Tretja.Oseba("Gfgf Sidg", "Zczw"),
            new Tretja.Oseba("Dkuj Wero", "Zczw"),
            new Tretja.Oseba("Znao Jmrv", "Zczw"),
            new Tretja.Oseba("Ehdt Qaza", "Ejcx"),
            new Tretja.Oseba("Mife Pwyd", "Zczw"),
            new Tretja.Oseba("Yjmw Ffrb", "Zczw"),
            new Tretja.Oseba("Igkl Cija", "Zczw"),
            new Tretja.Oseba("Fdeo Frpx", "Zczw"),
            new Tretja.Oseba("Dyom Fegl", "Ejcx"),
            new Tretja.Oseba("Qdal Orih", "Zczw"),
            new Tretja.Oseba("Rnif Xdnf", "Zczw"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Ivly", "Ejcx"),
            new Tretja.Cilj("Jecw", "Ejcx"),
            new Tretja.Cilj("Isge", "Ejcx"),
            new Tretja.Cilj("Sird", "Ejcx"),
            new Tretja.Cilj("Nldb", "Ejcx"),
            new Tretja.Cilj("Cqrh", "Zczw"),
            new Tretja.Cilj("Eym", "Ejcx"),
            new Tretja.Cilj("Vivd", "Ejcx"),
            new Tretja.Cilj("Xrkd", "Ejcx"),
            new Tretja.Cilj("Wtyq", "Zczw"),
            new Tretja.Cilj("Nqez", "Zczw"),
            new Tretja.Cilj("Vugk", "Zczw"),
            new Tretja.Cilj("Khdc", "Ejcx"),
            new Tretja.Cilj("Hmon", "Ejcx"),
            new Tretja.Cilj("Zqcy", "Zczw"),
            new Tretja.Cilj("Berj", "Zczw"),
            new Tretja.Cilj("Doql", "Ejcx"),
            new Tretja.Cilj("Hzcn", "Ejcx"),
            new Tretja.Cilj("Sswl", "Zczw"),
            new Tretja.Cilj("Cpup", "Ejcx"),
            new Tretja.Cilj("Ojtp", "Ejcx"),
            new Tretja.Cilj("Yujt", "Ejcx"),
            new Tretja.Cilj("Xtqg", "Ejcx"),
            new Tretja.Cilj("Outm", "Ejcx"),
            new Tretja.Cilj("Ypwo", "Ejcx"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[10], cilji[2], 2009),
            new Tretja.Nocitev(osebe[28], cilji[13], 2014),
            new Tretja.Nocitev(osebe[3], cilji[9], 2014),
            new Tretja.Nocitev(osebe[12], cilji[10], 2000),
            new Tretja.Nocitev(osebe[38], cilji[7], 2011),
            new Tretja.Nocitev(osebe[20], cilji[24], 2011),
            new Tretja.Nocitev(osebe[4], cilji[23], 2012),
            new Tretja.Nocitev(osebe[1], cilji[3], 2017),
            new Tretja.Nocitev(osebe[34], cilji[13], 2015),
            new Tretja.Nocitev(osebe[39], cilji[13], 2011),
            new Tretja.Nocitev(osebe[4], cilji[23], 2016),
            new Tretja.Nocitev(osebe[3], cilji[6], 2011),
            new Tretja.Nocitev(osebe[10], cilji[23], 2014),
            new Tretja.Nocitev(osebe[6], cilji[7], 2015),
            new Tretja.Nocitev(osebe[23], cilji[1], 2011),
            new Tretja.Nocitev(osebe[4], cilji[23], 2001),
            new Tretja.Nocitev(osebe[30], cilji[17], 2010),
            new Tretja.Nocitev(osebe[24], cilji[4], 2017),
            new Tretja.Nocitev(osebe[33], cilji[18], 2001),
            new Tretja.Nocitev(osebe[34], cilji[13], 2018),
            new Tretja.Nocitev(osebe[0], cilji[18], 2000),
            new Tretja.Nocitev(osebe[26], cilji[1], 2017),
            new Tretja.Nocitev(osebe[26], cilji[12], 2013),
            new Tretja.Nocitev(osebe[0], cilji[18], 2018),
            new Tretja.Nocitev(osebe[34], cilji[13], 2007),
            new Tretja.Nocitev(osebe[28], cilji[12], 2018),
            new Tretja.Nocitev(osebe[0], cilji[18], 2014),
            new Tretja.Nocitev(osebe[11], cilji[10], 2010),
            new Tretja.Nocitev(osebe[0], cilji[18], 2014),
            new Tretja.Nocitev(osebe[21], cilji[16], 2019),
            new Tretja.Nocitev(osebe[28], cilji[4], 2002),
            new Tretja.Nocitev(osebe[0], cilji[18], 2000),
            new Tretja.Nocitev(osebe[15], cilji[16], 2000),
            new Tretja.Nocitev(osebe[37], cilji[6], 2020),
            new Tretja.Nocitev(osebe[16], cilji[1], 2016),
            new Tretja.Nocitev(osebe[31], cilji[1], 2000),
            new Tretja.Nocitev(osebe[24], cilji[13], 2007),
            new Tretja.Nocitev(osebe[14], cilji[23], 2006),
            new Tretja.Nocitev(osebe[30], cilji[17], 2005),
            new Tretja.Nocitev(osebe[30], cilji[17], 2005),
            new Tretja.Nocitev(osebe[35], cilji[4], 2015),
            new Tretja.Nocitev(osebe[19], cilji[16], 2010),
            new Tretja.Nocitev(osebe[36], cilji[11], 2013),
            new Tretja.Nocitev(osebe[6], cilji[7], 2005),
            new Tretja.Nocitev(osebe[25], cilji[13], 2010),
            new Tretja.Nocitev(osebe[11], cilji[10], 2001),
            new Tretja.Nocitev(osebe[26], cilji[17], 2016),
            new Tretja.Nocitev(osebe[29], cilji[18], 2006),
            new Tretja.Nocitev(osebe[11], cilji[10], 2017),
            new Tretja.Nocitev(osebe[12], cilji[10], 2013),
            new Tretja.Nocitev(osebe[16], cilji[5], 2010),
            new Tretja.Nocitev(osebe[10], cilji[12], 2002),
            new Tretja.Nocitev(osebe[31], cilji[10], 2020),
            new Tretja.Nocitev(osebe[15], cilji[16], 2007),
            new Tretja.Nocitev(osebe[17], cilji[10], 2009),
            new Tretja.Nocitev(osebe[19], cilji[9], 2012),
            new Tretja.Nocitev(osebe[4], cilji[23], 2020),
            new Tretja.Nocitev(osebe[17], cilji[10], 2008),
            new Tretja.Nocitev(osebe[0], cilji[18], 2017),
            new Tretja.Nocitev(osebe[12], cilji[10], 2012),
            new Tretja.Nocitev(osebe[37], cilji[20], 2012),
            new Tretja.Nocitev(osebe[16], cilji[21], 2001),
            new Tretja.Nocitev(osebe[16], cilji[22], 2000),
            new Tretja.Nocitev(osebe[23], cilji[14], 2019),
            new Tretja.Nocitev(osebe[37], cilji[7], 2013),
            new Tretja.Nocitev(osebe[26], cilji[10], 2001),
            new Tretja.Nocitev(osebe[28], cilji[15], 2020),
            new Tretja.Nocitev(osebe[21], cilji[11], 2008),
            new Tretja.Nocitev(osebe[5], cilji[6], 2016),
            new Tretja.Nocitev(osebe[15], cilji[16], 2011),
            new Tretja.Nocitev(osebe[22], cilji[14], 2003),
            new Tretja.Nocitev(osebe[29], cilji[18], 2013),
            new Tretja.Nocitev(osebe[23], cilji[0], 2008),
            new Tretja.Nocitev(osebe[14], cilji[23], 2004),
            new Tretja.Nocitev(osebe[39], cilji[24], 2007),
            new Tretja.Nocitev(osebe[0], cilji[18], 2002),
            new Tretja.Nocitev(osebe[33], cilji[18], 2015),
            new Tretja.Nocitev(osebe[36], cilji[9], 2008),
            new Tretja.Nocitev(osebe[29], cilji[18], 2017),
            new Tretja.Nocitev(osebe[15], cilji[16], 2016),
            new Tretja.Nocitev(osebe[0], cilji[18], 2007),
            new Tretja.Nocitev(osebe[33], cilji[18], 2001),
            new Tretja.Nocitev(osebe[23], cilji[14], 2002),
            new Tretja.Nocitev(osebe[25], cilji[18], 2001),
            new Tretja.Nocitev(osebe[19], cilji[9], 2014),
            new Tretja.Nocitev(osebe[5], cilji[6], 2010),
            new Tretja.Nocitev(osebe[39], cilji[19], 2009),
            new Tretja.Nocitev(osebe[0], cilji[18], 2007),
            new Tretja.Nocitev(osebe[14], cilji[23], 2005),
            new Tretja.Nocitev(osebe[7], cilji[5], 2012),
            new Tretja.Nocitev(osebe[23], cilji[9], 2014),
            new Tretja.Nocitev(osebe[0], cilji[18], 2013),
            new Tretja.Nocitev(osebe[29], cilji[18], 2000),
            new Tretja.Nocitev(osebe[8], cilji[17], 2009),
            new Tretja.Nocitev(osebe[15], cilji[16], 2013),
            new Tretja.Nocitev(osebe[25], cilji[2], 2005),
            new Tretja.Nocitev(osebe[18], cilji[1], 2000),
            new Tretja.Nocitev(osebe[1], cilji[3], 2012),
            new Tretja.Nocitev(osebe[16], cilji[15], 2013),
            new Tretja.Nocitev(osebe[11], cilji[10], 2000),
            new Tretja.Nocitev(osebe[38], cilji[19], 2012),
            new Tretja.Nocitev(osebe[17], cilji[10], 2010),
            new Tretja.Nocitev(osebe[10], cilji[23], 2014),
            new Tretja.Nocitev(osebe[1], cilji[3], 2002),
            new Tretja.Nocitev(osebe[32], cilji[1], 2015),
            new Tretja.Nocitev(osebe[36], cilji[1], 2012),
            new Tretja.Nocitev(osebe[24], cilji[15], 2011),
            new Tretja.Nocitev(osebe[4], cilji[23], 2014),
            new Tretja.Nocitev(osebe[6], cilji[7], 2006),
            new Tretja.Nocitev(osebe[38], cilji[8], 2003),
            new Tretja.Nocitev(osebe[25], cilji[18], 2000),
            new Tretja.Nocitev(osebe[36], cilji[14], 2017),
            new Tretja.Nocitev(osebe[32], cilji[1], 2011),
            new Tretja.Nocitev(osebe[10], cilji[24], 2009),
            new Tretja.Nocitev(osebe[33], cilji[18], 2000),
            new Tretja.Nocitev(osebe[22], cilji[20], 2009),
            new Tretja.Nocitev(osebe[12], cilji[10], 2016),
            new Tretja.Nocitev(osebe[34], cilji[13], 2018),
            new Tretja.Nocitev(osebe[4], cilji[23], 2008),
            new Tretja.Nocitev(osebe[9], cilji[3], 2005),
            new Tretja.Nocitev(osebe[12], cilji[10], 2018),
            new Tretja.Nocitev(osebe[23], cilji[10], 2003),
            new Tretja.Nocitev(osebe[21], cilji[20], 2017),
            new Tretja.Nocitev(osebe[33], cilji[18], 2010),
            new Tretja.Nocitev(osebe[1], cilji[3], 2008),
            new Tretja.Nocitev(osebe[38], cilji[17], 2009),
            new Tretja.Nocitev(osebe[0], cilji[18], 2013),
            new Tretja.Nocitev(osebe[37], cilji[11], 2016),
            new Tretja.Nocitev(osebe[0], cilji[18], 2014),
            new Tretja.Nocitev(osebe[6], cilji[7], 2007),
            new Tretja.Nocitev(osebe[31], cilji[22], 2019),
            new Tretja.Nocitev(osebe[23], cilji[20], 2000),
            new Tretja.Nocitev(osebe[39], cilji[22], 2014),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
