
public class Test08 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Abvf Qzjj", "Vdze"),
            new Tretja.Oseba("Rgex Czjj", "Slzg"),
            new Tretja.Oseba("Rgtz Wadi", "Slzg"),
            new Tretja.Oseba("Vnmn Sfkd", "Vdze"),
            new Tretja.Oseba("Bxw Ktwv", "Msou"),
            new Tretja.Oseba("Bgds Qyte", "Ylb"),
            new Tretja.Oseba("Iprj Golq", "Vdze"),
            new Tretja.Oseba("Bflm Jgxa", "Slzg"),
            new Tretja.Oseba("Drvi Lcsb", "Ylb"),
            new Tretja.Oseba("Vxsh Wxfb", "Msou"),
            new Tretja.Oseba("Nfkp Kaot", "Slzg"),
            new Tretja.Oseba("Ngzg Dymc", "Ylb"),
            new Tretja.Oseba("Jhca Qimr", "Vdze"),
            new Tretja.Oseba("Ebsq Wzxr", "Vdze"),
            new Tretja.Oseba("Jueo Pnse", "Slzg"),
            new Tretja.Oseba("Ermg Ppyj", "Ylb"),
            new Tretja.Oseba("Zinf Bwmp", "Slzg"),
            new Tretja.Oseba("Aqhg Ifv", "Vdze"),
            new Tretja.Oseba("Dupf Iymd", "Msou"),
            new Tretja.Oseba("Eak Bspi", "Ylb"),
            new Tretja.Oseba("Ozhj Jpvj", "Vdze"),
            new Tretja.Oseba("Glth Nrux", "Vdze"),
            new Tretja.Oseba("Euyq Tnph", "Msou"),
            new Tretja.Oseba("Ptgu Axmp", "Slzg"),
            new Tretja.Oseba("Jelv Htzb", "Ylb"),
            new Tretja.Oseba("Kwzk Rffe", "Vdze"),
            new Tretja.Oseba("Qtgm Zztf", "Ylb"),
            new Tretja.Oseba("Zvao Ruty", "Msou"),
            new Tretja.Oseba("Wqzn Fjxp", "Vdze"),
            new Tretja.Oseba("Cwps Zgns", "Msou"),
            new Tretja.Oseba("Tulr Tmkg", "Msou"),
            new Tretja.Oseba("Hxti Vuib", "Msou"),
            new Tretja.Oseba("Yofo Gjxf", "Slzg"),
            new Tretja.Oseba("Wnah Fgjj", "Ylb"),
            new Tretja.Oseba("Nfp Shfi", "Msou"),
            new Tretja.Oseba("Suve Cizz", "Ylb"),
            new Tretja.Oseba("Bdcj Ptty", "Slzg"),
            new Tretja.Oseba("Brxa Bsib", "Msou"),
            new Tretja.Oseba("Bmmk Vzld", "Ylb"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Ydus", "Vdze"),
            new Tretja.Cilj("Nsya", "Slzg"),
            new Tretja.Cilj("Vkiq", "Vdze"),
            new Tretja.Cilj("Lcxm", "Ylb"),
            new Tretja.Cilj("Njet", "Vdze"),
            new Tretja.Cilj("Fbqi", "Msou"),
            new Tretja.Cilj("Rqiw", "Ylb"),
            new Tretja.Cilj("Bawq", "Msou"),
            new Tretja.Cilj("Jkgt", "Vdze"),
            new Tretja.Cilj("Ffmg", "Ylb"),
            new Tretja.Cilj("Ztoa", "Msou"),
            new Tretja.Cilj("Mthd", "Msou"),
            new Tretja.Cilj("Dpdf", "Ylb"),
            new Tretja.Cilj("Zmwi", "Slzg"),
            new Tretja.Cilj("Wpit", "Slzg"),
            new Tretja.Cilj("Amlb", "Msou"),
            new Tretja.Cilj("Gjjh", "Slzg"),
            new Tretja.Cilj("Klbc", "Ylb"),
            new Tretja.Cilj("Ukaz", "Msou"),
            new Tretja.Cilj("Sbs", "Slzg"),
            new Tretja.Cilj("Fqlv", "Msou"),
            new Tretja.Cilj("Obtz", "Msou"),
            new Tretja.Cilj("Rgcu", "Vdze"),
            new Tretja.Cilj("Yaqw", "Msou"),
            new Tretja.Cilj("Fmrx", "Slzg"),
            new Tretja.Cilj("Hyhq", "Slzg"),
            new Tretja.Cilj("Mslg", "Msou"),
            new Tretja.Cilj("Smwb", "Msou"),
            new Tretja.Cilj("Tbfc", "Msou"),
            new Tretja.Cilj("Oltj", "Ylb"),
            new Tretja.Cilj("Udzc", "Slzg"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[38], cilji[5], 2006),
            new Tretja.Nocitev(osebe[26], cilji[22], 2009),
            new Tretja.Nocitev(osebe[38], cilji[5], 2011),
            new Tretja.Nocitev(osebe[36], cilji[27], 2005),
            new Tretja.Nocitev(osebe[8], cilji[18], 2007),
            new Tretja.Nocitev(osebe[38], cilji[5], 2003),
            new Tretja.Nocitev(osebe[19], cilji[11], 2004),
            new Tretja.Nocitev(osebe[19], cilji[11], 2012),
            new Tretja.Nocitev(osebe[31], cilji[3], 2015),
            new Tretja.Nocitev(osebe[31], cilji[1], 2003),
            new Tretja.Nocitev(osebe[30], cilji[1], 2006),
            new Tretja.Nocitev(osebe[24], cilji[25], 2005),
            new Tretja.Nocitev(osebe[36], cilji[0], 2006),
            new Tretja.Nocitev(osebe[12], cilji[13], 2006),
            new Tretja.Nocitev(osebe[32], cilji[2], 2009),
            new Tretja.Nocitev(osebe[31], cilji[1], 2003),
            new Tretja.Nocitev(osebe[19], cilji[11], 2001),
            new Tretja.Nocitev(osebe[33], cilji[2], 2012),
            new Tretja.Nocitev(osebe[0], cilji[11], 2008),
            new Tretja.Nocitev(osebe[32], cilji[9], 2002),
            new Tretja.Nocitev(osebe[16], cilji[21], 2010),
            new Tretja.Nocitev(osebe[10], cilji[27], 2015),
            new Tretja.Nocitev(osebe[14], cilji[19], 2008),
            new Tretja.Nocitev(osebe[20], cilji[13], 2003),
            new Tretja.Nocitev(osebe[4], cilji[21], 2012),
            new Tretja.Nocitev(osebe[11], cilji[10], 2004),
            new Tretja.Nocitev(osebe[15], cilji[18], 2013),
            new Tretja.Nocitev(osebe[33], cilji[2], 2005),
            new Tretja.Nocitev(osebe[18], cilji[4], 2002),
            new Tretja.Nocitev(osebe[22], cilji[21], 2015),
            new Tretja.Nocitev(osebe[21], cilji[3], 2008),
            new Tretja.Nocitev(osebe[27], cilji[12], 2005),
            new Tretja.Nocitev(osebe[34], cilji[25], 2004),
            new Tretja.Nocitev(osebe[20], cilji[21], 2001),
            new Tretja.Nocitev(osebe[3], cilji[25], 2014),
            new Tretja.Nocitev(osebe[8], cilji[18], 2008),
            new Tretja.Nocitev(osebe[13], cilji[4], 2005),
            new Tretja.Nocitev(osebe[26], cilji[22], 2016),
            new Tretja.Nocitev(osebe[30], cilji[1], 2017),
            new Tretja.Nocitev(osebe[0], cilji[1], 2020),
            new Tretja.Nocitev(osebe[4], cilji[21], 2005),
            new Tretja.Nocitev(osebe[33], cilji[2], 2019),
            new Tretja.Nocitev(osebe[23], cilji[12], 2018),
            new Tretja.Nocitev(osebe[29], cilji[29], 2000),
            new Tretja.Nocitev(osebe[34], cilji[25], 2008),
            new Tretja.Nocitev(osebe[27], cilji[12], 2011),
            new Tretja.Nocitev(osebe[38], cilji[5], 2012),
            new Tretja.Nocitev(osebe[5], cilji[17], 2013),
            new Tretja.Nocitev(osebe[31], cilji[13], 2013),
            new Tretja.Nocitev(osebe[22], cilji[21], 2016),
            new Tretja.Nocitev(osebe[4], cilji[21], 2015),
            new Tretja.Nocitev(osebe[5], cilji[17], 2001),
            new Tretja.Nocitev(osebe[13], cilji[4], 2004),
            new Tretja.Nocitev(osebe[21], cilji[0], 2011),
            new Tretja.Nocitev(osebe[3], cilji[8], 2012),
            new Tretja.Nocitev(osebe[30], cilji[1], 2006),
            new Tretja.Nocitev(osebe[21], cilji[15], 2007),
            new Tretja.Nocitev(osebe[12], cilji[13], 2003),
            new Tretja.Nocitev(osebe[9], cilji[22], 2020),
            new Tretja.Nocitev(osebe[29], cilji[6], 2009),
            new Tretja.Nocitev(osebe[14], cilji[19], 2000),
            new Tretja.Nocitev(osebe[28], cilji[8], 2014),
            new Tretja.Nocitev(osebe[2], cilji[20], 2010),
            new Tretja.Nocitev(osebe[32], cilji[1], 2006),
            new Tretja.Nocitev(osebe[34], cilji[25], 2005),
            new Tretja.Nocitev(osebe[21], cilji[23], 2007),
            new Tretja.Nocitev(osebe[17], cilji[1], 2006),
            new Tretja.Nocitev(osebe[30], cilji[1], 2000),
            new Tretja.Nocitev(osebe[33], cilji[2], 2010),
            new Tretja.Nocitev(osebe[0], cilji[20], 2006),
            new Tretja.Nocitev(osebe[23], cilji[2], 2012),
            new Tretja.Nocitev(osebe[34], cilji[25], 2018),
            new Tretja.Nocitev(osebe[1], cilji[19], 2016),
            new Tretja.Nocitev(osebe[33], cilji[2], 2012),
            new Tretja.Nocitev(osebe[25], cilji[10], 2000),
            new Tretja.Nocitev(osebe[31], cilji[11], 2008),
            new Tretja.Nocitev(osebe[10], cilji[24], 2006),
            new Tretja.Nocitev(osebe[6], cilji[18], 2017),
            new Tretja.Nocitev(osebe[13], cilji[4], 2020),
            new Tretja.Nocitev(osebe[17], cilji[1], 2009),
            new Tretja.Nocitev(osebe[9], cilji[5], 2017),
            new Tretja.Nocitev(osebe[8], cilji[18], 2002),
            new Tretja.Nocitev(osebe[11], cilji[3], 2004),
            new Tretja.Nocitev(osebe[28], cilji[8], 2001),
            new Tretja.Nocitev(osebe[21], cilji[14], 2019),
            new Tretja.Nocitev(osebe[14], cilji[19], 2007),
            new Tretja.Nocitev(osebe[11], cilji[29], 2016),
            new Tretja.Nocitev(osebe[11], cilji[7], 2020),
            new Tretja.Nocitev(osebe[36], cilji[13], 2016),
            new Tretja.Nocitev(osebe[31], cilji[4], 2011),
            new Tretja.Nocitev(osebe[26], cilji[22], 2010),
            new Tretja.Nocitev(osebe[11], cilji[26], 2020),
            new Tretja.Nocitev(osebe[34], cilji[25], 2019),
            new Tretja.Nocitev(osebe[25], cilji[18], 2005),
            new Tretja.Nocitev(osebe[23], cilji[30], 2019),
            new Tretja.Nocitev(osebe[23], cilji[26], 2019),
            new Tretja.Nocitev(osebe[14], cilji[19], 2006),
            new Tretja.Nocitev(osebe[10], cilji[6], 2013),
            new Tretja.Nocitev(osebe[8], cilji[18], 2000),
            new Tretja.Nocitev(osebe[5], cilji[17], 2019),
            new Tretja.Nocitev(osebe[12], cilji[13], 2018),
            new Tretja.Nocitev(osebe[20], cilji[14], 2013),
            new Tretja.Nocitev(osebe[21], cilji[19], 2017),
            new Tretja.Nocitev(osebe[23], cilji[19], 2005),
            new Tretja.Nocitev(osebe[22], cilji[21], 2006),
            new Tretja.Nocitev(osebe[21], cilji[7], 2011),
            new Tretja.Nocitev(osebe[18], cilji[25], 2012),
            new Tretja.Nocitev(osebe[34], cilji[25], 2012),
            new Tretja.Nocitev(osebe[14], cilji[19], 2005),
            new Tretja.Nocitev(osebe[28], cilji[8], 2020),
            new Tretja.Nocitev(osebe[7], cilji[16], 2016),
            new Tretja.Nocitev(osebe[24], cilji[24], 2001),
            new Tretja.Nocitev(osebe[7], cilji[16], 2007),
            new Tretja.Nocitev(osebe[30], cilji[1], 2015),
            new Tretja.Nocitev(osebe[30], cilji[1], 2006),
            new Tretja.Nocitev(osebe[29], cilji[4], 2020),
            new Tretja.Nocitev(osebe[7], cilji[22], 2001),
            new Tretja.Nocitev(osebe[9], cilji[1], 2005),
            new Tretja.Nocitev(osebe[21], cilji[20], 2008),
            new Tretja.Nocitev(osebe[28], cilji[8], 2009),
            new Tretja.Nocitev(osebe[4], cilji[21], 2011),
            new Tretja.Nocitev(osebe[28], cilji[8], 2000),
            new Tretja.Nocitev(osebe[3], cilji[14], 2020),
            new Tretja.Nocitev(osebe[24], cilji[10], 2013),
            new Tretja.Nocitev(osebe[21], cilji[19], 2019),
            new Tretja.Nocitev(osebe[1], cilji[21], 2008),
            new Tretja.Nocitev(osebe[32], cilji[26], 2007),
            new Tretja.Nocitev(osebe[30], cilji[1], 2007),
            new Tretja.Nocitev(osebe[30], cilji[1], 2019),
            new Tretja.Nocitev(osebe[22], cilji[21], 2012),
            new Tretja.Nocitev(osebe[3], cilji[28], 2012),
            new Tretja.Nocitev(osebe[35], cilji[24], 2019),
            new Tretja.Nocitev(osebe[20], cilji[1], 2006),
            new Tretja.Nocitev(osebe[20], cilji[7], 2015),
            new Tretja.Nocitev(osebe[9], cilji[6], 2002),
            new Tretja.Nocitev(osebe[9], cilji[0], 2010),
            new Tretja.Nocitev(osebe[12], cilji[13], 2003),
            new Tretja.Nocitev(osebe[15], cilji[18], 2002),
            new Tretja.Nocitev(osebe[27], cilji[12], 2008),
            new Tretja.Nocitev(osebe[16], cilji[21], 2000),
            new Tretja.Nocitev(osebe[34], cilji[25], 2002),
            new Tretja.Nocitev(osebe[3], cilji[16], 2018),
            new Tretja.Nocitev(osebe[15], cilji[18], 2014),
            new Tretja.Nocitev(osebe[23], cilji[1], 2004),
            new Tretja.Nocitev(osebe[27], cilji[12], 2004),
            new Tretja.Nocitev(osebe[38], cilji[5], 2005),
            new Tretja.Nocitev(osebe[3], cilji[20], 2012),
            new Tretja.Nocitev(osebe[8], cilji[18], 2003),
            new Tretja.Nocitev(osebe[2], cilji[6], 2007),
            new Tretja.Nocitev(osebe[8], cilji[18], 2009),
            new Tretja.Nocitev(osebe[2], cilji[8], 2019),
            new Tretja.Nocitev(osebe[30], cilji[1], 2003),
            new Tretja.Nocitev(osebe[3], cilji[7], 2007),
            new Tretja.Nocitev(osebe[35], cilji[27], 2010),
            new Tretja.Nocitev(osebe[2], cilji[19], 2004),
            new Tretja.Nocitev(osebe[6], cilji[18], 2013),
            new Tretja.Nocitev(osebe[27], cilji[12], 2006),
            new Tretja.Nocitev(osebe[14], cilji[19], 2015),
            new Tretja.Nocitev(osebe[29], cilji[26], 2013),
            new Tretja.Nocitev(osebe[2], cilji[28], 2006),
            new Tretja.Nocitev(osebe[31], cilji[0], 2009),
            new Tretja.Nocitev(osebe[31], cilji[17], 2008),
            new Tretja.Nocitev(osebe[18], cilji[13], 2002),
            new Tretja.Nocitev(osebe[17], cilji[1], 2006),
            new Tretja.Nocitev(osebe[5], cilji[17], 2014),
            new Tretja.Nocitev(osebe[10], cilji[27], 2002),
            new Tretja.Nocitev(osebe[14], cilji[19], 2009),
            new Tretja.Nocitev(osebe[3], cilji[4], 2014),
            new Tretja.Nocitev(osebe[26], cilji[22], 2014),
            new Tretja.Nocitev(osebe[30], cilji[1], 2011),
            new Tretja.Nocitev(osebe[37], cilji[12], 2003),
            new Tretja.Nocitev(osebe[31], cilji[16], 2017),
            new Tretja.Nocitev(osebe[30], cilji[1], 2012),
            new Tretja.Nocitev(osebe[25], cilji[6], 2015),
            new Tretja.Nocitev(osebe[12], cilji[13], 2007),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
