
public class Test17 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Jwtn Hwpb", "Kgkf"),
            new Tretja.Oseba("Zpcx Qauk", "Vvtw"),
            new Tretja.Oseba("Symd Qnjr", "Wdxp"),
            new Tretja.Oseba("Vjbz Cceo", "Ivcy"),
            new Tretja.Oseba("Wmjl Xsey", "Kppz"),
            new Tretja.Oseba("Uhpz Qdra", "Wdxp"),
            new Tretja.Oseba("Hmwz Clny", "Kppz"),
            new Tretja.Oseba("Zzrk Erbn", "Wdxp"),
            new Tretja.Oseba("Npek Fizh", "Ivcy"),
            new Tretja.Oseba("Ixyz Oxsh", "Ivcy"),
            new Tretja.Oseba("Rxou Rjak", "Vvtw"),
            new Tretja.Oseba("Bddq Aoyt", "Kppz"),
            new Tretja.Oseba("Ucvn Vape", "Kgkf"),
            new Tretja.Oseba("Glot Zhuo", "Vvtw"),
            new Tretja.Oseba("Cvoi Ucxv", "Kgkf"),
            new Tretja.Oseba("Moct Cpcb", "Kppz"),
            new Tretja.Oseba("Fzya Ifec", "Vvtw"),
            new Tretja.Oseba("Gogg Abdf", "Kgkf"),
            new Tretja.Oseba("Luwg Aifq", "Ivcy"),
            new Tretja.Oseba("Hhpa Bglf", "Wdxp"),
            new Tretja.Oseba("Gpli Rull", "Vvtw"),
            new Tretja.Oseba("Tths Momj", "Wdxp"),
            new Tretja.Oseba("Vwkq Mbcw", "Kppz"),
            new Tretja.Oseba("Rod Emze", "Ivcy"),
            new Tretja.Oseba("Juhi Ktkz", "Kppz"),
            new Tretja.Oseba("Sirz Schf", "Ivcy"),
            new Tretja.Oseba("Ehi Nbvt", "Kppz"),
            new Tretja.Oseba("Ywdr Eone", "Vvtw"),
            new Tretja.Oseba("Kdss Zeav", "Ivcy"),
            new Tretja.Oseba("Uthz Nlix", "Ivcy"),
            new Tretja.Oseba("Xtuu Bfav", "Kppz"),
            new Tretja.Oseba("Tdhm Spax", "Vvtw"),
            new Tretja.Oseba("Dkih Oezj", "Wdxp"),
            new Tretja.Oseba("Nkzr Irpo", "Ivcy"),
            new Tretja.Oseba("Pzny Bvor", "Ivcy"),
            new Tretja.Oseba("Hppt Fkfu", "Ivcy"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Utcr", "Kppz"),
            new Tretja.Cilj("Bivv", "Kgkf"),
            new Tretja.Cilj("Ptar", "Kgkf"),
            new Tretja.Cilj("Rgvu", "Vvtw"),
            new Tretja.Cilj("Dgqk", "Kppz"),
            new Tretja.Cilj("Pfpl", "Kgkf"),
            new Tretja.Cilj("Jrgd", "Ivcy"),
            new Tretja.Cilj("Hiht", "Vvtw"),
            new Tretja.Cilj("Pwyu", "Ivcy"),
            new Tretja.Cilj("Jowc", "Kgkf"),
            new Tretja.Cilj("Jn", "Kgkf"),
            new Tretja.Cilj("Siec", "Vvtw"),
            new Tretja.Cilj("Wgiw", "Vvtw"),
            new Tretja.Cilj("Owxe", "Kppz"),
            new Tretja.Cilj("Wcww", "Wdxp"),
            new Tretja.Cilj("Tatt", "Wdxp"),
            new Tretja.Cilj("Bbzw", "Kppz"),
            new Tretja.Cilj("Xhrb", "Kgkf"),
            new Tretja.Cilj("Krcu", "Ivcy"),
            new Tretja.Cilj("Msjj", "Kppz"),
            new Tretja.Cilj("Vels", "Kppz"),
            new Tretja.Cilj("Egwl", "Ivcy"),
            new Tretja.Cilj("Xnqj", "Kppz"),
            new Tretja.Cilj("Gbwk", "Ivcy"),
            new Tretja.Cilj("Xpbm", "Wdxp"),
            new Tretja.Cilj("Couo", "Wdxp"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[27], cilji[12], 2008),
            new Tretja.Nocitev(osebe[14], cilji[10], 2006),
            new Tretja.Nocitev(osebe[15], cilji[17], 2009),
            new Tretja.Nocitev(osebe[1], cilji[21], 2013),
            new Tretja.Nocitev(osebe[25], cilji[6], 2009),
            new Tretja.Nocitev(osebe[4], cilji[17], 2013),
            new Tretja.Nocitev(osebe[9], cilji[3], 2013),
            new Tretja.Nocitev(osebe[0], cilji[11], 2006),
            new Tretja.Nocitev(osebe[26], cilji[18], 2005),
            new Tretja.Nocitev(osebe[14], cilji[10], 2005),
            new Tretja.Nocitev(osebe[5], cilji[14], 2017),
            new Tretja.Nocitev(osebe[20], cilji[9], 2020),
            new Tretja.Nocitev(osebe[25], cilji[17], 2010),
            new Tretja.Nocitev(osebe[29], cilji[24], 2002),
            new Tretja.Nocitev(osebe[22], cilji[1], 2003),
            new Tretja.Nocitev(osebe[14], cilji[10], 2006),
            new Tretja.Nocitev(osebe[0], cilji[19], 2000),
            new Tretja.Nocitev(osebe[27], cilji[12], 2012),
            new Tretja.Nocitev(osebe[13], cilji[3], 2005),
            new Tretja.Nocitev(osebe[16], cilji[22], 2016),
            new Tretja.Nocitev(osebe[26], cilji[2], 2003),
            new Tretja.Nocitev(osebe[33], cilji[25], 2016),
            new Tretja.Nocitev(osebe[3], cilji[1], 2004),
            new Tretja.Nocitev(osebe[30], cilji[7], 2003),
            new Tretja.Nocitev(osebe[24], cilji[7], 2018),
            new Tretja.Nocitev(osebe[22], cilji[22], 2003),
            new Tretja.Nocitev(osebe[5], cilji[14], 2006),
            new Tretja.Nocitev(osebe[31], cilji[20], 2017),
            new Tretja.Nocitev(osebe[6], cilji[12], 2019),
            new Tretja.Nocitev(osebe[16], cilji[22], 2004),
            new Tretja.Nocitev(osebe[33], cilji[25], 2001),
            new Tretja.Nocitev(osebe[2], cilji[7], 2003),
            new Tretja.Nocitev(osebe[23], cilji[10], 2007),
            new Tretja.Nocitev(osebe[26], cilji[10], 2005),
            new Tretja.Nocitev(osebe[23], cilji[13], 2011),
            new Tretja.Nocitev(osebe[5], cilji[14], 2009),
            new Tretja.Nocitev(osebe[34], cilji[0], 2020),
            new Tretja.Nocitev(osebe[10], cilji[6], 2008),
            new Tretja.Nocitev(osebe[15], cilji[13], 2000),
            new Tretja.Nocitev(osebe[3], cilji[6], 2005),
            new Tretja.Nocitev(osebe[32], cilji[9], 2013),
            new Tretja.Nocitev(osebe[1], cilji[22], 2002),
            new Tretja.Nocitev(osebe[33], cilji[25], 2008),
            new Tretja.Nocitev(osebe[31], cilji[20], 2007),
            new Tretja.Nocitev(osebe[30], cilji[7], 2005),
            new Tretja.Nocitev(osebe[24], cilji[23], 2009),
            new Tretja.Nocitev(osebe[24], cilji[8], 2015),
            new Tretja.Nocitev(osebe[32], cilji[9], 2013),
            new Tretja.Nocitev(osebe[2], cilji[7], 2002),
            new Tretja.Nocitev(osebe[23], cilji[10], 2016),
            new Tretja.Nocitev(osebe[16], cilji[22], 2015),
            new Tretja.Nocitev(osebe[11], cilji[9], 2011),
            new Tretja.Nocitev(osebe[35], cilji[0], 2018),
            new Tretja.Nocitev(osebe[17], cilji[25], 2004),
            new Tretja.Nocitev(osebe[31], cilji[20], 2013),
            new Tretja.Nocitev(osebe[21], cilji[10], 2008),
            new Tretja.Nocitev(osebe[5], cilji[14], 2014),
            new Tretja.Nocitev(osebe[20], cilji[9], 2010),
            new Tretja.Nocitev(osebe[33], cilji[25], 2015),
            new Tretja.Nocitev(osebe[25], cilji[0], 2017),
            new Tretja.Nocitev(osebe[4], cilji[21], 2001),
            new Tretja.Nocitev(osebe[31], cilji[20], 2004),
            new Tretja.Nocitev(osebe[33], cilji[25], 2012),
            new Tretja.Nocitev(osebe[28], cilji[9], 2014),
            new Tretja.Nocitev(osebe[5], cilji[14], 2013),
            new Tretja.Nocitev(osebe[10], cilji[6], 2018),
            new Tretja.Nocitev(osebe[33], cilji[25], 2014),
            new Tretja.Nocitev(osebe[34], cilji[4], 2015),
            new Tretja.Nocitev(osebe[31], cilji[20], 2018),
            new Tretja.Nocitev(osebe[30], cilji[7], 2009),
            new Tretja.Nocitev(osebe[9], cilji[3], 2020),
            new Tretja.Nocitev(osebe[14], cilji[10], 2008),
            new Tretja.Nocitev(osebe[5], cilji[14], 2004),
            new Tretja.Nocitev(osebe[5], cilji[14], 2019),
            new Tretja.Nocitev(osebe[9], cilji[3], 2018),
            new Tretja.Nocitev(osebe[10], cilji[6], 2002),
            new Tretja.Nocitev(osebe[32], cilji[9], 2008),
            new Tretja.Nocitev(osebe[12], cilji[2], 2009),
            new Tretja.Nocitev(osebe[19], cilji[21], 2007),
            new Tretja.Nocitev(osebe[1], cilji[8], 2000),
            new Tretja.Nocitev(osebe[2], cilji[7], 2003),
            new Tretja.Nocitev(osebe[27], cilji[12], 2002),
            new Tretja.Nocitev(osebe[19], cilji[12], 2017),
            new Tretja.Nocitev(osebe[32], cilji[9], 2002),
            new Tretja.Nocitev(osebe[9], cilji[3], 2012),
            new Tretja.Nocitev(osebe[0], cilji[17], 2011),
            new Tretja.Nocitev(osebe[13], cilji[3], 2003),
            new Tretja.Nocitev(osebe[34], cilji[17], 2013),
            new Tretja.Nocitev(osebe[25], cilji[23], 2001),
            new Tretja.Nocitev(osebe[22], cilji[1], 2014),
            new Tretja.Nocitev(osebe[17], cilji[25], 2010),
            new Tretja.Nocitev(osebe[5], cilji[14], 2003),
            new Tretja.Nocitev(osebe[2], cilji[7], 2003),
            new Tretja.Nocitev(osebe[8], cilji[6], 2017),
            new Tretja.Nocitev(osebe[7], cilji[2], 2019),
            new Tretja.Nocitev(osebe[11], cilji[10], 2011),
            new Tretja.Nocitev(osebe[10], cilji[6], 2012),
            new Tretja.Nocitev(osebe[19], cilji[17], 2007),
            new Tretja.Nocitev(osebe[23], cilji[0], 2002),
            new Tretja.Nocitev(osebe[14], cilji[10], 2004),
            new Tretja.Nocitev(osebe[6], cilji[16], 2002),
            new Tretja.Nocitev(osebe[4], cilji[14], 2018),
            new Tretja.Nocitev(osebe[5], cilji[14], 2010),
            new Tretja.Nocitev(osebe[35], cilji[0], 2013),
            new Tretja.Nocitev(osebe[2], cilji[7], 2020),
            new Tretja.Nocitev(osebe[28], cilji[9], 2016),
            new Tretja.Nocitev(osebe[0], cilji[5], 2015),
            new Tretja.Nocitev(osebe[9], cilji[3], 2019),
            new Tretja.Nocitev(osebe[15], cilji[12], 2000),
            new Tretja.Nocitev(osebe[35], cilji[0], 2009),
            new Tretja.Nocitev(osebe[2], cilji[7], 2005),
            new Tretja.Nocitev(osebe[15], cilji[18], 2010),
            new Tretja.Nocitev(osebe[33], cilji[25], 2001),
            new Tretja.Nocitev(osebe[0], cilji[15], 2007),
            new Tretja.Nocitev(osebe[27], cilji[12], 2000),
            new Tretja.Nocitev(osebe[29], cilji[24], 2015),
            new Tretja.Nocitev(osebe[35], cilji[0], 2005),
            new Tretja.Nocitev(osebe[4], cilji[6], 2011),
            new Tretja.Nocitev(osebe[1], cilji[23], 2006),
            new Tretja.Nocitev(osebe[24], cilji[15], 2019),
            new Tretja.Nocitev(osebe[30], cilji[7], 2014),
            new Tretja.Nocitev(osebe[35], cilji[0], 2019),
            new Tretja.Nocitev(osebe[29], cilji[24], 2005),
            new Tretja.Nocitev(osebe[9], cilji[3], 2008),
            new Tretja.Nocitev(osebe[6], cilji[19], 2008),
            new Tretja.Nocitev(osebe[8], cilji[1], 2000),
            new Tretja.Nocitev(osebe[1], cilji[17], 2005),
            new Tretja.Nocitev(osebe[20], cilji[9], 2002),
            new Tretja.Nocitev(osebe[9], cilji[3], 2006),
            new Tretja.Nocitev(osebe[14], cilji[10], 2019),
            new Tretja.Nocitev(osebe[14], cilji[10], 2000),
            new Tretja.Nocitev(osebe[0], cilji[24], 2017),
            new Tretja.Nocitev(osebe[34], cilji[22], 2004),
            new Tretja.Nocitev(osebe[23], cilji[9], 2001),
            new Tretja.Nocitev(osebe[18], cilji[17], 2001),
            new Tretja.Nocitev(osebe[18], cilji[18], 2016),
            new Tretja.Nocitev(osebe[25], cilji[7], 2019),
            new Tretja.Nocitev(osebe[26], cilji[0], 2009),
            new Tretja.Nocitev(osebe[24], cilji[23], 2019),
            new Tretja.Nocitev(osebe[8], cilji[23], 2015),
            new Tretja.Nocitev(osebe[4], cilji[9], 2000),
            new Tretja.Nocitev(osebe[18], cilji[17], 2003),
            new Tretja.Nocitev(osebe[33], cilji[25], 2000),
            new Tretja.Nocitev(osebe[9], cilji[3], 2018),
            new Tretja.Nocitev(osebe[17], cilji[25], 2011),
            new Tretja.Nocitev(osebe[20], cilji[9], 2007),
            new Tretja.Nocitev(osebe[13], cilji[3], 2013),
            new Tretja.Nocitev(osebe[20], cilji[9], 2019),
            new Tretja.Nocitev(osebe[7], cilji[2], 2019),
            new Tretja.Nocitev(osebe[1], cilji[10], 2001),
            new Tretja.Nocitev(osebe[4], cilji[6], 2010),
            new Tretja.Nocitev(osebe[13], cilji[3], 2015),
            new Tretja.Nocitev(osebe[12], cilji[2], 2014),
            new Tretja.Nocitev(osebe[5], cilji[14], 2014),
            new Tretja.Nocitev(osebe[6], cilji[0], 2019),
            new Tretja.Nocitev(osebe[14], cilji[10], 2019),
            new Tretja.Nocitev(osebe[16], cilji[22], 2015),
            new Tretja.Nocitev(osebe[17], cilji[25], 2018),
            new Tretja.Nocitev(osebe[30], cilji[7], 2012),
            new Tretja.Nocitev(osebe[1], cilji[13], 2017),
            new Tretja.Nocitev(osebe[24], cilji[9], 2004),
            new Tretja.Nocitev(osebe[22], cilji[22], 2013),
            new Tretja.Nocitev(osebe[22], cilji[16], 2011),
            new Tretja.Nocitev(osebe[21], cilji[20], 2010),
            new Tretja.Nocitev(osebe[21], cilji[8], 2019),
            new Tretja.Nocitev(osebe[15], cilji[7], 2019),
            new Tretja.Nocitev(osebe[11], cilji[25], 2016),
            new Tretja.Nocitev(osebe[16], cilji[22], 2018),
            new Tretja.Nocitev(osebe[9], cilji[3], 2013),
            new Tretja.Nocitev(osebe[3], cilji[11], 2001),
            new Tretja.Nocitev(osebe[26], cilji[4], 2014),
            new Tretja.Nocitev(osebe[35], cilji[0], 2019),
            new Tretja.Nocitev(osebe[26], cilji[19], 2006),
            new Tretja.Nocitev(osebe[3], cilji[2], 2003),
            new Tretja.Nocitev(osebe[20], cilji[9], 2020),
            new Tretja.Nocitev(osebe[31], cilji[20], 2011),
            new Tretja.Nocitev(osebe[27], cilji[12], 2019),
            new Tretja.Nocitev(osebe[12], cilji[2], 2010),
            new Tretja.Nocitev(osebe[2], cilji[7], 2010),
            new Tretja.Nocitev(osebe[1], cilji[3], 2006),
            new Tretja.Nocitev(osebe[33], cilji[25], 2009),
            new Tretja.Nocitev(osebe[9], cilji[3], 2009),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
