
public class Test19 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Vtil Dkbc", "Cyvx"),
            new Tretja.Oseba("Sdvm Vnoi", "Brie"),
            new Tretja.Oseba("Lijl Fnq", "Cuhz"),
            new Tretja.Oseba("Cgml Xcxd", "Qfel"),
            new Tretja.Oseba("Qojf Xqik", "Brie"),
            new Tretja.Oseba("Cuqr Kqdw", "Brie"),
            new Tretja.Oseba("Mrbt Rsmj", "Brie"),
            new Tretja.Oseba("Gyz Mbne", "Qfel"),
            new Tretja.Oseba("Djmu Yyky", "Cuhz"),
            new Tretja.Oseba("Gaku Xovp", "Qfel"),
            new Tretja.Oseba("Zcgm Brsg", "Cyvx"),
            new Tretja.Oseba("Rlxl Efiy", "Brie"),
            new Tretja.Oseba("Ziky Lkyk", "Qfel"),
            new Tretja.Oseba("Mqvr Tevv", "Cuhz"),
            new Tretja.Oseba("Xyoq Tazu", "Cuhz"),
            new Tretja.Oseba("Nhwl Swne", "Cuhz"),
            new Tretja.Oseba("Rzgt Fukz", "Cyvx"),
            new Tretja.Oseba("Btva Rujv", "Brie"),
            new Tretja.Oseba("Zilj Jvev", "Brie"),
            new Tretja.Oseba("Avoy Ipce", "Brie"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Ubpe", "Qfel"),
            new Tretja.Cilj("Unzr", "Cyvx"),
            new Tretja.Cilj("Zrzm", "Qfel"),
            new Tretja.Cilj("Soye", "Cuhz"),
            new Tretja.Cilj("Ehog", "Cuhz"),
            new Tretja.Cilj("Zujv", "Qfel"),
            new Tretja.Cilj("Ctea", "Cyvx"),
            new Tretja.Cilj("Dovo", "Cuhz"),
            new Tretja.Cilj("Cxzn", "Cyvx"),
            new Tretja.Cilj("Qreu", "Qfel"),
            new Tretja.Cilj("Awvb", "Qfel"),
            new Tretja.Cilj("Fgsl", "Cuhz"),
            new Tretja.Cilj("Ypfw", "Brie"),
            new Tretja.Cilj("Peex", "Cuhz"),
            new Tretja.Cilj("Vzpy", "Qfel"),
            new Tretja.Cilj("Yptg", "Brie"),
            new Tretja.Cilj("Hea", "Qfel"),
            new Tretja.Cilj("Dlsk", "Qfel"),
            new Tretja.Cilj("Befl", "Qfel"),
            new Tretja.Cilj("Ogjr", "Qfel"),
            new Tretja.Cilj("Nhry", "Brie"),
            new Tretja.Cilj("Axjc", "Cuhz"),
            new Tretja.Cilj("Hdfy", "Brie"),
            new Tretja.Cilj("Hjis", "Cuhz"),
            new Tretja.Cilj("Vzpb", "Brie"),
            new Tretja.Cilj("Mavd", "Cuhz"),
            new Tretja.Cilj("Dogg", "Cyvx"),
            new Tretja.Cilj("Wxxd", "Qfel"),
            new Tretja.Cilj("Gwi", "Qfel"),
            new Tretja.Cilj("Jrmd", "Cuhz"),
            new Tretja.Cilj("Ekec", "Qfel"),
            new Tretja.Cilj("Qqyy", "Cyvx"),
            new Tretja.Cilj("Rgio", "Brie"),
            new Tretja.Cilj("Wbcm", "Cuhz"),
            new Tretja.Cilj("Ttxp", "Brie"),
            new Tretja.Cilj("Qkyd", "Cyvx"),
            new Tretja.Cilj("Hjwv", "Qfel"),
            new Tretja.Cilj("Wtau", "Cuhz"),
            new Tretja.Cilj("Pyte", "Brie"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[15], cilji[20], 2018),
            new Tretja.Nocitev(osebe[7], cilji[21], 2000),
            new Tretja.Nocitev(osebe[19], cilji[38], 2016),
            new Tretja.Nocitev(osebe[12], cilji[23], 2014),
            new Tretja.Nocitev(osebe[19], cilji[12], 2000),
            new Tretja.Nocitev(osebe[16], cilji[5], 2002),
            new Tretja.Nocitev(osebe[14], cilji[18], 2016),
            new Tretja.Nocitev(osebe[15], cilji[20], 2003),
            new Tretja.Nocitev(osebe[15], cilji[20], 2010),
            new Tretja.Nocitev(osebe[8], cilji[21], 2006),
            new Tretja.Nocitev(osebe[5], cilji[4], 2014),
            new Tretja.Nocitev(osebe[11], cilji[21], 2006),
            new Tretja.Nocitev(osebe[8], cilji[25], 2012),
            new Tretja.Nocitev(osebe[13], cilji[4], 2005),
            new Tretja.Nocitev(osebe[17], cilji[12], 2012),
            new Tretja.Nocitev(osebe[1], cilji[16], 2017),
            new Tretja.Nocitev(osebe[15], cilji[20], 2013),
            new Tretja.Nocitev(osebe[0], cilji[24], 2016),
            new Tretja.Nocitev(osebe[12], cilji[13], 2019),
            new Tretja.Nocitev(osebe[2], cilji[18], 2018),
            new Tretja.Nocitev(osebe[2], cilji[18], 2018),
            new Tretja.Nocitev(osebe[5], cilji[4], 2009),
            new Tretja.Nocitev(osebe[15], cilji[20], 2013),
            new Tretja.Nocitev(osebe[8], cilji[8], 2003),
            new Tretja.Nocitev(osebe[13], cilji[26], 2011),
            new Tretja.Nocitev(osebe[19], cilji[9], 2018),
            new Tretja.Nocitev(osebe[11], cilji[21], 2016),
            new Tretja.Nocitev(osebe[8], cilji[23], 2008),
            new Tretja.Nocitev(osebe[13], cilji[38], 2007),
            new Tretja.Nocitev(osebe[19], cilji[13], 2019),
            new Tretja.Nocitev(osebe[3], cilji[24], 2012),
            new Tretja.Nocitev(osebe[2], cilji[18], 2009),
            new Tretja.Nocitev(osebe[0], cilji[21], 2012),
            new Tretja.Nocitev(osebe[6], cilji[35], 2013),
            new Tretja.Nocitev(osebe[0], cilji[20], 2013),
            new Tretja.Nocitev(osebe[0], cilji[20], 2011),
            new Tretja.Nocitev(osebe[4], cilji[21], 2011),
            new Tretja.Nocitev(osebe[9], cilji[13], 2013),
            new Tretja.Nocitev(osebe[18], cilji[31], 2005),
            new Tretja.Nocitev(osebe[17], cilji[28], 2002),
            new Tretja.Nocitev(osebe[16], cilji[7], 2014),
            new Tretja.Nocitev(osebe[0], cilji[5], 2007),
            new Tretja.Nocitev(osebe[19], cilji[4], 2002),
            new Tretja.Nocitev(osebe[0], cilji[8], 2002),
            new Tretja.Nocitev(osebe[15], cilji[20], 2012),
            new Tretja.Nocitev(osebe[0], cilji[19], 2020),
            new Tretja.Nocitev(osebe[8], cilji[15], 2015),
            new Tretja.Nocitev(osebe[14], cilji[0], 2018),
            new Tretja.Nocitev(osebe[0], cilji[19], 2004),
            new Tretja.Nocitev(osebe[7], cilji[25], 2015),
            new Tretja.Nocitev(osebe[4], cilji[32], 2005),
            new Tretja.Nocitev(osebe[0], cilji[2], 2004),
            new Tretja.Nocitev(osebe[14], cilji[30], 2003),
            new Tretja.Nocitev(osebe[14], cilji[12], 2009),
            new Tretja.Nocitev(osebe[15], cilji[20], 2010),
            new Tretja.Nocitev(osebe[3], cilji[24], 2014),
            new Tretja.Nocitev(osebe[10], cilji[13], 2012),
            new Tretja.Nocitev(osebe[3], cilji[24], 2007),
            new Tretja.Nocitev(osebe[6], cilji[35], 2004),
            new Tretja.Nocitev(osebe[4], cilji[25], 2014),
            new Tretja.Nocitev(osebe[5], cilji[4], 2001),
            new Tretja.Nocitev(osebe[2], cilji[18], 2017),
            new Tretja.Nocitev(osebe[7], cilji[27], 2010),
            new Tretja.Nocitev(osebe[16], cilji[35], 2014),
            new Tretja.Nocitev(osebe[5], cilji[4], 2019),
            new Tretja.Nocitev(osebe[17], cilji[19], 2018),
            new Tretja.Nocitev(osebe[16], cilji[22], 2006),
            new Tretja.Nocitev(osebe[13], cilji[1], 2010),
            new Tretja.Nocitev(osebe[6], cilji[35], 2012),
            new Tretja.Nocitev(osebe[3], cilji[24], 2016),
            new Tretja.Nocitev(osebe[14], cilji[33], 2006),
            new Tretja.Nocitev(osebe[17], cilji[2], 2008),
            new Tretja.Nocitev(osebe[8], cilji[16], 2017),
            new Tretja.Nocitev(osebe[18], cilji[31], 2012),
            new Tretja.Nocitev(osebe[19], cilji[21], 2010),
            new Tretja.Nocitev(osebe[0], cilji[38], 2019),
            new Tretja.Nocitev(osebe[19], cilji[4], 2002),
            new Tretja.Nocitev(osebe[4], cilji[2], 2001),
            new Tretja.Nocitev(osebe[6], cilji[35], 2008),
            new Tretja.Nocitev(osebe[15], cilji[20], 2004),
            new Tretja.Nocitev(osebe[10], cilji[13], 2012),
            new Tretja.Nocitev(osebe[3], cilji[24], 2019),
            new Tretja.Nocitev(osebe[13], cilji[20], 2019),
            new Tretja.Nocitev(osebe[16], cilji[22], 2000),
            new Tretja.Nocitev(osebe[11], cilji[21], 2004),
            new Tretja.Nocitev(osebe[8], cilji[28], 2012),
            new Tretja.Nocitev(osebe[7], cilji[11], 2016),
            new Tretja.Nocitev(osebe[3], cilji[24], 2019),
            new Tretja.Nocitev(osebe[16], cilji[26], 2004),
            new Tretja.Nocitev(osebe[5], cilji[4], 2003),
            new Tretja.Nocitev(osebe[2], cilji[18], 2004),
            new Tretja.Nocitev(osebe[12], cilji[3], 2013),
            new Tretja.Nocitev(osebe[17], cilji[33], 2003),
            new Tretja.Nocitev(osebe[4], cilji[34], 2019),
            new Tretja.Nocitev(osebe[19], cilji[10], 2003),
            new Tretja.Nocitev(osebe[4], cilji[33], 2000),
            new Tretja.Nocitev(osebe[6], cilji[35], 2012),
            new Tretja.Nocitev(osebe[4], cilji[5], 2007),
            new Tretja.Nocitev(osebe[9], cilji[13], 2001),
            new Tretja.Nocitev(osebe[15], cilji[20], 2014),
            new Tretja.Nocitev(osebe[8], cilji[19], 2011),
            new Tretja.Nocitev(osebe[5], cilji[4], 2013),
            new Tretja.Nocitev(osebe[17], cilji[21], 2011),
            new Tretja.Nocitev(osebe[1], cilji[16], 2000),
            new Tretja.Nocitev(osebe[2], cilji[18], 2003),
            new Tretja.Nocitev(osebe[3], cilji[24], 2002),
            new Tretja.Nocitev(osebe[0], cilji[32], 2009),
            new Tretja.Nocitev(osebe[0], cilji[28], 2002),
            new Tretja.Nocitev(osebe[4], cilji[33], 2016),
            new Tretja.Nocitev(osebe[15], cilji[20], 2010),
            new Tretja.Nocitev(osebe[15], cilji[20], 2001),
            new Tretja.Nocitev(osebe[5], cilji[4], 2005),
            new Tretja.Nocitev(osebe[11], cilji[21], 2009),
            new Tretja.Nocitev(osebe[10], cilji[13], 2017),
            new Tretja.Nocitev(osebe[0], cilji[16], 2015),
            new Tretja.Nocitev(osebe[10], cilji[13], 2002),
            new Tretja.Nocitev(osebe[2], cilji[18], 2003),
            new Tretja.Nocitev(osebe[6], cilji[35], 2016),
            new Tretja.Nocitev(osebe[0], cilji[29], 2002),
            new Tretja.Nocitev(osebe[7], cilji[20], 2009),
            new Tretja.Nocitev(osebe[2], cilji[18], 2003),
            new Tretja.Nocitev(osebe[3], cilji[24], 2001),
            new Tretja.Nocitev(osebe[5], cilji[4], 2010),
            new Tretja.Nocitev(osebe[17], cilji[26], 2010),
            new Tretja.Nocitev(osebe[19], cilji[33], 2006),
            new Tretja.Nocitev(osebe[14], cilji[29], 2004),
            new Tretja.Nocitev(osebe[18], cilji[31], 2001),
            new Tretja.Nocitev(osebe[3], cilji[24], 2019),
            new Tretja.Nocitev(osebe[0], cilji[7], 2005),
            new Tretja.Nocitev(osebe[7], cilji[14], 2015),
            new Tretja.Nocitev(osebe[2], cilji[18], 2007),
            new Tretja.Nocitev(osebe[8], cilji[11], 2017),
            new Tretja.Nocitev(osebe[8], cilji[9], 2003),
            new Tretja.Nocitev(osebe[0], cilji[29], 2017),
            new Tretja.Nocitev(osebe[2], cilji[18], 2020),
            new Tretja.Nocitev(osebe[15], cilji[20], 2003),
            new Tretja.Nocitev(osebe[7], cilji[28], 2001),
            new Tretja.Nocitev(osebe[12], cilji[15], 2004),
            new Tretja.Nocitev(osebe[9], cilji[13], 2018),
            new Tretja.Nocitev(osebe[1], cilji[16], 2020),
            new Tretja.Nocitev(osebe[15], cilji[20], 2009),
            new Tretja.Nocitev(osebe[19], cilji[25], 2002),
            new Tretja.Nocitev(osebe[1], cilji[16], 2002),
            new Tretja.Nocitev(osebe[11], cilji[21], 2019),
            new Tretja.Nocitev(osebe[12], cilji[30], 2003),
            new Tretja.Nocitev(osebe[19], cilji[16], 2010),
            new Tretja.Nocitev(osebe[9], cilji[13], 2012),
            new Tretja.Nocitev(osebe[17], cilji[7], 2016),
            new Tretja.Nocitev(osebe[12], cilji[2], 2014),
            new Tretja.Nocitev(osebe[13], cilji[28], 2003),
            new Tretja.Nocitev(osebe[8], cilji[22], 2001),
            new Tretja.Nocitev(osebe[9], cilji[13], 2020),
            new Tretja.Nocitev(osebe[10], cilji[13], 2002),
            new Tretja.Nocitev(osebe[9], cilji[13], 2002),
            new Tretja.Nocitev(osebe[7], cilji[11], 2012),
            new Tretja.Nocitev(osebe[1], cilji[16], 2010),
            new Tretja.Nocitev(osebe[5], cilji[4], 2014),
            new Tretja.Nocitev(osebe[19], cilji[19], 2004),
            new Tretja.Nocitev(osebe[0], cilji[0], 2011),
            new Tretja.Nocitev(osebe[18], cilji[31], 2007),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
