
public class Test16 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Jpmh Vaxm", "Jxy"),
            new Tretja.Oseba("Ofdw Rbgw", "Jxy"),
            new Tretja.Oseba("Wnbv Hfqc", "Jxy"),
            new Tretja.Oseba("Hgkb Cweu", "Cvnl"),
            new Tretja.Oseba("Vylq Zwan", "Utkp"),
            new Tretja.Oseba("Susx Wpe", "Getm"),
            new Tretja.Oseba("Pmpw Hygo", "Ygha"),
            new Tretja.Oseba("Dcbg Fogn", "Getm"),
            new Tretja.Oseba("Vrdh Vplr", "Utkp"),
            new Tretja.Oseba("Umoy Loka", "Ygha"),
            new Tretja.Oseba("Awcx Ymgr", "Getm"),
            new Tretja.Oseba("Qfxu Aiwg", "Getm"),
            new Tretja.Oseba("Lwjk Rgme", "Getm"),
            new Tretja.Oseba("Rcur Fqmy", "Jxy"),
            new Tretja.Oseba("Vqen Mwpl", "Cvnl"),
            new Tretja.Oseba("Ikrx Hztb", "Utkp"),
            new Tretja.Oseba("Rkjj Obmu", "Utkp"),
            new Tretja.Oseba("Eskn Ucpc", "Ygha"),
            new Tretja.Oseba("Owsa Gyms", "Utkp"),
            new Tretja.Oseba("Pgqx Csks", "Cvnl"),
            new Tretja.Oseba("Dgmg Jjvm", "Utkp"),
            new Tretja.Oseba("Dhfa Pumt", "Jxy"),
            new Tretja.Oseba("Xoca Cswo", "Jxy"),
            new Tretja.Oseba("Iadg Sdoo", "Ygha"),
            new Tretja.Oseba("Murg Hipa", "Ygha"),
            new Tretja.Oseba("Ilru Bojl", "Ygha"),
            new Tretja.Oseba("Mfkw Zrqr", "Cvnl"),
            new Tretja.Oseba("Juya Pbio", "Cvnl"),
            new Tretja.Oseba("Psmq Hpga", "Jxy"),
            new Tretja.Oseba("Yqph Amkm", "Cvnl"),
            new Tretja.Oseba("Naky Fjcf", "Getm"),
            new Tretja.Oseba("Citr Lfxu", "Cvnl"),
            new Tretja.Oseba("Dxz Afot", "Jxy"),
            new Tretja.Oseba("Hpfr Zjzt", "Getm"),
            new Tretja.Oseba("Tnry Lxbc", "Utkp"),
            new Tretja.Oseba("Xqky Dwtv", "Ygha"),
            new Tretja.Oseba("Obu Jppk", "Utkp"),
            new Tretja.Oseba("Xmlw Uvud", "Ygha"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Gzwx", "Ygha"),
            new Tretja.Cilj("Vpzc", "Jxy"),
            new Tretja.Cilj("Frkb", "Ygha"),
            new Tretja.Cilj("Sgeu", "Ygha"),
            new Tretja.Cilj("Iny", "Utkp"),
            new Tretja.Cilj("Mwvr", "Ygha"),
            new Tretja.Cilj("Pgsv", "Utkp"),
            new Tretja.Cilj("Bhvp", "Getm"),
            new Tretja.Cilj("Pwxn", "Jxy"),
            new Tretja.Cilj("Ligh", "Cvnl"),
            new Tretja.Cilj("Sdvt", "Cvnl"),
            new Tretja.Cilj("Khdo", "Getm"),
            new Tretja.Cilj("Skwd", "Jxy"),
            new Tretja.Cilj("Lbgd", "Jxy"),
            new Tretja.Cilj("Nnnr", "Jxy"),
            new Tretja.Cilj("Qayd", "Utkp"),
            new Tretja.Cilj("Kbab", "Utkp"),
            new Tretja.Cilj("Suko", "Getm"),
            new Tretja.Cilj("Rwmy", "Ygha"),
            new Tretja.Cilj("Pbho", "Utkp"),
            new Tretja.Cilj("Vatf", "Getm"),
            new Tretja.Cilj("Mjpa", "Ygha"),
            new Tretja.Cilj("Oyvd", "Ygha"),
            new Tretja.Cilj("Czhf", "Getm"),
            new Tretja.Cilj("Qzkl", "Ygha"),
            new Tretja.Cilj("Ocet", "Getm"),
            new Tretja.Cilj("Kury", "Utkp"),
            new Tretja.Cilj("Thgf", "Ygha"),
            new Tretja.Cilj("Gewq", "Ygha"),
            new Tretja.Cilj("Khsz", "Jxy"),
            new Tretja.Cilj("Krnf", "Jxy"),
            new Tretja.Cilj("Lpam", "Cvnl"),
            new Tretja.Cilj("Bjtj", "Jxy"),
            new Tretja.Cilj("Udtt", "Getm"),
            new Tretja.Cilj("Upuv", "Cvnl"),
            new Tretja.Cilj("Iht", "Utkp"),
            new Tretja.Cilj("Cgj", "Cvnl"),
            new Tretja.Cilj("Vigr", "Ygha"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[30], cilji[15], 2004),
            new Tretja.Nocitev(osebe[30], cilji[15], 2018),
            new Tretja.Nocitev(osebe[34], cilji[7], 2009),
            new Tretja.Nocitev(osebe[6], cilji[34], 2011),
            new Tretja.Nocitev(osebe[1], cilji[12], 2004),
            new Tretja.Nocitev(osebe[14], cilji[20], 2019),
            new Tretja.Nocitev(osebe[18], cilji[0], 2018),
            new Tretja.Nocitev(osebe[4], cilji[24], 2007),
            new Tretja.Nocitev(osebe[34], cilji[7], 2002),
            new Tretja.Nocitev(osebe[3], cilji[15], 2005),
            new Tretja.Nocitev(osebe[28], cilji[8], 2011),
            new Tretja.Nocitev(osebe[22], cilji[34], 2007),
            new Tretja.Nocitev(osebe[24], cilji[30], 2001),
            new Tretja.Nocitev(osebe[25], cilji[31], 2012),
            new Tretja.Nocitev(osebe[31], cilji[4], 2014),
            new Tretja.Nocitev(osebe[18], cilji[0], 2020),
            new Tretja.Nocitev(osebe[1], cilji[32], 2016),
            new Tretja.Nocitev(osebe[28], cilji[29], 2016),
            new Tretja.Nocitev(osebe[27], cilji[15], 2012),
            new Tretja.Nocitev(osebe[23], cilji[15], 2002),
            new Tretja.Nocitev(osebe[7], cilji[22], 2013),
            new Tretja.Nocitev(osebe[23], cilji[15], 2007),
            new Tretja.Nocitev(osebe[22], cilji[14], 2005),
            new Tretja.Nocitev(osebe[19], cilji[31], 2014),
            new Tretja.Nocitev(osebe[33], cilji[11], 2015),
            new Tretja.Nocitev(osebe[24], cilji[30], 2006),
            new Tretja.Nocitev(osebe[32], cilji[32], 2019),
            new Tretja.Nocitev(osebe[20], cilji[10], 2012),
            new Tretja.Nocitev(osebe[5], cilji[14], 2014),
            new Tretja.Nocitev(osebe[15], cilji[31], 2011),
            new Tretja.Nocitev(osebe[4], cilji[24], 2011),
            new Tretja.Nocitev(osebe[17], cilji[33], 2008),
            new Tretja.Nocitev(osebe[22], cilji[24], 2011),
            new Tretja.Nocitev(osebe[8], cilji[4], 2005),
            new Tretja.Nocitev(osebe[17], cilji[22], 2005),
            new Tretja.Nocitev(osebe[22], cilji[29], 2018),
            new Tretja.Nocitev(osebe[30], cilji[15], 2007),
            new Tretja.Nocitev(osebe[34], cilji[7], 2019),
            new Tretja.Nocitev(osebe[29], cilji[23], 2006),
            new Tretja.Nocitev(osebe[2], cilji[33], 2020),
            new Tretja.Nocitev(osebe[7], cilji[22], 2004),
            new Tretja.Nocitev(osebe[7], cilji[22], 2007),
            new Tretja.Nocitev(osebe[24], cilji[30], 2014),
            new Tretja.Nocitev(osebe[12], cilji[17], 2014),
            new Tretja.Nocitev(osebe[18], cilji[0], 2008),
            new Tretja.Nocitev(osebe[16], cilji[2], 2008),
            new Tretja.Nocitev(osebe[16], cilji[5], 2008),
            new Tretja.Nocitev(osebe[5], cilji[14], 2017),
            new Tretja.Nocitev(osebe[5], cilji[14], 2015),
            new Tretja.Nocitev(osebe[33], cilji[11], 2018),
            new Tretja.Nocitev(osebe[22], cilji[19], 2006),
            new Tretja.Nocitev(osebe[36], cilji[16], 2020),
            new Tretja.Nocitev(osebe[35], cilji[4], 2014),
            new Tretja.Nocitev(osebe[25], cilji[31], 2014),
            new Tretja.Nocitev(osebe[26], cilji[1], 2017),
            new Tretja.Nocitev(osebe[34], cilji[7], 2013),
            new Tretja.Nocitev(osebe[7], cilji[22], 2020),
            new Tretja.Nocitev(osebe[9], cilji[15], 2015),
            new Tretja.Nocitev(osebe[22], cilji[31], 2008),
            new Tretja.Nocitev(osebe[27], cilji[15], 2000),
            new Tretja.Nocitev(osebe[36], cilji[18], 2010),
            new Tretja.Nocitev(osebe[27], cilji[15], 2001),
            new Tretja.Nocitev(osebe[2], cilji[33], 2002),
            new Tretja.Nocitev(osebe[26], cilji[1], 2013),
            new Tretja.Nocitev(osebe[17], cilji[18], 2002),
            new Tretja.Nocitev(osebe[13], cilji[3], 2014),
            new Tretja.Nocitev(osebe[10], cilji[36], 2007),
            new Tretja.Nocitev(osebe[4], cilji[24], 2014),
            new Tretja.Nocitev(osebe[17], cilji[36], 2000),
            new Tretja.Nocitev(osebe[36], cilji[23], 2015),
            new Tretja.Nocitev(osebe[14], cilji[7], 2003),
            new Tretja.Nocitev(osebe[10], cilji[12], 2008),
            new Tretja.Nocitev(osebe[1], cilji[25], 2008),
            new Tretja.Nocitev(osebe[0], cilji[17], 2003),
            new Tretja.Nocitev(osebe[23], cilji[15], 2020),
            new Tretja.Nocitev(osebe[0], cilji[21], 2002),
            new Tretja.Nocitev(osebe[32], cilji[32], 2006),
            new Tretja.Nocitev(osebe[12], cilji[17], 2000),
            new Tretja.Nocitev(osebe[27], cilji[15], 2015),
            new Tretja.Nocitev(osebe[15], cilji[22], 2018),
            new Tretja.Nocitev(osebe[13], cilji[3], 2011),
            new Tretja.Nocitev(osebe[4], cilji[24], 2007),
            new Tretja.Nocitev(osebe[37], cilji[3], 2014),
            new Tretja.Nocitev(osebe[14], cilji[20], 2002),
            new Tretja.Nocitev(osebe[18], cilji[0], 2004),
            new Tretja.Nocitev(osebe[17], cilji[35], 2000),
            new Tretja.Nocitev(osebe[31], cilji[4], 2001),
            new Tretja.Nocitev(osebe[4], cilji[24], 2017),
            new Tretja.Nocitev(osebe[31], cilji[4], 2015),
            new Tretja.Nocitev(osebe[8], cilji[22], 2013),
            new Tretja.Nocitev(osebe[31], cilji[4], 2020),
            new Tretja.Nocitev(osebe[15], cilji[10], 2017),
            new Tretja.Nocitev(osebe[15], cilji[20], 2000),
            new Tretja.Nocitev(osebe[11], cilji[10], 2019),
            new Tretja.Nocitev(osebe[18], cilji[0], 2007),
            new Tretja.Nocitev(osebe[36], cilji[26], 2007),
            new Tretja.Nocitev(osebe[0], cilji[10], 2017),
            new Tretja.Nocitev(osebe[4], cilji[24], 2001),
            new Tretja.Nocitev(osebe[37], cilji[3], 2013),
            new Tretja.Nocitev(osebe[11], cilji[14], 2009),
            new Tretja.Nocitev(osebe[14], cilji[23], 2005),
            new Tretja.Nocitev(osebe[25], cilji[31], 2017),
            new Tretja.Nocitev(osebe[11], cilji[35], 2011),
            new Tretja.Nocitev(osebe[30], cilji[15], 2016),
            new Tretja.Nocitev(osebe[6], cilji[10], 2005),
            new Tretja.Nocitev(osebe[1], cilji[31], 2008),
            new Tretja.Nocitev(osebe[4], cilji[24], 2010),
            new Tretja.Nocitev(osebe[32], cilji[32], 2005),
            new Tretja.Nocitev(osebe[28], cilji[27], 2014),
            new Tretja.Nocitev(osebe[4], cilji[24], 2018),
            new Tretja.Nocitev(osebe[6], cilji[25], 2014),
            new Tretja.Nocitev(osebe[20], cilji[10], 2010),
            new Tretja.Nocitev(osebe[10], cilji[19], 2009),
            new Tretja.Nocitev(osebe[10], cilji[12], 2006),
            new Tretja.Nocitev(osebe[15], cilji[36], 2005),
            new Tretja.Nocitev(osebe[21], cilji[1], 2014),
            new Tretja.Nocitev(osebe[9], cilji[20], 2013),
            new Tretja.Nocitev(osebe[1], cilji[30], 2018),
            new Tretja.Nocitev(osebe[5], cilji[14], 2015),
            new Tretja.Nocitev(osebe[1], cilji[1], 2018),
            new Tretja.Nocitev(osebe[15], cilji[10], 2014),
            new Tretja.Nocitev(osebe[1], cilji[30], 2001),
            new Tretja.Nocitev(osebe[30], cilji[15], 2000),
            new Tretja.Nocitev(osebe[33], cilji[11], 2008),
            new Tretja.Nocitev(osebe[7], cilji[22], 2015),
            new Tretja.Nocitev(osebe[35], cilji[4], 2001),
            new Tretja.Nocitev(osebe[6], cilji[9], 2001),
            new Tretja.Nocitev(osebe[7], cilji[22], 2005),
            new Tretja.Nocitev(osebe[15], cilji[37], 2019),
            new Tretja.Nocitev(osebe[20], cilji[10], 2020),
            new Tretja.Nocitev(osebe[20], cilji[10], 2010),
            new Tretja.Nocitev(osebe[9], cilji[37], 2010),
            new Tretja.Nocitev(osebe[28], cilji[20], 2005),
            new Tretja.Nocitev(osebe[24], cilji[30], 2020),
            new Tretja.Nocitev(osebe[16], cilji[26], 2006),
            new Tretja.Nocitev(osebe[4], cilji[24], 2007),
            new Tretja.Nocitev(osebe[25], cilji[31], 2009),
            new Tretja.Nocitev(osebe[16], cilji[1], 2004),
            new Tretja.Nocitev(osebe[3], cilji[6], 2003),
            new Tretja.Nocitev(osebe[5], cilji[14], 2010),
            new Tretja.Nocitev(osebe[11], cilji[23], 2011),
            new Tretja.Nocitev(osebe[27], cilji[15], 2011),
            new Tretja.Nocitev(osebe[24], cilji[30], 2012),
            new Tretja.Nocitev(osebe[8], cilji[2], 2005),
            new Tretja.Nocitev(osebe[0], cilji[21], 2004),
            new Tretja.Nocitev(osebe[12], cilji[17], 2007),
            new Tretja.Nocitev(osebe[33], cilji[11], 2015),
            new Tretja.Nocitev(osebe[25], cilji[31], 2016),
            new Tretja.Nocitev(osebe[10], cilji[30], 2006),
            new Tretja.Nocitev(osebe[35], cilji[33], 2014),
            new Tretja.Nocitev(osebe[15], cilji[21], 2001),
            new Tretja.Nocitev(osebe[16], cilji[13], 2002),
            new Tretja.Nocitev(osebe[7], cilji[22], 2015),
            new Tretja.Nocitev(osebe[7], cilji[22], 2007),
            new Tretja.Nocitev(osebe[34], cilji[7], 2000),
            new Tretja.Nocitev(osebe[28], cilji[2], 2005),
            new Tretja.Nocitev(osebe[34], cilji[7], 2001),
            new Tretja.Nocitev(osebe[29], cilji[8], 2001),
            new Tretja.Nocitev(osebe[36], cilji[29], 2016),
            new Tretja.Nocitev(osebe[26], cilji[1], 2006),
            new Tretja.Nocitev(osebe[27], cilji[15], 2016),
            new Tretja.Nocitev(osebe[0], cilji[27], 2004),
            new Tretja.Nocitev(osebe[21], cilji[16], 2001),
            new Tretja.Nocitev(osebe[6], cilji[29], 2020),
            new Tretja.Nocitev(osebe[37], cilji[3], 2020),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
