
public class Test46 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Goow Zbhg", "Mirm"),
            new Tretja.Oseba("Blyh Dbjb", "Vtot"),
            new Tretja.Oseba("Posb Pjdb", "Mirm"),
            new Tretja.Oseba("Svzv Bpfl", "Mirm"),
            new Tretja.Oseba("Egkq Khp", "Mirm"),
            new Tretja.Oseba("Wzmj Icvw", "Mirm"),
            new Tretja.Oseba("Ydz Meru", "Mirm"),
            new Tretja.Oseba("Ziwu Tfom", "Mirm"),
            new Tretja.Oseba("Xzmb Eoxs", "Vtot"),
            new Tretja.Oseba("Tgep Kzrr", "Vtot"),
            new Tretja.Oseba("Lgvj Twt", "Vtot"),
            new Tretja.Oseba("Ersu Gnmo", "Vtot"),
            new Tretja.Oseba("Wksr Iyja", "Vtot"),
            new Tretja.Oseba("Rseo Qxpq", "Mirm"),
            new Tretja.Oseba("Yvgh Pfki", "Vtot"),
            new Tretja.Oseba("Jaoo Nqsw", "Vtot"),
            new Tretja.Oseba("Kclh Gmcp", "Vtot"),
            new Tretja.Oseba("Beag Wgjy", "Vtot"),
            new Tretja.Oseba("Qojd Rnts", "Mirm"),
            new Tretja.Oseba("Pvyg Crxu", "Mirm"),
            new Tretja.Oseba("Jgqa Vbet", "Mirm"),
            new Tretja.Oseba("Snju Siny", "Mirm"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Nhve", "Mirm"),
            new Tretja.Cilj("Gyjl", "Vtot"),
            new Tretja.Cilj("Pseh", "Vtot"),
            new Tretja.Cilj("Msnc", "Vtot"),
            new Tretja.Cilj("Hxrd", "Vtot"),
            new Tretja.Cilj("Ajze", "Mirm"),
            new Tretja.Cilj("Ihmr", "Vtot"),
            new Tretja.Cilj("Szqn", "Vtot"),
            new Tretja.Cilj("Xfyt", "Mirm"),
            new Tretja.Cilj("Xlak", "Mirm"),
            new Tretja.Cilj("Bkxj", "Vtot"),
            new Tretja.Cilj("Klrv", "Vtot"),
            new Tretja.Cilj("Lynb", "Vtot"),
            new Tretja.Cilj("Vpit", "Vtot"),
            new Tretja.Cilj("Wywg", "Mirm"),
            new Tretja.Cilj("Bjfw", "Mirm"),
            new Tretja.Cilj("Numy", "Mirm"),
            new Tretja.Cilj("Faw", "Vtot"),
            new Tretja.Cilj("Ffds", "Mirm"),
            new Tretja.Cilj("Odyj", "Vtot"),
            new Tretja.Cilj("Xzlh", "Vtot"),
            new Tretja.Cilj("Ohtq", "Mirm"),
            new Tretja.Cilj("Smss", "Vtot"),
            new Tretja.Cilj("Gued", "Mirm"),
            new Tretja.Cilj("Aiha", "Mirm"),
            new Tretja.Cilj("Dzgy", "Vtot"),
            new Tretja.Cilj("Pkgm", "Vtot"),
            new Tretja.Cilj("Fuye", "Mirm"),
            new Tretja.Cilj("Hhjt", "Mirm"),
            new Tretja.Cilj("Vikx", "Mirm"),
            new Tretja.Cilj("Xoss", "Vtot"),
            new Tretja.Cilj("Hgjz", "Vtot"),
            new Tretja.Cilj("Zwjx", "Vtot"),
            new Tretja.Cilj("Kpxu", "Mirm"),
            new Tretja.Cilj("Hthn", "Mirm"),
            new Tretja.Cilj("Qwij", "Vtot"),
            new Tretja.Cilj("Acct", "Mirm"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[15], cilji[3], 2007),
            new Tretja.Nocitev(osebe[1], cilji[21], 2004),
            new Tretja.Nocitev(osebe[6], cilji[10], 2002),
            new Tretja.Nocitev(osebe[9], cilji[34], 2011),
            new Tretja.Nocitev(osebe[7], cilji[32], 2010),
            new Tretja.Nocitev(osebe[0], cilji[34], 2004),
            new Tretja.Nocitev(osebe[2], cilji[9], 2003),
            new Tretja.Nocitev(osebe[19], cilji[10], 2004),
            new Tretja.Nocitev(osebe[6], cilji[33], 2000),
            new Tretja.Nocitev(osebe[18], cilji[26], 2013),
            new Tretja.Nocitev(osebe[7], cilji[20], 2016),
            new Tretja.Nocitev(osebe[6], cilji[36], 2016),
            new Tretja.Nocitev(osebe[20], cilji[1], 2017),
            new Tretja.Nocitev(osebe[9], cilji[34], 2008),
            new Tretja.Nocitev(osebe[10], cilji[9], 2012),
            new Tretja.Nocitev(osebe[6], cilji[32], 2005),
            new Tretja.Nocitev(osebe[5], cilji[12], 2009),
            new Tretja.Nocitev(osebe[7], cilji[11], 2012),
            new Tretja.Nocitev(osebe[11], cilji[4], 2004),
            new Tretja.Nocitev(osebe[19], cilji[10], 2018),
            new Tretja.Nocitev(osebe[3], cilji[1], 2014),
            new Tretja.Nocitev(osebe[20], cilji[5], 2009),
            new Tretja.Nocitev(osebe[16], cilji[15], 2007),
            new Tretja.Nocitev(osebe[11], cilji[32], 2011),
            new Tretja.Nocitev(osebe[21], cilji[27], 2019),
            new Tretja.Nocitev(osebe[6], cilji[36], 2011),
            new Tretja.Nocitev(osebe[20], cilji[3], 2011),
            new Tretja.Nocitev(osebe[3], cilji[1], 2013),
            new Tretja.Nocitev(osebe[6], cilji[18], 2014),
            new Tretja.Nocitev(osebe[8], cilji[24], 2006),
            new Tretja.Nocitev(osebe[19], cilji[10], 2016),
            new Tretja.Nocitev(osebe[8], cilji[24], 2001),
            new Tretja.Nocitev(osebe[19], cilji[10], 2016),
            new Tretja.Nocitev(osebe[11], cilji[24], 2019),
            new Tretja.Nocitev(osebe[1], cilji[29], 2012),
            new Tretja.Nocitev(osebe[20], cilji[5], 2003),
            new Tretja.Nocitev(osebe[20], cilji[19], 2004),
            new Tretja.Nocitev(osebe[8], cilji[24], 2018),
            new Tretja.Nocitev(osebe[1], cilji[23], 2004),
            new Tretja.Nocitev(osebe[14], cilji[19], 2011),
            new Tretja.Nocitev(osebe[16], cilji[15], 2002),
            new Tretja.Nocitev(osebe[15], cilji[23], 2011),
            new Tretja.Nocitev(osebe[4], cilji[9], 2001),
            new Tretja.Nocitev(osebe[10], cilji[35], 2001),
            new Tretja.Nocitev(osebe[14], cilji[23], 2004),
            new Tretja.Nocitev(osebe[2], cilji[9], 2017),
            new Tretja.Nocitev(osebe[19], cilji[10], 2010),
            new Tretja.Nocitev(osebe[17], cilji[24], 2004),
            new Tretja.Nocitev(osebe[2], cilji[9], 2017),
            new Tretja.Nocitev(osebe[14], cilji[15], 2013),
            new Tretja.Nocitev(osebe[12], cilji[3], 2003),
            new Tretja.Nocitev(osebe[10], cilji[34], 2004),
            new Tretja.Nocitev(osebe[6], cilji[1], 2016),
            new Tretja.Nocitev(osebe[7], cilji[25], 2012),
            new Tretja.Nocitev(osebe[13], cilji[4], 2016),
            new Tretja.Nocitev(osebe[6], cilji[27], 2009),
            new Tretja.Nocitev(osebe[16], cilji[15], 2002),
            new Tretja.Nocitev(osebe[19], cilji[10], 2005),
            new Tretja.Nocitev(osebe[15], cilji[27], 2010),
            new Tretja.Nocitev(osebe[11], cilji[21], 2013),
            new Tretja.Nocitev(osebe[3], cilji[1], 2007),
            new Tretja.Nocitev(osebe[2], cilji[9], 2009),
            new Tretja.Nocitev(osebe[10], cilji[25], 2010),
            new Tretja.Nocitev(osebe[5], cilji[12], 2003),
            new Tretja.Nocitev(osebe[21], cilji[27], 2016),
            new Tretja.Nocitev(osebe[13], cilji[4], 2009),
            new Tretja.Nocitev(osebe[10], cilji[4], 2002),
            new Tretja.Nocitev(osebe[4], cilji[28], 2017),
            new Tretja.Nocitev(osebe[17], cilji[24], 2010),
            new Tretja.Nocitev(osebe[1], cilji[22], 2003),
            new Tretja.Nocitev(osebe[20], cilji[24], 2013),
            new Tretja.Nocitev(osebe[0], cilji[31], 2010),
            new Tretja.Nocitev(osebe[13], cilji[4], 2015),
            new Tretja.Nocitev(osebe[15], cilji[27], 2019),
            new Tretja.Nocitev(osebe[2], cilji[9], 2016),
            new Tretja.Nocitev(osebe[20], cilji[7], 2018),
            new Tretja.Nocitev(osebe[5], cilji[12], 2000),
            new Tretja.Nocitev(osebe[9], cilji[34], 2015),
            new Tretja.Nocitev(osebe[7], cilji[12], 2002),
            new Tretja.Nocitev(osebe[1], cilji[5], 2017),
            new Tretja.Nocitev(osebe[6], cilji[35], 2003),
            new Tretja.Nocitev(osebe[1], cilji[20], 2004),
            new Tretja.Nocitev(osebe[15], cilji[21], 2007),
            new Tretja.Nocitev(osebe[14], cilji[6], 2017),
            new Tretja.Nocitev(osebe[15], cilji[7], 2002),
            new Tretja.Nocitev(osebe[0], cilji[35], 2019),
            new Tretja.Nocitev(osebe[7], cilji[24], 2005),
            new Tretja.Nocitev(osebe[20], cilji[1], 2005),
            new Tretja.Nocitev(osebe[5], cilji[12], 2011),
            new Tretja.Nocitev(osebe[16], cilji[15], 2003),
            new Tretja.Nocitev(osebe[0], cilji[19], 2010),
            new Tretja.Nocitev(osebe[11], cilji[30], 2004),
            new Tretja.Nocitev(osebe[10], cilji[27], 2009),
            new Tretja.Nocitev(osebe[20], cilji[30], 2020),
            new Tretja.Nocitev(osebe[11], cilji[19], 2004),
            new Tretja.Nocitev(osebe[2], cilji[9], 2018),
            new Tretja.Nocitev(osebe[2], cilji[9], 2013),
            new Tretja.Nocitev(osebe[1], cilji[30], 2019),
            new Tretja.Nocitev(osebe[19], cilji[10], 2020),
            new Tretja.Nocitev(osebe[21], cilji[27], 2018),
            new Tretja.Nocitev(osebe[15], cilji[1], 2012),
            new Tretja.Nocitev(osebe[12], cilji[5], 2016),
            new Tretja.Nocitev(osebe[19], cilji[10], 2007),
            new Tretja.Nocitev(osebe[17], cilji[24], 2011),
            new Tretja.Nocitev(osebe[8], cilji[24], 2006),
            new Tretja.Nocitev(osebe[1], cilji[27], 2014),
            new Tretja.Nocitev(osebe[5], cilji[12], 2014),
            new Tretja.Nocitev(osebe[1], cilji[23], 2016),
            new Tretja.Nocitev(osebe[9], cilji[34], 2003),
            new Tretja.Nocitev(osebe[16], cilji[15], 2017),
            new Tretja.Nocitev(osebe[11], cilji[15], 2007),
            new Tretja.Nocitev(osebe[12], cilji[27], 2016),
            new Tretja.Nocitev(osebe[4], cilji[32], 2006),
            new Tretja.Nocitev(osebe[4], cilji[1], 2013),
            new Tretja.Nocitev(osebe[8], cilji[24], 2001),
            new Tretja.Nocitev(osebe[7], cilji[1], 2011),
            new Tretja.Nocitev(osebe[20], cilji[34], 2012),
            new Tretja.Nocitev(osebe[10], cilji[35], 2008),
            new Tretja.Nocitev(osebe[9], cilji[34], 2011),
            new Tretja.Nocitev(osebe[0], cilji[21], 2015),
            new Tretja.Nocitev(osebe[3], cilji[1], 2004),
            new Tretja.Nocitev(osebe[3], cilji[1], 2005),
            new Tretja.Nocitev(osebe[21], cilji[27], 2009),
            new Tretja.Nocitev(osebe[15], cilji[6], 2010),
            new Tretja.Nocitev(osebe[5], cilji[12], 2012),
            new Tretja.Nocitev(osebe[6], cilji[21], 2019),
            new Tretja.Nocitev(osebe[20], cilji[8], 2014),
            new Tretja.Nocitev(osebe[20], cilji[15], 2019),
            new Tretja.Nocitev(osebe[21], cilji[27], 2013),
            new Tretja.Nocitev(osebe[19], cilji[10], 2000),
            new Tretja.Nocitev(osebe[4], cilji[6], 2020),
            new Tretja.Nocitev(osebe[9], cilji[34], 2000),
            new Tretja.Nocitev(osebe[10], cilji[8], 2007),
            new Tretja.Nocitev(osebe[5], cilji[12], 2000),
            new Tretja.Nocitev(osebe[11], cilji[3], 2002),
            new Tretja.Nocitev(osebe[11], cilji[18], 2014),
            new Tretja.Nocitev(osebe[6], cilji[32], 2006),
            new Tretja.Nocitev(osebe[18], cilji[26], 2014),
            new Tretja.Nocitev(osebe[5], cilji[12], 2016),
            new Tretja.Nocitev(osebe[19], cilji[10], 2016),
            new Tretja.Nocitev(osebe[5], cilji[12], 2020),
            new Tretja.Nocitev(osebe[8], cilji[24], 2009),
            new Tretja.Nocitev(osebe[9], cilji[34], 2000),
            new Tretja.Nocitev(osebe[16], cilji[15], 2014),
            new Tretja.Nocitev(osebe[13], cilji[4], 2011),
            new Tretja.Nocitev(osebe[12], cilji[25], 2007),
            new Tretja.Nocitev(osebe[15], cilji[33], 2003),
            new Tretja.Nocitev(osebe[16], cilji[15], 2004),
            new Tretja.Nocitev(osebe[12], cilji[10], 2000),
            new Tretja.Nocitev(osebe[2], cilji[9], 2011),
            new Tretja.Nocitev(osebe[0], cilji[10], 2016),
            new Tretja.Nocitev(osebe[8], cilji[24], 2020),
            new Tretja.Nocitev(osebe[5], cilji[12], 2009),
            new Tretja.Nocitev(osebe[11], cilji[8], 2001),
            new Tretja.Nocitev(osebe[2], cilji[9], 2020),
            new Tretja.Nocitev(osebe[20], cilji[22], 2008),
            new Tretja.Nocitev(osebe[13], cilji[4], 2018),
            new Tretja.Nocitev(osebe[6], cilji[34], 2001),
            new Tretja.Nocitev(osebe[8], cilji[24], 2017),
            new Tretja.Nocitev(osebe[20], cilji[35], 2003),
            new Tretja.Nocitev(osebe[10], cilji[34], 2001),
            new Tretja.Nocitev(osebe[11], cilji[16], 2015),
            new Tretja.Nocitev(osebe[0], cilji[31], 2004),
            new Tretja.Nocitev(osebe[2], cilji[9], 2013),
            new Tretja.Nocitev(osebe[12], cilji[17], 2001),
            new Tretja.Nocitev(osebe[6], cilji[33], 2007),
            new Tretja.Nocitev(osebe[4], cilji[8], 2003),
            new Tretja.Nocitev(osebe[13], cilji[4], 2008),
            new Tretja.Nocitev(osebe[14], cilji[20], 2015),
            new Tretja.Nocitev(osebe[14], cilji[26], 2003),
            new Tretja.Nocitev(osebe[3], cilji[1], 2004),
            new Tretja.Nocitev(osebe[20], cilji[1], 2014),
            new Tretja.Nocitev(osebe[6], cilji[31], 2009),
            new Tretja.Nocitev(osebe[2], cilji[9], 2013),
            new Tretja.Nocitev(osebe[3], cilji[1], 2008),
            new Tretja.Nocitev(osebe[3], cilji[1], 2002),
            new Tretja.Nocitev(osebe[1], cilji[7], 2000),
            new Tretja.Nocitev(osebe[6], cilji[20], 2019),
            new Tretja.Nocitev(osebe[16], cilji[15], 2001),
            new Tretja.Nocitev(osebe[20], cilji[0], 2011),
            new Tretja.Nocitev(osebe[7], cilji[33], 2008),
            new Tretja.Nocitev(osebe[5], cilji[12], 2002),
            new Tretja.Nocitev(osebe[11], cilji[14], 2016),
            new Tretja.Nocitev(osebe[11], cilji[30], 2000),
            new Tretja.Nocitev(osebe[18], cilji[26], 2019),
            new Tretja.Nocitev(osebe[8], cilji[24], 2016),
            new Tretja.Nocitev(osebe[13], cilji[4], 2009),
            new Tretja.Nocitev(osebe[4], cilji[22], 2008),
            new Tretja.Nocitev(osebe[15], cilji[27], 2008),
            new Tretja.Nocitev(osebe[12], cilji[12], 2011),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2001, 2012);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
