
public class Test38 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Jyeb Nsft", "Fxuz"),
            new Tretja.Oseba("Sqjd Jdqs", "Fxuz"),
            new Tretja.Oseba("Pdlo Fafq", "Fxuz"),
            new Tretja.Oseba("Qwtt Sxca", "Inhd"),
            new Tretja.Oseba("Pitt Nyvh", "Inhd"),
            new Tretja.Oseba("Sws Rzym", "Ejav"),
            new Tretja.Oseba("Ybcn Nzar", "Ejav"),
            new Tretja.Oseba("Tols Laeg", "Inhd"),
            new Tretja.Oseba("Kbl Fevs", "Fxuz"),
            new Tretja.Oseba("Dsze Sizy", "Inhd"),
            new Tretja.Oseba("Gmdo Svhu", "Inhd"),
            new Tretja.Oseba("Nypg Ejsb", "Siae"),
            new Tretja.Oseba("Sdyb Tvyx", "Ejav"),
            new Tretja.Oseba("Vieb Bonc", "Inhd"),
            new Tretja.Oseba("Lrea Oshb", "Inhd"),
            new Tretja.Oseba("Euaq Bhve", "Inhd"),
            new Tretja.Oseba("Srro Uink", "Ejav"),
            new Tretja.Oseba("Fyji Qqw", "Inhd"),
            new Tretja.Oseba("Brhx Skvc", "Inhd"),
            new Tretja.Oseba("Bqfy Fovz", "Inhd"),
            new Tretja.Oseba("Ujep Ydph", "Inhd"),
            new Tretja.Oseba("Wvcm Djqj", "Inhd"),
            new Tretja.Oseba("Qegm Mztx", "Fxuz"),
            new Tretja.Oseba("Mnzq Lqrb", "Inhd"),
            new Tretja.Oseba("Qyzx Nzgr", "Ejav"),
            new Tretja.Oseba("Avbi Nzkc", "Fxuz"),
            new Tretja.Oseba("Igat Prho", "Fxuz"),
            new Tretja.Oseba("Abmo Ohmt", "Inhd"),
            new Tretja.Oseba("Iwfl Zked", "Siae"),
            new Tretja.Oseba("Qkus Dqso", "Siae"),
            new Tretja.Oseba("Ngbg Upfq", "Siae"),
            new Tretja.Oseba("Fhbk Mnp", "Ejav"),
            new Tretja.Oseba("Try Wsjq", "Fxuz"),
            new Tretja.Oseba("Eomx Fmad", "Ejav"),
            new Tretja.Oseba("Efrp Bwoc", "Inhd"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Qoiz", "Ejav"),
            new Tretja.Cilj("Mlya", "Ejav"),
            new Tretja.Cilj("Nera", "Fxuz"),
            new Tretja.Cilj("Mtk", "Ejav"),
            new Tretja.Cilj("Gmtq", "Fxuz"),
            new Tretja.Cilj("Wypo", "Siae"),
            new Tretja.Cilj("Uqly", "Ejav"),
            new Tretja.Cilj("Zyc", "Ejav"),
            new Tretja.Cilj("Gcwz", "Fxuz"),
            new Tretja.Cilj("Hwvn", "Fxuz"),
            new Tretja.Cilj("Lpj", "Inhd"),
            new Tretja.Cilj("Lldj", "Fxuz"),
            new Tretja.Cilj("Mkxe", "Ejav"),
            new Tretja.Cilj("Vezq", "Ejav"),
            new Tretja.Cilj("Spmr", "Fxuz"),
            new Tretja.Cilj("Zbrf", "Inhd"),
            new Tretja.Cilj("Yxrb", "Ejav"),
            new Tretja.Cilj("Ujax", "Siae"),
            new Tretja.Cilj("Qker", "Siae"),
            new Tretja.Cilj("Geuw", "Siae"),
            new Tretja.Cilj("Mqjq", "Fxuz"),
            new Tretja.Cilj("Fxup", "Siae"),
            new Tretja.Cilj("Vshh", "Ejav"),
            new Tretja.Cilj("Wfpw", "Fxuz"),
            new Tretja.Cilj("Gdxb", "Inhd"),
            new Tretja.Cilj("Ckxd", "Inhd"),
            new Tretja.Cilj("Qxxg", "Inhd"),
            new Tretja.Cilj("Rkil", "Fxuz"),
            new Tretja.Cilj("Ywrl", "Siae"),
            new Tretja.Cilj("Mxrl", "Ejav"),
            new Tretja.Cilj("Birw", "Fxuz"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[15], cilji[15], 2009),
            new Tretja.Nocitev(osebe[8], cilji[30], 2020),
            new Tretja.Nocitev(osebe[12], cilji[16], 2001),
            new Tretja.Nocitev(osebe[29], cilji[15], 2008),
            new Tretja.Nocitev(osebe[5], cilji[6], 2005),
            new Tretja.Nocitev(osebe[2], cilji[9], 2019),
            new Tretja.Nocitev(osebe[10], cilji[14], 2009),
            new Tretja.Nocitev(osebe[3], cilji[10], 2007),
            new Tretja.Nocitev(osebe[6], cilji[6], 2010),
            new Tretja.Nocitev(osebe[5], cilji[6], 2005),
            new Tretja.Nocitev(osebe[33], cilji[14], 2016),
            new Tretja.Nocitev(osebe[7], cilji[11], 2017),
            new Tretja.Nocitev(osebe[10], cilji[10], 2015),
            new Tretja.Nocitev(osebe[28], cilji[26], 2020),
            new Tretja.Nocitev(osebe[22], cilji[5], 2011),
            new Tretja.Nocitev(osebe[31], cilji[4], 2000),
            new Tretja.Nocitev(osebe[8], cilji[30], 2006),
            new Tretja.Nocitev(osebe[31], cilji[4], 2011),
            new Tretja.Nocitev(osebe[12], cilji[16], 2010),
            new Tretja.Nocitev(osebe[2], cilji[3], 2018),
            new Tretja.Nocitev(osebe[24], cilji[8], 2004),
            new Tretja.Nocitev(osebe[31], cilji[4], 2004),
            new Tretja.Nocitev(osebe[25], cilji[10], 2011),
            new Tretja.Nocitev(osebe[15], cilji[15], 2019),
            new Tretja.Nocitev(osebe[4], cilji[29], 2011),
            new Tretja.Nocitev(osebe[32], cilji[17], 2014),
            new Tretja.Nocitev(osebe[24], cilji[24], 2002),
            new Tretja.Nocitev(osebe[10], cilji[15], 2004),
            new Tretja.Nocitev(osebe[19], cilji[11], 2018),
            new Tretja.Nocitev(osebe[22], cilji[17], 2005),
            new Tretja.Nocitev(osebe[8], cilji[30], 2013),
            new Tretja.Nocitev(osebe[12], cilji[16], 2017),
            new Tretja.Nocitev(osebe[25], cilji[10], 2020),
            new Tretja.Nocitev(osebe[34], cilji[7], 2009),
            new Tretja.Nocitev(osebe[26], cilji[1], 2012),
            new Tretja.Nocitev(osebe[34], cilji[7], 2001),
            new Tretja.Nocitev(osebe[15], cilji[15], 2010),
            new Tretja.Nocitev(osebe[10], cilji[17], 2013),
            new Tretja.Nocitev(osebe[17], cilji[5], 2012),
            new Tretja.Nocitev(osebe[29], cilji[15], 2001),
            new Tretja.Nocitev(osebe[19], cilji[29], 2009),
            new Tretja.Nocitev(osebe[30], cilji[19], 2017),
            new Tretja.Nocitev(osebe[16], cilji[26], 2005),
            new Tretja.Nocitev(osebe[9], cilji[8], 2020),
            new Tretja.Nocitev(osebe[24], cilji[5], 2002),
            new Tretja.Nocitev(osebe[18], cilji[4], 2004),
            new Tretja.Nocitev(osebe[30], cilji[20], 2008),
            new Tretja.Nocitev(osebe[29], cilji[15], 2018),
            new Tretja.Nocitev(osebe[18], cilji[2], 2001),
            new Tretja.Nocitev(osebe[28], cilji[1], 2008),
            new Tretja.Nocitev(osebe[6], cilji[5], 2011),
            new Tretja.Nocitev(osebe[4], cilji[16], 2018),
            new Tretja.Nocitev(osebe[15], cilji[15], 2020),
            new Tretja.Nocitev(osebe[20], cilji[0], 2003),
            new Tretja.Nocitev(osebe[10], cilji[29], 2016),
            new Tretja.Nocitev(osebe[0], cilji[28], 2020),
            new Tretja.Nocitev(osebe[15], cilji[15], 2016),
            new Tretja.Nocitev(osebe[9], cilji[17], 2007),
            new Tretja.Nocitev(osebe[17], cilji[5], 2018),
            new Tretja.Nocitev(osebe[33], cilji[14], 2019),
            new Tretja.Nocitev(osebe[9], cilji[28], 2000),
            new Tretja.Nocitev(osebe[27], cilji[16], 2007),
            new Tretja.Nocitev(osebe[27], cilji[5], 2000),
            new Tretja.Nocitev(osebe[26], cilji[1], 2001),
            new Tretja.Nocitev(osebe[27], cilji[9], 2004),
            new Tretja.Nocitev(osebe[13], cilji[26], 2004),
            new Tretja.Nocitev(osebe[21], cilji[0], 2000),
            new Tretja.Nocitev(osebe[34], cilji[7], 2003),
            new Tretja.Nocitev(osebe[14], cilji[29], 2003),
            new Tretja.Nocitev(osebe[29], cilji[15], 2018),
            new Tretja.Nocitev(osebe[17], cilji[5], 2017),
            new Tretja.Nocitev(osebe[9], cilji[27], 2019),
            new Tretja.Nocitev(osebe[22], cilji[6], 2004),
            new Tretja.Nocitev(osebe[32], cilji[17], 2008),
            new Tretja.Nocitev(osebe[2], cilji[26], 2019),
            new Tretja.Nocitev(osebe[25], cilji[10], 2008),
            new Tretja.Nocitev(osebe[3], cilji[10], 2020),
            new Tretja.Nocitev(osebe[19], cilji[24], 2001),
            new Tretja.Nocitev(osebe[20], cilji[0], 2015),
            new Tretja.Nocitev(osebe[21], cilji[2], 2013),
            new Tretja.Nocitev(osebe[20], cilji[0], 2004),
            new Tretja.Nocitev(osebe[21], cilji[28], 2015),
            new Tretja.Nocitev(osebe[4], cilji[24], 2004),
            new Tretja.Nocitev(osebe[1], cilji[19], 2001),
            new Tretja.Nocitev(osebe[32], cilji[17], 2019),
            new Tretja.Nocitev(osebe[9], cilji[10], 2009),
            new Tretja.Nocitev(osebe[2], cilji[20], 2009),
            new Tretja.Nocitev(osebe[14], cilji[19], 2015),
            new Tretja.Nocitev(osebe[29], cilji[15], 2011),
            new Tretja.Nocitev(osebe[7], cilji[11], 2001),
            new Tretja.Nocitev(osebe[18], cilji[0], 2003),
            new Tretja.Nocitev(osebe[24], cilji[24], 2007),
            new Tretja.Nocitev(osebe[32], cilji[17], 2002),
            new Tretja.Nocitev(osebe[9], cilji[19], 2005),
            new Tretja.Nocitev(osebe[23], cilji[16], 2012),
            new Tretja.Nocitev(osebe[17], cilji[5], 2018),
            new Tretja.Nocitev(osebe[13], cilji[30], 2009),
            new Tretja.Nocitev(osebe[1], cilji[4], 2016),
            new Tretja.Nocitev(osebe[3], cilji[10], 2007),
            new Tretja.Nocitev(osebe[20], cilji[0], 2010),
            new Tretja.Nocitev(osebe[20], cilji[0], 2002),
            new Tretja.Nocitev(osebe[10], cilji[26], 2014),
            new Tretja.Nocitev(osebe[16], cilji[26], 2012),
            new Tretja.Nocitev(osebe[18], cilji[9], 2016),
            new Tretja.Nocitev(osebe[19], cilji[22], 2018),
            new Tretja.Nocitev(osebe[8], cilji[30], 2015),
            new Tretja.Nocitev(osebe[32], cilji[17], 2000),
            new Tretja.Nocitev(osebe[12], cilji[16], 2016),
            new Tretja.Nocitev(osebe[13], cilji[4], 2000),
            new Tretja.Nocitev(osebe[6], cilji[23], 2017),
            new Tretja.Nocitev(osebe[32], cilji[17], 2006),
            new Tretja.Nocitev(osebe[19], cilji[28], 2005),
            new Tretja.Nocitev(osebe[8], cilji[30], 2000),
            new Tretja.Nocitev(osebe[8], cilji[30], 2017),
            new Tretja.Nocitev(osebe[7], cilji[11], 2018),
            new Tretja.Nocitev(osebe[21], cilji[9], 2014),
            new Tretja.Nocitev(osebe[9], cilji[9], 2004),
            new Tretja.Nocitev(osebe[13], cilji[26], 2011),
            new Tretja.Nocitev(osebe[14], cilji[14], 2007),
            new Tretja.Nocitev(osebe[11], cilji[21], 2008),
            new Tretja.Nocitev(osebe[31], cilji[4], 2008),
            new Tretja.Nocitev(osebe[31], cilji[4], 2002),
            new Tretja.Nocitev(osebe[0], cilji[16], 2020),
            new Tretja.Nocitev(osebe[32], cilji[17], 2009),
            new Tretja.Nocitev(osebe[20], cilji[0], 2000),
            new Tretja.Nocitev(osebe[23], cilji[23], 2011),
            new Tretja.Nocitev(osebe[21], cilji[24], 2002),
            new Tretja.Nocitev(osebe[1], cilji[4], 2010),
            new Tretja.Nocitev(osebe[28], cilji[18], 2013),
            new Tretja.Nocitev(osebe[33], cilji[14], 2007),
            new Tretja.Nocitev(osebe[21], cilji[15], 2000),
            new Tretja.Nocitev(osebe[28], cilji[11], 2002),
            new Tretja.Nocitev(osebe[25], cilji[10], 2004),
            new Tretja.Nocitev(osebe[12], cilji[16], 2007),
            new Tretja.Nocitev(osebe[33], cilji[14], 2016),
            new Tretja.Nocitev(osebe[27], cilji[3], 2016),
            new Tretja.Nocitev(osebe[33], cilji[14], 2018),
            new Tretja.Nocitev(osebe[10], cilji[27], 2005),
            new Tretja.Nocitev(osebe[33], cilji[14], 2009),
            new Tretja.Nocitev(osebe[34], cilji[7], 2004),
            new Tretja.Nocitev(osebe[18], cilji[14], 2001),
            new Tretja.Nocitev(osebe[1], cilji[18], 2003),
            new Tretja.Nocitev(osebe[31], cilji[4], 2019),
            new Tretja.Nocitev(osebe[25], cilji[10], 2017),
            new Tretja.Nocitev(osebe[31], cilji[4], 2014),
            new Tretja.Nocitev(osebe[8], cilji[30], 2011),
            new Tretja.Nocitev(osebe[9], cilji[22], 2003),
            new Tretja.Nocitev(osebe[22], cilji[19], 2012),
            new Tretja.Nocitev(osebe[0], cilji[21], 2002),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2000, 2011);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
