
public class Test35 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Pcwv Wkny", "Tbwv"),
            new Tretja.Oseba("Xsoj Lfll", "Rtpm"),
            new Tretja.Oseba("Kbvg Ujyb", "Rtpm"),
            new Tretja.Oseba("Hixn Zaum", "Tbwv"),
            new Tretja.Oseba("Cezq Ygvj", "Mewk"),
            new Tretja.Oseba("Zhur Kas", "Rtpm"),
            new Tretja.Oseba("Pbun Yzip", "Mkjo"),
            new Tretja.Oseba("Bpln Vlkp", "Rtpm"),
            new Tretja.Oseba("Waoj Rvjf", "Rtpm"),
            new Tretja.Oseba("Cfpf Ngqh", "Tbwv"),
            new Tretja.Oseba("Jrus Sisf", "Rtpm"),
            new Tretja.Oseba("Oocp Voye", "Mkjo"),
            new Tretja.Oseba("Mvmk Nges", "Mewk"),
            new Tretja.Oseba("Psca Dghq", "Mkjo"),
            new Tretja.Oseba("Sdsu Ztvw", "Xhyz"),
            new Tretja.Oseba("Ldmm Vltp", "Rtpm"),
            new Tretja.Oseba("Chyx Hbes", "Rtpm"),
            new Tretja.Oseba("Jsvj Utzu", "Mkjo"),
            new Tretja.Oseba("Gwwo Xuvb", "Rtpm"),
            new Tretja.Oseba("Wohj Svov", "Rtpm"),
            new Tretja.Oseba("Wem Ahac", "Rtpm"),
            new Tretja.Oseba("Zyai Zonz", "Rtpm"),
            new Tretja.Oseba("Afrw Nlkg", "Mewk"),
            new Tretja.Oseba("Ucyv Anhg", "Mewk"),
            new Tretja.Oseba("Rk Dvdi", "Mkjo"),
            new Tretja.Oseba("Fcif Worn", "Mewk"),
            new Tretja.Oseba("Voyf Hauo", "Mkjo"),
            new Tretja.Oseba("Hkss Nopc", "Tbwv"),
            new Tretja.Oseba("Orma Qppz", "Mkjo"),
            new Tretja.Oseba("Qdoe Hciw", "Rtpm"),
            new Tretja.Oseba("Sucs Qtly", "Mewk"),
            new Tretja.Oseba("Rzrg Ffic", "Tbwv"),
            new Tretja.Oseba("Kvmg Pfrj", "Mkjo"),
            new Tretja.Oseba("Aaul Wsxc", "Mkjo"),
            new Tretja.Oseba("Nxud Pwpj", "Rtpm"),
            new Tretja.Oseba("Szdc Zwii", "Tbwv"),
            new Tretja.Oseba("Snqh Ixrh", "Mkjo"),
            new Tretja.Oseba("Ghva Snwu", "Rtpm"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Ywrf", "Mewk"),
            new Tretja.Cilj("Gciw", "Mewk"),
            new Tretja.Cilj("Imhc", "Rtpm"),
            new Tretja.Cilj("Xuin", "Mewk"),
            new Tretja.Cilj("Nadt", "Rtpm"),
            new Tretja.Cilj("Dbrd", "Mewk"),
            new Tretja.Cilj("Keeg", "Xhyz"),
            new Tretja.Cilj("Mrfo", "Xhyz"),
            new Tretja.Cilj("Mmym", "Xhyz"),
            new Tretja.Cilj("Jqjo", "Rtpm"),
            new Tretja.Cilj("Yjxn", "Tbwv"),
            new Tretja.Cilj("Mzfg", "Xhyz"),
            new Tretja.Cilj("Sfrq", "Mkjo"),
            new Tretja.Cilj("Wnmu", "Rtpm"),
            new Tretja.Cilj("Flcw", "Rtpm"),
            new Tretja.Cilj("Ofur", "Xhyz"),
            new Tretja.Cilj("Dtcp", "Xhyz"),
            new Tretja.Cilj("Ggce", "Mkjo"),
            new Tretja.Cilj("Gfja", "Xhyz"),
            new Tretja.Cilj("Aak", "Tbwv"),
            new Tretja.Cilj("Yjre", "Mewk"),
            new Tretja.Cilj("Uqid", "Mewk"),
            new Tretja.Cilj("Mdmq", "Rtpm"),
            new Tretja.Cilj("Obhu", "Rtpm"),
            new Tretja.Cilj("Kcrv", "Mkjo"),
            new Tretja.Cilj("Prnh", "Mkjo"),
            new Tretja.Cilj("Obvu", "Xhyz"),
            new Tretja.Cilj("Revj", "Xhyz"),
            new Tretja.Cilj("Wgan", "Mkjo"),
            new Tretja.Cilj("Lumu", "Tbwv"),
            new Tretja.Cilj("Nxrj", "Mewk"),
            new Tretja.Cilj("Ofrf", "Mkjo"),
            new Tretja.Cilj("Vvjs", "Mkjo"),
            new Tretja.Cilj("Rdjs", "Mewk"),
            new Tretja.Cilj("Zsot", "Tbwv"),
            new Tretja.Cilj("Glnb", "Xhyz"),
            new Tretja.Cilj("Gujb", "Mewk"),
            new Tretja.Cilj("Ognb", "Rtpm"),
            new Tretja.Cilj("Obca", "Mewk"),
            new Tretja.Cilj("Nmnz", "Xhyz"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[5], cilji[6], 2011),
            new Tretja.Nocitev(osebe[30], cilji[34], 2019),
            new Tretja.Nocitev(osebe[24], cilji[32], 2002),
            new Tretja.Nocitev(osebe[35], cilji[12], 2017),
            new Tretja.Nocitev(osebe[8], cilji[19], 2016),
            new Tretja.Nocitev(osebe[21], cilji[3], 2007),
            new Tretja.Nocitev(osebe[17], cilji[8], 2011),
            new Tretja.Nocitev(osebe[16], cilji[29], 2012),
            new Tretja.Nocitev(osebe[3], cilji[9], 2014),
            new Tretja.Nocitev(osebe[34], cilji[29], 2011),
            new Tretja.Nocitev(osebe[5], cilji[2], 2007),
            new Tretja.Nocitev(osebe[24], cilji[32], 2017),
            new Tretja.Nocitev(osebe[15], cilji[38], 2010),
            new Tretja.Nocitev(osebe[21], cilji[3], 2007),
            new Tretja.Nocitev(osebe[20], cilji[1], 2015),
            new Tretja.Nocitev(osebe[20], cilji[1], 2009),
            new Tretja.Nocitev(osebe[8], cilji[19], 2006),
            new Tretja.Nocitev(osebe[30], cilji[34], 2004),
            new Tretja.Nocitev(osebe[1], cilji[4], 2009),
            new Tretja.Nocitev(osebe[27], cilji[0], 2002),
            new Tretja.Nocitev(osebe[21], cilji[3], 2006),
            new Tretja.Nocitev(osebe[25], cilji[29], 2015),
            new Tretja.Nocitev(osebe[1], cilji[4], 2016),
            new Tretja.Nocitev(osebe[27], cilji[31], 2008),
            new Tretja.Nocitev(osebe[2], cilji[0], 2019),
            new Tretja.Nocitev(osebe[20], cilji[6], 2005),
            new Tretja.Nocitev(osebe[11], cilji[8], 2009),
            new Tretja.Nocitev(osebe[13], cilji[22], 2004),
            new Tretja.Nocitev(osebe[26], cilji[11], 2013),
            new Tretja.Nocitev(osebe[8], cilji[19], 2001),
            new Tretja.Nocitev(osebe[12], cilji[25], 2009),
            new Tretja.Nocitev(osebe[35], cilji[5], 2000),
            new Tretja.Nocitev(osebe[36], cilji[32], 2009),
            new Tretja.Nocitev(osebe[10], cilji[27], 2019),
            new Tretja.Nocitev(osebe[15], cilji[31], 2004),
            new Tretja.Nocitev(osebe[27], cilji[2], 2015),
            new Tretja.Nocitev(osebe[30], cilji[34], 2017),
            new Tretja.Nocitev(osebe[9], cilji[3], 2009),
            new Tretja.Nocitev(osebe[37], cilji[10], 2016),
            new Tretja.Nocitev(osebe[6], cilji[15], 2001),
            new Tretja.Nocitev(osebe[22], cilji[1], 2014),
            new Tretja.Nocitev(osebe[24], cilji[32], 2019),
            new Tretja.Nocitev(osebe[18], cilji[10], 2008),
            new Tretja.Nocitev(osebe[36], cilji[32], 2002),
            new Tretja.Nocitev(osebe[27], cilji[36], 2002),
            new Tretja.Nocitev(osebe[28], cilji[32], 2012),
            new Tretja.Nocitev(osebe[8], cilji[19], 2009),
            new Tretja.Nocitev(osebe[30], cilji[34], 2005),
            new Tretja.Nocitev(osebe[10], cilji[28], 2010),
            new Tretja.Nocitev(osebe[2], cilji[13], 2010),
            new Tretja.Nocitev(osebe[10], cilji[24], 2016),
            new Tretja.Nocitev(osebe[24], cilji[32], 2006),
            new Tretja.Nocitev(osebe[16], cilji[29], 2012),
            new Tretja.Nocitev(osebe[3], cilji[9], 2016),
            new Tretja.Nocitev(osebe[26], cilji[9], 2004),
            new Tretja.Nocitev(osebe[16], cilji[29], 2013),
            new Tretja.Nocitev(osebe[21], cilji[3], 2001),
            new Tretja.Nocitev(osebe[31], cilji[17], 2006),
            new Tretja.Nocitev(osebe[15], cilji[20], 2011),
            new Tretja.Nocitev(osebe[22], cilji[27], 2019),
            new Tretja.Nocitev(osebe[5], cilji[31], 2002),
            new Tretja.Nocitev(osebe[25], cilji[29], 2005),
            new Tretja.Nocitev(osebe[13], cilji[33], 2014),
            new Tretja.Nocitev(osebe[1], cilji[4], 2015),
            new Tretja.Nocitev(osebe[18], cilji[10], 2016),
            new Tretja.Nocitev(osebe[2], cilji[39], 2014),
            new Tretja.Nocitev(osebe[23], cilji[20], 2006),
            new Tretja.Nocitev(osebe[5], cilji[37], 2009),
            new Tretja.Nocitev(osebe[34], cilji[20], 2015),
            new Tretja.Nocitev(osebe[22], cilji[0], 2003),
            new Tretja.Nocitev(osebe[7], cilji[39], 2002),
            new Tretja.Nocitev(osebe[31], cilji[17], 2016),
            new Tretja.Nocitev(osebe[19], cilji[30], 2008),
            new Tretja.Nocitev(osebe[25], cilji[29], 2013),
            new Tretja.Nocitev(osebe[19], cilji[28], 2009),
            new Tretja.Nocitev(osebe[8], cilji[19], 2010),
            new Tretja.Nocitev(osebe[8], cilji[19], 2009),
            new Tretja.Nocitev(osebe[21], cilji[3], 2008),
            new Tretja.Nocitev(osebe[21], cilji[3], 2008),
            new Tretja.Nocitev(osebe[14], cilji[27], 2019),
            new Tretja.Nocitev(osebe[1], cilji[4], 2001),
            new Tretja.Nocitev(osebe[2], cilji[19], 2011),
            new Tretja.Nocitev(osebe[22], cilji[12], 2012),
            new Tretja.Nocitev(osebe[6], cilji[15], 2012),
            new Tretja.Nocitev(osebe[16], cilji[29], 2004),
            new Tretja.Nocitev(osebe[33], cilji[39], 2015),
            new Tretja.Nocitev(osebe[12], cilji[33], 2003),
            new Tretja.Nocitev(osebe[17], cilji[8], 2010),
            new Tretja.Nocitev(osebe[27], cilji[8], 2020),
            new Tretja.Nocitev(osebe[5], cilji[17], 2018),
            new Tretja.Nocitev(osebe[29], cilji[33], 2012),
            new Tretja.Nocitev(osebe[35], cilji[38], 2013),
            new Tretja.Nocitev(osebe[26], cilji[23], 2005),
            new Tretja.Nocitev(osebe[14], cilji[29], 2008),
            new Tretja.Nocitev(osebe[5], cilji[15], 2000),
            new Tretja.Nocitev(osebe[21], cilji[3], 2020),
            new Tretja.Nocitev(osebe[1], cilji[4], 2011),
            new Tretja.Nocitev(osebe[30], cilji[34], 2000),
            new Tretja.Nocitev(osebe[29], cilji[33], 2009),
            new Tretja.Nocitev(osebe[26], cilji[18], 2003),
            new Tretja.Nocitev(osebe[6], cilji[15], 2014),
            new Tretja.Nocitev(osebe[25], cilji[29], 2012),
            new Tretja.Nocitev(osebe[0], cilji[35], 2001),
            new Tretja.Nocitev(osebe[17], cilji[8], 2004),
            new Tretja.Nocitev(osebe[2], cilji[24], 2005),
            new Tretja.Nocitev(osebe[35], cilji[31], 2012),
            new Tretja.Nocitev(osebe[21], cilji[3], 2011),
            new Tretja.Nocitev(osebe[22], cilji[31], 2009),
            new Tretja.Nocitev(osebe[1], cilji[4], 2004),
            new Tretja.Nocitev(osebe[32], cilji[12], 2004),
            new Tretja.Nocitev(osebe[24], cilji[32], 2009),
            new Tretja.Nocitev(osebe[15], cilji[4], 2009),
            new Tretja.Nocitev(osebe[30], cilji[34], 2008),
            new Tretja.Nocitev(osebe[0], cilji[35], 2005),
            new Tretja.Nocitev(osebe[33], cilji[39], 2011),
            new Tretja.Nocitev(osebe[16], cilji[29], 2009),
            new Tretja.Nocitev(osebe[25], cilji[29], 2005),
            new Tretja.Nocitev(osebe[17], cilji[8], 2000),
            new Tretja.Nocitev(osebe[25], cilji[29], 2014),
            new Tretja.Nocitev(osebe[30], cilji[34], 2019),
            new Tretja.Nocitev(osebe[11], cilji[0], 2019),
            new Tretja.Nocitev(osebe[0], cilji[35], 2020),
            new Tretja.Nocitev(osebe[25], cilji[29], 2018),
            new Tretja.Nocitev(osebe[7], cilji[34], 2008),
            new Tretja.Nocitev(osebe[22], cilji[7], 2016),
            new Tretja.Nocitev(osebe[15], cilji[37], 2019),
            new Tretja.Nocitev(osebe[35], cilji[1], 2014),
            new Tretja.Nocitev(osebe[25], cilji[29], 2018),
            new Tretja.Nocitev(osebe[4], cilji[10], 2001),
            new Tretja.Nocitev(osebe[23], cilji[20], 2010),
            new Tretja.Nocitev(osebe[23], cilji[20], 2002),
            new Tretja.Nocitev(osebe[36], cilji[32], 2012),
            new Tretja.Nocitev(osebe[12], cilji[18], 2003),
            new Tretja.Nocitev(osebe[15], cilji[21], 2001),
            new Tretja.Nocitev(osebe[14], cilji[18], 2013),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2007, 2008);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
