
public class Test04 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Cary Hrih", "Ljqk"),
            new Tretja.Oseba("Cnpw Gzxu", "Wimo"),
            new Tretja.Oseba("Lcnv Onic", "Ftrr"),
            new Tretja.Oseba("Ybeo Ztgn", "Wimo"),
            new Tretja.Oseba("Kqim Mdmb", "Ftrr"),
            new Tretja.Oseba("Uctr Clse", "Ftrr"),
            new Tretja.Oseba("Uadb Iqk", "Ljqk"),
            new Tretja.Oseba("Rcvu Fyoa", "Wimo"),
            new Tretja.Oseba("Ddat Airk", "Ftrr"),
            new Tretja.Oseba("Igsr Delv", "Ljqk"),
            new Tretja.Oseba("Rdgp Evdl", "Ljqk"),
            new Tretja.Oseba("Azcn Laoa", "Ljqk"),
            new Tretja.Oseba("Aqra Zvbx", "Ljqk"),
            new Tretja.Oseba("Oqxm Irqs", "Ljqk"),
            new Tretja.Oseba("Wwar Nkez", "Wimo"),
            new Tretja.Oseba("Ldbk Agtz", "Ljqk"),
            new Tretja.Oseba("Fzth Ewlr", "Ljqk"),
            new Tretja.Oseba("Skjm Uljp", "Ftrr"),
            new Tretja.Oseba("Dlhw Dlrk", "Ftrr"),
            new Tretja.Oseba("Uixb Csrn", "Ftrr"),
            new Tretja.Oseba("Nuqh Kzi", "Ftrr"),
            new Tretja.Oseba("Fmjp Blqi", "Ljqk"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Dvxq", "Ljqk"),
            new Tretja.Cilj("Atme", "Ftrr"),
            new Tretja.Cilj("Dvgl", "Ftrr"),
            new Tretja.Cilj("Ehne", "Ftrr"),
            new Tretja.Cilj("Zoib", "Ftrr"),
            new Tretja.Cilj("Sjle", "Ljqk"),
            new Tretja.Cilj("Bgfl", "Ftrr"),
            new Tretja.Cilj("Mhse", "Ljqk"),
            new Tretja.Cilj("Lkmb", "Wimo"),
            new Tretja.Cilj("Qeqs", "Wimo"),
            new Tretja.Cilj("Xtod", "Wimo"),
            new Tretja.Cilj("Rvou", "Wimo"),
            new Tretja.Cilj("Cehn", "Ljqk"),
            new Tretja.Cilj("Nqgb", "Wimo"),
            new Tretja.Cilj("Yevh", "Ljqk"),
            new Tretja.Cilj("Rwgn", "Ftrr"),
            new Tretja.Cilj("Gbfg", "Ljqk"),
            new Tretja.Cilj("Egov", "Ftrr"),
            new Tretja.Cilj("Yzlt", "Ftrr"),
            new Tretja.Cilj("Gobf", "Wimo"),
            new Tretja.Cilj("Naqw", "Ljqk"),
            new Tretja.Cilj("Ptoa", "Ftrr"),
            new Tretja.Cilj("Cxfr", "Wimo"),
            new Tretja.Cilj("Wssa", "Ftrr"),
            new Tretja.Cilj("Zpdd", "Wimo"),
            new Tretja.Cilj("Lgyh", "Wimo"),
            new Tretja.Cilj("Efcd", "Ljqk"),
            new Tretja.Cilj("Dhcp", "Wimo"),
            new Tretja.Cilj("Teq", "Wimo"),
            new Tretja.Cilj("Fhqj", "Ljqk"),
            new Tretja.Cilj("Ervd", "Ljqk"),
            new Tretja.Cilj("Fzzz", "Ftrr"),
            new Tretja.Cilj("Vdza", "Ljqk"),
            new Tretja.Cilj("Hobc", "Wimo"),
            new Tretja.Cilj("Sofd", "Wimo"),
            new Tretja.Cilj("Xcax", "Wimo"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[9], cilji[31], 2012),
            new Tretja.Nocitev(osebe[9], cilji[31], 2020),
            new Tretja.Nocitev(osebe[19], cilji[29], 2009),
            new Tretja.Nocitev(osebe[11], cilji[23], 2002),
            new Tretja.Nocitev(osebe[5], cilji[0], 2007),
            new Tretja.Nocitev(osebe[18], cilji[20], 2000),
            new Tretja.Nocitev(osebe[18], cilji[30], 2005),
            new Tretja.Nocitev(osebe[11], cilji[23], 2003),
            new Tretja.Nocitev(osebe[0], cilji[22], 2005),
            new Tretja.Nocitev(osebe[1], cilji[0], 2004),
            new Tretja.Nocitev(osebe[11], cilji[23], 2011),
            new Tretja.Nocitev(osebe[20], cilji[20], 2007),
            new Tretja.Nocitev(osebe[5], cilji[0], 2015),
            new Tretja.Nocitev(osebe[15], cilji[16], 2016),
            new Tretja.Nocitev(osebe[2], cilji[4], 2009),
            new Tretja.Nocitev(osebe[2], cilji[4], 2002),
            new Tretja.Nocitev(osebe[6], cilji[25], 2006),
            new Tretja.Nocitev(osebe[1], cilji[0], 2007),
            new Tretja.Nocitev(osebe[3], cilji[14], 2017),
            new Tretja.Nocitev(osebe[8], cilji[25], 2014),
            new Tretja.Nocitev(osebe[9], cilji[31], 2017),
            new Tretja.Nocitev(osebe[0], cilji[18], 2011),
            new Tretja.Nocitev(osebe[17], cilji[22], 2019),
            new Tretja.Nocitev(osebe[18], cilji[8], 2008),
            new Tretja.Nocitev(osebe[16], cilji[6], 2016),
            new Tretja.Nocitev(osebe[6], cilji[25], 2000),
            new Tretja.Nocitev(osebe[6], cilji[25], 2008),
            new Tretja.Nocitev(osebe[16], cilji[6], 2014),
            new Tretja.Nocitev(osebe[6], cilji[25], 2001),
            new Tretja.Nocitev(osebe[19], cilji[3], 2020),
            new Tretja.Nocitev(osebe[3], cilji[0], 2013),
            new Tretja.Nocitev(osebe[8], cilji[6], 2017),
            new Tretja.Nocitev(osebe[12], cilji[1], 2009),
            new Tretja.Nocitev(osebe[13], cilji[19], 2005),
            new Tretja.Nocitev(osebe[9], cilji[31], 2008),
            new Tretja.Nocitev(osebe[13], cilji[12], 2004),
            new Tretja.Nocitev(osebe[21], cilji[13], 2018),
            new Tretja.Nocitev(osebe[10], cilji[0], 2008),
            new Tretja.Nocitev(osebe[0], cilji[30], 2002),
            new Tretja.Nocitev(osebe[16], cilji[6], 2010),
            new Tretja.Nocitev(osebe[1], cilji[0], 2016),
            new Tretja.Nocitev(osebe[20], cilji[26], 2000),
            new Tretja.Nocitev(osebe[21], cilji[13], 2008),
            new Tretja.Nocitev(osebe[7], cilji[7], 2006),
            new Tretja.Nocitev(osebe[12], cilji[1], 2020),
            new Tretja.Nocitev(osebe[3], cilji[7], 2019),
            new Tretja.Nocitev(osebe[6], cilji[25], 2013),
            new Tretja.Nocitev(osebe[6], cilji[25], 2015),
            new Tretja.Nocitev(osebe[4], cilji[5], 2006),
            new Tretja.Nocitev(osebe[14], cilji[25], 2010),
            new Tretja.Nocitev(osebe[4], cilji[5], 2001),
            new Tretja.Nocitev(osebe[19], cilji[8], 2015),
            new Tretja.Nocitev(osebe[4], cilji[5], 2009),
            new Tretja.Nocitev(osebe[8], cilji[27], 2000),
            new Tretja.Nocitev(osebe[6], cilji[25], 2014),
            new Tretja.Nocitev(osebe[10], cilji[16], 2013),
            new Tretja.Nocitev(osebe[1], cilji[0], 2008),
            new Tretja.Nocitev(osebe[6], cilji[25], 2005),
            new Tretja.Nocitev(osebe[21], cilji[13], 2012),
            new Tretja.Nocitev(osebe[16], cilji[6], 2018),
            new Tretja.Nocitev(osebe[16], cilji[6], 2017),
            new Tretja.Nocitev(osebe[17], cilji[28], 2011),
            new Tretja.Nocitev(osebe[11], cilji[23], 2014),
            new Tretja.Nocitev(osebe[11], cilji[23], 2017),
            new Tretja.Nocitev(osebe[3], cilji[20], 2006),
            new Tretja.Nocitev(osebe[5], cilji[0], 2019),
            new Tretja.Nocitev(osebe[2], cilji[4], 2000),
            new Tretja.Nocitev(osebe[19], cilji[25], 2001),
            new Tretja.Nocitev(osebe[0], cilji[19], 2014),
            new Tretja.Nocitev(osebe[20], cilji[33], 2016),
            new Tretja.Nocitev(osebe[0], cilji[18], 2011),
            new Tretja.Nocitev(osebe[7], cilji[24], 2011),
            new Tretja.Nocitev(osebe[1], cilji[0], 2015),
            new Tretja.Nocitev(osebe[11], cilji[23], 2009),
            new Tretja.Nocitev(osebe[1], cilji[0], 2000),
            new Tretja.Nocitev(osebe[2], cilji[4], 2005),
            new Tretja.Nocitev(osebe[5], cilji[0], 2017),
            new Tretja.Nocitev(osebe[15], cilji[16], 2001),
            new Tretja.Nocitev(osebe[6], cilji[25], 2009),
            new Tretja.Nocitev(osebe[21], cilji[13], 2010),
            new Tretja.Nocitev(osebe[17], cilji[26], 2008),
            new Tretja.Nocitev(osebe[19], cilji[32], 2014),
            new Tretja.Nocitev(osebe[21], cilji[13], 2012),
            new Tretja.Nocitev(osebe[13], cilji[5], 2006),
            new Tretja.Nocitev(osebe[14], cilji[2], 2011),
            new Tretja.Nocitev(osebe[2], cilji[4], 2011),
            new Tretja.Nocitev(osebe[11], cilji[23], 2004),
            new Tretja.Nocitev(osebe[3], cilji[11], 2011),
            new Tretja.Nocitev(osebe[8], cilji[27], 2000),
            new Tretja.Nocitev(osebe[12], cilji[1], 2010),
            new Tretja.Nocitev(osebe[21], cilji[13], 2016),
            new Tretja.Nocitev(osebe[3], cilji[5], 2009),
            new Tretja.Nocitev(osebe[13], cilji[2], 2014),
            new Tretja.Nocitev(osebe[10], cilji[33], 2009),
            new Tretja.Nocitev(osebe[7], cilji[30], 2013),
            new Tretja.Nocitev(osebe[4], cilji[5], 2003),
            new Tretja.Nocitev(osebe[2], cilji[4], 2007),
            new Tretja.Nocitev(osebe[19], cilji[17], 2019),
            new Tretja.Nocitev(osebe[20], cilji[35], 2016),
            new Tretja.Nocitev(osebe[16], cilji[6], 2002),
            new Tretja.Nocitev(osebe[9], cilji[31], 2011),
            new Tretja.Nocitev(osebe[11], cilji[23], 2017),
            new Tretja.Nocitev(osebe[13], cilji[11], 2016),
            new Tretja.Nocitev(osebe[13], cilji[30], 2013),
            new Tretja.Nocitev(osebe[4], cilji[5], 2000),
            new Tretja.Nocitev(osebe[19], cilji[25], 2017),
            new Tretja.Nocitev(osebe[16], cilji[6], 2001),
            new Tretja.Nocitev(osebe[8], cilji[1], 2007),
            new Tretja.Nocitev(osebe[9], cilji[31], 2016),
            new Tretja.Nocitev(osebe[7], cilji[25], 2014),
            new Tretja.Nocitev(osebe[2], cilji[4], 2018),
            new Tretja.Nocitev(osebe[15], cilji[16], 2000),
            new Tretja.Nocitev(osebe[16], cilji[6], 2013),
            new Tretja.Nocitev(osebe[5], cilji[0], 2014),
            new Tretja.Nocitev(osebe[8], cilji[28], 2018),
            new Tretja.Nocitev(osebe[8], cilji[27], 2002),
            new Tretja.Nocitev(osebe[17], cilji[33], 2019),
            new Tretja.Nocitev(osebe[1], cilji[0], 2009),
            new Tretja.Nocitev(osebe[3], cilji[20], 2017),
            new Tretja.Nocitev(osebe[11], cilji[23], 2009),
            new Tretja.Nocitev(osebe[16], cilji[6], 2001),
            new Tretja.Nocitev(osebe[11], cilji[23], 2002),
            new Tretja.Nocitev(osebe[13], cilji[6], 2006),
            new Tretja.Nocitev(osebe[5], cilji[0], 2019),
            new Tretja.Nocitev(osebe[12], cilji[1], 2014),
            new Tretja.Nocitev(osebe[21], cilji[13], 2000),
            new Tretja.Nocitev(osebe[20], cilji[6], 2008),
            new Tretja.Nocitev(osebe[0], cilji[28], 2008),
            new Tretja.Nocitev(osebe[5], cilji[0], 2020),
            new Tretja.Nocitev(osebe[10], cilji[26], 2011),
            new Tretja.Nocitev(osebe[20], cilji[33], 2016),
            new Tretja.Nocitev(osebe[6], cilji[25], 2004),
            new Tretja.Nocitev(osebe[0], cilji[13], 2014),
            new Tretja.Nocitev(osebe[13], cilji[7], 2007),
            new Tretja.Nocitev(osebe[1], cilji[0], 2003),
            new Tretja.Nocitev(osebe[14], cilji[15], 2013),
            new Tretja.Nocitev(osebe[21], cilji[13], 2018),
            new Tretja.Nocitev(osebe[18], cilji[21], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2017),
            new Tretja.Nocitev(osebe[6], cilji[25], 2009),
            new Tretja.Nocitev(osebe[4], cilji[5], 2009),
            new Tretja.Nocitev(osebe[11], cilji[23], 2000),
            new Tretja.Nocitev(osebe[19], cilji[23], 2005),
            new Tretja.Nocitev(osebe[2], cilji[4], 2002),
            new Tretja.Nocitev(osebe[4], cilji[5], 2014),
            new Tretja.Nocitev(osebe[20], cilji[9], 2016),
            new Tretja.Nocitev(osebe[12], cilji[1], 2015),
            new Tretja.Nocitev(osebe[4], cilji[5], 2007),
            new Tretja.Nocitev(osebe[2], cilji[4], 2004),
            new Tretja.Nocitev(osebe[20], cilji[15], 2011),
            new Tretja.Nocitev(osebe[20], cilji[10], 2003),
            new Tretja.Nocitev(osebe[13], cilji[20], 2009),
            new Tretja.Nocitev(osebe[1], cilji[0], 2010),
            new Tretja.Nocitev(osebe[6], cilji[25], 2013),
            new Tretja.Nocitev(osebe[13], cilji[31], 2007),
            new Tretja.Nocitev(osebe[20], cilji[32], 2020),
            new Tretja.Nocitev(osebe[9], cilji[31], 2013),
            new Tretja.Nocitev(osebe[0], cilji[23], 2017),
            new Tretja.Nocitev(osebe[20], cilji[10], 2015),
            new Tretja.Nocitev(osebe[10], cilji[16], 2006),
            new Tretja.Nocitev(osebe[5], cilji[0], 2005),
            new Tretja.Nocitev(osebe[21], cilji[13], 2005),
            new Tretja.Nocitev(osebe[13], cilji[29], 2005),
            new Tretja.Nocitev(osebe[8], cilji[24], 2004),
            new Tretja.Nocitev(osebe[15], cilji[16], 2001),
            new Tretja.Nocitev(osebe[2], cilji[4], 2005),
            new Tretja.Nocitev(osebe[19], cilji[9], 2013),
            new Tretja.Nocitev(osebe[16], cilji[6], 2004),
            new Tretja.Nocitev(osebe[18], cilji[26], 2009),
            new Tretja.Nocitev(osebe[9], cilji[31], 2008),
            new Tretja.Nocitev(osebe[6], cilji[25], 2014),
            new Tretja.Nocitev(osebe[8], cilji[33], 2014),
            new Tretja.Nocitev(osebe[12], cilji[1], 2007),
            new Tretja.Nocitev(osebe[7], cilji[23], 2012),
            new Tretja.Nocitev(osebe[20], cilji[14], 2015),
            new Tretja.Nocitev(osebe[17], cilji[4], 2001),
            new Tretja.Nocitev(osebe[15], cilji[16], 2001),
            new Tretja.Nocitev(osebe[12], cilji[1], 2020),
            new Tretja.Nocitev(osebe[13], cilji[13], 2017),
            new Tretja.Nocitev(osebe[5], cilji[0], 2018),
            new Tretja.Nocitev(osebe[8], cilji[14], 2020),
            new Tretja.Nocitev(osebe[10], cilji[8], 2005),
            new Tretja.Nocitev(osebe[18], cilji[5], 2006),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
