
public class Test13 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Qsmd Lqeb", "Ycbf"),
            new Tretja.Oseba("Yozd Umsz", "Ycbf"),
            new Tretja.Oseba("Bjgx Hijp", "Uhim"),
            new Tretja.Oseba("Jeja Qwbn", "Ycbf"),
            new Tretja.Oseba("Suwc Nlgy", "Ycbf"),
            new Tretja.Oseba("Hkwv Cyud", "Uhim"),
            new Tretja.Oseba("Gwjd Dljv", "Ycbf"),
            new Tretja.Oseba("Nhmo Qdeq", "Uhim"),
            new Tretja.Oseba("Lwdt Dxxq", "Ycbf"),
            new Tretja.Oseba("Vsbg Scge", "Uhim"),
            new Tretja.Oseba("Ycdp Oajk", "Uhim"),
            new Tretja.Oseba("Hnue Nljg", "Ycbf"),
            new Tretja.Oseba("Ttau Aug", "Uhim"),
            new Tretja.Oseba("Fxxc Scmx", "Uhim"),
            new Tretja.Oseba("Epkl Mjbr", "Uhim"),
            new Tretja.Oseba("Vowo Togq", "Ycbf"),
            new Tretja.Oseba("Rdgx Ccbq", "Uhim"),
            new Tretja.Oseba("Ugwe Zzxo", "Ycbf"),
            new Tretja.Oseba("Idxw Wwnq", "Ycbf"),
            new Tretja.Oseba("Nngf Hqh", "Ycbf"),
            new Tretja.Oseba("Focb Dmix", "Ycbf"),
            new Tretja.Oseba("Xpk Myxx", "Uhim"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Avbb", "Ycbf"),
            new Tretja.Cilj("Iupq", "Uhim"),
            new Tretja.Cilj("Gcue", "Ycbf"),
            new Tretja.Cilj("Aqkf", "Uhim"),
            new Tretja.Cilj("Pdbi", "Ycbf"),
            new Tretja.Cilj("Wgj", "Ycbf"),
            new Tretja.Cilj("Clv", "Uhim"),
            new Tretja.Cilj("Lyhy", "Uhim"),
            new Tretja.Cilj("Itij", "Uhim"),
            new Tretja.Cilj("Xnbm", "Uhim"),
            new Tretja.Cilj("Gesy", "Uhim"),
            new Tretja.Cilj("Csnr", "Uhim"),
            new Tretja.Cilj("Lfhy", "Ycbf"),
            new Tretja.Cilj("Jnzx", "Uhim"),
            new Tretja.Cilj("Wvyf", "Uhim"),
            new Tretja.Cilj("Tbid", "Ycbf"),
            new Tretja.Cilj("Bedi", "Uhim"),
            new Tretja.Cilj("Bwha", "Uhim"),
            new Tretja.Cilj("Acco", "Uhim"),
            new Tretja.Cilj("Mjhq", "Uhim"),
            new Tretja.Cilj("Mlvf", "Ycbf"),
            new Tretja.Cilj("Cdav", "Ycbf"),
            new Tretja.Cilj("Gvhm", "Uhim"),
            new Tretja.Cilj("Gfjq", "Ycbf"),
            new Tretja.Cilj("Neiy", "Uhim"),
            new Tretja.Cilj("Tnro", "Uhim"),
            new Tretja.Cilj("Wtqm", "Ycbf"),
            new Tretja.Cilj("Oxyn", "Ycbf"),
            new Tretja.Cilj("Lucx", "Ycbf"),
            new Tretja.Cilj("Ekzu", "Uhim"),
            new Tretja.Cilj("Owbu", "Ycbf"),
            new Tretja.Cilj("Enwr", "Ycbf"),
            new Tretja.Cilj("Cghf", "Ycbf"),
            new Tretja.Cilj("Aopk", "Uhim"),
            new Tretja.Cilj("Jvte", "Ycbf"),
            new Tretja.Cilj("Cmrw", "Ycbf"),
            new Tretja.Cilj("Eljh", "Uhim"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[18], cilji[25], 2006),
            new Tretja.Nocitev(osebe[1], cilji[2], 2020),
            new Tretja.Nocitev(osebe[5], cilji[34], 2007),
            new Tretja.Nocitev(osebe[12], cilji[19], 2005),
            new Tretja.Nocitev(osebe[17], cilji[27], 2013),
            new Tretja.Nocitev(osebe[12], cilji[19], 2001),
            new Tretja.Nocitev(osebe[19], cilji[16], 2009),
            new Tretja.Nocitev(osebe[12], cilji[19], 2004),
            new Tretja.Nocitev(osebe[6], cilji[0], 2020),
            new Tretja.Nocitev(osebe[2], cilji[1], 2002),
            new Tretja.Nocitev(osebe[3], cilji[12], 2018),
            new Tretja.Nocitev(osebe[11], cilji[15], 2014),
            new Tretja.Nocitev(osebe[1], cilji[2], 2015),
            new Tretja.Nocitev(osebe[0], cilji[9], 2010),
            new Tretja.Nocitev(osebe[14], cilji[8], 2014),
            new Tretja.Nocitev(osebe[9], cilji[16], 2005),
            new Tretja.Nocitev(osebe[10], cilji[33], 2000),
            new Tretja.Nocitev(osebe[5], cilji[20], 2009),
            new Tretja.Nocitev(osebe[0], cilji[19], 2009),
            new Tretja.Nocitev(osebe[10], cilji[33], 2020),
            new Tretja.Nocitev(osebe[7], cilji[12], 2000),
            new Tretja.Nocitev(osebe[6], cilji[18], 2008),
            new Tretja.Nocitev(osebe[1], cilji[2], 2015),
            new Tretja.Nocitev(osebe[8], cilji[22], 2017),
            new Tretja.Nocitev(osebe[16], cilji[25], 2016),
            new Tretja.Nocitev(osebe[6], cilji[24], 2014),
            new Tretja.Nocitev(osebe[21], cilji[35], 2001),
            new Tretja.Nocitev(osebe[14], cilji[1], 2013),
            new Tretja.Nocitev(osebe[15], cilji[28], 2012),
            new Tretja.Nocitev(osebe[6], cilji[9], 2007),
            new Tretja.Nocitev(osebe[14], cilji[4], 2016),
            new Tretja.Nocitev(osebe[9], cilji[25], 2001),
            new Tretja.Nocitev(osebe[6], cilji[36], 2004),
            new Tretja.Nocitev(osebe[20], cilji[7], 2007),
            new Tretja.Nocitev(osebe[18], cilji[23], 2017),
            new Tretja.Nocitev(osebe[16], cilji[25], 2000),
            new Tretja.Nocitev(osebe[4], cilji[13], 2018),
            new Tretja.Nocitev(osebe[8], cilji[22], 2020),
            new Tretja.Nocitev(osebe[12], cilji[19], 2005),
            new Tretja.Nocitev(osebe[3], cilji[12], 2016),
            new Tretja.Nocitev(osebe[9], cilji[5], 2018),
            new Tretja.Nocitev(osebe[6], cilji[0], 2019),
            new Tretja.Nocitev(osebe[13], cilji[26], 2017),
            new Tretja.Nocitev(osebe[18], cilji[13], 2009),
            new Tretja.Nocitev(osebe[18], cilji[26], 2011),
            new Tretja.Nocitev(osebe[3], cilji[12], 2003),
            new Tretja.Nocitev(osebe[17], cilji[27], 2011),
            new Tretja.Nocitev(osebe[9], cilji[1], 2012),
            new Tretja.Nocitev(osebe[20], cilji[7], 2004),
            new Tretja.Nocitev(osebe[5], cilji[31], 2007),
            new Tretja.Nocitev(osebe[7], cilji[12], 2007),
            new Tretja.Nocitev(osebe[7], cilji[12], 2012),
            new Tretja.Nocitev(osebe[5], cilji[18], 2003),
            new Tretja.Nocitev(osebe[17], cilji[27], 2008),
            new Tretja.Nocitev(osebe[6], cilji[18], 2002),
            new Tretja.Nocitev(osebe[0], cilji[17], 2020),
            new Tretja.Nocitev(osebe[7], cilji[12], 2008),
            new Tretja.Nocitev(osebe[3], cilji[12], 2002),
            new Tretja.Nocitev(osebe[12], cilji[19], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2016),
            new Tretja.Nocitev(osebe[13], cilji[3], 2012),
            new Tretja.Nocitev(osebe[15], cilji[28], 2002),
            new Tretja.Nocitev(osebe[0], cilji[7], 2009),
            new Tretja.Nocitev(osebe[17], cilji[27], 2020),
            new Tretja.Nocitev(osebe[10], cilji[33], 2015),
            new Tretja.Nocitev(osebe[2], cilji[11], 2012),
            new Tretja.Nocitev(osebe[6], cilji[28], 2002),
            new Tretja.Nocitev(osebe[5], cilji[2], 2019),
            new Tretja.Nocitev(osebe[11], cilji[10], 2011),
            new Tretja.Nocitev(osebe[17], cilji[27], 2018),
            new Tretja.Nocitev(osebe[14], cilji[6], 2006),
            new Tretja.Nocitev(osebe[6], cilji[7], 2016),
            new Tretja.Nocitev(osebe[13], cilji[35], 2003),
            new Tretja.Nocitev(osebe[11], cilji[4], 2012),
            new Tretja.Nocitev(osebe[17], cilji[27], 2010),
            new Tretja.Nocitev(osebe[12], cilji[19], 2015),
            new Tretja.Nocitev(osebe[19], cilji[16], 2017),
            new Tretja.Nocitev(osebe[10], cilji[33], 2014),
            new Tretja.Nocitev(osebe[15], cilji[28], 2006),
            new Tretja.Nocitev(osebe[9], cilji[14], 2001),
            new Tretja.Nocitev(osebe[21], cilji[32], 2008),
            new Tretja.Nocitev(osebe[5], cilji[15], 2016),
            new Tretja.Nocitev(osebe[14], cilji[10], 2017),
            new Tretja.Nocitev(osebe[18], cilji[31], 2006),
            new Tretja.Nocitev(osebe[17], cilji[27], 2006),
            new Tretja.Nocitev(osebe[19], cilji[16], 2012),
            new Tretja.Nocitev(osebe[7], cilji[12], 2015),
            new Tretja.Nocitev(osebe[18], cilji[26], 2017),
            new Tretja.Nocitev(osebe[14], cilji[3], 2010),
            new Tretja.Nocitev(osebe[8], cilji[22], 2003),
            new Tretja.Nocitev(osebe[12], cilji[19], 2001),
            new Tretja.Nocitev(osebe[18], cilji[1], 2011),
            new Tretja.Nocitev(osebe[17], cilji[27], 2018),
            new Tretja.Nocitev(osebe[5], cilji[32], 2020),
            new Tretja.Nocitev(osebe[17], cilji[27], 2002),
            new Tretja.Nocitev(osebe[8], cilji[22], 2000),
            new Tretja.Nocitev(osebe[13], cilji[31], 2010),
            new Tretja.Nocitev(osebe[1], cilji[2], 2005),
            new Tretja.Nocitev(osebe[11], cilji[17], 2012),
            new Tretja.Nocitev(osebe[12], cilji[19], 2018),
            new Tretja.Nocitev(osebe[4], cilji[22], 2016),
            new Tretja.Nocitev(osebe[18], cilji[2], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2016),
            new Tretja.Nocitev(osebe[12], cilji[19], 2013),
            new Tretja.Nocitev(osebe[9], cilji[11], 2014),
            new Tretja.Nocitev(osebe[4], cilji[10], 2013),
            new Tretja.Nocitev(osebe[20], cilji[7], 2012),
            new Tretja.Nocitev(osebe[5], cilji[31], 2015),
            new Tretja.Nocitev(osebe[8], cilji[22], 2016),
            new Tretja.Nocitev(osebe[17], cilji[27], 2016),
            new Tretja.Nocitev(osebe[10], cilji[33], 2004),
            new Tretja.Nocitev(osebe[14], cilji[14], 2019),
            new Tretja.Nocitev(osebe[11], cilji[20], 2014),
            new Tretja.Nocitev(osebe[3], cilji[12], 2007),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
