
public class Test02 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Ndmt Fkuo", "Tjiv"),
            new Tretja.Oseba("Kffd Nqvb", "Gmwh"),
            new Tretja.Oseba("Oytc Qagk", "Itwu"),
            new Tretja.Oseba("Uyhm Eptj", "Gmwh"),
            new Tretja.Oseba("Gdze Idip", "Tjiv"),
            new Tretja.Oseba("Lnkl Ozax", "Gmwh"),
            new Tretja.Oseba("Ihqc Mtgy", "Tmht"),
            new Tretja.Oseba("Jdwl Kmrm", "Tmht"),
            new Tretja.Oseba("Rasw Kfqr", "Gmwh"),
            new Tretja.Oseba("Qroc Rnhd", "Tjiv"),
            new Tretja.Oseba("Pftd Rkxo", "Ians"),
            new Tretja.Oseba("Ugmn Gmaz", "Itwu"),
            new Tretja.Oseba("Nyxm Qwcw", "Ians"),
            new Tretja.Oseba("Lwau Gxqx", "Itwu"),
            new Tretja.Oseba("Wffp Mlbq", "Tmht"),
            new Tretja.Oseba("Avjx Dtwf", "Tjiv"),
            new Tretja.Oseba("Lyly Cgwz", "Itwu"),
            new Tretja.Oseba("Dhbj Lfzn", "Gmwh"),
            new Tretja.Oseba("Rwjc Kdqn", "Tmht"),
            new Tretja.Oseba("Gyry Hldd", "Tjiv"),
            new Tretja.Oseba("Gfgu Qxej", "Gmwh"),
            new Tretja.Oseba("Jkoq Ohdz", "Itwu"),
            new Tretja.Oseba("Zhyc Nzkt", "Tmht"),
            new Tretja.Oseba("Ityc Zbci", "Tjiv"),
            new Tretja.Oseba("Rsno Fdpi", "Itwu"),
            new Tretja.Oseba("Cjps Jxzp", "Tmht"),
            new Tretja.Oseba("Pmef Atku", "Itwu"),
            new Tretja.Oseba("Ooqj Ibtb", "Ians"),
            new Tretja.Oseba("Pvuf Pdvw", "Itwu"),
            new Tretja.Oseba("Reom Mht", "Tjiv"),
            new Tretja.Oseba("Wtdp Yszb", "Tjiv"),
            new Tretja.Oseba("Bpwn Kfot", "Tjiv"),
            new Tretja.Oseba("Cwks Plg", "Tjiv"),
            new Tretja.Oseba("Ktza Vocr", "Tjiv"),
            new Tretja.Oseba("Quij Euhp", "Tmht"),
            new Tretja.Oseba("Jsrw Ircf", "Ians"),
            new Tretja.Oseba("Pdmw Vzsr", "Gmwh"),
            new Tretja.Oseba("Iwfl Mhhw", "Tjiv"),
            new Tretja.Oseba("Nfro Fhhj", "Itwu"),
            new Tretja.Oseba("Avkm Ltaa", "Itwu"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Tmrm", "Itwu"),
            new Tretja.Cilj("Ylgk", "Tmht"),
            new Tretja.Cilj("Nzwx", "Gmwh"),
            new Tretja.Cilj("Ysju", "Tmht"),
            new Tretja.Cilj("Qnjc", "Tmht"),
            new Tretja.Cilj("Enot", "Ians"),
            new Tretja.Cilj("Jfg", "Itwu"),
            new Tretja.Cilj("Woky", "Tjiv"),
            new Tretja.Cilj("Kjgd", "Gmwh"),
            new Tretja.Cilj("Gxgq", "Gmwh"),
            new Tretja.Cilj("Edas", "Tmht"),
            new Tretja.Cilj("Upwc", "Tjiv"),
            new Tretja.Cilj("Voni", "Gmwh"),
            new Tretja.Cilj("Hqsa", "Tjiv"),
            new Tretja.Cilj("Nnpj", "Itwu"),
            new Tretja.Cilj("Ivvb", "Tmht"),
            new Tretja.Cilj("Sexw", "Tmht"),
            new Tretja.Cilj("Xrpq", "Tjiv"),
            new Tretja.Cilj("Pure", "Tmht"),
            new Tretja.Cilj("Drsn", "Tmht"),
            new Tretja.Cilj("Rgtc", "Tjiv"),
            new Tretja.Cilj("Fbju", "Gmwh"),
            new Tretja.Cilj("Ztog", "Tmht"),
            new Tretja.Cilj("Rrzw", "Ians"),
            new Tretja.Cilj("Vxeu", "Tjiv"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[0], cilji[14], 2019),
            new Tretja.Nocitev(osebe[14], cilji[20], 2014),
            new Tretja.Nocitev(osebe[8], cilji[11], 2001),
            new Tretja.Nocitev(osebe[32], cilji[21], 2014),
            new Tretja.Nocitev(osebe[8], cilji[11], 2016),
            new Tretja.Nocitev(osebe[31], cilji[15], 2010),
            new Tretja.Nocitev(osebe[18], cilji[21], 2011),
            new Tretja.Nocitev(osebe[17], cilji[8], 2013),
            new Tretja.Nocitev(osebe[15], cilji[5], 2004),
            new Tretja.Nocitev(osebe[0], cilji[17], 2014),
            new Tretja.Nocitev(osebe[39], cilji[20], 2006),
            new Tretja.Nocitev(osebe[15], cilji[5], 2006),
            new Tretja.Nocitev(osebe[12], cilji[2], 2010),
            new Tretja.Nocitev(osebe[13], cilji[11], 2009),
            new Tretja.Nocitev(osebe[20], cilji[12], 2012),
            new Tretja.Nocitev(osebe[30], cilji[0], 2020),
            new Tretja.Nocitev(osebe[17], cilji[8], 2013),
            new Tretja.Nocitev(osebe[1], cilji[24], 2016),
            new Tretja.Nocitev(osebe[9], cilji[8], 2000),
            new Tretja.Nocitev(osebe[23], cilji[1], 2007),
            new Tretja.Nocitev(osebe[27], cilji[4], 2017),
            new Tretja.Nocitev(osebe[13], cilji[7], 2006),
            new Tretja.Nocitev(osebe[26], cilji[6], 2019),
            new Tretja.Nocitev(osebe[29], cilji[18], 2011),
            new Tretja.Nocitev(osebe[3], cilji[7], 2005),
            new Tretja.Nocitev(osebe[39], cilji[3], 2016),
            new Tretja.Nocitev(osebe[3], cilji[24], 2011),
            new Tretja.Nocitev(osebe[13], cilji[0], 2007),
            new Tretja.Nocitev(osebe[1], cilji[6], 2004),
            new Tretja.Nocitev(osebe[27], cilji[21], 2007),
            new Tretja.Nocitev(osebe[15], cilji[5], 2005),
            new Tretja.Nocitev(osebe[8], cilji[11], 2017),
            new Tretja.Nocitev(osebe[25], cilji[12], 2007),
            new Tretja.Nocitev(osebe[13], cilji[10], 2014),
            new Tretja.Nocitev(osebe[9], cilji[8], 2005),
            new Tretja.Nocitev(osebe[35], cilji[16], 2014),
            new Tretja.Nocitev(osebe[29], cilji[18], 2006),
            new Tretja.Nocitev(osebe[21], cilji[1], 2012),
            new Tretja.Nocitev(osebe[5], cilji[19], 2005),
            new Tretja.Nocitev(osebe[24], cilji[16], 2000),
            new Tretja.Nocitev(osebe[34], cilji[4], 2003),
            new Tretja.Nocitev(osebe[17], cilji[8], 2015),
            new Tretja.Nocitev(osebe[24], cilji[16], 2013),
            new Tretja.Nocitev(osebe[19], cilji[5], 2007),
            new Tretja.Nocitev(osebe[26], cilji[6], 2000),
            new Tretja.Nocitev(osebe[2], cilji[16], 2002),
            new Tretja.Nocitev(osebe[17], cilji[8], 2009),
            new Tretja.Nocitev(osebe[31], cilji[20], 2020),
            new Tretja.Nocitev(osebe[6], cilji[24], 2010),
            new Tretja.Nocitev(osebe[7], cilji[12], 2006),
            new Tretja.Nocitev(osebe[0], cilji[2], 2016),
            new Tretja.Nocitev(osebe[5], cilji[19], 2001),
            new Tretja.Nocitev(osebe[12], cilji[2], 2015),
            new Tretja.Nocitev(osebe[25], cilji[12], 2007),
            new Tretja.Nocitev(osebe[30], cilji[0], 2002),
            new Tretja.Nocitev(osebe[39], cilji[8], 2009),
            new Tretja.Nocitev(osebe[15], cilji[5], 2019),
            new Tretja.Nocitev(osebe[38], cilji[7], 2003),
            new Tretja.Nocitev(osebe[33], cilji[22], 2000),
            new Tretja.Nocitev(osebe[22], cilji[15], 2005),
            new Tretja.Nocitev(osebe[32], cilji[21], 2006),
            new Tretja.Nocitev(osebe[12], cilji[2], 2000),
            new Tretja.Nocitev(osebe[10], cilji[16], 2008),
            new Tretja.Nocitev(osebe[22], cilji[20], 2017),
            new Tretja.Nocitev(osebe[23], cilji[22], 2003),
            new Tretja.Nocitev(osebe[8], cilji[11], 2016),
            new Tretja.Nocitev(osebe[23], cilji[11], 2009),
            new Tretja.Nocitev(osebe[35], cilji[16], 2009),
            new Tretja.Nocitev(osebe[0], cilji[13], 2016),
            new Tretja.Nocitev(osebe[8], cilji[11], 2008),
            new Tretja.Nocitev(osebe[24], cilji[16], 2017),
            new Tretja.Nocitev(osebe[33], cilji[22], 2005),
            new Tretja.Nocitev(osebe[26], cilji[6], 2007),
            new Tretja.Nocitev(osebe[3], cilji[3], 2008),
            new Tretja.Nocitev(osebe[6], cilji[10], 2008),
            new Tretja.Nocitev(osebe[7], cilji[5], 2004),
            new Tretja.Nocitev(osebe[23], cilji[22], 2009),
            new Tretja.Nocitev(osebe[18], cilji[19], 2010),
            new Tretja.Nocitev(osebe[6], cilji[8], 2012),
            new Tretja.Nocitev(osebe[16], cilji[19], 2007),
            new Tretja.Nocitev(osebe[5], cilji[19], 2012),
            new Tretja.Nocitev(osebe[5], cilji[19], 2017),
            new Tretja.Nocitev(osebe[10], cilji[6], 2020),
            new Tretja.Nocitev(osebe[30], cilji[0], 2018),
            new Tretja.Nocitev(osebe[1], cilji[5], 2001),
            new Tretja.Nocitev(osebe[28], cilji[8], 2017),
            new Tretja.Nocitev(osebe[39], cilji[14], 2012),
            new Tretja.Nocitev(osebe[35], cilji[16], 2002),
            new Tretja.Nocitev(osebe[29], cilji[18], 2018),
            new Tretja.Nocitev(osebe[39], cilji[9], 2003),
            new Tretja.Nocitev(osebe[20], cilji[12], 2011),
            new Tretja.Nocitev(osebe[31], cilji[18], 2001),
            new Tretja.Nocitev(osebe[23], cilji[14], 2003),
            new Tretja.Nocitev(osebe[28], cilji[8], 2014),
            new Tretja.Nocitev(osebe[35], cilji[16], 2019),
            new Tretja.Nocitev(osebe[22], cilji[12], 2013),
            new Tretja.Nocitev(osebe[38], cilji[7], 2013),
            new Tretja.Nocitev(osebe[6], cilji[7], 2008),
            new Tretja.Nocitev(osebe[11], cilji[1], 2019),
            new Tretja.Nocitev(osebe[11], cilji[24], 2015),
            new Tretja.Nocitev(osebe[38], cilji[7], 2017),
            new Tretja.Nocitev(osebe[17], cilji[8], 2005),
            new Tretja.Nocitev(osebe[36], cilji[14], 2012),
            new Tretja.Nocitev(osebe[36], cilji[14], 2004),
            new Tretja.Nocitev(osebe[19], cilji[5], 2000),
            new Tretja.Nocitev(osebe[29], cilji[18], 2002),
            new Tretja.Nocitev(osebe[13], cilji[14], 2011),
            new Tretja.Nocitev(osebe[17], cilji[8], 2010),
            new Tretja.Nocitev(osebe[29], cilji[18], 2003),
            new Tretja.Nocitev(osebe[37], cilji[19], 2011),
            new Tretja.Nocitev(osebe[12], cilji[2], 2017),
            new Tretja.Nocitev(osebe[19], cilji[5], 2004),
            new Tretja.Nocitev(osebe[7], cilji[1], 2015),
            new Tretja.Nocitev(osebe[2], cilji[9], 2015),
            new Tretja.Nocitev(osebe[21], cilji[13], 2010),
            new Tretja.Nocitev(osebe[10], cilji[24], 2004),
            new Tretja.Nocitev(osebe[9], cilji[8], 2016),
            new Tretja.Nocitev(osebe[21], cilji[6], 2001),
            new Tretja.Nocitev(osebe[11], cilji[19], 2018),
            new Tretja.Nocitev(osebe[23], cilji[4], 2017),
            new Tretja.Nocitev(osebe[36], cilji[14], 2001),
            new Tretja.Nocitev(osebe[1], cilji[3], 2014),
            new Tretja.Nocitev(osebe[31], cilji[22], 2003),
            new Tretja.Nocitev(osebe[15], cilji[5], 2002),
            new Tretja.Nocitev(osebe[8], cilji[11], 2014),
            new Tretja.Nocitev(osebe[7], cilji[8], 2011),
            new Tretja.Nocitev(osebe[35], cilji[16], 2008),
            new Tretja.Nocitev(osebe[1], cilji[6], 2011),
            new Tretja.Nocitev(osebe[23], cilji[11], 2009),
            new Tretja.Nocitev(osebe[13], cilji[23], 2014),
            new Tretja.Nocitev(osebe[14], cilji[8], 2012),
            new Tretja.Nocitev(osebe[5], cilji[19], 2006),
            new Tretja.Nocitev(osebe[33], cilji[22], 2003),
            new Tretja.Nocitev(osebe[28], cilji[8], 2017),
            new Tretja.Nocitev(osebe[5], cilji[19], 2017),
            new Tretja.Nocitev(osebe[19], cilji[5], 2018),
            new Tretja.Nocitev(osebe[34], cilji[18], 2013),
            new Tretja.Nocitev(osebe[35], cilji[16], 2002),
            new Tretja.Nocitev(osebe[34], cilji[14], 2003),
            new Tretja.Nocitev(osebe[28], cilji[8], 2009),
            new Tretja.Nocitev(osebe[38], cilji[7], 2008),
            new Tretja.Nocitev(osebe[23], cilji[18], 2008),
            new Tretja.Nocitev(osebe[19], cilji[5], 2010),
            new Tretja.Nocitev(osebe[8], cilji[11], 2017),
            new Tretja.Nocitev(osebe[36], cilji[14], 2010),
            new Tretja.Nocitev(osebe[39], cilji[7], 2010),
            new Tretja.Nocitev(osebe[38], cilji[7], 2016),
            new Tretja.Nocitev(osebe[16], cilji[19], 2015),
            new Tretja.Nocitev(osebe[30], cilji[0], 2019),
            new Tretja.Nocitev(osebe[8], cilji[11], 2009),
            new Tretja.Nocitev(osebe[19], cilji[5], 2010),
            new Tretja.Nocitev(osebe[27], cilji[5], 2006),
            new Tretja.Nocitev(osebe[28], cilji[8], 2016),
            new Tretja.Nocitev(osebe[37], cilji[19], 2014),
            new Tretja.Nocitev(osebe[6], cilji[13], 2016),
            new Tretja.Nocitev(osebe[26], cilji[6], 2011),
            new Tretja.Nocitev(osebe[34], cilji[19], 2017),
            new Tretja.Nocitev(osebe[26], cilji[6], 2009),
        };

        System.out.println(Tretja.notranje(nocitve));
    }
}
