
public class Test23 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Vpkh Fdfe", "Ocho"),
            new Tretja.Oseba("Lfvm Qxsc", "Insr"),
            new Tretja.Oseba("Jpbe Togi", "Ocho"),
            new Tretja.Oseba("Omqy Fbpk", "Ocho"),
            new Tretja.Oseba("Ceqk Nulw", "Mfax"),
            new Tretja.Oseba("Aual Spte", "Ocho"),
            new Tretja.Oseba("Krue Mlyf", "Tjvh"),
            new Tretja.Oseba("Joet Kxzd", "Mfax"),
            new Tretja.Oseba("Gjax Riyg", "Mfax"),
            new Tretja.Oseba("Hwrr Ctda", "Insr"),
            new Tretja.Oseba("Otje Rgpv", "Ocho"),
            new Tretja.Oseba("Vyeo Xkbc", "Insr"),
            new Tretja.Oseba("Xevm Jrwn", "Insr"),
            new Tretja.Oseba("Cknn Nqty", "Ocho"),
            new Tretja.Oseba("Gnfr Pjkr", "Tjvh"),
            new Tretja.Oseba("Ipvf Uhkl", "Ocho"),
            new Tretja.Oseba("Ihxx Fkdc", "Insr"),
            new Tretja.Oseba("Fcgu Qrbm", "Tjvh"),
            new Tretja.Oseba("Gssj Jjfm", "Mfax"),
            new Tretja.Oseba("Anns Cwcf", "Tjvh"),
            new Tretja.Oseba("Ackh Akhj", "Tjvh"),
            new Tretja.Oseba("Itmt Usbk", "Ocho"),
            new Tretja.Oseba("Ahwp Uxsc", "Ocho"),
            new Tretja.Oseba("Prot Wwre", "Mfax"),
            new Tretja.Oseba("Wckd Mrjj", "Insr"),
            new Tretja.Oseba("Fkcm Vmxl", "Mfax"),
            new Tretja.Oseba("Pcnx Niit", "Ocho"),
            new Tretja.Oseba("Zlvy Bpro", "Insr"),
            new Tretja.Oseba("Iozj Afcp", "Insr"),
            new Tretja.Oseba("Ltbw Ijnf", "Mfax"),
            new Tretja.Oseba("Fyhy Ljdo", "Ocho"),
            new Tretja.Oseba("Tlgq Qoye", "Tjvh"),
            new Tretja.Oseba("Cyti Cief", "Ocho"),
            new Tretja.Oseba("Astu Irrr", "Ocho"),
            new Tretja.Oseba("Idzc Qqbp", "Mfax"),
            new Tretja.Oseba("Vzch Twrt", "Insr"),
            new Tretja.Oseba("Ixyj Tebx", "Tjvh"),
            new Tretja.Oseba("Nphr Oygz", "Ocho"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Tpyf", "Ocho"),
            new Tretja.Cilj("Mowx", "Insr"),
            new Tretja.Cilj("Kvaa", "Ocho"),
            new Tretja.Cilj("Bbgt", "Ocho"),
            new Tretja.Cilj("Ekix", "Ocho"),
            new Tretja.Cilj("Ukjq", "Mfax"),
            new Tretja.Cilj("Skid", "Ocho"),
            new Tretja.Cilj("Ntso", "Insr"),
            new Tretja.Cilj("Vtkq", "Insr"),
            new Tretja.Cilj("Zcbq", "Ocho"),
            new Tretja.Cilj("Texw", "Insr"),
            new Tretja.Cilj("Tyei", "Ocho"),
            new Tretja.Cilj("Syrm", "Tjvh"),
            new Tretja.Cilj("Xyzm", "Mfax"),
            new Tretja.Cilj("Mwik", "Mfax"),
            new Tretja.Cilj("Klhh", "Mfax"),
            new Tretja.Cilj("Hmsn", "Tjvh"),
            new Tretja.Cilj("Rkyv", "Mfax"),
            new Tretja.Cilj("Wzre", "Tjvh"),
            new Tretja.Cilj("Izcb", "Ocho"),
            new Tretja.Cilj("Zvyx", "Mfax"),
            new Tretja.Cilj("Grpx", "Mfax"),
            new Tretja.Cilj("Gnur", "Tjvh"),
            new Tretja.Cilj("Zouz", "Insr"),
            new Tretja.Cilj("Ghpo", "Ocho"),
            new Tretja.Cilj("Ymuw", "Tjvh"),
            new Tretja.Cilj("Pwqk", "Insr"),
            new Tretja.Cilj("Zvor", "Insr"),
            new Tretja.Cilj("Vgt", "Mfax"),
            new Tretja.Cilj("Csmf", "Tjvh"),
            new Tretja.Cilj("Jplj", "Ocho"),
            new Tretja.Cilj("Mrbh", "Tjvh"),
            new Tretja.Cilj("Srio", "Ocho"),
            new Tretja.Cilj("Lopz", "Ocho"),
            new Tretja.Cilj("Fqgc", "Insr"),
            new Tretja.Cilj("Mvjh", "Tjvh"),
            new Tretja.Cilj("Qlcb", "Insr"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[34], cilji[19], 2016),
            new Tretja.Nocitev(osebe[11], cilji[24], 2020),
            new Tretja.Nocitev(osebe[19], cilji[15], 2000),
            new Tretja.Nocitev(osebe[35], cilji[2], 2015),
            new Tretja.Nocitev(osebe[1], cilji[16], 2007),
            new Tretja.Nocitev(osebe[14], cilji[7], 2017),
            new Tretja.Nocitev(osebe[37], cilji[31], 2006),
            new Tretja.Nocitev(osebe[3], cilji[28], 2004),
            new Tretja.Nocitev(osebe[3], cilji[18], 2005),
            new Tretja.Nocitev(osebe[19], cilji[25], 2010),
            new Tretja.Nocitev(osebe[5], cilji[36], 2001),
            new Tretja.Nocitev(osebe[23], cilji[24], 2007),
            new Tretja.Nocitev(osebe[11], cilji[24], 2007),
            new Tretja.Nocitev(osebe[9], cilji[30], 2015),
            new Tretja.Nocitev(osebe[17], cilji[12], 2015),
            new Tretja.Nocitev(osebe[33], cilji[33], 2007),
            new Tretja.Nocitev(osebe[20], cilji[5], 2012),
            new Tretja.Nocitev(osebe[1], cilji[16], 2011),
            new Tretja.Nocitev(osebe[24], cilji[2], 2012),
            new Tretja.Nocitev(osebe[19], cilji[16], 2005),
            new Tretja.Nocitev(osebe[4], cilji[22], 2011),
            new Tretja.Nocitev(osebe[14], cilji[18], 2001),
            new Tretja.Nocitev(osebe[28], cilji[35], 2010),
            new Tretja.Nocitev(osebe[14], cilji[32], 2016),
            new Tretja.Nocitev(osebe[19], cilji[31], 2010),
            new Tretja.Nocitev(osebe[8], cilji[21], 2005),
            new Tretja.Nocitev(osebe[10], cilji[32], 2005),
            new Tretja.Nocitev(osebe[22], cilji[17], 2002),
            new Tretja.Nocitev(osebe[17], cilji[12], 2011),
            new Tretja.Nocitev(osebe[11], cilji[24], 2013),
            new Tretja.Nocitev(osebe[10], cilji[7], 2019),
            new Tretja.Nocitev(osebe[23], cilji[33], 2004),
            new Tretja.Nocitev(osebe[35], cilji[2], 2008),
            new Tretja.Nocitev(osebe[12], cilji[3], 2007),
            new Tretja.Nocitev(osebe[34], cilji[19], 2006),
            new Tretja.Nocitev(osebe[13], cilji[35], 2016),
            new Tretja.Nocitev(osebe[22], cilji[16], 2017),
            new Tretja.Nocitev(osebe[8], cilji[0], 2005),
            new Tretja.Nocitev(osebe[19], cilji[11], 2000),
            new Tretja.Nocitev(osebe[25], cilji[19], 2002),
            new Tretja.Nocitev(osebe[19], cilji[15], 2000),
            new Tretja.Nocitev(osebe[31], cilji[32], 2018),
            new Tretja.Nocitev(osebe[1], cilji[16], 2017),
            new Tretja.Nocitev(osebe[0], cilji[36], 2019),
            new Tretja.Nocitev(osebe[16], cilji[13], 2018),
            new Tretja.Nocitev(osebe[31], cilji[32], 2020),
            new Tretja.Nocitev(osebe[10], cilji[18], 2014),
            new Tretja.Nocitev(osebe[16], cilji[13], 2014),
            new Tretja.Nocitev(osebe[31], cilji[32], 2002),
            new Tretja.Nocitev(osebe[36], cilji[10], 2017),
            new Tretja.Nocitev(osebe[14], cilji[12], 2000),
            new Tretja.Nocitev(osebe[30], cilji[22], 2019),
            new Tretja.Nocitev(osebe[7], cilji[20], 2004),
            new Tretja.Nocitev(osebe[33], cilji[33], 2013),
            new Tretja.Nocitev(osebe[6], cilji[19], 2017),
            new Tretja.Nocitev(osebe[16], cilji[13], 2011),
            new Tretja.Nocitev(osebe[19], cilji[34], 2001),
            new Tretja.Nocitev(osebe[1], cilji[16], 2000),
            new Tretja.Nocitev(osebe[3], cilji[27], 2018),
            new Tretja.Nocitev(osebe[12], cilji[2], 2018),
            new Tretja.Nocitev(osebe[24], cilji[21], 2010),
            new Tretja.Nocitev(osebe[13], cilji[35], 2019),
            new Tretja.Nocitev(osebe[12], cilji[11], 2002),
            new Tretja.Nocitev(osebe[32], cilji[18], 2000),
            new Tretja.Nocitev(osebe[29], cilji[21], 2002),
            new Tretja.Nocitev(osebe[32], cilji[18], 2019),
            new Tretja.Nocitev(osebe[17], cilji[12], 2015),
            new Tretja.Nocitev(osebe[35], cilji[2], 2019),
            new Tretja.Nocitev(osebe[19], cilji[26], 2013),
            new Tretja.Nocitev(osebe[9], cilji[11], 2015),
            new Tretja.Nocitev(osebe[13], cilji[35], 2000),
            new Tretja.Nocitev(osebe[26], cilji[24], 2007),
            new Tretja.Nocitev(osebe[5], cilji[36], 2009),
            new Tretja.Nocitev(osebe[31], cilji[32], 2012),
            new Tretja.Nocitev(osebe[37], cilji[2], 2005),
            new Tretja.Nocitev(osebe[2], cilji[16], 2012),
            new Tretja.Nocitev(osebe[27], cilji[25], 2011),
            new Tretja.Nocitev(osebe[19], cilji[28], 2001),
            new Tretja.Nocitev(osebe[34], cilji[19], 2015),
            new Tretja.Nocitev(osebe[2], cilji[16], 2011),
            new Tretja.Nocitev(osebe[9], cilji[10], 2005),
            new Tretja.Nocitev(osebe[35], cilji[2], 2007),
            new Tretja.Nocitev(osebe[7], cilji[27], 2014),
            new Tretja.Nocitev(osebe[13], cilji[35], 2004),
            new Tretja.Nocitev(osebe[32], cilji[18], 2007),
            new Tretja.Nocitev(osebe[9], cilji[26], 2015),
            new Tretja.Nocitev(osebe[17], cilji[12], 2020),
            new Tretja.Nocitev(osebe[13], cilji[35], 2012),
            new Tretja.Nocitev(osebe[10], cilji[14], 2006),
            new Tretja.Nocitev(osebe[7], cilji[13], 2011),
            new Tretja.Nocitev(osebe[31], cilji[32], 2005),
            new Tretja.Nocitev(osebe[0], cilji[19], 2014),
            new Tretja.Nocitev(osebe[23], cilji[5], 2005),
            new Tretja.Nocitev(osebe[33], cilji[33], 2017),
            new Tretja.Nocitev(osebe[28], cilji[35], 2015),
            new Tretja.Nocitev(osebe[10], cilji[2], 2005),
            new Tretja.Nocitev(osebe[24], cilji[1], 2017),
            new Tretja.Nocitev(osebe[19], cilji[32], 2012),
            new Tretja.Nocitev(osebe[6], cilji[6], 2020),
            new Tretja.Nocitev(osebe[19], cilji[32], 2007),
            new Tretja.Nocitev(osebe[31], cilji[32], 2017),
            new Tretja.Nocitev(osebe[14], cilji[26], 2014),
            new Tretja.Nocitev(osebe[4], cilji[22], 2010),
            new Tretja.Nocitev(osebe[14], cilji[2], 2010),
            new Tretja.Nocitev(osebe[35], cilji[2], 2004),
            new Tretja.Nocitev(osebe[12], cilji[8], 2019),
            new Tretja.Nocitev(osebe[22], cilji[23], 2012),
            new Tretja.Nocitev(osebe[34], cilji[19], 2012),
            new Tretja.Nocitev(osebe[4], cilji[22], 2008),
            new Tretja.Nocitev(osebe[4], cilji[22], 2009),
            new Tretja.Nocitev(osebe[31], cilji[32], 2006),
            new Tretja.Nocitev(osebe[12], cilji[21], 2010),
            new Tretja.Nocitev(osebe[21], cilji[26], 2017),
            new Tretja.Nocitev(osebe[22], cilji[31], 2015),
            new Tretja.Nocitev(osebe[16], cilji[13], 2006),
            new Tretja.Nocitev(osebe[34], cilji[19], 2017),
            new Tretja.Nocitev(osebe[36], cilji[10], 2013),
            new Tretja.Nocitev(osebe[17], cilji[12], 2015),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
