
public class Test37 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Thqb Wgaw", "Sohb"),
            new Tretja.Oseba("Qibj Eyza", "Bbpa"),
            new Tretja.Oseba("Hbhk Unij", "Bbpa"),
            new Tretja.Oseba("Wuck Ddrh", "Bbpa"),
            new Tretja.Oseba("Hxsv Zyad", "Sohb"),
            new Tretja.Oseba("Fnlq Glwt", "Stdg"),
            new Tretja.Oseba("Dllj Zcxn", "Stdg"),
            new Tretja.Oseba("Cire Aqga", "Bbpa"),
            new Tretja.Oseba("Iqgk Nhhh", "Jgnz"),
            new Tretja.Oseba("Nakk Vtub", "Stdg"),
            new Tretja.Oseba("Tgqd Opli", "Jgnz"),
            new Tretja.Oseba("Cqca Txea", "Sohb"),
            new Tretja.Oseba("Fagc Bzqf", "Jgnz"),
            new Tretja.Oseba("Ykfb Aala", "Jgnz"),
            new Tretja.Oseba("Lmra Easd", "Sohb"),
            new Tretja.Oseba("Fkdw Aqqp", "Stdg"),
            new Tretja.Oseba("Ylly Njtv", "Jgnz"),
            new Tretja.Oseba("Msfp Igvv", "Stdg"),
            new Tretja.Oseba("Ddja Ajsw", "Jgnz"),
            new Tretja.Oseba("Hedv Tkxh", "Bbpa"),
            new Tretja.Oseba("Vffm Zqit", "Sohb"),
            new Tretja.Oseba("Djbp Gqjb", "Sohb"),
            new Tretja.Oseba("Pjsv Xpcl", "Jgnz"),
            new Tretja.Oseba("Zgxn Fbgw", "Stdg"),
            new Tretja.Oseba("Xmud Bshj", "Stdg"),
            new Tretja.Oseba("Fefh Cfbt", "Sohb"),
            new Tretja.Oseba("Zjns Lrke", "Bbpa"),
            new Tretja.Oseba("Tutv Octr", "Stdg"),
            new Tretja.Oseba("Qqhj Ihqy", "Stdg"),
            new Tretja.Oseba("Xlnb Cvrt", "Bbpa"),
            new Tretja.Oseba("Izoy Rxdj", "Jgnz"),
            new Tretja.Oseba("Bkpt Wljc", "Sohb"),
            new Tretja.Oseba("Kkyt Fxxf", "Sohb"),
            new Tretja.Oseba("Oxve Abgl", "Sohb"),
            new Tretja.Oseba("Jddd Lezp", "Bbpa"),
            new Tretja.Oseba("Sbdp Chtt", "Jgnz"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Dhuo", "Stdg"),
            new Tretja.Cilj("Dhoe", "Jgnz"),
            new Tretja.Cilj("Rgix", "Jgnz"),
            new Tretja.Cilj("Lydj", "Stdg"),
            new Tretja.Cilj("Meka", "Sohb"),
            new Tretja.Cilj("Ttxn", "Sohb"),
            new Tretja.Cilj("Lsjp", "Jgnz"),
            new Tretja.Cilj("Pjzt", "Jgnz"),
            new Tretja.Cilj("Qawa", "Bbpa"),
            new Tretja.Cilj("Whuq", "Sohb"),
            new Tretja.Cilj("Yxxd", "Jgnz"),
            new Tretja.Cilj("Qklg", "Stdg"),
            new Tretja.Cilj("Xueh", "Stdg"),
            new Tretja.Cilj("Qjqp", "Bbpa"),
            new Tretja.Cilj("Ijwy", "Jgnz"),
            new Tretja.Cilj("Vtqr", "Stdg"),
            new Tretja.Cilj("Nwgn", "Bbpa"),
            new Tretja.Cilj("Vrcs", "Stdg"),
            new Tretja.Cilj("Qlha", "Bbpa"),
            new Tretja.Cilj("Okfp", "Sohb"),
            new Tretja.Cilj("Zdsh", "Bbpa"),
            new Tretja.Cilj("Ngrw", "Stdg"),
            new Tretja.Cilj("Jati", "Bbpa"),
            new Tretja.Cilj("Fare", "Jgnz"),
            new Tretja.Cilj("Zwiq", "Bbpa"),
            new Tretja.Cilj("Pkdg", "Sohb"),
            new Tretja.Cilj("Iebb", "Stdg"),
            new Tretja.Cilj("Zzdr", "Stdg"),
            new Tretja.Cilj("Kfkd", "Bbpa"),
            new Tretja.Cilj("Iaxv", "Bbpa"),
            new Tretja.Cilj("Autq", "Bbpa"),
            new Tretja.Cilj("Ehog", "Stdg"),
            new Tretja.Cilj("Gbff", "Stdg"),
            new Tretja.Cilj("Omas", "Bbpa"),
            new Tretja.Cilj("Rvtq", "Sohb"),
            new Tretja.Cilj("Ihkv", "Jgnz"),
            new Tretja.Cilj("Dict", "Stdg"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[5], cilji[36], 2014),
            new Tretja.Nocitev(osebe[30], cilji[21], 2015),
            new Tretja.Nocitev(osebe[28], cilji[9], 2018),
            new Tretja.Nocitev(osebe[4], cilji[3], 2002),
            new Tretja.Nocitev(osebe[21], cilji[27], 2013),
            new Tretja.Nocitev(osebe[14], cilji[8], 2015),
            new Tretja.Nocitev(osebe[30], cilji[21], 2000),
            new Tretja.Nocitev(osebe[16], cilji[1], 2013),
            new Tretja.Nocitev(osebe[28], cilji[9], 2002),
            new Tretja.Nocitev(osebe[14], cilji[15], 2007),
            new Tretja.Nocitev(osebe[16], cilji[1], 2008),
            new Tretja.Nocitev(osebe[32], cilji[12], 2012),
            new Tretja.Nocitev(osebe[6], cilji[2], 2007),
            new Tretja.Nocitev(osebe[12], cilji[8], 2006),
            new Tretja.Nocitev(osebe[3], cilji[11], 2010),
            new Tretja.Nocitev(osebe[21], cilji[27], 2011),
            new Tretja.Nocitev(osebe[30], cilji[21], 2020),
            new Tretja.Nocitev(osebe[16], cilji[1], 2009),
            new Tretja.Nocitev(osebe[17], cilji[28], 2004),
            new Tretja.Nocitev(osebe[25], cilji[33], 2014),
            new Tretja.Nocitev(osebe[21], cilji[27], 2011),
            new Tretja.Nocitev(osebe[21], cilji[27], 2015),
            new Tretja.Nocitev(osebe[14], cilji[10], 2017),
            new Tretja.Nocitev(osebe[17], cilji[28], 2000),
            new Tretja.Nocitev(osebe[3], cilji[29], 2002),
            new Tretja.Nocitev(osebe[27], cilji[0], 2008),
            new Tretja.Nocitev(osebe[10], cilji[1], 2013),
            new Tretja.Nocitev(osebe[15], cilji[28], 2018),
            new Tretja.Nocitev(osebe[8], cilji[32], 2005),
            new Tretja.Nocitev(osebe[21], cilji[27], 2017),
            new Tretja.Nocitev(osebe[6], cilji[34], 2000),
            new Tretja.Nocitev(osebe[8], cilji[32], 2009),
            new Tretja.Nocitev(osebe[19], cilji[21], 2014),
            new Tretja.Nocitev(osebe[23], cilji[0], 2019),
            new Tretja.Nocitev(osebe[14], cilji[2], 2000),
            new Tretja.Nocitev(osebe[15], cilji[28], 2006),
            new Tretja.Nocitev(osebe[32], cilji[28], 2002),
            new Tretja.Nocitev(osebe[21], cilji[27], 2009),
            new Tretja.Nocitev(osebe[4], cilji[34], 2020),
            new Tretja.Nocitev(osebe[6], cilji[17], 2020),
            new Tretja.Nocitev(osebe[32], cilji[34], 2002),
            new Tretja.Nocitev(osebe[7], cilji[28], 2015),
            new Tretja.Nocitev(osebe[33], cilji[7], 2006),
            new Tretja.Nocitev(osebe[32], cilji[25], 2019),
            new Tretja.Nocitev(osebe[31], cilji[2], 2014),
            new Tretja.Nocitev(osebe[20], cilji[30], 2018),
            new Tretja.Nocitev(osebe[4], cilji[9], 2004),
            new Tretja.Nocitev(osebe[34], cilji[32], 2010),
            new Tretja.Nocitev(osebe[29], cilji[10], 2001),
            new Tretja.Nocitev(osebe[25], cilji[31], 2019),
            new Tretja.Nocitev(osebe[5], cilji[36], 2019),
            new Tretja.Nocitev(osebe[21], cilji[27], 2004),
            new Tretja.Nocitev(osebe[24], cilji[2], 2002),
            new Tretja.Nocitev(osebe[9], cilji[10], 2016),
            new Tretja.Nocitev(osebe[29], cilji[8], 2010),
            new Tretja.Nocitev(osebe[15], cilji[28], 2000),
            new Tretja.Nocitev(osebe[20], cilji[16], 2007),
            new Tretja.Nocitev(osebe[15], cilji[28], 2012),
            new Tretja.Nocitev(osebe[15], cilji[28], 2011),
            new Tretja.Nocitev(osebe[10], cilji[11], 2000),
            new Tretja.Nocitev(osebe[25], cilji[34], 2006),
            new Tretja.Nocitev(osebe[12], cilji[8], 2003),
            new Tretja.Nocitev(osebe[22], cilji[25], 2001),
            new Tretja.Nocitev(osebe[31], cilji[0], 2000),
            new Tretja.Nocitev(osebe[18], cilji[3], 2016),
            new Tretja.Nocitev(osebe[30], cilji[21], 2001),
            new Tretja.Nocitev(osebe[29], cilji[0], 2001),
            new Tretja.Nocitev(osebe[20], cilji[14], 2017),
            new Tretja.Nocitev(osebe[29], cilji[30], 2005),
            new Tretja.Nocitev(osebe[28], cilji[9], 2020),
            new Tretja.Nocitev(osebe[26], cilji[16], 2016),
            new Tretja.Nocitev(osebe[33], cilji[26], 2005),
            new Tretja.Nocitev(osebe[18], cilji[29], 2000),
            new Tretja.Nocitev(osebe[17], cilji[28], 2009),
            new Tretja.Nocitev(osebe[20], cilji[21], 2014),
            new Tretja.Nocitev(osebe[33], cilji[9], 2010),
            new Tretja.Nocitev(osebe[18], cilji[24], 2000),
            new Tretja.Nocitev(osebe[35], cilji[8], 2006),
            new Tretja.Nocitev(osebe[35], cilji[24], 2014),
            new Tretja.Nocitev(osebe[5], cilji[36], 2011),
            new Tretja.Nocitev(osebe[26], cilji[16], 2014),
            new Tretja.Nocitev(osebe[28], cilji[9], 2011),
            new Tretja.Nocitev(osebe[32], cilji[22], 2001),
            new Tretja.Nocitev(osebe[32], cilji[11], 2006),
            new Tretja.Nocitev(osebe[34], cilji[36], 2010),
            new Tretja.Nocitev(osebe[26], cilji[16], 2006),
            new Tretja.Nocitev(osebe[30], cilji[21], 2003),
            new Tretja.Nocitev(osebe[34], cilji[28], 2005),
            new Tretja.Nocitev(osebe[21], cilji[27], 2010),
            new Tretja.Nocitev(osebe[27], cilji[0], 2017),
            new Tretja.Nocitev(osebe[30], cilji[21], 2011),
            new Tretja.Nocitev(osebe[31], cilji[27], 2010),
            new Tretja.Nocitev(osebe[33], cilji[30], 2015),
            new Tretja.Nocitev(osebe[18], cilji[34], 2014),
            new Tretja.Nocitev(osebe[10], cilji[13], 2018),
            new Tretja.Nocitev(osebe[0], cilji[20], 2007),
            new Tretja.Nocitev(osebe[32], cilji[25], 2011),
            new Tretja.Nocitev(osebe[0], cilji[20], 2016),
            new Tretja.Nocitev(osebe[6], cilji[23], 2007),
            new Tretja.Nocitev(osebe[2], cilji[36], 2016),
            new Tretja.Nocitev(osebe[12], cilji[8], 2006),
            new Tretja.Nocitev(osebe[24], cilji[2], 2009),
            new Tretja.Nocitev(osebe[20], cilji[1], 2005),
            new Tretja.Nocitev(osebe[28], cilji[9], 2020),
            new Tretja.Nocitev(osebe[0], cilji[20], 2005),
            new Tretja.Nocitev(osebe[7], cilji[28], 2007),
            new Tretja.Nocitev(osebe[7], cilji[28], 2003),
            new Tretja.Nocitev(osebe[1], cilji[16], 2011),
            new Tretja.Nocitev(osebe[30], cilji[21], 2002),
            new Tretja.Nocitev(osebe[22], cilji[25], 2017),
            new Tretja.Nocitev(osebe[27], cilji[0], 2003),
            new Tretja.Nocitev(osebe[35], cilji[32], 2005),
            new Tretja.Nocitev(osebe[18], cilji[13], 2012),
            new Tretja.Nocitev(osebe[24], cilji[2], 2008),
            new Tretja.Nocitev(osebe[22], cilji[25], 2008),
            new Tretja.Nocitev(osebe[8], cilji[32], 2015),
            new Tretja.Nocitev(osebe[31], cilji[28], 2005),
            new Tretja.Nocitev(osebe[7], cilji[28], 2002),
            new Tretja.Nocitev(osebe[20], cilji[31], 2004),
            new Tretja.Nocitev(osebe[21], cilji[27], 2012),
            new Tretja.Nocitev(osebe[9], cilji[25], 2006),
            new Tretja.Nocitev(osebe[27], cilji[0], 2011),
            new Tretja.Nocitev(osebe[1], cilji[1], 2011),
            new Tretja.Nocitev(osebe[22], cilji[25], 2001),
            new Tretja.Nocitev(osebe[34], cilji[9], 2018),
            new Tretja.Nocitev(osebe[27], cilji[0], 2008),
            new Tretja.Nocitev(osebe[22], cilji[25], 2000),
            new Tretja.Nocitev(osebe[30], cilji[21], 2013),
            new Tretja.Nocitev(osebe[24], cilji[2], 2001),
            new Tretja.Nocitev(osebe[29], cilji[34], 2018),
            new Tretja.Nocitev(osebe[24], cilji[2], 2010),
            new Tretja.Nocitev(osebe[19], cilji[21], 2011),
            new Tretja.Nocitev(osebe[35], cilji[19], 2004),
            new Tretja.Nocitev(osebe[34], cilji[19], 2010),
            new Tretja.Nocitev(osebe[11], cilji[28], 2010),
            new Tretja.Nocitev(osebe[2], cilji[19], 2012),
            new Tretja.Nocitev(osebe[12], cilji[8], 2020),
            new Tretja.Nocitev(osebe[13], cilji[14], 2010),
            new Tretja.Nocitev(osebe[2], cilji[7], 2020),
            new Tretja.Nocitev(osebe[17], cilji[28], 2015),
            new Tretja.Nocitev(osebe[15], cilji[28], 2014),
            new Tretja.Nocitev(osebe[6], cilji[26], 2000),
            new Tretja.Nocitev(osebe[30], cilji[21], 2000),
            new Tretja.Nocitev(osebe[24], cilji[2], 2003),
            new Tretja.Nocitev(osebe[15], cilji[28], 2017),
            new Tretja.Nocitev(osebe[30], cilji[21], 2016),
            new Tretja.Nocitev(osebe[16], cilji[1], 2016),
            new Tretja.Nocitev(osebe[7], cilji[28], 2017),
            new Tretja.Nocitev(osebe[29], cilji[22], 2007),
            new Tretja.Nocitev(osebe[30], cilji[21], 2019),
            new Tretja.Nocitev(osebe[3], cilji[20], 2001),
            new Tretja.Nocitev(osebe[8], cilji[32], 2012),
            new Tretja.Nocitev(osebe[7], cilji[28], 2002),
            new Tretja.Nocitev(osebe[2], cilji[32], 2003),
            new Tretja.Nocitev(osebe[13], cilji[14], 2013),
            new Tretja.Nocitev(osebe[15], cilji[28], 2016),
            new Tretja.Nocitev(osebe[8], cilji[32], 2017),
            new Tretja.Nocitev(osebe[34], cilji[11], 2001),
            new Tretja.Nocitev(osebe[4], cilji[33], 2001),
            new Tretja.Nocitev(osebe[25], cilji[11], 2016),
            new Tretja.Nocitev(osebe[23], cilji[35], 2002),
            new Tretja.Nocitev(osebe[12], cilji[8], 2010),
            new Tretja.Nocitev(osebe[33], cilji[32], 2013),
            new Tretja.Nocitev(osebe[30], cilji[21], 2015),
            new Tretja.Nocitev(osebe[29], cilji[22], 2015),
            new Tretja.Nocitev(osebe[19], cilji[21], 2002),
            new Tretja.Nocitev(osebe[4], cilji[26], 2018),
            new Tretja.Nocitev(osebe[17], cilji[28], 2000),
            new Tretja.Nocitev(osebe[11], cilji[28], 2003),
            new Tretja.Nocitev(osebe[16], cilji[1], 2008),
            new Tretja.Nocitev(osebe[17], cilji[28], 2013),
            new Tretja.Nocitev(osebe[35], cilji[13], 2002),
            new Tretja.Nocitev(osebe[0], cilji[20], 2018),
            new Tretja.Nocitev(osebe[8], cilji[32], 2018),
            new Tretja.Nocitev(osebe[31], cilji[22], 2002),
            new Tretja.Nocitev(osebe[32], cilji[20], 2007),
            new Tretja.Nocitev(osebe[11], cilji[28], 2018),
            new Tretja.Nocitev(osebe[26], cilji[16], 2012),
            new Tretja.Nocitev(osebe[12], cilji[8], 2016),
            new Tretja.Nocitev(osebe[4], cilji[35], 2010),
            new Tretja.Nocitev(osebe[7], cilji[28], 2013),
            new Tretja.Nocitev(osebe[23], cilji[15], 2006),
            new Tretja.Nocitev(osebe[1], cilji[22], 2010),
            new Tretja.Nocitev(osebe[4], cilji[1], 2007),
            new Tretja.Nocitev(osebe[11], cilji[28], 2005),
            new Tretja.Nocitev(osebe[11], cilji[28], 2017),
            new Tretja.Nocitev(osebe[29], cilji[6], 2002),
            new Tretja.Nocitev(osebe[27], cilji[0], 2018),
            new Tretja.Nocitev(osebe[6], cilji[22], 2004),
            new Tretja.Nocitev(osebe[3], cilji[24], 2009),
            new Tretja.Nocitev(osebe[13], cilji[14], 2018),
            new Tretja.Nocitev(osebe[32], cilji[18], 2009),
            new Tretja.Nocitev(osebe[3], cilji[2], 2006),
            new Tretja.Nocitev(osebe[26], cilji[16], 2001),
            new Tretja.Nocitev(osebe[7], cilji[28], 2005),
            new Tretja.Nocitev(osebe[4], cilji[9], 2019),
            new Tretja.Nocitev(osebe[13], cilji[14], 2003),
            new Tretja.Nocitev(osebe[3], cilji[11], 2009),
            new Tretja.Nocitev(osebe[3], cilji[12], 2008),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2005, 2008);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
