
public class Test43 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Wfpu Ffnn", "Wfwl"),
            new Tretja.Oseba("Fdgl Fnlo", "Blfi"),
            new Tretja.Oseba("Vwcf Zrza", "Wfwl"),
            new Tretja.Oseba("Udqw Mjbb", "Voyv"),
            new Tretja.Oseba("Srxw Oroe", "Voyv"),
            new Tretja.Oseba("Vikl Tgng", "Blfi"),
            new Tretja.Oseba("Oivm Efv", "Voyv"),
            new Tretja.Oseba("Jmua Apwq", "Blfi"),
            new Tretja.Oseba("Pbkg Qqpr", "Blfi"),
            new Tretja.Oseba("Wxrc Lxtg", "Wfwl"),
            new Tretja.Oseba("Qiuu Srt", "Wfwl"),
            new Tretja.Oseba("Ayfs Cqfj", "Voyv"),
            new Tretja.Oseba("Rhov Chjb", "Wfwl"),
            new Tretja.Oseba("Nfod Meud", "Wfwl"),
            new Tretja.Oseba("Zjj Xajx", "Voyv"),
            new Tretja.Oseba("Sihc Nxlh", "Voyv"),
            new Tretja.Oseba("Jkit Ndwk", "Wfwl"),
            new Tretja.Oseba("Yofa Vtme", "Voyv"),
            new Tretja.Oseba("Bvhi Pdds", "Blfi"),
            new Tretja.Oseba("Cshn Jgwi", "Blfi"),
            new Tretja.Oseba("Bzni Xwhy", "Blfi"),
            new Tretja.Oseba("Ktnu Qtfy", "Blfi"),
            new Tretja.Oseba("Phmy Bbft", "Blfi"),
            new Tretja.Oseba("Npdw Ihtd", "Blfi"),
            new Tretja.Oseba("Vori Ywnj", "Blfi"),
            new Tretja.Oseba("Hgdj Jppk", "Blfi"),
            new Tretja.Oseba("Tauo Oewx", "Voyv"),
            new Tretja.Oseba("Ujqh Kgoz", "Wfwl"),
            new Tretja.Oseba("Tjjt Rdgj", "Voyv"),
            new Tretja.Oseba("Wkpy Ayzp", "Voyv"),
            new Tretja.Oseba("Rjwb Xvnz", "Voyv"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Wvfi", "Wfwl"),
            new Tretja.Cilj("Udok", "Voyv"),
            new Tretja.Cilj("Hkhn", "Wfwl"),
            new Tretja.Cilj("Ywtp", "Wfwl"),
            new Tretja.Cilj("Stfx", "Wfwl"),
            new Tretja.Cilj("Vrtn", "Blfi"),
            new Tretja.Cilj("Pkse", "Voyv"),
            new Tretja.Cilj("Ipws", "Wfwl"),
            new Tretja.Cilj("Okgz", "Voyv"),
            new Tretja.Cilj("Klgu", "Voyv"),
            new Tretja.Cilj("Ublh", "Wfwl"),
            new Tretja.Cilj("Fzkb", "Voyv"),
            new Tretja.Cilj("Rgip", "Blfi"),
            new Tretja.Cilj("Nlrq", "Wfwl"),
            new Tretja.Cilj("Yzyr", "Blfi"),
            new Tretja.Cilj("Zamo", "Voyv"),
            new Tretja.Cilj("Udtd", "Blfi"),
            new Tretja.Cilj("Vgqm", "Blfi"),
            new Tretja.Cilj("Nmbx", "Wfwl"),
            new Tretja.Cilj("Qsvc", "Blfi"),
            new Tretja.Cilj("Uud", "Voyv"),
            new Tretja.Cilj("Ynwz", "Voyv"),
            new Tretja.Cilj("Lrda", "Blfi"),
            new Tretja.Cilj("Zcvj", "Blfi"),
            new Tretja.Cilj("Kjfe", "Blfi"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[1], cilji[15], 2013),
            new Tretja.Nocitev(osebe[27], cilji[2], 2015),
            new Tretja.Nocitev(osebe[0], cilji[22], 2017),
            new Tretja.Nocitev(osebe[22], cilji[10], 2013),
            new Tretja.Nocitev(osebe[25], cilji[7], 2001),
            new Tretja.Nocitev(osebe[6], cilji[13], 2008),
            new Tretja.Nocitev(osebe[16], cilji[21], 2000),
            new Tretja.Nocitev(osebe[24], cilji[22], 2003),
            new Tretja.Nocitev(osebe[1], cilji[15], 2007),
            new Tretja.Nocitev(osebe[19], cilji[3], 2001),
            new Tretja.Nocitev(osebe[22], cilji[23], 2018),
            new Tretja.Nocitev(osebe[10], cilji[21], 2003),
            new Tretja.Nocitev(osebe[6], cilji[13], 2018),
            new Tretja.Nocitev(osebe[22], cilji[18], 2002),
            new Tretja.Nocitev(osebe[4], cilji[10], 2018),
            new Tretja.Nocitev(osebe[30], cilji[17], 2013),
            new Tretja.Nocitev(osebe[13], cilji[7], 2010),
            new Tretja.Nocitev(osebe[5], cilji[0], 2014),
            new Tretja.Nocitev(osebe[10], cilji[21], 2003),
            new Tretja.Nocitev(osebe[28], cilji[2], 2020),
            new Tretja.Nocitev(osebe[24], cilji[10], 2010),
            new Tretja.Nocitev(osebe[15], cilji[15], 2007),
            new Tretja.Nocitev(osebe[5], cilji[0], 2015),
            new Tretja.Nocitev(osebe[29], cilji[10], 2010),
            new Tretja.Nocitev(osebe[14], cilji[9], 2011),
            new Tretja.Nocitev(osebe[21], cilji[11], 2017),
            new Tretja.Nocitev(osebe[27], cilji[23], 2013),
            new Tretja.Nocitev(osebe[6], cilji[13], 2010),
            new Tretja.Nocitev(osebe[14], cilji[9], 2000),
            new Tretja.Nocitev(osebe[8], cilji[7], 2018),
            new Tretja.Nocitev(osebe[9], cilji[6], 2013),
            new Tretja.Nocitev(osebe[22], cilji[16], 2009),
            new Tretja.Nocitev(osebe[13], cilji[8], 2012),
            new Tretja.Nocitev(osebe[17], cilji[4], 2002),
            new Tretja.Nocitev(osebe[1], cilji[17], 2009),
            new Tretja.Nocitev(osebe[7], cilji[15], 2000),
            new Tretja.Nocitev(osebe[4], cilji[10], 2013),
            new Tretja.Nocitev(osebe[1], cilji[23], 2019),
            new Tretja.Nocitev(osebe[15], cilji[7], 2013),
            new Tretja.Nocitev(osebe[27], cilji[9], 2019),
            new Tretja.Nocitev(osebe[23], cilji[6], 2013),
            new Tretja.Nocitev(osebe[2], cilji[17], 2017),
            new Tretja.Nocitev(osebe[16], cilji[21], 2011),
            new Tretja.Nocitev(osebe[11], cilji[21], 2017),
            new Tretja.Nocitev(osebe[26], cilji[20], 2019),
            new Tretja.Nocitev(osebe[24], cilji[5], 2017),
            new Tretja.Nocitev(osebe[26], cilji[20], 2000),
            new Tretja.Nocitev(osebe[12], cilji[1], 2001),
            new Tretja.Nocitev(osebe[26], cilji[20], 2001),
            new Tretja.Nocitev(osebe[23], cilji[6], 2010),
            new Tretja.Nocitev(osebe[23], cilji[6], 2015),
            new Tretja.Nocitev(osebe[2], cilji[17], 2007),
            new Tretja.Nocitev(osebe[18], cilji[7], 2003),
            new Tretja.Nocitev(osebe[17], cilji[13], 2003),
            new Tretja.Nocitev(osebe[8], cilji[7], 2001),
            new Tretja.Nocitev(osebe[25], cilji[7], 2010),
            new Tretja.Nocitev(osebe[20], cilji[4], 2012),
            new Tretja.Nocitev(osebe[11], cilji[21], 2002),
            new Tretja.Nocitev(osebe[12], cilji[3], 2018),
            new Tretja.Nocitev(osebe[27], cilji[6], 2005),
            new Tretja.Nocitev(osebe[29], cilji[7], 2006),
            new Tretja.Nocitev(osebe[1], cilji[0], 2020),
            new Tretja.Nocitev(osebe[8], cilji[7], 2016),
            new Tretja.Nocitev(osebe[16], cilji[21], 2001),
            new Tretja.Nocitev(osebe[20], cilji[5], 2006),
            new Tretja.Nocitev(osebe[17], cilji[18], 2008),
            new Tretja.Nocitev(osebe[3], cilji[16], 2020),
            new Tretja.Nocitev(osebe[8], cilji[7], 2004),
            new Tretja.Nocitev(osebe[19], cilji[21], 2020),
            new Tretja.Nocitev(osebe[13], cilji[13], 2007),
            new Tretja.Nocitev(osebe[9], cilji[6], 2011),
            new Tretja.Nocitev(osebe[6], cilji[13], 2009),
            new Tretja.Nocitev(osebe[5], cilji[0], 2011),
            new Tretja.Nocitev(osebe[15], cilji[7], 2007),
            new Tretja.Nocitev(osebe[18], cilji[6], 2000),
            new Tretja.Nocitev(osebe[6], cilji[13], 2015),
            new Tretja.Nocitev(osebe[6], cilji[13], 2015),
            new Tretja.Nocitev(osebe[9], cilji[6], 2005),
            new Tretja.Nocitev(osebe[22], cilji[8], 2007),
            new Tretja.Nocitev(osebe[3], cilji[3], 2007),
            new Tretja.Nocitev(osebe[0], cilji[12], 2013),
            new Tretja.Nocitev(osebe[14], cilji[9], 2001),
            new Tretja.Nocitev(osebe[17], cilji[13], 2015),
            new Tretja.Nocitev(osebe[20], cilji[4], 2019),
            new Tretja.Nocitev(osebe[20], cilji[6], 2010),
            new Tretja.Nocitev(osebe[7], cilji[15], 2000),
            new Tretja.Nocitev(osebe[18], cilji[21], 2003),
            new Tretja.Nocitev(osebe[17], cilji[4], 2005),
            new Tretja.Nocitev(osebe[16], cilji[21], 2004),
            new Tretja.Nocitev(osebe[14], cilji[9], 2012),
            new Tretja.Nocitev(osebe[2], cilji[17], 2020),
            new Tretja.Nocitev(osebe[24], cilji[11], 2002),
            new Tretja.Nocitev(osebe[22], cilji[17], 2014),
            new Tretja.Nocitev(osebe[3], cilji[4], 2018),
            new Tretja.Nocitev(osebe[30], cilji[17], 2007),
            new Tretja.Nocitev(osebe[23], cilji[6], 2019),
            new Tretja.Nocitev(osebe[20], cilji[23], 2017),
            new Tretja.Nocitev(osebe[8], cilji[7], 2007),
            new Tretja.Nocitev(osebe[0], cilji[22], 2008),
            new Tretja.Nocitev(osebe[9], cilji[6], 2008),
            new Tretja.Nocitev(osebe[0], cilji[9], 2001),
            new Tretja.Nocitev(osebe[23], cilji[6], 2015),
            new Tretja.Nocitev(osebe[28], cilji[2], 2002),
            new Tretja.Nocitev(osebe[25], cilji[7], 2002),
            new Tretja.Nocitev(osebe[2], cilji[17], 2019),
            new Tretja.Nocitev(osebe[4], cilji[22], 2002),
            new Tretja.Nocitev(osebe[23], cilji[6], 2001),
            new Tretja.Nocitev(osebe[27], cilji[21], 2004),
            new Tretja.Nocitev(osebe[4], cilji[13], 2014),
            new Tretja.Nocitev(osebe[8], cilji[7], 2003),
            new Tretja.Nocitev(osebe[12], cilji[17], 2017),
            new Tretja.Nocitev(osebe[5], cilji[0], 2017),
            new Tretja.Nocitev(osebe[20], cilji[15], 2009),
            new Tretja.Nocitev(osebe[27], cilji[22], 2003),
            new Tretja.Nocitev(osebe[5], cilji[0], 2020),
            new Tretja.Nocitev(osebe[14], cilji[9], 2011),
            new Tretja.Nocitev(osebe[29], cilji[9], 2003),
            new Tretja.Nocitev(osebe[0], cilji[1], 2016),
            new Tretja.Nocitev(osebe[17], cilji[19], 2012),
            new Tretja.Nocitev(osebe[27], cilji[20], 2002),
            new Tretja.Nocitev(osebe[6], cilji[13], 2000),
            new Tretja.Nocitev(osebe[7], cilji[15], 2016),
            new Tretja.Nocitev(osebe[18], cilji[17], 2006),
            new Tretja.Nocitev(osebe[30], cilji[17], 2019),
            new Tretja.Nocitev(osebe[4], cilji[2], 2004),
            new Tretja.Nocitev(osebe[29], cilji[12], 2005),
            new Tretja.Nocitev(osebe[2], cilji[17], 2018),
            new Tretja.Nocitev(osebe[19], cilji[2], 2020),
            new Tretja.Nocitev(osebe[25], cilji[7], 2000),
            new Tretja.Nocitev(osebe[12], cilji[13], 2017),
            new Tretja.Nocitev(osebe[8], cilji[7], 2016),
            new Tretja.Nocitev(osebe[25], cilji[7], 2010),
            new Tretja.Nocitev(osebe[28], cilji[2], 2020),
            new Tretja.Nocitev(osebe[29], cilji[8], 2009),
            new Tretja.Nocitev(osebe[15], cilji[13], 2004),
            new Tretja.Nocitev(osebe[21], cilji[11], 2004),
            new Tretja.Nocitev(osebe[5], cilji[0], 2020),
            new Tretja.Nocitev(osebe[4], cilji[21], 2014),
            new Tretja.Nocitev(osebe[1], cilji[22], 2017),
            new Tretja.Nocitev(osebe[13], cilji[4], 2003),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2007, 2019);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
