
public class Test39 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Wdfd Wfhj", "Xdyx"),
            new Tretja.Oseba("Jcmw Slff", "Zjco"),
            new Tretja.Oseba("Vzkt Qigp", "Xdyx"),
            new Tretja.Oseba("Zkeg Wfss", "Zjco"),
            new Tretja.Oseba("Miqj Aauu", "Xdyx"),
            new Tretja.Oseba("Jnam Mjx", "Xdyx"),
            new Tretja.Oseba("Aepd Ygbu", "Xdyx"),
            new Tretja.Oseba("Rpfi Gsxf", "Zjco"),
            new Tretja.Oseba("Mndf Ruy", "Zjco"),
            new Tretja.Oseba("Eehl Wifb", "Xdyx"),
            new Tretja.Oseba("Raqc Awwv", "Xdyx"),
            new Tretja.Oseba("Fmff Zjst", "Zjco"),
            new Tretja.Oseba("Mwoz Xfux", "Xdyx"),
            new Tretja.Oseba("Qubk Idl", "Zjco"),
            new Tretja.Oseba("Cmgs Jixx", "Xdyx"),
            new Tretja.Oseba("Ysux Nrci", "Xdyx"),
            new Tretja.Oseba("Coev Sbfq", "Zjco"),
            new Tretja.Oseba("Bpvp Hsyl", "Zjco"),
            new Tretja.Oseba("Qmlz Pjhg", "Zjco"),
            new Tretja.Oseba("Jalo Meyi", "Zjco"),
            new Tretja.Oseba("Tqlq Pilg", "Xdyx"),
            new Tretja.Oseba("Muui Fmbx", "Xdyx"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Zmeb", "Xdyx"),
            new Tretja.Cilj("Dmmp", "Xdyx"),
            new Tretja.Cilj("Zpfx", "Zjco"),
            new Tretja.Cilj("Tsdd", "Xdyx"),
            new Tretja.Cilj("Bugx", "Xdyx"),
            new Tretja.Cilj("Imjj", "Xdyx"),
            new Tretja.Cilj("Grqc", "Xdyx"),
            new Tretja.Cilj("Lrnl", "Zjco"),
            new Tretja.Cilj("Kmzd", "Zjco"),
            new Tretja.Cilj("Pjsu", "Xdyx"),
            new Tretja.Cilj("Jgyi", "Xdyx"),
            new Tretja.Cilj("Qecb", "Xdyx"),
            new Tretja.Cilj("Pivl", "Zjco"),
            new Tretja.Cilj("Mqzs", "Xdyx"),
            new Tretja.Cilj("Gnyp", "Xdyx"),
            new Tretja.Cilj("Dtmq", "Zjco"),
            new Tretja.Cilj("Tpht", "Xdyx"),
            new Tretja.Cilj("Thct", "Zjco"),
            new Tretja.Cilj("Heuy", "Zjco"),
            new Tretja.Cilj("Kj", "Xdyx"),
            new Tretja.Cilj("Tmhv", "Xdyx"),
            new Tretja.Cilj("Owsk", "Zjco"),
            new Tretja.Cilj("Zetn", "Zjco"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[5], cilji[10], 2008),
            new Tretja.Nocitev(osebe[17], cilji[0], 2014),
            new Tretja.Nocitev(osebe[1], cilji[12], 2008),
            new Tretja.Nocitev(osebe[0], cilji[3], 2011),
            new Tretja.Nocitev(osebe[18], cilji[19], 2004),
            new Tretja.Nocitev(osebe[19], cilji[15], 2016),
            new Tretja.Nocitev(osebe[11], cilji[9], 2007),
            new Tretja.Nocitev(osebe[12], cilji[16], 2010),
            new Tretja.Nocitev(osebe[0], cilji[14], 2000),
            new Tretja.Nocitev(osebe[0], cilji[8], 2002),
            new Tretja.Nocitev(osebe[12], cilji[5], 2014),
            new Tretja.Nocitev(osebe[21], cilji[14], 2001),
            new Tretja.Nocitev(osebe[15], cilji[11], 2011),
            new Tretja.Nocitev(osebe[16], cilji[8], 2002),
            new Tretja.Nocitev(osebe[17], cilji[14], 2009),
            new Tretja.Nocitev(osebe[13], cilji[22], 2016),
            new Tretja.Nocitev(osebe[13], cilji[22], 2002),
            new Tretja.Nocitev(osebe[8], cilji[4], 2008),
            new Tretja.Nocitev(osebe[11], cilji[9], 2013),
            new Tretja.Nocitev(osebe[11], cilji[9], 2007),
            new Tretja.Nocitev(osebe[18], cilji[19], 2015),
            new Tretja.Nocitev(osebe[10], cilji[6], 2008),
            new Tretja.Nocitev(osebe[3], cilji[12], 2017),
            new Tretja.Nocitev(osebe[0], cilji[22], 2005),
            new Tretja.Nocitev(osebe[2], cilji[17], 2016),
            new Tretja.Nocitev(osebe[19], cilji[15], 2003),
            new Tretja.Nocitev(osebe[9], cilji[9], 2003),
            new Tretja.Nocitev(osebe[0], cilji[18], 2015),
            new Tretja.Nocitev(osebe[19], cilji[15], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2010),
            new Tretja.Nocitev(osebe[16], cilji[8], 2003),
            new Tretja.Nocitev(osebe[10], cilji[15], 2017),
            new Tretja.Nocitev(osebe[10], cilji[12], 2005),
            new Tretja.Nocitev(osebe[5], cilji[8], 2001),
            new Tretja.Nocitev(osebe[19], cilji[15], 2016),
            new Tretja.Nocitev(osebe[1], cilji[12], 2001),
            new Tretja.Nocitev(osebe[15], cilji[11], 2009),
            new Tretja.Nocitev(osebe[3], cilji[12], 2017),
            new Tretja.Nocitev(osebe[9], cilji[12], 2014),
            new Tretja.Nocitev(osebe[18], cilji[19], 2017),
            new Tretja.Nocitev(osebe[5], cilji[12], 2010),
            new Tretja.Nocitev(osebe[20], cilji[10], 2013),
            new Tretja.Nocitev(osebe[14], cilji[19], 2012),
            new Tretja.Nocitev(osebe[6], cilji[17], 2007),
            new Tretja.Nocitev(osebe[12], cilji[15], 2015),
            new Tretja.Nocitev(osebe[17], cilji[17], 2013),
            new Tretja.Nocitev(osebe[3], cilji[12], 2018),
            new Tretja.Nocitev(osebe[4], cilji[22], 2013),
            new Tretja.Nocitev(osebe[5], cilji[14], 2011),
            new Tretja.Nocitev(osebe[12], cilji[17], 2012),
            new Tretja.Nocitev(osebe[15], cilji[11], 2016),
            new Tretja.Nocitev(osebe[5], cilji[9], 2012),
            new Tretja.Nocitev(osebe[21], cilji[14], 2002),
            new Tretja.Nocitev(osebe[0], cilji[20], 2015),
            new Tretja.Nocitev(osebe[5], cilji[9], 2020),
            new Tretja.Nocitev(osebe[10], cilji[17], 2009),
            new Tretja.Nocitev(osebe[6], cilji[5], 2002),
            new Tretja.Nocitev(osebe[19], cilji[15], 2008),
            new Tretja.Nocitev(osebe[20], cilji[17], 2005),
            new Tretja.Nocitev(osebe[4], cilji[22], 2013),
            new Tretja.Nocitev(osebe[7], cilji[6], 2004),
            new Tretja.Nocitev(osebe[8], cilji[9], 2009),
            new Tretja.Nocitev(osebe[11], cilji[9], 2020),
            new Tretja.Nocitev(osebe[10], cilji[10], 2019),
            new Tretja.Nocitev(osebe[3], cilji[12], 2001),
            new Tretja.Nocitev(osebe[14], cilji[4], 2008),
            new Tretja.Nocitev(osebe[2], cilji[20], 2014),
            new Tretja.Nocitev(osebe[2], cilji[4], 2019),
            new Tretja.Nocitev(osebe[15], cilji[11], 2009),
            new Tretja.Nocitev(osebe[3], cilji[12], 2012),
            new Tretja.Nocitev(osebe[2], cilji[5], 2014),
            new Tretja.Nocitev(osebe[1], cilji[12], 2011),
            new Tretja.Nocitev(osebe[12], cilji[0], 2015),
            new Tretja.Nocitev(osebe[18], cilji[19], 2016),
            new Tretja.Nocitev(osebe[3], cilji[12], 2002),
            new Tretja.Nocitev(osebe[3], cilji[12], 2011),
            new Tretja.Nocitev(osebe[12], cilji[14], 2003),
            new Tretja.Nocitev(osebe[19], cilji[15], 2015),
            new Tretja.Nocitev(osebe[10], cilji[1], 2003),
            new Tretja.Nocitev(osebe[13], cilji[22], 2017),
            new Tretja.Nocitev(osebe[17], cilji[12], 2007),
            new Tretja.Nocitev(osebe[5], cilji[4], 2003),
            new Tretja.Nocitev(osebe[1], cilji[12], 2008),
            new Tretja.Nocitev(osebe[0], cilji[12], 2007),
            new Tretja.Nocitev(osebe[16], cilji[8], 2018),
            new Tretja.Nocitev(osebe[18], cilji[19], 2014),
            new Tretja.Nocitev(osebe[1], cilji[12], 2000),
            new Tretja.Nocitev(osebe[1], cilji[12], 2004),
            new Tretja.Nocitev(osebe[17], cilji[12], 2015),
            new Tretja.Nocitev(osebe[16], cilji[8], 2006),
            new Tretja.Nocitev(osebe[1], cilji[12], 2018),
            new Tretja.Nocitev(osebe[15], cilji[11], 2016),
            new Tretja.Nocitev(osebe[3], cilji[12], 2007),
            new Tretja.Nocitev(osebe[9], cilji[4], 2000),
            new Tretja.Nocitev(osebe[17], cilji[21], 2006),
            new Tretja.Nocitev(osebe[10], cilji[12], 2007),
            new Tretja.Nocitev(osebe[16], cilji[8], 2016),
            new Tretja.Nocitev(osebe[14], cilji[12], 2001),
            new Tretja.Nocitev(osebe[0], cilji[13], 2015),
            new Tretja.Nocitev(osebe[18], cilji[19], 2016),
            new Tretja.Nocitev(osebe[13], cilji[22], 2000),
            new Tretja.Nocitev(osebe[8], cilji[18], 2001),
            new Tretja.Nocitev(osebe[0], cilji[21], 2009),
            new Tretja.Nocitev(osebe[10], cilji[3], 2000),
            new Tretja.Nocitev(osebe[0], cilji[12], 2020),
            new Tretja.Nocitev(osebe[4], cilji[22], 2013),
            new Tretja.Nocitev(osebe[21], cilji[14], 2014),
            new Tretja.Nocitev(osebe[7], cilji[6], 2020),
            new Tretja.Nocitev(osebe[20], cilji[12], 2006),
            new Tretja.Nocitev(osebe[5], cilji[6], 2016),
            new Tretja.Nocitev(osebe[10], cilji[22], 2020),
            new Tretja.Nocitev(osebe[10], cilji[6], 2001),
            new Tretja.Nocitev(osebe[4], cilji[22], 2015),
            new Tretja.Nocitev(osebe[15], cilji[11], 2016),
            new Tretja.Nocitev(osebe[5], cilji[0], 2016),
            new Tretja.Nocitev(osebe[14], cilji[1], 2002),
            new Tretja.Nocitev(osebe[17], cilji[7], 2017),
            new Tretja.Nocitev(osebe[18], cilji[19], 2000),
            new Tretja.Nocitev(osebe[11], cilji[9], 2013),
            new Tretja.Nocitev(osebe[14], cilji[22], 2019),
            new Tretja.Nocitev(osebe[9], cilji[6], 2014),
            new Tretja.Nocitev(osebe[17], cilji[20], 2020),
            new Tretja.Nocitev(osebe[6], cilji[20], 2000),
            new Tretja.Nocitev(osebe[4], cilji[22], 2010),
            new Tretja.Nocitev(osebe[17], cilji[9], 2011),
            new Tretja.Nocitev(osebe[12], cilji[19], 2016),
            new Tretja.Nocitev(osebe[20], cilji[3], 2010),
            new Tretja.Nocitev(osebe[12], cilji[22], 2007),
            new Tretja.Nocitev(osebe[21], cilji[14], 2006),
            new Tretja.Nocitev(osebe[11], cilji[9], 2009),
            new Tretja.Nocitev(osebe[12], cilji[17], 2020),
            new Tretja.Nocitev(osebe[18], cilji[19], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2012),
            new Tretja.Nocitev(osebe[21], cilji[14], 2000),
            new Tretja.Nocitev(osebe[13], cilji[22], 2008),
            new Tretja.Nocitev(osebe[3], cilji[12], 2011),
            new Tretja.Nocitev(osebe[10], cilji[20], 2000),
            new Tretja.Nocitev(osebe[3], cilji[12], 2016),
            new Tretja.Nocitev(osebe[14], cilji[2], 2014),
            new Tretja.Nocitev(osebe[3], cilji[12], 2005),
            new Tretja.Nocitev(osebe[17], cilji[2], 2005),
            new Tretja.Nocitev(osebe[14], cilji[15], 2015),
            new Tretja.Nocitev(osebe[2], cilji[20], 2004),
            new Tretja.Nocitev(osebe[5], cilji[11], 2004),
            new Tretja.Nocitev(osebe[6], cilji[4], 2018),
            new Tretja.Nocitev(osebe[13], cilji[22], 2016),
            new Tretja.Nocitev(osebe[21], cilji[14], 2005),
            new Tretja.Nocitev(osebe[5], cilji[9], 2009),
            new Tretja.Nocitev(osebe[11], cilji[9], 2000),
            new Tretja.Nocitev(osebe[6], cilji[12], 2017),
            new Tretja.Nocitev(osebe[2], cilji[16], 2002),
            new Tretja.Nocitev(osebe[13], cilji[22], 2003),
            new Tretja.Nocitev(osebe[16], cilji[8], 2019),
            new Tretja.Nocitev(osebe[7], cilji[6], 2016),
            new Tretja.Nocitev(osebe[0], cilji[22], 2019),
            new Tretja.Nocitev(osebe[20], cilji[12], 2019),
            new Tretja.Nocitev(osebe[17], cilji[9], 2016),
            new Tretja.Nocitev(osebe[18], cilji[19], 2000),
            new Tretja.Nocitev(osebe[21], cilji[14], 2003),
            new Tretja.Nocitev(osebe[4], cilji[22], 2003),
            new Tretja.Nocitev(osebe[6], cilji[12], 2012),
            new Tretja.Nocitev(osebe[3], cilji[12], 2019),
            new Tretja.Nocitev(osebe[16], cilji[8], 2016),
            new Tretja.Nocitev(osebe[7], cilji[6], 2019),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2006, 2007);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
