
public class Test49 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Ygeg Rzzc", "Qijt"),
            new Tretja.Oseba("Fbjd Wday", "Xuah"),
            new Tretja.Oseba("Wdao Ltqp", "Xuah"),
            new Tretja.Oseba("Foiv Dgwx", "Timb"),
            new Tretja.Oseba("Eahl Nvva", "Xuah"),
            new Tretja.Oseba("Czsf Bfhf", "Mfdx"),
            new Tretja.Oseba("Asiu Maxa", "Qijt"),
            new Tretja.Oseba("Gqnw Idrx", "Qijt"),
            new Tretja.Oseba("Oupn Uijk", "Qijt"),
            new Tretja.Oseba("Ytmg Blob", "Qijt"),
            new Tretja.Oseba("Nuya Kzqi", "Mfdx"),
            new Tretja.Oseba("Rls Ihan", "Timb"),
            new Tretja.Oseba("Bttn Rkvp", "Qijt"),
            new Tretja.Oseba("Vxul Muez", "Timb"),
            new Tretja.Oseba("Rmuq Zyjm", "Xuah"),
            new Tretja.Oseba("Xgcv Uwcw", "Mfdx"),
            new Tretja.Oseba("Uanu Zsfx", "Mfdx"),
            new Tretja.Oseba("Djwo Cest", "Xuah"),
            new Tretja.Oseba("Ofxu Nfci", "Timb"),
            new Tretja.Oseba("Yuwo Aztx", "Timb"),
            new Tretja.Oseba("Dcxj Wmkq", "Xuah"),
            new Tretja.Oseba("Vfpy Zmxj", "Qijt"),
            new Tretja.Oseba("Cbxf Vavp", "Xuah"),
            new Tretja.Oseba("Aaan Tihb", "Timb"),
            new Tretja.Oseba("Ldum Plda", "Xuah"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Xiio", "Mfdx"),
            new Tretja.Cilj("Ykoq", "Timb"),
            new Tretja.Cilj("Expr", "Timb"),
            new Tretja.Cilj("Skn", "Xuah"),
            new Tretja.Cilj("Bwmb", "Timb"),
            new Tretja.Cilj("Zqdm", "Qijt"),
            new Tretja.Cilj("Pchj", "Qijt"),
            new Tretja.Cilj("Wcfj", "Mfdx"),
            new Tretja.Cilj("Tcbq", "Mfdx"),
            new Tretja.Cilj("Enoz", "Xuah"),
            new Tretja.Cilj("Lqcy", "Mfdx"),
            new Tretja.Cilj("Ziot", "Qijt"),
            new Tretja.Cilj("Pzzd", "Mfdx"),
            new Tretja.Cilj("Suzt", "Qijt"),
            new Tretja.Cilj("Tvvf", "Mfdx"),
            new Tretja.Cilj("Owzu", "Xuah"),
            new Tretja.Cilj("Siof", "Timb"),
            new Tretja.Cilj("Rhev", "Timb"),
            new Tretja.Cilj("Raez", "Timb"),
            new Tretja.Cilj("Noij", "Mfdx"),
            new Tretja.Cilj("Oucv", "Qijt"),
            new Tretja.Cilj("Cdtr", "Qijt"),
            new Tretja.Cilj("Fndb", "Mfdx"),
            new Tretja.Cilj("Sfxn", "Xuah"),
            new Tretja.Cilj("Fvqw", "Qijt"),
            new Tretja.Cilj("Hsiz", "Xuah"),
            new Tretja.Cilj("Ozyy", "Xuah"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[0], cilji[15], 2014),
            new Tretja.Nocitev(osebe[1], cilji[3], 2002),
            new Tretja.Nocitev(osebe[22], cilji[13], 2010),
            new Tretja.Nocitev(osebe[10], cilji[24], 2016),
            new Tretja.Nocitev(osebe[7], cilji[18], 2018),
            new Tretja.Nocitev(osebe[20], cilji[8], 2014),
            new Tretja.Nocitev(osebe[9], cilji[17], 2011),
            new Tretja.Nocitev(osebe[17], cilji[20], 2016),
            new Tretja.Nocitev(osebe[9], cilji[25], 2020),
            new Tretja.Nocitev(osebe[10], cilji[21], 2016),
            new Tretja.Nocitev(osebe[0], cilji[15], 2015),
            new Tretja.Nocitev(osebe[13], cilji[3], 2008),
            new Tretja.Nocitev(osebe[0], cilji[15], 2009),
            new Tretja.Nocitev(osebe[24], cilji[24], 2008),
            new Tretja.Nocitev(osebe[7], cilji[18], 2002),
            new Tretja.Nocitev(osebe[4], cilji[6], 2014),
            new Tretja.Nocitev(osebe[22], cilji[13], 2008),
            new Tretja.Nocitev(osebe[21], cilji[23], 2006),
            new Tretja.Nocitev(osebe[4], cilji[6], 2002),
            new Tretja.Nocitev(osebe[16], cilji[16], 2009),
            new Tretja.Nocitev(osebe[20], cilji[8], 2010),
            new Tretja.Nocitev(osebe[10], cilji[7], 2011),
            new Tretja.Nocitev(osebe[11], cilji[18], 2005),
            new Tretja.Nocitev(osebe[22], cilji[13], 2004),
            new Tretja.Nocitev(osebe[15], cilji[0], 2001),
            new Tretja.Nocitev(osebe[20], cilji[8], 2007),
            new Tretja.Nocitev(osebe[0], cilji[15], 2011),
            new Tretja.Nocitev(osebe[20], cilji[8], 2003),
            new Tretja.Nocitev(osebe[9], cilji[16], 2005),
            new Tretja.Nocitev(osebe[8], cilji[9], 2009),
            new Tretja.Nocitev(osebe[21], cilji[26], 2008),
            new Tretja.Nocitev(osebe[16], cilji[9], 2014),
            new Tretja.Nocitev(osebe[15], cilji[0], 2001),
            new Tretja.Nocitev(osebe[6], cilji[11], 2019),
            new Tretja.Nocitev(osebe[23], cilji[7], 2011),
            new Tretja.Nocitev(osebe[20], cilji[8], 2002),
            new Tretja.Nocitev(osebe[13], cilji[3], 2008),
            new Tretja.Nocitev(osebe[2], cilji[19], 2010),
            new Tretja.Nocitev(osebe[14], cilji[7], 2010),
            new Tretja.Nocitev(osebe[19], cilji[17], 2016),
            new Tretja.Nocitev(osebe[12], cilji[19], 2006),
            new Tretja.Nocitev(osebe[14], cilji[11], 2004),
            new Tretja.Nocitev(osebe[14], cilji[23], 2005),
            new Tretja.Nocitev(osebe[24], cilji[24], 2015),
            new Tretja.Nocitev(osebe[13], cilji[3], 2002),
            new Tretja.Nocitev(osebe[16], cilji[23], 2008),
            new Tretja.Nocitev(osebe[6], cilji[23], 2005),
            new Tretja.Nocitev(osebe[17], cilji[20], 2006),
            new Tretja.Nocitev(osebe[14], cilji[20], 2004),
            new Tretja.Nocitev(osebe[24], cilji[24], 2019),
            new Tretja.Nocitev(osebe[13], cilji[3], 2009),
            new Tretja.Nocitev(osebe[3], cilji[0], 2013),
            new Tretja.Nocitev(osebe[11], cilji[18], 2005),
            new Tretja.Nocitev(osebe[5], cilji[0], 2018),
            new Tretja.Nocitev(osebe[15], cilji[0], 2003),
            new Tretja.Nocitev(osebe[7], cilji[18], 2013),
            new Tretja.Nocitev(osebe[4], cilji[6], 2003),
            new Tretja.Nocitev(osebe[12], cilji[19], 2005),
            new Tretja.Nocitev(osebe[18], cilji[7], 2016),
            new Tretja.Nocitev(osebe[22], cilji[13], 2005),
            new Tretja.Nocitev(osebe[18], cilji[13], 2019),
            new Tretja.Nocitev(osebe[21], cilji[18], 2003),
            new Tretja.Nocitev(osebe[0], cilji[15], 2020),
            new Tretja.Nocitev(osebe[0], cilji[15], 2020),
            new Tretja.Nocitev(osebe[1], cilji[23], 2008),
            new Tretja.Nocitev(osebe[13], cilji[3], 2004),
            new Tretja.Nocitev(osebe[21], cilji[12], 2010),
            new Tretja.Nocitev(osebe[1], cilji[21], 2015),
            new Tretja.Nocitev(osebe[19], cilji[0], 2010),
            new Tretja.Nocitev(osebe[15], cilji[0], 2017),
            new Tretja.Nocitev(osebe[14], cilji[1], 2012),
            new Tretja.Nocitev(osebe[20], cilji[8], 2005),
            new Tretja.Nocitev(osebe[18], cilji[8], 2002),
            new Tretja.Nocitev(osebe[10], cilji[10], 2018),
            new Tretja.Nocitev(osebe[14], cilji[2], 2010),
            new Tretja.Nocitev(osebe[15], cilji[0], 2017),
            new Tretja.Nocitev(osebe[16], cilji[11], 2018),
            new Tretja.Nocitev(osebe[13], cilji[3], 2013),
            new Tretja.Nocitev(osebe[0], cilji[15], 2015),
            new Tretja.Nocitev(osebe[21], cilji[16], 2011),
            new Tretja.Nocitev(osebe[18], cilji[5], 2018),
            new Tretja.Nocitev(osebe[6], cilji[14], 2000),
            new Tretja.Nocitev(osebe[0], cilji[15], 2015),
            new Tretja.Nocitev(osebe[16], cilji[10], 2015),
            new Tretja.Nocitev(osebe[16], cilji[24], 2009),
            new Tretja.Nocitev(osebe[6], cilji[13], 2017),
            new Tretja.Nocitev(osebe[4], cilji[6], 2000),
            new Tretja.Nocitev(osebe[6], cilji[3], 2000),
            new Tretja.Nocitev(osebe[3], cilji[23], 2019),
            new Tretja.Nocitev(osebe[14], cilji[20], 2015),
            new Tretja.Nocitev(osebe[9], cilji[19], 2003),
            new Tretja.Nocitev(osebe[9], cilji[1], 2005),
            new Tretja.Nocitev(osebe[5], cilji[20], 2020),
            new Tretja.Nocitev(osebe[5], cilji[24], 2014),
            new Tretja.Nocitev(osebe[17], cilji[20], 2011),
            new Tretja.Nocitev(osebe[17], cilji[20], 2009),
            new Tretja.Nocitev(osebe[1], cilji[16], 2014),
            new Tretja.Nocitev(osebe[24], cilji[24], 2011),
            new Tretja.Nocitev(osebe[23], cilji[5], 2013),
            new Tretja.Nocitev(osebe[24], cilji[24], 2005),
            new Tretja.Nocitev(osebe[6], cilji[8], 2001),
            new Tretja.Nocitev(osebe[8], cilji[5], 2015),
            new Tretja.Nocitev(osebe[21], cilji[10], 2008),
            new Tretja.Nocitev(osebe[14], cilji[17], 2001),
            new Tretja.Nocitev(osebe[19], cilji[22], 2005),
            new Tretja.Nocitev(osebe[16], cilji[8], 2009),
            new Tretja.Nocitev(osebe[2], cilji[19], 2020),
            new Tretja.Nocitev(osebe[17], cilji[20], 2012),
            new Tretja.Nocitev(osebe[19], cilji[3], 2015),
            new Tretja.Nocitev(osebe[20], cilji[8], 2020),
            new Tretja.Nocitev(osebe[11], cilji[18], 2015),
            new Tretja.Nocitev(osebe[1], cilji[9], 2017),
            new Tretja.Nocitev(osebe[5], cilji[20], 2012),
            new Tretja.Nocitev(osebe[17], cilji[20], 2004),
            new Tretja.Nocitev(osebe[9], cilji[15], 2012),
            new Tretja.Nocitev(osebe[12], cilji[19], 2018),
            new Tretja.Nocitev(osebe[16], cilji[21], 2012),
            new Tretja.Nocitev(osebe[16], cilji[3], 2003),
            new Tretja.Nocitev(osebe[2], cilji[19], 2001),
            new Tretja.Nocitev(osebe[22], cilji[13], 2014),
            new Tretja.Nocitev(osebe[22], cilji[13], 2005),
            new Tretja.Nocitev(osebe[6], cilji[23], 2011),
            new Tretja.Nocitev(osebe[0], cilji[15], 2004),
            new Tretja.Nocitev(osebe[2], cilji[19], 2003),
            new Tretja.Nocitev(osebe[20], cilji[8], 2002),
            new Tretja.Nocitev(osebe[1], cilji[14], 2012),
            new Tretja.Nocitev(osebe[3], cilji[6], 2017),
            new Tretja.Nocitev(osebe[4], cilji[6], 2005),
            new Tretja.Nocitev(osebe[19], cilji[2], 2014),
            new Tretja.Nocitev(osebe[0], cilji[15], 2009),
            new Tretja.Nocitev(osebe[10], cilji[13], 2009),
            new Tretja.Nocitev(osebe[16], cilji[15], 2008),
            new Tretja.Nocitev(osebe[2], cilji[19], 2003),
            new Tretja.Nocitev(osebe[5], cilji[21], 2020),
            new Tretja.Nocitev(osebe[6], cilji[8], 2018),
            new Tretja.Nocitev(osebe[0], cilji[15], 2007),
            new Tretja.Nocitev(osebe[13], cilji[3], 2017),
            new Tretja.Nocitev(osebe[23], cilji[0], 2019),
            new Tretja.Nocitev(osebe[12], cilji[19], 2020),
            new Tretja.Nocitev(osebe[11], cilji[18], 2018),
            new Tretja.Nocitev(osebe[6], cilji[20], 2011),
            new Tretja.Nocitev(osebe[5], cilji[23], 2018),
            new Tretja.Nocitev(osebe[23], cilji[18], 2018),
            new Tretja.Nocitev(osebe[12], cilji[19], 2012),
            new Tretja.Nocitev(osebe[24], cilji[24], 2003),
            new Tretja.Nocitev(osebe[16], cilji[26], 2017),
            new Tretja.Nocitev(osebe[6], cilji[12], 2002),
            new Tretja.Nocitev(osebe[10], cilji[3], 2007),
            new Tretja.Nocitev(osebe[9], cilji[20], 2020),
            new Tretja.Nocitev(osebe[3], cilji[4], 2019),
            new Tretja.Nocitev(osebe[20], cilji[8], 2018),
            new Tretja.Nocitev(osebe[18], cilji[6], 2003),
            new Tretja.Nocitev(osebe[14], cilji[18], 2020),
            new Tretja.Nocitev(osebe[4], cilji[6], 2019),
            new Tretja.Nocitev(osebe[5], cilji[20], 2012),
            new Tretja.Nocitev(osebe[3], cilji[24], 2010),
            new Tretja.Nocitev(osebe[3], cilji[1], 2001),
            new Tretja.Nocitev(osebe[15], cilji[0], 2010),
            new Tretja.Nocitev(osebe[11], cilji[18], 2005),
            new Tretja.Nocitev(osebe[2], cilji[19], 2005),
            new Tretja.Nocitev(osebe[6], cilji[4], 2004),
            new Tretja.Nocitev(osebe[23], cilji[20], 2002),
            new Tretja.Nocitev(osebe[21], cilji[17], 2003),
            new Tretja.Nocitev(osebe[5], cilji[20], 2008),
            new Tretja.Nocitev(osebe[24], cilji[24], 2008),
            new Tretja.Nocitev(osebe[20], cilji[8], 2008),
            new Tretja.Nocitev(osebe[10], cilji[11], 2009),
            new Tretja.Nocitev(osebe[3], cilji[9], 2009),
            new Tretja.Nocitev(osebe[19], cilji[24], 2002),
            new Tretja.Nocitev(osebe[24], cilji[24], 2008),
            new Tretja.Nocitev(osebe[12], cilji[19], 2006),
            new Tretja.Nocitev(osebe[22], cilji[13], 2008),
        };

        int[][] obiskanost = Tretja.obiskanost(nocitve, cilji, 2018, 2019);
        for (int i = 0;  i < obiskanost.length;  i++) {
            for (int j = 0;  j < obiskanost[i].length;  j++) {
                System.out.printf("%2d", obiskanost[i][j]);
            }
            System.out.println();
        }
    }
}
