
public class Test31 {

    public static void main(String[] args) {
        Tretja.Oseba[] osebe = {
            new Tretja.Oseba("Yezk Swsu", "Yzdw"),
            new Tretja.Oseba("Qlmu Oyfr", "Kjpw"),
            new Tretja.Oseba("Glnj Nlqn", "Kjpw"),
            new Tretja.Oseba("Apbg Dcuy", "Mkso"),
            new Tretja.Oseba("Xwfc Lueo", "Kjpw"),
            new Tretja.Oseba("Upsn Wukp", "Yzdw"),
            new Tretja.Oseba("Mpsb Oyvj", "Yzdw"),
            new Tretja.Oseba("Jhht Mjka", "Mkso"),
            new Tretja.Oseba("Ifqr Zuow", "Mkso"),
            new Tretja.Oseba("Gcnk Zdwm", "Yzdw"),
            new Tretja.Oseba("Gsvf Ojgd", "Epoi"),
            new Tretja.Oseba("Iias Bhwq", "Kjpw"),
            new Tretja.Oseba("Ueej Jfrm", "Mkso"),
            new Tretja.Oseba("Ugaf Vftq", "Kjpw"),
            new Tretja.Oseba("Kwjg Jlns", "Epoi"),
            new Tretja.Oseba("Offe Ptao", "Yzdw"),
            new Tretja.Oseba("Ciui Ylgo", "Epoi"),
            new Tretja.Oseba("Ioce Xlaa", "Yzdw"),
            new Tretja.Oseba("Oumm Unpq", "Yzdw"),
            new Tretja.Oseba("Bouy Wcrb", "Yzdw"),
            new Tretja.Oseba("Totm Wnh", "Yzdw"),
            new Tretja.Oseba("Rlsw Tgfk", "Kjpw"),
            new Tretja.Oseba("Hvjt Faaj", "Epoi"),
            new Tretja.Oseba("Pmkv Qcrx", "Mkso"),
            new Tretja.Oseba("Womm Suuh", "Epoi"),
            new Tretja.Oseba("Uecn Metw", "Mkso"),
            new Tretja.Oseba("Rgat Xkcq", "Kjpw"),
            new Tretja.Oseba("Yseg Oytu", "Mkso"),
            new Tretja.Oseba("Wbqm Jtqy", "Epoi"),
            new Tretja.Oseba("Olyp Ynkp", "Kjpw"),
            new Tretja.Oseba("Regx Tubt", "Kjpw"),
            new Tretja.Oseba("Wkmb Aedz", "Epoi"),
        };

        Tretja.Cilj[] cilji = {
            new Tretja.Cilj("Znj", "Epoi"),
            new Tretja.Cilj("Kocz", "Yzdw"),
            new Tretja.Cilj("Aslg", "Epoi"),
            new Tretja.Cilj("Kqaf", "Kjpw"),
            new Tretja.Cilj("Ucnm", "Epoi"),
            new Tretja.Cilj("Lgzy", "Epoi"),
            new Tretja.Cilj("Hopb", "Yzdw"),
            new Tretja.Cilj("Qkdz", "Mkso"),
            new Tretja.Cilj("Gkv", "Kjpw"),
            new Tretja.Cilj("Xluf", "Yzdw"),
            new Tretja.Cilj("Jsfw", "Kjpw"),
            new Tretja.Cilj("Ppaa", "Yzdw"),
            new Tretja.Cilj("Utzo", "Epoi"),
            new Tretja.Cilj("Wdvp", "Mkso"),
            new Tretja.Cilj("Ozlz", "Epoi"),
            new Tretja.Cilj("Bddi", "Mkso"),
            new Tretja.Cilj("Yrva", "Kjpw"),
            new Tretja.Cilj("Gihd", "Yzdw"),
            new Tretja.Cilj("Rdxp", "Kjpw"),
            new Tretja.Cilj("Bsvz", "Yzdw"),
            new Tretja.Cilj("Mzbl", "Kjpw"),
            new Tretja.Cilj("Dxrx", "Yzdw"),
            new Tretja.Cilj("Kxfr", "Yzdw"),
            new Tretja.Cilj("Qtxa", "Epoi"),
            new Tretja.Cilj("Vvfg", "Kjpw"),
            new Tretja.Cilj("Poea", "Epoi"),
            new Tretja.Cilj("Wbis", "Mkso"),
            new Tretja.Cilj("Ayis", "Epoi"),
            new Tretja.Cilj("Btau", "Kjpw"),
        };

        Tretja.Nocitev[] nocitve = {
            new Tretja.Nocitev(osebe[30], cilji[1], 2004),
            new Tretja.Nocitev(osebe[6], cilji[28], 2013),
            new Tretja.Nocitev(osebe[2], cilji[22], 2006),
            new Tretja.Nocitev(osebe[31], cilji[21], 2019),
            new Tretja.Nocitev(osebe[25], cilji[14], 2000),
            new Tretja.Nocitev(osebe[17], cilji[17], 2007),
            new Tretja.Nocitev(osebe[2], cilji[22], 2009),
            new Tretja.Nocitev(osebe[28], cilji[21], 2019),
            new Tretja.Nocitev(osebe[8], cilji[13], 2001),
            new Tretja.Nocitev(osebe[14], cilji[4], 2004),
            new Tretja.Nocitev(osebe[23], cilji[17], 2016),
            new Tretja.Nocitev(osebe[24], cilji[24], 2018),
            new Tretja.Nocitev(osebe[23], cilji[17], 2003),
            new Tretja.Nocitev(osebe[16], cilji[22], 2000),
            new Tretja.Nocitev(osebe[30], cilji[19], 2015),
            new Tretja.Nocitev(osebe[29], cilji[12], 2015),
            new Tretja.Nocitev(osebe[9], cilji[9], 2014),
            new Tretja.Nocitev(osebe[26], cilji[28], 2005),
            new Tretja.Nocitev(osebe[29], cilji[12], 2014),
            new Tretja.Nocitev(osebe[27], cilji[5], 2001),
            new Tretja.Nocitev(osebe[6], cilji[28], 2005),
            new Tretja.Nocitev(osebe[20], cilji[14], 2007),
            new Tretja.Nocitev(osebe[3], cilji[16], 2019),
            new Tretja.Nocitev(osebe[3], cilji[23], 2000),
            new Tretja.Nocitev(osebe[12], cilji[13], 2014),
            new Tretja.Nocitev(osebe[10], cilji[14], 2010),
            new Tretja.Nocitev(osebe[30], cilji[4], 2000),
            new Tretja.Nocitev(osebe[7], cilji[27], 2009),
            new Tretja.Nocitev(osebe[13], cilji[7], 2008),
            new Tretja.Nocitev(osebe[2], cilji[22], 2008),
            new Tretja.Nocitev(osebe[25], cilji[14], 2018),
            new Tretja.Nocitev(osebe[21], cilji[14], 2002),
            new Tretja.Nocitev(osebe[24], cilji[11], 2009),
            new Tretja.Nocitev(osebe[14], cilji[9], 2017),
            new Tretja.Nocitev(osebe[22], cilji[21], 2018),
            new Tretja.Nocitev(osebe[26], cilji[3], 2006),
            new Tretja.Nocitev(osebe[6], cilji[28], 2015),
            new Tretja.Nocitev(osebe[22], cilji[8], 2002),
            new Tretja.Nocitev(osebe[3], cilji[7], 2010),
            new Tretja.Nocitev(osebe[3], cilji[25], 2014),
            new Tretja.Nocitev(osebe[4], cilji[14], 2000),
            new Tretja.Nocitev(osebe[8], cilji[13], 2009),
            new Tretja.Nocitev(osebe[23], cilji[17], 2012),
            new Tretja.Nocitev(osebe[12], cilji[13], 2002),
            new Tretja.Nocitev(osebe[31], cilji[21], 2007),
            new Tretja.Nocitev(osebe[10], cilji[5], 2011),
            new Tretja.Nocitev(osebe[12], cilji[13], 2005),
            new Tretja.Nocitev(osebe[5], cilji[28], 2005),
            new Tretja.Nocitev(osebe[1], cilji[21], 2010),
            new Tretja.Nocitev(osebe[11], cilji[15], 2012),
            new Tretja.Nocitev(osebe[3], cilji[0], 2012),
            new Tretja.Nocitev(osebe[14], cilji[7], 2015),
            new Tretja.Nocitev(osebe[24], cilji[11], 2006),
            new Tretja.Nocitev(osebe[28], cilji[21], 2015),
            new Tretja.Nocitev(osebe[23], cilji[17], 2014),
            new Tretja.Nocitev(osebe[9], cilji[23], 2004),
            new Tretja.Nocitev(osebe[9], cilji[27], 2010),
            new Tretja.Nocitev(osebe[29], cilji[12], 2017),
            new Tretja.Nocitev(osebe[9], cilji[6], 2003),
            new Tretja.Nocitev(osebe[9], cilji[21], 2009),
            new Tretja.Nocitev(osebe[18], cilji[4], 2012),
            new Tretja.Nocitev(osebe[21], cilji[20], 2000),
            new Tretja.Nocitev(osebe[17], cilji[4], 2011),
            new Tretja.Nocitev(osebe[20], cilji[24], 2012),
            new Tretja.Nocitev(osebe[22], cilji[7], 2004),
            new Tretja.Nocitev(osebe[13], cilji[7], 2019),
            new Tretja.Nocitev(osebe[29], cilji[12], 2005),
            new Tretja.Nocitev(osebe[23], cilji[17], 2019),
            new Tretja.Nocitev(osebe[1], cilji[0], 2020),
            new Tretja.Nocitev(osebe[26], cilji[1], 2017),
            new Tretja.Nocitev(osebe[3], cilji[5], 2011),
            new Tretja.Nocitev(osebe[13], cilji[7], 2006),
            new Tretja.Nocitev(osebe[30], cilji[21], 2004),
            new Tretja.Nocitev(osebe[14], cilji[17], 2012),
            new Tretja.Nocitev(osebe[11], cilji[15], 2009),
            new Tretja.Nocitev(osebe[24], cilji[5], 2005),
            new Tretja.Nocitev(osebe[26], cilji[6], 2002),
            new Tretja.Nocitev(osebe[10], cilji[24], 2001),
            new Tretja.Nocitev(osebe[28], cilji[21], 2016),
            new Tretja.Nocitev(osebe[4], cilji[22], 2003),
            new Tretja.Nocitev(osebe[21], cilji[6], 2020),
            new Tretja.Nocitev(osebe[9], cilji[25], 2016),
            new Tretja.Nocitev(osebe[2], cilji[22], 2011),
            new Tretja.Nocitev(osebe[0], cilji[1], 2003),
            new Tretja.Nocitev(osebe[3], cilji[8], 2007),
            new Tretja.Nocitev(osebe[8], cilji[13], 2010),
            new Tretja.Nocitev(osebe[11], cilji[15], 2004),
            new Tretja.Nocitev(osebe[21], cilji[6], 2013),
            new Tretja.Nocitev(osebe[11], cilji[15], 2008),
            new Tretja.Nocitev(osebe[3], cilji[13], 2020),
            new Tretja.Nocitev(osebe[19], cilji[16], 2002),
            new Tretja.Nocitev(osebe[31], cilji[21], 2017),
            new Tretja.Nocitev(osebe[17], cilji[22], 2019),
            new Tretja.Nocitev(osebe[3], cilji[15], 2020),
            new Tretja.Nocitev(osebe[11], cilji[15], 2004),
            new Tretja.Nocitev(osebe[5], cilji[28], 2005),
            new Tretja.Nocitev(osebe[1], cilji[24], 2018),
            new Tretja.Nocitev(osebe[20], cilji[13], 2012),
            new Tretja.Nocitev(osebe[9], cilji[14], 2011),
            new Tretja.Nocitev(osebe[1], cilji[26], 2019),
            new Tretja.Nocitev(osebe[19], cilji[1], 2007),
            new Tretja.Nocitev(osebe[8], cilji[13], 2011),
            new Tretja.Nocitev(osebe[10], cilji[8], 2019),
            new Tretja.Nocitev(osebe[20], cilji[28], 2006),
            new Tretja.Nocitev(osebe[26], cilji[13], 2016),
            new Tretja.Nocitev(osebe[1], cilji[27], 2000),
            new Tretja.Nocitev(osebe[18], cilji[4], 2005),
            new Tretja.Nocitev(osebe[15], cilji[19], 2017),
            new Tretja.Nocitev(osebe[11], cilji[15], 2009),
            new Tretja.Nocitev(osebe[5], cilji[28], 2006),
            new Tretja.Nocitev(osebe[12], cilji[13], 2003),
            new Tretja.Nocitev(osebe[15], cilji[19], 2013),
            new Tretja.Nocitev(osebe[18], cilji[4], 2001),
            new Tretja.Nocitev(osebe[9], cilji[24], 2019),
            new Tretja.Nocitev(osebe[27], cilji[5], 2018),
            new Tretja.Nocitev(osebe[23], cilji[17], 2010),
            new Tretja.Nocitev(osebe[10], cilji[9], 2017),
            new Tretja.Nocitev(osebe[19], cilji[0], 2009),
            new Tretja.Nocitev(osebe[17], cilji[4], 2004),
            new Tretja.Nocitev(osebe[24], cilji[16], 2014),
            new Tretja.Nocitev(osebe[22], cilji[13], 2013),
            new Tretja.Nocitev(osebe[8], cilji[13], 2019),
            new Tretja.Nocitev(osebe[14], cilji[23], 2002),
            new Tretja.Nocitev(osebe[7], cilji[15], 2003),
            new Tretja.Nocitev(osebe[12], cilji[13], 2015),
            new Tretja.Nocitev(osebe[8], cilji[13], 2007),
            new Tretja.Nocitev(osebe[29], cilji[12], 2019),
            new Tretja.Nocitev(osebe[25], cilji[14], 2013),
            new Tretja.Nocitev(osebe[9], cilji[5], 2007),
            new Tretja.Nocitev(osebe[24], cilji[10], 2014),
            new Tretja.Nocitev(osebe[29], cilji[12], 2003),
            new Tretja.Nocitev(osebe[27], cilji[5], 2006),
            new Tretja.Nocitev(osebe[5], cilji[28], 2008),
            new Tretja.Nocitev(osebe[20], cilji[0], 2012),
            new Tretja.Nocitev(osebe[26], cilji[10], 2013),
            new Tretja.Nocitev(osebe[6], cilji[28], 2009),
            new Tretja.Nocitev(osebe[30], cilji[1], 2001),
            new Tretja.Nocitev(osebe[12], cilji[13], 2004),
            new Tretja.Nocitev(osebe[30], cilji[24], 2008),
            new Tretja.Nocitev(osebe[30], cilji[22], 2004),
            new Tretja.Nocitev(osebe[13], cilji[7], 2009),
            new Tretja.Nocitev(osebe[28], cilji[21], 2011),
            new Tretja.Nocitev(osebe[8], cilji[13], 2018),
            new Tretja.Nocitev(osebe[30], cilji[23], 2003),
            new Tretja.Nocitev(osebe[31], cilji[21], 2001),
            new Tretja.Nocitev(osebe[29], cilji[12], 2004),
            new Tretja.Nocitev(osebe[8], cilji[13], 2008),
            new Tretja.Nocitev(osebe[10], cilji[24], 2015),
        };

        for (Tretja.Oseba oseba: osebe) {
            System.out.println(Tretja.jeZvesta(nocitve, oseba));
        }
    }
}
