
public class Test44 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 68);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 725);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 475);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 223);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 577);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 33);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 226);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 683);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 886);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 804);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 207);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 680);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 9);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 322);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 699);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 416);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 715);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 621);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 64);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 348);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 470);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 62);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 219);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 255);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 819);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 38);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 702);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 172);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 702);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 224);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 594);
        Tretja.Opravilo o31 = new Tretja.Opravilo("o31", 245);
        Tretja.Opravilo o32 = new Tretja.Opravilo("o32", 435);
        Tretja.Opravilo o33 = new Tretja.Opravilo("o33", 640);
        Tretja.Opravilo o34 = new Tretja.Opravilo("o34", 564);
        Tretja.Opravilo o35 = new Tretja.Opravilo("o35", 271);
        Tretja.Opravilo o36 = new Tretja.Opravilo("o36", 322);
        Tretja.Opravilo o37 = new Tretja.Opravilo("o37", 69);
        Tretja.Opravilo o38 = new Tretja.Opravilo("o38", 653);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o20, o10, o7});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o21, o33, o10, o2, o28, o30, o9, o16, o36, o13});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o35, o7, o24, o18, o12, o0, o28});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o38, o29, o16, o9, o18, o2, o35, o6});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o8, o12, o19, o37, o2, o3, o1});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o10, o20, o7});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o6, o16, o18, o35, o38, o9});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o16, o32, o6, o0, o19, o30, o27, o22, o29, o11, o23});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o21, o37, o13, o34, o22});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o35});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o12, o1, o0});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o19, o34, o1, o7, o13, o9, o30, o16});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o10});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o22, o35, o20, o8, o7, o26, o3, o25, o14});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o19, o37, o2, o3, o1, o12, o8});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o30, o10, o28, o14, o29, o5, o6, o33, o23, o17, o25, o21});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o2, o29, o6, o16, o18, o9, o38, o35});

        System.out.println(p6.jePermutacijaOd(p15));
        System.out.println(p6.jePermutacijaOd(p13));
        System.out.println(p16.jePermutacijaOd(p4));
        System.out.println(p15.jePermutacijaOd(p4));
        System.out.println(p13.jePermutacijaOd(p1));
        System.out.println(p16.jePermutacijaOd(p4));
        System.out.println(p15.jePermutacijaOd(p12));
        System.out.println(p9.jePermutacijaOd(p7));
        System.out.println(p1.jePermutacijaOd(p9));
        System.out.println(p15.jePermutacijaOd(p16));
        System.out.println(p10.jePermutacijaOd(p9));
        System.out.println(p8.jePermutacijaOd(p15));
        System.out.println(p2.jePermutacijaOd(p1));
        System.out.println(p3.jePermutacijaOd(p14));
        System.out.println(p6.jePermutacijaOd(p12));
        System.out.println(p0.jePermutacijaOd(p14));
        System.out.println(p5.jePermutacijaOd(p10));
        System.out.println(p6.jePermutacijaOd(p12));
        System.out.println(p0.jePermutacijaOd(p12));
        System.out.println(p9.jePermutacijaOd(p10));
        System.out.println(p8.jePermutacijaOd(p6));
        System.out.println(p2.jePermutacijaOd(p3));
        System.out.println(p11.jePermutacijaOd(p9));
        System.out.println(p10.jePermutacijaOd(p6));
        System.out.println(p15.jePermutacijaOd(p10));
        System.out.println(p4.jePermutacijaOd(p5));
        System.out.println(p11.jePermutacijaOd(p3));
        System.out.println(p11.jePermutacijaOd(p6));
        System.out.println(p12.jePermutacijaOd(p0));
        System.out.println(p1.jePermutacijaOd(p6));
        System.out.println(p0.jePermutacijaOd(p6));
        System.out.println(p14.jePermutacijaOd(p4));
        System.out.println(p12.jePermutacijaOd(p5));
        System.out.println(p11.jePermutacijaOd(p15));
        System.out.println(p8.jePermutacijaOd(p12));
        System.out.println(p11.jePermutacijaOd(p1));
        System.out.println(p7.jePermutacijaOd(p1));
        System.out.println(p2.jePermutacijaOd(p11));
        System.out.println(p10.jePermutacijaOd(p7));
        System.out.println(p2.jePermutacijaOd(p4));
        System.out.println(p16.jePermutacijaOd(p8));
        System.out.println(p3.jePermutacijaOd(p0));
        System.out.println(p3.jePermutacijaOd(p14));
        System.out.println(p11.jePermutacijaOd(p16));
        System.out.println(p15.jePermutacijaOd(p8));
        System.out.println(p1.jePermutacijaOd(p5));
        System.out.println(p8.jePermutacijaOd(p3));
        System.out.println(p0.jePermutacijaOd(p4));
        System.out.println(p9.jePermutacijaOd(p6));
        System.out.println(p5.jePermutacijaOd(p3));
        System.out.println(p13.jePermutacijaOd(p15));
        System.out.println(p5.jePermutacijaOd(p11));
        System.out.println(p14.jePermutacijaOd(p10));
        System.out.println(p14.jePermutacijaOd(p8));
        System.out.println(p15.jePermutacijaOd(p6));
        System.out.println(p5.jePermutacijaOd(p7));
        System.out.println(p6.jePermutacijaOd(p14));
        System.out.println(p15.jePermutacijaOd(p2));
        System.out.println(p13.jePermutacijaOd(p4));
        System.out.println(p7.jePermutacijaOd(p5));
    }
}
