
public class Test38 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 143);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 734);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 69);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 842);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 513);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 224);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 220);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 448);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 674);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 739);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 363);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 823);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 854);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 347);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 415);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 237);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 693);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 991);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 651);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 557);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 1);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 354);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 63);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 320);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 320);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 817);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 942);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 346);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 760);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 698);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 766);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o22});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o13, o5, o6, o23, o20, o21, o14});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o13, o6, o5, o14, o23, o21, o20});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o11, o1, o15, o18, o20, o12, o21, o5, o27, o30});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o14, o6, o23, o13, o5, o20});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o18, o14, o26, o1, o0, o11, o15, o28, o29, o6});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o17, o27, o3, o7, o24});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o19, o23, o3});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o3});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o3});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o24, o15});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o10, o8, o6, o5});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o5, o8, o10, o6});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o10});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o5, o10});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o14, o17, o30, o3, o21, o26, o24, o1});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o18, o2, o0, o23, o22, o20});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o3, o19, o23});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o3});
        Tretja.Projekt p19 = new Tretja.Projekt("p19", new Tretja.Opravilo[]{o4, o1, o6});
        Tretja.Projekt p20 = new Tretja.Projekt("p20", new Tretja.Opravilo[]{o24, o15});
        Tretja.Projekt p21 = new Tretja.Projekt("p21", new Tretja.Opravilo[]{o10, o5});
        Tretja.Projekt p22 = new Tretja.Projekt("p22", new Tretja.Opravilo[]{o12, o16, o26, o18, o1, o11, o5, o21});

        System.out.println(p15.jePermutacijaOd(p8));
        System.out.println(p16.jePermutacijaOd(p8));
        System.out.println(p9.jePermutacijaOd(p4));
        System.out.println(p15.jePermutacijaOd(p17));
        System.out.println(p15.jePermutacijaOd(p13));
        System.out.println(p7.jePermutacijaOd(p6));
        System.out.println(p18.jePermutacijaOd(p5));
        System.out.println(p7.jePermutacijaOd(p11));
        System.out.println(p8.jePermutacijaOd(p12));
        System.out.println(p18.jePermutacijaOd(p6));
        System.out.println(p12.jePermutacijaOd(p11));
        System.out.println(p10.jePermutacijaOd(p5));
        System.out.println(p7.jePermutacijaOd(p6));
        System.out.println(p18.jePermutacijaOd(p2));
        System.out.println(p16.jePermutacijaOd(p11));
        System.out.println(p20.jePermutacijaOd(p14));
        System.out.println(p15.jePermutacijaOd(p7));
        System.out.println(p5.jePermutacijaOd(p19));
        System.out.println(p18.jePermutacijaOd(p17));
        System.out.println(p14.jePermutacijaOd(p6));
        System.out.println(p7.jePermutacijaOd(p15));
        System.out.println(p7.jePermutacijaOd(p4));
        System.out.println(p14.jePermutacijaOd(p11));
        System.out.println(p20.jePermutacijaOd(p4));
        System.out.println(p5.jePermutacijaOd(p6));
        System.out.println(p2.jePermutacijaOd(p12));
        System.out.println(p17.jePermutacijaOd(p7));
        System.out.println(p13.jePermutacijaOd(p8));
        System.out.println(p8.jePermutacijaOd(p10));
        System.out.println(p6.jePermutacijaOd(p1));
        System.out.println(p0.jePermutacijaOd(p18));
        System.out.println(p21.jePermutacijaOd(p1));
        System.out.println(p7.jePermutacijaOd(p0));
        System.out.println(p0.jePermutacijaOd(p21));
        System.out.println(p15.jePermutacijaOd(p9));
        System.out.println(p10.jePermutacijaOd(p0));
        System.out.println(p10.jePermutacijaOd(p11));
        System.out.println(p1.jePermutacijaOd(p6));
        System.out.println(p2.jePermutacijaOd(p17));
        System.out.println(p22.jePermutacijaOd(p7));
        System.out.println(p7.jePermutacijaOd(p13));
        System.out.println(p10.jePermutacijaOd(p22));
        System.out.println(p14.jePermutacijaOd(p9));
        System.out.println(p15.jePermutacijaOd(p7));
        System.out.println(p16.jePermutacijaOd(p22));
        System.out.println(p15.jePermutacijaOd(p1));
        System.out.println(p9.jePermutacijaOd(p10));
        System.out.println(p4.jePermutacijaOd(p21));
        System.out.println(p21.jePermutacijaOd(p19));
        System.out.println(p7.jePermutacijaOd(p22));
        System.out.println(p3.jePermutacijaOd(p1));
        System.out.println(p2.jePermutacijaOd(p4));
        System.out.println(p13.jePermutacijaOd(p18));
    }
}
