
public class Test41 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 700);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 151);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 577);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 879);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 691);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 5);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 333);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 774);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 454);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 972);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 834);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 995);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 424);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 211);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 189);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 155);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 53);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 603);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 329);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 43);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 462);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 170);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 831);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 893);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 538);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 551);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 656);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 5);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 184);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 224);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 669);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o18, o5, o7, o21, o30, o29, o9});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o21, o18, o7, o5});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o5, o30});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o29, o21, o18});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o5, o21, o18, o7});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o5, o30});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o21, o7, o30, o9, o5, o29, o18});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o0, o26, o20});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o28, o24, o13, o22, o10, o30, o1});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o9, o5, o29, o18, o21, o30, o7});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o11, o20, o0});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o21, o29, o15, o0});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o18, o21});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o18, o21});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o5, o30});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o15, o3});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o21});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o17, o12, o2, o21, o5, o10, o20, o24});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o17, o10, o22, o26, o8, o2, o5, o6, o19, o23});
        Tretja.Projekt p19 = new Tretja.Projekt("p19", new Tretja.Opravilo[]{o21, o29, o15, o0});
        Tretja.Projekt p20 = new Tretja.Projekt("p20", new Tretja.Opravilo[]{o3, o7, o15, o8, o23, o1, o9, o18});
        Tretja.Projekt p21 = new Tretja.Projekt("p21", new Tretja.Opravilo[]{o27, o17, o28, o7, o18, o10, o15});
        Tretja.Projekt p22 = new Tretja.Projekt("p22", new Tretja.Opravilo[]{o28, o17, o9, o13, o30, o19, o5, o26, o25, o2});
        Tretja.Projekt p23 = new Tretja.Projekt("p23", new Tretja.Opravilo[]{o14, o13, o16});
        Tretja.Projekt p24 = new Tretja.Projekt("p24", new Tretja.Opravilo[]{o2, o30, o18, o16, o29, o5, o21, o23, o14, o4});
        Tretja.Projekt p25 = new Tretja.Projekt("p25", new Tretja.Opravilo[]{o30, o5});

        System.out.println(p9.jePermutacijaOd(p13));
        System.out.println(p23.jePermutacijaOd(p10));
        System.out.println(p17.jePermutacijaOd(p0));
        System.out.println(p17.jePermutacijaOd(p18));
        System.out.println(p20.jePermutacijaOd(p23));
        System.out.println(p17.jePermutacijaOd(p12));
        System.out.println(p3.jePermutacijaOd(p24));
        System.out.println(p21.jePermutacijaOd(p22));
        System.out.println(p18.jePermutacijaOd(p15));
        System.out.println(p18.jePermutacijaOd(p24));
        System.out.println(p11.jePermutacijaOd(p18));
        System.out.println(p4.jePermutacijaOd(p25));
        System.out.println(p21.jePermutacijaOd(p20));
        System.out.println(p18.jePermutacijaOd(p6));
        System.out.println(p18.jePermutacijaOd(p17));
        System.out.println(p1.jePermutacijaOd(p25));
        System.out.println(p18.jePermutacijaOd(p12));
        System.out.println(p8.jePermutacijaOd(p17));
        System.out.println(p1.jePermutacijaOd(p6));
        System.out.println(p7.jePermutacijaOd(p11));
        System.out.println(p6.jePermutacijaOd(p10));
        System.out.println(p1.jePermutacijaOd(p6));
        System.out.println(p1.jePermutacijaOd(p7));
        System.out.println(p17.jePermutacijaOd(p0));
        System.out.println(p5.jePermutacijaOd(p10));
        System.out.println(p22.jePermutacijaOd(p3));
        System.out.println(p12.jePermutacijaOd(p22));
        System.out.println(p2.jePermutacijaOd(p13));
        System.out.println(p17.jePermutacijaOd(p21));
        System.out.println(p23.jePermutacijaOd(p2));
        System.out.println(p17.jePermutacijaOd(p16));
        System.out.println(p1.jePermutacijaOd(p25));
        System.out.println(p6.jePermutacijaOd(p7));
        System.out.println(p6.jePermutacijaOd(p9));
        System.out.println(p9.jePermutacijaOd(p0));
        System.out.println(p1.jePermutacijaOd(p3));
        System.out.println(p18.jePermutacijaOd(p9));
        System.out.println(p19.jePermutacijaOd(p11));
        System.out.println(p21.jePermutacijaOd(p1));
        System.out.println(p11.jePermutacijaOd(p18));
        System.out.println(p22.jePermutacijaOd(p14));
        System.out.println(p11.jePermutacijaOd(p4));
        System.out.println(p23.jePermutacijaOd(p13));
        System.out.println(p4.jePermutacijaOd(p3));
        System.out.println(p7.jePermutacijaOd(p21));
        System.out.println(p23.jePermutacijaOd(p22));
        System.out.println(p21.jePermutacijaOd(p9));
        System.out.println(p2.jePermutacijaOd(p8));
        System.out.println(p10.jePermutacijaOd(p9));
        System.out.println(p7.jePermutacijaOd(p22));
        System.out.println(p17.jePermutacijaOd(p9));
        System.out.println(p22.jePermutacijaOd(p15));
        System.out.println(p3.jePermutacijaOd(p4));
        System.out.println(p12.jePermutacijaOd(p5));
        System.out.println(p23.jePermutacijaOd(p13));
        System.out.println(p3.jePermutacijaOd(p14));
    }
}
