
public class Test34 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 232);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 7);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 768);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 56);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 920);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 91);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 870);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 14);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 858);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 362);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 510);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 783);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 303);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 743);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 40);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 251);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 740);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 442);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 769);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 789);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 41);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 324);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 724);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 231);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 327);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 885);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 256);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 113);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 314);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 563);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 829);
        Tretja.Opravilo o31 = new Tretja.Opravilo("o31", 511);
        Tretja.Opravilo o32 = new Tretja.Opravilo("o32", 80);
        Tretja.Opravilo o33 = new Tretja.Opravilo("o33", 140);
        Tretja.Opravilo o34 = new Tretja.Opravilo("o34", 820);
        Tretja.Opravilo o35 = new Tretja.Opravilo("o35", 492);
        Tretja.Opravilo o36 = new Tretja.Opravilo("o36", 488);
        Tretja.Opravilo o37 = new Tretja.Opravilo("o37", 679);
        Tretja.Opravilo o38 = new Tretja.Opravilo("o38", 332);
        Tretja.Opravilo o39 = new Tretja.Opravilo("o39", 639);
        Tretja.Opravilo o40 = new Tretja.Opravilo("o40", 529);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o38, o8, o24, o13, o31});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o4, o34, o33, o30, o29, o0});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o34, o30, o4, o29, o33, o0});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o38, o40, o15, o4, o17, o11, o9, o31, o1, o28, o37, o7, o19});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o33, o30, o0, o34, o29, o4});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o29, o34, o30, o4, o0, o33});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o30, o29, o34, o4, o33, o0});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o6, o1, o5, o4, o29, o21, o37, o24, o10, o14, o0});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o24, o31, o38, o13, o8});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o38, o13, o31, o24});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o13, o31, o38, o8, o24});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o39, o0, o7});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o30, o29, o0, o34, o33, o4});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o40, o33, o34, o8, o14, o13, o20, o37});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o1, o4, o19, o7, o31, o17, o40, o28, o37, o11, o9, o38, o15});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o34, o4, o0, o33, o30, o29});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o26, o1, o7, o39, o2, o17});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o34, o29, o33, o0, o30, o4});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o29});
        Tretja.Projekt p19 = new Tretja.Projekt("p19", new Tretja.Opravilo[]{o38, o4, o9, o15, o19, o1, o37, o28, o7, o40, o31, o11, o17});
        Tretja.Projekt p20 = new Tretja.Projekt("p20", new Tretja.Opravilo[]{o13, o8, o34, o20, o33, o40, o14, o37});
        Tretja.Projekt p21 = new Tretja.Projekt("p21", new Tretja.Opravilo[]{o24, o38, o13, o8, o31});
        Tretja.Projekt p22 = new Tretja.Projekt("p22", new Tretja.Opravilo[]{o13, o30, o22, o2});

        System.out.println(p19.jePermutacijaOd(p18));
        System.out.println(p11.jePermutacijaOd(p9));
        System.out.println(p17.jePermutacijaOd(p8));
        System.out.println(p17.jePermutacijaOd(p12));
        System.out.println(p8.jePermutacijaOd(p21));
        System.out.println(p14.jePermutacijaOd(p0));
        System.out.println(p15.jePermutacijaOd(p5));
        System.out.println(p8.jePermutacijaOd(p1));
        System.out.println(p2.jePermutacijaOd(p0));
        System.out.println(p9.jePermutacijaOd(p3));
        System.out.println(p13.jePermutacijaOd(p12));
        System.out.println(p1.jePermutacijaOd(p7));
        System.out.println(p2.jePermutacijaOd(p17));
        System.out.println(p21.jePermutacijaOd(p10));
        System.out.println(p8.jePermutacijaOd(p13));
        System.out.println(p14.jePermutacijaOd(p20));
        System.out.println(p22.jePermutacijaOd(p2));
        System.out.println(p5.jePermutacijaOd(p16));
        System.out.println(p8.jePermutacijaOd(p13));
        System.out.println(p11.jePermutacijaOd(p0));
        System.out.println(p5.jePermutacijaOd(p7));
        System.out.println(p20.jePermutacijaOd(p4));
        System.out.println(p19.jePermutacijaOd(p16));
        System.out.println(p14.jePermutacijaOd(p12));
        System.out.println(p16.jePermutacijaOd(p0));
        System.out.println(p20.jePermutacijaOd(p18));
        System.out.println(p18.jePermutacijaOd(p7));
        System.out.println(p12.jePermutacijaOd(p13));
        System.out.println(p1.jePermutacijaOd(p9));
        System.out.println(p18.jePermutacijaOd(p1));
        System.out.println(p2.jePermutacijaOd(p20));
        System.out.println(p11.jePermutacijaOd(p14));
        System.out.println(p18.jePermutacijaOd(p5));
        System.out.println(p17.jePermutacijaOd(p11));
        System.out.println(p20.jePermutacijaOd(p2));
        System.out.println(p3.jePermutacijaOd(p2));
        System.out.println(p11.jePermutacijaOd(p2));
        System.out.println(p21.jePermutacijaOd(p16));
        System.out.println(p15.jePermutacijaOd(p12));
        System.out.println(p3.jePermutacijaOd(p8));
        System.out.println(p1.jePermutacijaOd(p8));
        System.out.println(p20.jePermutacijaOd(p18));
        System.out.println(p18.jePermutacijaOd(p9));
        System.out.println(p16.jePermutacijaOd(p21));
        System.out.println(p4.jePermutacijaOd(p19));
        System.out.println(p1.jePermutacijaOd(p10));
        System.out.println(p8.jePermutacijaOd(p15));
        System.out.println(p10.jePermutacijaOd(p20));
        System.out.println(p18.jePermutacijaOd(p21));
        System.out.println(p6.jePermutacijaOd(p13));
        System.out.println(p16.jePermutacijaOd(p12));
        System.out.println(p16.jePermutacijaOd(p12));
        System.out.println(p4.jePermutacijaOd(p2));
        System.out.println(p7.jePermutacijaOd(p19));
        System.out.println(p13.jePermutacijaOd(p22));
        System.out.println(p5.jePermutacijaOd(p3));
        System.out.println(p5.jePermutacijaOd(p11));
        System.out.println(p11.jePermutacijaOd(p16));
        System.out.println(p0.jePermutacijaOd(p3));
        System.out.println(p18.jePermutacijaOd(p7));
        System.out.println(p15.jePermutacijaOd(p10));
        System.out.println(p16.jePermutacijaOd(p18));
        System.out.println(p18.jePermutacijaOd(p1));
        System.out.println(p8.jePermutacijaOd(p0));
    }
}
