
public class Test45 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 978);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 744);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 190);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 916);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 830);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 824);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 947);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 907);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 168);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 459);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 762);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 267);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 604);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o8, o9, o6});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o6});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o6});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o8, o12});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o11, o3, o10});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o7, o0, o11});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o9, o10});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o1, o7});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o6});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o5});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o3, o2, o11});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o12, o4});

        System.out.println(p7.jePermutacijaOd(p11));
        System.out.println(p0.jePermutacijaOd(p10));
        System.out.println(p3.jePermutacijaOd(p10));
        System.out.println(p5.jePermutacijaOd(p2));
        System.out.println(p10.jePermutacijaOd(p2));
        System.out.println(p10.jePermutacijaOd(p8));
        System.out.println(p1.jePermutacijaOd(p9));
        System.out.println(p2.jePermutacijaOd(p0));
        System.out.println(p9.jePermutacijaOd(p4));
        System.out.println(p1.jePermutacijaOd(p2));
        System.out.println(p0.jePermutacijaOd(p5));
        System.out.println(p0.jePermutacijaOd(p5));
        System.out.println(p9.jePermutacijaOd(p11));
        System.out.println(p0.jePermutacijaOd(p8));
        System.out.println(p11.jePermutacijaOd(p10));
        System.out.println(p9.jePermutacijaOd(p6));
        System.out.println(p2.jePermutacijaOd(p3));
        System.out.println(p10.jePermutacijaOd(p7));
        System.out.println(p9.jePermutacijaOd(p7));
        System.out.println(p4.jePermutacijaOd(p5));
        System.out.println(p11.jePermutacijaOd(p1));
        System.out.println(p1.jePermutacijaOd(p11));
        System.out.println(p3.jePermutacijaOd(p2));
        System.out.println(p3.jePermutacijaOd(p1));
        System.out.println(p6.jePermutacijaOd(p8));
        System.out.println(p7.jePermutacijaOd(p6));
        System.out.println(p3.jePermutacijaOd(p9));
        System.out.println(p3.jePermutacijaOd(p8));
        System.out.println(p5.jePermutacijaOd(p8));
        System.out.println(p0.jePermutacijaOd(p6));
        System.out.println(p1.jePermutacijaOd(p9));
        System.out.println(p1.jePermutacijaOd(p2));
        System.out.println(p10.jePermutacijaOd(p1));
        System.out.println(p10.jePermutacijaOd(p0));
        System.out.println(p9.jePermutacijaOd(p7));
        System.out.println(p1.jePermutacijaOd(p0));
        System.out.println(p11.jePermutacijaOd(p10));
        System.out.println(p3.jePermutacijaOd(p2));
        System.out.println(p7.jePermutacijaOd(p1));
        System.out.println(p11.jePermutacijaOd(p0));
        System.out.println(p11.jePermutacijaOd(p6));
        System.out.println(p4.jePermutacijaOd(p10));
        System.out.println(p0.jePermutacijaOd(p6));
        System.out.println(p4.jePermutacijaOd(p8));
        System.out.println(p6.jePermutacijaOd(p4));
        System.out.println(p3.jePermutacijaOd(p7));
        System.out.println(p7.jePermutacijaOd(p11));
        System.out.println(p0.jePermutacijaOd(p5));
        System.out.println(p4.jePermutacijaOd(p9));
        System.out.println(p3.jePermutacijaOd(p1));
        System.out.println(p10.jePermutacijaOd(p0));
        System.out.println(p11.jePermutacijaOd(p1));
        System.out.println(p0.jePermutacijaOd(p6));
        System.out.println(p11.jePermutacijaOd(p9));
        System.out.println(p5.jePermutacijaOd(p10));
        System.out.println(p0.jePermutacijaOd(p11));
        System.out.println(p8.jePermutacijaOd(p6));
        System.out.println(p8.jePermutacijaOd(p1));
        System.out.println(p7.jePermutacijaOd(p5));
        System.out.println(p8.jePermutacijaOd(p5));
        System.out.println(p1.jePermutacijaOd(p5));
        System.out.println(p7.jePermutacijaOd(p4));
        System.out.println(p5.jePermutacijaOd(p1));
        System.out.println(p7.jePermutacijaOd(p0));
        System.out.println(p10.jePermutacijaOd(p5));
        System.out.println(p3.jePermutacijaOd(p0));
        System.out.println(p3.jePermutacijaOd(p2));
    }
}
