
public class Test43 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 35);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 644);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 761);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 710);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 804);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 946);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 79);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 375);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 745);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 564);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 635);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 437);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 554);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 566);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 884);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 170);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 58);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 316);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 121);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 656);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 207);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 726);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 129);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 655);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 59);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 132);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 888);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 509);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 107);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 410);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 782);
        Tretja.Opravilo o31 = new Tretja.Opravilo("o31", 913);
        Tretja.Opravilo o32 = new Tretja.Opravilo("o32", 405);
        Tretja.Opravilo o33 = new Tretja.Opravilo("o33", 829);
        Tretja.Opravilo o34 = new Tretja.Opravilo("o34", 9);
        Tretja.Opravilo o35 = new Tretja.Opravilo("o35", 99);
        Tretja.Opravilo o36 = new Tretja.Opravilo("o36", 839);
        Tretja.Opravilo o37 = new Tretja.Opravilo("o37", 189);
        Tretja.Opravilo o38 = new Tretja.Opravilo("o38", 480);
        Tretja.Opravilo o39 = new Tretja.Opravilo("o39", 263);
        Tretja.Opravilo o40 = new Tretja.Opravilo("o40", 38);
        Tretja.Opravilo o41 = new Tretja.Opravilo("o41", 793);
        Tretja.Opravilo o42 = new Tretja.Opravilo("o42", 429);
        Tretja.Opravilo o43 = new Tretja.Opravilo("o43", 431);
        Tretja.Opravilo o44 = new Tretja.Opravilo("o44", 731);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o33, o32, o12, o13, o36, o42, o37, o27, o25, o31, o1, o4, o44});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o42, o4, o12, o25, o33});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o27, o1, o42, o33, o12, o25, o36, o44, o37, o13, o31, o4, o32});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o1, o36, o25, o33, o42, o37, o12, o4, o13, o27, o44, o31, o32});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o12, o33, o25, o4, o42});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o1, o15, o3, o12, o32, o39, o40, o13});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o13, o32, o37, o27, o31, o12, o1, o25, o42, o4});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o4});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o42, o24, o10, o17, o30, o4, o7, o44, o23});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o28, o1, o39, o37, o35});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o26, o0, o32, o3, o30, o18, o37, o31});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o15, o11, o13, o3, o9, o10, o42, o24, o25, o38, o16, o4, o2});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o13, o27, o12, o42});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o36, o0, o1, o26, o33, o10, o15, o30, o19, o25, o18, o21, o8});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o25, o31, o44, o42, o37, o1, o32, o27, o13, o33, o4, o12, o36});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o18, o32, o15, o10, o36, o33, o8, o1, o31, o24, o3, o21, o38, o12, o13});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o33});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o31, o23});

        System.out.println(p2.jePermutacijaOd(p14));
        System.out.println(p17.jePermutacijaOd(p7));
        System.out.println(p6.jePermutacijaOd(p9));
        System.out.println(p0.jePermutacijaOd(p3));
        System.out.println(p11.jePermutacijaOd(p17));
        System.out.println(p8.jePermutacijaOd(p2));
        System.out.println(p9.jePermutacijaOd(p0));
        System.out.println(p2.jePermutacijaOd(p14));
        System.out.println(p17.jePermutacijaOd(p12));
        System.out.println(p2.jePermutacijaOd(p10));
        System.out.println(p5.jePermutacijaOd(p10));
        System.out.println(p1.jePermutacijaOd(p8));
        System.out.println(p11.jePermutacijaOd(p2));
        System.out.println(p1.jePermutacijaOd(p13));
        System.out.println(p5.jePermutacijaOd(p11));
        System.out.println(p14.jePermutacijaOd(p8));
        System.out.println(p0.jePermutacijaOd(p5));
        System.out.println(p11.jePermutacijaOd(p14));
        System.out.println(p14.jePermutacijaOd(p7));
        System.out.println(p10.jePermutacijaOd(p6));
        System.out.println(p2.jePermutacijaOd(p5));
        System.out.println(p6.jePermutacijaOd(p16));
        System.out.println(p0.jePermutacijaOd(p6));
        System.out.println(p3.jePermutacijaOd(p5));
        System.out.println(p11.jePermutacijaOd(p5));
        System.out.println(p2.jePermutacijaOd(p11));
        System.out.println(p17.jePermutacijaOd(p3));
        System.out.println(p11.jePermutacijaOd(p4));
        System.out.println(p13.jePermutacijaOd(p14));
        System.out.println(p3.jePermutacijaOd(p14));
        System.out.println(p12.jePermutacijaOd(p8));
        System.out.println(p16.jePermutacijaOd(p2));
        System.out.println(p8.jePermutacijaOd(p16));
        System.out.println(p16.jePermutacijaOd(p4));
        System.out.println(p16.jePermutacijaOd(p7));
        System.out.println(p17.jePermutacijaOd(p2));
        System.out.println(p13.jePermutacijaOd(p12));
        System.out.println(p4.jePermutacijaOd(p10));
        System.out.println(p16.jePermutacijaOd(p14));
        System.out.println(p11.jePermutacijaOd(p2));
        System.out.println(p8.jePermutacijaOd(p15));
        System.out.println(p5.jePermutacijaOd(p1));
        System.out.println(p0.jePermutacijaOd(p12));
        System.out.println(p13.jePermutacijaOd(p8));
        System.out.println(p13.jePermutacijaOd(p17));
        System.out.println(p4.jePermutacijaOd(p5));
        System.out.println(p13.jePermutacijaOd(p11));
        System.out.println(p6.jePermutacijaOd(p15));
        System.out.println(p0.jePermutacijaOd(p5));
        System.out.println(p12.jePermutacijaOd(p3));
        System.out.println(p8.jePermutacijaOd(p10));
        System.out.println(p4.jePermutacijaOd(p3));
        System.out.println(p17.jePermutacijaOd(p16));
    }
}
