
public class Test48 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 262);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 936);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 519);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 221);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 4);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 650);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 59);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 521);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 617);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 285);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 268);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 670);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 412);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 441);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 50);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 680);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 960);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 321);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 818);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 486);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 523);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 273);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 898);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 547);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 374);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 256);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o24, o3, o6, o15, o17, o10, o23});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o15, o23});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o25, o20, o7, o12, o10});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o10, o17, o3});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o10, o24, o17, o15, o6, o3});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o6, o24, o23, o10, o17, o3, o15});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o25, o12, o10, o7, o20});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o23});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o23});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o1, o5, o24, o10, o11, o14, o4, o20});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o0, o23, o19, o14, o15, o20, o2});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o6, o10, o3});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o25, o12, o20});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o20, o7, o15, o11});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o20, o14, o3, o16});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o2, o7, o23, o12});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o14, o16, o20, o3});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o20, o12, o25});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o23});
        Tretja.Projekt p19 = new Tretja.Projekt("p19", new Tretja.Opravilo[]{o0, o15, o23, o2, o19, o14, o20});
        Tretja.Projekt p20 = new Tretja.Projekt("p20", new Tretja.Opravilo[]{o4, o21, o6, o25, o24, o14});

        System.out.println(p4.jePermutacijaOd(p1));
        System.out.println(p9.jePermutacijaOd(p15));
        System.out.println(p10.jePermutacijaOd(p15));
        System.out.println(p18.jePermutacijaOd(p0));
        System.out.println(p6.jePermutacijaOd(p7));
        System.out.println(p20.jePermutacijaOd(p7));
        System.out.println(p13.jePermutacijaOd(p11));
        System.out.println(p4.jePermutacijaOd(p8));
        System.out.println(p11.jePermutacijaOd(p12));
        System.out.println(p5.jePermutacijaOd(p18));
        System.out.println(p0.jePermutacijaOd(p20));
        System.out.println(p5.jePermutacijaOd(p1));
        System.out.println(p1.jePermutacijaOd(p18));
        System.out.println(p9.jePermutacijaOd(p6));
        System.out.println(p6.jePermutacijaOd(p5));
        System.out.println(p18.jePermutacijaOd(p1));
        System.out.println(p8.jePermutacijaOd(p9));
        System.out.println(p0.jePermutacijaOd(p3));
        System.out.println(p3.jePermutacijaOd(p8));
        System.out.println(p20.jePermutacijaOd(p10));
        System.out.println(p10.jePermutacijaOd(p14));
        System.out.println(p11.jePermutacijaOd(p13));
        System.out.println(p6.jePermutacijaOd(p7));
        System.out.println(p20.jePermutacijaOd(p16));
        System.out.println(p15.jePermutacijaOd(p16));
        System.out.println(p19.jePermutacijaOd(p16));
        System.out.println(p2.jePermutacijaOd(p19));
        System.out.println(p0.jePermutacijaOd(p14));
        System.out.println(p5.jePermutacijaOd(p11));
        System.out.println(p10.jePermutacijaOd(p12));
        System.out.println(p15.jePermutacijaOd(p13));
        System.out.println(p16.jePermutacijaOd(p0));
        System.out.println(p16.jePermutacijaOd(p4));
        System.out.println(p6.jePermutacijaOd(p20));
        System.out.println(p3.jePermutacijaOd(p4));
        System.out.println(p10.jePermutacijaOd(p5));
        System.out.println(p13.jePermutacijaOd(p0));
        System.out.println(p2.jePermutacijaOd(p15));
        System.out.println(p18.jePermutacijaOd(p15));
        System.out.println(p13.jePermutacijaOd(p16));
        System.out.println(p4.jePermutacijaOd(p12));
        System.out.println(p12.jePermutacijaOd(p2));
        System.out.println(p14.jePermutacijaOd(p11));
        System.out.println(p9.jePermutacijaOd(p3));
        System.out.println(p15.jePermutacijaOd(p8));
        System.out.println(p20.jePermutacijaOd(p5));
        System.out.println(p7.jePermutacijaOd(p2));
        System.out.println(p18.jePermutacijaOd(p20));
        System.out.println(p7.jePermutacijaOd(p12));
        System.out.println(p18.jePermutacijaOd(p2));
        System.out.println(p18.jePermutacijaOd(p11));
        System.out.println(p19.jePermutacijaOd(p2));
        System.out.println(p12.jePermutacijaOd(p11));
        System.out.println(p20.jePermutacijaOd(p1));
        System.out.println(p12.jePermutacijaOd(p17));
    }
}
