
public class Test36 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 864);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 115);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 500);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 956);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 937);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 133);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 649);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 811);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 659);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 722);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 619);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 468);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 238);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 200);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 959);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 392);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 771);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 7);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 51);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 519);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 645);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 26);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 312);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 199);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 422);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 445);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 546);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 834);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o15, o2, o19, o17, o12, o5, o23, o1});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o5});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o5, o23, o12, o19});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o1, o5, o19, o12, o17, o23, o2});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o19});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o19});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o20, o26, o18, o15, o21, o10, o7});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o19, o23, o5, o12});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o12, o19, o23, o5});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o19, o15, o22, o21, o1, o18, o2, o24});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o4, o1, o13, o17, o14, o18});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o5, o17, o19, o12, o2, o23, o1, o15});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o2, o5});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o19});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o10, o20});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o19, o21, o22, o1, o2, o18, o15, o24});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o19});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o24, o8, o4, o7, o25, o10, o16, o2});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o5});
        Tretja.Projekt p19 = new Tretja.Projekt("p19", new Tretja.Opravilo[]{o7, o8, o24});
        Tretja.Projekt p20 = new Tretja.Projekt("p20", new Tretja.Opravilo[]{o20, o27, o10, o26, o2, o1, o3});
        Tretja.Projekt p21 = new Tretja.Projekt("p21", new Tretja.Opravilo[]{o27, o22, o17, o14, o11, o10});
        Tretja.Projekt p22 = new Tretja.Projekt("p22", new Tretja.Opravilo[]{o21});
        Tretja.Projekt p23 = new Tretja.Projekt("p23", new Tretja.Opravilo[]{o5});
        Tretja.Projekt p24 = new Tretja.Projekt("p24", new Tretja.Opravilo[]{o26, o10, o20, o2, o27, o3, o1});
        Tretja.Projekt p25 = new Tretja.Projekt("p25", new Tretja.Opravilo[]{o5});
        Tretja.Projekt p26 = new Tretja.Projekt("p26", new Tretja.Opravilo[]{o27, o10, o2, o1, o26, o20, o3});
        Tretja.Projekt p27 = new Tretja.Projekt("p27", new Tretja.Opravilo[]{o7, o9, o24, o27, o5, o3});

        System.out.println(p9.jePermutacijaOd(p10));
        System.out.println(p6.jePermutacijaOd(p13));
        System.out.println(p10.jePermutacijaOd(p0));
        System.out.println(p3.jePermutacijaOd(p0));
        System.out.println(p26.jePermutacijaOd(p9));
        System.out.println(p20.jePermutacijaOd(p2));
        System.out.println(p14.jePermutacijaOd(p6));
        System.out.println(p20.jePermutacijaOd(p8));
        System.out.println(p16.jePermutacijaOd(p8));
        System.out.println(p21.jePermutacijaOd(p5));
        System.out.println(p15.jePermutacijaOd(p3));
        System.out.println(p3.jePermutacijaOd(p22));
        System.out.println(p6.jePermutacijaOd(p20));
        System.out.println(p22.jePermutacijaOd(p0));
        System.out.println(p19.jePermutacijaOd(p3));
        System.out.println(p20.jePermutacijaOd(p13));
        System.out.println(p1.jePermutacijaOd(p21));
        System.out.println(p10.jePermutacijaOd(p1));
        System.out.println(p27.jePermutacijaOd(p22));
        System.out.println(p3.jePermutacijaOd(p7));
        System.out.println(p0.jePermutacijaOd(p10));
        System.out.println(p2.jePermutacijaOd(p1));
        System.out.println(p24.jePermutacijaOd(p14));
        System.out.println(p5.jePermutacijaOd(p13));
        System.out.println(p5.jePermutacijaOd(p11));
        System.out.println(p18.jePermutacijaOd(p25));
        System.out.println(p24.jePermutacijaOd(p22));
        System.out.println(p7.jePermutacijaOd(p22));
        System.out.println(p2.jePermutacijaOd(p22));
        System.out.println(p13.jePermutacijaOd(p0));
        System.out.println(p16.jePermutacijaOd(p1));
        System.out.println(p8.jePermutacijaOd(p21));
        System.out.println(p23.jePermutacijaOd(p7));
        System.out.println(p2.jePermutacijaOd(p24));
        System.out.println(p18.jePermutacijaOd(p11));
        System.out.println(p25.jePermutacijaOd(p12));
        System.out.println(p0.jePermutacijaOd(p10));
        System.out.println(p4.jePermutacijaOd(p5));
        System.out.println(p18.jePermutacijaOd(p3));
        System.out.println(p18.jePermutacijaOd(p26));
        System.out.println(p24.jePermutacijaOd(p6));
        System.out.println(p17.jePermutacijaOd(p15));
        System.out.println(p17.jePermutacijaOd(p0));
        System.out.println(p25.jePermutacijaOd(p27));
        System.out.println(p18.jePermutacijaOd(p16));
        System.out.println(p27.jePermutacijaOd(p1));
        System.out.println(p7.jePermutacijaOd(p26));
        System.out.println(p21.jePermutacijaOd(p12));
        System.out.println(p11.jePermutacijaOd(p7));
        System.out.println(p6.jePermutacijaOd(p15));
        System.out.println(p8.jePermutacijaOd(p6));
        System.out.println(p4.jePermutacijaOd(p22));
        System.out.println(p15.jePermutacijaOd(p27));
        System.out.println(p19.jePermutacijaOd(p15));
        System.out.println(p9.jePermutacijaOd(p2));
        System.out.println(p17.jePermutacijaOd(p6));
        System.out.println(p1.jePermutacijaOd(p0));
        System.out.println(p18.jePermutacijaOd(p26));
        System.out.println(p8.jePermutacijaOd(p13));
        System.out.println(p7.jePermutacijaOd(p4));
    }
}
