
public class Test42 {

    public static void main(String[] args) {
        Tretja.Opravilo o0 = new Tretja.Opravilo("o0", 183);
        Tretja.Opravilo o1 = new Tretja.Opravilo("o1", 862);
        Tretja.Opravilo o2 = new Tretja.Opravilo("o2", 422);
        Tretja.Opravilo o3 = new Tretja.Opravilo("o3", 113);
        Tretja.Opravilo o4 = new Tretja.Opravilo("o4", 39);
        Tretja.Opravilo o5 = new Tretja.Opravilo("o5", 138);
        Tretja.Opravilo o6 = new Tretja.Opravilo("o6", 613);
        Tretja.Opravilo o7 = new Tretja.Opravilo("o7", 683);
        Tretja.Opravilo o8 = new Tretja.Opravilo("o8", 301);
        Tretja.Opravilo o9 = new Tretja.Opravilo("o9", 397);
        Tretja.Opravilo o10 = new Tretja.Opravilo("o10", 125);
        Tretja.Opravilo o11 = new Tretja.Opravilo("o11", 185);
        Tretja.Opravilo o12 = new Tretja.Opravilo("o12", 445);
        Tretja.Opravilo o13 = new Tretja.Opravilo("o13", 315);
        Tretja.Opravilo o14 = new Tretja.Opravilo("o14", 473);
        Tretja.Opravilo o15 = new Tretja.Opravilo("o15", 235);
        Tretja.Opravilo o16 = new Tretja.Opravilo("o16", 724);
        Tretja.Opravilo o17 = new Tretja.Opravilo("o17", 992);
        Tretja.Opravilo o18 = new Tretja.Opravilo("o18", 671);
        Tretja.Opravilo o19 = new Tretja.Opravilo("o19", 554);
        Tretja.Opravilo o20 = new Tretja.Opravilo("o20", 427);
        Tretja.Opravilo o21 = new Tretja.Opravilo("o21", 395);
        Tretja.Opravilo o22 = new Tretja.Opravilo("o22", 244);
        Tretja.Opravilo o23 = new Tretja.Opravilo("o23", 379);
        Tretja.Opravilo o24 = new Tretja.Opravilo("o24", 161);
        Tretja.Opravilo o25 = new Tretja.Opravilo("o25", 333);
        Tretja.Opravilo o26 = new Tretja.Opravilo("o26", 10);
        Tretja.Opravilo o27 = new Tretja.Opravilo("o27", 744);
        Tretja.Opravilo o28 = new Tretja.Opravilo("o28", 755);
        Tretja.Opravilo o29 = new Tretja.Opravilo("o29", 644);
        Tretja.Opravilo o30 = new Tretja.Opravilo("o30", 83);
        Tretja.Opravilo o31 = new Tretja.Opravilo("o31", 505);
        Tretja.Opravilo o32 = new Tretja.Opravilo("o32", 151);
        Tretja.Opravilo o33 = new Tretja.Opravilo("o33", 260);
        Tretja.Opravilo o34 = new Tretja.Opravilo("o34", 810);
        Tretja.Opravilo o35 = new Tretja.Opravilo("o35", 965);
        Tretja.Opravilo o36 = new Tretja.Opravilo("o36", 831);
        Tretja.Opravilo o37 = new Tretja.Opravilo("o37", 564);
        Tretja.Opravilo o38 = new Tretja.Opravilo("o38", 163);
        Tretja.Opravilo o39 = new Tretja.Opravilo("o39", 627);
        Tretja.Opravilo o40 = new Tretja.Opravilo("o40", 335);
        Tretja.Opravilo o41 = new Tretja.Opravilo("o41", 599);
        Tretja.Opravilo o42 = new Tretja.Opravilo("o42", 379);
        Tretja.Opravilo o43 = new Tretja.Opravilo("o43", 846);

        Tretja.Projekt p0 = new Tretja.Projekt("p0", new Tretja.Opravilo[]{o3, o31, o32, o21, o27, o25, o17, o13, o19});
        Tretja.Projekt p1 = new Tretja.Projekt("p1", new Tretja.Opravilo[]{o19, o17, o21, o3, o27, o31, o32, o25, o13});
        Tretja.Projekt p2 = new Tretja.Projekt("p2", new Tretja.Opravilo[]{o19, o21, o3});
        Tretja.Projekt p3 = new Tretja.Projekt("p3", new Tretja.Opravilo[]{o21, o19, o3});
        Tretja.Projekt p4 = new Tretja.Projekt("p4", new Tretja.Opravilo[]{o19, o21, o3});
        Tretja.Projekt p5 = new Tretja.Projekt("p5", new Tretja.Opravilo[]{o14, o18, o31, o10, o24, o0, o2, o7});
        Tretja.Projekt p6 = new Tretja.Projekt("p6", new Tretja.Opravilo[]{o10, o18, o40, o32, o6, o41, o12, o5, o39});
        Tretja.Projekt p7 = new Tretja.Projekt("p7", new Tretja.Opravilo[]{o32, o25, o31, o3, o17, o19, o27});
        Tretja.Projekt p8 = new Tretja.Projekt("p8", new Tretja.Opravilo[]{o9, o12, o14, o1, o28, o27, o2, o40, o15});
        Tretja.Projekt p9 = new Tretja.Projekt("p9", new Tretja.Opravilo[]{o13, o32, o31, o3, o17, o21, o27, o25, o19});
        Tretja.Projekt p10 = new Tretja.Projekt("p10", new Tretja.Opravilo[]{o3});
        Tretja.Projekt p11 = new Tretja.Projekt("p11", new Tretja.Opravilo[]{o3, o21, o17, o27, o31, o25, o19, o13, o32});
        Tretja.Projekt p12 = new Tretja.Projekt("p12", new Tretja.Opravilo[]{o39, o6, o18, o41, o5});
        Tretja.Projekt p13 = new Tretja.Projekt("p13", new Tretja.Opravilo[]{o12, o1, o40, o9, o28, o27, o15, o14, o2});
        Tretja.Projekt p14 = new Tretja.Projekt("p14", new Tretja.Opravilo[]{o31, o14, o2, o7, o18, o24, o10, o0});
        Tretja.Projekt p15 = new Tretja.Projekt("p15", new Tretja.Opravilo[]{o3});
        Tretja.Projekt p16 = new Tretja.Projekt("p16", new Tretja.Opravilo[]{o8, o22, o25, o35});
        Tretja.Projekt p17 = new Tretja.Projekt("p17", new Tretja.Opravilo[]{o16});
        Tretja.Projekt p18 = new Tretja.Projekt("p18", new Tretja.Opravilo[]{o2, o12, o15, o27, o28, o40, o14, o1, o9});

        System.out.println(p2.jePermutacijaOd(p17));
        System.out.println(p14.jePermutacijaOd(p8));
        System.out.println(p17.jePermutacijaOd(p0));
        System.out.println(p10.jePermutacijaOd(p14));
        System.out.println(p4.jePermutacijaOd(p5));
        System.out.println(p2.jePermutacijaOd(p7));
        System.out.println(p8.jePermutacijaOd(p13));
        System.out.println(p4.jePermutacijaOd(p17));
        System.out.println(p10.jePermutacijaOd(p18));
        System.out.println(p4.jePermutacijaOd(p6));
        System.out.println(p5.jePermutacijaOd(p1));
        System.out.println(p9.jePermutacijaOd(p0));
        System.out.println(p18.jePermutacijaOd(p12));
        System.out.println(p7.jePermutacijaOd(p0));
        System.out.println(p15.jePermutacijaOd(p3));
        System.out.println(p14.jePermutacijaOd(p3));
        System.out.println(p10.jePermutacijaOd(p17));
        System.out.println(p3.jePermutacijaOd(p5));
        System.out.println(p16.jePermutacijaOd(p0));
        System.out.println(p5.jePermutacijaOd(p12));
        System.out.println(p13.jePermutacijaOd(p11));
        System.out.println(p9.jePermutacijaOd(p18));
        System.out.println(p16.jePermutacijaOd(p11));
        System.out.println(p12.jePermutacijaOd(p5));
        System.out.println(p17.jePermutacijaOd(p6));
        System.out.println(p14.jePermutacijaOd(p17));
        System.out.println(p3.jePermutacijaOd(p13));
        System.out.println(p12.jePermutacijaOd(p2));
        System.out.println(p6.jePermutacijaOd(p8));
        System.out.println(p14.jePermutacijaOd(p11));
        System.out.println(p18.jePermutacijaOd(p11));
        System.out.println(p5.jePermutacijaOd(p6));
        System.out.println(p16.jePermutacijaOd(p13));
        System.out.println(p10.jePermutacijaOd(p5));
        System.out.println(p18.jePermutacijaOd(p9));
        System.out.println(p7.jePermutacijaOd(p4));
        System.out.println(p7.jePermutacijaOd(p17));
        System.out.println(p6.jePermutacijaOd(p11));
        System.out.println(p14.jePermutacijaOd(p16));
        System.out.println(p2.jePermutacijaOd(p3));
        System.out.println(p6.jePermutacijaOd(p1));
        System.out.println(p14.jePermutacijaOd(p0));
        System.out.println(p2.jePermutacijaOd(p12));
        System.out.println(p1.jePermutacijaOd(p14));
        System.out.println(p7.jePermutacijaOd(p10));
        System.out.println(p7.jePermutacijaOd(p15));
        System.out.println(p14.jePermutacijaOd(p6));
        System.out.println(p1.jePermutacijaOd(p5));
        System.out.println(p5.jePermutacijaOd(p12));
        System.out.println(p6.jePermutacijaOd(p15));
        System.out.println(p0.jePermutacijaOd(p8));
        System.out.println(p14.jePermutacijaOd(p4));
        System.out.println(p5.jePermutacijaOd(p14));
        System.out.println(p11.jePermutacijaOd(p17));
        System.out.println(p18.jePermutacijaOd(p13));
        System.out.println(p15.jePermutacijaOd(p14));
        System.out.println(p7.jePermutacijaOd(p17));
        System.out.println(p12.jePermutacijaOd(p10));
        System.out.println(p13.jePermutacijaOd(p15));
        System.out.println(p5.jePermutacijaOd(p16));
        System.out.println(p12.jePermutacijaOd(p17));
        System.out.println(p5.jePermutacijaOd(p2));
        System.out.println(p3.jePermutacijaOd(p14));
        System.out.println(p1.jePermutacijaOd(p17));
        System.out.println(p15.jePermutacijaOd(p0));
        System.out.println(p8.jePermutacijaOd(p6));
    }
}
