
public class Test08 {

    public static void main(String[] args) {
        StiriVVrsto igra = new StiriVVrsto(20, 25);
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        igra.vrzi(9);
        igra.vrzi(9);
        igra.vrzi(9);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(20);
        igra.vrzi(1);
        igra.vrzi(13);
        igra.vrzi(12);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        igra.vrzi(4);
        igra.vrzi(15);
        igra.vrzi(22);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        igra.vrzi(5);
        igra.vrzi(12);
        igra.vrzi(19);
        igra.vrzi(19);
        igra.vrzi(7);
        igra.vrzi(13);
        igra.vrzi(6);
        igra.vrzi(0);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(14);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(22);
        igra.vrzi(10);
        igra.vrzi(9);
        igra.vrzi(5);
        igra.vrzi(6);
        igra.vrzi(8);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(13);
        igra.vrzi(10);
        igra.vrzi(21);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(22);
        igra.vrzi(17);
        igra.vrzi(11);
        igra.vrzi(18);
        igra.vrzi(18);
        igra.vrzi(3);
        igra.vrzi(14);
        igra.vrzi(4);
        igra.vrzi(13);
        igra.vrzi(11);
        igra.vrzi(12);
        igra.vrzi(3);
        igra.vrzi(6);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(24);
        igra.vrzi(9);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(13);
        igra.vrzi(21);
        igra.vrzi(10);
        igra.vrzi(19);
        igra.vrzi(3);
        igra.vrzi(11);
        igra.vrzi(7);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(12);
        igra.vrzi(3);
        igra.vrzi(6);
        igra.vrzi(23);
        igra.vrzi(11);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(19);
        igra.vrzi(22);
        igra.vrzi(10);
        igra.vrzi(22);
        igra.vrzi(6);
        igra.vrzi(3);
        igra.vrzi(22);
        igra.vrzi(23);
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(3);
        igra.vrzi(12);
        igra.vrzi(18);
        igra.vrzi(18);
        igra.vrzi(16);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(16);
        igra.vrzi(8);
        igra.vrzi(9);
        igra.vrzi(20);
        igra.vrzi(6);
        igra.vrzi(12);
        igra.vrzi(15);
        igra.vrzi(0);
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(11);
        igra.vrzi(15);
        igra.vrzi(9);
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(6);
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(17);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(23);
        igra.vrzi(2);
        igra.vrzi(13);
        igra.vrzi(4);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(3);
        igra.vrzi(4);
        igra.vrzi(16);
        igra.vrzi(17);
        igra.vrzi(4);
        igra.vrzi(15);
        igra.vrzi(12);
        igra.vrzi(17);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(16);
        igra.vrzi(4);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(23);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(10);
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(20);
        igra.vrzi(5);
        igra.vrzi(9);
        igra.vrzi(18);
        igra.vrzi(22);
        igra.vrzi(12);
        igra.vrzi(19);
        igra.vrzi(21);
        igra.vrzi(12);
        igra.vrzi(10);
        igra.vrzi(15);
        igra.vrzi(13);
        igra.vrzi(3);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(20);
        igra.vrzi(15);
        igra.vrzi(20);
        igra.vrzi(8);
        igra.vrzi(3);
        igra.vrzi(19);
        igra.vrzi(2);
        igra.vrzi(17);
        igra.vrzi(19);
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(3);
        igra.vrzi(1);
        igra.vrzi(6);
        igra.vrzi(19);
        igra.vrzi(17);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(20);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(12);
        igra.vrzi(5);
        igra.vrzi(12);
        igra.vrzi(3);
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        igra.vrzi(9);
        igra.vrzi(7);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(6);
        igra.vrzi(6);
        igra.vrzi(4);
        igra.vrzi(9);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(16);
        igra.vrzi(15);
        igra.vrzi(5);
        igra.vrzi(2);
        igra.vrzi(23);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(18);
        igra.vrzi(0);
        igra.vrzi(5);
        igra.vrzi(8);
        igra.vrzi(10);
        igra.vrzi(16);
        igra.vrzi(10);
        igra.vrzi(24);
        igra.vrzi(3);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(2);
        igra.vrzi(6);
        igra.vrzi(12);
        igra.vrzi(0);
        igra.vrzi(14);
        igra.vrzi(8);
        igra.vrzi(3);
        igra.vrzi(16);
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(23);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(16);
        igra.vrzi(23);
        igra.vrzi(11);
        igra.vrzi(13);
        igra.vrzi(3);
        igra.vrzi(14);
        igra.vrzi(17);
        igra.vrzi(7);
        igra.vrzi(4);
        igra.vrzi(10);
        igra.vrzi(21);
        igra.vrzi(0);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(9);
        igra.vrzi(12);
        igra.vrzi(20);
        igra.vrzi(20);
        igra.vrzi(18);
        igra.vrzi(23);
        igra.vrzi(22);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(8);
        igra.vrzi(23);
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(23);
        igra.vrzi(22);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(23);
        igra.vrzi(6);
        igra.vrzi(3);
        igra.vrzi(18);
        igra.vrzi(23);
        igra.vrzi(14);
        igra.vrzi(21);
        igra.vrzi(24);
        igra.vrzi(23);
        igra.vrzi(17);
        igra.vrzi(10);
        igra.vrzi(2);
        igra.vrzi(10);
        igra.vrzi(14);
        igra.vrzi(20);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(17);
        igra.vrzi(20);
        igra.vrzi(19);
        igra.vrzi(9);
        igra.vrzi(4);
        igra.vrzi(12);
        igra.vrzi(12);
        igra.vrzi(7);
        igra.vrzi(16);
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(7);
        igra.vrzi(3);
        igra.vrzi(23);
        igra.vrzi(0);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        igra.vrzi(12);
        igra.vrzi(5);
        igra.vrzi(3);
        igra.vrzi(12);
        igra.vrzi(23);
        igra.vrzi(16);
        igra.vrzi(3);
        igra.vrzi(24);
        igra.vrzi(8);
        igra.vrzi(18);
        igra.vrzi(23);
        igra.vrzi(18);
        igra.vrzi(24);
        igra.vrzi(4);
        igra.vrzi(6);
        igra.vrzi(10);
        igra.vrzi(14);
        igra.vrzi(5);
        igra.vrzi(23);
        igra.vrzi(12);
        igra.vrzi(15);
        igra.vrzi(10);
        igra.vrzi(18);
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(12);
        igra.vrzi(5);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(6);
        igra.vrzi(9);
        igra.vrzi(14);
        igra.vrzi(17);
        igra.vrzi(6);
        igra.vrzi(22);
        igra.vrzi(0);
        igra.vrzi(22);
        igra.vrzi(4);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(2);
        igra.vrzi(10);
        igra.vrzi(24);
        igra.vrzi(9);
        igra.vrzi(19);
        igra.vrzi(14);
        igra.vrzi(1);
        igra.vrzi(5);
        igra.vrzi(22);
        igra.vrzi(10);
        igra.vrzi(12);
        igra.vrzi(6);
        igra.vrzi(16);
        igra.vrzi(4);
        igra.vrzi(14);
        igra.vrzi(9);
        igra.vrzi(15);
        igra.vrzi(7);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(12);
        igra.vrzi(7);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(4);
        igra.vrzi(11);
        igra.vrzi(14);
        igra.vrzi(6);
        igra.vrzi(19);
        igra.vrzi(14);
        igra.vrzi(6);
        igra.vrzi(21);
        igra.vrzi(3);
        igra.vrzi(13);
        igra.vrzi(10);
        igra.vrzi(10);
        igra.vrzi(23);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(23);
        igra.vrzi(7);
        igra.vrzi(4);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(18);
        igra.vrzi(7);
        igra.vrzi(11);
        igra.vrzi(1);
        igra.vrzi(12);
        igra.vrzi(7);
        igra.vrzi(3);
        igra.vrzi(23);
        igra.vrzi(20);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(7);
        igra.vrzi(16);
        igra.vrzi(24);
        igra.vrzi(20);
        igra.vrzi(7);
        igra.vrzi(18);
        igra.vrzi(12);
        igra.vrzi(9);
        igra.vrzi(3);
        igra.vrzi(21);
        igra.vrzi(18);
        igra.vrzi(15);
        igra.vrzi(24);
        igra.vrzi(16);
        igra.vrzi(2);
        igra.vrzi(22);
        igra.vrzi(9);
        igra.vrzi(14);
        igra.vrzi(4);
        igra.vrzi(14);
        igra.vrzi(4);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        igra.vrzi(10);
        igra.vrzi(20);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(13);
        igra.vrzi(8);
        igra.vrzi(15);
        igra.vrzi(24);
        igra.vrzi(8);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(14);
        igra.vrzi(6);
        igra.vrzi(1);
        igra.vrzi(15);
        igra.vrzi(16);
        igra.vrzi(13);
        igra.vrzi(18);
        igra.vrzi(10);
        igra.vrzi(11);
        igra.vrzi(10);
        igra.vrzi(9);
        igra.vrzi(23);
        igra.vrzi(13);
        igra.vrzi(2);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(23);
        igra.vrzi(21);
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(12);
        igra.vrzi(3);
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(19);
        igra.vrzi(23);
        igra.vrzi(1);
        igra.vrzi(10);
        igra.vrzi(1);
        igra.vrzi(5);
        igra.vrzi(11);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(15);
        igra.vrzi(1);
        igra.vrzi(9);
        igra.vrzi(18);
        igra.vrzi(20);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(9);
        igra.vrzi(2);
        igra.vrzi(6);
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(24);
        igra.vrzi(13);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(2);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(3);
        igra.vrzi(19);
        igra.vrzi(18);
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(3);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        igra.vrzi(23);
        igra.vrzi(14);
        igra.vrzi(22);
        igra.vrzi(7);
        igra.vrzi(12);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(4);
        igra.vrzi(3);
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(5);
        igra.vrzi(2);
        igra.vrzi(3);
        igra.vrzi(9);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(7);
        igra.vrzi(11);
        igra.vrzi(17);
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        igra.vrzi(9);
        igra.vrzi(11);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(22);
        igra.vrzi(10);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(20);
        igra.vrzi(11);
        igra.vrzi(20);
        igra.vrzi(16);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(9);
        igra.vrzi(16);
        igra.vrzi(1);
        igra.vrzi(20);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(24);
        igra.vrzi(18);
        igra.vrzi(22);
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(22);
        igra.vrzi(13);
        igra.vrzi(19);
        igra.vrzi(4);
        igra.vrzi(5);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(8);
        igra.vrzi(3);
        igra.vrzi(0);
        igra.vrzi(19);
        igra.vrzi(5);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(10);
        igra.vrzi(19);
        igra.vrzi(16);
        igra.vrzi(1);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(2);
        igra.vrzi(24);
        igra.vrzi(12);
        igra.vrzi(14);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(20);
        igra.vrzi(16);
        igra.vrzi(15);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(19);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(1);
        igra.vrzi(3);
        igra.vrzi(20);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(11);
        igra.vrzi(0);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(13);
        igra.vrzi(12);
        igra.vrzi(12);
        igra.vrzi(18);
        igra.vrzi(10);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(4);
        igra.vrzi(17);
        igra.vrzi(11);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(2);
        igra.vrzi(6);
        igra.vrzi(18);
        igra.vrzi(22);
        igra.vrzi(6);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(0);
        igra.vrzi(9);
        igra.vrzi(11);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(21);
        igra.vrzi(12);
        igra.vrzi(2);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(19);
        igra.vrzi(9);
        igra.vrzi(4);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
        igra.vrzi(12);
        igra.vrzi(8);
        igra.vrzi(20);
        igra.vrzi(8);
        igra.vrzi(11);
        igra.vrzi(8);
        System.out.printf("%d/%d%n", igra.najdaljseZaporedje(0), igra.najdaljseZaporedje(1));
    }
}
