
public class Test36 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_deNHD");
        t.prejmi(new Tretja.Docent(), "doc_zPsio");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5kLTb");
        t.prejmi(new Tretja.Docent(), "doc_VvhpH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iG3Ws");
        t.prejmi(new Tretja.Docent(), "doc_humj0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_yGduG");
        t.prejmi(new Tretja.Profesor(), "prof_FtdHI");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6Jyr7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_nkDAL");
        t.prejmi(new Tretja.Profesor(), "prof_DIyO3");
        t.prejmi(new Tretja.Profesor(), "prof_bYUwB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZjXcl");
        t.prejmi(new Tretja.Asistent(), "as_jaY6R");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hgJgU");
        t.prejmi(new Tretja.Asistent(), "as_fYrcl");
        t.prejmi(new Tretja.Profesor(), "prof_xSNtk");
        t.prejmi(new Tretja.Asistent(), "as_CKfzu");
        t.prejmi(new Tretja.Asistent(), "as_LYQSp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5LoZn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_iPm7c");
        t.prejmi(new Tretja.Asistent(), "as_FLhHN");
        t.prejmi(new Tretja.Asistent(), "as_t7F5z");
        t.prejmi(new Tretja.Docent(), "doc_ihH6Q");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_jR4zy");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_DUqCK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_f9o7E");
        t.prejmi(new Tretja.Asistent(), "as_5Gsl4");
        t.prejmi(new Tretja.Asistent(), "as_mRkHa");
        t.prejmi(new Tretja.Docent(), "doc_CjKtt");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_AXPHN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_UdL8w");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_UZRaR");
        t.prejmi(new Tretja.Asistent(), "as_74dSp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_NDC4Z");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_KLgnk");
        t.prejmi(new Tretja.Profesor(), "prof_FYv7l");
        t.prejmi(new Tretja.Profesor(), "prof_Tmolz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_aqLdL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8tcMe");
        t.prejmi(new Tretja.Asistent(), "as_dnRl3");
        t.prejmi(new Tretja.Asistent(), "as_REOmK");
        t.prejmi(new Tretja.Docent(), "doc_OAxSz");
        t.prejmi(new Tretja.Docent(), "doc_HwW9U");
        t.prejmi(new Tretja.Docent(), "doc_7mwR4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_FUtGf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_KGbp7");
        t.prejmi(new Tretja.Profesor(), "prof_ThYCH");
        t.prejmi(new Tretja.Profesor(), "prof_Y2yvc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XvNFJ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w962S");
        t.prejmi(new Tretja.Asistent(), "as_v3f5s");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_uGOuc");
        t.prejmi(new Tretja.Docent(), "doc_pMJ0X");
        t.prejmi(new Tretja.Asistent(), "as_vAIqV");
        t.prejmi(new Tretja.Asistent(), "as_9S4mM");
        t.prejmi(new Tretja.Docent(), "doc_wFGkf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rcVtr");
        t.prejmi(new Tretja.Profesor(), "prof_H5y3G");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_CcZLX");
        t.prejmi(new Tretja.Profesor(), "prof_Vi8LQ");
        t.prejmi(new Tretja.Profesor(), "prof_7zecQ");
        t.prejmi(new Tretja.Profesor(), "prof_che44");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hIqy3");
        t.prejmi(new Tretja.Profesor(), "prof_FxlsL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Begcm");
        t.prejmi(new Tretja.Asistent(), "as_3zUU5");
        t.prejmi(new Tretja.Asistent(), "as_y7hk4");
        t.prejmi(new Tretja.Asistent(), "as_oqGT7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TW0hv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_si9in");
        t.prejmi(new Tretja.Profesor(), "prof_MJFvy");
        t.prejmi(new Tretja.Asistent(), "as_VVQx3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HPDzC");
        t.prejmi(new Tretja.Docent(), "doc_MSFtk");
        t.prejmi(new Tretja.Asistent(), "as_0ksG5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ojYga");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ZVaM3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_7JKgX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_LBPLY");
        t.prejmi(new Tretja.Docent(), "doc_hj5VW");
        t.prejmi(new Tretja.Asistent(), "as_iRDSc");
        t.prejmi(new Tretja.Docent(), "doc_o0Ste");
        t.prejmi(new Tretja.Profesor(), "prof_eOiw9");
        t.prejmi(new Tretja.Profesor(), "prof_H4mSL");
        t.prejmi(new Tretja.Profesor(), "prof_mQEEz");
        t.prejmi(new Tretja.Asistent(), "as_oq0Lk");
        t.prejmi(new Tretja.Profesor(), "prof_41NSE");
        t.prejmi(new Tretja.Asistent(), "as_9EKEE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_bBpG9");
        t.prejmi(new Tretja.Docent(), "doc_E6JSq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_i5cKo");
        t.prejmi(new Tretja.Docent(), "doc_DgtuY");
        t.prejmi(new Tretja.Asistent(), "as_OM6p0");
        t.prejmi(new Tretja.Profesor(), "prof_R3i0I");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vXAlN");
        t.prejmi(new Tretja.Asistent(), "as_Wp1Al");
        t.prejmi(new Tretja.Profesor(), "prof_yA6ea");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_w8A2I");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lRMx1");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TeXvn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_MjASG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZdOxv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_fhzjk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_84X1t");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_SHEIL");
        t.prejmi(new Tretja.Profesor(), "prof_XQXzI");
        t.prejmi(new Tretja.Docent(), "doc_Xytr7");
        t.prejmi(new Tretja.Docent(), "doc_YSzbF");
        t.prejmi(new Tretja.Docent(), "doc_qre2w");
        t.prejmi(new Tretja.Profesor(), "prof_xcwBs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NMbpa");
        t.prejmi(new Tretja.Asistent(), "as_zH6Cj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_W3UCk");
        t.prejmi(new Tretja.Profesor(), "prof_vnJfJ");
        t.prejmi(new Tretja.Asistent(), "as_kuRo4");
        t.prejmi(new Tretja.Profesor(), "prof_UIjVo");
        t.prejmi(new Tretja.Profesor(), "prof_3NeEE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rMz5n");
        t.prejmi(new Tretja.Asistent(), "as_S4dMM");
        t.prejmi(new Tretja.Asistent(), "as_hwhOy");
        t.prejmi(new Tretja.Asistent(), "as_6eaqj");
        t.prejmi(new Tretja.Docent(), "doc_Q96BT");
        t.prejmi(new Tretja.Asistent(), "as_jq3gt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_JJJjB");
        t.prejmi(new Tretja.Asistent(), "as_Ikd5O");
        t.prejmi(new Tretja.Profesor(), "prof_rI8pH");
        t.prejmi(new Tretja.Docent(), "doc_Xq38T");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Nwr42");
        t.prejmi(new Tretja.Docent(), "doc_Grqgz");
        t.prejmi(new Tretja.Docent(), "doc_7Rnzz");
        t.prejmi(new Tretja.Docent(), "doc_1nSZr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SiBGa");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_R2w4Z");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_EB0ga");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_quPMs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_zIms1");
        t.prejmi(new Tretja.Docent(), "doc_1NCbO");
        t.prejmi(new Tretja.Asistent(), "as_hC5QG");
        t.prejmi(new Tretja.Asistent(), "as_5yciS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IoC6n");
        t.prejmi(new Tretja.Asistent(), "as_Vfv6E");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_d0Mbi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XUXeM");
        t.prejmi(new Tretja.Asistent(), "as_ZZQ26");
        t.prejmi(new Tretja.Profesor(), "prof_xFFm6");
        t.prejmi(new Tretja.Profesor(), "prof_ni0qU");
        t.prejmi(new Tretja.Docent(), "doc_5OaEj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_jAc7o");
        t.prejmi(new Tretja.Asistent(), "as_ep2uM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_huM1l");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1yDXR");
        t.prejmi(new Tretja.Docent(), "doc_wjkSE");
        t.prejmi(new Tretja.Profesor(), "prof_2ZswW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HHQ44");
        t.prejmi(new Tretja.Profesor(), "prof_SCYC2");
        t.prejmi(new Tretja.Profesor(), "prof_0WUZD");
        t.prejmi(new Tretja.Asistent(), "as_zWtoI");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_32X2B");
        t.prejmi(new Tretja.Asistent(), "as_AQCXf");
        t.prejmi(new Tretja.Docent(), "doc_eFVa2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iwzLe");
        t.prejmi(new Tretja.Asistent(), "as_IGWP0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rAPoM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_BkYfS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_fsE22");
        t.prejmi(new Tretja.Profesor(), "prof_CF5vI");
        t.prejmi(new Tretja.Profesor(), "prof_8wR3M");
        t.prejmi(new Tretja.Asistent(), "as_VQfv4");
        t.prejmi(new Tretja.Profesor(), "prof_k2O0z");
        t.prejmi(new Tretja.Profesor(), "prof_28uIu");
        t.prejmi(new Tretja.Docent(), "doc_eFaVW");
        t.prejmi(new Tretja.Asistent(), "as_fk4hB");
        t.prejmi(new Tretja.Asistent(), "as_mUMvs");
        t.prejmi(new Tretja.Docent(), "doc_tFdnT");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6fiht");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_wrwtS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_mzeVw");
        t.prejmi(new Tretja.Profesor(), "prof_C1T9Q");
        t.prejmi(new Tretja.Asistent(), "as_3DvzI");
        t.prejmi(new Tretja.Asistent(), "as_oIcTe");
        t.prejmi(new Tretja.Asistent(), "as_nqk1V");
        t.prejmi(new Tretja.Profesor(), "prof_AyWXF");
        t.prejmi(new Tretja.Profesor(), "prof_EhW5F");
        t.prejmi(new Tretja.Profesor(), "prof_4fvFE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_YumZP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rYNV8");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1GKpM");
        t.prejmi(new Tretja.Profesor(), "prof_UOsZl");
        t.prejmi(new Tretja.Profesor(), "prof_XBp2f");
        t.prejmi(new Tretja.Asistent(), "as_OkMWm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0XtHr");
        t.prejmi(new Tretja.Docent(), "doc_oMwNm");
        t.prejmi(new Tretja.Asistent(), "as_46cR9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_yv4pO");
        t.prejmi(new Tretja.Asistent(), "as_CJpW1");
        t.prejmi(new Tretja.Asistent(), "as_H41Vp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TUCWX");
        t.prejmi(new Tretja.Profesor(), "prof_Rt1tE");
        t.prejmi(new Tretja.Profesor(), "prof_DftWt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_KlR8p");
        t.prejmi(new Tretja.Docent(), "doc_BurzA");
        t.prejmi(new Tretja.Docent(), "doc_Fwqy9");
        t.prejmi(new Tretja.Profesor(), "prof_P0LDY");
        t.prejmi(new Tretja.Asistent(), "as_auFFu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Bbint");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_VmDxs");
        t.prejmi(new Tretja.Profesor(), "prof_5LqTZ");
        t.prejmi(new Tretja.Asistent(), "as_lmOPp");
        t.prejmi(new Tretja.Asistent(), "as_RSjib");
        t.prejmi(new Tretja.Asistent(), "as_HLFMS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_O6Rtm");
        t.prejmi(new Tretja.Profesor(), "prof_olbBm");
        t.prejmi(new Tretja.Asistent(), "as_iNZsc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_mEIsr");
        t.prejmi(new Tretja.Profesor(), "prof_SVJ5j");
        t.prejmi(new Tretja.Docent(), "doc_6Gk5D");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZJEae");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_goSvf");
        t.prejmi(new Tretja.Profesor(), "prof_yf9v3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_tgvvE");
        t.prejmi(new Tretja.Profesor(), "prof_wXCPR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Fg6hk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0Zquj");
        t.prejmi(new Tretja.Asistent(), "as_jAuDL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_KlaSu");
        t.prejmi(new Tretja.Profesor(), "prof_Jim2L");
        t.prejmi(new Tretja.Docent(), "doc_8n9CB");
        t.prejmi(new Tretja.Asistent(), "as_KNh2x");
        t.prejmi(new Tretja.Docent(), "doc_BajhX");
        t.prejmi(new Tretja.Docent(), "doc_GWnDe");
        t.prejmi(new Tretja.Asistent(), "as_AMbWx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IY8GJ");
        t.prejmi(new Tretja.Profesor(), "prof_OsiUz");
        t.prejmi(new Tretja.Asistent(), "as_FICyr");
        t.prejmi(new Tretja.Docent(), "doc_WVTnR");
        t.prejmi(new Tretja.Profesor(), "prof_xDwet");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VMZ1V");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ASKqB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_A8nHi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_su5da");
        t.prejmi(new Tretja.Profesor(), "prof_M6j3g");
        t.prejmi(new Tretja.Docent(), "doc_U9tKK");
        t.prejmi(new Tretja.Asistent(), "as_Ov3sP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_8nTlo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Q6oQC");
        t.prejmi(new Tretja.Profesor(), "prof_A6a1H");
        t.prejmi(new Tretja.Profesor(), "prof_Nxctm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HEzKm");
        t.prejmi(new Tretja.Asistent(), "as_gJWCE");
        t.prejmi(new Tretja.Profesor(), "prof_HYh1c");
        t.prejmi(new Tretja.Docent(), "doc_GN9MV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uvUbR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_cCRgc");
        t.prejmi(new Tretja.Docent(), "doc_s8lyx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_lAQjR");
        t.prejmi(new Tretja.Asistent(), "as_HuCOR");
        t.prejmi(new Tretja.Docent(), "doc_aX9CN");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tZxC4");
        t.prejmi(new Tretja.Asistent(), "as_XFz3n");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_8Zvfw");
        t.prejmi(new Tretja.Profesor(), "prof_jVGDH");
        t.prejmi(new Tretja.Profesor(), "prof_AaXo3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_PSofj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5EcXL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JqZkh");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_VsZ7K");
        t.prejmi(new Tretja.Docent(), "doc_q2M0Y");
        t.prejmi(new Tretja.Asistent(), "as_uNLwI");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_oCUVw");
        t.prejmi(new Tretja.Docent(), "doc_BrpRS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Omm3n");
        t.prejmi(new Tretja.Docent(), "doc_qT53X");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_dVwoK");
        t.prejmi(new Tretja.Asistent(), "as_QbAkv");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_os1pf");
        t.prejmi(new Tretja.Asistent(), "as_8jibI");
        t.prejmi(new Tretja.Profesor(), "prof_LS4vM");
        t.prejmi(new Tretja.Docent(), "doc_WBqsK");
        t.prejmi(new Tretja.Asistent(), "as_OQvbW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VfL2B");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ggnsU");
        t.prejmi(new Tretja.Docent(), "doc_eJDUu");
        t.prejmi(new Tretja.Profesor(), "prof_En5J9");
        System.out.println(t.natisni());
    }
}
