
public class Test22 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_wo2Eq");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_PXSab");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_CGu6R");
        t.prejmi(new Tretja.Docent(), "doc_f632V");
        t.prejmi(new Tretja.Docent(), "doc_2UKwv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_QKe0U");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_JRtsE");
        t.prejmi(new Tretja.Asistent(), "as_ItckZ");
        t.prejmi(new Tretja.Profesor(), "prof_EtjmZ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_ZWbNV");
        t.prejmi(new Tretja.Asistent(), "as_5OeJg");
        t.prejmi(new Tretja.Docent(), "doc_QiUeb");
        t.prejmi(new Tretja.Profesor(), "prof_TiUBZ");
        t.prejmi(new Tretja.Docent(), "doc_hjj2x");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_iU6La");
        t.prejmi(new Tretja.Asistent(), "as_3hN33");
        t.prejmi(new Tretja.Asistent(), "as_RzDZe");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_HAAZz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_w6FwP");
        t.prejmi(new Tretja.Asistent(), "as_Ym6W3");
        t.prejmi(new Tretja.Asistent(), "as_gNtXA");
        t.prejmi(new Tretja.Asistent(), "as_cTk7n");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_tEUju");
        t.prejmi(new Tretja.Asistent(), "as_jUhSV");
        t.prejmi(new Tretja.Docent(), "doc_hl03v");
        t.prejmi(new Tretja.Docent(), "doc_dvylX");
        t.prejmi(new Tretja.Docent(), "doc_8N1Ab");
        t.prejmi(new Tretja.Profesor(), "prof_1Wies");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_wkA8f");
        t.prejmi(new Tretja.Asistent(), "as_HZ0zx");
        t.prejmi(new Tretja.Asistent(), "as_Pt7C6");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_14zdK");
        t.prejmi(new Tretja.Profesor(), "prof_BEPBK");
        t.prejmi(new Tretja.Asistent(), "as_0iHXn");
        t.prejmi(new Tretja.Asistent(), "as_k2SSj");
        t.prejmi(new Tretja.Profesor(), "prof_2phfB");
        t.prejmi(new Tretja.Asistent(), "as_NZMy8");
        t.prejmi(new Tretja.Docent(), "doc_Ov1pN");
        t.prejmi(new Tretja.Asistent(), "as_ceVrc");
        t.prejmi(new Tretja.Docent(), "doc_xHsj3");
        t.prejmi(new Tretja.Profesor(), "prof_5UZxl");
        t.prejmi(new Tretja.Profesor(), "prof_q2LYT");
        t.prejmi(new Tretja.Profesor(), "prof_mcQkw");
        t.prejmi(new Tretja.Docent(), "doc_Eo2TC");
        t.prejmi(new Tretja.Profesor(), "prof_SNhX2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_qWyDw");
        t.prejmi(new Tretja.Asistent(), "as_KFWEm");
        t.prejmi(new Tretja.Docent(), "doc_N8MFt");
        t.prejmi(new Tretja.Profesor(), "prof_VFhGz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_PM5rI");
        t.prejmi(new Tretja.Profesor(), "prof_BK5vr");
        t.prejmi(new Tretja.Profesor(), "prof_XbkZH");
        t.prejmi(new Tretja.Docent(), "doc_ZWMpx");
        t.prejmi(new Tretja.Docent(), "doc_6n0ZH");
        t.prejmi(new Tretja.Asistent(), "as_IHMoG");
        t.prejmi(new Tretja.Docent(), "doc_8QBUy");
        t.prejmi(new Tretja.Profesor(), "prof_X6QB8");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_oUllw");
        t.prejmi(new Tretja.Docent(), "doc_gmK77");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_3qfdY");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_6P6n2");
        t.prejmi(new Tretja.Profesor(), "prof_ETULy");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_SMAUY");
        t.prejmi(new Tretja.Asistent(), "as_9WPmN");
        t.prejmi(new Tretja.Docent(), "doc_UUR1S");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_ioVp8");
        t.prejmi(new Tretja.Docent(), "doc_Eqn7d");
        t.prejmi(new Tretja.Asistent(), "as_Kz70p");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_rHrlX");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_LWQp5");
        t.prejmi(new Tretja.Profesor(), "prof_cQg1d");
        t.prejmi(new Tretja.Docent(), "doc_xU7pe");
        t.prejmi(new Tretja.Profesor(), "prof_jh8xe");
        t.prejmi(new Tretja.Profesor(), "prof_Y5uti");
        t.prejmi(new Tretja.Profesor(), "prof_7zPEl");
        t.prejmi(new Tretja.Docent(), "doc_I5vrI");
        t.prejmi(new Tretja.Asistent(), "as_mTEU4");
        t.prejmi(new Tretja.Docent(), "doc_5aV9N");
        t.prejmi(new Tretja.Profesor(), "prof_obAz1");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_D1YdR");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_gofwl");
        t.prejmi(new Tretja.Profesor(), "prof_6LNMX");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_JAFVc");
        t.prejmi(new Tretja.Asistent(), "as_u1jae");
        t.prejmi(new Tretja.Docent(), "doc_1ZXR5");
        t.prejmi(new Tretja.Docent(), "doc_n6pDW");
        t.prejmi(new Tretja.Asistent(), "as_5t6td");
        t.prejmi(new Tretja.Profesor(), "prof_5wSZA");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_6a14u");
        t.prejmi(new Tretja.Docent(), "doc_YX03T");
        t.prejmi(new Tretja.Docent(), "doc_ZZHXV");
        t.prejmi(new Tretja.Docent(), "doc_4Rq1c");
        t.prejmi(new Tretja.Docent(), "doc_7NsKg");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_TjbkE");
        t.prejmi(new Tretja.Docent(), "doc_RxhOx");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_oAlZX");
        t.prejmi(new Tretja.Docent(), "doc_cFdYD");
        t.prejmi(new Tretja.Asistent(), "as_SYA7c");
        t.prejmi(new Tretja.Profesor(), "prof_RIM3d");
        t.prejmi(new Tretja.Profesor(), "prof_jdDT7");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_4ZkYA");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_bJWGD");
        t.prejmi(new Tretja.Profesor(), "prof_SYJho");
        t.prejmi(new Tretja.Asistent(), "as_TEw03");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_K6mNK");
        t.prejmi(new Tretja.Asistent(), "as_DZ5Kj");
        t.prejmi(new Tretja.Asistent(), "as_P0uAa");
        t.prejmi(new Tretja.Asistent(), "as_NYYsu");
        t.prejmi(new Tretja.Profesor(), "prof_kNdm7");
        t.prejmi(new Tretja.Profesor(), "prof_HmMWt");
        t.prejmi(new Tretja.Profesor(), "prof_LWcl2");
        t.prejmi(new Tretja.Asistent(), "as_KkJTJ");
        t.prejmi(new Tretja.Docent(), "doc_DCPdD");
        t.prejmi(new Tretja.Asistent(), "as_5M6MH");
        t.prejmi(new Tretja.Profesor(), "prof_HWGIe");
        t.prejmi(new Tretja.Asistent(), "as_Jp3si");
        t.prejmi(new Tretja.Profesor(), "prof_r0QOX");
        t.prejmi(new Tretja.Asistent(), "as_dSr9n");
        t.prejmi(new Tretja.Profesor(), "prof_ChsXg");
        t.prejmi(new Tretja.Asistent(), "as_6O5ip");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_USDHf");
        t.prejmi(new Tretja.Profesor(), "prof_ZcAy2");
        t.prejmi(new Tretja.Asistent(), "as_gugRl");
        t.prejmi(new Tretja.Asistent(), "as_2KJQp");
        t.prejmi(new Tretja.Asistent(), "as_w4ddp");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_JYy6X");
        t.prejmi(new Tretja.Profesor(), "prof_OBzmq");
        t.prejmi(new Tretja.Asistent(), "as_lQg0o");
        t.prejmi(new Tretja.Profesor(), "prof_UdI6X");
        t.prejmi(new Tretja.Profesor(), "prof_xJxNw");
        t.prejmi(new Tretja.Profesor(), "prof_eVu4k");
        t.prejmi(new Tretja.Profesor(), "prof_7EW5y");
        t.prejmi(new Tretja.Docent(), "doc_pLUGr");
        t.prejmi(new Tretja.Docent(), "doc_cpwIp");
        t.prejmi(new Tretja.Asistent(), "as_oXtiG");
        t.prejmi(new Tretja.Docent(), "doc_oFT8x");
        t.prejmi(new Tretja.Asistent(), "as_P2yQs");
        t.prejmi(new Tretja.Asistent(), "as_Q08Ix");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_B4BjV");
        t.prejmi(new Tretja.Asistent(), "as_Fi3Ij");
        t.prejmi(new Tretja.Docent(), "doc_y2Xl4");
        t.prejmi(new Tretja.Docent(), "doc_O2nhq");
        t.prejmi(new Tretja.Profesor(), "prof_Z5Jt8");
        t.prejmi(new Tretja.Asistent(), "as_5w8I5");
        t.prejmi(new Tretja.Profesor(), "prof_E2yzQ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_r1LLI");
        t.prejmi(new Tretja.Asistent(), "as_FZ3Br");
        t.prejmi(new Tretja.Docent(), "doc_drqKD");
        t.prejmi(new Tretja.Asistent(), "as_foWUv");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Kxbkj");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_JZ8sw");
        t.prejmi(new Tretja.Asistent(), "as_8jiaE");
        t.prejmi(new Tretja.Asistent(), "as_StkPR");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_NtKbS");
        t.prejmi(new Tretja.Docent(), "doc_vdFf6");
        t.prejmi(new Tretja.Profesor(), "prof_3Rjcu");
        t.prejmi(new Tretja.Docent(), "doc_TVz0W");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_fVZXu");
        t.prejmi(new Tretja.Profesor(), "prof_vKBQI");
        t.prejmi(new Tretja.Profesor(), "prof_3NtgN");
        t.prejmi(new Tretja.Docent(), "doc_ePCuS");
        t.prejmi(new Tretja.Docent(), "doc_75PMP");
        t.prejmi(new Tretja.Asistent(), "as_aELHy");
        t.prejmi(new Tretja.Profesor(), "prof_sL03Z");
        t.prejmi(new Tretja.Docent(), "doc_dP4tP");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_cQb1r");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_WjyzN");
        t.prejmi(new Tretja.Asistent(), "as_eFNJ9");
        t.prejmi(new Tretja.Profesor(), "prof_cBvWf");
        t.prejmi(new Tretja.Profesor(), "prof_tWWok");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_35xnR");
        t.prejmi(new Tretja.Asistent(), "as_Q9zm6");
        t.prejmi(new Tretja.Profesor(), "prof_7N9uJ");
        t.prejmi(new Tretja.Asistent(), "as_TXfVd");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_Splfy");
        t.prejmi(new Tretja.Profesor(), "prof_0xkbB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_9V9Qp");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_DeTTu");
        t.prejmi(new Tretja.Docent(), "doc_FwJYm");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_h73QN");
        t.prejmi(new Tretja.Profesor(), "prof_dtyOi");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_mObeI");
        t.prejmi(new Tretja.Docent(), "doc_eJVQZ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_OHqKU");
        t.prejmi(new Tretja.Profesor(), "prof_77SvU");
        t.prejmi(new Tretja.Profesor(), "prof_7UoPK");
        t.prejmi(new Tretja.Profesor(), "prof_F41Ng");
        t.prejmi(new Tretja.Profesor(), "prof_NA5e8");
        t.prejmi(new Tretja.Docent(), "doc_tK4Ry");
        t.prejmi(new Tretja.Profesor(), "prof_apkEl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Wy6AI");
        t.prejmi(new Tretja.Docent(), "doc_Woy6I");
        t.prejmi(new Tretja.Docent(), "doc_8vHIS");
        t.prejmi(new Tretja.Profesor(), "prof_RC3Fi");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_g4PTu");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_gGcBz");
        t.prejmi(new Tretja.Profesor(), "prof_5yF66");
        t.prejmi(new Tretja.Asistent(), "as_xhH13");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_LuTRt");
        t.prejmi(new Tretja.Asistent(), "as_O1ZoA");
        t.prejmi(new Tretja.Profesor(), "prof_fQ77G");
        t.prejmi(new Tretja.Asistent(), "as_e8jun");
        t.prejmi(new Tretja.Profesor(), "prof_O1Bl9");
        t.prejmi(new Tretja.Asistent(), "as_KQQAz");
        t.prejmi(new Tretja.Asistent(), "as_8iDKL");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_nJGFi");
        t.prejmi(new Tretja.Asistent(), "as_KXBFE");
        t.prejmi(new Tretja.Profesor(), "prof_aKh1V");
        t.prejmi(new Tretja.Asistent(), "as_0pZge");
        t.prejmi(new Tretja.Profesor(), "prof_iuWnk");
        t.prejmi(new Tretja.Docent(), "doc_zefzn");
        t.prejmi(new Tretja.Profesor(), "prof_R357C");
        t.prejmi(new Tretja.Asistent(), "as_j7acK");
        t.prejmi(new Tretja.Profesor(), "prof_eKDKa");
        t.prejmi(new Tretja.Asistent(), "as_GE6sZ");
        t.prejmi(new Tretja.Asistent(), "as_OvZKq");
        t.prejmi(new Tretja.Profesor(), "prof_EmGg4");
        t.prejmi(new Tretja.Profesor(), "prof_FVONc");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_j37Xl");
        t.prejmi(new Tretja.Profesor(), "prof_e0uL3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_ojlkD");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_5BtEb");
        t.prejmi(new Tretja.Docent(), "doc_HyNRB");
        t.prejmi(new Tretja.Profesor(), "prof_xQlIr");
        t.prejmi(new Tretja.Profesor(), "prof_BjDb7");
        t.prejmi(new Tretja.Asistent(), "as_Ab84G");
        t.prejmi(new Tretja.Profesor(), "prof_o3l3p");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_afwpR");
        t.prejmi(new Tretja.Docent(), "doc_Swu5V");
        t.prejmi(new Tretja.Docent(), "doc_cgldb");
        t.prejmi(new Tretja.Asistent(), "as_0KW5X");
        t.prejmi(new Tretja.Asistent(), "as_mRT0C");
        t.prejmi(new Tretja.Profesor(), "prof_y6E1n");
        t.prejmi(new Tretja.Asistent(), "as_yghXM");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_ntjK0");
        t.prejmi(new Tretja.Profesor(), "prof_aHYhv");
        t.prejmi(new Tretja.Asistent(), "as_wXJeg");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_BW2DH");
        t.prejmi(new Tretja.Docent(), "doc_BHWAv");
        t.prejmi(new Tretja.Asistent(), "as_fgZ6C");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_pspUE");
        t.prejmi(new Tretja.Profesor(), "prof_E1Scb");
        t.prejmi(new Tretja.Asistent(), "as_ecDkb");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_i2DOQ");
        t.prejmi(new Tretja.Asistent(), "as_PJvtk");
        t.prejmi(new Tretja.Asistent(), "as_r93WP");
        t.prejmi(new Tretja.Asistent(), "as_Z8wbm");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Ewv9W");
        t.prejmi(new Tretja.Docent(), "doc_RKqU6");
        t.prejmi(new Tretja.Profesor(), "prof_dHj5u");
        t.prejmi(new Tretja.Profesor(), "prof_9XxpI");
        t.prejmi(new Tretja.Asistent(), "as_xfaPw");
        t.prejmi(new Tretja.Asistent(), "as_gMMvo");
        t.prejmi(new Tretja.Asistent(), "as_9sClM");
        t.prejmi(new Tretja.Profesor(), "prof_Nw9xc");
        t.prejmi(new Tretja.Docent(), "doc_NW495");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_TPwfc");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_v1bXf");
        t.prejmi(new Tretja.Docent(), "doc_bvjnu");
        t.prejmi(new Tretja.Asistent(), "as_n7ujH");
        t.prejmi(new Tretja.Asistent(), "as_gBPHn");
        t.prejmi(new Tretja.Profesor(), "prof_OXsg6");
        t.prejmi(new Tretja.Profesor(), "prof_quTZg");
        t.prejmi(new Tretja.Asistent(), "as_nlvfQ");
        t.prejmi(new Tretja.Asistent(), "as_8I0wY");
        t.prejmi(new Tretja.Profesor(), "prof_JaHBG");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_lwrTS");
        t.prejmi(new Tretja.Docent(), "doc_yh62K");
        t.prejmi(new Tretja.Asistent(), "as_LZZu8");
        t.prejmi(new Tretja.Asistent(), "as_M9iQZ");
        t.prejmi(new Tretja.Profesor(), "prof_kjsLW");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Nnxko");
        t.prejmi(new Tretja.Asistent(), "as_DsHMx");
        t.prejmi(new Tretja.Docent(), "doc_j5H2T");
        t.prejmi(new Tretja.Docent(), "doc_g5nRA");
        t.prejmi(new Tretja.Profesor(), "prof_0MjQ7");
        t.prejmi(new Tretja.Docent(), "doc_lxyMg");
        t.prejmi(new Tretja.Profesor(), "prof_oAUJv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_jfLpp");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_fIljB");
        t.prejmi(new Tretja.Asistent(), "as_HNa8s");
        t.prejmi(new Tretja.Profesor(), "prof_Z8clA");
        t.prejmi(new Tretja.Asistent(), "as_BqS2K");
        t.prejmi(new Tretja.Docent(), "doc_Hu1SB");
        t.prejmi(new Tretja.Profesor(), "prof_ZVS3a");
        t.prejmi(new Tretja.Asistent(), "as_kG1eG");
        t.prejmi(new Tretja.Asistent(), "as_gK1xT");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_7Sg2i");
        t.prejmi(new Tretja.Asistent(), "as_uc8cj");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_nL6w6");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_zRa9c");
        t.prejmi(new Tretja.Asistent(), "as_zWILH");
        t.prejmi(new Tretja.Asistent(), "as_UykCD");
        t.prejmi(new Tretja.Docent(), "doc_ArWcy");
        t.prejmi(new Tretja.Asistent(), "as_hEdbt");
        t.prejmi(new Tretja.Asistent(), "as_cKqGY");
        t.prejmi(new Tretja.Asistent(), "as_brHEb");
        t.prejmi(new Tretja.Docent(), "doc_0r04T");
        t.prejmi(new Tretja.Docent(), "doc_fdoCR");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ayc5B");
        t.prejmi(new Tretja.Profesor(), "prof_jCDkc");
        t.prejmi(new Tretja.Profesor(), "prof_eFIDJ");
        t.prejmi(new Tretja.Asistent(), "as_KFQkV");
        t.prejmi(new Tretja.Asistent(), "as_Z41Bs");
        t.prejmi(new Tretja.Profesor(), "prof_mY2R9");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_AOBcr");
        t.prejmi(new Tretja.Docent(), "doc_OJUG1");
        t.prejmi(new Tretja.Docent(), "doc_UDZQr");
        t.prejmi(new Tretja.Docent(), "doc_8bftS");
        t.prejmi(new Tretja.Profesor(), "prof_R6NXM");
        t.prejmi(new Tretja.Docent(), "doc_nFzeZ");
        t.prejmi(new Tretja.Docent(), "doc_zSkPb");
        t.prejmi(new Tretja.Profesor(), "prof_B65k3");
        t.prejmi(new Tretja.Docent(), "doc_JWUN0");
        t.prejmi(new Tretja.Profesor(), "prof_6Gz0W");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Or3HT");
        t.prejmi(new Tretja.Asistent(), "as_sfjsO");
        t.prejmi(new Tretja.Asistent(), "as_H0Hy2");
        t.prejmi(new Tretja.Docent(), "doc_PIxMe");
        t.prejmi(new Tretja.Profesor(), "prof_SbqMa");
        t.prejmi(new Tretja.Asistent(), "as_8lwA1");
        t.prejmi(new Tretja.Profesor(), "prof_8cZGm");
        t.prejmi(new Tretja.Asistent(), "as_FYakZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Ecm3I");
        t.prejmi(new Tretja.Profesor(), "prof_pnr9V");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_2lB2D");
        t.prejmi(new Tretja.Profesor(), "prof_DGO4n");
        t.prejmi(new Tretja.Docent(), "doc_Jb2yM");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_EpNY3");
        t.prejmi(new Tretja.Docent(), "doc_JcVEr");
        t.prejmi(new Tretja.Docent(), "doc_XIFDO");
        t.prejmi(new Tretja.Docent(), "doc_oAcEh");
        t.prejmi(new Tretja.Asistent(), "as_0Hz6n");
        t.prejmi(new Tretja.Asistent(), "as_5V9Yw");
        t.prejmi(new Tretja.Profesor(), "prof_2Z7Al");
        t.prejmi(new Tretja.Asistent(), "as_0Sv6s");
        t.prejmi(new Tretja.Docent(), "doc_wY4k7");
        t.prejmi(new Tretja.Asistent(), "as_A7f2z");
        t.prejmi(new Tretja.Docent(), "doc_BMXcP");
        t.prejmi(new Tretja.Profesor(), "prof_1a5Nx");
        t.prejmi(new Tretja.Docent(), "doc_DvzY8");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_OqtT7");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_hXjri");
        t.prejmi(new Tretja.Asistent(), "as_XSOKl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_9lzd5");
        t.prejmi(new Tretja.Docent(), "doc_CN9CC");
        t.prejmi(new Tretja.Asistent(), "as_NvIWT");
        t.prejmi(new Tretja.Profesor(), "prof_pFm7l");
        t.prejmi(new Tretja.Docent(), "doc_VNvZO");
        t.prejmi(new Tretja.Docent(), "doc_ZIW3k");
        t.prejmi(new Tretja.Docent(), "doc_et3Ra");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wzoK6");
        t.prejmi(new Tretja.Asistent(), "as_iygYm");
        t.prejmi(new Tretja.Profesor(), "prof_X6Mjj");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_gRYwt");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_38CUb");
        t.prejmi(new Tretja.Asistent(), "as_mciAK");
        t.prejmi(new Tretja.Profesor(), "prof_zFo1T");
        t.prejmi(new Tretja.Docent(), "doc_mMQOi");
        t.prejmi(new Tretja.Asistent(), "as_s5RJu");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_KA9e5");
        t.prejmi(new Tretja.Docent(), "doc_2Pb4T");
        t.prejmi(new Tretja.Asistent(), "as_h4itB");
        t.prejmi(new Tretja.Docent(), "doc_TZEnU");
        t.prejmi(new Tretja.Asistent(), "as_wdkEW");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_UYlmd");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_1ZbdW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_4SGdA");
        t.prejmi(new Tretja.Docent(), "doc_7GtEK");
        t.prejmi(new Tretja.Asistent(), "as_kQTgG");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_sGVcd");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_4Rs9a");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_jBrdO");
        t.prejmi(new Tretja.Asistent(), "as_g0x1n");
        t.prejmi(new Tretja.Profesor(), "prof_4Dk23");
        t.prejmi(new Tretja.Asistent(), "as_XvZ9F");
        t.prejmi(new Tretja.Profesor(), "prof_NFAIl");
        t.prejmi(new Tretja.Asistent(), "as_dDo8W");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_3XJNG");
        t.prejmi(new Tretja.Asistent(), "as_gOslP");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_JPX7m");
        t.prejmi(new Tretja.Asistent(), "as_vtX0M");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_ZqSHT");
        t.prejmi(new Tretja.Profesor(), "prof_7bGzm");
        t.prejmi(new Tretja.Asistent(), "as_3Nysw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_VlxWX");
        t.prejmi(new Tretja.Docent(), "doc_0vsOi");
        t.prejmi(new Tretja.Asistent(), "as_0uCLE");
        t.prejmi(new Tretja.Docent(), "doc_WpuOn");
        t.prejmi(new Tretja.Asistent(), "as_Gb9DF");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_plyn0");
        t.prejmi(new Tretja.Docent(), "doc_KP0B1");
        t.prejmi(new Tretja.Asistent(), "as_GjUrK");
        t.prejmi(new Tretja.Profesor(), "prof_EMBCx");
        t.prejmi(new Tretja.Asistent(), "as_57qF8");
        t.prejmi(new Tretja.Profesor(), "prof_SlSRM");
        t.prejmi(new Tretja.Docent(), "doc_vRtad");
        t.prejmi(new Tretja.Profesor(), "prof_shcv4");
        t.prejmi(new Tretja.Profesor(), "prof_RDaEB");
    }
}
