
public class Test40 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_qXbdn");
        t.prejmi(new Tretja.Docent(), "doc_2ZNcx");
        t.prejmi(new Tretja.Profesor(), "prof_MmWg5");
        t.prejmi(new Tretja.Asistent(), "as_WJ6tW");
        t.prejmi(new Tretja.Docent(), "doc_ocm0R");
        t.prejmi(new Tretja.Docent(), "doc_6JGcf");
        t.prejmi(new Tretja.Profesor(), "prof_2INPb");
        t.prejmi(new Tretja.Asistent(), "as_wpHSJ");
        t.prejmi(new Tretja.Asistent(), "as_88Qqd");
        t.prejmi(new Tretja.Asistent(), "as_zJxtN");
        t.prejmi(new Tretja.Profesor(), "prof_cKykl");
        t.prejmi(new Tretja.Docent(), "doc_omhzO");
        t.prejmi(new Tretja.Asistent(), "as_iOLQd");
        t.prejmi(new Tretja.Profesor(), "prof_mtpBq");
        t.prejmi(new Tretja.Profesor(), "prof_PIOyF");
        t.prejmi(new Tretja.Profesor(), "prof_L8d8q");
        t.prejmi(new Tretja.Asistent(), "as_5U2bD");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_UKExZ");
        t.prejmi(new Tretja.Docent(), "doc_W6Cah");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Qn0wG");
        t.prejmi(new Tretja.Profesor(), "prof_AOz3S");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zxuM2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_64V4e");
        t.prejmi(new Tretja.Asistent(), "as_v8hbO");
        t.prejmi(new Tretja.Docent(), "doc_sTj8V");
        t.prejmi(new Tretja.Profesor(), "prof_aQwLh");
        t.prejmi(new Tretja.Profesor(), "prof_C7C0P");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_brZgP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_2Vskv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_xDZqp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_0u638");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_5RuRC");
        t.prejmi(new Tretja.Profesor(), "prof_HYyCF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fbOrZ");
        t.prejmi(new Tretja.Asistent(), "as_YnWD4");
        t.prejmi(new Tretja.Profesor(), "prof_0mbb3");
        t.prejmi(new Tretja.Asistent(), "as_bEoj0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Ei30L");
        t.prejmi(new Tretja.Asistent(), "as_z0wrl");
        t.prejmi(new Tretja.Asistent(), "as_QCGdJ");
        t.prejmi(new Tretja.Asistent(), "as_m3frt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_VQBua");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_HYHON");
        t.prejmi(new Tretja.Profesor(), "prof_8jhSI");
        t.prejmi(new Tretja.Asistent(), "as_n0Q39");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_uP3GU");
        t.prejmi(new Tretja.Profesor(), "prof_Wx2yk");
        t.prejmi(new Tretja.Profesor(), "prof_z3G0M");
        t.prejmi(new Tretja.Asistent(), "as_YXUp6");
        t.prejmi(new Tretja.Profesor(), "prof_pCtD7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_kk95B");
        t.prejmi(new Tretja.Docent(), "doc_dTVM9");
        t.prejmi(new Tretja.Asistent(), "as_uHJ3H");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_j9vKs");
        t.prejmi(new Tretja.Docent(), "doc_fGYyi");
        t.prejmi(new Tretja.Docent(), "doc_5ybn9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XuDa5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_dRo7B");
        t.prejmi(new Tretja.Profesor(), "prof_v5ls2");
        t.prejmi(new Tretja.Docent(), "doc_pGMGt");
        t.prejmi(new Tretja.Docent(), "doc_aetaS");
        t.prejmi(new Tretja.Profesor(), "prof_dhJfS");
        t.prejmi(new Tretja.Profesor(), "prof_TMyTV");
        t.prejmi(new Tretja.Docent(), "doc_u3Per");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_IeNTJ");
        t.prejmi(new Tretja.Docent(), "doc_NZacG");
        t.prejmi(new Tretja.Profesor(), "prof_7x0JC");
        t.prejmi(new Tretja.Profesor(), "prof_27ppP");
        t.prejmi(new Tretja.Docent(), "doc_LNHvk");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_9dTbq");
        t.prejmi(new Tretja.Docent(), "doc_aXoxX");
        t.prejmi(new Tretja.Asistent(), "as_FUS8A");
        t.prejmi(new Tretja.Asistent(), "as_UyrbP");
        t.prejmi(new Tretja.Asistent(), "as_96iX4");
        t.prejmi(new Tretja.Profesor(), "prof_kY7eD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TmsKc");
        t.prejmi(new Tretja.Profesor(), "prof_GcOhB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_CuWht");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_c7tKb");
        t.prejmi(new Tretja.Docent(), "doc_0N9hA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zPoOw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9Q8Su");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9KZZo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_qfJli");
        t.prejmi(new Tretja.Asistent(), "as_hj9N8");
        t.prejmi(new Tretja.Docent(), "doc_06RO2");
        t.prejmi(new Tretja.Docent(), "doc_SBOhv");
        t.prejmi(new Tretja.Asistent(), "as_VFsEq");
        t.prejmi(new Tretja.Asistent(), "as_HeX7t");
        t.prejmi(new Tretja.Docent(), "doc_mYrT0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_g0WeV");
        t.prejmi(new Tretja.Docent(), "doc_e0Huo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TK7Wu");
        t.prejmi(new Tretja.Profesor(), "prof_9yJsy");
        t.prejmi(new Tretja.Profesor(), "prof_OGv05");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9326O");
        t.prejmi(new Tretja.Docent(), "doc_nuMVi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rqPq4");
        t.prejmi(new Tretja.Docent(), "doc_RhLMP");
        t.prejmi(new Tretja.Docent(), "doc_ygwxN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_PHWDt");
        t.prejmi(new Tretja.Profesor(), "prof_Qv9gj");
        t.prejmi(new Tretja.Asistent(), "as_3dEB3");
        t.prejmi(new Tretja.Asistent(), "as_mXuGf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TN1Ab");
        t.prejmi(new Tretja.Docent(), "doc_LRVCx");
        t.prejmi(new Tretja.Docent(), "doc_9DJHu");
        t.prejmi(new Tretja.Asistent(), "as_hjR9k");
        t.prejmi(new Tretja.Docent(), "doc_wUpei");
        t.prejmi(new Tretja.Asistent(), "as_Q4qP5");
        t.prejmi(new Tretja.Asistent(), "as_XF9Og");
        t.prejmi(new Tretja.Asistent(), "as_uCiiU");
        t.prejmi(new Tretja.Docent(), "doc_wbPO4");
        t.prejmi(new Tretja.Profesor(), "prof_ESLKN");
        t.prejmi(new Tretja.Profesor(), "prof_Qx7Za");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vICjc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_jZamB");
        t.prejmi(new Tretja.Profesor(), "prof_CESPf");
        t.prejmi(new Tretja.Asistent(), "as_1mCBe");
        t.prejmi(new Tretja.Asistent(), "as_LEGRz");
        t.prejmi(new Tretja.Docent(), "doc_YPWxi");
        t.prejmi(new Tretja.Docent(), "doc_JTTvY");
        t.prejmi(new Tretja.Profesor(), "prof_R0DLn");
        t.prejmi(new Tretja.Profesor(), "prof_kRcBA");
        t.prejmi(new Tretja.Asistent(), "as_qHHlE");
        t.prejmi(new Tretja.Asistent(), "as_eWJiw");
        t.prejmi(new Tretja.Docent(), "doc_AgetT");
        t.prejmi(new Tretja.Asistent(), "as_IdBc1");
        t.prejmi(new Tretja.Asistent(), "as_V1qu7");
        t.prejmi(new Tretja.Docent(), "doc_kGODf");
        t.prejmi(new Tretja.Profesor(), "prof_Wzuc1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZwAV4");
        t.prejmi(new Tretja.Asistent(), "as_jfpUu");
        t.prejmi(new Tretja.Profesor(), "prof_eEyQa");
        t.prejmi(new Tretja.Docent(), "doc_RoGOF");
        t.prejmi(new Tretja.Asistent(), "as_7tUv0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zo34Z");
        t.prejmi(new Tretja.Profesor(), "prof_CsDRP");
        t.prejmi(new Tretja.Asistent(), "as_jeMw6");
        t.prejmi(new Tretja.Docent(), "doc_gPax8");
        t.prejmi(new Tretja.Profesor(), "prof_vBykF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_OMK01");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_f6o3p");
        t.prejmi(new Tretja.Docent(), "doc_b8Nhi");
        t.prejmi(new Tretja.Profesor(), "prof_GLBvC");
        t.prejmi(new Tretja.Docent(), "doc_ZNwtf");
        t.prejmi(new Tretja.Docent(), "doc_A0t7S");
        t.prejmi(new Tretja.Asistent(), "as_yMvbY");
        t.prejmi(new Tretja.Profesor(), "prof_b0cop");
        t.prejmi(new Tretja.Asistent(), "as_QguHY");
        t.prejmi(new Tretja.Profesor(), "prof_5GDoO");
        t.prejmi(new Tretja.Docent(), "doc_DfQet");
        t.prejmi(new Tretja.Docent(), "doc_H08jD");
        t.prejmi(new Tretja.Docent(), "doc_OmPPZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Y2Jk7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Sinie");
        t.prejmi(new Tretja.Profesor(), "prof_HsOnZ");
        t.prejmi(new Tretja.Docent(), "doc_UhW2k");
        t.prejmi(new Tretja.Docent(), "doc_6YNM2");
        t.prejmi(new Tretja.Profesor(), "prof_SKC5o");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Kqjxe");
        t.prejmi(new Tretja.Asistent(), "as_j96lf");
        t.prejmi(new Tretja.Profesor(), "prof_SStwO");
        t.prejmi(new Tretja.Docent(), "doc_Am3En");
        t.prejmi(new Tretja.Docent(), "doc_yhVnd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w4HeG");
        t.prejmi(new Tretja.Profesor(), "prof_F9ZrV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MmtIy");
        t.prejmi(new Tretja.Asistent(), "as_MqeeJ");
        t.prejmi(new Tretja.Profesor(), "prof_AqJF2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_bRBe7");
        t.prejmi(new Tretja.Docent(), "doc_lV2BY");
        t.prejmi(new Tretja.Docent(), "doc_CNELY");
        t.prejmi(new Tretja.Profesor(), "prof_QL5vh");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aLgRr");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Hzs3P");
        t.prejmi(new Tretja.Docent(), "doc_60phd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wsZWx");
        t.prejmi(new Tretja.Asistent(), "as_RoVZH");
        t.prejmi(new Tretja.Asistent(), "as_N6hkY");
        t.prejmi(new Tretja.Profesor(), "prof_PkhDA");
        t.prejmi(new Tretja.Docent(), "doc_PtdW1");
        t.prejmi(new Tretja.Profesor(), "prof_Io2Xr");
        t.prejmi(new Tretja.Profesor(), "prof_cQqYo");
        t.prejmi(new Tretja.Docent(), "doc_E5mP8");
        t.prejmi(new Tretja.Asistent(), "as_pPmqY");
        t.prejmi(new Tretja.Docent(), "doc_RiqoH");
        t.prejmi(new Tretja.Profesor(), "prof_ir8iv");
        t.prejmi(new Tretja.Asistent(), "as_PdkcA");
        t.prejmi(new Tretja.Profesor(), "prof_0OwL5");
        t.prejmi(new Tretja.Docent(), "doc_xrnfk");
        t.prejmi(new Tretja.Asistent(), "as_qT5E4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uSBT3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_p0nwi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_LvG7W");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_2QgRj");
        t.prejmi(new Tretja.Profesor(), "prof_1zId3");
        t.prejmi(new Tretja.Asistent(), "as_YTUgM");
        t.prejmi(new Tretja.Asistent(), "as_5aoYu");
        t.prejmi(new Tretja.Asistent(), "as_giT7G");
        t.prejmi(new Tretja.Docent(), "doc_xiPSF");
        t.prejmi(new Tretja.Profesor(), "prof_aeqnX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_KiLAG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_yC1YE");
        t.prejmi(new Tretja.Docent(), "doc_p2PGw");
        t.prejmi(new Tretja.Asistent(), "as_Y7XiR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_59bOD");
        t.prejmi(new Tretja.Asistent(), "as_pQzex");
        t.prejmi(new Tretja.Profesor(), "prof_bvVIL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6Umpe");
        t.prejmi(new Tretja.Docent(), "doc_YHWTA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Rfvkl");
        t.prejmi(new Tretja.Asistent(), "as_1UV8D");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Sa3OD");
        t.prejmi(new Tretja.Docent(), "doc_6LCfD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_unRSZ");
        t.prejmi(new Tretja.Asistent(), "as_7HfAk");
        t.prejmi(new Tretja.Docent(), "doc_hedz7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rwivF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bi1hv");
        t.prejmi(new Tretja.Profesor(), "prof_AupBx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lNeCm");
        t.prejmi(new Tretja.Asistent(), "as_FocRZ");
        t.prejmi(new Tretja.Asistent(), "as_z6mYy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ItSg2");
        t.prejmi(new Tretja.Docent(), "doc_KpDiH");
        t.prejmi(new Tretja.Profesor(), "prof_Nx0vp");
        t.prejmi(new Tretja.Asistent(), "as_6r8nn");
        t.prejmi(new Tretja.Asistent(), "as_ZKBhW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_6HQmb");
        t.prejmi(new Tretja.Asistent(), "as_cPEjy");
        t.prejmi(new Tretja.Asistent(), "as_ypPLY");
        t.prejmi(new Tretja.Asistent(), "as_WdbBO");
        t.prejmi(new Tretja.Docent(), "doc_oX222");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_iUMVs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_pvkZ0");
        t.prejmi(new Tretja.Asistent(), "as_z2kga");
        t.prejmi(new Tretja.Docent(), "doc_egxER");
        t.prejmi(new Tretja.Asistent(), "as_JcqcX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tn32u");
        t.prejmi(new Tretja.Profesor(), "prof_xNoa5");
        t.prejmi(new Tretja.Docent(), "doc_oK51I");
        t.prejmi(new Tretja.Profesor(), "prof_PDpnu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Tao2S");
        t.prejmi(new Tretja.Docent(), "doc_FPkBh");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_dSnbJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ey33a");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_qFf3i");
        t.prejmi(new Tretja.Asistent(), "as_FNFey");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ue3yf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_1UN2p");
        t.prejmi(new Tretja.Asistent(), "as_ZuB01");
        t.prejmi(new Tretja.Profesor(), "prof_4eMFz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zV6uv");
        t.prejmi(new Tretja.Profesor(), "prof_PpjWw");
        t.prejmi(new Tretja.Docent(), "doc_NmUMF");
        t.prejmi(new Tretja.Docent(), "doc_JKbZh");
        t.prejmi(new Tretja.Asistent(), "as_3EiCw");
        t.prejmi(new Tretja.Docent(), "doc_faNcm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_yyEiE");
        t.prejmi(new Tretja.Docent(), "doc_PaPJP");
        t.prejmi(new Tretja.Docent(), "doc_YaRny");
        t.prejmi(new Tretja.Asistent(), "as_BXtgX");
        t.prejmi(new Tretja.Docent(), "doc_1nFT6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_CoViC");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_KtGB2");
        t.prejmi(new Tretja.Docent(), "doc_lV7YJ");
        t.prejmi(new Tretja.Docent(), "doc_SS1x9");
        t.prejmi(new Tretja.Docent(), "doc_pQ6Ad");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_R9ILR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_doTvA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9orUy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_xEZQx");
        t.prejmi(new Tretja.Docent(), "doc_X4cPY");
        t.prejmi(new Tretja.Asistent(), "as_3poa0");
        t.prejmi(new Tretja.Asistent(), "as_YkI8n");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aVYyK");
        t.prejmi(new Tretja.Docent(), "doc_dMq3S");
        t.prejmi(new Tretja.Asistent(), "as_STgzT");
        t.prejmi(new Tretja.Docent(), "doc_D5HjD");
        t.prejmi(new Tretja.Asistent(), "as_aKfJc");
        t.prejmi(new Tretja.Docent(), "doc_CaGGP");
        t.prejmi(new Tretja.Asistent(), "as_SXapS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_sYtBY");
        t.prejmi(new Tretja.Docent(), "doc_m1YHI");
        t.prejmi(new Tretja.Asistent(), "as_bF8GF");
        t.prejmi(new Tretja.Asistent(), "as_Gctqy");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_uWD0f");
        t.prejmi(new Tretja.Asistent(), "as_cx1Qt");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Zq9Cy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SBApM");
        t.prejmi(new Tretja.Asistent(), "as_9DTAq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_3wSxh");
        t.prejmi(new Tretja.Docent(), "doc_j54n3");
        t.prejmi(new Tretja.Asistent(), "as_750pF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_QC11r");
        t.prejmi(new Tretja.Profesor(), "prof_ReAFr");
        t.prejmi(new Tretja.Asistent(), "as_raRLq");
        t.prejmi(new Tretja.Docent(), "doc_YiElj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Wd68m");
        t.prejmi(new Tretja.Profesor(), "prof_42gIg");
        t.prejmi(new Tretja.Asistent(), "as_mrnaq");
        t.prejmi(new Tretja.Profesor(), "prof_WJdcF");
        t.prejmi(new Tretja.Docent(), "doc_EU2Y9");
        t.prejmi(new Tretja.Profesor(), "prof_wHna2");
        t.prejmi(new Tretja.Profesor(), "prof_n5Zpv");
        t.prejmi(new Tretja.Asistent(), "as_OxJi3");
        t.prejmi(new Tretja.Asistent(), "as_vUb2f");
        t.prejmi(new Tretja.Asistent(), "as_lrbOa");
        t.prejmi(new Tretja.Profesor(), "prof_v0aGr");
        t.prejmi(new Tretja.Docent(), "doc_9P5Kp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_VVUlK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GNefM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_2trPM");
        t.prejmi(new Tretja.Asistent(), "as_Udtvc");
        t.prejmi(new Tretja.Profesor(), "prof_mtpPO");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_nfy2O");
        t.prejmi(new Tretja.Profesor(), "prof_EaFxk");
        t.prejmi(new Tretja.Asistent(), "as_TfN7D");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_5aQkZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_SEiW0");
        t.prejmi(new Tretja.Asistent(), "as_7ppsM");
        t.prejmi(new Tretja.Asistent(), "as_JYWL6");
        t.prejmi(new Tretja.Profesor(), "prof_2EMAg");
        t.prejmi(new Tretja.Docent(), "doc_MUKhn");
        t.prejmi(new Tretja.Profesor(), "prof_BDndJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_BKlcF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_EHvZH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_kMO8l");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1ddSg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_15NB7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ytN7L");
        t.prejmi(new Tretja.Asistent(), "as_3euOG");
        t.prejmi(new Tretja.Profesor(), "prof_NHJEh");
        t.prejmi(new Tretja.Profesor(), "prof_y0uCT");
        t.prejmi(new Tretja.Docent(), "doc_q2seh");
        t.prejmi(new Tretja.Docent(), "doc_wg0nG");
        t.prejmi(new Tretja.Docent(), "doc_RjNe2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_sOkzH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JFjrJ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_djnf5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vVxMQ");
        t.prejmi(new Tretja.Profesor(), "prof_FzTYJ");
        t.prejmi(new Tretja.Asistent(), "as_iY1SH");
        t.prejmi(new Tretja.Docent(), "doc_NCb9J");
        t.prejmi(new Tretja.Profesor(), "prof_vzjrU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_qOtvU");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_K2oa4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_APLEd");
        t.prejmi(new Tretja.Profesor(), "prof_FQHkC");
        t.prejmi(new Tretja.Profesor(), "prof_ZVU0y");
        t.prejmi(new Tretja.Docent(), "doc_hi85p");
        t.prejmi(new Tretja.Profesor(), "prof_Pm7Yk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pVhZa");
        t.prejmi(new Tretja.Docent(), "doc_0jkMZ");
        t.prejmi(new Tretja.Docent(), "doc_i009Q");
        t.prejmi(new Tretja.Profesor(), "prof_JoXUz");
        t.prejmi(new Tretja.Docent(), "doc_OhpXx");
        t.prejmi(new Tretja.Asistent(), "as_DmWiA");
        t.prejmi(new Tretja.Profesor(), "prof_FYjEm");
        t.prejmi(new Tretja.Asistent(), "as_bZJbz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_n6XMY");
        t.prejmi(new Tretja.Profesor(), "prof_CJb6x");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_R0rpx");
        t.prejmi(new Tretja.Profesor(), "prof_Vw21i");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_s0Zfy");
        t.prejmi(new Tretja.Asistent(), "as_iBPoM");
        t.prejmi(new Tretja.Docent(), "doc_vgCa2");
        t.prejmi(new Tretja.Docent(), "doc_r5tlq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5cVK5");
        t.prejmi(new Tretja.Profesor(), "prof_76b34");
        t.prejmi(new Tretja.Docent(), "doc_3Y1pp");
        t.prejmi(new Tretja.Asistent(), "as_ySB5T");
        t.prejmi(new Tretja.Docent(), "doc_mxim3");
        t.prejmi(new Tretja.Docent(), "doc_ffJV1");
        t.prejmi(new Tretja.Docent(), "doc_EGn3V");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_tafui");
    }
}
