
public class Test32 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_QQEpo");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_7V6mH");
        t.prejmi(new Tretja.Docent(), "doc_NUFk9");
        t.prejmi(new Tretja.Asistent(), "as_0VZd8");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_CtrDV");
        t.prejmi(new Tretja.Profesor(), "prof_dVUYC");
        t.prejmi(new Tretja.Docent(), "doc_h6oE4");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_gVQEY");
        t.prejmi(new Tretja.Profesor(), "prof_c2GjM");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_Uk7tE");
        t.prejmi(new Tretja.Docent(), "doc_t9Zwe");
        t.prejmi(new Tretja.Docent(), "doc_RKyYc");
        t.prejmi(new Tretja.Profesor(), "prof_yuBUU");
        t.prejmi(new Tretja.Profesor(), "prof_6qgCt");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_T8cc5");
        t.prejmi(new Tretja.Asistent(), "as_rNIMy");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_MgA5U");
        t.prejmi(new Tretja.Asistent(), "as_S5Gg2");
        t.prejmi(new Tretja.Profesor(), "prof_0wsyj");
        t.prejmi(new Tretja.Profesor(), "prof_Afl6v");
        t.prejmi(new Tretja.Docent(), "doc_4VQTb");
        t.prejmi(new Tretja.Docent(), "doc_4v88b");
        t.prejmi(new Tretja.Profesor(), "prof_D2oL9");
        t.prejmi(new Tretja.Profesor(), "prof_BY1qt");
        t.prejmi(new Tretja.Asistent(), "as_6rECC");
        t.prejmi(new Tretja.Profesor(), "prof_xrt40");
        t.prejmi(new Tretja.Docent(), "doc_KBiyB");
        t.prejmi(new Tretja.Profesor(), "prof_aS2Fa");
        t.prejmi(new Tretja.Docent(), "doc_TXwra");
        t.prejmi(new Tretja.Asistent(), "as_UcTAB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_YWyrw");
        t.prejmi(new Tretja.Profesor(), "prof_eFD4A");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_pOd2g");
        t.prejmi(new Tretja.Asistent(), "as_Tm2Dr");
        t.prejmi(new Tretja.Docent(), "doc_1w8jD");
        t.prejmi(new Tretja.Profesor(), "prof_po1Wl");
        t.prejmi(new Tretja.Profesor(), "prof_2dHwO");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_t3WA7");
        t.prejmi(new Tretja.Docent(), "doc_vfYeO");
        t.prejmi(new Tretja.Asistent(), "as_wxkTK");
        t.prejmi(new Tretja.Docent(), "doc_Txi8Q");
        t.prejmi(new Tretja.Docent(), "doc_wzUTT");
        t.prejmi(new Tretja.Docent(), "doc_0XEXJ");
        t.prejmi(new Tretja.Profesor(), "prof_eY8A4");
        t.prejmi(new Tretja.Profesor(), "prof_nJM3K");
        t.prejmi(new Tretja.Docent(), "doc_N3NiN");
        t.prejmi(new Tretja.Docent(), "doc_WTfo6");
        t.prejmi(new Tretja.Docent(), "doc_aiWdb");
        t.prejmi(new Tretja.Docent(), "doc_DLS1U");
        t.prejmi(new Tretja.Asistent(), "as_5DDMb");
        t.prejmi(new Tretja.Profesor(), "prof_lAt1W");
        t.prejmi(new Tretja.Profesor(), "prof_4pTng");
        t.prejmi(new Tretja.Docent(), "doc_UdjNc");
        t.prejmi(new Tretja.Profesor(), "prof_HQABx");
        t.prejmi(new Tretja.Profesor(), "prof_K7yds");
        t.prejmi(new Tretja.Asistent(), "as_zgL69");
        t.prejmi(new Tretja.Docent(), "doc_HROab");
        t.prejmi(new Tretja.Profesor(), "prof_JwwGY");
        t.prejmi(new Tretja.Profesor(), "prof_A5veP");
        t.prejmi(new Tretja.Docent(), "doc_HLDRX");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_PQAIA");
        t.prejmi(new Tretja.Profesor(), "prof_bYsle");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_pohVL");
        t.prejmi(new Tretja.Profesor(), "prof_0NTZy");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_9no8L");
        t.prejmi(new Tretja.Docent(), "doc_tlJjw");
        t.prejmi(new Tretja.Docent(), "doc_PrhbS");
        t.prejmi(new Tretja.Docent(), "doc_L9WaV");
        t.prejmi(new Tretja.Profesor(), "prof_g44WD");
        t.prejmi(new Tretja.Docent(), "doc_M01yz");
        t.prejmi(new Tretja.Docent(), "doc_dxLEt");
        t.prejmi(new Tretja.Asistent(), "as_WOLNb");
        t.prejmi(new Tretja.Profesor(), "prof_MkbEf");
        t.prejmi(new Tretja.Asistent(), "as_EM33y");
        t.prejmi(new Tretja.Docent(), "doc_ppWZl");
        t.prejmi(new Tretja.Profesor(), "prof_hgO9e");
        t.prejmi(new Tretja.Docent(), "doc_9xAHw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_fF7XR");
        t.prejmi(new Tretja.Docent(), "doc_hlzYv");
        t.prejmi(new Tretja.Profesor(), "prof_LPCXb");
        t.prejmi(new Tretja.Profesor(), "prof_S93SH");
        t.prejmi(new Tretja.Profesor(), "prof_ncNpn");
        t.prejmi(new Tretja.Docent(), "doc_HbjpJ");
        t.prejmi(new Tretja.Profesor(), "prof_3wEXZ");
        t.prejmi(new Tretja.Asistent(), "as_jrZ13");
        t.prejmi(new Tretja.Docent(), "doc_4nFGx");
        t.prejmi(new Tretja.Docent(), "doc_hwQ3R");
        t.prejmi(new Tretja.Docent(), "doc_nfpvv");
        t.prejmi(new Tretja.Docent(), "doc_vneBy");
        t.prejmi(new Tretja.Profesor(), "prof_9v76B");
        t.prejmi(new Tretja.Asistent(), "as_mvSCi");
        t.prejmi(new Tretja.Asistent(), "as_wS9Zc");
        t.prejmi(new Tretja.Profesor(), "prof_J6cku");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_Vt6Tr");
        t.prejmi(new Tretja.Asistent(), "as_IedOC");
        t.prejmi(new Tretja.Docent(), "doc_3IThq");
        t.prejmi(new Tretja.Asistent(), "as_axGJG");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_hrUlJ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_KMrUO");
        t.prejmi(new Tretja.Docent(), "doc_hWYAL");
        t.prejmi(new Tretja.Profesor(), "prof_S0f3G");
        t.prejmi(new Tretja.Docent(), "doc_ebAIo");
        t.prejmi(new Tretja.Docent(), "doc_0KYt2");
        t.prejmi(new Tretja.Docent(), "doc_HFH2S");
        t.prejmi(new Tretja.Profesor(), "prof_J3xBR");
        t.prejmi(new Tretja.Asistent(), "as_8kgCK");
        t.prejmi(new Tretja.Docent(), "doc_g1ooZ");
        t.prejmi(new Tretja.Asistent(), "as_vpgBC");
        t.prejmi(new Tretja.Docent(), "doc_8fTcS");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_IzkUT");
        t.prejmi(new Tretja.Asistent(), "as_LwDvv");
        t.prejmi(new Tretja.Docent(), "doc_6VeMI");
        t.prejmi(new Tretja.Profesor(), "prof_PdgSo");
        t.prejmi(new Tretja.Docent(), "doc_FqDOr");
        t.prejmi(new Tretja.Asistent(), "as_3OTFk");
        t.prejmi(new Tretja.Asistent(), "as_wkeE0");
        t.prejmi(new Tretja.Profesor(), "prof_PLsbN");
        t.prejmi(new Tretja.Docent(), "doc_SyCTN");
        t.prejmi(new Tretja.Profesor(), "prof_F46lH");
        t.prejmi(new Tretja.Docent(), "doc_eO37e");
        t.prejmi(new Tretja.Profesor(), "prof_IgxbT");
        t.prejmi(new Tretja.Asistent(), "as_2nH57");
        t.prejmi(new Tretja.Docent(), "doc_hyioE");
        t.prejmi(new Tretja.Asistent(), "as_0YrGk");
        t.prejmi(new Tretja.Asistent(), "as_OG0V4");
        t.prejmi(new Tretja.Docent(), "doc_FNNam");
        t.prejmi(new Tretja.Docent(), "doc_UV8Pq");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_BVKVJ");
        t.prejmi(new Tretja.Docent(), "doc_kbzNT");
        t.prejmi(new Tretja.Profesor(), "prof_WmdNg");
        t.prejmi(new Tretja.Docent(), "doc_KNWhe");
        t.prejmi(new Tretja.Docent(), "doc_lQmXb");
        t.prejmi(new Tretja.Asistent(), "as_ib5Qu");
        t.prejmi(new Tretja.Docent(), "doc_dZgSt");
        t.prejmi(new Tretja.Asistent(), "as_E2Naq");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_fG4ld");
        t.prejmi(new Tretja.Docent(), "doc_poNMS");
        t.prejmi(new Tretja.Docent(), "doc_WzR3A");
        t.prejmi(new Tretja.Asistent(), "as_qM8OA");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Mo7GX");
        t.prejmi(new Tretja.Docent(), "doc_NYwcm");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_gzhRf");
        t.prejmi(new Tretja.Profesor(), "prof_N9JF9");
        t.prejmi(new Tretja.Asistent(), "as_6oLi1");
        t.prejmi(new Tretja.Asistent(), "as_KTWsw");
        t.prejmi(new Tretja.Asistent(), "as_dutKC");
        t.prejmi(new Tretja.Asistent(), "as_nqBLI");
        t.prejmi(new Tretja.Asistent(), "as_EIerb");
        t.prejmi(new Tretja.Profesor(), "prof_FN0Eh");
        t.prejmi(new Tretja.Docent(), "doc_YcpXz");
        t.prejmi(new Tretja.Profesor(), "prof_oIHEN");
        t.prejmi(new Tretja.Docent(), "doc_47smr");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_daMYo");
        t.prejmi(new Tretja.Docent(), "doc_TCS3o");
        t.prejmi(new Tretja.Docent(), "doc_ogsW2");
        t.prejmi(new Tretja.Asistent(), "as_Dtwdy");
        t.prejmi(new Tretja.Asistent(), "as_A6KoB");
        t.prejmi(new Tretja.Asistent(), "as_5cFn3");
        t.prejmi(new Tretja.Docent(), "doc_d7ytE");
        t.prejmi(new Tretja.Asistent(), "as_91oXt");
        t.prejmi(new Tretja.Profesor(), "prof_pGdCI");
        t.prejmi(new Tretja.Asistent(), "as_IhZWh");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_njsSS");
        t.prejmi(new Tretja.Docent(), "doc_zbgei");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_G26dt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_vhB58");
        t.prejmi(new Tretja.Asistent(), "as_hGnZP");
        t.prejmi(new Tretja.Asistent(), "as_4GWvP");
        t.prejmi(new Tretja.Profesor(), "prof_uDbGE");
        t.prejmi(new Tretja.Profesor(), "prof_KnoiY");
        t.prejmi(new Tretja.Asistent(), "as_uK1xs");
        t.prejmi(new Tretja.Profesor(), "prof_wfvEU");
        t.prejmi(new Tretja.Profesor(), "prof_kLeLS");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_rMgGe");
        t.prejmi(new Tretja.Docent(), "doc_aEjDZ");
        t.prejmi(new Tretja.Docent(), "doc_fvdmo");
        t.prejmi(new Tretja.Profesor(), "prof_dkyoR");
        t.prejmi(new Tretja.Asistent(), "as_BJ6VE");
        t.prejmi(new Tretja.Asistent(), "as_fvo9l");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_eC94H");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_XO6y2");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_jzi74");
        t.prejmi(new Tretja.Profesor(), "prof_VEnk3");
        t.prejmi(new Tretja.Docent(), "doc_3llES");
        t.prejmi(new Tretja.Docent(), "doc_i4sys");
        t.prejmi(new Tretja.Docent(), "doc_Pbphg");
        t.prejmi(new Tretja.Asistent(), "as_e6w0n");
        t.prejmi(new Tretja.Asistent(), "as_B2ubX");
        t.prejmi(new Tretja.Profesor(), "prof_TT2Vu");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Fiar2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_TPpIh");
        t.prejmi(new Tretja.Asistent(), "as_KrOON");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_V215a");
        t.prejmi(new Tretja.Docent(), "doc_fsHzL");
        t.prejmi(new Tretja.Docent(), "doc_O6ZgH");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_TIMia");
        t.prejmi(new Tretja.Profesor(), "prof_stIZE");
        t.prejmi(new Tretja.Asistent(), "as_HYJAH");
        t.prejmi(new Tretja.Profesor(), "prof_lGzl0");
        t.prejmi(new Tretja.Docent(), "doc_PoZ1e");
        t.prejmi(new Tretja.Profesor(), "prof_5hZQh");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_OAyhB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_QkUkw");
        t.prejmi(new Tretja.Docent(), "doc_0RYsU");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_8sVPx");
        t.prejmi(new Tretja.Docent(), "doc_RD9SV");
        t.prejmi(new Tretja.Docent(), "doc_iaPpi");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_hKzUM");
        t.prejmi(new Tretja.Profesor(), "prof_dXYGs");
        t.prejmi(new Tretja.Docent(), "doc_syEUl");
        t.prejmi(new Tretja.Docent(), "doc_qdX7A");
        t.prejmi(new Tretja.Asistent(), "as_Jvxdy");
        t.prejmi(new Tretja.Asistent(), "as_u3pQo");
        t.prejmi(new Tretja.Docent(), "doc_SpcuX");
        t.prejmi(new Tretja.Profesor(), "prof_DpL4S");
        t.prejmi(new Tretja.Profesor(), "prof_KWNJo");
        t.prejmi(new Tretja.Docent(), "doc_a9TRM");
        t.prejmi(new Tretja.Profesor(), "prof_7irae");
        t.prejmi(new Tretja.Docent(), "doc_9cXAj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_3pWCa");
        t.prejmi(new Tretja.Docent(), "doc_9t6Tv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_8GEzv");
        t.prejmi(new Tretja.Docent(), "doc_bVrm8");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_XSNXZ");
        t.prejmi(new Tretja.Asistent(), "as_rNZCx");
        t.prejmi(new Tretja.Docent(), "doc_h1Fb6");
        t.prejmi(new Tretja.Docent(), "doc_4XVpA");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_qAgG3");
        t.prejmi(new Tretja.Profesor(), "prof_667pV");
        t.prejmi(new Tretja.Asistent(), "as_I9A1A");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_AaK2S");
        t.prejmi(new Tretja.Asistent(), "as_HdkKK");
        t.prejmi(new Tretja.Asistent(), "as_fCiCj");
        t.prejmi(new Tretja.Asistent(), "as_0JH9W");
        t.prejmi(new Tretja.Profesor(), "prof_X3jj0");
        t.prejmi(new Tretja.Asistent(), "as_mFAMq");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_2RbXw");
        t.prejmi(new Tretja.Docent(), "doc_Xq8RN");
        t.prejmi(new Tretja.Profesor(), "prof_4BnrY");
        t.prejmi(new Tretja.Profesor(), "prof_XZ80I");
        t.prejmi(new Tretja.Asistent(), "as_ho7J0");
        t.prejmi(new Tretja.Profesor(), "prof_2JMDg");
        t.prejmi(new Tretja.Asistent(), "as_BsQ8R");
        t.prejmi(new Tretja.Asistent(), "as_jDLmR");
        t.prejmi(new Tretja.Docent(), "doc_joGU2");
        t.prejmi(new Tretja.Docent(), "doc_l697G");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_WO3yG");
        t.prejmi(new Tretja.Docent(), "doc_ykzn0");
        t.prejmi(new Tretja.Asistent(), "as_QgJtt");
        t.prejmi(new Tretja.Docent(), "doc_nVpyL");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_DbdJg");
        t.prejmi(new Tretja.Asistent(), "as_BtyKw");
        t.prejmi(new Tretja.Docent(), "doc_CZaIb");
        t.prejmi(new Tretja.Asistent(), "as_xYl0i");
        t.prejmi(new Tretja.Profesor(), "prof_b5iQm");
        t.prejmi(new Tretja.Asistent(), "as_CNmjv");
        t.prejmi(new Tretja.Profesor(), "prof_HCOqB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_O3QsL");
        t.prejmi(new Tretja.Docent(), "doc_Qft6n");
        t.prejmi(new Tretja.Asistent(), "as_EQsS3");
        t.prejmi(new Tretja.Docent(), "doc_v5bp5");
        t.prejmi(new Tretja.Docent(), "doc_eU8Yc");
        t.prejmi(new Tretja.Docent(), "doc_wGylh");
        t.prejmi(new Tretja.Profesor(), "prof_T4uJc");
        t.prejmi(new Tretja.Profesor(), "prof_EWz4s");
        t.prejmi(new Tretja.Docent(), "doc_Hk8je");
        t.prejmi(new Tretja.Profesor(), "prof_0bhw9");
        t.prejmi(new Tretja.Profesor(), "prof_E2pHr");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_MbXAR");
        t.prejmi(new Tretja.Docent(), "doc_hwtwU");
        t.prejmi(new Tretja.Asistent(), "as_C8DgZ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_xAHHo");
        t.prejmi(new Tretja.Asistent(), "as_WFLXJ");
        t.prejmi(new Tretja.Asistent(), "as_iXXqZ");
        t.prejmi(new Tretja.Docent(), "doc_ZbTK5");
        t.prejmi(new Tretja.Docent(), "doc_zR0f8");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_38et6");
        t.prejmi(new Tretja.Asistent(), "as_fnAVl");
        t.prejmi(new Tretja.Asistent(), "as_x4tgV");
        t.prejmi(new Tretja.Profesor(), "prof_oXySP");
        t.prejmi(new Tretja.Asistent(), "as_RhJP5");
        t.prejmi(new Tretja.Profesor(), "prof_FByyr");
        t.prejmi(new Tretja.Asistent(), "as_klWWB");
        t.prejmi(new Tretja.Asistent(), "as_IC6GJ");
        t.prejmi(new Tretja.Asistent(), "as_fnfXd");
        t.prejmi(new Tretja.Profesor(), "prof_kX3XD");
        t.prejmi(new Tretja.Asistent(), "as_sEd1m");
        t.prejmi(new Tretja.Profesor(), "prof_dHN88");
        t.prejmi(new Tretja.Profesor(), "prof_8UP1J");
        t.prejmi(new Tretja.Profesor(), "prof_Ps7KY");
        t.prejmi(new Tretja.Asistent(), "as_nZroG");
        t.prejmi(new Tretja.Docent(), "doc_hzIuC");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
    }
}
