
public class Test14 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_5ZM02");
        t.prejmi(new Tretja.Docent(), "doc_rot1y");
        t.prejmi(new Tretja.Profesor(), "prof_gPXr5");
        t.prejmi(new Tretja.Docent(), "doc_jUmRF");
        t.prejmi(new Tretja.Profesor(), "prof_vCKgi");
        t.prejmi(new Tretja.Asistent(), "as_AbyDG");
        t.prejmi(new Tretja.Asistent(), "as_B8Ex3");
        t.prejmi(new Tretja.Docent(), "doc_hA3qi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_nbTRQ");
        t.prejmi(new Tretja.Profesor(), "prof_lV5ST");
        t.prejmi(new Tretja.Asistent(), "as_GNRDa");
        t.prejmi(new Tretja.Profesor(), "prof_erRMp");
        t.prejmi(new Tretja.Profesor(), "prof_LdTud");
        t.prejmi(new Tretja.Profesor(), "prof_4fXjU");
        t.prejmi(new Tretja.Profesor(), "prof_spA35");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_jMI3p");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_XnZwW");
        t.prejmi(new Tretja.Profesor(), "prof_YI8Bx");
        t.prejmi(new Tretja.Asistent(), "as_5c9wN");
        t.prejmi(new Tretja.Docent(), "doc_OBWgF");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_EwCDQ");
        t.prejmi(new Tretja.Asistent(), "as_fBPwJ");
        t.prejmi(new Tretja.Profesor(), "prof_6ujDM");
        t.prejmi(new Tretja.Profesor(), "prof_ghthH");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_tUk8A");
        t.prejmi(new Tretja.Profesor(), "prof_OdqWS");
        t.prejmi(new Tretja.Profesor(), "prof_8q5hQ");
        t.prejmi(new Tretja.Asistent(), "as_6NEze");
        t.prejmi(new Tretja.Asistent(), "as_7rDQR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_YYQe3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_JiNri");
        t.prejmi(new Tretja.Docent(), "doc_FWo6P");
        t.prejmi(new Tretja.Docent(), "doc_8DQY6");
        t.prejmi(new Tretja.Profesor(), "prof_mnHwi");
        t.prejmi(new Tretja.Docent(), "doc_dHiD7");
        t.prejmi(new Tretja.Docent(), "doc_WUVSi");
        t.prejmi(new Tretja.Profesor(), "prof_UVfRU");
        t.prejmi(new Tretja.Docent(), "doc_LoBNy");
        t.prejmi(new Tretja.Asistent(), "as_zDA6c");
        t.prejmi(new Tretja.Asistent(), "as_SFEKG");
        t.prejmi(new Tretja.Docent(), "doc_O0YVH");
        t.prejmi(new Tretja.Profesor(), "prof_gXFLt");
        t.prejmi(new Tretja.Profesor(), "prof_rBjrr");
        t.prejmi(new Tretja.Asistent(), "as_4d3cM");
        t.prejmi(new Tretja.Docent(), "doc_engxC");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1tEjm");
        t.prejmi(new Tretja.Profesor(), "prof_1a1wY");
        t.prejmi(new Tretja.Profesor(), "prof_2iDUt");
        t.prejmi(new Tretja.Profesor(), "prof_vtkiX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_xotss");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_pt7YD");
        t.prejmi(new Tretja.Docent(), "doc_1oeh1");
        t.prejmi(new Tretja.Asistent(), "as_D7s8F");
        t.prejmi(new Tretja.Profesor(), "prof_eMUap");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_2klzl");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_qKmHP");
        t.prejmi(new Tretja.Docent(), "doc_3EQlk");
        t.prejmi(new Tretja.Docent(), "doc_3v1QN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_DissZ");
        t.prejmi(new Tretja.Docent(), "doc_EPxwF");
        t.prejmi(new Tretja.Docent(), "doc_1nHrL");
        t.prejmi(new Tretja.Asistent(), "as_b86gN");
        t.prejmi(new Tretja.Profesor(), "prof_2TvcS");
        t.prejmi(new Tretja.Docent(), "doc_uqBit");
        t.prejmi(new Tretja.Asistent(), "as_Ds1t6");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_X4JMA");
        t.prejmi(new Tretja.Asistent(), "as_Rwdpf");
        t.prejmi(new Tretja.Asistent(), "as_3t1tw");
        t.prejmi(new Tretja.Profesor(), "prof_5qpji");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_xt5W9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_XOrYi");
        t.prejmi(new Tretja.Profesor(), "prof_BhbNr");
        t.prejmi(new Tretja.Profesor(), "prof_wrCr6");
        t.prejmi(new Tretja.Docent(), "doc_3IWwt");
        t.prejmi(new Tretja.Asistent(), "as_eSQ7H");
        t.prejmi(new Tretja.Docent(), "doc_XyXGS");
        t.prejmi(new Tretja.Asistent(), "as_JlccZ");
        t.prejmi(new Tretja.Profesor(), "prof_JlPxJ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_azq7K");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Y5sWq");
        t.prejmi(new Tretja.Profesor(), "prof_z8e8y");
        t.prejmi(new Tretja.Docent(), "doc_Pp7jw");
        t.prejmi(new Tretja.Docent(), "doc_rndGP");
        t.prejmi(new Tretja.Profesor(), "prof_kJZkv");
        t.prejmi(new Tretja.Asistent(), "as_dRN9L");
        t.prejmi(new Tretja.Asistent(), "as_pIyRR");
        t.prejmi(new Tretja.Docent(), "doc_VP3Qi");
        t.prejmi(new Tretja.Profesor(), "prof_dGxJX");
        t.prejmi(new Tretja.Profesor(), "prof_qwEQq");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_W3mTz");
        t.prejmi(new Tretja.Profesor(), "prof_Rjik6");
        t.prejmi(new Tretja.Docent(), "doc_8ILp1");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_PzDNl");
        t.prejmi(new Tretja.Docent(), "doc_D076w");
        t.prejmi(new Tretja.Profesor(), "prof_uqdEy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ANLlM");
        t.prejmi(new Tretja.Profesor(), "prof_OM6dz");
        t.prejmi(new Tretja.Docent(), "doc_x59CQ");
        t.prejmi(new Tretja.Profesor(), "prof_J9e4s");
        t.prejmi(new Tretja.Docent(), "doc_HIAuI");
        t.prejmi(new Tretja.Docent(), "doc_7a28Q");
        t.prejmi(new Tretja.Profesor(), "prof_3UYdy");
        t.prejmi(new Tretja.Asistent(), "as_OllPb");
        t.prejmi(new Tretja.Profesor(), "prof_IDytS");
        t.prejmi(new Tretja.Docent(), "doc_2vErd");
        t.prejmi(new Tretja.Docent(), "doc_YjkPM");
        t.prejmi(new Tretja.Docent(), "doc_aahC5");
        t.prejmi(new Tretja.Profesor(), "prof_B3xIp");
        t.prejmi(new Tretja.Profesor(), "prof_Qiaco");
        t.prejmi(new Tretja.Docent(), "doc_ZhJ4G");
        t.prejmi(new Tretja.Profesor(), "prof_TY8wF");
        t.prejmi(new Tretja.Asistent(), "as_yCFcC");
        t.prejmi(new Tretja.Profesor(), "prof_SD0Gq");
        t.prejmi(new Tretja.Asistent(), "as_CYDM7");
        t.prejmi(new Tretja.Asistent(), "as_7kKjE");
        t.prejmi(new Tretja.Docent(), "doc_SGxky");
        t.prejmi(new Tretja.Docent(), "doc_NSmmC");
        t.prejmi(new Tretja.Asistent(), "as_WzBm6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_KLYq2");
        t.prejmi(new Tretja.Docent(), "doc_739GV");
        t.prejmi(new Tretja.Profesor(), "prof_s7q4A");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_nsk5v");
        t.prejmi(new Tretja.Asistent(), "as_uxnKy");
        t.prejmi(new Tretja.Asistent(), "as_YbGrv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Vzcyv");
        t.prejmi(new Tretja.Asistent(), "as_ZwVWO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_BNecM");
        t.prejmi(new Tretja.Profesor(), "prof_nGC6n");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_tKyUu");
        t.prejmi(new Tretja.Docent(), "doc_xqG0L");
        t.prejmi(new Tretja.Profesor(), "prof_Q0Rdo");
        t.prejmi(new Tretja.Docent(), "doc_N7tPg");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_0EeWY");
        t.prejmi(new Tretja.Profesor(), "prof_IoTcN");
        t.prejmi(new Tretja.Docent(), "doc_7CbtM");
        t.prejmi(new Tretja.Docent(), "doc_RKm9n");
        t.prejmi(new Tretja.Profesor(), "prof_ie5fk");
        t.prejmi(new Tretja.Profesor(), "prof_NsMYB");
        t.prejmi(new Tretja.Docent(), "doc_VTgEv");
        t.prejmi(new Tretja.Docent(), "doc_aOMDU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_s6H4o");
        t.prejmi(new Tretja.Docent(), "doc_ZcsvJ");
        t.prejmi(new Tretja.Docent(), "doc_DC28Q");
        t.prejmi(new Tretja.Profesor(), "prof_MmoKr");
        t.prejmi(new Tretja.Docent(), "doc_S3PEt");
        t.prejmi(new Tretja.Docent(), "doc_JJwS8");
        t.prejmi(new Tretja.Docent(), "doc_GXDyQ");
        t.prejmi(new Tretja.Asistent(), "as_IQmTt");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_a0qr6");
        t.prejmi(new Tretja.Profesor(), "prof_ILubW");
        t.prejmi(new Tretja.Profesor(), "prof_1M2Zq");
        t.prejmi(new Tretja.Asistent(), "as_satqB");
        t.prejmi(new Tretja.Asistent(), "as_my2Wn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_AdA78");
        t.prejmi(new Tretja.Docent(), "doc_liJ34");
        t.prejmi(new Tretja.Profesor(), "prof_oAnjB");
        t.prejmi(new Tretja.Profesor(), "prof_Xr8pm");
        t.prejmi(new Tretja.Docent(), "doc_K4P2K");
        t.prejmi(new Tretja.Asistent(), "as_o1Hl8");
        t.prejmi(new Tretja.Docent(), "doc_Ea30s");
        t.prejmi(new Tretja.Docent(), "doc_vWCQx");
        t.prejmi(new Tretja.Docent(), "doc_6vgPB");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_P6wkn");
        t.prejmi(new Tretja.Profesor(), "prof_CKitf");
        t.prejmi(new Tretja.Profesor(), "prof_OTQSq");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_1IKP5");
        t.prejmi(new Tretja.Asistent(), "as_4FA1z");
        t.prejmi(new Tretja.Docent(), "doc_wQjFu");
        t.prejmi(new Tretja.Profesor(), "prof_re8Fc");
        t.prejmi(new Tretja.Docent(), "doc_myYTf");
        t.prejmi(new Tretja.Profesor(), "prof_0alux");
        t.prejmi(new Tretja.Profesor(), "prof_fKybw");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_sUdIT");
        t.prejmi(new Tretja.Profesor(), "prof_Mn0eA");
        t.prejmi(new Tretja.Asistent(), "as_OrekZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_QYGHg");
        t.prejmi(new Tretja.Asistent(), "as_4iGD9");
        t.prejmi(new Tretja.Profesor(), "prof_mBNQj");
        t.prejmi(new Tretja.Asistent(), "as_FkbIg");
        t.prejmi(new Tretja.Docent(), "doc_CAIdA");
        t.prejmi(new Tretja.Docent(), "doc_cNVts");
        t.prejmi(new Tretja.Profesor(), "prof_JQDAv");
        t.prejmi(new Tretja.Docent(), "doc_HNfTH");
        t.prejmi(new Tretja.Asistent(), "as_XQ9l5");
        t.prejmi(new Tretja.Docent(), "doc_vBuD2");
        t.prejmi(new Tretja.Profesor(), "prof_JsM2c");
        t.prejmi(new Tretja.Docent(), "doc_o3LPM");
        t.prejmi(new Tretja.Asistent(), "as_rdUYe");
        t.prejmi(new Tretja.Docent(), "doc_93ygp");
        t.prejmi(new Tretja.Asistent(), "as_tdUHN");
        t.prejmi(new Tretja.Profesor(), "prof_T1kOk");
        t.prejmi(new Tretja.Asistent(), "as_2fDKR");
        t.prejmi(new Tretja.Docent(), "doc_5ssDb");
        t.prejmi(new Tretja.Docent(), "doc_18FKY");
        t.prejmi(new Tretja.Asistent(), "as_YlOcG");
        t.prejmi(new Tretja.Profesor(), "prof_9A4fa");
        t.prejmi(new Tretja.Docent(), "doc_ZSutz");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_nNbPA");
        t.prejmi(new Tretja.Docent(), "doc_oaUqE");
        t.prejmi(new Tretja.Docent(), "doc_9BxiA");
        t.prejmi(new Tretja.Profesor(), "prof_JNGe6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_uy4TH");
        t.prejmi(new Tretja.Asistent(), "as_9NHq7");
        t.prejmi(new Tretja.Docent(), "doc_UjCuE");
        t.prejmi(new Tretja.Docent(), "doc_k7kr2");
        t.prejmi(new Tretja.Profesor(), "prof_NZoMQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_AZYlf");
        t.prejmi(new Tretja.Docent(), "doc_cDN0H");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_yY15R");
        t.prejmi(new Tretja.Asistent(), "as_iGVTf");
        t.prejmi(new Tretja.Asistent(), "as_qznUs");
        t.prejmi(new Tretja.Asistent(), "as_qUtwF");
        t.prejmi(new Tretja.Asistent(), "as_whott");
        t.prejmi(new Tretja.Profesor(), "prof_iRe2S");
        t.prejmi(new Tretja.Asistent(), "as_d5vg2");
        t.prejmi(new Tretja.Docent(), "doc_1srW6");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_iLWog");
        t.prejmi(new Tretja.Docent(), "doc_TvDsY");
        t.prejmi(new Tretja.Profesor(), "prof_aiXi7");
        t.prejmi(new Tretja.Profesor(), "prof_LAXoK");
        t.prejmi(new Tretja.Asistent(), "as_XwLVD");
        t.prejmi(new Tretja.Asistent(), "as_c8aMr");
        t.prejmi(new Tretja.Docent(), "doc_6nrd7");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_yxCJi");
        t.prejmi(new Tretja.Asistent(), "as_ZcvID");
        t.prejmi(new Tretja.Asistent(), "as_WfoEA");
        t.prejmi(new Tretja.Profesor(), "prof_V8OJV");
        t.prejmi(new Tretja.Docent(), "doc_wzCSx");
        t.prejmi(new Tretja.Asistent(), "as_UqHOI");
        t.prejmi(new Tretja.Asistent(), "as_LoEvE");
        t.prejmi(new Tretja.Profesor(), "prof_radCQ");
        t.prejmi(new Tretja.Profesor(), "prof_JtHZQ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_bl8H5");
        t.prejmi(new Tretja.Profesor(), "prof_YeJA2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_UWLG9");
        t.prejmi(new Tretja.Asistent(), "as_69jUO");
        t.prejmi(new Tretja.Asistent(), "as_YNliO");
        t.prejmi(new Tretja.Asistent(), "as_9dRP5");
        t.prejmi(new Tretja.Asistent(), "as_rAlOy");
        t.prejmi(new Tretja.Docent(), "doc_tWgKt");
        t.prejmi(new Tretja.Profesor(), "prof_brGp0");
        t.prejmi(new Tretja.Asistent(), "as_crhZ6");
        t.prejmi(new Tretja.Asistent(), "as_EMhCZ");
        t.prejmi(new Tretja.Asistent(), "as_WOivZ");
        t.prejmi(new Tretja.Profesor(), "prof_EhygB");
    }
}
