
public class Test41 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ehwOT");
        t.prejmi(new Tretja.Profesor(), "prof_5knB3");
        t.prejmi(new Tretja.Profesor(), "prof_TewVV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1RL8C");
        t.prejmi(new Tretja.Asistent(), "as_QMrdz");
        t.prejmi(new Tretja.Docent(), "doc_uc7h8");
        t.prejmi(new Tretja.Docent(), "doc_V98sV");
        t.prejmi(new Tretja.Docent(), "doc_1Vx43");
        t.prejmi(new Tretja.Asistent(), "as_Yp5H8");
        t.prejmi(new Tretja.Docent(), "doc_fmPUj");
        t.prejmi(new Tretja.Docent(), "doc_snCgT");
        t.prejmi(new Tretja.Asistent(), "as_3qChT");
        t.prejmi(new Tretja.Docent(), "doc_aEix6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_x3IjD");
        t.prejmi(new Tretja.Docent(), "doc_HTlX4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_a68SB");
        t.prejmi(new Tretja.Asistent(), "as_8WAt7");
        t.prejmi(new Tretja.Profesor(), "prof_lrkLI");
        t.prejmi(new Tretja.Asistent(), "as_Y0C9n");
        t.prejmi(new Tretja.Docent(), "doc_NMNdC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_zdvLW");
        t.prejmi(new Tretja.Docent(), "doc_Qj4s4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1c6no");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Yd2Bp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GAsRo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_0E0yR");
        t.prejmi(new Tretja.Docent(), "doc_TgoTD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ZMo5S");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_IelxY");
        t.prejmi(new Tretja.Asistent(), "as_imOaw");
        t.prejmi(new Tretja.Profesor(), "prof_vqxNj");
        t.prejmi(new Tretja.Asistent(), "as_0aADo");
        t.prejmi(new Tretja.Docent(), "doc_plbXN");
        t.prejmi(new Tretja.Docent(), "doc_eEjwG");
        t.prejmi(new Tretja.Docent(), "doc_D8Fx8");
        t.prejmi(new Tretja.Asistent(), "as_Hgf1f");
        t.prejmi(new Tretja.Docent(), "doc_n4vEn");
        t.prejmi(new Tretja.Profesor(), "prof_1RuP8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JPmVJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3rZSd");
        t.prejmi(new Tretja.Docent(), "doc_L9791");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_P8JO3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_lXxph");
        t.prejmi(new Tretja.Docent(), "doc_Q3EWe");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4sI82");
        t.prejmi(new Tretja.Docent(), "doc_nMS9e");
        t.prejmi(new Tretja.Profesor(), "prof_tQXX9");
        t.prejmi(new Tretja.Asistent(), "as_zMDyJ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MJkfc");
        t.prejmi(new Tretja.Docent(), "doc_dTHtd");
        t.prejmi(new Tretja.Asistent(), "as_XtOlQ");
        t.prejmi(new Tretja.Profesor(), "prof_UtTh4");
        t.prejmi(new Tretja.Docent(), "doc_gLH0J");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_gwOmG");
        t.prejmi(new Tretja.Docent(), "doc_4wjTV");
        t.prejmi(new Tretja.Docent(), "doc_lsOPw");
        t.prejmi(new Tretja.Docent(), "doc_BIaSg");
        t.prejmi(new Tretja.Docent(), "doc_Ljocw");
        t.prejmi(new Tretja.Asistent(), "as_bJE0J");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ApDtH");
        t.prejmi(new Tretja.Asistent(), "as_xfyUn");
        t.prejmi(new Tretja.Docent(), "doc_DsAfy");
        t.prejmi(new Tretja.Asistent(), "as_Ad0WO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_gYMnP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_YQOkw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_EPghb");
        t.prejmi(new Tretja.Docent(), "doc_eQ9E5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_mbI5b");
        t.prejmi(new Tretja.Profesor(), "prof_XMhP8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vJUqy");
        t.prejmi(new Tretja.Asistent(), "as_VzQLp");
        t.prejmi(new Tretja.Profesor(), "prof_O87Bz");
        t.prejmi(new Tretja.Docent(), "doc_20GRL");
        t.prejmi(new Tretja.Asistent(), "as_41b3P");
        t.prejmi(new Tretja.Asistent(), "as_TMYBg");
        t.prejmi(new Tretja.Docent(), "doc_S0JXM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RjjlD");
        t.prejmi(new Tretja.Asistent(), "as_0RDT6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_P1dS0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6HfhA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_khBNC");
        t.prejmi(new Tretja.Profesor(), "prof_nzVqP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6eOZz");
        t.prejmi(new Tretja.Profesor(), "prof_VoHbC");
        t.prejmi(new Tretja.Asistent(), "as_y2VlC");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ni7v7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_h26zO");
        t.prejmi(new Tretja.Docent(), "doc_t0gc3");
        t.prejmi(new Tretja.Asistent(), "as_03p0O");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XQ22f");
        t.prejmi(new Tretja.Profesor(), "prof_aK0u9");
        t.prejmi(new Tretja.Profesor(), "prof_Gem5f");
        t.prejmi(new Tretja.Profesor(), "prof_GZITV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7brzp");
        t.prejmi(new Tretja.Docent(), "doc_Qwbpa");
        t.prejmi(new Tretja.Profesor(), "prof_YWe2b");
        t.prejmi(new Tretja.Profesor(), "prof_T4zVd");
        t.prejmi(new Tretja.Profesor(), "prof_UdKhs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_mNjG3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_3ubWu");
        t.prejmi(new Tretja.Asistent(), "as_rpQv7");
        t.prejmi(new Tretja.Docent(), "doc_EaOq0");
        t.prejmi(new Tretja.Docent(), "doc_Pm8pR");
        t.prejmi(new Tretja.Profesor(), "prof_5Ln3Z");
        t.prejmi(new Tretja.Docent(), "doc_1huQe");
        t.prejmi(new Tretja.Asistent(), "as_U9R5v");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_E7B3H");
        t.prejmi(new Tretja.Profesor(), "prof_dSRPC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_gfpnv");
        t.prejmi(new Tretja.Profesor(), "prof_IZ3uT");
        t.prejmi(new Tretja.Asistent(), "as_92J6q");
        t.prejmi(new Tretja.Asistent(), "as_JSkR0");
        t.prejmi(new Tretja.Profesor(), "prof_89sRK");
        t.prejmi(new Tretja.Asistent(), "as_rQyHA");
        t.prejmi(new Tretja.Asistent(), "as_jfY4t");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JZzrm");
        t.prejmi(new Tretja.Asistent(), "as_7XsEl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_aWnEt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xhRr9");
        t.prejmi(new Tretja.Profesor(), "prof_vWzcA");
        t.prejmi(new Tretja.Profesor(), "prof_vXIBr");
        t.prejmi(new Tretja.Asistent(), "as_BozQS");
        t.prejmi(new Tretja.Asistent(), "as_2vAel");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_djF4r");
        t.prejmi(new Tretja.Profesor(), "prof_TXzx3");
        t.prejmi(new Tretja.Asistent(), "as_TWADQ");
        t.prejmi(new Tretja.Docent(), "doc_Hx7Fh");
        t.prejmi(new Tretja.Asistent(), "as_4usD8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_y6ZRs");
        t.prejmi(new Tretja.Asistent(), "as_FqycR");
        t.prejmi(new Tretja.Asistent(), "as_vQer0");
        t.prejmi(new Tretja.Docent(), "doc_glVTf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_v3azi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_86ENA");
        t.prejmi(new Tretja.Docent(), "doc_rCtX3");
        t.prejmi(new Tretja.Profesor(), "prof_mOIU5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_17DQ3");
        t.prejmi(new Tretja.Asistent(), "as_pBHum");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_oEy8K");
        t.prejmi(new Tretja.Asistent(), "as_VfpSd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_QpFXr");
        t.prejmi(new Tretja.Docent(), "doc_ab0Va");
        t.prejmi(new Tretja.Profesor(), "prof_stOpF");
        t.prejmi(new Tretja.Docent(), "doc_Ilqnv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2qfpW");
        t.prejmi(new Tretja.Profesor(), "prof_RCFf1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_3e9vl");
        t.prejmi(new Tretja.Asistent(), "as_1xCpb");
        t.prejmi(new Tretja.Profesor(), "prof_UUbTs");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hoGPP");
        t.prejmi(new Tretja.Asistent(), "as_i0B8c");
        t.prejmi(new Tretja.Asistent(), "as_YTzkg");
        t.prejmi(new Tretja.Docent(), "doc_6vTXV");
        t.prejmi(new Tretja.Docent(), "doc_BXjwS");
        t.prejmi(new Tretja.Docent(), "doc_R8FFT");
        t.prejmi(new Tretja.Asistent(), "as_XnADl");
        t.prejmi(new Tretja.Docent(), "doc_lv82J");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4Zl1i");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_N937o");
        t.prejmi(new Tretja.Asistent(), "as_WKT0y");
        t.prejmi(new Tretja.Docent(), "doc_3HA3J");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_1NRD8");
        t.prejmi(new Tretja.Docent(), "doc_wFSuj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6cMuV");
        t.prejmi(new Tretja.Asistent(), "as_RkZ0C");
        t.prejmi(new Tretja.Asistent(), "as_Oa89d");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fKxTY");
        t.prejmi(new Tretja.Docent(), "doc_5Nv9s");
        t.prejmi(new Tretja.Docent(), "doc_dZw3T");
        t.prejmi(new Tretja.Profesor(), "prof_O3QO4");
        t.prejmi(new Tretja.Asistent(), "as_Gkxx9");
        t.prejmi(new Tretja.Asistent(), "as_kZqds");
        t.prejmi(new Tretja.Asistent(), "as_oMJkX");
        t.prejmi(new Tretja.Docent(), "doc_5PpNi");
        t.prejmi(new Tretja.Profesor(), "prof_IyoPM");
        t.prejmi(new Tretja.Profesor(), "prof_CBuDN");
        t.prejmi(new Tretja.Docent(), "doc_8MjdM");
        t.prejmi(new Tretja.Docent(), "doc_6ENHC");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_0SMja");
        t.prejmi(new Tretja.Docent(), "doc_TA8SL");
        t.prejmi(new Tretja.Docent(), "doc_opcEa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_YERB8");
        t.prejmi(new Tretja.Docent(), "doc_zoi5M");
        t.prejmi(new Tretja.Docent(), "doc_HElZk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RTlnF");
        t.prejmi(new Tretja.Asistent(), "as_beCl8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_dkD7z");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_A61FA");
        t.prejmi(new Tretja.Docent(), "doc_mzvgw");
        t.prejmi(new Tretja.Asistent(), "as_RKtuC");
        t.prejmi(new Tretja.Profesor(), "prof_fej9w");
        t.prejmi(new Tretja.Asistent(), "as_92vSg");
        t.prejmi(new Tretja.Profesor(), "prof_H6eo2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_nna03");
        t.prejmi(new Tretja.Profesor(), "prof_Qv5cC");
        t.prejmi(new Tretja.Docent(), "doc_jQ07N");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9KqkW");
        t.prejmi(new Tretja.Asistent(), "as_c7xtZ");
        t.prejmi(new Tretja.Docent(), "doc_p0iph");
        t.prejmi(new Tretja.Asistent(), "as_DY4xS");
        t.prejmi(new Tretja.Profesor(), "prof_LCRUt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3oceD");
        t.prejmi(new Tretja.Asistent(), "as_UCZEQ");
        t.prejmi(new Tretja.Profesor(), "prof_OZRFO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_yPzZc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XacZq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wTtVn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Ov7RF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Vp2vp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_EYbW8");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_l21mQ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_X2ZtU");
        t.prejmi(new Tretja.Docent(), "doc_boJHv");
        t.prejmi(new Tretja.Profesor(), "prof_h0cQu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_WGrUv");
        t.prejmi(new Tretja.Docent(), "doc_xjtyQ");
        t.prejmi(new Tretja.Docent(), "doc_64Ejl");
        t.prejmi(new Tretja.Profesor(), "prof_2GhUP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_sQnEF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_OPb1u");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_uPsOJ");
        t.prejmi(new Tretja.Docent(), "doc_ami55");
        t.prejmi(new Tretja.Asistent(), "as_Uqy0Q");
        t.prejmi(new Tretja.Asistent(), "as_FryJU");
        t.prejmi(new Tretja.Profesor(), "prof_FKKi7");
        t.prejmi(new Tretja.Asistent(), "as_QKS8t");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_v93mi");
        t.prejmi(new Tretja.Docent(), "doc_jfsxt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lWqOi");
        t.prejmi(new Tretja.Asistent(), "as_DnbHI");
        t.prejmi(new Tretja.Profesor(), "prof_RjsNs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_dhl5d");
        t.prejmi(new Tretja.Profesor(), "prof_pKi7j");
        t.prejmi(new Tretja.Profesor(), "prof_ymVW0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ePrIj");
        t.prejmi(new Tretja.Docent(), "doc_zHkNh");
        t.prejmi(new Tretja.Asistent(), "as_t8qcy");
        t.prejmi(new Tretja.Asistent(), "as_pN1E7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2I8LJ");
        t.prejmi(new Tretja.Asistent(), "as_mTGYY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_26LGv");
        t.prejmi(new Tretja.Profesor(), "prof_tRSfq");
        t.prejmi(new Tretja.Profesor(), "prof_XSrQd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_AIuKK");
        t.prejmi(new Tretja.Asistent(), "as_KwrZ3");
        t.prejmi(new Tretja.Asistent(), "as_zvkrP");
        t.prejmi(new Tretja.Asistent(), "as_IeYka");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_M6mAe");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_4odwB");
        t.prejmi(new Tretja.Profesor(), "prof_R4T79");
        t.prejmi(new Tretja.Asistent(), "as_Uj2WR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6Yub0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_PzMCG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_k0GGm");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wNCCV");
        t.prejmi(new Tretja.Docent(), "doc_380bk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5x7iG");
        t.prejmi(new Tretja.Profesor(), "prof_iJIvv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_m1Z1i");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_sgcc2");
        t.prejmi(new Tretja.Asistent(), "as_eaCim");
        t.prejmi(new Tretja.Docent(), "doc_UVhUf");
        t.prejmi(new Tretja.Profesor(), "prof_1oHvD");
        t.prejmi(new Tretja.Docent(), "doc_Lhybj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JVh4L");
        t.prejmi(new Tretja.Profesor(), "prof_1jodO");
        t.prejmi(new Tretja.Profesor(), "prof_NpGgO");
        t.prejmi(new Tretja.Docent(), "doc_LenOa");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_PKMoH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_7vxYy");
        t.prejmi(new Tretja.Docent(), "doc_xYNYr");
        t.prejmi(new Tretja.Asistent(), "as_M1lff");
        t.prejmi(new Tretja.Profesor(), "prof_gp9GR");
        t.prejmi(new Tretja.Asistent(), "as_um7Q6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SrUSw");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_gphAn");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_WIDCV");
        t.prejmi(new Tretja.Docent(), "doc_sGTUr");
        t.prejmi(new Tretja.Docent(), "doc_zaJdG");
        t.prejmi(new Tretja.Asistent(), "as_4oIIB");
        t.prejmi(new Tretja.Profesor(), "prof_JvsxF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_FKPCB");
        t.prejmi(new Tretja.Profesor(), "prof_78aRz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_1G7z0");
        t.prejmi(new Tretja.Profesor(), "prof_AnF0M");
        t.prejmi(new Tretja.Asistent(), "as_2SN3L");
        t.prejmi(new Tretja.Profesor(), "prof_H8M7I");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fmrJ7");
    }
}
