
public class Test03 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_vP5hT");
        t.prejmi(new Tretja.Profesor(), "prof_QWFOs");
        t.prejmi(new Tretja.Asistent(), "as_aQh3W");
        t.prejmi(new Tretja.Profesor(), "prof_XJLRC");
        t.prejmi(new Tretja.Docent(), "doc_Lg5Jn");
        t.prejmi(new Tretja.Docent(), "doc_sU8GR");
        t.prejmi(new Tretja.Profesor(), "prof_3dHcS");
        t.prejmi(new Tretja.Docent(), "doc_xyskL");
        t.prejmi(new Tretja.Profesor(), "prof_mkjJs");
        t.prejmi(new Tretja.Docent(), "doc_3uhDV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_za6oG");
        t.prejmi(new Tretja.Asistent(), "as_Ct7kq");
        t.prejmi(new Tretja.Asistent(), "as_0OOwE");
        t.prejmi(new Tretja.Docent(), "doc_T2BD3");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_843xC");
        t.prejmi(new Tretja.Asistent(), "as_eKxA1");
        t.prejmi(new Tretja.Docent(), "doc_7nJy1");
        t.prejmi(new Tretja.Profesor(), "prof_cuBtc");
        t.prejmi(new Tretja.Docent(), "doc_Mxxs2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_UL0dh");
        t.prejmi(new Tretja.Profesor(), "prof_AWNK3");
        t.prejmi(new Tretja.Profesor(), "prof_OOOvm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_HVySX");
        t.prejmi(new Tretja.Profesor(), "prof_LRPEI");
        t.prejmi(new Tretja.Profesor(), "prof_xlnY2");
        t.prejmi(new Tretja.Asistent(), "as_ppkfQ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1ISjq");
        t.prejmi(new Tretja.Profesor(), "prof_ylLSl");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_8F2rB");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_TjVP5");
        t.prejmi(new Tretja.Profesor(), "prof_SLkRQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_18wHY");
        t.prejmi(new Tretja.Asistent(), "as_8CFJQ");
        t.prejmi(new Tretja.Profesor(), "prof_olfBg");
        t.prejmi(new Tretja.Profesor(), "prof_34NKZ");
        t.prejmi(new Tretja.Profesor(), "prof_zepKp");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_S7nbB");
        t.prejmi(new Tretja.Profesor(), "prof_V6c7R");
        t.prejmi(new Tretja.Profesor(), "prof_pmytE");
        t.prejmi(new Tretja.Docent(), "doc_9qyYy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_4oj1H");
        t.prejmi(new Tretja.Asistent(), "as_Md7Nm");
        t.prejmi(new Tretja.Profesor(), "prof_qpvsL");
        t.prejmi(new Tretja.Asistent(), "as_JXSCE");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_8zI9c");
        t.prejmi(new Tretja.Docent(), "doc_hgD7E");
        t.prejmi(new Tretja.Profesor(), "prof_TgGCN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_k4dCC");
        t.prejmi(new Tretja.Profesor(), "prof_L37TF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_kvLFD");
        t.prejmi(new Tretja.Asistent(), "as_PrsxL");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_h6JYb");
        t.prejmi(new Tretja.Docent(), "doc_1Gc90");
        t.prejmi(new Tretja.Docent(), "doc_KqPsx");
        t.prejmi(new Tretja.Profesor(), "prof_VKH3k");
        t.prejmi(new Tretja.Asistent(), "as_AeJgV");
        t.prejmi(new Tretja.Profesor(), "prof_K23rc");
        t.prejmi(new Tretja.Docent(), "doc_HVhfd");
        t.prejmi(new Tretja.Asistent(), "as_MnbDQ");
        t.prejmi(new Tretja.Docent(), "doc_r2Rx7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_05ZCI");
        t.prejmi(new Tretja.Docent(), "doc_ApMdB");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_q1NEH");
        t.prejmi(new Tretja.Profesor(), "prof_Lhkt7");
        t.prejmi(new Tretja.Asistent(), "as_Uo2O2");
        t.prejmi(new Tretja.Profesor(), "prof_o3CPk");
        t.prejmi(new Tretja.Asistent(), "as_2QOgG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_SELa3");
        t.prejmi(new Tretja.Docent(), "doc_yJ1ma");
        t.prejmi(new Tretja.Profesor(), "prof_Zxug5");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_D8CAQ");
        t.prejmi(new Tretja.Docent(), "doc_00f8o");
        t.prejmi(new Tretja.Asistent(), "as_5LH8e");
        t.prejmi(new Tretja.Asistent(), "as_ztmhV");
        t.prejmi(new Tretja.Profesor(), "prof_mrugy");
        t.prejmi(new Tretja.Profesor(), "prof_tPUwl");
        t.prejmi(new Tretja.Asistent(), "as_9CGqW");
        t.prejmi(new Tretja.Docent(), "doc_r27UK");
        t.prejmi(new Tretja.Profesor(), "prof_ESlRc");
        t.prejmi(new Tretja.Asistent(), "as_q1iGm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_MTGj3");
        t.prejmi(new Tretja.Profesor(), "prof_96PJ3");
        t.prejmi(new Tretja.Profesor(), "prof_rEyxZ");
        t.prejmi(new Tretja.Docent(), "doc_VmhRd");
        t.prejmi(new Tretja.Docent(), "doc_pSAbn");
        t.prejmi(new Tretja.Profesor(), "prof_OUXI3");
        t.prejmi(new Tretja.Profesor(), "prof_G5dC3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Pcnpi");
        t.prejmi(new Tretja.Profesor(), "prof_cCgwa");
        t.prejmi(new Tretja.Asistent(), "as_uW4FV");
        t.prejmi(new Tretja.Asistent(), "as_6XMxd");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_X553O");
        t.prejmi(new Tretja.Docent(), "doc_v4Tdl");
        t.prejmi(new Tretja.Profesor(), "prof_UvZnw");
        t.prejmi(new Tretja.Docent(), "doc_dzQTz");
        t.prejmi(new Tretja.Profesor(), "prof_PeEP3");
        t.prejmi(new Tretja.Docent(), "doc_bGTBN");
        t.prejmi(new Tretja.Docent(), "doc_emLJC");
        t.prejmi(new Tretja.Docent(), "doc_ZZ4SL");
        t.prejmi(new Tretja.Asistent(), "as_3aoQM");
        t.prejmi(new Tretja.Asistent(), "as_j5fPq");
        t.prejmi(new Tretja.Profesor(), "prof_G1p19");
        t.prejmi(new Tretja.Profesor(), "prof_2aJGx");
        t.prejmi(new Tretja.Docent(), "doc_DgIk5");
        t.prejmi(new Tretja.Asistent(), "as_BL3pB");
        t.prejmi(new Tretja.Docent(), "doc_bqoXT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_KlkI8");
        t.prejmi(new Tretja.Docent(), "doc_1fw1B");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_GGheF");
        t.prejmi(new Tretja.Asistent(), "as_jSq9g");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_FyS7a");
        t.prejmi(new Tretja.Docent(), "doc_Gei9a");
        t.prejmi(new Tretja.Asistent(), "as_DUrDY");
        t.prejmi(new Tretja.Asistent(), "as_oQopQ");
        t.prejmi(new Tretja.Docent(), "doc_ozriy");
        t.prejmi(new Tretja.Docent(), "doc_Ww4pP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_BYGXs");
        t.prejmi(new Tretja.Profesor(), "prof_Yw8kH");
        t.prejmi(new Tretja.Profesor(), "prof_bBRey");
        t.prejmi(new Tretja.Docent(), "doc_ldBKF");
        t.prejmi(new Tretja.Docent(), "doc_mKW7l");
        t.prejmi(new Tretja.Docent(), "doc_kYtZz");
        t.prejmi(new Tretja.Asistent(), "as_TXxVm");
        t.prejmi(new Tretja.Asistent(), "as_Hnni3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1CRaf");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_F8TIu");
        t.prejmi(new Tretja.Profesor(), "prof_D6MXf");
        t.prejmi(new Tretja.Asistent(), "as_fxiki");
        t.prejmi(new Tretja.Docent(), "doc_uwz2g");
        t.prejmi(new Tretja.Profesor(), "prof_goVWP");
        t.prejmi(new Tretja.Docent(), "doc_gw9Xn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_dnvy3");
        t.prejmi(new Tretja.Profesor(), "prof_DaRK0");
        t.prejmi(new Tretja.Profesor(), "prof_L2Jcu");
        t.prejmi(new Tretja.Profesor(), "prof_M8UwC");
        t.prejmi(new Tretja.Asistent(), "as_LnysP");
        t.prejmi(new Tretja.Profesor(), "prof_OT5FX");
        t.prejmi(new Tretja.Docent(), "doc_mr8Iy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_EEOGN");
        t.prejmi(new Tretja.Profesor(), "prof_EeJah");
        t.prejmi(new Tretja.Docent(), "doc_dJYsH");
        t.prejmi(new Tretja.Docent(), "doc_AZdyn");
        t.prejmi(new Tretja.Docent(), "doc_KmXm1");
        t.prejmi(new Tretja.Docent(), "doc_pipii");
        t.prejmi(new Tretja.Docent(), "doc_Q02CY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_00wn4");
        t.prejmi(new Tretja.Asistent(), "as_PrIGi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_G4v2F");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_VU48R");
        t.prejmi(new Tretja.Docent(), "doc_1aq55");
        t.prejmi(new Tretja.Asistent(), "as_Ngtyw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_INpMC");
        t.prejmi(new Tretja.Docent(), "doc_zj29z");
        t.prejmi(new Tretja.Profesor(), "prof_7Tzrl");
        t.prejmi(new Tretja.Profesor(), "prof_aJMXN");
        t.prejmi(new Tretja.Profesor(), "prof_a7uSV");
        t.prejmi(new Tretja.Profesor(), "prof_biyWw");
        t.prejmi(new Tretja.Asistent(), "as_65aQJ");
        t.prejmi(new Tretja.Profesor(), "prof_thhm2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_O23KF");
        t.prejmi(new Tretja.Profesor(), "prof_5n2CL");
        t.prejmi(new Tretja.Profesor(), "prof_7EYhy");
        t.prejmi(new Tretja.Profesor(), "prof_Tpv4e");
        t.prejmi(new Tretja.Profesor(), "prof_XnINU");
        t.prejmi(new Tretja.Asistent(), "as_Cq8r8");
        t.prejmi(new Tretja.Profesor(), "prof_pKk5p");
        t.prejmi(new Tretja.Asistent(), "as_WKq5B");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_y6dg8");
        t.prejmi(new Tretja.Profesor(), "prof_EJfok");
    }
}
