
public class Test23 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_hm7BR");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_FfRLj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_aCz8d");
        t.prejmi(new Tretja.Asistent(), "as_7dveM");
        t.prejmi(new Tretja.Profesor(), "prof_wpT61");
        t.prejmi(new Tretja.Profesor(), "prof_ZvYuy");
        t.prejmi(new Tretja.Docent(), "doc_mcBz1");
        t.prejmi(new Tretja.Docent(), "doc_K66M3");
        t.prejmi(new Tretja.Asistent(), "as_2fz1u");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_2qc8p");
        t.prejmi(new Tretja.Docent(), "doc_hSb6j");
        t.prejmi(new Tretja.Profesor(), "prof_1SK5J");
        t.prejmi(new Tretja.Profesor(), "prof_3BvyV");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_7zo9n");
        t.prejmi(new Tretja.Docent(), "doc_t7Lg7");
        t.prejmi(new Tretja.Profesor(), "prof_L6GnX");
        t.prejmi(new Tretja.Profesor(), "prof_Wd9hZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_BmTC6");
        t.prejmi(new Tretja.Docent(), "doc_95sj4");
        t.prejmi(new Tretja.Docent(), "doc_spcKZ");
        t.prejmi(new Tretja.Docent(), "doc_9vP9T");
        t.prejmi(new Tretja.Docent(), "doc_y730b");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_jfGz7");
        t.prejmi(new Tretja.Docent(), "doc_K37JH");
        t.prejmi(new Tretja.Asistent(), "as_obf5V");
        t.prejmi(new Tretja.Asistent(), "as_jylMZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_ZsYBZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Kv7Nh");
        t.prejmi(new Tretja.Profesor(), "prof_2DuFU");
        t.prejmi(new Tretja.Asistent(), "as_uHg1G");
        t.prejmi(new Tretja.Docent(), "doc_EST2w");
        t.prejmi(new Tretja.Docent(), "doc_tbJpB");
        t.prejmi(new Tretja.Asistent(), "as_bRwMh");
        t.prejmi(new Tretja.Docent(), "doc_kiKtj");
        t.prejmi(new Tretja.Profesor(), "prof_XwasT");
        t.prejmi(new Tretja.Profesor(), "prof_M3YZ6");
        t.prejmi(new Tretja.Docent(), "doc_4ax5T");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_mtt9I");
        t.prejmi(new Tretja.Profesor(), "prof_uW2KO");
        t.prejmi(new Tretja.Asistent(), "as_e92aN");
        t.prejmi(new Tretja.Docent(), "doc_M8TF0");
        t.prejmi(new Tretja.Profesor(), "prof_N68qr");
        t.prejmi(new Tretja.Profesor(), "prof_QFH2u");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_AnWhE");
        t.prejmi(new Tretja.Asistent(), "as_peyTQ");
        t.prejmi(new Tretja.Docent(), "doc_3RVaN");
        t.prejmi(new Tretja.Asistent(), "as_dLpLi");
        t.prejmi(new Tretja.Profesor(), "prof_W7nTW");
        t.prejmi(new Tretja.Docent(), "doc_4vEnY");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_PfPBH");
        t.prejmi(new Tretja.Profesor(), "prof_7j2LI");
        t.prejmi(new Tretja.Docent(), "doc_fKmJQ");
        t.prejmi(new Tretja.Asistent(), "as_6Gxkm");
        t.prejmi(new Tretja.Docent(), "doc_2aA8c");
        t.prejmi(new Tretja.Profesor(), "prof_aklgA");
        t.prejmi(new Tretja.Asistent(), "as_hHm3C");
        t.prejmi(new Tretja.Docent(), "doc_vCHzA");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_nYdAa");
        t.prejmi(new Tretja.Profesor(), "prof_woxFU");
        t.prejmi(new Tretja.Docent(), "doc_57rQu");
        t.prejmi(new Tretja.Docent(), "doc_E8oHw");
        t.prejmi(new Tretja.Profesor(), "prof_21sUk");
        t.prejmi(new Tretja.Asistent(), "as_wtos7");
        t.prejmi(new Tretja.Profesor(), "prof_8iif3");
        t.prejmi(new Tretja.Asistent(), "as_1vXQs");
        t.prejmi(new Tretja.Asistent(), "as_5kBRH");
        t.prejmi(new Tretja.Asistent(), "as_00VOI");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_mYyj7");
        t.prejmi(new Tretja.Docent(), "doc_6uf4g");
        t.prejmi(new Tretja.Docent(), "doc_OuCvZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_KVZwR");
        t.prejmi(new Tretja.Profesor(), "prof_SElQB");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_GNRBN");
        t.prejmi(new Tretja.Asistent(), "as_ZJcY0");
        t.prejmi(new Tretja.Docent(), "doc_qGtlV");
        t.prejmi(new Tretja.Docent(), "doc_3aOQ4");
        t.prejmi(new Tretja.Profesor(), "prof_KraaY");
        t.prejmi(new Tretja.Docent(), "doc_xeiso");
        t.prejmi(new Tretja.Docent(), "doc_3DXYN");
        t.prejmi(new Tretja.Profesor(), "prof_eyJ4C");
        t.prejmi(new Tretja.Profesor(), "prof_A5L50");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_TSbyG");
        t.prejmi(new Tretja.Docent(), "doc_Qb7qT");
        t.prejmi(new Tretja.Docent(), "doc_5Cwmq");
        t.prejmi(new Tretja.Profesor(), "prof_HduHI");
        t.prejmi(new Tretja.Docent(), "doc_zHwqU");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_voYr5");
        t.prejmi(new Tretja.Asistent(), "as_KqmYY");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_T9aO9");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_uu6fb");
        t.prejmi(new Tretja.Docent(), "doc_lGpsX");
        t.prejmi(new Tretja.Asistent(), "as_fH0TL");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_WAW2m");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_3aOGF");
        t.prejmi(new Tretja.Profesor(), "prof_evEEr");
        t.prejmi(new Tretja.Docent(), "doc_haCYN");
        t.prejmi(new Tretja.Profesor(), "prof_W9glV");
        t.prejmi(new Tretja.Profesor(), "prof_21vlc");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_bKr4O");
        t.prejmi(new Tretja.Docent(), "doc_J2qIa");
        t.prejmi(new Tretja.Profesor(), "prof_zkIKR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_hsWGd");
        t.prejmi(new Tretja.Docent(), "doc_AU21m");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_CwqnV");
        t.prejmi(new Tretja.Profesor(), "prof_qWQmi");
        t.prejmi(new Tretja.Asistent(), "as_RgZS7");
        t.prejmi(new Tretja.Docent(), "doc_VkWZI");
        t.prejmi(new Tretja.Profesor(), "prof_5N94Q");
        t.prejmi(new Tretja.Asistent(), "as_Jj1nG");
        t.prejmi(new Tretja.Asistent(), "as_tZsJi");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_sgm0u");
        t.prejmi(new Tretja.Profesor(), "prof_e3xGh");
        t.prejmi(new Tretja.Asistent(), "as_x38tA");
        t.prejmi(new Tretja.Asistent(), "as_Nptvm");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_DVSco");
        t.prejmi(new Tretja.Asistent(), "as_Mc69E");
        t.prejmi(new Tretja.Profesor(), "prof_k5a3r");
        t.prejmi(new Tretja.Profesor(), "prof_cum9Z");
        t.prejmi(new Tretja.Profesor(), "prof_DjdqM");
        t.prejmi(new Tretja.Asistent(), "as_NS4gs");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_M4zx1");
        t.prejmi(new Tretja.Profesor(), "prof_KsPH2");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_ldE3m");
        t.prejmi(new Tretja.Asistent(), "as_ByWRN");
        t.prejmi(new Tretja.Profesor(), "prof_xxAd5");
        t.prejmi(new Tretja.Profesor(), "prof_WUXax");
        t.prejmi(new Tretja.Asistent(), "as_tnFJf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_LRZST");
        t.prejmi(new Tretja.Profesor(), "prof_4PPvg");
        t.prejmi(new Tretja.Docent(), "doc_mUjl4");
        t.prejmi(new Tretja.Docent(), "doc_k9eCx");
        t.prejmi(new Tretja.Docent(), "doc_HV7XA");
        t.prejmi(new Tretja.Docent(), "doc_LPPKN");
        t.prejmi(new Tretja.Asistent(), "as_vcazv");
        t.prejmi(new Tretja.Asistent(), "as_tn7eb");
        t.prejmi(new Tretja.Asistent(), "as_mn38d");
        t.prejmi(new Tretja.Docent(), "doc_vPQM0");
        t.prejmi(new Tretja.Docent(), "doc_Z7OBM");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_GhXIM");
        t.prejmi(new Tretja.Asistent(), "as_IpaRn");
        t.prejmi(new Tretja.Profesor(), "prof_0Qhmi");
        t.prejmi(new Tretja.Asistent(), "as_E2ofC");
        t.prejmi(new Tretja.Docent(), "doc_TCY89");
        t.prejmi(new Tretja.Asistent(), "as_TkTpW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_nWGCX");
        t.prejmi(new Tretja.Asistent(), "as_I4Awn");
        t.prejmi(new Tretja.Asistent(), "as_vzooq");
        t.prejmi(new Tretja.Docent(), "doc_p3GRI");
        t.prejmi(new Tretja.Profesor(), "prof_i0Nmu");
        t.prejmi(new Tretja.Profesor(), "prof_7QoVl");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_9uBPP");
        t.prejmi(new Tretja.Asistent(), "as_b1iaV");
        t.prejmi(new Tretja.Profesor(), "prof_wGKbi");
        t.prejmi(new Tretja.Docent(), "doc_kfuA0");
        t.prejmi(new Tretja.Profesor(), "prof_fyWJL");
        t.prejmi(new Tretja.Docent(), "doc_fog67");
        t.prejmi(new Tretja.Docent(), "doc_TgVa2");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_qNfbx");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_pFmes");
        t.prejmi(new Tretja.Docent(), "doc_1r1Yk");
        t.prejmi(new Tretja.Asistent(), "as_afi4E");
        t.prejmi(new Tretja.Docent(), "doc_C5Tdg");
        t.prejmi(new Tretja.Profesor(), "prof_fK3I5");
        t.prejmi(new Tretja.Profesor(), "prof_d3yWQ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_bulU5");
        t.prejmi(new Tretja.Asistent(), "as_OF28n");
        t.prejmi(new Tretja.Profesor(), "prof_8iZnM");
        t.prejmi(new Tretja.Profesor(), "prof_Kr8wh");
        t.prejmi(new Tretja.Profesor(), "prof_KWYch");
        t.prejmi(new Tretja.Docent(), "doc_uUIqQ");
        t.prejmi(new Tretja.Profesor(), "prof_dMpGl");
        t.prejmi(new Tretja.Profesor(), "prof_wcUn7");
        t.prejmi(new Tretja.Profesor(), "prof_54NYG");
        t.prejmi(new Tretja.Asistent(), "as_b4Aqv");
        t.prejmi(new Tretja.Profesor(), "prof_V6MI7");
        t.prejmi(new Tretja.Profesor(), "prof_Eqsok");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Vhh6x");
        t.prejmi(new Tretja.Profesor(), "prof_yZ313");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_JhdCk");
        t.prejmi(new Tretja.Asistent(), "as_O4SPJ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_h8568");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_coNty");
        t.prejmi(new Tretja.Asistent(), "as_hcZXH");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_9E5P1");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_77vF7");
        t.prejmi(new Tretja.Asistent(), "as_adZsM");
        t.prejmi(new Tretja.Profesor(), "prof_wqpjc");
        t.prejmi(new Tretja.Asistent(), "as_wB8M2");
        t.prejmi(new Tretja.Docent(), "doc_7qZnY");
        t.prejmi(new Tretja.Docent(), "doc_LjSVe");
        t.prejmi(new Tretja.Asistent(), "as_bBZAz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Smhqk");
        t.prejmi(new Tretja.Docent(), "doc_jFQJR");
        t.prejmi(new Tretja.Profesor(), "prof_DdwZg");
        t.prejmi(new Tretja.Docent(), "doc_O6BCm");
        t.prejmi(new Tretja.Profesor(), "prof_CSTAV");
        t.prejmi(new Tretja.Asistent(), "as_w2AXs");
        t.prejmi(new Tretja.Docent(), "doc_A8eNx");
        t.prejmi(new Tretja.Profesor(), "prof_veFWR");
        t.prejmi(new Tretja.Profesor(), "prof_NWE9K");
        t.prejmi(new Tretja.Asistent(), "as_R9BPh");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_rS73l");
        t.prejmi(new Tretja.Docent(), "doc_uRHCr");
        t.prejmi(new Tretja.Profesor(), "prof_NRN5E");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_NGVS2");
        t.prejmi(new Tretja.Docent(), "doc_cY1B1");
        t.prejmi(new Tretja.Profesor(), "prof_NBGn0");
        t.prejmi(new Tretja.Asistent(), "as_BaG4B");
        t.prejmi(new Tretja.Profesor(), "prof_eZjps");
        t.prejmi(new Tretja.Docent(), "doc_Jp6ZW");
        t.prejmi(new Tretja.Profesor(), "prof_Sf1qx");
        t.prejmi(new Tretja.Asistent(), "as_R5VfL");
        t.prejmi(new Tretja.Asistent(), "as_cegQe");
        t.prejmi(new Tretja.Profesor(), "prof_DlbEh");
        t.prejmi(new Tretja.Asistent(), "as_m7wGf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_CSMFA");
        t.prejmi(new Tretja.Docent(), "doc_GOUJS");
        t.prejmi(new Tretja.Profesor(), "prof_7AF8T");
        t.prejmi(new Tretja.Asistent(), "as_Npfgl");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_8uSpQ");
        t.prejmi(new Tretja.Docent(), "doc_x5MtS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_dYBSu");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_zYGG8");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_tmdq7");
        t.prejmi(new Tretja.Profesor(), "prof_6sWLl");
        t.prejmi(new Tretja.Profesor(), "prof_FaiMQ");
        t.prejmi(new Tretja.Docent(), "doc_ZX8qv");
        t.prejmi(new Tretja.Profesor(), "prof_t3YhA");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_snCIg");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_EEJV4");
        t.prejmi(new Tretja.Docent(), "doc_njnha");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_U1Mao");
        t.prejmi(new Tretja.Profesor(), "prof_cCZLi");
        t.prejmi(new Tretja.Docent(), "doc_PvylH");
        t.prejmi(new Tretja.Asistent(), "as_PKp33");
        t.prejmi(new Tretja.Profesor(), "prof_cU8nJ");
        t.prejmi(new Tretja.Docent(), "doc_izxTZ");
        t.prejmi(new Tretja.Docent(), "doc_VXnLN");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_x7Cef");
        t.prejmi(new Tretja.Asistent(), "as_TXcKb");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_QzOC6");
        t.prejmi(new Tretja.Profesor(), "prof_Hqj6J");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_nsqF0");
        t.prejmi(new Tretja.Profesor(), "prof_gykg5");
        t.prejmi(new Tretja.Asistent(), "as_bjI8J");
        t.prejmi(new Tretja.Docent(), "doc_YIAPr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_qaUCE");
        t.prejmi(new Tretja.Profesor(), "prof_PHsTj");
        t.prejmi(new Tretja.Docent(), "doc_XtiHS");
        t.prejmi(new Tretja.Asistent(), "as_z5ZMV");
        t.prejmi(new Tretja.Docent(), "doc_VtDd6");
        t.prejmi(new Tretja.Profesor(), "prof_gDWkE");
        t.prejmi(new Tretja.Docent(), "doc_q216P");
        t.prejmi(new Tretja.Profesor(), "prof_rR4as");
        t.prejmi(new Tretja.Asistent(), "as_VgW0n");
        t.prejmi(new Tretja.Profesor(), "prof_3bRYl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_a6RcL");
        t.prejmi(new Tretja.Docent(), "doc_rwQrj");
        t.prejmi(new Tretja.Docent(), "doc_blo6c");
        t.prejmi(new Tretja.Profesor(), "prof_nwB9K");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_Sep3C");
        t.prejmi(new Tretja.Asistent(), "as_9tWfu");
        t.prejmi(new Tretja.Profesor(), "prof_Fj0oE");
        t.prejmi(new Tretja.Asistent(), "as_ZdVn2");
        t.prejmi(new Tretja.Docent(), "doc_j7UBS");
        t.prejmi(new Tretja.Asistent(), "as_V5AMy");
        t.prejmi(new Tretja.Asistent(), "as_TyZpH");
        t.prejmi(new Tretja.Asistent(), "as_WhqWJ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_4ZGLx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_8J7pX");
        t.prejmi(new Tretja.Asistent(), "as_2mZgi");
        t.prejmi(new Tretja.Asistent(), "as_qYXij");
        t.prejmi(new Tretja.Asistent(), "as_VeKaC");
        t.prejmi(new Tretja.Docent(), "doc_CG5Fh");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_EYYmg");
        t.prejmi(new Tretja.Profesor(), "prof_0twMN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_YTxlD");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_S7aEM");
        t.prejmi(new Tretja.Profesor(), "prof_73L6X");
        t.prejmi(new Tretja.Docent(), "doc_9Sv5m");
        t.prejmi(new Tretja.Asistent(), "as_5C8Fz");
        t.prejmi(new Tretja.Asistent(), "as_BPzDr");
        t.prejmi(new Tretja.Profesor(), "prof_Ck16O");
        t.prejmi(new Tretja.Profesor(), "prof_gMWTB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_CDcSC");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_koqST");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_09GJV");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_kb2LH");
        t.prejmi(new Tretja.Docent(), "doc_7MwpZ");
        t.prejmi(new Tretja.Profesor(), "prof_G4BXT");
        t.prejmi(new Tretja.Asistent(), "as_A733S");
        t.prejmi(new Tretja.Profesor(), "prof_TAWul");
        t.prejmi(new Tretja.Asistent(), "as_qn1Gz");
        t.prejmi(new Tretja.Asistent(), "as_rAAzv");
        t.prejmi(new Tretja.Asistent(), "as_P46PC");
        t.prejmi(new Tretja.Profesor(), "prof_MFyIG");
        t.prejmi(new Tretja.Docent(), "doc_MrGIG");
        t.prejmi(new Tretja.Profesor(), "prof_CcNid");
        t.prejmi(new Tretja.Profesor(), "prof_qnsnc");
        t.prejmi(new Tretja.Asistent(), "as_aA4zV");
        t.prejmi(new Tretja.Profesor(), "prof_Fegno");
        t.prejmi(new Tretja.Asistent(), "as_4XIQE");
        t.prejmi(new Tretja.Profesor(), "prof_1VDGM");
        t.prejmi(new Tretja.Profesor(), "prof_10frG");
        t.prejmi(new Tretja.Profesor(), "prof_xPwIe");
        t.prejmi(new Tretja.Docent(), "doc_XQxSU");
        t.prejmi(new Tretja.Docent(), "doc_gYT89");
        t.prejmi(new Tretja.Asistent(), "as_LDp9J");
        t.prejmi(new Tretja.Docent(), "doc_IMOYO");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_hM658");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_WlCdl");
        t.prejmi(new Tretja.Profesor(), "prof_x1A0J");
        t.prejmi(new Tretja.Profesor(), "prof_1uvnJ");
        t.prejmi(new Tretja.Asistent(), "as_ZLqz4");
        t.prejmi(new Tretja.Asistent(), "as_9UcSr");
        t.prejmi(new Tretja.Profesor(), "prof_o8ctR");
        t.prejmi(new Tretja.Docent(), "doc_QEtRF");
        t.prejmi(new Tretja.Profesor(), "prof_bFG9A");
        t.prejmi(new Tretja.Asistent(), "as_JFlFD");
        t.prejmi(new Tretja.Docent(), "doc_ZpRk1");
        t.prejmi(new Tretja.Profesor(), "prof_nCGoh");
        t.prejmi(new Tretja.Asistent(), "as_blOBp");
        t.prejmi(new Tretja.Profesor(), "prof_52sxS");
        t.prejmi(new Tretja.Docent(), "doc_spJ1M");
        t.prejmi(new Tretja.Profesor(), "prof_CL2X0");
        t.prejmi(new Tretja.Docent(), "doc_ELMD0");
        t.prejmi(new Tretja.Asistent(), "as_Qgczi");
        t.prejmi(new Tretja.Asistent(), "as_YMjPl");
        t.prejmi(new Tretja.Docent(), "doc_ta8t4");
        t.prejmi(new Tretja.Profesor(), "prof_jdqms");
        t.prejmi(new Tretja.Profesor(), "prof_KpmLS");
        t.prejmi(new Tretja.Docent(), "doc_xwWkt");
        t.prejmi(new Tretja.Asistent(), "as_tW7kF");
        t.prejmi(new Tretja.Docent(), "doc_yGqvm");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_Oh7Av");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_jB4Gm");
        t.prejmi(new Tretja.Profesor(), "prof_gxA4y");
        t.prejmi(new Tretja.Docent(), "doc_tialF");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_a5ewG");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_41Zbq");
        t.prejmi(new Tretja.Asistent(), "as_rheJL");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_IW5yP");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_uzA6e");
        t.prejmi(new Tretja.Profesor(), "prof_JhThL");
        t.prejmi(new Tretja.Asistent(), "as_JMGm3");
        t.prejmi(new Tretja.Asistent(), "as_J1EyU");
        t.prejmi(new Tretja.Docent(), "doc_btKCh");
        t.prejmi(new Tretja.Profesor(), "prof_9sMRR");
        t.prejmi(new Tretja.Docent(), "doc_Nr6IT");
        t.prejmi(new Tretja.Profesor(), "prof_HZOOv");
        t.prejmi(new Tretja.Asistent(), "as_c4xfw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_Wg7Wl");
        t.prejmi(new Tretja.Asistent(), "as_R8QZC");
        t.prejmi(new Tretja.Asistent(), "as_wCguB");
        t.prejmi(new Tretja.Asistent(), "as_3CQaw");
        t.prejmi(new Tretja.Docent(), "doc_ZrQQU");
        t.prejmi(new Tretja.Asistent(), "as_Wd8Sc");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Mrzcn");
        t.prejmi(new Tretja.Asistent(), "as_bjX6y");
        t.prejmi(new Tretja.Asistent(), "as_ETQVF");
        t.prejmi(new Tretja.Asistent(), "as_7l1bh");
        t.prejmi(new Tretja.Docent(), "doc_GGtXb");
        t.prejmi(new Tretja.Asistent(), "as_bjgiD");
        t.prejmi(new Tretja.Asistent(), "as_iXHiJ");
        t.prejmi(new Tretja.Docent(), "doc_6OWya");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_lOkAv");
        t.prejmi(new Tretja.Docent(), "doc_srup1");
        t.prejmi(new Tretja.Profesor(), "prof_IBdyZ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_MdQI2");
        t.prejmi(new Tretja.Profesor(), "prof_JZ2Qv");
        t.prejmi(new Tretja.Asistent(), "as_abB8h");
        t.prejmi(new Tretja.Asistent(), "as_u3iim");
        t.prejmi(new Tretja.Docent(), "doc_UkzD3");
        t.prejmi(new Tretja.Asistent(), "as_YKBng");
        t.prejmi(new Tretja.Docent(), "doc_0wIke");
        t.prejmi(new Tretja.Docent(), "doc_lW6wM");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_bYQbi");
        t.prejmi(new Tretja.Asistent(), "as_tKOWX");
        t.prejmi(new Tretja.Docent(), "doc_R59IA");
        t.prejmi(new Tretja.Asistent(), "as_kiYfg");
        t.prejmi(new Tretja.Docent(), "doc_RD14r");
        t.prejmi(new Tretja.Profesor(), "prof_FSbW5");
        t.prejmi(new Tretja.Asistent(), "as_shmEf");
        t.prejmi(new Tretja.Docent(), "doc_dbnfd");
        t.prejmi(new Tretja.Asistent(), "as_B7TrG");
        t.prejmi(new Tretja.Asistent(), "as_vRSQV");
        t.prejmi(new Tretja.Profesor(), "prof_NW13u");
        t.prejmi(new Tretja.Profesor(), "prof_OBXyD");
        t.prejmi(new Tretja.Asistent(), "as_Bzv8W");
        t.prejmi(new Tretja.Profesor(), "prof_XhXtR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_eVJVu");
        t.prejmi(new Tretja.Docent(), "doc_rMeau");
        t.prejmi(new Tretja.Asistent(), "as_44nWt");
        t.prejmi(new Tretja.Asistent(), "as_qHKlU");
        t.prejmi(new Tretja.Asistent(), "as_MIIFx");
        t.prejmi(new Tretja.Asistent(), "as_enXWl");
        t.prejmi(new Tretja.Profesor(), "prof_n2mvB");
        t.prejmi(new Tretja.Asistent(), "as_14pmk");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_eyXRU");
        t.prejmi(new Tretja.Docent(), "doc_yoVwD");
        t.prejmi(new Tretja.Profesor(), "prof_xU9zC");
        t.prejmi(new Tretja.Asistent(), "as_wrgEb");
        t.prejmi(new Tretja.Docent(), "doc_J7LmV");
        t.prejmi(new Tretja.Asistent(), "as_cRoG0");
        t.prejmi(new Tretja.Docent(), "doc_aurf5");
        t.prejmi(new Tretja.Profesor(), "prof_kx9VS");
        t.prejmi(new Tretja.Profesor(), "prof_C7AG2");
        t.prejmi(new Tretja.Docent(), "doc_CbHs7");
        t.prejmi(new Tretja.Docent(), "doc_sgKPA");
        t.prejmi(new Tretja.Profesor(), "prof_JGaHC");
        t.prejmi(new Tretja.Profesor(), "prof_FLsp6");
        t.prejmi(new Tretja.Asistent(), "as_uP0TN");
        t.prejmi(new Tretja.Profesor(), "prof_fo42J");
        t.prejmi(new Tretja.Docent(), "doc_y1x4N");
        t.prejmi(new Tretja.Docent(), "doc_DZVMc");
        t.prejmi(new Tretja.Docent(), "doc_5yvn6");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_qtSiv");
        t.prejmi(new Tretja.Asistent(), "as_8Dj4k");
        t.prejmi(new Tretja.Profesor(), "prof_MbS2o");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_pipLe");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_UI8U4");
        t.prejmi(new Tretja.Docent(), "doc_RDCkO");
        t.prejmi(new Tretja.Asistent(), "as_RaOYm");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_dJZDg");
        t.prejmi(new Tretja.Asistent(), "as_kl3lu");
        t.prejmi(new Tretja.Docent(), "doc_vZLQ9");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_ZCOYt");
        t.prejmi(new Tretja.Profesor(), "prof_cMQAQ");
        t.prejmi(new Tretja.Docent(), "doc_evvmq");
        t.prejmi(new Tretja.Asistent(), "as_SRYqM");
        t.prejmi(new Tretja.Asistent(), "as_ynZSK");
        t.prejmi(new Tretja.Asistent(), "as_NKvD9");
        t.prejmi(new Tretja.Profesor(), "prof_KiRP1");
        t.prejmi(new Tretja.Profesor(), "prof_z4YJt");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_OIcD0");
        t.prejmi(new Tretja.Profesor(), "prof_AgV3Z");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_68AUb");
        t.prejmi(new Tretja.Docent(), "doc_vRUaT");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_dQXYv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Gu9TM");
        t.prejmi(new Tretja.Profesor(), "prof_zXNCh");
        t.prejmi(new Tretja.Asistent(), "as_uqIjo");
        t.prejmi(new Tretja.Asistent(), "as_q00fB");
        t.prejmi(new Tretja.Asistent(), "as_yO41q");
        t.prejmi(new Tretja.Asistent(), "as_A0l6G");
        t.prejmi(new Tretja.Docent(), "doc_Jxhvl");
        t.prejmi(new Tretja.Asistent(), "as_XJ9W0");
        t.prejmi(new Tretja.Asistent(), "as_4nOE9");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_OqAEJ");
        t.prejmi(new Tretja.Docent(), "doc_fccwE");
        t.prejmi(new Tretja.Profesor(), "prof_X5zQM");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_j2qRs");
    }
}
