
public class Test18 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_blStL");
        t.prejmi(new Tretja.Asistent(), "as_mGWHp");
        t.prejmi(new Tretja.Profesor(), "prof_89vWd");
        t.prejmi(new Tretja.Profesor(), "prof_6O79V");
        t.prejmi(new Tretja.Asistent(), "as_CYEIz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_Ng1Po");
        t.prejmi(new Tretja.Docent(), "doc_IzU0a");
        t.prejmi(new Tretja.Docent(), "doc_O0y9Q");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_PMUiX");
        t.prejmi(new Tretja.Profesor(), "prof_C6bic");
        t.prejmi(new Tretja.Profesor(), "prof_ycBqn");
        t.prejmi(new Tretja.Asistent(), "as_xCMdO");
        t.prejmi(new Tretja.Profesor(), "prof_4RPnI");
        t.prejmi(new Tretja.Docent(), "doc_5fOnD");
        t.prejmi(new Tretja.Profesor(), "prof_3o5Ws");
        t.prejmi(new Tretja.Asistent(), "as_hJpCj");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_hlXoH");
        t.prejmi(new Tretja.Profesor(), "prof_ldiye");
        t.prejmi(new Tretja.Asistent(), "as_GKxsO");
        t.prejmi(new Tretja.Docent(), "doc_YMybC");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_n1voe");
        t.prejmi(new Tretja.Profesor(), "prof_fwi8T");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_xBpky");
        t.prejmi(new Tretja.Asistent(), "as_iRnWh");
        t.prejmi(new Tretja.Asistent(), "as_gPSZR");
        t.prejmi(new Tretja.Docent(), "doc_EmzJ7");
        t.prejmi(new Tretja.Profesor(), "prof_2MGDB");
        t.prejmi(new Tretja.Docent(), "doc_EWMSD");
        t.prejmi(new Tretja.Asistent(), "as_0x076");
        t.prejmi(new Tretja.Profesor(), "prof_UCXA1");
        t.prejmi(new Tretja.Docent(), "doc_RtF6g");
        t.prejmi(new Tretja.Asistent(), "as_mUlV7");
        t.prejmi(new Tretja.Docent(), "doc_SrbQ9");
        t.prejmi(new Tretja.Profesor(), "prof_rTpfl");
        t.prejmi(new Tretja.Profesor(), "prof_SIczf");
        t.prejmi(new Tretja.Profesor(), "prof_vFFeP");
        t.prejmi(new Tretja.Docent(), "doc_UJDAB");
        t.prejmi(new Tretja.Docent(), "doc_XAXis");
        t.prejmi(new Tretja.Asistent(), "as_chFLB");
        t.prejmi(new Tretja.Asistent(), "as_noRbm");
        t.prejmi(new Tretja.Docent(), "doc_qrWiE");
        t.prejmi(new Tretja.Profesor(), "prof_QRymN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_FyTHT");
        t.prejmi(new Tretja.Asistent(), "as_GIzyf");
        t.prejmi(new Tretja.Docent(), "doc_LvUtR");
        t.prejmi(new Tretja.Profesor(), "prof_Unw4j");
        t.prejmi(new Tretja.Docent(), "doc_LVeag");
        t.prejmi(new Tretja.Profesor(), "prof_Qdgj7");
        t.prejmi(new Tretja.Profesor(), "prof_y6q15");
        t.prejmi(new Tretja.Profesor(), "prof_eO0Ed");
        t.prejmi(new Tretja.Docent(), "doc_dgQJf");
        t.prejmi(new Tretja.Profesor(), "prof_oYu1O");
        t.prejmi(new Tretja.Profesor(), "prof_k6fxm");
        t.prejmi(new Tretja.Asistent(), "as_SFME7");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_sg1Mm");
        t.prejmi(new Tretja.Profesor(), "prof_GwKTs");
        t.prejmi(new Tretja.Asistent(), "as_l7gss");
        t.prejmi(new Tretja.Docent(), "doc_epfZz");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_6i1KA");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_kVm3Q");
        t.prejmi(new Tretja.Profesor(), "prof_05ray");
        t.prejmi(new Tretja.Asistent(), "as_vFhKE");
        t.prejmi(new Tretja.Profesor(), "prof_4S9Y4");
        t.prejmi(new Tretja.Profesor(), "prof_ruiWE");
        t.prejmi(new Tretja.Profesor(), "prof_Xtqnt");
        t.prejmi(new Tretja.Profesor(), "prof_rmFYN");
        t.prejmi(new Tretja.Docent(), "doc_U0w8X");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_VScg2");
        t.prejmi(new Tretja.Docent(), "doc_LyuAZ");
        t.prejmi(new Tretja.Profesor(), "prof_HUc5H");
        t.prejmi(new Tretja.Docent(), "doc_OoCRx");
        t.prejmi(new Tretja.Profesor(), "prof_Z0M9U");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_XnoQB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Jv8co");
        t.prejmi(new Tretja.Profesor(), "prof_mQLG5");
        t.prejmi(new Tretja.Asistent(), "as_CMiDO");
        t.prejmi(new Tretja.Asistent(), "as_PhKVm");
        t.prejmi(new Tretja.Docent(), "doc_vrl5N");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_lFDis");
        t.prejmi(new Tretja.Asistent(), "as_w0a4G");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_JE8ay");
        t.prejmi(new Tretja.Profesor(), "prof_GkVas");
        t.prejmi(new Tretja.Docent(), "doc_kYR3j");
        t.prejmi(new Tretja.Docent(), "doc_l5wFv");
        t.prejmi(new Tretja.Profesor(), "prof_IVE9B");
        t.prejmi(new Tretja.Profesor(), "prof_x8AkK");
        t.prejmi(new Tretja.Docent(), "doc_KzMW9");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_eVXHp");
        t.prejmi(new Tretja.Profesor(), "prof_0U8vG");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_o9XPe");
        t.prejmi(new Tretja.Docent(), "doc_MCyli");
        t.prejmi(new Tretja.Profesor(), "prof_Atn8m");
        t.prejmi(new Tretja.Docent(), "doc_W1k4d");
        t.prejmi(new Tretja.Profesor(), "prof_vuyrB");
        t.prejmi(new Tretja.Profesor(), "prof_p9CCk");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_0tQwr");
        t.prejmi(new Tretja.Profesor(), "prof_y1Hgm");
        t.prejmi(new Tretja.Asistent(), "as_ANWJC");
        t.prejmi(new Tretja.Profesor(), "prof_0QIc4");
        t.prejmi(new Tretja.Profesor(), "prof_myqps");
        t.prejmi(new Tretja.Asistent(), "as_1Gfuv");
        t.prejmi(new Tretja.Asistent(), "as_n9E5z");
        t.prejmi(new Tretja.Profesor(), "prof_RuXYj");
        t.prejmi(new Tretja.Asistent(), "as_VNSvY");
        t.prejmi(new Tretja.Asistent(), "as_9q5Pg");
        t.prejmi(new Tretja.Profesor(), "prof_AYIW8");
        t.prejmi(new Tretja.Profesor(), "prof_SfItL");
        t.prejmi(new Tretja.Docent(), "doc_QxJW6");
        t.prejmi(new Tretja.Asistent(), "as_UJt49");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_rfUPj");
        t.prejmi(new Tretja.Asistent(), "as_GFSJI");
        t.prejmi(new Tretja.Asistent(), "as_6bUBo");
        t.prejmi(new Tretja.Asistent(), "as_igzDo");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_kDU9y");
        t.prejmi(new Tretja.Docent(), "doc_qZ61C");
        t.prejmi(new Tretja.Asistent(), "as_XHhgM");
        t.prejmi(new Tretja.Asistent(), "as_rfJlH");
        t.prejmi(new Tretja.Asistent(), "as_yIJvD");
        t.prejmi(new Tretja.Docent(), "doc_wOvj7");
        t.prejmi(new Tretja.Asistent(), "as_4Mmg2");
        t.prejmi(new Tretja.Docent(), "doc_D6vLm");
        t.prejmi(new Tretja.Docent(), "doc_GiwvJ");
        t.prejmi(new Tretja.Docent(), "doc_sv3O2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_9zXfe");
        t.prejmi(new Tretja.Asistent(), "as_ySClm");
        t.prejmi(new Tretja.Profesor(), "prof_dPbb5");
        t.prejmi(new Tretja.Asistent(), "as_k7ZiD");
        t.prejmi(new Tretja.Docent(), "doc_KS43k");
        t.prejmi(new Tretja.Asistent(), "as_angqX");
        t.prejmi(new Tretja.Asistent(), "as_zVuuz");
        t.prejmi(new Tretja.Profesor(), "prof_kRq9Q");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_lwmjK");
        t.prejmi(new Tretja.Docent(), "doc_AU7ml");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_uOaDF");
        t.prejmi(new Tretja.Docent(), "doc_iJAAO");
        t.prejmi(new Tretja.Asistent(), "as_CeMh9");
        t.prejmi(new Tretja.Docent(), "doc_83t9A");
        t.prejmi(new Tretja.Profesor(), "prof_DY7Ih");
        t.prejmi(new Tretja.Asistent(), "as_Z2glz");
        t.prejmi(new Tretja.Profesor(), "prof_gfwKu");
        t.prejmi(new Tretja.Docent(), "doc_Pi9ZY");
        t.prejmi(new Tretja.Profesor(), "prof_1vdAP");
        t.prejmi(new Tretja.Profesor(), "prof_RDQzv");
        t.prejmi(new Tretja.Asistent(), "as_YVr6e");
        t.prejmi(new Tretja.Docent(), "doc_QHW3g");
        t.prejmi(new Tretja.Asistent(), "as_AgnYC");
        t.prejmi(new Tretja.Asistent(), "as_KGiM7");
        t.prejmi(new Tretja.Asistent(), "as_sukgb");
        t.prejmi(new Tretja.Profesor(), "prof_yw9Y7");
        t.prejmi(new Tretja.Asistent(), "as_BdcrB");
        t.prejmi(new Tretja.Profesor(), "prof_Ek2f6");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_raJeZ");
        t.prejmi(new Tretja.Docent(), "doc_1NGoA");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_dEl8V");
        t.prejmi(new Tretja.Profesor(), "prof_x8hm7");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_8WjYg");
        t.prejmi(new Tretja.Profesor(), "prof_AeOA2");
        t.prejmi(new Tretja.Profesor(), "prof_rmSPs");
        t.prejmi(new Tretja.Asistent(), "as_9Kmn3");
        t.prejmi(new Tretja.Docent(), "doc_kCH0l");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_muBU1");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_2Zgve");
        t.prejmi(new Tretja.Docent(), "doc_odlLV");
        t.prejmi(new Tretja.Asistent(), "as_gboJr");
        t.prejmi(new Tretja.Asistent(), "as_MgvTn");
        t.prejmi(new Tretja.Docent(), "doc_WmaQ4");
        t.prejmi(new Tretja.Docent(), "doc_zR7fX");
        t.prejmi(new Tretja.Asistent(), "as_duSVT");
        t.prejmi(new Tretja.Docent(), "doc_WjGNr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_st9Eh");
        t.prejmi(new Tretja.Asistent(), "as_Xi8C2");
        t.prejmi(new Tretja.Asistent(), "as_uIMdL");
        t.prejmi(new Tretja.Profesor(), "prof_vsDzr");
        t.prejmi(new Tretja.Docent(), "doc_RYPWB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_aU3Fn");
        t.prejmi(new Tretja.Profesor(), "prof_5Ymgq");
        t.prejmi(new Tretja.Profesor(), "prof_rQHJK");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_l5Nhc");
        t.prejmi(new Tretja.Profesor(), "prof_XnOq1");
        t.prejmi(new Tretja.Asistent(), "as_16qCq");
        t.prejmi(new Tretja.Profesor(), "prof_xgkks");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_ujvI7");
        t.prejmi(new Tretja.Docent(), "doc_ly9nf");
        t.prejmi(new Tretja.Profesor(), "prof_CXZle");
        t.prejmi(new Tretja.Profesor(), "prof_yrrzS");
        t.prejmi(new Tretja.Profesor(), "prof_Z3qPj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_p9kfQ");
        t.prejmi(new Tretja.Asistent(), "as_MeZkJ");
    }
}
