
public class Test26 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_Kuka3");
        t.prejmi(new Tretja.Docent(), "doc_4VluI");
        t.prejmi(new Tretja.Profesor(), "prof_NMrSl");
        t.prejmi(new Tretja.Docent(), "doc_aght3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_QaEab");
        t.prejmi(new Tretja.Docent(), "doc_Ozmor");
        t.prejmi(new Tretja.Asistent(), "as_fxPKA");
        t.prejmi(new Tretja.Profesor(), "prof_MpToi");
        t.prejmi(new Tretja.Asistent(), "as_AoiHW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ZDf2f");
        t.prejmi(new Tretja.Docent(), "doc_DjihE");
        t.prejmi(new Tretja.Asistent(), "as_bIJZz");
        t.prejmi(new Tretja.Profesor(), "prof_3qFk9");
        t.prejmi(new Tretja.Docent(), "doc_TZw6E");
        t.prejmi(new Tretja.Asistent(), "as_zF6AO");
        t.prejmi(new Tretja.Docent(), "doc_axrlk");
        t.prejmi(new Tretja.Profesor(), "prof_F9qER");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_0iTCK");
        t.prejmi(new Tretja.Docent(), "doc_vwBU9");
        t.prejmi(new Tretja.Asistent(), "as_WR9J8");
        t.prejmi(new Tretja.Profesor(), "prof_BEGJx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_EDs5l");
        t.prejmi(new Tretja.Docent(), "doc_crrkm");
        t.prejmi(new Tretja.Docent(), "doc_y2R90");
        t.prejmi(new Tretja.Docent(), "doc_ldBHj");
        t.prejmi(new Tretja.Profesor(), "prof_VuTPe");
        t.prejmi(new Tretja.Profesor(), "prof_m0rxW");
        t.prejmi(new Tretja.Asistent(), "as_TwIO4");
        t.prejmi(new Tretja.Asistent(), "as_JFeZ1");
        t.prejmi(new Tretja.Docent(), "doc_uYDPg");
        t.prejmi(new Tretja.Profesor(), "prof_qlV7S");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_PpcVe");
        t.prejmi(new Tretja.Profesor(), "prof_cdhAr");
        t.prejmi(new Tretja.Docent(), "doc_Dcjyq");
        t.prejmi(new Tretja.Docent(), "doc_QYnRX");
        t.prejmi(new Tretja.Docent(), "doc_8kNML");
        t.prejmi(new Tretja.Docent(), "doc_tu52s");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_CzAcF");
        t.prejmi(new Tretja.Asistent(), "as_L6TTX");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_wgRi3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_SbfVr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_S6Aqq");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_NfOEE");
        t.prejmi(new Tretja.Docent(), "doc_me2fh");
        t.prejmi(new Tretja.Profesor(), "prof_mdibZ");
        t.prejmi(new Tretja.Docent(), "doc_6Ufu5");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_kLVLN");
        t.prejmi(new Tretja.Docent(), "doc_RhyXV");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_qWBNC");
        t.prejmi(new Tretja.Docent(), "doc_snrOj");
        t.prejmi(new Tretja.Profesor(), "prof_qmCxM");
        t.prejmi(new Tretja.Asistent(), "as_PrQyu");
        t.prejmi(new Tretja.Profesor(), "prof_7cfic");
        t.prejmi(new Tretja.Asistent(), "as_129FV");
        t.prejmi(new Tretja.Asistent(), "as_vx9xc");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_pKE4L");
        t.prejmi(new Tretja.Profesor(), "prof_1x6tg");
        t.prejmi(new Tretja.Docent(), "doc_koQBe");
        t.prejmi(new Tretja.Asistent(), "as_OE2j4");
        t.prejmi(new Tretja.Profesor(), "prof_BbVg4");
        t.prejmi(new Tretja.Docent(), "doc_pW0CM");
        t.prejmi(new Tretja.Asistent(), "as_jrxTi");
        t.prejmi(new Tretja.Profesor(), "prof_r5v49");
        t.prejmi(new Tretja.Profesor(), "prof_6ffHR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_S32mu");
        t.prejmi(new Tretja.Docent(), "doc_v6wE8");
        t.prejmi(new Tretja.Asistent(), "as_b2o9v");
        t.prejmi(new Tretja.Docent(), "doc_3DLzV");
        t.prejmi(new Tretja.Asistent(), "as_MD5q4");
        t.prejmi(new Tretja.Asistent(), "as_ET312");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wUKhF");
        t.prejmi(new Tretja.Docent(), "doc_8p978");
        t.prejmi(new Tretja.Asistent(), "as_9A5Zu");
        t.prejmi(new Tretja.Profesor(), "prof_eGGBl");
        t.prejmi(new Tretja.Docent(), "doc_T2lFY");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_iWLC6");
        t.prejmi(new Tretja.Docent(), "doc_UAADP");
        t.prejmi(new Tretja.Profesor(), "prof_9Bxia");
        t.prejmi(new Tretja.Docent(), "doc_cG8fH");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_BSP42");
        t.prejmi(new Tretja.Docent(), "doc_0rs09");
        t.prejmi(new Tretja.Profesor(), "prof_5RbpX");
        t.prejmi(new Tretja.Profesor(), "prof_IGpH0");
        t.prejmi(new Tretja.Docent(), "doc_siYct");
        t.prejmi(new Tretja.Docent(), "doc_pM7PD");
        t.prejmi(new Tretja.Docent(), "doc_ZL6Um");
        t.prejmi(new Tretja.Docent(), "doc_cwoXw");
        t.prejmi(new Tretja.Profesor(), "prof_9l1us");
        t.prejmi(new Tretja.Docent(), "doc_r0HgA");
        t.prejmi(new Tretja.Docent(), "doc_z184M");
        t.prejmi(new Tretja.Docent(), "doc_G0yAJ");
        t.prejmi(new Tretja.Asistent(), "as_Z2RXI");
        t.prejmi(new Tretja.Docent(), "doc_b8R5n");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_hJIQd");
        t.prejmi(new Tretja.Profesor(), "prof_hLT5g");
        t.prejmi(new Tretja.Docent(), "doc_DtIGT");
        t.prejmi(new Tretja.Profesor(), "prof_WV3kN");
        t.prejmi(new Tretja.Asistent(), "as_SSEug");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Zuws5");
        t.prejmi(new Tretja.Profesor(), "prof_pZMHe");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_UpOME");
        t.prejmi(new Tretja.Docent(), "doc_7RCGH");
        t.prejmi(new Tretja.Profesor(), "prof_26oqT");
        t.prejmi(new Tretja.Profesor(), "prof_2O5gR");
        t.prejmi(new Tretja.Docent(), "doc_beJDq");
        t.prejmi(new Tretja.Profesor(), "prof_063Fr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_Jqe6H");
        t.prejmi(new Tretja.Asistent(), "as_diw68");
        t.prejmi(new Tretja.Asistent(), "as_Wf68G");
        t.prejmi(new Tretja.Docent(), "doc_8bzOI");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_DAXB9");
        t.prejmi(new Tretja.Docent(), "doc_bf2bj");
        t.prejmi(new Tretja.Profesor(), "prof_fyyLF");
        t.prejmi(new Tretja.Profesor(), "prof_ODIQW");
        t.prejmi(new Tretja.Profesor(), "prof_jTlOA");
        t.prejmi(new Tretja.Profesor(), "prof_01NuR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_iqfwq");
        t.prejmi(new Tretja.Profesor(), "prof_ZtA6C");
        t.prejmi(new Tretja.Docent(), "doc_YIk2y");
        t.prejmi(new Tretja.Docent(), "doc_479U6");
        t.prejmi(new Tretja.Docent(), "doc_j4yEK");
        t.prejmi(new Tretja.Asistent(), "as_ayI0v");
        t.prejmi(new Tretja.Docent(), "doc_1xYai");
        t.prejmi(new Tretja.Docent(), "doc_Qz5o5");
        t.prejmi(new Tretja.Docent(), "doc_F51fk");
        t.prejmi(new Tretja.Profesor(), "prof_7FNyE");
        t.prejmi(new Tretja.Asistent(), "as_sKJmJ");
        t.prejmi(new Tretja.Asistent(), "as_tnfQ3");
        t.prejmi(new Tretja.Asistent(), "as_SoMHl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_L6pbi");
        t.prejmi(new Tretja.Docent(), "doc_nStkq");
        t.prejmi(new Tretja.Asistent(), "as_u660P");
        t.prejmi(new Tretja.Docent(), "doc_XJy51");
        t.prejmi(new Tretja.Asistent(), "as_JzTgQ");
        t.prejmi(new Tretja.Docent(), "doc_JJXKp");
        t.prejmi(new Tretja.Profesor(), "prof_0HFLN");
        t.prejmi(new Tretja.Asistent(), "as_HmzyE");
        t.prejmi(new Tretja.Profesor(), "prof_5RLwm");
        t.prejmi(new Tretja.Docent(), "doc_76dYx");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_W9lRj");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_KQXCh");
        t.prejmi(new Tretja.Asistent(), "as_hzwqs");
        t.prejmi(new Tretja.Docent(), "doc_5UPGc");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Fp5p4");
        t.prejmi(new Tretja.Profesor(), "prof_WAzkb");
        t.prejmi(new Tretja.Docent(), "doc_yiji3");
        t.prejmi(new Tretja.Asistent(), "as_MJva1");
        t.prejmi(new Tretja.Profesor(), "prof_weTTs");
        t.prejmi(new Tretja.Docent(), "doc_G61zK");
        t.prejmi(new Tretja.Docent(), "doc_MHYM8");
        t.prejmi(new Tretja.Docent(), "doc_Ge2gi");
        t.prejmi(new Tretja.Profesor(), "prof_6OvcV");
        t.prejmi(new Tretja.Asistent(), "as_CMjJm");
        t.prejmi(new Tretja.Asistent(), "as_hqj3U");
        t.prejmi(new Tretja.Docent(), "doc_FRD9a");
        t.prejmi(new Tretja.Asistent(), "as_fD495");
        t.prejmi(new Tretja.Docent(), "doc_cIkbu");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_buDRT");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_leyVS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_F82ft");
        t.prejmi(new Tretja.Profesor(), "prof_REkTa");
        t.prejmi(new Tretja.Profesor(), "prof_uSwiI");
        t.prejmi(new Tretja.Asistent(), "as_Ao3Hx");
        t.prejmi(new Tretja.Asistent(), "as_L0cGD");
        t.prejmi(new Tretja.Asistent(), "as_3N3gE");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Qr3TD");
        t.prejmi(new Tretja.Profesor(), "prof_DE6Wg");
        t.prejmi(new Tretja.Profesor(), "prof_X2D97");
        t.prejmi(new Tretja.Docent(), "doc_apalD");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_XhXUl");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_PkHQ1");
        t.prejmi(new Tretja.Profesor(), "prof_COt77");
        t.prejmi(new Tretja.Asistent(), "as_Tdtfk");
        t.prejmi(new Tretja.Docent(), "doc_oS8vq");
        t.prejmi(new Tretja.Docent(), "doc_cv3Rp");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_68CQD");
        t.prejmi(new Tretja.Docent(), "doc_80Qfs");
        t.prejmi(new Tretja.Asistent(), "as_HNj1V");
        t.prejmi(new Tretja.Profesor(), "prof_OBfEx");
        t.prejmi(new Tretja.Asistent(), "as_lAAGP");
        t.prejmi(new Tretja.Docent(), "doc_MUx5T");
        t.prejmi(new Tretja.Docent(), "doc_SKXjr");
        t.prejmi(new Tretja.Profesor(), "prof_PdSBf");
        t.prejmi(new Tretja.Profesor(), "prof_YoTIo");
        t.prejmi(new Tretja.Asistent(), "as_6MAoz");
        t.prejmi(new Tretja.Profesor(), "prof_8QjyE");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ctFeg");
        t.prejmi(new Tretja.Docent(), "doc_9I75l");
        t.prejmi(new Tretja.Profesor(), "prof_KAZSD");
        t.prejmi(new Tretja.Docent(), "doc_HVZ4X");
        t.prejmi(new Tretja.Profesor(), "prof_qLAUA");
        t.prejmi(new Tretja.Profesor(), "prof_d7hXd");
        t.prejmi(new Tretja.Asistent(), "as_dtGTg");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_FGpDu");
        t.prejmi(new Tretja.Profesor(), "prof_flm8L");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_IHV3B");
        t.prejmi(new Tretja.Docent(), "doc_drRCv");
        t.prejmi(new Tretja.Profesor(), "prof_6Bnaw");
        t.prejmi(new Tretja.Asistent(), "as_ekzAf");
        t.prejmi(new Tretja.Profesor(), "prof_cbxXs");
        t.prejmi(new Tretja.Docent(), "doc_HXVQO");
        t.prejmi(new Tretja.Profesor(), "prof_sJmNw");
        t.prejmi(new Tretja.Profesor(), "prof_C9vnG");
        t.prejmi(new Tretja.Asistent(), "as_sZS5t");
        t.prejmi(new Tretja.Docent(), "doc_mD0GR");
        t.prejmi(new Tretja.Profesor(), "prof_zS1wH");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_0e3vI");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_AWzU6");
        t.prejmi(new Tretja.Docent(), "doc_nhlBU");
        t.prejmi(new Tretja.Docent(), "doc_OWa8i");
        t.prejmi(new Tretja.Docent(), "doc_YLo7j");
        t.prejmi(new Tretja.Profesor(), "prof_F77m7");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_bIcPb");
        t.prejmi(new Tretja.Profesor(), "prof_IAOAu");
        t.prejmi(new Tretja.Asistent(), "as_1g8Ds");
        t.prejmi(new Tretja.Docent(), "doc_eob45");
        t.prejmi(new Tretja.Docent(), "doc_p0dva");
        t.prejmi(new Tretja.Profesor(), "prof_C9t28");
        t.prejmi(new Tretja.Docent(), "doc_BFfwu");
        t.prejmi(new Tretja.Profesor(), "prof_0ngmQ");
        t.prejmi(new Tretja.Docent(), "doc_ijGnV");
        t.prejmi(new Tretja.Profesor(), "prof_PAYE6");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_KkZFV");
        t.prejmi(new Tretja.Asistent(), "as_XCpR1");
        t.prejmi(new Tretja.Docent(), "doc_ef3rN");
        t.prejmi(new Tretja.Asistent(), "as_4Pe4w");
        t.prejmi(new Tretja.Docent(), "doc_HOug1");
        t.prejmi(new Tretja.Asistent(), "as_MHKWt");
        t.prejmi(new Tretja.Asistent(), "as_cQG9e");
        t.prejmi(new Tretja.Docent(), "doc_kWSFj");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_CLL1F");
        t.prejmi(new Tretja.Docent(), "doc_UhhHf");
        t.prejmi(new Tretja.Asistent(), "as_KeaRK");
        t.prejmi(new Tretja.Asistent(), "as_Zg6MK");
        t.prejmi(new Tretja.Docent(), "doc_etHDa");
        t.prejmi(new Tretja.Docent(), "doc_AHI54");
        t.prejmi(new Tretja.Profesor(), "prof_oJO2U");
        t.prejmi(new Tretja.Asistent(), "as_W8z0C");
        t.prejmi(new Tretja.Docent(), "doc_tVOIR");
        t.prejmi(new Tretja.Asistent(), "as_5zPmD");
        t.prejmi(new Tretja.Docent(), "doc_p5XeE");
        t.prejmi(new Tretja.Docent(), "doc_maWmI");
        t.prejmi(new Tretja.Docent(), "doc_HBIDF");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_SkOMy");
        t.prejmi(new Tretja.Asistent(), "as_VwiVK");
        t.prejmi(new Tretja.Docent(), "doc_yGM2y");
        t.prejmi(new Tretja.Profesor(), "prof_IoK7f");
        t.prejmi(new Tretja.Docent(), "doc_kxFMz");
        t.prejmi(new Tretja.Asistent(), "as_18UHY");
        t.prejmi(new Tretja.Docent(), "doc_eF9ul");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_xHzd6");
        t.prejmi(new Tretja.Profesor(), "prof_0fEw4");
        t.prejmi(new Tretja.Asistent(), "as_HY7Z6");
        t.prejmi(new Tretja.Docent(), "doc_T3kvw");
        t.prejmi(new Tretja.Docent(), "doc_dTUXm");
        t.prejmi(new Tretja.Profesor(), "prof_Zkf0e");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wWnJt");
        t.prejmi(new Tretja.Profesor(), "prof_Z95cC");
        t.prejmi(new Tretja.Profesor(), "prof_eysG7");
        t.prejmi(new Tretja.Profesor(), "prof_hzeMF");
        t.prejmi(new Tretja.Asistent(), "as_OHjMn");
        t.prejmi(new Tretja.Docent(), "doc_VeS41");
        t.prejmi(new Tretja.Profesor(), "prof_1Ie8q");
        t.prejmi(new Tretja.Profesor(), "prof_IZdzy");
        t.prejmi(new Tretja.Profesor(), "prof_GmGWn");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_zw2hV");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_dnWpr");
        t.prejmi(new Tretja.Asistent(), "as_HiVnw");
        t.prejmi(new Tretja.Profesor(), "prof_tuhfz");
        t.prejmi(new Tretja.Docent(), "doc_AKrXK");
        t.prejmi(new Tretja.Profesor(), "prof_cgb22");
        t.prejmi(new Tretja.Docent(), "doc_XHSNz");
        t.prejmi(new Tretja.Profesor(), "prof_yjgY5");
        t.prejmi(new Tretja.Profesor(), "prof_YKOXX");
        t.prejmi(new Tretja.Profesor(), "prof_w19Wb");
        t.prejmi(new Tretja.Profesor(), "prof_vGMRG");
        t.prejmi(new Tretja.Profesor(), "prof_Hf8MB");
        t.prejmi(new Tretja.Docent(), "doc_5KeKt");
        t.prejmi(new Tretja.Profesor(), "prof_l0QnV");
        t.prejmi(new Tretja.Docent(), "doc_YUDDN");
        t.prejmi(new Tretja.Profesor(), "prof_gbsqp");
        t.prejmi(new Tretja.Asistent(), "as_jibjR");
        t.prejmi(new Tretja.Docent(), "doc_Q6XFb");
        t.prejmi(new Tretja.Docent(), "doc_9Kjtw");
        t.prejmi(new Tretja.Docent(), "doc_8ww8r");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wETTm");
        t.prejmi(new Tretja.Docent(), "doc_hg9hr");
        t.prejmi(new Tretja.Asistent(), "as_2HG0F");
        t.prejmi(new Tretja.Docent(), "doc_Blrg0");
        t.prejmi(new Tretja.Profesor(), "prof_s1GE5");
        t.prejmi(new Tretja.Profesor(), "prof_b4OrR");
        t.prejmi(new Tretja.Docent(), "doc_pBPD1");
        t.prejmi(new Tretja.Docent(), "doc_L9JX0");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_IheIr");
        t.prejmi(new Tretja.Asistent(), "as_q3wPY");
        t.prejmi(new Tretja.Docent(), "doc_O3sBQ");
        t.prejmi(new Tretja.Docent(), "doc_z2jy3");
        t.prejmi(new Tretja.Asistent(), "as_qwGH0");
        t.prejmi(new Tretja.Asistent(), "as_CupPt");
        t.prejmi(new Tretja.Docent(), "doc_cyYfJ");
        t.prejmi(new Tretja.Asistent(), "as_0IhBQ");
        t.prejmi(new Tretja.Profesor(), "prof_cVMCi");
        t.prejmi(new Tretja.Docent(), "doc_EtJqW");
        t.prejmi(new Tretja.Docent(), "doc_Xm2BR");
        t.prejmi(new Tretja.Asistent(), "as_HrdEf");
        t.prejmi(new Tretja.Asistent(), "as_z2geO");
        t.prejmi(new Tretja.Docent(), "doc_AdflA");
        t.prejmi(new Tretja.Asistent(), "as_nLKhK");
        t.prejmi(new Tretja.Asistent(), "as_mhx2v");
        t.prejmi(new Tretja.Asistent(), "as_FW4Vn");
        t.prejmi(new Tretja.Asistent(), "as_PfteE");
        t.prejmi(new Tretja.Asistent(), "as_LvfU9");
        t.prejmi(new Tretja.Docent(), "doc_piJXs");
        t.prejmi(new Tretja.Profesor(), "prof_3sMbW");
        t.prejmi(new Tretja.Asistent(), "as_pQwmD");
        t.prejmi(new Tretja.Docent(), "doc_hQRsW");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_x2cjX");
        t.prejmi(new Tretja.Asistent(), "as_WLnvk");
        t.prejmi(new Tretja.Docent(), "doc_KVZhC");
        t.prejmi(new Tretja.Docent(), "doc_xgNyr");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_63Jrs");
        t.prejmi(new Tretja.Profesor(), "prof_br9bQ");
        t.prejmi(new Tretja.Docent(), "doc_R4NSV");
        t.prejmi(new Tretja.Profesor(), "prof_Vjbpi");
        t.prejmi(new Tretja.Docent(), "doc_B0LwY");
        t.prejmi(new Tretja.Asistent(), "as_NvKDO");
        t.prejmi(new Tretja.Profesor(), "prof_uiIRL");
        t.prejmi(new Tretja.Docent(), "doc_aEzA6");
        t.prejmi(new Tretja.Docent(), "doc_Pwj68");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_baC8b");
        t.prejmi(new Tretja.Docent(), "doc_l112F");
        t.prejmi(new Tretja.Profesor(), "prof_Bzmwj");
        t.prejmi(new Tretja.Docent(), "doc_28nFE");
        t.prejmi(new Tretja.Profesor(), "prof_s3ri9");
        t.prejmi(new Tretja.Docent(), "doc_33myq");
        t.prejmi(new Tretja.Profesor(), "prof_JCqm0");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_8cHrC");
        t.prejmi(new Tretja.Docent(), "doc_FX7vW");
        t.prejmi(new Tretja.Asistent(), "as_a5t2b");
        t.prejmi(new Tretja.Asistent(), "as_9N8FR");
        t.prejmi(new Tretja.Profesor(), "prof_m9Jw3");
        t.prejmi(new Tretja.Docent(), "doc_zpAGX");
        t.prejmi(new Tretja.Profesor(), "prof_ydXKm");
        t.prejmi(new Tretja.Docent(), "doc_RKPhl");
        t.prejmi(new Tretja.Docent(), "doc_fLei4");
        t.prejmi(new Tretja.Asistent(), "as_aDfn9");
        t.prejmi(new Tretja.Profesor(), "prof_GeJ6z");
        t.prejmi(new Tretja.Asistent(), "as_1iO41");
        t.prejmi(new Tretja.Asistent(), "as_7OfL4");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_3HUwh");
        t.prejmi(new Tretja.Profesor(), "prof_MzAgJ");
        t.prejmi(new Tretja.Docent(), "doc_JcWmi");
        t.prejmi(new Tretja.Docent(), "doc_92Tn1");
        t.prejmi(new Tretja.Profesor(), "prof_3DRwB");
        t.prejmi(new Tretja.Docent(), "doc_HQzv6");
        t.prejmi(new Tretja.Profesor(), "prof_SYvi6");
        t.prejmi(new Tretja.Docent(), "doc_DqZvF");
        t.prejmi(new Tretja.Docent(), "doc_j5Ok2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_BmwWX");
        t.prejmi(new Tretja.Asistent(), "as_316Hn");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_nrpgm");
        t.prejmi(new Tretja.Asistent(), "as_pWGzQ");
        t.prejmi(new Tretja.Docent(), "doc_LILDe");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_TPRdH");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_WnTlp");
        t.prejmi(new Tretja.Asistent(), "as_aW1Iy");
        t.prejmi(new Tretja.Profesor(), "prof_a2lpQ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_nteRV");
        t.prejmi(new Tretja.Profesor(), "prof_Rgtoz");
        t.prejmi(new Tretja.Docent(), "doc_GYI4j");
        t.prejmi(new Tretja.Docent(), "doc_IClpO");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_qcq1I");
        t.prejmi(new Tretja.Profesor(), "prof_zKM9l");
        t.prejmi(new Tretja.Asistent(), "as_ERPDu");
        t.prejmi(new Tretja.Profesor(), "prof_Lpk9X");
        t.prejmi(new Tretja.Profesor(), "prof_KLRsu");
        t.prejmi(new Tretja.Asistent(), "as_CjRgp");
        t.prejmi(new Tretja.Asistent(), "as_UNe7M");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_QcEZu");
        t.prejmi(new Tretja.Profesor(), "prof_YuaWZ");
        t.prejmi(new Tretja.Docent(), "doc_ROae9");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_Z0bnL");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_eMF4M");
        t.prejmi(new Tretja.Asistent(), "as_6X791");
        t.prejmi(new Tretja.Profesor(), "prof_xAS7o");
        t.prejmi(new Tretja.Profesor(), "prof_6FtlD");
        t.prejmi(new Tretja.Docent(), "doc_biYCr");
        t.prejmi(new Tretja.Docent(), "doc_68Mnq");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_pqv1t");
        t.prejmi(new Tretja.Docent(), "doc_bVajE");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_uGxiy");
        t.prejmi(new Tretja.Profesor(), "prof_2Bbgm");
        t.prejmi(new Tretja.Asistent(), "as_T6FrG");
        t.prejmi(new Tretja.Profesor(), "prof_nojNW");
        t.prejmi(new Tretja.Docent(), "doc_TCulM");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ZYahD");
        t.prejmi(new Tretja.Profesor(), "prof_feNPt");
        t.prejmi(new Tretja.Docent(), "doc_ZHgap");
        t.prejmi(new Tretja.Asistent(), "as_1F44I");
        t.prejmi(new Tretja.Asistent(), "as_9yBg1");
        t.prejmi(new Tretja.Profesor(), "prof_8e8HC");
        t.prejmi(new Tretja.Docent(), "doc_INvi0");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_Pc0j4");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_6d7XW");
        t.prejmi(new Tretja.Profesor(), "prof_6dhaN");
        t.prejmi(new Tretja.Docent(), "doc_mE4K5");
        t.prejmi(new Tretja.Asistent(), "as_eBnrw");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_mnzJs");
        t.prejmi(new Tretja.Asistent(), "as_SHj0f");
        t.prejmi(new Tretja.Asistent(), "as_ziiJq");
        t.prejmi(new Tretja.Docent(), "doc_BSeem");
        t.prejmi(new Tretja.Profesor(), "prof_UiEVT");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_6dnmR");
        t.prejmi(new Tretja.Asistent(), "as_43DSJ");
        t.prejmi(new Tretja.Asistent(), "as_rFUwn");
        t.prejmi(new Tretja.Docent(), "doc_S3ma5");
    }
}
