
public class Test02 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_udSoZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Iub8g");
        t.prejmi(new Tretja.Docent(), "doc_rksmK");
        t.prejmi(new Tretja.Asistent(), "as_caezN");
        t.prejmi(new Tretja.Profesor(), "prof_KLlxy");
        t.prejmi(new Tretja.Docent(), "doc_OG8u7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Zb7Tg");
        t.prejmi(new Tretja.Docent(), "doc_gAaKE");
        t.prejmi(new Tretja.Asistent(), "as_MoPvt");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_GN9Mf");
        t.prejmi(new Tretja.Profesor(), "prof_Nc91H");
        t.prejmi(new Tretja.Asistent(), "as_gSvJF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_zyOkZ");
        t.prejmi(new Tretja.Profesor(), "prof_E6xSP");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_iwMbG");
        t.prejmi(new Tretja.Profesor(), "prof_xrvTe");
        t.prejmi(new Tretja.Profesor(), "prof_JDGsc");
        t.prejmi(new Tretja.Profesor(), "prof_eD64a");
        t.prejmi(new Tretja.Asistent(), "as_IxEfc");
        t.prejmi(new Tretja.Asistent(), "as_JvL2E");
        t.prejmi(new Tretja.Profesor(), "prof_X2B3X");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_9krl1");
        t.prejmi(new Tretja.Docent(), "doc_4ndXe");
        t.prejmi(new Tretja.Asistent(), "as_AyUG6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_IwGs5");
        t.prejmi(new Tretja.Asistent(), "as_Lu4Ok");
        t.prejmi(new Tretja.Asistent(), "as_Oca36");
        t.prejmi(new Tretja.Asistent(), "as_miIJc");
        t.prejmi(new Tretja.Asistent(), "as_TuSH0");
        t.prejmi(new Tretja.Profesor(), "prof_ZtsSe");
        t.prejmi(new Tretja.Profesor(), "prof_QMojK");
        t.prejmi(new Tretja.Asistent(), "as_v32K3");
        t.prejmi(new Tretja.Profesor(), "prof_EybMa");
        t.prejmi(new Tretja.Docent(), "doc_3s0Xi");
        t.prejmi(new Tretja.Profesor(), "prof_CKMtc");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_105I9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ntLsn");
        t.prejmi(new Tretja.Asistent(), "as_WVfz3");
        t.prejmi(new Tretja.Docent(), "doc_dSeHN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_6XD5r");
        t.prejmi(new Tretja.Asistent(), "as_DPsNI");
        t.prejmi(new Tretja.Profesor(), "prof_fejBz");
        t.prejmi(new Tretja.Asistent(), "as_LlhNp");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_FAA3x");
        t.prejmi(new Tretja.Docent(), "doc_9wpy0");
        t.prejmi(new Tretja.Profesor(), "prof_sOFOA");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ITXlQ");
        t.prejmi(new Tretja.Profesor(), "prof_oI1pE");
        t.prejmi(new Tretja.Profesor(), "prof_rkUcD");
        t.prejmi(new Tretja.Profesor(), "prof_qWeBM");
        t.prejmi(new Tretja.Profesor(), "prof_szCge");
        t.prejmi(new Tretja.Profesor(), "prof_I6jHB");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_VYKLg");
        t.prejmi(new Tretja.Asistent(), "as_wEQGH");
        t.prejmi(new Tretja.Docent(), "doc_Hbkqg");
        t.prejmi(new Tretja.Docent(), "doc_HAioh");
        t.prejmi(new Tretja.Docent(), "doc_izDz0");
        t.prejmi(new Tretja.Profesor(), "prof_p3nUv");
        t.prejmi(new Tretja.Profesor(), "prof_5zWEK");
        t.prejmi(new Tretja.Asistent(), "as_EwYSu");
        t.prejmi(new Tretja.Asistent(), "as_ARYMp");
        t.prejmi(new Tretja.Docent(), "doc_WEF1g");
        t.prejmi(new Tretja.Profesor(), "prof_I7juR");
        t.prejmi(new Tretja.Profesor(), "prof_BqgeZ");
        t.prejmi(new Tretja.Profesor(), "prof_mJ9jk");
        t.prejmi(new Tretja.Docent(), "doc_qOlEo");
        t.prejmi(new Tretja.Profesor(), "prof_6xMsU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_LwzUh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JMk9G");
        t.prejmi(new Tretja.Asistent(), "as_7ee2d");
        t.prejmi(new Tretja.Docent(), "doc_EGOTE");
        t.prejmi(new Tretja.Docent(), "doc_DaR9E");
        t.prejmi(new Tretja.Asistent(), "as_H7bDo");
        t.prejmi(new Tretja.Profesor(), "prof_MTj0K");
        t.prejmi(new Tretja.Asistent(), "as_Y8sS0");
        t.prejmi(new Tretja.Docent(), "doc_PmgdI");
        t.prejmi(new Tretja.Asistent(), "as_rbI14");
        t.prejmi(new Tretja.Profesor(), "prof_Eci05");
        t.prejmi(new Tretja.Profesor(), "prof_B5epd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_0XMFT");
        t.prejmi(new Tretja.Docent(), "doc_Tn0jS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_gn0NJ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ei6To");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_oSgTi");
        t.prejmi(new Tretja.Asistent(), "as_3skv1");
        t.prejmi(new Tretja.Docent(), "doc_I7yxk");
        t.prejmi(new Tretja.Asistent(), "as_kUOoe");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_AmY2E");
        t.prejmi(new Tretja.Profesor(), "prof_ZUgTn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_KIfvy");
        t.prejmi(new Tretja.Profesor(), "prof_ydeWY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_TluZS");
        t.prejmi(new Tretja.Docent(), "doc_Ahsxt");
        t.prejmi(new Tretja.Profesor(), "prof_CbfwJ");
        t.prejmi(new Tretja.Asistent(), "as_8HHyJ");
        t.prejmi(new Tretja.Profesor(), "prof_0MLd9");
        t.prejmi(new Tretja.Profesor(), "prof_WD3UR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_a99es");
        t.prejmi(new Tretja.Profesor(), "prof_MLs7K");
        t.prejmi(new Tretja.Docent(), "doc_UapSZ");
        t.prejmi(new Tretja.Docent(), "doc_fzKFO");
        t.prejmi(new Tretja.Profesor(), "prof_DE6D6");
        t.prejmi(new Tretja.Profesor(), "prof_4oP2a");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_cWNQu");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_3mf0B");
        t.prejmi(new Tretja.Profesor(), "prof_vegdM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_mJmUH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_oD1y9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_WLpab");
        t.prejmi(new Tretja.Asistent(), "as_y9q9v");
        t.prejmi(new Tretja.Asistent(), "as_7Tc8H");
        t.prejmi(new Tretja.Docent(), "doc_AzSi3");
        t.prejmi(new Tretja.Profesor(), "prof_OA0QA");
        t.prejmi(new Tretja.Profesor(), "prof_5rb8y");
        t.prejmi(new Tretja.Docent(), "doc_M1Dmt");
        t.prejmi(new Tretja.Profesor(), "prof_EuiYM");
        t.prejmi(new Tretja.Profesor(), "prof_djYHA");
        t.prejmi(new Tretja.Docent(), "doc_Ai58U");
        t.prejmi(new Tretja.Profesor(), "prof_llTQL");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_FRbDZ");
        t.prejmi(new Tretja.Profesor(), "prof_ag5cr");
        t.prejmi(new Tretja.Asistent(), "as_mA9jR");
        t.prejmi(new Tretja.Asistent(), "as_IckEt");
        t.prejmi(new Tretja.Asistent(), "as_rqY2Z");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_2vRNk");
        t.prejmi(new Tretja.Docent(), "doc_rl5ob");
        t.prejmi(new Tretja.Asistent(), "as_N1gsr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_ls2GK");
        t.prejmi(new Tretja.Profesor(), "prof_QpNRv");
        t.prejmi(new Tretja.Docent(), "doc_KAwIj");
        t.prejmi(new Tretja.Profesor(), "prof_DqSdD");
        t.prejmi(new Tretja.Docent(), "doc_kY5c4");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_3HpjM");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_CK27q");
        t.prejmi(new Tretja.Docent(), "doc_x58xh");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_9nMyR");
        t.prejmi(new Tretja.Docent(), "doc_fHBYX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_3rAwo");
        t.prejmi(new Tretja.Docent(), "doc_hrAAF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_uVFkD");
        t.prejmi(new Tretja.Docent(), "doc_AESj0");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_mqTmv");
        t.prejmi(new Tretja.Docent(), "doc_7Lmep");
        t.prejmi(new Tretja.Docent(), "doc_LoEfd");
        t.prejmi(new Tretja.Asistent(), "as_f7mZE");
        t.prejmi(new Tretja.Docent(), "doc_ZzsNi");
        t.prejmi(new Tretja.Profesor(), "prof_nkUz5");
        t.prejmi(new Tretja.Asistent(), "as_P4e8T");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_oXUjM");
        t.prejmi(new Tretja.Docent(), "doc_gAHtA");
        t.prejmi(new Tretja.Profesor(), "prof_TAeUc");
        t.prejmi(new Tretja.Docent(), "doc_O5Tir");
        t.prejmi(new Tretja.Asistent(), "as_jIUVT");
        t.prejmi(new Tretja.Asistent(), "as_qUA0W");
        t.prejmi(new Tretja.Profesor(), "prof_28vXe");
        t.prejmi(new Tretja.Profesor(), "prof_rmSfi");
        t.prejmi(new Tretja.Profesor(), "prof_adwtB");
        t.prejmi(new Tretja.Profesor(), "prof_bBrJ7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_sBR4y");
        t.prejmi(new Tretja.Asistent(), "as_j5UNM");
        t.prejmi(new Tretja.Asistent(), "as_ZSjBP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_IWOPQ");
        t.prejmi(new Tretja.Docent(), "doc_ddrY2");
        t.prejmi(new Tretja.Profesor(), "prof_Q9GN6");
        t.prejmi(new Tretja.Asistent(), "as_vJwQ1");
        t.prejmi(new Tretja.Asistent(), "as_mqgDz");
        t.prejmi(new Tretja.Docent(), "doc_DpmEj");
        t.prejmi(new Tretja.Docent(), "doc_wlwmE");
        t.prejmi(new Tretja.Profesor(), "prof_YvdHW");
        t.prejmi(new Tretja.Asistent(), "as_9bPvI");
        t.prejmi(new Tretja.Profesor(), "prof_lJOaQ");
        t.prejmi(new Tretja.Docent(), "doc_XmZYs");
        t.prejmi(new Tretja.Profesor(), "prof_mg9KS");
        t.prejmi(new Tretja.Profesor(), "prof_NB7oN");
        t.prejmi(new Tretja.Profesor(), "prof_lEh6p");
        t.prejmi(new Tretja.Docent(), "doc_tyMNz");
        t.prejmi(new Tretja.Asistent(), "as_xP0l2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_jb0KP");
        t.prejmi(new Tretja.Asistent(), "as_gh6VN");
        t.prejmi(new Tretja.Profesor(), "prof_7HdIc");
        t.prejmi(new Tretja.Profesor(), "prof_u0Bx4");
        t.prejmi(new Tretja.Profesor(), "prof_DUbts");
        t.prejmi(new Tretja.Profesor(), "prof_utccR");
        t.prejmi(new Tretja.Docent(), "doc_2NGI9");
        t.prejmi(new Tretja.Docent(), "doc_v9xqG");
        t.prejmi(new Tretja.Docent(), "doc_ChrOC");
        t.prejmi(new Tretja.Profesor(), "prof_eMXji");
        t.prejmi(new Tretja.Profesor(), "prof_DE0AZ");
        t.prejmi(new Tretja.Profesor(), "prof_VhOca");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_BfcOf");
        t.prejmi(new Tretja.Asistent(), "as_ufTKp");
        t.prejmi(new Tretja.Profesor(), "prof_VTg25");
        t.prejmi(new Tretja.Profesor(), "prof_3eGhf");
        t.prejmi(new Tretja.Profesor(), "prof_dAdlq");
        t.prejmi(new Tretja.Docent(), "doc_F43Wy");
        t.prejmi(new Tretja.Profesor(), "prof_KbfCM");
        t.prejmi(new Tretja.Docent(), "doc_XVska");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_U1Yok");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_hLjzp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_jP2b6");
        t.prejmi(new Tretja.Profesor(), "prof_Ncvuu");
        t.prejmi(new Tretja.Asistent(), "as_0uYJb");
        t.prejmi(new Tretja.Asistent(), "as_indp9");
        t.prejmi(new Tretja.Profesor(), "prof_wvv20");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_OmKaE");
        t.prejmi(new Tretja.Profesor(), "prof_S5WHn");
        t.prejmi(new Tretja.Asistent(), "as_LJXv2");
        t.prejmi(new Tretja.Profesor(), "prof_wHSF8");
        t.prejmi(new Tretja.Asistent(), "as_ugeQN");
        t.prejmi(new Tretja.Profesor(), "prof_Ccd5i");
        t.prejmi(new Tretja.Asistent(), "as_zCX9y");
        t.prejmi(new Tretja.Profesor(), "prof_Fd4fu");
        t.prejmi(new Tretja.Asistent(), "as_yVPok");
        t.prejmi(new Tretja.Asistent(), "as_hIS6a");
        t.prejmi(new Tretja.Profesor(), "prof_07kPb");
        t.prejmi(new Tretja.Profesor(), "prof_rHciQ");
        t.prejmi(new Tretja.Asistent(), "as_vImsQ");
        t.prejmi(new Tretja.Docent(), "doc_qEq1q");
        t.prejmi(new Tretja.Profesor(), "prof_d9aFm");
        t.prejmi(new Tretja.Asistent(), "as_uFchd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_YGv3Y");
        t.prejmi(new Tretja.Docent(), "doc_3g9Hf");
        t.prejmi(new Tretja.Profesor(), "prof_6jWj2");
        t.prejmi(new Tretja.Docent(), "doc_vz2Gy");
        t.prejmi(new Tretja.Docent(), "doc_5xKhx");
        t.prejmi(new Tretja.Asistent(), "as_Tl62e");
        t.prejmi(new Tretja.Docent(), "doc_hM0VA");
        t.prejmi(new Tretja.Docent(), "doc_uWi0y");
        t.prejmi(new Tretja.Docent(), "doc_89VfB");
        t.prejmi(new Tretja.Asistent(), "as_WVRVY");
        t.prejmi(new Tretja.Profesor(), "prof_oyC6J");
        t.prejmi(new Tretja.Profesor(), "prof_ojJpb");
        t.prejmi(new Tretja.Profesor(), "prof_MR4Sp");
        t.prejmi(new Tretja.Profesor(), "prof_tRHjf");
        t.prejmi(new Tretja.Docent(), "doc_dDNmY");
        t.prejmi(new Tretja.Profesor(), "prof_gxFkw");
        t.prejmi(new Tretja.Docent(), "doc_eSY3o");
        t.prejmi(new Tretja.Asistent(), "as_rIlvB");
        t.prejmi(new Tretja.Asistent(), "as_XMkJl");
        t.prejmi(new Tretja.Docent(), "doc_ITsa5");
        t.prejmi(new Tretja.Asistent(), "as_PomMB");
        t.prejmi(new Tretja.Profesor(), "prof_80TKP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_FSrcB");
        t.prejmi(new Tretja.Docent(), "doc_3g51R");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_SVjFj");
        t.prejmi(new Tretja.Profesor(), "prof_YTnuS");
        t.prejmi(new Tretja.Profesor(), "prof_8rnY3");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_h2O0H");
        t.prejmi(new Tretja.Docent(), "doc_ReXHR");
        t.prejmi(new Tretja.Profesor(), "prof_xKgPg");
        t.prejmi(new Tretja.Asistent(), "as_K1q1h");
        t.prejmi(new Tretja.Docent(), "doc_Mx1wu");
        t.prejmi(new Tretja.Docent(), "doc_yNvgF");
        t.prejmi(new Tretja.Docent(), "doc_7eW2t");
        t.prejmi(new Tretja.Asistent(), "as_fSWAf");
        t.prejmi(new Tretja.Profesor(), "prof_k67Bc");
        t.prejmi(new Tretja.Docent(), "doc_IYNsg");
        t.prejmi(new Tretja.Asistent(), "as_RC7qJ");
        t.prejmi(new Tretja.Asistent(), "as_U7P3B");
        t.prejmi(new Tretja.Profesor(), "prof_NiXJa");
        t.prejmi(new Tretja.Profesor(), "prof_9GotX");
        t.prejmi(new Tretja.Docent(), "doc_UtXIi");
        t.prejmi(new Tretja.Profesor(), "prof_huIkT");
        t.prejmi(new Tretja.Profesor(), "prof_C2rjg");
        t.prejmi(new Tretja.Profesor(), "prof_jWJEj");
        t.prejmi(new Tretja.Docent(), "doc_QVEiX");
        t.prejmi(new Tretja.Asistent(), "as_9kWUS");
        t.prejmi(new Tretja.Docent(), "doc_EBmfj");
        t.prejmi(new Tretja.Profesor(), "prof_2LA9L");
        t.prejmi(new Tretja.Docent(), "doc_mBZsa");
        t.prejmi(new Tretja.Profesor(), "prof_VeIZy");
        t.prejmi(new Tretja.Docent(), "doc_xXwWw");
        t.prejmi(new Tretja.Profesor(), "prof_0NWqV");
        t.prejmi(new Tretja.Asistent(), "as_aFwwN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_C10Ck");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_ney51");
        t.prejmi(new Tretja.Docent(), "doc_9VwFI");
        t.prejmi(new Tretja.Profesor(), "prof_zrICp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_IER3N");
        t.prejmi(new Tretja.Asistent(), "as_OKYvq");
        t.prejmi(new Tretja.Docent(), "doc_Otrm4");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_m7kXa");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_kruxb");
        t.prejmi(new Tretja.Docent(), "doc_UsbqP");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_q465R");
        t.prejmi(new Tretja.Docent(), "doc_w0MB2");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Ep2Hr");
        t.prejmi(new Tretja.Profesor(), "prof_1Kolu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_rRPeo");
        t.prejmi(new Tretja.Asistent(), "as_42FXi");
        t.prejmi(new Tretja.Asistent(), "as_ADlY8");
        t.prejmi(new Tretja.Asistent(), "as_6DeeT");
        t.prejmi(new Tretja.Docent(), "doc_fcTpn");
        t.prejmi(new Tretja.Profesor(), "prof_ComvZ");
        t.prejmi(new Tretja.Profesor(), "prof_Fs0p9");
        t.prejmi(new Tretja.Docent(), "doc_hXlom");
        t.prejmi(new Tretja.Asistent(), "as_z3uJR");
        t.prejmi(new Tretja.Profesor(), "prof_imwBW");
        t.prejmi(new Tretja.Docent(), "doc_oRuf5");
        t.prejmi(new Tretja.Profesor(), "prof_I548t");
        t.prejmi(new Tretja.Asistent(), "as_qWiJx");
        t.prejmi(new Tretja.Asistent(), "as_I338o");
        t.prejmi(new Tretja.Profesor(), "prof_6Ed48");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_CHfcR");
        t.prejmi(new Tretja.Docent(), "doc_u4r8P");
        t.prejmi(new Tretja.Profesor(), "prof_ELKeJ");
        t.prejmi(new Tretja.Docent(), "doc_lkS1C");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_nSaxJ");
        t.prejmi(new Tretja.Asistent(), "as_HgZxQ");
        t.prejmi(new Tretja.Docent(), "doc_nu8u2");
        t.prejmi(new Tretja.Docent(), "doc_eRawh");
        t.prejmi(new Tretja.Asistent(), "as_9Nxui");
        t.prejmi(new Tretja.Docent(), "doc_oitv3");
        t.prejmi(new Tretja.Asistent(), "as_rsTYG");
        t.prejmi(new Tretja.Asistent(), "as_OpLsg");
        t.prejmi(new Tretja.Profesor(), "prof_9rqAi");
        t.prejmi(new Tretja.Docent(), "doc_S6K5O");
        t.prejmi(new Tretja.Profesor(), "prof_JnPMb");
        t.prejmi(new Tretja.Asistent(), "as_QOet0");
        t.prejmi(new Tretja.Asistent(), "as_EMQzO");
        t.prejmi(new Tretja.Docent(), "doc_7fCV0");
        t.prejmi(new Tretja.Docent(), "doc_6Avoo");
        t.prejmi(new Tretja.Asistent(), "as_eieq3");
        t.prejmi(new Tretja.Asistent(), "as_Tpd26");
        t.prejmi(new Tretja.Profesor(), "prof_AT96k");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Cd1EW");
        t.prejmi(new Tretja.Profesor(), "prof_fyJ97");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_4pZEC");
        t.prejmi(new Tretja.Profesor(), "prof_4ODNc");
        t.prejmi(new Tretja.Asistent(), "as_AL3Ge");
        t.prejmi(new Tretja.Asistent(), "as_duLlz");
        t.prejmi(new Tretja.Profesor(), "prof_8T5HJ");
        t.prejmi(new Tretja.Asistent(), "as_kqbKc");
        t.prejmi(new Tretja.Asistent(), "as_EzjFW");
        t.prejmi(new Tretja.Asistent(), "as_3Z60C");
        t.prejmi(new Tretja.Docent(), "doc_9VZEe");
        t.prejmi(new Tretja.Docent(), "doc_WbWGD");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
    }
}
