
public class Test39 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ggeMw");
        t.prejmi(new Tretja.Profesor(), "prof_71mYl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_359x2");
        t.prejmi(new Tretja.Docent(), "doc_Ew8iL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Tky5V");
        t.prejmi(new Tretja.Asistent(), "as_5XHMf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_vd5IS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_B88Kj");
        t.prejmi(new Tretja.Profesor(), "prof_TKt4C");
        t.prejmi(new Tretja.Profesor(), "prof_f0s05");
        t.prejmi(new Tretja.Profesor(), "prof_R5zDw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_bSBYn");
        t.prejmi(new Tretja.Profesor(), "prof_r5ffk");
        t.prejmi(new Tretja.Profesor(), "prof_0RfBo");
        t.prejmi(new Tretja.Asistent(), "as_GzqnC");
        t.prejmi(new Tretja.Asistent(), "as_UnnUb");
        t.prejmi(new Tretja.Asistent(), "as_VvCjf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rX4vM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_rt6yx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2j6zE");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TLDk2");
        t.prejmi(new Tretja.Profesor(), "prof_q60Fq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VYOGG");
        t.prejmi(new Tretja.Docent(), "doc_KtqfT");
        t.prejmi(new Tretja.Asistent(), "as_FSsyA");
        t.prejmi(new Tretja.Docent(), "doc_aAEl1");
        t.prejmi(new Tretja.Docent(), "doc_ORvDL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wVwNK");
        t.prejmi(new Tretja.Profesor(), "prof_EBHSD");
        t.prejmi(new Tretja.Docent(), "doc_BeRWB");
        t.prejmi(new Tretja.Profesor(), "prof_mmRO4");
        t.prejmi(new Tretja.Asistent(), "as_z6p82");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_cvpbB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JpQs8");
        t.prejmi(new Tretja.Profesor(), "prof_9jRTr");
        t.prejmi(new Tretja.Asistent(), "as_CRuGh");
        t.prejmi(new Tretja.Asistent(), "as_CRGju");
        t.prejmi(new Tretja.Asistent(), "as_GngVs");
        t.prejmi(new Tretja.Docent(), "doc_hHMvB");
        t.prejmi(new Tretja.Profesor(), "prof_mcZ3f");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_BNvDI");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_qdkPT");
        t.prejmi(new Tretja.Profesor(), "prof_xKo1M");
        t.prejmi(new Tretja.Profesor(), "prof_QUEZx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_jBU4d");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_J4RxO");
        t.prejmi(new Tretja.Asistent(), "as_C1Em5");
        t.prejmi(new Tretja.Asistent(), "as_bJwAl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hpfOq");
        t.prejmi(new Tretja.Docent(), "doc_NHjhl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_HO4L8");
        t.prejmi(new Tretja.Profesor(), "prof_Qi0m8");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4lQRS");
        t.prejmi(new Tretja.Asistent(), "as_Tyqyc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZjwyY");
        t.prejmi(new Tretja.Docent(), "doc_mVvnM");
        t.prejmi(new Tretja.Docent(), "doc_BIjdx");
        t.prejmi(new Tretja.Profesor(), "prof_c26Yw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_NEGi3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MqweP");
        t.prejmi(new Tretja.Asistent(), "as_Rssai");
        t.prejmi(new Tretja.Docent(), "doc_uwJU7");
        t.prejmi(new Tretja.Profesor(), "prof_tdbRx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VacGF");
        t.prejmi(new Tretja.Asistent(), "as_PPrYc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_qxJ7a");
        t.prejmi(new Tretja.Docent(), "doc_s5BJl");
        t.prejmi(new Tretja.Profesor(), "prof_XtSqT");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_l0UsT");
        t.prejmi(new Tretja.Docent(), "doc_ZW6wB");
        t.prejmi(new Tretja.Docent(), "doc_GYLEh");
        t.prejmi(new Tretja.Profesor(), "prof_WDTDS");
        t.prejmi(new Tretja.Asistent(), "as_Nirwq");
        t.prejmi(new Tretja.Asistent(), "as_ZzFG7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MScKL");
        t.prejmi(new Tretja.Docent(), "doc_Iwu9O");
        t.prejmi(new Tretja.Asistent(), "as_O3wDW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_y5NST");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ECyUS");
        t.prejmi(new Tretja.Docent(), "doc_jsYUZ");
        t.prejmi(new Tretja.Asistent(), "as_spCsr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_OX4o4");
        t.prejmi(new Tretja.Asistent(), "as_ONlan");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_lUZFm");
        t.prejmi(new Tretja.Profesor(), "prof_4YGWc");
        t.prejmi(new Tretja.Profesor(), "prof_DTHr6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Te8mB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fb8of");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_1vQcX");
        t.prejmi(new Tretja.Docent(), "doc_KhB7j");
        t.prejmi(new Tretja.Docent(), "doc_6lkDm");
        t.prejmi(new Tretja.Asistent(), "as_fLSr7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_SaHFD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_dwF0K");
        t.prejmi(new Tretja.Docent(), "doc_N06MA");
        t.prejmi(new Tretja.Profesor(), "prof_L9kNo");
        t.prejmi(new Tretja.Asistent(), "as_tmdmP");
        t.prejmi(new Tretja.Docent(), "doc_aR3BP");
        t.prejmi(new Tretja.Docent(), "doc_giebi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_M6Oak");
        t.prejmi(new Tretja.Docent(), "doc_E4DLe");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_GnlKm");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Hdu2c");
        t.prejmi(new Tretja.Docent(), "doc_f4vqs");
        t.prejmi(new Tretja.Profesor(), "prof_bbgV8");
        t.prejmi(new Tretja.Docent(), "doc_IWuvn");
        t.prejmi(new Tretja.Docent(), "doc_TEmOo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_WtB29");
        t.prejmi(new Tretja.Profesor(), "prof_JrLjz");
        t.prejmi(new Tretja.Asistent(), "as_h2Zbe");
        t.prejmi(new Tretja.Profesor(), "prof_NQfjx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RCtOs");
        t.prejmi(new Tretja.Asistent(), "as_mt1RA");
        t.prejmi(new Tretja.Docent(), "doc_uLw6w");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Ly5mv");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4mk14");
        t.prejmi(new Tretja.Docent(), "doc_nhjHf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_o9eGZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3medN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lEQji");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_s6vVB");
        t.prejmi(new Tretja.Asistent(), "as_zK8GX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_eMK8r");
        t.prejmi(new Tretja.Profesor(), "prof_PFuRe");
        t.prejmi(new Tretja.Docent(), "doc_erowN");
        t.prejmi(new Tretja.Docent(), "doc_12FAj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_vh3Ci");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_f8TtV");
        t.prejmi(new Tretja.Asistent(), "as_qcIqj");
        t.prejmi(new Tretja.Asistent(), "as_CKCOY");
        t.prejmi(new Tretja.Docent(), "doc_mRb6B");
        t.prejmi(new Tretja.Profesor(), "prof_8I3SZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JZBzA");
        t.prejmi(new Tretja.Asistent(), "as_tGXOo");
        t.prejmi(new Tretja.Docent(), "doc_FNLWM");
        t.prejmi(new Tretja.Profesor(), "prof_s3p1F");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_BrNat");
        t.prejmi(new Tretja.Docent(), "doc_wQMNQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pl37f");
        t.prejmi(new Tretja.Profesor(), "prof_dtDkx");
        t.prejmi(new Tretja.Asistent(), "as_OIJCb");
        t.prejmi(new Tretja.Asistent(), "as_SaLXo");
        t.prejmi(new Tretja.Profesor(), "prof_FAuyE");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_tpceq");
        t.prejmi(new Tretja.Asistent(), "as_P1Xl2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Ie8Zc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_iL0hP");
        t.prejmi(new Tretja.Profesor(), "prof_39c3U");
        t.prejmi(new Tretja.Docent(), "doc_vDpAS");
        t.prejmi(new Tretja.Profesor(), "prof_AlZfT");
        t.prejmi(new Tretja.Profesor(), "prof_burL2");
        t.prejmi(new Tretja.Docent(), "doc_gn0QO");
        t.prejmi(new Tretja.Docent(), "doc_koxT4");
        t.prejmi(new Tretja.Asistent(), "as_DYsYE");
        t.prejmi(new Tretja.Asistent(), "as_pDCCt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_fw2C6");
        t.prejmi(new Tretja.Profesor(), "prof_o3Aj2");
        t.prejmi(new Tretja.Profesor(), "prof_cx23E");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_20TDp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_jZDcA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_oaeL2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_G5SQI");
        t.prejmi(new Tretja.Docent(), "doc_FsQyq");
        t.prejmi(new Tretja.Asistent(), "as_QO1Zc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_DHEnm");
        t.prejmi(new Tretja.Docent(), "doc_dQCux");
        t.prejmi(new Tretja.Docent(), "doc_r1hoA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_g0HeS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_zDvdR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_cVRul");
        t.prejmi(new Tretja.Docent(), "doc_kvjss");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_FXBRA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uHUT0");
        t.prejmi(new Tretja.Docent(), "doc_tU29G");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_U8cPl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_GmUbi");
        t.prejmi(new Tretja.Docent(), "doc_TH1hf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wqglx");
        t.prejmi(new Tretja.Profesor(), "prof_fTgqr");
        t.prejmi(new Tretja.Asistent(), "as_AaBXT");
        t.prejmi(new Tretja.Docent(), "doc_qyP11");
        t.prejmi(new Tretja.Docent(), "doc_DTJye");
        t.prejmi(new Tretja.Asistent(), "as_fXZWu");
        t.prejmi(new Tretja.Profesor(), "prof_Tsbdn");
        t.prejmi(new Tretja.Profesor(), "prof_A2yKa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kEkaz");
        t.prejmi(new Tretja.Docent(), "doc_LJqMu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_eq6c2");
        t.prejmi(new Tretja.Docent(), "doc_MnJ3o");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_k350s");
        t.prejmi(new Tretja.Asistent(), "as_zXbSD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Ny6DW");
        t.prejmi(new Tretja.Docent(), "doc_PmZuQ");
        t.prejmi(new Tretja.Profesor(), "prof_htstQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Onukk");
        t.prejmi(new Tretja.Docent(), "doc_tuxjK");
        t.prejmi(new Tretja.Docent(), "doc_zztB6");
        t.prejmi(new Tretja.Profesor(), "prof_eV9Lo");
        System.out.println(t.natisni());
    }
}
