
public class Test28 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_Ybeca");
        t.prejmi(new Tretja.Docent(), "doc_5mKGE");
        t.prejmi(new Tretja.Asistent(), "as_Vv7lV");
        t.prejmi(new Tretja.Asistent(), "as_yFh1n");
        t.prejmi(new Tretja.Docent(), "doc_h4zsz");
        t.prejmi(new Tretja.Profesor(), "prof_QUcKX");
        t.prejmi(new Tretja.Docent(), "doc_wqcj5");
        t.prejmi(new Tretja.Docent(), "doc_vwTXl");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_Vo8Dy");
        t.prejmi(new Tretja.Asistent(), "as_2s1hC");
        t.prejmi(new Tretja.Docent(), "doc_wsbDl");
        t.prejmi(new Tretja.Asistent(), "as_oMP7t");
        t.prejmi(new Tretja.Docent(), "doc_yet3r");
        t.prejmi(new Tretja.Docent(), "doc_oC2i0");
        t.prejmi(new Tretja.Profesor(), "prof_n843j");
        t.prejmi(new Tretja.Asistent(), "as_F7Dem");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_o59Xc");
        t.prejmi(new Tretja.Profesor(), "prof_pTPzV");
        t.prejmi(new Tretja.Profesor(), "prof_UnnnV");
        t.prejmi(new Tretja.Docent(), "doc_e9PWu");
        t.prejmi(new Tretja.Profesor(), "prof_Ljp7f");
        t.prejmi(new Tretja.Docent(), "doc_ZQUEI");
        t.prejmi(new Tretja.Docent(), "doc_ccznA");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_pOgYu");
        t.prejmi(new Tretja.Docent(), "doc_z4kBf");
        t.prejmi(new Tretja.Docent(), "doc_0nzy0");
        t.prejmi(new Tretja.Profesor(), "prof_4miVq");
        t.prejmi(new Tretja.Asistent(), "as_EwKrO");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_lRNQm");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_eju7t");
        t.prejmi(new Tretja.Asistent(), "as_GmnZY");
        t.prejmi(new Tretja.Docent(), "doc_7zgHY");
        t.prejmi(new Tretja.Profesor(), "prof_Exo65");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_3T4m9");
        t.prejmi(new Tretja.Profesor(), "prof_4piZT");
        t.prejmi(new Tretja.Asistent(), "as_06a27");
        t.prejmi(new Tretja.Docent(), "doc_q12N7");
        t.prejmi(new Tretja.Docent(), "doc_ptlqw");
        t.prejmi(new Tretja.Docent(), "doc_y7F1o");
        t.prejmi(new Tretja.Asistent(), "as_T5VeD");
        t.prejmi(new Tretja.Asistent(), "as_8hgos");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ym6cW");
        t.prejmi(new Tretja.Profesor(), "prof_MonTz");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_7ESnd");
        t.prejmi(new Tretja.Profesor(), "prof_4dJc7");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_qnIy2");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_7lxob");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_9Js2I");
        t.prejmi(new Tretja.Docent(), "doc_989cC");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wdRIM");
        t.prejmi(new Tretja.Docent(), "doc_R8rNF");
        t.prejmi(new Tretja.Profesor(), "prof_NCrwF");
        t.prejmi(new Tretja.Docent(), "doc_EmvRF");
        t.prejmi(new Tretja.Asistent(), "as_cwlWL");
        t.prejmi(new Tretja.Profesor(), "prof_9Ue3R");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_Pih1Y");
        t.prejmi(new Tretja.Docent(), "doc_0li1O");
        t.prejmi(new Tretja.Asistent(), "as_ESs6E");
        t.prejmi(new Tretja.Profesor(), "prof_NerAb");
        t.prejmi(new Tretja.Docent(), "doc_cUNLB");
        t.prejmi(new Tretja.Docent(), "doc_SkP08");
        t.prejmi(new Tretja.Docent(), "doc_qC6sM");
        t.prejmi(new Tretja.Asistent(), "as_BnOc1");
        t.prejmi(new Tretja.Profesor(), "prof_c5Ocw");
        t.prejmi(new Tretja.Asistent(), "as_Ta1bN");
        t.prejmi(new Tretja.Asistent(), "as_dg86s");
        t.prejmi(new Tretja.Docent(), "doc_IIQiB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_38atY");
        t.prejmi(new Tretja.Asistent(), "as_QYOby");
        t.prejmi(new Tretja.Asistent(), "as_M16BU");
        t.prejmi(new Tretja.Docent(), "doc_bP3Zl");
        t.prejmi(new Tretja.Profesor(), "prof_gDz7T");
        t.prejmi(new Tretja.Docent(), "doc_pukyN");
        t.prejmi(new Tretja.Asistent(), "as_EJz6y");
        t.prejmi(new Tretja.Docent(), "doc_06ADI");
        t.prejmi(new Tretja.Profesor(), "prof_jlqYo");
        t.prejmi(new Tretja.Profesor(), "prof_oTop3");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_yw8Pg");
        t.prejmi(new Tretja.Docent(), "doc_qAGwD");
        t.prejmi(new Tretja.Asistent(), "as_4GGT6");
        t.prejmi(new Tretja.Profesor(), "prof_5SCR3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_A2E21");
        t.prejmi(new Tretja.Profesor(), "prof_S5dkx");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_NwV2z");
        t.prejmi(new Tretja.Docent(), "doc_F1Wzu");
        t.prejmi(new Tretja.Asistent(), "as_zWx3j");
        t.prejmi(new Tretja.Docent(), "doc_7gzUU");
        t.prejmi(new Tretja.Docent(), "doc_byB2c");
        t.prejmi(new Tretja.Docent(), "doc_c0Mvx");
        t.prejmi(new Tretja.Docent(), "doc_uJuLG");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_bEZnW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_WAMFg");
        t.prejmi(new Tretja.Profesor(), "prof_lABqe");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_pB0Ex");
        t.prejmi(new Tretja.Docent(), "doc_vm3Wf");
        t.prejmi(new Tretja.Docent(), "doc_hH5Ce");
        t.prejmi(new Tretja.Docent(), "doc_ury3H");
        t.prejmi(new Tretja.Asistent(), "as_Gu0Fr");
        t.prejmi(new Tretja.Docent(), "doc_HYk51");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Y3D95");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_hn8IB");
        t.prejmi(new Tretja.Docent(), "doc_S8Z3W");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_GRHqw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_gz7Dt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_5ZwuX");
        t.prejmi(new Tretja.Docent(), "doc_qSlEQ");
        t.prejmi(new Tretja.Profesor(), "prof_GCDE2");
        t.prejmi(new Tretja.Asistent(), "as_UYdqn");
        t.prejmi(new Tretja.Docent(), "doc_FAUJI");
        t.prejmi(new Tretja.Docent(), "doc_twHfO");
        t.prejmi(new Tretja.Docent(), "doc_3XgDr");
        t.prejmi(new Tretja.Docent(), "doc_jTAq2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_UWA7k");
        t.prejmi(new Tretja.Profesor(), "prof_qdcCo");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_BK4Zw");
        t.prejmi(new Tretja.Asistent(), "as_9ys1U");
        t.prejmi(new Tretja.Asistent(), "as_yCoxQ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_3Ed4t");
        t.prejmi(new Tretja.Profesor(), "prof_Omct1");
        t.prejmi(new Tretja.Docent(), "doc_XXdrO");
        t.prejmi(new Tretja.Docent(), "doc_Al6MC");
        t.prejmi(new Tretja.Docent(), "doc_pzqn7");
        t.prejmi(new Tretja.Docent(), "doc_xTJ02");
        t.prejmi(new Tretja.Docent(), "doc_Hzns7");
        t.prejmi(new Tretja.Profesor(), "prof_loGr7");
        t.prejmi(new Tretja.Profesor(), "prof_XKIJU");
        t.prejmi(new Tretja.Asistent(), "as_YDnXU");
        t.prejmi(new Tretja.Asistent(), "as_6d25v");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_qgKfv");
        t.prejmi(new Tretja.Profesor(), "prof_4loa6");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_yzj1g");
        t.prejmi(new Tretja.Asistent(), "as_OnuGD");
        t.prejmi(new Tretja.Asistent(), "as_keFS4");
        t.prejmi(new Tretja.Docent(), "doc_KBpS9");
        t.prejmi(new Tretja.Docent(), "doc_jWaPG");
        t.prejmi(new Tretja.Docent(), "doc_SXWxX");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_sR0q2");
        t.prejmi(new Tretja.Docent(), "doc_dMxfu");
        t.prejmi(new Tretja.Profesor(), "prof_Cdanz");
        t.prejmi(new Tretja.Profesor(), "prof_hyhix");
        t.prejmi(new Tretja.Docent(), "doc_F6UCo");
        t.prejmi(new Tretja.Docent(), "doc_0KN3A");
        t.prejmi(new Tretja.Profesor(), "prof_dt6fv");
        t.prejmi(new Tretja.Asistent(), "as_cXNXK");
        t.prejmi(new Tretja.Docent(), "doc_bJx1p");
        t.prejmi(new Tretja.Profesor(), "prof_LWWfk");
        t.prejmi(new Tretja.Profesor(), "prof_Z5EsP");
        t.prejmi(new Tretja.Profesor(), "prof_qCICT");
        t.prejmi(new Tretja.Docent(), "doc_i4Q6W");
        t.prejmi(new Tretja.Asistent(), "as_3GuN0");
        t.prejmi(new Tretja.Docent(), "doc_PUm6f");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_Efck4");
        t.prejmi(new Tretja.Profesor(), "prof_KcEUu");
        t.prejmi(new Tretja.Docent(), "doc_vJ4Oa");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_Slkt2");
        t.prejmi(new Tretja.Profesor(), "prof_Aq2c3");
        t.prejmi(new Tretja.Docent(), "doc_VXB9N");
        t.prejmi(new Tretja.Asistent(), "as_YqtFh");
        t.prejmi(new Tretja.Asistent(), "as_i21M3");
        t.prejmi(new Tretja.Docent(), "doc_W5CZF");
        t.prejmi(new Tretja.Profesor(), "prof_9BUBy");
        t.prejmi(new Tretja.Docent(), "doc_Ih7yn");
        t.prejmi(new Tretja.Docent(), "doc_EzLMJ");
        t.prejmi(new Tretja.Profesor(), "prof_VOfuo");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_ZqxyW");
        t.prejmi(new Tretja.Docent(), "doc_qNJpv");
        t.prejmi(new Tretja.Asistent(), "as_CNLyg");
        t.prejmi(new Tretja.Docent(), "doc_930Z5");
        t.prejmi(new Tretja.Docent(), "doc_J0bom");
        t.prejmi(new Tretja.Asistent(), "as_JBnFR");
        t.prejmi(new Tretja.Asistent(), "as_WLc5J");
        t.prejmi(new Tretja.Docent(), "doc_inhbN");
        t.prejmi(new Tretja.Profesor(), "prof_wuGsC");
        t.prejmi(new Tretja.Docent(), "doc_MJ7X2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_M75PY");
        t.prejmi(new Tretja.Profesor(), "prof_hneF7");
        t.prejmi(new Tretja.Docent(), "doc_IZV42");
        t.prejmi(new Tretja.Asistent(), "as_nKJ63");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_7H95I");
        t.prejmi(new Tretja.Docent(), "doc_xN2jV");
        t.prejmi(new Tretja.Docent(), "doc_JV4C2");
        t.prejmi(new Tretja.Asistent(), "as_DJh7H");
        t.prejmi(new Tretja.Docent(), "doc_ANVA6");
        t.prejmi(new Tretja.Asistent(), "as_x0uUI");
        t.prejmi(new Tretja.Asistent(), "as_jNSrC");
        t.prejmi(new Tretja.Docent(), "doc_EKmgg");
        t.prejmi(new Tretja.Docent(), "doc_KW1V6");
        t.prejmi(new Tretja.Asistent(), "as_raPzE");
        t.prejmi(new Tretja.Profesor(), "prof_Sf9EU");
        t.prejmi(new Tretja.Asistent(), "as_sJKhK");
        t.prejmi(new Tretja.Profesor(), "prof_Weexl");
        t.prejmi(new Tretja.Asistent(), "as_xIkCj");
        t.prejmi(new Tretja.Asistent(), "as_quTeZ");
        t.prejmi(new Tretja.Profesor(), "prof_pmmSr");
        t.prejmi(new Tretja.Docent(), "doc_6QKh3");
        t.prejmi(new Tretja.Profesor(), "prof_PDVmx");
        t.prejmi(new Tretja.Docent(), "doc_n10uf");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_HD5Ao");
        t.prejmi(new Tretja.Asistent(), "as_gAGbi");
        t.prejmi(new Tretja.Docent(), "doc_ZdrXA");
        t.prejmi(new Tretja.Docent(), "doc_0qWZA");
        t.prejmi(new Tretja.Asistent(), "as_al76a");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_jbGGx");
        t.prejmi(new Tretja.Asistent(), "as_a6eA5");
        t.prejmi(new Tretja.Profesor(), "prof_j9RPr");
        t.prejmi(new Tretja.Docent(), "doc_kk2qU");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_1fLUO");
        t.prejmi(new Tretja.Profesor(), "prof_h47kQ");
        t.prejmi(new Tretja.Profesor(), "prof_LtjT0");
        t.prejmi(new Tretja.Docent(), "doc_G8Nm8");
        t.prejmi(new Tretja.Docent(), "doc_S10JG");
        t.prejmi(new Tretja.Asistent(), "as_k2VkN");
        t.prejmi(new Tretja.Asistent(), "as_aVr5c");
        t.prejmi(new Tretja.Docent(), "doc_lSH0y");
        t.prejmi(new Tretja.Docent(), "doc_nKwtL");
        t.prejmi(new Tretja.Asistent(), "as_kiQT3");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_u7zOl");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_Bsv3v");
        t.prejmi(new Tretja.Asistent(), "as_epYoy");
        t.prejmi(new Tretja.Profesor(), "prof_EWK5N");
        t.prejmi(new Tretja.Asistent(), "as_PoHtd");
        t.prejmi(new Tretja.Docent(), "doc_wp23K");
        t.prejmi(new Tretja.Asistent(), "as_fB9dW");
        t.prejmi(new Tretja.Asistent(), "as_PezxJ");
        t.prejmi(new Tretja.Profesor(), "prof_nvN5V");
        t.prejmi(new Tretja.Asistent(), "as_BRU6i");
        t.prejmi(new Tretja.Profesor(), "prof_TGt90");
        t.prejmi(new Tretja.Asistent(), "as_z3es3");
        t.prejmi(new Tretja.Asistent(), "as_4oF9Y");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_LyrLB");
        t.prejmi(new Tretja.Asistent(), "as_n3FDC");
        t.prejmi(new Tretja.Profesor(), "prof_KZ5oF");
        t.prejmi(new Tretja.Asistent(), "as_a4LGz");
        t.prejmi(new Tretja.Asistent(), "as_IDaC5");
        t.prejmi(new Tretja.Profesor(), "prof_8XiY3");
        t.prejmi(new Tretja.Asistent(), "as_IHvcF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_kQNm2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_RabIm");
        t.prejmi(new Tretja.Asistent(), "as_arQus");
        t.prejmi(new Tretja.Docent(), "doc_Saawn");
        t.prejmi(new Tretja.Asistent(), "as_hpGTt");
        t.prejmi(new Tretja.Docent(), "doc_r6axl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_CdGSQ");
        t.prejmi(new Tretja.Asistent(), "as_M34v9");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_dyUsf");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_Fh3Pu");
        t.prejmi(new Tretja.Asistent(), "as_KVvQR");
        t.prejmi(new Tretja.Profesor(), "prof_p8azR");
        t.prejmi(new Tretja.Docent(), "doc_yesfI");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_eoUer");
        t.prejmi(new Tretja.Asistent(), "as_ffzda");
        t.prejmi(new Tretja.Asistent(), "as_m93S9");
        t.prejmi(new Tretja.Profesor(), "prof_kWvog");
        t.prejmi(new Tretja.Profesor(), "prof_nb9cC");
        t.prejmi(new Tretja.Profesor(), "prof_Ui27T");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_50E1j");
        t.prejmi(new Tretja.Profesor(), "prof_OTSEo");
        t.prejmi(new Tretja.Asistent(), "as_aFrwg");
        t.prejmi(new Tretja.Asistent(), "as_sdxrX");
        t.prejmi(new Tretja.Asistent(), "as_GEpen");
        t.prejmi(new Tretja.Profesor(), "prof_if61q");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_pqkU1");
        t.prejmi(new Tretja.Profesor(), "prof_k1gFZ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_dDF36");
        t.prejmi(new Tretja.Profesor(), "prof_6UIn3");
        t.prejmi(new Tretja.Asistent(), "as_uFygo");
        t.prejmi(new Tretja.Asistent(), "as_qsAS9");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_EBqij");
        t.prejmi(new Tretja.Docent(), "doc_yzs2V");
        t.prejmi(new Tretja.Profesor(), "prof_9S4Fi");
        t.prejmi(new Tretja.Asistent(), "as_iQDxV");
        t.prejmi(new Tretja.Docent(), "doc_sxdyj");
        t.prejmi(new Tretja.Asistent(), "as_bBwoR");
        t.prejmi(new Tretja.Profesor(), "prof_bfzwT");
        t.prejmi(new Tretja.Profesor(), "prof_REML6");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_lnDKB");
        t.prejmi(new Tretja.Asistent(), "as_uVQxu");
        t.prejmi(new Tretja.Profesor(), "prof_qpD1K");
        t.prejmi(new Tretja.Docent(), "doc_QhTGo");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_e0wsx");
        t.prejmi(new Tretja.Asistent(), "as_N0Ozh");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_pYrIl");
        t.prejmi(new Tretja.Asistent(), "as_Zo09R");
        t.prejmi(new Tretja.Profesor(), "prof_9XhXK");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Wawl5");
        t.prejmi(new Tretja.Docent(), "doc_oQJbh");
        t.prejmi(new Tretja.Profesor(), "prof_8bFfz");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_D2flB");
        t.prejmi(new Tretja.Asistent(), "as_Et2zs");
        t.prejmi(new Tretja.Docent(), "doc_dFOie");
        t.prejmi(new Tretja.Profesor(), "prof_cLhoI");
        t.prejmi(new Tretja.Profesor(), "prof_tZs3c");
        t.prejmi(new Tretja.Asistent(), "as_4AVBT");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_hicoq");
        t.prejmi(new Tretja.Profesor(), "prof_KjBX4");
        t.prejmi(new Tretja.Asistent(), "as_PjWl3");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_ILB44");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_BToQK");
        t.prejmi(new Tretja.Profesor(), "prof_q8u2K");
        t.prejmi(new Tretja.Profesor(), "prof_3EMwy");
        t.prejmi(new Tretja.Profesor(), "prof_WJelE");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_dBIv4");
        t.prejmi(new Tretja.Profesor(), "prof_oe688");
        t.prejmi(new Tretja.Profesor(), "prof_lXO8B");
        t.prejmi(new Tretja.Asistent(), "as_mCPhM");
        t.prejmi(new Tretja.Docent(), "doc_tpTTf");
        t.prejmi(new Tretja.Docent(), "doc_1TUW9");
        t.prejmi(new Tretja.Docent(), "doc_t433Y");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_fapWT");
        t.prejmi(new Tretja.Docent(), "doc_qYvzl");
        t.prejmi(new Tretja.Docent(), "doc_SIg1E");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_BvI07");
        t.prejmi(new Tretja.Docent(), "doc_aEVl7");
        t.prejmi(new Tretja.Docent(), "doc_76oQU");
        t.prejmi(new Tretja.Asistent(), "as_FE9xK");
        t.prejmi(new Tretja.Asistent(), "as_o53Mz");
        t.prejmi(new Tretja.Docent(), "doc_Um7He");
        t.prejmi(new Tretja.Asistent(), "as_X8ye2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_lBpM5");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Cy0cg");
        t.prejmi(new Tretja.Profesor(), "prof_1OylT");
        t.prejmi(new Tretja.Asistent(), "as_Qhtpk");
        t.prejmi(new Tretja.Asistent(), "as_UVg0N");
        t.prejmi(new Tretja.Profesor(), "prof_VcSw3");
        t.prejmi(new Tretja.Docent(), "doc_vGxRP");
        t.prejmi(new Tretja.Profesor(), "prof_s0lCz");
        t.prejmi(new Tretja.Profesor(), "prof_Tg9IB");
        t.prejmi(new Tretja.Asistent(), "as_qAPKR");
        t.prejmi(new Tretja.Asistent(), "as_6fpKk");
        t.prejmi(new Tretja.Docent(), "doc_UgOLU");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_LWexi");
        t.prejmi(new Tretja.Profesor(), "prof_V1qBg");
        t.prejmi(new Tretja.Docent(), "doc_YMqhc");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_AJiVb");
        t.prejmi(new Tretja.Profesor(), "prof_dPms2");
        t.prejmi(new Tretja.Profesor(), "prof_LRxEm");
        t.prejmi(new Tretja.Asistent(), "as_pxoVA");
        t.prejmi(new Tretja.Docent(), "doc_dLj12");
        t.prejmi(new Tretja.Asistent(), "as_gHx5a");
        t.prejmi(new Tretja.Profesor(), "prof_WrKhD");
        t.prejmi(new Tretja.Profesor(), "prof_Xrenr");
        t.prejmi(new Tretja.Asistent(), "as_8koXn");
        t.prejmi(new Tretja.Profesor(), "prof_0hEe7");
        t.prejmi(new Tretja.Profesor(), "prof_DYjOj");
        t.prejmi(new Tretja.Profesor(), "prof_zmOei");
        t.prejmi(new Tretja.Profesor(), "prof_vU2E5");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_sgDsF");
        t.prejmi(new Tretja.Docent(), "doc_Jx4D5");
        t.prejmi(new Tretja.Docent(), "doc_Wnhsi");
        t.prejmi(new Tretja.Docent(), "doc_J0HtV");
        t.prejmi(new Tretja.Docent(), "doc_gSoSl");
        t.prejmi(new Tretja.Asistent(), "as_71J0U");
        t.prejmi(new Tretja.Profesor(), "prof_I8fEb");
        t.prejmi(new Tretja.Profesor(), "prof_3xJBD");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_556HK");
        t.prejmi(new Tretja.Profesor(), "prof_X0YQI");
        t.prejmi(new Tretja.Profesor(), "prof_lYMpP");
        t.prejmi(new Tretja.Profesor(), "prof_jHGGb");
        t.prejmi(new Tretja.Asistent(), "as_rDFoV");
        t.prejmi(new Tretja.Asistent(), "as_Bv9mC");
        t.prejmi(new Tretja.Profesor(), "prof_zlX7S");
        t.prejmi(new Tretja.Docent(), "doc_09Woi");
        t.prejmi(new Tretja.Asistent(), "as_sIUA3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_7TOv1");
        t.prejmi(new Tretja.Asistent(), "as_pzkjz");
        t.prejmi(new Tretja.Profesor(), "prof_DkkBp");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_2bhcJ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_WrQ1V");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_c2q0R");
        t.prejmi(new Tretja.Docent(), "doc_UGrsz");
        t.prejmi(new Tretja.Docent(), "doc_P4Uov");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_kb7kJ");
        t.prejmi(new Tretja.Profesor(), "prof_KKBTb");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_J4SY5");
        t.prejmi(new Tretja.Profesor(), "prof_EFZvj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_nA9tm");
        t.prejmi(new Tretja.Profesor(), "prof_tUatD");
        t.prejmi(new Tretja.Asistent(), "as_gA7q3");
        t.prejmi(new Tretja.Docent(), "doc_4O4ic");
        t.prejmi(new Tretja.Profesor(), "prof_JqblQ");
        t.prejmi(new Tretja.Profesor(), "prof_YD1px");
        t.prejmi(new Tretja.Profesor(), "prof_ndugR");
        t.prejmi(new Tretja.Profesor(), "prof_Lcljg");
        t.prejmi(new Tretja.Asistent(), "as_MNleG");
        t.prejmi(new Tretja.Asistent(), "as_xGzEd");
        t.prejmi(new Tretja.Asistent(), "as_Eou5E");
        t.prejmi(new Tretja.Docent(), "doc_zqWIJ");
        t.prejmi(new Tretja.Profesor(), "prof_o8Qwh");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_A3SWm");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_2iavA");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_AuKKZ");
        t.prejmi(new Tretja.Profesor(), "prof_GosEs");
        t.prejmi(new Tretja.Asistent(), "as_50ibh");
        t.prejmi(new Tretja.Asistent(), "as_rVTn7");
        t.prejmi(new Tretja.Docent(), "doc_HkjCV");
        t.prejmi(new Tretja.Asistent(), "as_ynnfa");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_qy80C");
        t.prejmi(new Tretja.Docent(), "doc_LEeJR");
        t.prejmi(new Tretja.Docent(), "doc_bL9Pg");
        t.prejmi(new Tretja.Profesor(), "prof_VFTbf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_BYmxR");
        t.prejmi(new Tretja.Docent(), "doc_S8CqG");
        t.prejmi(new Tretja.Asistent(), "as_rYEhV");
        t.prejmi(new Tretja.Asistent(), "as_i3p0s");
        t.prejmi(new Tretja.Docent(), "doc_JzL0U");
        t.prejmi(new Tretja.Docent(), "doc_NQLKn");
        t.prejmi(new Tretja.Asistent(), "as_ticzx");
        t.prejmi(new Tretja.Asistent(), "as_eqqkz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_Bif2N");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_mc1nj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_eFfqv");
        t.prejmi(new Tretja.Asistent(), "as_VAAWk");
        t.prejmi(new Tretja.Asistent(), "as_LXtgd");
        t.prejmi(new Tretja.Asistent(), "as_HvR0x");
        t.prejmi(new Tretja.Asistent(), "as_eudtv");
        t.prejmi(new Tretja.Docent(), "doc_1rUqK");
        t.prejmi(new Tretja.Profesor(), "prof_o4S9K");
        t.prejmi(new Tretja.Docent(), "doc_W3HLB");
        t.prejmi(new Tretja.Profesor(), "prof_8YB01");
        t.prejmi(new Tretja.Profesor(), "prof_CVcy3");
        t.prejmi(new Tretja.Profesor(), "prof_BiGb0");
        t.prejmi(new Tretja.Profesor(), "prof_QWu9u");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_yuLcH");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_BdAEM");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_lycOp");
        t.prejmi(new Tretja.Docent(), "doc_HneyT");
        t.prejmi(new Tretja.Asistent(), "as_JBkDc");
        t.prejmi(new Tretja.Docent(), "doc_OBJia");
        t.prejmi(new Tretja.Profesor(), "prof_RCknU");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_9rsyL");
        t.prejmi(new Tretja.Asistent(), "as_yJppE");
        t.prejmi(new Tretja.Profesor(), "prof_w5gWx");
        t.prejmi(new Tretja.Profesor(), "prof_kcvNc");
        t.prejmi(new Tretja.Docent(), "doc_2tLUd");
        t.prejmi(new Tretja.Profesor(), "prof_7ClbB");
    }
}
