
public class Test27 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_CYTnd");
        t.prejmi(new Tretja.Asistent(), "as_8FYhE");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_rFyn6");
        t.prejmi(new Tretja.Asistent(), "as_W8bj0");
        t.prejmi(new Tretja.Docent(), "doc_2PzJC");
        t.prejmi(new Tretja.Docent(), "doc_d5vxO");
        t.prejmi(new Tretja.Profesor(), "prof_0IgwJ");
        t.prejmi(new Tretja.Profesor(), "prof_TY5Kr");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_deepe");
        t.prejmi(new Tretja.Asistent(), "as_PM8Ii");
        t.prejmi(new Tretja.Asistent(), "as_3ekQQ");
        t.prejmi(new Tretja.Asistent(), "as_7956H");
        t.prejmi(new Tretja.Profesor(), "prof_h56E5");
        t.prejmi(new Tretja.Asistent(), "as_9zt37");
        t.prejmi(new Tretja.Docent(), "doc_o6qNv");
        t.prejmi(new Tretja.Profesor(), "prof_J253V");
        t.prejmi(new Tretja.Asistent(), "as_NaJmv");
        t.prejmi(new Tretja.Asistent(), "as_qLvrz");
        t.prejmi(new Tretja.Profesor(), "prof_4dlkx");
        t.prejmi(new Tretja.Asistent(), "as_JcHVh");
        t.prejmi(new Tretja.Profesor(), "prof_chsWi");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_6owIT");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_liqtn");
        t.prejmi(new Tretja.Docent(), "doc_iUrZH");
        t.prejmi(new Tretja.Profesor(), "prof_GWo6E");
        t.prejmi(new Tretja.Docent(), "doc_Ug4KY");
        t.prejmi(new Tretja.Profesor(), "prof_gl8Cr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_C51Tp");
        t.prejmi(new Tretja.Profesor(), "prof_6I1eR");
        t.prejmi(new Tretja.Profesor(), "prof_lDnft");
        t.prejmi(new Tretja.Asistent(), "as_yZSbi");
        t.prejmi(new Tretja.Asistent(), "as_yZLmb");
        t.prejmi(new Tretja.Docent(), "doc_43R0F");
        t.prejmi(new Tretja.Asistent(), "as_gsbRt");
        t.prejmi(new Tretja.Asistent(), "as_8eiYj");
        t.prejmi(new Tretja.Docent(), "doc_oT8p8");
        t.prejmi(new Tretja.Docent(), "doc_lG3cz");
        t.prejmi(new Tretja.Asistent(), "as_x7c2e");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_OIzia");
        t.prejmi(new Tretja.Asistent(), "as_IbGwi");
        t.prejmi(new Tretja.Docent(), "doc_DxjvM");
        t.prejmi(new Tretja.Asistent(), "as_Rv8ue");
        t.prejmi(new Tretja.Asistent(), "as_NxYVT");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_TAJdI");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_KgeDR");
        t.prejmi(new Tretja.Docent(), "doc_NRyPm");
        t.prejmi(new Tretja.Asistent(), "as_2yVqH");
        t.prejmi(new Tretja.Asistent(), "as_AZzvt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_fXrsj");
        t.prejmi(new Tretja.Profesor(), "prof_Pi085");
        t.prejmi(new Tretja.Asistent(), "as_E1EF7");
        t.prejmi(new Tretja.Asistent(), "as_jmDtk");
        t.prejmi(new Tretja.Profesor(), "prof_mzqHL");
        t.prejmi(new Tretja.Profesor(), "prof_obrKo");
        t.prejmi(new Tretja.Docent(), "doc_dApyf");
        t.prejmi(new Tretja.Docent(), "doc_fXkaz");
        t.prejmi(new Tretja.Asistent(), "as_7Xs8n");
        t.prejmi(new Tretja.Profesor(), "prof_8Pu5W");
        t.prejmi(new Tretja.Docent(), "doc_JPed6");
        t.prejmi(new Tretja.Profesor(), "prof_K8odq");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_PS3Zg");
        t.prejmi(new Tretja.Asistent(), "as_OrKFu");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_vBd15");
        t.prejmi(new Tretja.Docent(), "doc_tZ9xZ");
        t.prejmi(new Tretja.Docent(), "doc_YLxIl");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_zX7MK");
        t.prejmi(new Tretja.Docent(), "doc_rBGEL");
        t.prejmi(new Tretja.Asistent(), "as_BJe7I");
        t.prejmi(new Tretja.Profesor(), "prof_ZXwy9");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_fNpH4");
        t.prejmi(new Tretja.Docent(), "doc_agYWQ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_nRkwD");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_IEfoF");
        t.prejmi(new Tretja.Docent(), "doc_BkhuH");
        t.prejmi(new Tretja.Profesor(), "prof_PZDWn");
        t.prejmi(new Tretja.Profesor(), "prof_lZK5l");
        t.prejmi(new Tretja.Asistent(), "as_dbqQL");
        t.prejmi(new Tretja.Profesor(), "prof_Ya0GL");
        t.prejmi(new Tretja.Asistent(), "as_bE72X");
        t.prejmi(new Tretja.Asistent(), "as_ocVBt");
        t.prejmi(new Tretja.Docent(), "doc_9aMCd");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_sc546");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_P46DL");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_QuVbB");
        t.prejmi(new Tretja.Asistent(), "as_T9XGY");
        t.prejmi(new Tretja.Docent(), "doc_nG6kw");
        t.prejmi(new Tretja.Asistent(), "as_4lFja");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_FRMPU");
        t.prejmi(new Tretja.Profesor(), "prof_DByjn");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_EE4Af");
        t.prejmi(new Tretja.Docent(), "doc_44E7j");
        t.prejmi(new Tretja.Docent(), "doc_OQnVC");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_xUNpx");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_t3iJi");
        t.prejmi(new Tretja.Asistent(), "as_BxCg6");
        t.prejmi(new Tretja.Docent(), "doc_3IGIf");
        t.prejmi(new Tretja.Asistent(), "as_QxSPI");
        t.prejmi(new Tretja.Docent(), "doc_J6IJo");
        t.prejmi(new Tretja.Profesor(), "prof_PyYCZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_GDJHh");
        t.prejmi(new Tretja.Profesor(), "prof_tYlaL");
        t.prejmi(new Tretja.Docent(), "doc_T2dX8");
        t.prejmi(new Tretja.Asistent(), "as_yMmZ4");
        t.prejmi(new Tretja.Profesor(), "prof_LyOaz");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_Jyq1C");
        t.prejmi(new Tretja.Asistent(), "as_45xNg");
        t.prejmi(new Tretja.Docent(), "doc_gMF2M");
        t.prejmi(new Tretja.Profesor(), "prof_CBK91");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_VAH9R");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_xoIwt");
        t.prejmi(new Tretja.Docent(), "doc_oq9a0");
        t.prejmi(new Tretja.Profesor(), "prof_HQXzf");
        t.prejmi(new Tretja.Docent(), "doc_IxMAX");
        t.prejmi(new Tretja.Asistent(), "as_fbHI6");
        t.prejmi(new Tretja.Profesor(), "prof_9Ra0s");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_vKuPR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_JL1iJ");
        t.prejmi(new Tretja.Profesor(), "prof_nNSU0");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_0TpBS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_oRY0C");
        t.prejmi(new Tretja.Profesor(), "prof_Br6JA");
        t.prejmi(new Tretja.Profesor(), "prof_mS6cx");
        t.prejmi(new Tretja.Profesor(), "prof_EfE4x");
        t.prejmi(new Tretja.Asistent(), "as_uzAIA");
        t.prejmi(new Tretja.Profesor(), "prof_V6fKE");
        t.prejmi(new Tretja.Profesor(), "prof_G7oUQ");
        t.prejmi(new Tretja.Docent(), "doc_N9Ce9");
        t.prejmi(new Tretja.Asistent(), "as_bh9gh");
        t.prejmi(new Tretja.Asistent(), "as_tkrGm");
        t.prejmi(new Tretja.Docent(), "doc_aytv3");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_ssyO2");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_Mp60Y");
        t.prejmi(new Tretja.Profesor(), "prof_xgIcx");
        t.prejmi(new Tretja.Asistent(), "as_xCoYH");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_0aRMr");
        t.prejmi(new Tretja.Docent(), "doc_IB63s");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_4688e");
        t.prejmi(new Tretja.Asistent(), "as_zO1Ha");
        t.prejmi(new Tretja.Profesor(), "prof_khN6b");
        t.prejmi(new Tretja.Profesor(), "prof_AvMBK");
        t.prejmi(new Tretja.Asistent(), "as_kTEqH");
        t.prejmi(new Tretja.Docent(), "doc_ZRj31");
        t.prejmi(new Tretja.Asistent(), "as_BHRDb");
        t.prejmi(new Tretja.Profesor(), "prof_L5mwo");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_gaosf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_QpYcs");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_blnpo");
        t.prejmi(new Tretja.Profesor(), "prof_KXm8X");
        t.prejmi(new Tretja.Docent(), "doc_O1NnH");
        t.prejmi(new Tretja.Docent(), "doc_kWJmm");
        t.prejmi(new Tretja.Asistent(), "as_dOkV0");
        t.prejmi(new Tretja.Profesor(), "prof_AbYHl");
        t.prejmi(new Tretja.Docent(), "doc_JHWLE");
        t.prejmi(new Tretja.Profesor(), "prof_snzcw");
        t.prejmi(new Tretja.Asistent(), "as_mgDJQ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_1aXXt");
        t.prejmi(new Tretja.Asistent(), "as_cKx9i");
        t.prejmi(new Tretja.Asistent(), "as_FkMlW");
        t.prejmi(new Tretja.Profesor(), "prof_sepyC");
        t.prejmi(new Tretja.Docent(), "doc_76XxT");
        t.prejmi(new Tretja.Profesor(), "prof_wampZ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_wAciK");
        t.prejmi(new Tretja.Profesor(), "prof_zv0j6");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_g0LQx");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_L5Ekx");
        t.prejmi(new Tretja.Profesor(), "prof_DiwiS");
        t.prejmi(new Tretja.Profesor(), "prof_pFTKB");
        t.prejmi(new Tretja.Asistent(), "as_PzLbA");
        t.prejmi(new Tretja.Profesor(), "prof_AAJvw");
        t.prejmi(new Tretja.Asistent(), "as_HfoQR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_GanSO");
        t.prejmi(new Tretja.Docent(), "doc_Ht3YB");
        t.prejmi(new Tretja.Asistent(), "as_YHJuC");
        t.prejmi(new Tretja.Docent(), "doc_32N6U");
        t.prejmi(new Tretja.Asistent(), "as_CR8Fq");
        t.prejmi(new Tretja.Docent(), "doc_DLGz0");
        t.prejmi(new Tretja.Docent(), "doc_PMU44");
        t.prejmi(new Tretja.Asistent(), "as_i4VRb");
        t.prejmi(new Tretja.Profesor(), "prof_xmyed");
        t.prejmi(new Tretja.Docent(), "doc_jaaqc");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_8oxEV");
        t.prejmi(new Tretja.Asistent(), "as_Ry1HF");
        t.prejmi(new Tretja.Docent(), "doc_ihLjk");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_VIzsn");
        t.prejmi(new Tretja.Asistent(), "as_Hsna2");
        t.prejmi(new Tretja.Docent(), "doc_STw4r");
        t.prejmi(new Tretja.Docent(), "doc_ILCI2");
        t.prejmi(new Tretja.Docent(), "doc_HY3Cx");
        t.prejmi(new Tretja.Profesor(), "prof_wOcjv");
        t.prejmi(new Tretja.Profesor(), "prof_idSOK");
        t.prejmi(new Tretja.Asistent(), "as_fQpUl");
        t.prejmi(new Tretja.Profesor(), "prof_kwNfb");
        t.prejmi(new Tretja.Asistent(), "as_PN1SI");
        t.prejmi(new Tretja.Docent(), "doc_lAeu3");
        t.prejmi(new Tretja.Profesor(), "prof_H1AIr");
        t.prejmi(new Tretja.Profesor(), "prof_7sYHV");
        t.prejmi(new Tretja.Profesor(), "prof_7H2P0");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_I825h");
        t.prejmi(new Tretja.Asistent(), "as_JI9Gq");
        t.prejmi(new Tretja.Asistent(), "as_JVeHk");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_nWGR4");
        t.prejmi(new Tretja.Asistent(), "as_jfwrF");
        t.prejmi(new Tretja.Asistent(), "as_nxudq");
        t.prejmi(new Tretja.Docent(), "doc_j7TPv");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_3yHy4");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_JcpNu");
        t.prejmi(new Tretja.Profesor(), "prof_QgYJR");
        t.prejmi(new Tretja.Profesor(), "prof_DDajV");
        t.prejmi(new Tretja.Profesor(), "prof_XyqdL");
        t.prejmi(new Tretja.Asistent(), "as_aYsoH");
        t.prejmi(new Tretja.Asistent(), "as_goky0");
        t.prejmi(new Tretja.Asistent(), "as_zLXwD");
        t.prejmi(new Tretja.Profesor(), "prof_X5aQZ");
        t.prejmi(new Tretja.Asistent(), "as_hIY0z");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_U0vDb");
        t.prejmi(new Tretja.Profesor(), "prof_ACdCs");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_ky5wh");
        t.prejmi(new Tretja.Profesor(), "prof_fSzDp");
        t.prejmi(new Tretja.Profesor(), "prof_VBzYo");
        t.prejmi(new Tretja.Profesor(), "prof_epr6U");
        t.prejmi(new Tretja.Docent(), "doc_6VFQc");
        t.prejmi(new Tretja.Asistent(), "as_QbDG1");
        t.prejmi(new Tretja.Docent(), "doc_iZt0p");
        t.prejmi(new Tretja.Docent(), "doc_6iL8l");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_hhXV7");
        t.prejmi(new Tretja.Profesor(), "prof_UL56h");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_O2Dy6");
        t.prejmi(new Tretja.Profesor(), "prof_gyHNU");
        t.prejmi(new Tretja.Profesor(), "prof_tu4nc");
        t.prejmi(new Tretja.Asistent(), "as_dt0Ud");
        t.prejmi(new Tretja.Profesor(), "prof_bluZa");
        t.prejmi(new Tretja.Profesor(), "prof_w7WuT");
        t.prejmi(new Tretja.Profesor(), "prof_78BIK");
        t.prejmi(new Tretja.Profesor(), "prof_RGx6O");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Tlwjy");
        t.prejmi(new Tretja.Docent(), "doc_VqGCE");
        t.prejmi(new Tretja.Profesor(), "prof_pmcno");
        t.prejmi(new Tretja.Asistent(), "as_Emn1R");
        t.prejmi(new Tretja.Asistent(), "as_slRJI");
        t.prejmi(new Tretja.Profesor(), "prof_FDqw3");
        t.prejmi(new Tretja.Profesor(), "prof_stZB6");
        t.prejmi(new Tretja.Profesor(), "prof_VEMBj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_fgh7X");
        t.prejmi(new Tretja.Profesor(), "prof_cAUJS");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_iUruL");
        t.prejmi(new Tretja.Asistent(), "as_y4NHF");
        t.prejmi(new Tretja.Docent(), "doc_DNeoE");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_j7Dbf");
        t.prejmi(new Tretja.Asistent(), "as_JHw4h");
        t.prejmi(new Tretja.Docent(), "doc_vTNyq");
        t.prejmi(new Tretja.Profesor(), "prof_Igb6t");
        t.prejmi(new Tretja.Profesor(), "prof_fkkYb");
        t.prejmi(new Tretja.Docent(), "doc_JGD22");
        t.prejmi(new Tretja.Docent(), "doc_TPtrx");
        t.prejmi(new Tretja.Asistent(), "as_I4lXZ");
        t.prejmi(new Tretja.Asistent(), "as_gQvdA");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_vyKkI");
        t.prejmi(new Tretja.Docent(), "doc_OdS4A");
        t.prejmi(new Tretja.Asistent(), "as_XubB6");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_BNn4m");
        t.prejmi(new Tretja.Profesor(), "prof_Xz8JM");
        t.prejmi(new Tretja.Asistent(), "as_BMo28");
        t.prejmi(new Tretja.Asistent(), "as_t7cTH");
        t.prejmi(new Tretja.Asistent(), "as_jzIaI");
        t.prejmi(new Tretja.Docent(), "doc_luVXJ");
        t.prejmi(new Tretja.Docent(), "doc_F3kzJ");
        t.prejmi(new Tretja.Asistent(), "as_Ge5us");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_3YBVv");
        t.prejmi(new Tretja.Docent(), "doc_MMXS4");
        t.prejmi(new Tretja.Docent(), "doc_oSFND");
        t.prejmi(new Tretja.Asistent(), "as_u0d3l");
        t.prejmi(new Tretja.Profesor(), "prof_8JUgY");
        t.prejmi(new Tretja.Profesor(), "prof_Qbf0L");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_dpK3s");
        t.prejmi(new Tretja.Profesor(), "prof_JrykM");
        t.prejmi(new Tretja.Docent(), "doc_L7UwL");
        t.prejmi(new Tretja.Docent(), "doc_Ok4Y9");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_jvRhG");
        t.prejmi(new Tretja.Profesor(), "prof_cANJe");
        t.prejmi(new Tretja.Docent(), "doc_4sh56");
        t.prejmi(new Tretja.Docent(), "doc_M1e9J");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_buaXG");
        t.prejmi(new Tretja.Asistent(), "as_4xpoK");
        t.prejmi(new Tretja.Asistent(), "as_vbVJ6");
        t.prejmi(new Tretja.Docent(), "doc_QSV6L");
        t.prejmi(new Tretja.Asistent(), "as_EJMKS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_krlWQ");
        t.prejmi(new Tretja.Asistent(), "as_BoDbm");
        t.prejmi(new Tretja.Profesor(), "prof_P6FPr");
        t.prejmi(new Tretja.Docent(), "doc_DuhuA");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_Jb5Fg");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_8ghrq");
        t.prejmi(new Tretja.Profesor(), "prof_Mixu0");
        t.prejmi(new Tretja.Docent(), "doc_qSsdv");
        t.prejmi(new Tretja.Asistent(), "as_Ckx4m");
        t.prejmi(new Tretja.Profesor(), "prof_hD0gs");
        t.prejmi(new Tretja.Docent(), "doc_li7NR");
        t.prejmi(new Tretja.Profesor(), "prof_bpe6n");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_sXYkS");
        t.prejmi(new Tretja.Asistent(), "as_jM1nb");
        t.prejmi(new Tretja.Asistent(), "as_Qc3lT");
        t.prejmi(new Tretja.Docent(), "doc_L7Ci5");
        t.prejmi(new Tretja.Profesor(), "prof_LH0nY");
        t.prejmi(new Tretja.Profesor(), "prof_ePWxS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_KWPqf");
        t.prejmi(new Tretja.Profesor(), "prof_uI0q7");
        t.prejmi(new Tretja.Profesor(), "prof_UDUZg");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_jIWpk");
        t.prejmi(new Tretja.Asistent(), "as_wWOzF");
        t.prejmi(new Tretja.Docent(), "doc_PSSpz");
        t.prejmi(new Tretja.Profesor(), "prof_xNhcD");
        t.prejmi(new Tretja.Profesor(), "prof_TNCSv");
        t.prejmi(new Tretja.Profesor(), "prof_i4FIR");
        t.prejmi(new Tretja.Asistent(), "as_DOCRM");
        t.prejmi(new Tretja.Asistent(), "as_OZIRI");
        t.prejmi(new Tretja.Asistent(), "as_1bNZZ");
        t.prejmi(new Tretja.Docent(), "doc_gaHiJ");
        t.prejmi(new Tretja.Profesor(), "prof_U1sc2");
        t.prejmi(new Tretja.Asistent(), "as_ZeGUq");
        t.prejmi(new Tretja.Docent(), "doc_1ZDhl");
        t.prejmi(new Tretja.Asistent(), "as_tth2P");
        t.prejmi(new Tretja.Docent(), "doc_lGYWb");
        t.prejmi(new Tretja.Profesor(), "prof_22Lp6");
        t.prejmi(new Tretja.Docent(), "doc_vU8vq");
        t.prejmi(new Tretja.Asistent(), "as_SmgSB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_hgLNP");
        t.prejmi(new Tretja.Docent(), "doc_e4AYV");
        t.prejmi(new Tretja.Profesor(), "prof_FVl8z");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_bdxXJ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_AEstf");
        t.prejmi(new Tretja.Asistent(), "as_caH50");
        t.prejmi(new Tretja.Docent(), "doc_PLODr");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_tsg5V");
        t.prejmi(new Tretja.Profesor(), "prof_QFoNV");
        t.prejmi(new Tretja.Asistent(), "as_5u3nh");
    }
}
