
public class Test45 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Nl2pt");
        t.prejmi(new Tretja.Asistent(), "as_4cqWU");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GnxyN");
        t.prejmi(new Tretja.Asistent(), "as_GmwYi");
        t.prejmi(new Tretja.Profesor(), "prof_ias9Y");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iwRdg");
        t.prejmi(new Tretja.Docent(), "doc_9aVMD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_yFuza");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_d0dFp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_FAuk0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_M7jLD");
        t.prejmi(new Tretja.Profesor(), "prof_lby4L");
        t.prejmi(new Tretja.Docent(), "doc_Vg1VR");
        t.prejmi(new Tretja.Docent(), "doc_7bO3A");
        t.prejmi(new Tretja.Docent(), "doc_WmhYw");
        t.prejmi(new Tretja.Asistent(), "as_wzpqf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_AlM7T");
        t.prejmi(new Tretja.Profesor(), "prof_tdY9i");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_VncyN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_MYsZL");
        t.prejmi(new Tretja.Docent(), "doc_weysx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_8cAgg");
        t.prejmi(new Tretja.Asistent(), "as_yB7T8");
        t.prejmi(new Tretja.Docent(), "doc_YanUF");
        t.prejmi(new Tretja.Docent(), "doc_LLqCB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vofqf");
        t.prejmi(new Tretja.Profesor(), "prof_qG2vG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_7NOPq");
        t.prejmi(new Tretja.Asistent(), "as_N3Tsp");
        t.prejmi(new Tretja.Docent(), "doc_2oEHo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ZiIte");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_081kF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_f1O4N");
        t.prejmi(new Tretja.Docent(), "doc_nkxxx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_lft8S");
        t.prejmi(new Tretja.Asistent(), "as_gO47X");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fXCM1");
        t.prejmi(new Tretja.Docent(), "doc_2Mf45");
        t.prejmi(new Tretja.Asistent(), "as_Ayd8H");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_FvUym");
        t.prejmi(new Tretja.Profesor(), "prof_7S6tf");
        t.prejmi(new Tretja.Docent(), "doc_HJxaX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Wtqgu");
        t.prejmi(new Tretja.Asistent(), "as_dzI1M");
        t.prejmi(new Tretja.Asistent(), "as_skRnA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_p6GYw");
        t.prejmi(new Tretja.Docent(), "doc_B9tsn");
        t.prejmi(new Tretja.Asistent(), "as_LQVKM");
        t.prejmi(new Tretja.Asistent(), "as_ghvWq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iMZ16");
        t.prejmi(new Tretja.Docent(), "doc_fm7qS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_q7bkW");
        t.prejmi(new Tretja.Asistent(), "as_WTY8m");
        t.prejmi(new Tretja.Asistent(), "as_mozew");
        t.prejmi(new Tretja.Profesor(), "prof_FbswU");
        t.prejmi(new Tretja.Profesor(), "prof_eoOY7");
        t.prejmi(new Tretja.Docent(), "doc_9rUDz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5LJ3C");
        t.prejmi(new Tretja.Docent(), "doc_EiNpv");
        t.prejmi(new Tretja.Profesor(), "prof_ehexp");
        t.prejmi(new Tretja.Profesor(), "prof_Sb1jE");
        t.prejmi(new Tretja.Asistent(), "as_PS5nX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MMRq3");
        t.prejmi(new Tretja.Profesor(), "prof_Pm0Ys");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_CdgU1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_s1v7X");
        t.prejmi(new Tretja.Asistent(), "as_QBGCb");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_dMKT5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_xSHrD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_fvpJV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_fA31K");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_t197R");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1NI3g");
        t.prejmi(new Tretja.Docent(), "doc_6z5KC");
        t.prejmi(new Tretja.Profesor(), "prof_Kz6LU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_6Lh6E");
        t.prejmi(new Tretja.Asistent(), "as_88iKL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_n4dz1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_NBlKG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ba0gJ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w1v9J");
        t.prejmi(new Tretja.Asistent(), "as_nakvJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_AwRBY");
        t.prejmi(new Tretja.Docent(), "doc_mH1T1");
        t.prejmi(new Tretja.Docent(), "doc_3xIMe");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hBXNb");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_LPpBz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_VSpRw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_13ZrL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_50UvB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_0s4bA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3GQZd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_IeX3D");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ef9vZ");
        t.prejmi(new Tretja.Profesor(), "prof_8SYPl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_I3W1J");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kdbhR");
        t.prejmi(new Tretja.Docent(), "doc_ijsT9");
        t.prejmi(new Tretja.Asistent(), "as_zYms6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_v6Ilr");
        t.prejmi(new Tretja.Docent(), "doc_RxfcZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_O8ZnP");
        t.prejmi(new Tretja.Asistent(), "as_KCjDr");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_s6hlu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_F0uiW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Xcj5c");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_16QcJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_IwrLP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xIIik");
        t.prejmi(new Tretja.Docent(), "doc_sjMlf");
        t.prejmi(new Tretja.Docent(), "doc_YtcjI");
        t.prejmi(new Tretja.Docent(), "doc_LLBi5");
        t.prejmi(new Tretja.Docent(), "doc_HEKaK");
        t.prejmi(new Tretja.Asistent(), "as_TalPH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vdxQW");
        t.prejmi(new Tretja.Asistent(), "as_JJEBf");
        t.prejmi(new Tretja.Asistent(), "as_YQxdL");
        t.prejmi(new Tretja.Docent(), "doc_NtRqc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_bULmD");
        t.prejmi(new Tretja.Asistent(), "as_ZTtIZ");
        t.prejmi(new Tretja.Asistent(), "as_agM6k");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Qs18P");
        t.prejmi(new Tretja.Profesor(), "prof_LzfYo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_IE0am");
        t.prejmi(new Tretja.Asistent(), "as_Br2q1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_CBPc5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_95JHV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Wr78M");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_agukm");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_OAilo");
        t.prejmi(new Tretja.Profesor(), "prof_IVZwK");
        t.prejmi(new Tretja.Profesor(), "prof_wDG7M");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3lasA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wY0nh");
        t.prejmi(new Tretja.Docent(), "doc_ieF9C");
        t.prejmi(new Tretja.Profesor(), "prof_S4oqB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aGPH1");
        t.prejmi(new Tretja.Docent(), "doc_uHq0e");
        t.prejmi(new Tretja.Docent(), "doc_cj3Hw");
        t.prejmi(new Tretja.Profesor(), "prof_YiP5n");
        t.prejmi(new Tretja.Profesor(), "prof_Rq8d2");
        t.prejmi(new Tretja.Docent(), "doc_NI0QX");
        t.prejmi(new Tretja.Asistent(), "as_EWtuO");
        t.prejmi(new Tretja.Profesor(), "prof_qZsTj");
        t.prejmi(new Tretja.Profesor(), "prof_Ush40");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GxFZy");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_HRfOl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_OpEs3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_edaWP");
        t.prejmi(new Tretja.Profesor(), "prof_UoYgV");
        t.prejmi(new Tretja.Profesor(), "prof_rLC74");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_hoGHx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_8QIC4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pX9Yw");
        t.prejmi(new Tretja.Docent(), "doc_TXo8t");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_eFc8H");
        t.prejmi(new Tretja.Docent(), "doc_EPddT");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_W8urU");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_sodB2");
        t.prejmi(new Tretja.Docent(), "doc_UybF3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wvNuD");
        t.prejmi(new Tretja.Asistent(), "as_eDfHT");
        t.prejmi(new Tretja.Docent(), "doc_EDPYL");
        t.prejmi(new Tretja.Docent(), "doc_vxDwv");
        t.prejmi(new Tretja.Profesor(), "prof_Dz9V0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zAHP9");
        t.prejmi(new Tretja.Asistent(), "as_PHTMm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zivaI");
        t.prejmi(new Tretja.Profesor(), "prof_QanLL");
        t.prejmi(new Tretja.Profesor(), "prof_qZ3iz");
        System.out.println(t.natisni());
    }
}
