
public class Test12 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_ec6Pm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_QPOuR");
        t.prejmi(new Tretja.Docent(), "doc_m0Urp");
        t.prejmi(new Tretja.Profesor(), "prof_LQS06");
        t.prejmi(new Tretja.Asistent(), "as_vPKUR");
        t.prejmi(new Tretja.Profesor(), "prof_l8p9t");
        t.prejmi(new Tretja.Asistent(), "as_BTM96");
        t.prejmi(new Tretja.Docent(), "doc_rIhKt");
        t.prejmi(new Tretja.Profesor(), "prof_sPp7x");
        t.prejmi(new Tretja.Docent(), "doc_yhZAh");
        t.prejmi(new Tretja.Profesor(), "prof_SVWBI");
        t.prejmi(new Tretja.Asistent(), "as_ElwPu");
        t.prejmi(new Tretja.Asistent(), "as_6Z1s8");
        t.prejmi(new Tretja.Asistent(), "as_25TbI");
        t.prejmi(new Tretja.Asistent(), "as_V6JbC");
        t.prejmi(new Tretja.Asistent(), "as_xN8O3");
        t.prejmi(new Tretja.Profesor(), "prof_Fw1Iz");
        t.prejmi(new Tretja.Docent(), "doc_uBEx4");
        t.prejmi(new Tretja.Docent(), "doc_UCPDj");
        t.prejmi(new Tretja.Profesor(), "prof_lLUd9");
        t.prejmi(new Tretja.Docent(), "doc_UM8S6");
        t.prejmi(new Tretja.Asistent(), "as_aChp3");
        t.prejmi(new Tretja.Asistent(), "as_ZeMga");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_nWc2O");
        t.prejmi(new Tretja.Asistent(), "as_9rlpa");
        t.prejmi(new Tretja.Docent(), "doc_SxzaB");
        t.prejmi(new Tretja.Profesor(), "prof_Arn6o");
        t.prejmi(new Tretja.Profesor(), "prof_yORHV");
        t.prejmi(new Tretja.Profesor(), "prof_CPm9D");
        t.prejmi(new Tretja.Asistent(), "as_OfRCV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_OEGiB");
        t.prejmi(new Tretja.Asistent(), "as_fNt2A");
        t.prejmi(new Tretja.Docent(), "doc_c0ZyN");
        t.prejmi(new Tretja.Docent(), "doc_P3wWb");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_S7nHQ");
        t.prejmi(new Tretja.Asistent(), "as_rXqDe");
        t.prejmi(new Tretja.Profesor(), "prof_b47Xj");
        t.prejmi(new Tretja.Docent(), "doc_eflSD");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_3Qs3V");
        t.prejmi(new Tretja.Docent(), "doc_6TMmr");
        t.prejmi(new Tretja.Profesor(), "prof_AFJyv");
        t.prejmi(new Tretja.Docent(), "doc_by2Fg");
        t.prejmi(new Tretja.Profesor(), "prof_5eomk");
        t.prejmi(new Tretja.Profesor(), "prof_rMCwH");
        t.prejmi(new Tretja.Docent(), "doc_jXE0O");
        t.prejmi(new Tretja.Asistent(), "as_2qG4U");
        t.prejmi(new Tretja.Profesor(), "prof_BJFOA");
        t.prejmi(new Tretja.Asistent(), "as_ZcAWf");
        t.prejmi(new Tretja.Profesor(), "prof_yR8rZ");
        t.prejmi(new Tretja.Docent(), "doc_S2QBG");
        t.prejmi(new Tretja.Asistent(), "as_qgUEs");
        t.prejmi(new Tretja.Asistent(), "as_WE7T2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_8Ct6t");
        t.prejmi(new Tretja.Profesor(), "prof_s8Jti");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_AtxuN");
        t.prejmi(new Tretja.Docent(), "doc_mR1RR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_8ig6r");
        t.prejmi(new Tretja.Asistent(), "as_aBp5q");
        t.prejmi(new Tretja.Docent(), "doc_1bWnP");
        t.prejmi(new Tretja.Docent(), "doc_Zc90u");
        t.prejmi(new Tretja.Docent(), "doc_oP535");
        t.prejmi(new Tretja.Docent(), "doc_X509R");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_lmOaj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_htBy4");
        t.prejmi(new Tretja.Profesor(), "prof_pZ62J");
        t.prejmi(new Tretja.Profesor(), "prof_LPmtY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_EPKoW");
        t.prejmi(new Tretja.Docent(), "doc_HYOOt");
        t.prejmi(new Tretja.Profesor(), "prof_aUekA");
        t.prejmi(new Tretja.Profesor(), "prof_CnrUc");
        t.prejmi(new Tretja.Profesor(), "prof_PP242");
        t.prejmi(new Tretja.Profesor(), "prof_85EiZ");
        t.prejmi(new Tretja.Profesor(), "prof_KShC5");
        t.prejmi(new Tretja.Docent(), "doc_Ucrqm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_LvUuC");
        t.prejmi(new Tretja.Profesor(), "prof_lx7bW");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_zZ6I3");
        t.prejmi(new Tretja.Profesor(), "prof_jH4eB");
        t.prejmi(new Tretja.Profesor(), "prof_QyvFl");
        t.prejmi(new Tretja.Profesor(), "prof_xJzzE");
        t.prejmi(new Tretja.Asistent(), "as_BAtYB");
        t.prejmi(new Tretja.Docent(), "doc_CpBty");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_RWg1d");
        t.prejmi(new Tretja.Asistent(), "as_FuLqe");
        t.prejmi(new Tretja.Profesor(), "prof_GmFEt");
        t.prejmi(new Tretja.Profesor(), "prof_tcT1F");
        t.prejmi(new Tretja.Docent(), "doc_k6pRX");
        t.prejmi(new Tretja.Docent(), "doc_xm2E9");
        t.prejmi(new Tretja.Docent(), "doc_kJTvu");
        t.prejmi(new Tretja.Profesor(), "prof_wwqRD");
        t.prejmi(new Tretja.Profesor(), "prof_Gdl7Y");
        t.prejmi(new Tretja.Asistent(), "as_TCUtM");
        t.prejmi(new Tretja.Asistent(), "as_n5VyR");
        t.prejmi(new Tretja.Profesor(), "prof_ypbPY");
        t.prejmi(new Tretja.Profesor(), "prof_aXvkw");
        t.prejmi(new Tretja.Docent(), "doc_V7n1m");
        t.prejmi(new Tretja.Asistent(), "as_uFXHq");
        t.prejmi(new Tretja.Profesor(), "prof_Wtxcq");
        t.prejmi(new Tretja.Asistent(), "as_CrXbo");
        t.prejmi(new Tretja.Profesor(), "prof_y7J0f");
        t.prejmi(new Tretja.Docent(), "doc_xwrrP");
        t.prejmi(new Tretja.Profesor(), "prof_aZ6v6");
        t.prejmi(new Tretja.Profesor(), "prof_Skb0T");
        t.prejmi(new Tretja.Docent(), "doc_MQboS");
        t.prejmi(new Tretja.Profesor(), "prof_mBXbm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_bk1SW");
        t.prejmi(new Tretja.Profesor(), "prof_qqRJU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_gByt1");
        t.prejmi(new Tretja.Docent(), "doc_CwR0v");
        t.prejmi(new Tretja.Docent(), "doc_2NvgN");
        t.prejmi(new Tretja.Docent(), "doc_4d0PD");
        t.prejmi(new Tretja.Profesor(), "prof_kuEbr");
        t.prejmi(new Tretja.Profesor(), "prof_TQNq6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_wWkjN");
        t.prejmi(new Tretja.Docent(), "doc_wRvdy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_p0vW8");
        t.prejmi(new Tretja.Asistent(), "as_f4oAL");
        t.prejmi(new Tretja.Asistent(), "as_MWYSh");
        t.prejmi(new Tretja.Docent(), "doc_ZL5Jq");
        t.prejmi(new Tretja.Profesor(), "prof_6wyYD");
        t.prejmi(new Tretja.Docent(), "doc_Q4eeS");
        t.prejmi(new Tretja.Docent(), "doc_bkwPQ");
        t.prejmi(new Tretja.Profesor(), "prof_EBCxa");
        t.prejmi(new Tretja.Profesor(), "prof_MIIZr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_PQwT7");
        t.prejmi(new Tretja.Profesor(), "prof_VxmG6");
        t.prejmi(new Tretja.Asistent(), "as_KzNUr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_RYtqx");
        t.prejmi(new Tretja.Profesor(), "prof_NWPL7");
        t.prejmi(new Tretja.Docent(), "doc_i5zcV");
        t.prejmi(new Tretja.Profesor(), "prof_NhQbP");
        t.prejmi(new Tretja.Profesor(), "prof_HARAR");
        t.prejmi(new Tretja.Profesor(), "prof_eoHWK");
        t.prejmi(new Tretja.Profesor(), "prof_qAV3Q");
        t.prejmi(new Tretja.Docent(), "doc_rcUOa");
        t.prejmi(new Tretja.Asistent(), "as_M8qKK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_XUHYX");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ZyLzS");
        t.prejmi(new Tretja.Profesor(), "prof_RYkiq");
        t.prejmi(new Tretja.Docent(), "doc_EPdgZ");
        t.prejmi(new Tretja.Asistent(), "as_8s5ZQ");
        t.prejmi(new Tretja.Docent(), "doc_bxmEc");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_03vg2");
        t.prejmi(new Tretja.Profesor(), "prof_2iYkf");
        t.prejmi(new Tretja.Asistent(), "as_YJ5BS");
        t.prejmi(new Tretja.Profesor(), "prof_I8dEl");
        t.prejmi(new Tretja.Docent(), "doc_q8K7w");
        t.prejmi(new Tretja.Asistent(), "as_0zOUA");
        t.prejmi(new Tretja.Docent(), "doc_JVx1L");
        t.prejmi(new Tretja.Asistent(), "as_ziODB");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_QzlU4");
        t.prejmi(new Tretja.Docent(), "doc_Y1DD8");
        t.prejmi(new Tretja.Docent(), "doc_MqtZg");
        t.prejmi(new Tretja.Docent(), "doc_eLjQa");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_eUUhN");
        t.prejmi(new Tretja.Asistent(), "as_2fEHf");
        t.prejmi(new Tretja.Docent(), "doc_7sEo4");
        t.prejmi(new Tretja.Asistent(), "as_pzjK9");
        t.prejmi(new Tretja.Asistent(), "as_2Qg3p");
        t.prejmi(new Tretja.Profesor(), "prof_8zQVk");
        t.prejmi(new Tretja.Profesor(), "prof_orf7R");
        t.prejmi(new Tretja.Docent(), "doc_TFwWD");
        t.prejmi(new Tretja.Docent(), "doc_WJ0D7");
        t.prejmi(new Tretja.Docent(), "doc_h4oTJ");
        t.prejmi(new Tretja.Docent(), "doc_Ri9ky");
        t.prejmi(new Tretja.Profesor(), "prof_LU4sF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_McsbO");
        t.prejmi(new Tretja.Asistent(), "as_GCNtd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_z1M0Q");
        t.prejmi(new Tretja.Profesor(), "prof_ZFDKS");
        t.prejmi(new Tretja.Asistent(), "as_bnPtR");
        t.prejmi(new Tretja.Asistent(), "as_yaB6z");
        t.prejmi(new Tretja.Docent(), "doc_xNN0e");
        t.prejmi(new Tretja.Docent(), "doc_9XTCK");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ATmTD");
        t.prejmi(new Tretja.Docent(), "doc_gqjiQ");
        t.prejmi(new Tretja.Profesor(), "prof_MtAz6");
        t.prejmi(new Tretja.Docent(), "doc_E15cU");
        t.prejmi(new Tretja.Docent(), "doc_tpDVg");
        t.prejmi(new Tretja.Asistent(), "as_wpfaM");
        t.prejmi(new Tretja.Profesor(), "prof_yAdjR");
        t.prejmi(new Tretja.Profesor(), "prof_ETPqs");
        t.prejmi(new Tretja.Asistent(), "as_2oAnj");
        t.prejmi(new Tretja.Asistent(), "as_xLSjh");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_5y1iy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_kgssX");
        t.prejmi(new Tretja.Asistent(), "as_So6Wr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_h5Mou");
        t.prejmi(new Tretja.Asistent(), "as_3qzxk");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Up7PW");
        t.prejmi(new Tretja.Profesor(), "prof_taJrR");
        t.prejmi(new Tretja.Profesor(), "prof_WsLHp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_VhfEq");
        t.prejmi(new Tretja.Profesor(), "prof_5zgNA");
        t.prejmi(new Tretja.Docent(), "doc_zlcko");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_eReIp");
        t.prejmi(new Tretja.Docent(), "doc_PwHPn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Pf5KB");
        t.prejmi(new Tretja.Profesor(), "prof_BNoj1");
        t.prejmi(new Tretja.Asistent(), "as_9SNBL");
        t.prejmi(new Tretja.Profesor(), "prof_jUes6");
        t.prejmi(new Tretja.Asistent(), "as_tz0H8");
        t.prejmi(new Tretja.Profesor(), "prof_cGPhb");
        t.prejmi(new Tretja.Profesor(), "prof_yCIn9");
        t.prejmi(new Tretja.Profesor(), "prof_FGgIM");
        t.prejmi(new Tretja.Profesor(), "prof_gZMxK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_TNjFZ");
        t.prejmi(new Tretja.Profesor(), "prof_g4riY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_xlqfZ");
        t.prejmi(new Tretja.Docent(), "doc_WjyoZ");
        t.prejmi(new Tretja.Profesor(), "prof_nXSaS");
        t.prejmi(new Tretja.Asistent(), "as_gr2Kx");
        t.prejmi(new Tretja.Docent(), "doc_pwJsS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_OEn35");
        t.prejmi(new Tretja.Profesor(), "prof_bKB51");
        t.prejmi(new Tretja.Profesor(), "prof_a45ol");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_HCei8");
        t.prejmi(new Tretja.Asistent(), "as_18LtP");
        t.prejmi(new Tretja.Profesor(), "prof_B6A3r");
        t.prejmi(new Tretja.Profesor(), "prof_awhTr");
        t.prejmi(new Tretja.Asistent(), "as_8TO1z");
        t.prejmi(new Tretja.Profesor(), "prof_tGMng");
        t.prejmi(new Tretja.Asistent(), "as_6TS2m");
        t.prejmi(new Tretja.Profesor(), "prof_1T6I9");
        t.prejmi(new Tretja.Profesor(), "prof_vB8P9");
        t.prejmi(new Tretja.Asistent(), "as_E6BIs");
        t.prejmi(new Tretja.Asistent(), "as_enXKx");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_SipDq");
        t.prejmi(new Tretja.Profesor(), "prof_zfIWN");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1EkHD");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_1EF38");
        t.prejmi(new Tretja.Profesor(), "prof_ORESn");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_7uIKp");
        t.prejmi(new Tretja.Docent(), "doc_J6SlW");
        t.prejmi(new Tretja.Asistent(), "as_sj8td");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_13Jd9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_R6IzV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_8jBlR");
        t.prejmi(new Tretja.Docent(), "doc_PLPAZ");
        t.prejmi(new Tretja.Profesor(), "prof_fbRCO");
        t.prejmi(new Tretja.Asistent(), "as_Y44em");
        t.prejmi(new Tretja.Docent(), "doc_v3M85");
        t.prejmi(new Tretja.Asistent(), "as_TCzlC");
        t.prejmi(new Tretja.Docent(), "doc_gRYKu");
        t.prejmi(new Tretja.Docent(), "doc_3s5Vn");
        t.prejmi(new Tretja.Docent(), "doc_hy58S");
        t.prejmi(new Tretja.Docent(), "doc_08bl2");
        t.prejmi(new Tretja.Docent(), "doc_VlCpV");
        t.prejmi(new Tretja.Docent(), "doc_GkyoM");
        t.prejmi(new Tretja.Profesor(), "prof_VeeGS");
        t.prejmi(new Tretja.Docent(), "doc_DyXLc");
        t.prejmi(new Tretja.Asistent(), "as_VPRNX");
        t.prejmi(new Tretja.Docent(), "doc_yXfOu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_7MGPE");
        t.prejmi(new Tretja.Asistent(), "as_oJ1VW");
        t.prejmi(new Tretja.Profesor(), "prof_DGDA3");
        t.prejmi(new Tretja.Asistent(), "as_qtBxu");
        t.prejmi(new Tretja.Profesor(), "prof_awHv5");
        t.prejmi(new Tretja.Asistent(), "as_7inrG");
        t.prejmi(new Tretja.Docent(), "doc_24bH9");
        t.prejmi(new Tretja.Docent(), "doc_BBeo2");
        t.prejmi(new Tretja.Asistent(), "as_AB80a");
        t.prejmi(new Tretja.Docent(), "doc_siCvS");
        t.prejmi(new Tretja.Asistent(), "as_gYQol");
        t.prejmi(new Tretja.Profesor(), "prof_pJzCz");
        t.prejmi(new Tretja.Profesor(), "prof_oyx2i");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_EV9Es");
        t.prejmi(new Tretja.Docent(), "doc_BqSgv");
        t.prejmi(new Tretja.Profesor(), "prof_e1ced");
        t.prejmi(new Tretja.Asistent(), "as_IBPgX");
        t.prejmi(new Tretja.Docent(), "doc_bB9zI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_uGfUm");
        t.prejmi(new Tretja.Docent(), "doc_nnUSf");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_B1pfJ");
        t.prejmi(new Tretja.Profesor(), "prof_TVHr1");
        t.prejmi(new Tretja.Profesor(), "prof_YMV7X");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ZOg3K");
        t.prejmi(new Tretja.Profesor(), "prof_Cwfvi");
        t.prejmi(new Tretja.Docent(), "doc_xHuZO");
        t.prejmi(new Tretja.Docent(), "doc_lMERH");
        t.prejmi(new Tretja.Docent(), "doc_iACX7");
        t.prejmi(new Tretja.Docent(), "doc_xot69");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_AHR24");
        t.prejmi(new Tretja.Asistent(), "as_PALFa");
        t.prejmi(new Tretja.Asistent(), "as_B5aTf");
        t.prejmi(new Tretja.Profesor(), "prof_vFHkg");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_rrBu6");
        t.prejmi(new Tretja.Docent(), "doc_TDmzT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_5iDBs");
        t.prejmi(new Tretja.Docent(), "doc_Ql3Ic");
        t.prejmi(new Tretja.Docent(), "doc_P44EZ");
        t.prejmi(new Tretja.Asistent(), "as_95xRg");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_qmYDT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_hjJQb");
        t.prejmi(new Tretja.Profesor(), "prof_SMKTg");
        t.prejmi(new Tretja.Docent(), "doc_umYAk");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_kFLqw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_4sfoh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_MBSZO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_i0YXy");
        t.prejmi(new Tretja.Profesor(), "prof_WwkRV");
        t.prejmi(new Tretja.Asistent(), "as_d5zMq");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_hu2E3");
        t.prejmi(new Tretja.Docent(), "doc_0FLTg");
        t.prejmi(new Tretja.Asistent(), "as_kZYk6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_9QX8W");
        t.prejmi(new Tretja.Asistent(), "as_bTgkB");
        t.prejmi(new Tretja.Profesor(), "prof_1yL7R");
        t.prejmi(new Tretja.Docent(), "doc_BUtaI");
        t.prejmi(new Tretja.Docent(), "doc_LTvu2");
        t.prejmi(new Tretja.Profesor(), "prof_gK1Nw");
        t.prejmi(new Tretja.Profesor(), "prof_NUi9D");
        t.prejmi(new Tretja.Docent(), "doc_8INra");
        t.prejmi(new Tretja.Profesor(), "prof_2Ulue");
        t.prejmi(new Tretja.Profesor(), "prof_T5CVH");
        t.prejmi(new Tretja.Asistent(), "as_aWIN1");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Tj1zk");
        t.prejmi(new Tretja.Profesor(), "prof_cSw1P");
        t.prejmi(new Tretja.Docent(), "doc_VpNU1");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1MFEU");
        t.prejmi(new Tretja.Asistent(), "as_XC0uC");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_u5BPU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_uW6U0");
        t.prejmi(new Tretja.Asistent(), "as_qaZQe");
        t.prejmi(new Tretja.Asistent(), "as_jqU6A");
        t.prejmi(new Tretja.Profesor(), "prof_TphJv");
        t.prejmi(new Tretja.Asistent(), "as_Us1Rc");
        t.prejmi(new Tretja.Docent(), "doc_DIsOm");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_8LghY");
        t.prejmi(new Tretja.Docent(), "doc_zFaqj");
        t.prejmi(new Tretja.Profesor(), "prof_juHhT");
        t.prejmi(new Tretja.Docent(), "doc_IwPbF");
        t.prejmi(new Tretja.Profesor(), "prof_JAUL1");
        t.prejmi(new Tretja.Docent(), "doc_pHC8u");
        t.prejmi(new Tretja.Profesor(), "prof_81fbM");
        t.prejmi(new Tretja.Docent(), "doc_3cYdu");
        t.prejmi(new Tretja.Docent(), "doc_cGcbI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_IVMaQ");
        t.prejmi(new Tretja.Docent(), "doc_MFhbJ");
        t.prejmi(new Tretja.Docent(), "doc_lKZNX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_LuK7Z");
        t.prejmi(new Tretja.Asistent(), "as_MwvID");
        t.prejmi(new Tretja.Docent(), "doc_Vd4Mz");
        t.prejmi(new Tretja.Docent(), "doc_gI5QQ");
        t.prejmi(new Tretja.Docent(), "doc_SDeIV");
        t.prejmi(new Tretja.Profesor(), "prof_DDwtq");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Uye2x");
        t.prejmi(new Tretja.Docent(), "doc_03vTO");
        t.prejmi(new Tretja.Asistent(), "as_IL7hI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_c0IUT");
        t.prejmi(new Tretja.Asistent(), "as_DIO4K");
        t.prejmi(new Tretja.Asistent(), "as_eO2YE");
        t.prejmi(new Tretja.Profesor(), "prof_wInup");
        t.prejmi(new Tretja.Asistent(), "as_Xqe7z");
        t.prejmi(new Tretja.Asistent(), "as_uObll");
        t.prejmi(new Tretja.Asistent(), "as_SmG2o");
        t.prejmi(new Tretja.Profesor(), "prof_zs9T0");
        t.prejmi(new Tretja.Asistent(), "as_TEqbA");
        t.prejmi(new Tretja.Docent(), "doc_mzezU");
        t.prejmi(new Tretja.Profesor(), "prof_pmyYM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ar4Ri");
        t.prejmi(new Tretja.Asistent(), "as_3NNrb");
        t.prejmi(new Tretja.Profesor(), "prof_Wu9Od");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_xN5zB");
        t.prejmi(new Tretja.Docent(), "doc_ZaUn8");
        t.prejmi(new Tretja.Profesor(), "prof_BWinX");
        t.prejmi(new Tretja.Docent(), "doc_nOoQV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_RuaiT");
        t.prejmi(new Tretja.Asistent(), "as_BWLTM");
        t.prejmi(new Tretja.Docent(), "doc_1CSy4");
        t.prejmi(new Tretja.Docent(), "doc_VTiyl");
        t.prejmi(new Tretja.Asistent(), "as_osNhZ");
        t.prejmi(new Tretja.Asistent(), "as_Sz0I4");
        t.prejmi(new Tretja.Profesor(), "prof_SpmaO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_wNpod");
        t.prejmi(new Tretja.Asistent(), "as_25uMO");
        t.prejmi(new Tretja.Asistent(), "as_S9txy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Tizgm");
        t.prejmi(new Tretja.Profesor(), "prof_znBCl");
        t.prejmi(new Tretja.Docent(), "doc_bE1wY");
        t.prejmi(new Tretja.Asistent(), "as_jC5BF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_7ay6G");
        t.prejmi(new Tretja.Asistent(), "as_DmhTh");
        t.prejmi(new Tretja.Profesor(), "prof_aRqTx");
        t.prejmi(new Tretja.Asistent(), "as_jXaNC");
        t.prejmi(new Tretja.Asistent(), "as_vN171");
        t.prejmi(new Tretja.Profesor(), "prof_wxA70");
        t.prejmi(new Tretja.Profesor(), "prof_Ic727");
        t.prejmi(new Tretja.Docent(), "doc_PKnPk");
        t.prejmi(new Tretja.Docent(), "doc_gUK75");
        t.prejmi(new Tretja.Asistent(), "as_5beDY");
        t.prejmi(new Tretja.Docent(), "doc_pJgzK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ZI4gj");
        t.prejmi(new Tretja.Docent(), "doc_w4UGA");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_xC2XV");
        t.prejmi(new Tretja.Asistent(), "as_mXaFS");
        t.prejmi(new Tretja.Profesor(), "prof_H7ufL");
        t.prejmi(new Tretja.Docent(), "doc_g1e0V");
        t.prejmi(new Tretja.Asistent(), "as_DM8Ys");
        t.prejmi(new Tretja.Profesor(), "prof_voDHZ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_UOyNz");
        t.prejmi(new Tretja.Docent(), "doc_6HlKv");
        t.prejmi(new Tretja.Profesor(), "prof_VNjiO");
        t.prejmi(new Tretja.Docent(), "doc_1vg51");
        t.prejmi(new Tretja.Asistent(), "as_CVJnl");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_EY91R");
        t.prejmi(new Tretja.Profesor(), "prof_hA4XP");
        t.prejmi(new Tretja.Asistent(), "as_HTREk");
        t.prejmi(new Tretja.Profesor(), "prof_1S3AC");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_F6oNX");
        t.prejmi(new Tretja.Asistent(), "as_wXv3A");
        t.prejmi(new Tretja.Docent(), "doc_YGL7A");
        t.prejmi(new Tretja.Asistent(), "as_N86FS");
        t.prejmi(new Tretja.Asistent(), "as_gvYDT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ltA4P");
        t.prejmi(new Tretja.Asistent(), "as_uNUDe");
        t.prejmi(new Tretja.Docent(), "doc_xn4Y0");
        t.prejmi(new Tretja.Asistent(), "as_PqpqY");
        t.prejmi(new Tretja.Profesor(), "prof_pzZ3B");
        t.prejmi(new Tretja.Profesor(), "prof_FrrCW");
        t.prejmi(new Tretja.Asistent(), "as_jcGF5");
        t.prejmi(new Tretja.Asistent(), "as_DLWqi");
        t.prejmi(new Tretja.Profesor(), "prof_zHYOb");
        t.prejmi(new Tretja.Docent(), "doc_uFgPK");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_YyLtx");
        t.prejmi(new Tretja.Asistent(), "as_VNHRh");
        t.prejmi(new Tretja.Docent(), "doc_9kB6T");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_qHYhu");
        t.prejmi(new Tretja.Docent(), "doc_ZRTYJ");
        t.prejmi(new Tretja.Docent(), "doc_3u525");
        t.prejmi(new Tretja.Asistent(), "as_poYfK");
        t.prejmi(new Tretja.Docent(), "doc_LF4sf");
        t.prejmi(new Tretja.Asistent(), "as_bg57p");
    }
}
