
public class Test46 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_jI8tO");
        t.prejmi(new Tretja.Profesor(), "prof_RNsPL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_NPVmh");
        t.prejmi(new Tretja.Profesor(), "prof_XbMkP");
        t.prejmi(new Tretja.Asistent(), "as_nDyCs");
        t.prejmi(new Tretja.Profesor(), "prof_ebgoZ");
        t.prejmi(new Tretja.Profesor(), "prof_ZKaUX");
        t.prejmi(new Tretja.Asistent(), "as_EfGgL");
        t.prejmi(new Tretja.Docent(), "doc_u071W");
        t.prejmi(new Tretja.Profesor(), "prof_i0l3Q");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_eNsQG");
        t.prejmi(new Tretja.Asistent(), "as_yysxG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vNnRT");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_YVj43");
        t.prejmi(new Tretja.Docent(), "doc_QlJOW");
        t.prejmi(new Tretja.Asistent(), "as_3p8ct");
        t.prejmi(new Tretja.Asistent(), "as_335f5");
        t.prejmi(new Tretja.Asistent(), "as_BgPBZ");
        t.prejmi(new Tretja.Asistent(), "as_6xAJr");
        t.prejmi(new Tretja.Docent(), "doc_w3Qnl");
        t.prejmi(new Tretja.Docent(), "doc_Yy7KF");
        t.prejmi(new Tretja.Docent(), "doc_TH1gs");
        t.prejmi(new Tretja.Asistent(), "as_LpENO");
        t.prejmi(new Tretja.Asistent(), "as_e8o0e");
        t.prejmi(new Tretja.Docent(), "doc_iE2mg");
        t.prejmi(new Tretja.Profesor(), "prof_NE9sO");
        t.prejmi(new Tretja.Profesor(), "prof_09TSX");
        t.prejmi(new Tretja.Asistent(), "as_ZEpuw");
        t.prejmi(new Tretja.Profesor(), "prof_RfMmR");
        t.prejmi(new Tretja.Docent(), "doc_JdiXZ");
        t.prejmi(new Tretja.Docent(), "doc_KTieK");
        t.prejmi(new Tretja.Profesor(), "prof_OwqWo");
        t.prejmi(new Tretja.Asistent(), "as_Lc3Gr");
        t.prejmi(new Tretja.Profesor(), "prof_8fShc");
        t.prejmi(new Tretja.Asistent(), "as_BU1GY");
        t.prejmi(new Tretja.Asistent(), "as_Z1Yof");
        t.prejmi(new Tretja.Profesor(), "prof_dLIWn");
        t.prejmi(new Tretja.Docent(), "doc_5CaAN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ZDr5F");
        t.prejmi(new Tretja.Asistent(), "as_q87LB");
        t.prejmi(new Tretja.Docent(), "doc_TQnO5");
        t.prejmi(new Tretja.Docent(), "doc_DPDGf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_QmV53");
        t.prejmi(new Tretja.Docent(), "doc_hSGuj");
        t.prejmi(new Tretja.Docent(), "doc_mfPRd");
        t.prejmi(new Tretja.Asistent(), "as_J0TBq");
        t.prejmi(new Tretja.Docent(), "doc_Li6BL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_A9EdR");
        t.prejmi(new Tretja.Asistent(), "as_5FDkS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6roEa");
        t.prejmi(new Tretja.Profesor(), "prof_BF8WS");
        t.prejmi(new Tretja.Profesor(), "prof_snpMe");
        t.prejmi(new Tretja.Docent(), "doc_6TDb2");
        t.prejmi(new Tretja.Profesor(), "prof_OKO8K");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wI4xZ");
        t.prejmi(new Tretja.Docent(), "doc_FIphP");
        t.prejmi(new Tretja.Docent(), "doc_HxqT9");
        t.prejmi(new Tretja.Docent(), "doc_wfJt8");
        t.prejmi(new Tretja.Docent(), "doc_Q8TOC");
        t.prejmi(new Tretja.Asistent(), "as_mPKP3");
        t.prejmi(new Tretja.Docent(), "doc_o33sm");
        t.prejmi(new Tretja.Profesor(), "prof_6U32f");
        t.prejmi(new Tretja.Docent(), "doc_TRDEz");
        t.prejmi(new Tretja.Asistent(), "as_QDJd6");
        t.prejmi(new Tretja.Asistent(), "as_hY4Hb");
        t.prejmi(new Tretja.Profesor(), "prof_y5qfR");
        t.prejmi(new Tretja.Asistent(), "as_2VY0R");
        t.prejmi(new Tretja.Docent(), "doc_Ff3wB");
        t.prejmi(new Tretja.Asistent(), "as_71Td5");
        t.prejmi(new Tretja.Docent(), "doc_qDPHf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_gFGES");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w7HQJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ktBxe");
        t.prejmi(new Tretja.Docent(), "doc_oFg41");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Ig2vD");
        t.prejmi(new Tretja.Asistent(), "as_sCx8Q");
        t.prejmi(new Tretja.Profesor(), "prof_TErcQ");
        t.prejmi(new Tretja.Docent(), "doc_OIBhk");
        t.prejmi(new Tretja.Docent(), "doc_4DRJV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_jyWOd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_L39CC");
        t.prejmi(new Tretja.Asistent(), "as_z7kuy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1GwcA");
        t.prejmi(new Tretja.Profesor(), "prof_ROpbX");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_kbvvC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4knAU");
        t.prejmi(new Tretja.Docent(), "doc_zcWyH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lV3xH");
        t.prejmi(new Tretja.Asistent(), "as_JkfiT");
        t.prejmi(new Tretja.Docent(), "doc_VVSJE");
        t.prejmi(new Tretja.Asistent(), "as_6x8lA");
        t.prejmi(new Tretja.Asistent(), "as_peh2l");
        t.prejmi(new Tretja.Asistent(), "as_PxXcU");
        t.prejmi(new Tretja.Docent(), "doc_ywQ8V");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_GIFqA");
        t.prejmi(new Tretja.Asistent(), "as_4R9pk");
        t.prejmi(new Tretja.Profesor(), "prof_fXFqF");
        t.prejmi(new Tretja.Profesor(), "prof_9RYkF");
        t.prejmi(new Tretja.Docent(), "doc_DKdrX");
        t.prejmi(new Tretja.Profesor(), "prof_DiQpf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7WrP0");
        t.prejmi(new Tretja.Asistent(), "as_T463v");
        t.prejmi(new Tretja.Asistent(), "as_FA4mY");
        t.prejmi(new Tretja.Asistent(), "as_jyISJ");
        t.prejmi(new Tretja.Asistent(), "as_TH7qW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5hV6X");
        t.prejmi(new Tretja.Docent(), "doc_J3Mcm");
        t.prejmi(new Tretja.Asistent(), "as_5at5E");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bJ8Xo");
        t.prejmi(new Tretja.Profesor(), "prof_irlu4");
        t.prejmi(new Tretja.Profesor(), "prof_mcCCc");
        t.prejmi(new Tretja.Profesor(), "prof_cP7Wt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_WxVK9");
        t.prejmi(new Tretja.Asistent(), "as_nYqUS");
        t.prejmi(new Tretja.Asistent(), "as_4wSvy");
        t.prejmi(new Tretja.Profesor(), "prof_bMmri");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MrUel");
        t.prejmi(new Tretja.Docent(), "doc_xU7xz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_8PhV0");
        t.prejmi(new Tretja.Docent(), "doc_Bx0WM");
        t.prejmi(new Tretja.Profesor(), "prof_FrEuR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_61niJ");
        t.prejmi(new Tretja.Docent(), "doc_tV4Ay");
        t.prejmi(new Tretja.Profesor(), "prof_7fsPV");
        t.prejmi(new Tretja.Docent(), "doc_wnCP0");
        t.prejmi(new Tretja.Profesor(), "prof_CqIjL");
        t.prejmi(new Tretja.Docent(), "doc_Ha3DP");
        t.prejmi(new Tretja.Profesor(), "prof_FhxMe");
        t.prejmi(new Tretja.Docent(), "doc_oo0ZP");
        t.prejmi(new Tretja.Docent(), "doc_UKNP9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aP1A8");
        t.prejmi(new Tretja.Asistent(), "as_MDFt6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_9Qc7x");
        t.prejmi(new Tretja.Docent(), "doc_Rn0BP");
        t.prejmi(new Tretja.Asistent(), "as_qXHgA");
        t.prejmi(new Tretja.Profesor(), "prof_Gw87a");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_iT9Ty");
        t.prejmi(new Tretja.Profesor(), "prof_5boSs");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_obzTK");
        t.prejmi(new Tretja.Asistent(), "as_AgqZ8");
        t.prejmi(new Tretja.Asistent(), "as_x2uuu");
        t.prejmi(new Tretja.Asistent(), "as_Qw59P");
        t.prejmi(new Tretja.Asistent(), "as_2adWI");
        t.prejmi(new Tretja.Asistent(), "as_OPSlL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_FiRjx");
        t.prejmi(new Tretja.Docent(), "doc_ehovP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_IuWOg");
        t.prejmi(new Tretja.Asistent(), "as_pWkOE");
        t.prejmi(new Tretja.Profesor(), "prof_AU3EB");
        t.prejmi(new Tretja.Docent(), "doc_hrdfu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NdRN5");
        t.prejmi(new Tretja.Profesor(), "prof_BIMpr");
        t.prejmi(new Tretja.Profesor(), "prof_URMWF");
        t.prejmi(new Tretja.Profesor(), "prof_t3MK9");
        t.prejmi(new Tretja.Docent(), "doc_qSRxQ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_9Uvx9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_cUzhK");
        t.prejmi(new Tretja.Asistent(), "as_uaoYs");
        t.prejmi(new Tretja.Asistent(), "as_kXkDh");
        t.prejmi(new Tretja.Docent(), "doc_rUNmv");
        t.prejmi(new Tretja.Asistent(), "as_EaUIb");
        t.prejmi(new Tretja.Asistent(), "as_7dnNr");
        t.prejmi(new Tretja.Docent(), "doc_5vWN8");
        t.prejmi(new Tretja.Profesor(), "prof_RvM7i");
        t.prejmi(new Tretja.Docent(), "doc_xeF29");
        t.prejmi(new Tretja.Profesor(), "prof_Te1EL");
        t.prejmi(new Tretja.Docent(), "doc_qTA1r");
        t.prejmi(new Tretja.Profesor(), "prof_15wB5");
        t.prejmi(new Tretja.Profesor(), "prof_yRAmv");
        t.prejmi(new Tretja.Docent(), "doc_SNRWT");
        t.prejmi(new Tretja.Profesor(), "prof_c6D35");
        t.prejmi(new Tretja.Docent(), "doc_Jp1sc");
        t.prejmi(new Tretja.Asistent(), "as_NLZ6n");
        t.prejmi(new Tretja.Asistent(), "as_desU1");
        t.prejmi(new Tretja.Docent(), "doc_SiPIK");
        t.prejmi(new Tretja.Docent(), "doc_sp6mC");
        t.prejmi(new Tretja.Asistent(), "as_dXD9l");
        t.prejmi(new Tretja.Asistent(), "as_fPCzX");
        t.prejmi(new Tretja.Profesor(), "prof_EOiZc");
        t.prejmi(new Tretja.Docent(), "doc_UA7AP");
        t.prejmi(new Tretja.Asistent(), "as_V9fVF");
        t.prejmi(new Tretja.Docent(), "doc_CwNyR");
        t.prejmi(new Tretja.Docent(), "doc_Yg5rZ");
        t.prejmi(new Tretja.Docent(), "doc_5gvYa");
        t.prejmi(new Tretja.Profesor(), "prof_TPEOe");
        t.prejmi(new Tretja.Docent(), "doc_1Jfef");
        t.prejmi(new Tretja.Profesor(), "prof_Z9bqk");
        t.prejmi(new Tretja.Profesor(), "prof_NsqGd");
        t.prejmi(new Tretja.Asistent(), "as_DL8Is");
        t.prejmi(new Tretja.Profesor(), "prof_XP9OV");
        t.prejmi(new Tretja.Asistent(), "as_fT1yv");
        t.prejmi(new Tretja.Profesor(), "prof_BIhQt");
        t.prejmi(new Tretja.Asistent(), "as_BeV7f");
        t.prejmi(new Tretja.Docent(), "doc_mUT1L");
        t.prejmi(new Tretja.Asistent(), "as_Gk4zg");
        t.prejmi(new Tretja.Docent(), "doc_Ndp4j");
        t.prejmi(new Tretja.Profesor(), "prof_3fSxT");
        t.prejmi(new Tretja.Asistent(), "as_p6RlH");
        t.prejmi(new Tretja.Profesor(), "prof_E7hEh");
        t.prejmi(new Tretja.Asistent(), "as_WMKEZ");
        t.prejmi(new Tretja.Asistent(), "as_TsP3l");
        t.prejmi(new Tretja.Docent(), "doc_7LsbE");
        t.prejmi(new Tretja.Asistent(), "as_qt7Qz");
        t.prejmi(new Tretja.Asistent(), "as_3g2s7");
        t.prejmi(new Tretja.Profesor(), "prof_KgBwX");
        t.prejmi(new Tretja.Asistent(), "as_66t5c");
        t.prejmi(new Tretja.Docent(), "doc_ZjDao");
        t.prejmi(new Tretja.Profesor(), "prof_AM8Hk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_LdxOw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_s9TXd");
        t.prejmi(new Tretja.Profesor(), "prof_9VDok");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TMcQj");
        t.prejmi(new Tretja.Docent(), "doc_JDSpH");
        t.prejmi(new Tretja.Asistent(), "as_f4FX4");
        t.prejmi(new Tretja.Asistent(), "as_9bMvg");
        t.prejmi(new Tretja.Docent(), "doc_KKRJX");
        t.prejmi(new Tretja.Asistent(), "as_ZiPXW");
        t.prejmi(new Tretja.Profesor(), "prof_y60kT");
        t.prejmi(new Tretja.Profesor(), "prof_EvQcK");
        t.prejmi(new Tretja.Asistent(), "as_Gevgc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_A5hGJ");
    }
}
