
public class Test47 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_2s43f");
        t.prejmi(new Tretja.Docent(), "doc_E3kyM");
        t.prejmi(new Tretja.Docent(), "doc_y8C6h");
        t.prejmi(new Tretja.Asistent(), "as_cO1ew");
        t.prejmi(new Tretja.Asistent(), "as_IWXlF");
        t.prejmi(new Tretja.Profesor(), "prof_juGeS");
        t.prejmi(new Tretja.Profesor(), "prof_iXILH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IxKBA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Se9cn");
        t.prejmi(new Tretja.Asistent(), "as_zuvmp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_IfO5F");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Pc2w1");
        t.prejmi(new Tretja.Asistent(), "as_1GF2J");
        t.prejmi(new Tretja.Asistent(), "as_qng4R");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_T4aEx");
        t.prejmi(new Tretja.Profesor(), "prof_gKPih");
        t.prejmi(new Tretja.Asistent(), "as_3Jdd1");
        t.prejmi(new Tretja.Docent(), "doc_6Psdy");
        t.prejmi(new Tretja.Profesor(), "prof_SrlY6");
        t.prejmi(new Tretja.Profesor(), "prof_D5TZN");
        t.prejmi(new Tretja.Docent(), "doc_n3O9N");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_1f0JV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_T6MqO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9EWgC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_mk2MV");
        t.prejmi(new Tretja.Docent(), "doc_6de6S");
        t.prejmi(new Tretja.Profesor(), "prof_RVaU0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0Qclz");
        t.prejmi(new Tretja.Asistent(), "as_IOehe");
        t.prejmi(new Tretja.Profesor(), "prof_tRrSo");
        t.prejmi(new Tretja.Docent(), "doc_737hF");
        t.prejmi(new Tretja.Docent(), "doc_8LxFS");
        t.prejmi(new Tretja.Docent(), "doc_wprHd");
        t.prejmi(new Tretja.Profesor(), "prof_edlF9");
        t.prejmi(new Tretja.Asistent(), "as_NhMyk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_1hjpn");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_dTSKu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lAQpn");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4HWoL");
        t.prejmi(new Tretja.Profesor(), "prof_QCXTa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ii3yM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_BtbQQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8UbSy");
        t.prejmi(new Tretja.Docent(), "doc_3LjZG");
        t.prejmi(new Tretja.Profesor(), "prof_3inSz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iiQAZ");
        t.prejmi(new Tretja.Docent(), "doc_qUDGn");
        t.prejmi(new Tretja.Profesor(), "prof_OesZB");
        t.prejmi(new Tretja.Asistent(), "as_sJPO3");
        t.prejmi(new Tretja.Docent(), "doc_tWtVy");
        t.prejmi(new Tretja.Docent(), "doc_5jPtd");
        t.prejmi(new Tretja.Docent(), "doc_rxOB8");
        t.prejmi(new Tretja.Asistent(), "as_JSfu0");
        t.prejmi(new Tretja.Asistent(), "as_eHp6l");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ppgoe");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_3pSYe");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_eCDzs");
        t.prejmi(new Tretja.Asistent(), "as_fvJ16");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_s4dFr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_lt4Vo");
        t.prejmi(new Tretja.Profesor(), "prof_DDnoR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_xcNbc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_kTbot");
        t.prejmi(new Tretja.Profesor(), "prof_pyVQp");
        t.prejmi(new Tretja.Docent(), "doc_PlpNH");
        t.prejmi(new Tretja.Asistent(), "as_k7eSv");
        t.prejmi(new Tretja.Docent(), "doc_Xoxlf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IJVLc");
        t.prejmi(new Tretja.Profesor(), "prof_YdsJR");
        t.prejmi(new Tretja.Profesor(), "prof_eVeyL");
        t.prejmi(new Tretja.Docent(), "doc_h4gHI");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_04VrK");
        t.prejmi(new Tretja.Profesor(), "prof_7gdhW");
        t.prejmi(new Tretja.Asistent(), "as_OqIsu");
        t.prejmi(new Tretja.Asistent(), "as_mpUgj");
        t.prejmi(new Tretja.Docent(), "doc_njIUG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_xCe6C");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7D0xW");
        t.prejmi(new Tretja.Asistent(), "as_eJnbQ");
        t.prejmi(new Tretja.Asistent(), "as_MjTLk");
        t.prejmi(new Tretja.Asistent(), "as_hJXvB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0cnmd");
        t.prejmi(new Tretja.Asistent(), "as_l0P3x");
        t.prejmi(new Tretja.Profesor(), "prof_nYV07");
        t.prejmi(new Tretja.Profesor(), "prof_uYziU");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_SpKGS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9YUWB");
        t.prejmi(new Tretja.Profesor(), "prof_W6Bz7");
        t.prejmi(new Tretja.Profesor(), "prof_ZrjhX");
        t.prejmi(new Tretja.Asistent(), "as_TrLak");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_dLK8Y");
        t.prejmi(new Tretja.Docent(), "doc_KBuZn");
        t.prejmi(new Tretja.Asistent(), "as_a2AIp");
        t.prejmi(new Tretja.Asistent(), "as_OjBAa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_N83GK");
        t.prejmi(new Tretja.Profesor(), "prof_e2Hfm");
        t.prejmi(new Tretja.Asistent(), "as_RzMke");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8dTgr");
        t.prejmi(new Tretja.Profesor(), "prof_nMpfw");
        t.prejmi(new Tretja.Asistent(), "as_vE4lj");
        t.prejmi(new Tretja.Docent(), "doc_AQEet");
        t.prejmi(new Tretja.Docent(), "doc_cswpY");
        t.prejmi(new Tretja.Profesor(), "prof_Jsct4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6hvjm");
        t.prejmi(new Tretja.Docent(), "doc_FiDXX");
        t.prejmi(new Tretja.Asistent(), "as_N6hDX");
        t.prejmi(new Tretja.Profesor(), "prof_jpKF5");
        t.prejmi(new Tretja.Docent(), "doc_hsP4P");
        t.prejmi(new Tretja.Docent(), "doc_wDNml");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tjoTR");
        t.prejmi(new Tretja.Asistent(), "as_doGWS");
        t.prejmi(new Tretja.Asistent(), "as_UqDtc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ujXSf");
        t.prejmi(new Tretja.Docent(), "doc_CGQFH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_X0TLX");
        t.prejmi(new Tretja.Profesor(), "prof_lkQlz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_1h6b8");
        t.prejmi(new Tretja.Docent(), "doc_Y1NmQ");
        t.prejmi(new Tretja.Asistent(), "as_KKucE");
        t.prejmi(new Tretja.Asistent(), "as_mf41Y");
        t.prejmi(new Tretja.Asistent(), "as_q8Xl5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_G8EM8");
        t.prejmi(new Tretja.Asistent(), "as_lAoCN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_osTmC");
        t.prejmi(new Tretja.Asistent(), "as_BGAuS");
        t.prejmi(new Tretja.Asistent(), "as_ekKIQ");
        t.prejmi(new Tretja.Profesor(), "prof_P2PVC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QYWx8");
        t.prejmi(new Tretja.Profesor(), "prof_TNjls");
        t.prejmi(new Tretja.Docent(), "doc_hzy4O");
        t.prejmi(new Tretja.Docent(), "doc_InvH7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IT8vo");
        t.prejmi(new Tretja.Profesor(), "prof_fwWOf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_R2Pn2");
        t.prejmi(new Tretja.Asistent(), "as_VRgZE");
        t.prejmi(new Tretja.Profesor(), "prof_Xzj3G");
        t.prejmi(new Tretja.Docent(), "doc_sm0W2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_oqbEX");
        t.prejmi(new Tretja.Asistent(), "as_Yc1rV");
        t.prejmi(new Tretja.Asistent(), "as_ewKMa");
    }
}
