
public class Test44 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_n8yNp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hHmSJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_zVn3o");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_flp35");
        t.prejmi(new Tretja.Profesor(), "prof_j6tgY");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Wxguq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_jHi3k");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_2COmW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_UXtMG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wRVNg");
        t.prejmi(new Tretja.Asistent(), "as_Jm7tO");
        t.prejmi(new Tretja.Profesor(), "prof_WL1gz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_DOr7G");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_q13uB");
        t.prejmi(new Tretja.Profesor(), "prof_Kw64f");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_DrTe3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_0Zn7l");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_mH8QM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_rkM5z");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_8WLNK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XyJxT");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_cyYbL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_h9vsk");
        t.prejmi(new Tretja.Profesor(), "prof_FTZjq");
        t.prejmi(new Tretja.Docent(), "doc_ojbB4");
        t.prejmi(new Tretja.Asistent(), "as_IXpW8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_C5brC");
        t.prejmi(new Tretja.Docent(), "doc_4ei5j");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_1sNQD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_JN6mV");
        t.prejmi(new Tretja.Asistent(), "as_vgdrq");
        t.prejmi(new Tretja.Asistent(), "as_yvOAU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_isrB6");
        t.prejmi(new Tretja.Profesor(), "prof_WBtJ9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_7yrsB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2rXQy");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_uQ3XM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ntqsp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_773uW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_WkB4F");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zhCBo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_L2V2k");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iB6vD");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4S8TL");
        t.prejmi(new Tretja.Profesor(), "prof_JoMuC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_nfk7T");
        t.prejmi(new Tretja.Asistent(), "as_1ruir");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_VVwto");
        t.prejmi(new Tretja.Docent(), "doc_rmlha");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_p0aXB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_sRB4q");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_CkAbw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_aaIRi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w6N7E");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XVr4o");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_snQfj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_FFY9l");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tVuYk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tAXM3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ECsVb");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_inF1r");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Mvm46");
        t.prejmi(new Tretja.Asistent(), "as_cR8wb");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_mHDw0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9R4jL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_20485");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6Csxy");
        t.prejmi(new Tretja.Asistent(), "as_1qalA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_wK9UR");
        t.prejmi(new Tretja.Docent(), "doc_WNcya");
        t.prejmi(new Tretja.Profesor(), "prof_UXnW3");
        t.prejmi(new Tretja.Docent(), "doc_ezfaK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bthS7");
        t.prejmi(new Tretja.Asistent(), "as_RnhJ6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_bpquU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_D1kGK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_LgvUb");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QOWNx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_WPgHZ");
        t.prejmi(new Tretja.Asistent(), "as_UY90b");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_0XKrV");
        t.prejmi(new Tretja.Profesor(), "prof_ODxEA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_lDOl6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8eucV");
        t.prejmi(new Tretja.Docent(), "doc_GXL1p");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rMpzr");
        t.prejmi(new Tretja.Profesor(), "prof_zzFxd");
        t.prejmi(new Tretja.Docent(), "doc_ij789");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_s05dO");
        t.prejmi(new Tretja.Asistent(), "as_gs62W");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Yjy7V");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9vJch");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hXA5w");
        t.prejmi(new Tretja.Docent(), "doc_8steU");
        t.prejmi(new Tretja.Profesor(), "prof_03SO5");
        t.prejmi(new Tretja.Asistent(), "as_89ITY");
        t.prejmi(new Tretja.Profesor(), "prof_cMfAA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_waFAq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_sQouc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wnyVw");
        t.prejmi(new Tretja.Docent(), "doc_Jf0m5");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_SGO01");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Dw1k8");
        t.prejmi(new Tretja.Profesor(), "prof_ciIui");
        t.prejmi(new Tretja.Docent(), "doc_6HY3w");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_L7qNp");
        t.prejmi(new Tretja.Docent(), "doc_mexYI");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_MO4O9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_PslNw");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_1F2pK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_xdV1R");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vm4tl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_QOs1n");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MhnAY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_EzM9a");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_YAClc");
        t.prejmi(new Tretja.Asistent(), "as_k0Hu9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_mm1Jw");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_08ui9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ijvFw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4zbOr");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hDUR6");
        t.prejmi(new Tretja.Asistent(), "as_Lwlmj");
        t.prejmi(new Tretja.Docent(), "doc_ofkUZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_oXgql");
        t.prejmi(new Tretja.Docent(), "doc_fQIx4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_2GgwB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_X8S35");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_J8bXI");
        t.prejmi(new Tretja.Asistent(), "as_CXNLb");
        t.prejmi(new Tretja.Asistent(), "as_1iRd5");
        t.prejmi(new Tretja.Docent(), "doc_CssoM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_3vqEY");
        t.prejmi(new Tretja.Asistent(), "as_mfimf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_iDvGR");
        t.prejmi(new Tretja.Docent(), "doc_y7iMp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pl1G1");
        t.prejmi(new Tretja.Profesor(), "prof_o1l18");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XTbWV");
        t.prejmi(new Tretja.Asistent(), "as_uLbdd");
        t.prejmi(new Tretja.Asistent(), "as_VH61o");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_M7LWl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_U3eE4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5hBRj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_eAXTP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4gkPl");
        t.prejmi(new Tretja.Asistent(), "as_qnSgp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7S1rD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_MoVz2");
        t.prejmi(new Tretja.Asistent(), "as_cmhqw");
        t.prejmi(new Tretja.Profesor(), "prof_GIyUn");
        t.prejmi(new Tretja.Asistent(), "as_IQUfm");
        t.prejmi(new Tretja.Asistent(), "as_vLeob");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_BrD3r");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_PVQ80");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_uYvpV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_au78x");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_dN2UF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_SFUFv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7ccMZ");
        t.prejmi(new Tretja.Docent(), "doc_FbbWA");
    }
}
