
public class Test20 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_u5X7S");
        t.prejmi(new Tretja.Asistent(), "as_HPWas");
        t.prejmi(new Tretja.Asistent(), "as_TOGyM");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_HRQDw");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_Zb2YC");
        t.prejmi(new Tretja.Asistent(), "as_OT033");
        t.prejmi(new Tretja.Profesor(), "prof_wL721");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_N8ls8");
        t.prejmi(new Tretja.Profesor(), "prof_98N0i");
        t.prejmi(new Tretja.Docent(), "doc_i2X9h");
        t.prejmi(new Tretja.Asistent(), "as_Wxjj3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_TzLRI");
        t.prejmi(new Tretja.Asistent(), "as_VyZiO");
        t.prejmi(new Tretja.Profesor(), "prof_jkaYT");
        t.prejmi(new Tretja.Profesor(), "prof_KE8Zo");
        t.prejmi(new Tretja.Profesor(), "prof_YuNNd");
        t.prejmi(new Tretja.Asistent(), "as_2MRqG");
        t.prejmi(new Tretja.Profesor(), "prof_DSrsy");
        t.prejmi(new Tretja.Asistent(), "as_Jx3bm");
        t.prejmi(new Tretja.Docent(), "doc_AT4fd");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_N4qcW");
        t.prejmi(new Tretja.Profesor(), "prof_5PD4m");
        t.prejmi(new Tretja.Docent(), "doc_CkTSD");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_nPfRR");
        t.prejmi(new Tretja.Profesor(), "prof_ntQY5");
        t.prejmi(new Tretja.Asistent(), "as_UuRzU");
        t.prejmi(new Tretja.Docent(), "doc_Ahhj2");
        t.prejmi(new Tretja.Profesor(), "prof_dbXRx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_Gsqb0");
        t.prejmi(new Tretja.Profesor(), "prof_MvFLY");
        t.prejmi(new Tretja.Docent(), "doc_xnfOd");
        t.prejmi(new Tretja.Docent(), "doc_wZ9Bo");
        t.prejmi(new Tretja.Profesor(), "prof_olnjF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_FvwWy");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_wRUWW");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_ZWJhe");
        t.prejmi(new Tretja.Docent(), "doc_3ighN");
        t.prejmi(new Tretja.Docent(), "doc_X8DOM");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_cdV9G");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_at2mo");
        t.prejmi(new Tretja.Profesor(), "prof_Y9EJ3");
        t.prejmi(new Tretja.Docent(), "doc_San8v");
        t.prejmi(new Tretja.Docent(), "doc_T577M");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_4rGxl");
        t.prejmi(new Tretja.Asistent(), "as_y660S");
        t.prejmi(new Tretja.Docent(), "doc_Rvvk0");
        t.prejmi(new Tretja.Profesor(), "prof_dLUlO");
        t.prejmi(new Tretja.Docent(), "doc_SqPLQ");
        t.prejmi(new Tretja.Profesor(), "prof_RzcMi");
        t.prejmi(new Tretja.Profesor(), "prof_qfjTO");
        t.prejmi(new Tretja.Asistent(), "as_HiIMv");
        t.prejmi(new Tretja.Docent(), "doc_UTVgN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_9vFSP");
        t.prejmi(new Tretja.Profesor(), "prof_jxy75");
        t.prejmi(new Tretja.Profesor(), "prof_ZMLqR");
        t.prejmi(new Tretja.Asistent(), "as_tu3LA");
        t.prejmi(new Tretja.Docent(), "doc_CA6fE");
        t.prejmi(new Tretja.Profesor(), "prof_T9snr");
        t.prejmi(new Tretja.Profesor(), "prof_uDQLJ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_qMERk");
        t.prejmi(new Tretja.Profesor(), "prof_ff0Hf");
        t.prejmi(new Tretja.Asistent(), "as_LcLj1");
        t.prejmi(new Tretja.Asistent(), "as_yQDg1");
        t.prejmi(new Tretja.Profesor(), "prof_JWVFo");
        t.prejmi(new Tretja.Profesor(), "prof_hNgHA");
        t.prejmi(new Tretja.Docent(), "doc_LLaNF");
        t.prejmi(new Tretja.Profesor(), "prof_VMfqv");
        t.prejmi(new Tretja.Asistent(), "as_BNnuW");
        t.prejmi(new Tretja.Docent(), "doc_3TbKF");
        t.prejmi(new Tretja.Docent(), "doc_QAHJW");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_DQyZI");
        t.prejmi(new Tretja.Docent(), "doc_jDFqW");
        t.prejmi(new Tretja.Profesor(), "prof_WbkAY");
        t.prejmi(new Tretja.Asistent(), "as_G4Cs8");
        t.prejmi(new Tretja.Docent(), "doc_8b5Tc");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_uiyMG");
        t.prejmi(new Tretja.Docent(), "doc_stnlU");
        t.prejmi(new Tretja.Docent(), "doc_iaAKl");
        t.prejmi(new Tretja.Asistent(), "as_LIars");
        t.prejmi(new Tretja.Profesor(), "prof_cEA64");
        t.prejmi(new Tretja.Asistent(), "as_SL4Xk");
        t.prejmi(new Tretja.Asistent(), "as_ykKcD");
        t.prejmi(new Tretja.Asistent(), "as_S9Nkr");
        t.prejmi(new Tretja.Docent(), "doc_TEMrR");
        t.prejmi(new Tretja.Docent(), "doc_gT1ph");
        t.prejmi(new Tretja.Profesor(), "prof_NOaDC");
        t.prejmi(new Tretja.Profesor(), "prof_mUf6B");
        t.prejmi(new Tretja.Asistent(), "as_xagKf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_xc0HS");
        t.prejmi(new Tretja.Profesor(), "prof_F4FuW");
        t.prejmi(new Tretja.Asistent(), "as_onW6i");
        t.prejmi(new Tretja.Asistent(), "as_ZmJU3");
        t.prejmi(new Tretja.Docent(), "doc_1FXmR");
        t.prejmi(new Tretja.Asistent(), "as_hg0HT");
        t.prejmi(new Tretja.Profesor(), "prof_o4l3L");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_cWAV3");
        t.prejmi(new Tretja.Profesor(), "prof_NcknN");
        t.prejmi(new Tretja.Docent(), "doc_ZJl7t");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_yxGfx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_jupu8");
        t.prejmi(new Tretja.Profesor(), "prof_oeNUj");
        t.prejmi(new Tretja.Asistent(), "as_C6Mq5");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_b6Z53");
        t.prejmi(new Tretja.Docent(), "doc_UBPrj");
        t.prejmi(new Tretja.Docent(), "doc_ffAWc");
        t.prejmi(new Tretja.Asistent(), "as_8SLm2");
        t.prejmi(new Tretja.Profesor(), "prof_AaY9R");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_KL7uW");
        t.prejmi(new Tretja.Asistent(), "as_Vui2y");
        t.prejmi(new Tretja.Docent(), "doc_lbYPE");
        t.prejmi(new Tretja.Asistent(), "as_XkFWf");
        t.prejmi(new Tretja.Profesor(), "prof_dGdCU");
        t.prejmi(new Tretja.Docent(), "doc_i6hWR");
        t.prejmi(new Tretja.Profesor(), "prof_q6INr");
        t.prejmi(new Tretja.Docent(), "doc_bcwSg");
        t.prejmi(new Tretja.Profesor(), "prof_B8M9l");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_vH10y");
        t.prejmi(new Tretja.Profesor(), "prof_Xfh83");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_X46x7");
        t.prejmi(new Tretja.Profesor(), "prof_bkBvZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_nuVh4");
        t.prejmi(new Tretja.Asistent(), "as_f1NGY");
        t.prejmi(new Tretja.Docent(), "doc_J5vSp");
        t.prejmi(new Tretja.Docent(), "doc_UdCIq");
        t.prejmi(new Tretja.Profesor(), "prof_VE6Hn");
        t.prejmi(new Tretja.Profesor(), "prof_4E0TD");
        t.prejmi(new Tretja.Profesor(), "prof_6IKn9");
        t.prejmi(new Tretja.Asistent(), "as_GfaBn");
        t.prejmi(new Tretja.Docent(), "doc_QCIV2");
        t.prejmi(new Tretja.Docent(), "doc_RUDOI");
        t.prejmi(new Tretja.Profesor(), "prof_kc6hC");
        t.prejmi(new Tretja.Docent(), "doc_dmYEw");
        t.prejmi(new Tretja.Profesor(), "prof_RKDJo");
        t.prejmi(new Tretja.Asistent(), "as_s4SsV");
        t.prejmi(new Tretja.Asistent(), "as_WpLt3");
        t.prejmi(new Tretja.Asistent(), "as_BL7TB");
        t.prejmi(new Tretja.Asistent(), "as_Pc344");
        t.prejmi(new Tretja.Docent(), "doc_suQbN");
        t.prejmi(new Tretja.Docent(), "doc_uydWY");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_TDg1C");
        t.prejmi(new Tretja.Profesor(), "prof_WJENf");
        t.prejmi(new Tretja.Docent(), "doc_nkuQo");
        t.prejmi(new Tretja.Asistent(), "as_XDwhj");
        t.prejmi(new Tretja.Asistent(), "as_Tw9sG");
        t.prejmi(new Tretja.Profesor(), "prof_V76Gg");
        t.prejmi(new Tretja.Asistent(), "as_VjkPA");
        t.prejmi(new Tretja.Asistent(), "as_ruNLH");
        t.prejmi(new Tretja.Asistent(), "as_ut5Ok");
        t.prejmi(new Tretja.Docent(), "doc_7H9xZ");
        t.prejmi(new Tretja.Profesor(), "prof_d3DWZ");
        t.prejmi(new Tretja.Asistent(), "as_XH0R1");
        t.prejmi(new Tretja.Docent(), "doc_VaR1S");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_FrAV7");
        t.prejmi(new Tretja.Profesor(), "prof_n58Fa");
        t.prejmi(new Tretja.Docent(), "doc_f3Yr7");
        t.prejmi(new Tretja.Asistent(), "as_idzlo");
        t.prejmi(new Tretja.Docent(), "doc_Z6XBb");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_IBj80");
        t.prejmi(new Tretja.Docent(), "doc_LP3Sd");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_RQeN0");
        t.prejmi(new Tretja.Docent(), "doc_lfBqo");
        t.prejmi(new Tretja.Profesor(), "prof_zbBsM");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_chI5b");
        t.prejmi(new Tretja.Asistent(), "as_1ovDf");
        t.prejmi(new Tretja.Profesor(), "prof_xE4XC");
        t.prejmi(new Tretja.Asistent(), "as_jrc5w");
        t.prejmi(new Tretja.Profesor(), "prof_9WbK9");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_5yOGD");
        t.prejmi(new Tretja.Asistent(), "as_3jEfu");
        t.prejmi(new Tretja.Profesor(), "prof_rF7al");
        t.prejmi(new Tretja.Profesor(), "prof_gWO3w");
        t.prejmi(new Tretja.Profesor(), "prof_GQRU5");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_YYfbR");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_8wYSG");
        t.prejmi(new Tretja.Docent(), "doc_vdNPX");
        t.prejmi(new Tretja.Docent(), "doc_QlDnG");
        t.prejmi(new Tretja.Asistent(), "as_Oy3kR");
        t.prejmi(new Tretja.Asistent(), "as_7jzB4");
        t.prejmi(new Tretja.Asistent(), "as_jYls4");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_gMj2r");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_1t3bY");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_nJ4U3");
        t.prejmi(new Tretja.Docent(), "doc_BQCQO");
        t.prejmi(new Tretja.Docent(), "doc_jX4QM");
        t.prejmi(new Tretja.Asistent(), "as_C2kwl");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_TnWXb");
        t.prejmi(new Tretja.Profesor(), "prof_OcoST");
        t.prejmi(new Tretja.Asistent(), "as_ynxjj");
        t.prejmi(new Tretja.Asistent(), "as_sd8XC");
        t.prejmi(new Tretja.Asistent(), "as_uv07o");
        t.prejmi(new Tretja.Docent(), "doc_6MkZJ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_vCfSC");
        t.prejmi(new Tretja.Profesor(), "prof_aEJBa");
        t.prejmi(new Tretja.Docent(), "doc_qIWUZ");
        t.prejmi(new Tretja.Asistent(), "as_KqX8w");
        t.prejmi(new Tretja.Docent(), "doc_NOUIs");
        t.prejmi(new Tretja.Asistent(), "as_0f9vQ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_cyZaM");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_JC8CM");
        t.prejmi(new Tretja.Asistent(), "as_2wAMh");
        t.prejmi(new Tretja.Profesor(), "prof_iNANR");
        t.prejmi(new Tretja.Profesor(), "prof_NagXZ");
        t.prejmi(new Tretja.Profesor(), "prof_MN4BB");
        t.prejmi(new Tretja.Profesor(), "prof_oBy4r");
        t.prejmi(new Tretja.Asistent(), "as_RyYRt");
        t.prejmi(new Tretja.Asistent(), "as_84oij");
        t.prejmi(new Tretja.Profesor(), "prof_vDPle");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_hytcG");
        t.prejmi(new Tretja.Docent(), "doc_9zQOi");
        t.prejmi(new Tretja.Profesor(), "prof_MGRYH");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_oa999");
        t.prejmi(new Tretja.Asistent(), "as_ldxoe");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_HXJvy");
        t.prejmi(new Tretja.Docent(), "doc_h0TTj");
        t.prejmi(new Tretja.Docent(), "doc_9V93B");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_bdn7T");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_3CE2b");
        t.prejmi(new Tretja.Asistent(), "as_Rq79T");
        t.prejmi(new Tretja.Asistent(), "as_LqPEH");
        t.prejmi(new Tretja.Profesor(), "prof_LAurB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_j2JAy");
        t.prejmi(new Tretja.Docent(), "doc_ppsXK");
        t.prejmi(new Tretja.Profesor(), "prof_84uUR");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_J4KOV");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_N8tPS");
        t.prejmi(new Tretja.Docent(), "doc_l7nqH");
        t.prejmi(new Tretja.Profesor(), "prof_5WZKW");
        t.prejmi(new Tretja.Asistent(), "as_V4hr5");
        t.prejmi(new Tretja.Profesor(), "prof_wBEYc");
        t.prejmi(new Tretja.Asistent(), "as_ebcfg");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_kYdqy");
        t.prejmi(new Tretja.Docent(), "doc_97ji7");
        t.prejmi(new Tretja.Profesor(), "prof_I1vM5");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_O1C3f");
        t.prejmi(new Tretja.Profesor(), "prof_H9J2R");
        t.prejmi(new Tretja.Profesor(), "prof_imLpE");
        t.prejmi(new Tretja.Asistent(), "as_HBYQs");
        t.prejmi(new Tretja.Profesor(), "prof_3niw3");
        t.prejmi(new Tretja.Docent(), "doc_Ldhuo");
        t.prejmi(new Tretja.Asistent(), "as_z1mYg");
        t.prejmi(new Tretja.Profesor(), "prof_yhCnd");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_TUsPo");
        t.prejmi(new Tretja.Docent(), "doc_CPChH");
        t.prejmi(new Tretja.Asistent(), "as_U6aCa");
        t.prejmi(new Tretja.Profesor(), "prof_HBETC");
        t.prejmi(new Tretja.Docent(), "doc_IJiZ1");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_Xjmad");
        t.prejmi(new Tretja.Asistent(), "as_qaOUw");
        t.prejmi(new Tretja.Profesor(), "prof_7K0Hq");
        t.prejmi(new Tretja.Profesor(), "prof_javxK");
        t.prejmi(new Tretja.Profesor(), "prof_NXlPe");
        t.prejmi(new Tretja.Asistent(), "as_M7elQ");
        t.prejmi(new Tretja.Docent(), "doc_rwnQj");
        t.prejmi(new Tretja.Profesor(), "prof_WibFJ");
        t.prejmi(new Tretja.Docent(), "doc_nxUYG");
        t.prejmi(new Tretja.Asistent(), "as_5G1SS");
        t.prejmi(new Tretja.Profesor(), "prof_0g3b8");
        t.prejmi(new Tretja.Profesor(), "prof_HLiKj");
        t.prejmi(new Tretja.Docent(), "doc_kaI1Z");
        t.prejmi(new Tretja.Profesor(), "prof_sXa4y");
        t.prejmi(new Tretja.Docent(), "doc_SThpq");
        t.prejmi(new Tretja.Docent(), "doc_sI4If");
        t.prejmi(new Tretja.Asistent(), "as_exzZW");
        t.prejmi(new Tretja.Asistent(), "as_SGpeK");
        t.prejmi(new Tretja.Asistent(), "as_j41jj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_DEQsI");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_TJVb9");
        t.prejmi(new Tretja.Asistent(), "as_JYiDS");
        t.prejmi(new Tretja.Docent(), "doc_gTs9x");
        t.prejmi(new Tretja.Profesor(), "prof_61NYo");
        t.prejmi(new Tretja.Asistent(), "as_vkvhX");
        t.prejmi(new Tretja.Asistent(), "as_Q9OFl");
        t.prejmi(new Tretja.Profesor(), "prof_Js3Xw");
        t.prejmi(new Tretja.Profesor(), "prof_8eZDH");
        t.prejmi(new Tretja.Profesor(), "prof_V3p78");
        t.prejmi(new Tretja.Docent(), "doc_R8txw");
        t.prejmi(new Tretja.Asistent(), "as_g3egj");
        t.prejmi(new Tretja.Asistent(), "as_S3vrD");
        t.prejmi(new Tretja.Docent(), "doc_xKVhY");
        t.prejmi(new Tretja.Profesor(), "prof_a1LGS");
        t.prejmi(new Tretja.Profesor(), "prof_jRMUT");
        t.prejmi(new Tretja.Docent(), "doc_zkgyg");
        t.prejmi(new Tretja.Profesor(), "prof_ieKWS");
        t.prejmi(new Tretja.Asistent(), "as_DufNH");
        t.prejmi(new Tretja.Docent(), "doc_IHNZZ");
        t.prejmi(new Tretja.Docent(), "doc_GnugW");
        t.prejmi(new Tretja.Asistent(), "as_EMOKP");
        t.prejmi(new Tretja.Docent(), "doc_ArxGw");
        t.prejmi(new Tretja.Profesor(), "prof_OueHA");
        t.prejmi(new Tretja.Asistent(), "as_j5j7m");
        t.prejmi(new Tretja.Docent(), "doc_D5fS9");
        t.prejmi(new Tretja.Profesor(), "prof_tfOSD");
        t.prejmi(new Tretja.Docent(), "doc_HbU4N");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_Q0cho");
        t.prejmi(new Tretja.Asistent(), "as_lpA70");
        t.prejmi(new Tretja.Docent(), "doc_nAVW5");
        t.prejmi(new Tretja.Asistent(), "as_aIYo9");
        t.prejmi(new Tretja.Asistent(), "as_SDH2H");
        t.prejmi(new Tretja.Docent(), "doc_gKk9B");
        t.prejmi(new Tretja.Asistent(), "as_YkNEx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_xlNkC");
        t.prejmi(new Tretja.Asistent(), "as_eQkEG");
        t.prejmi(new Tretja.Profesor(), "prof_EH8OT");
        t.prejmi(new Tretja.Profesor(), "prof_grHpR");
        t.prejmi(new Tretja.Profesor(), "prof_alfsv");
        t.prejmi(new Tretja.Asistent(), "as_BuZUk");
        t.prejmi(new Tretja.Docent(), "doc_9QE0A");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_1VvEj");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_0EgUS");
        t.prejmi(new Tretja.Docent(), "doc_9chkh");
        t.prejmi(new Tretja.Asistent(), "as_odd4K");
        t.prejmi(new Tretja.Docent(), "doc_Q0VNz");
        t.prejmi(new Tretja.Docent(), "doc_KMoYP");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_2zVD9");
        t.prejmi(new Tretja.Asistent(), "as_gy8Og");
        t.prejmi(new Tretja.Asistent(), "as_08Y25");
        t.prejmi(new Tretja.Docent(), "doc_KyUrO");
        t.prejmi(new Tretja.Profesor(), "prof_XQuRe");
        t.prejmi(new Tretja.Profesor(), "prof_3CR0H");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_GCURH");
        t.prejmi(new Tretja.Docent(), "doc_s7A9d");
        t.prejmi(new Tretja.Asistent(), "as_XdMW8");
        t.prejmi(new Tretja.Docent(), "doc_mU8m3");
        t.prejmi(new Tretja.Docent(), "doc_D00Mf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_0WkI3");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ZVTaz");
        t.prejmi(new Tretja.Asistent(), "as_M7Vvn");
        t.prejmi(new Tretja.Docent(), "doc_omMuj");
        t.prejmi(new Tretja.Profesor(), "prof_VzRUS");
        t.prejmi(new Tretja.Docent(), "doc_GBbU2");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_vNyeQ");
        t.prejmi(new Tretja.Profesor(), "prof_kBJhF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_GNYcQ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_47FJV");
        t.prejmi(new Tretja.Docent(), "doc_vZN8M");
        t.prejmi(new Tretja.Docent(), "doc_0Vqzq");
        t.prejmi(new Tretja.Docent(), "doc_yuclw");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_1SpCr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_j2cj4");
        t.prejmi(new Tretja.Profesor(), "prof_LAJLu");
        t.prejmi(new Tretja.Profesor(), "prof_EH1lZ");
        t.prejmi(new Tretja.Asistent(), "as_V3CZF");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_dUpH6");
        t.prejmi(new Tretja.Profesor(), "prof_mjI5e");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
    }
}
