
public class Test11 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_J2dzo");
        t.prejmi(new Tretja.Docent(), "doc_aKJxS");
        t.prejmi(new Tretja.Profesor(), "prof_QbFE3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_rwKeL");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_sQtJ1");
        t.prejmi(new Tretja.Profesor(), "prof_yvUr5");
        t.prejmi(new Tretja.Docent(), "doc_H9qIz");
        t.prejmi(new Tretja.Profesor(), "prof_apP9N");
        t.prejmi(new Tretja.Asistent(), "as_U7WNF");
        t.prejmi(new Tretja.Asistent(), "as_9eKlg");
        t.prejmi(new Tretja.Docent(), "doc_E13xD");
        t.prejmi(new Tretja.Profesor(), "prof_EDG0g");
        t.prejmi(new Tretja.Profesor(), "prof_VETGR");
        t.prejmi(new Tretja.Docent(), "doc_u3nVu");
        t.prejmi(new Tretja.Profesor(), "prof_E7gd3");
        t.prejmi(new Tretja.Asistent(), "as_58LQ9");
        t.prejmi(new Tretja.Profesor(), "prof_1SOdu");
        t.prejmi(new Tretja.Profesor(), "prof_Jjjxu");
        t.prejmi(new Tretja.Profesor(), "prof_QXMMf");
        t.prejmi(new Tretja.Profesor(), "prof_pWzdc");
        t.prejmi(new Tretja.Docent(), "doc_0ZgTQ");
        t.prejmi(new Tretja.Docent(), "doc_g1mtF");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_9IirE");
        t.prejmi(new Tretja.Profesor(), "prof_bG6EF");
        t.prejmi(new Tretja.Profesor(), "prof_xajJT");
        t.prejmi(new Tretja.Asistent(), "as_9FnoF");
        t.prejmi(new Tretja.Profesor(), "prof_Z6Pui");
        t.prejmi(new Tretja.Profesor(), "prof_aSnLt");
        t.prejmi(new Tretja.Profesor(), "prof_71fNI");
        t.prejmi(new Tretja.Asistent(), "as_krmxG");
        t.prejmi(new Tretja.Docent(), "doc_J6gkK");
        t.prejmi(new Tretja.Docent(), "doc_eqaRo");
        t.prejmi(new Tretja.Asistent(), "as_Jstqh");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_quB62");
        t.prejmi(new Tretja.Asistent(), "as_gQC49");
        t.prejmi(new Tretja.Docent(), "doc_FBGYa");
        t.prejmi(new Tretja.Asistent(), "as_2DpmO");
        t.prejmi(new Tretja.Docent(), "doc_kuiR2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_UnJK3");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_1PuCx");
        t.prejmi(new Tretja.Profesor(), "prof_vm3Si");
        t.prejmi(new Tretja.Profesor(), "prof_bt9S9");
        t.prejmi(new Tretja.Asistent(), "as_0mSXA");
        t.prejmi(new Tretja.Profesor(), "prof_0veAM");
        t.prejmi(new Tretja.Docent(), "doc_AWT1P");
        t.prejmi(new Tretja.Docent(), "doc_fLZjj");
        t.prejmi(new Tretja.Profesor(), "prof_wgPFT");
        t.prejmi(new Tretja.Docent(), "doc_LJUxh");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_sPdjs");
        t.prejmi(new Tretja.Profesor(), "prof_IAUgJ");
        t.prejmi(new Tretja.Asistent(), "as_TGmRp");
        t.prejmi(new Tretja.Asistent(), "as_0pbdW");
        t.prejmi(new Tretja.Docent(), "doc_30MJI");
        t.prejmi(new Tretja.Docent(), "doc_DydH8");
        t.prejmi(new Tretja.Asistent(), "as_c8ncU");
        t.prejmi(new Tretja.Docent(), "doc_znL6p");
        t.prejmi(new Tretja.Docent(), "doc_6ylFR");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_4xGzn");
        t.prejmi(new Tretja.Docent(), "doc_92fgg");
        t.prejmi(new Tretja.Asistent(), "as_p2OfZ");
        t.prejmi(new Tretja.Profesor(), "prof_K5A27");
        t.prejmi(new Tretja.Asistent(), "as_l8lND");
        t.prejmi(new Tretja.Asistent(), "as_8wcgz");
        t.prejmi(new Tretja.Asistent(), "as_luadb");
        t.prejmi(new Tretja.Profesor(), "prof_2f0B0");
        t.prejmi(new Tretja.Profesor(), "prof_kCJ4Q");
        t.prejmi(new Tretja.Profesor(), "prof_yapUL");
        t.prejmi(new Tretja.Asistent(), "as_fBd4U");
        t.prejmi(new Tretja.Asistent(), "as_kzNCc");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_V6bpC");
        t.prejmi(new Tretja.Asistent(), "as_kuurj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_AbBoS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_57hm6");
        t.prejmi(new Tretja.Docent(), "doc_9IjWQ");
        t.prejmi(new Tretja.Docent(), "doc_f0wCJ");
        t.prejmi(new Tretja.Profesor(), "prof_1PoX0");
        t.prejmi(new Tretja.Profesor(), "prof_z4Zgq");
        t.prejmi(new Tretja.Profesor(), "prof_5HUw1");
        t.prejmi(new Tretja.Asistent(), "as_luTCT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_zejgp");
        t.prejmi(new Tretja.Asistent(), "as_4UGZ2");
        t.prejmi(new Tretja.Asistent(), "as_Q8ldG");
        t.prejmi(new Tretja.Profesor(), "prof_r8uY0");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_FgY9K");
        t.prejmi(new Tretja.Asistent(), "as_Wvirt");
        t.prejmi(new Tretja.Asistent(), "as_wikMj");
        t.prejmi(new Tretja.Profesor(), "prof_lffgQ");
        t.prejmi(new Tretja.Asistent(), "as_FxR2X");
        t.prejmi(new Tretja.Docent(), "doc_5FOJ0");
        t.prejmi(new Tretja.Asistent(), "as_UqEpY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_JnCzm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Pb2wv");
        t.prejmi(new Tretja.Profesor(), "prof_MkqSc");
        t.prejmi(new Tretja.Docent(), "doc_vCN8o");
        t.prejmi(new Tretja.Profesor(), "prof_xT65D");
        t.prejmi(new Tretja.Profesor(), "prof_ZW2UX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_O1lKS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_MebV4");
        t.prejmi(new Tretja.Asistent(), "as_IXFXi");
        t.prejmi(new Tretja.Docent(), "doc_jBWWO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_wIvIv");
        t.prejmi(new Tretja.Asistent(), "as_P7bZz");
        t.prejmi(new Tretja.Docent(), "doc_uatAi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_T3BsU");
        t.prejmi(new Tretja.Profesor(), "prof_PbZ9Q");
        t.prejmi(new Tretja.Docent(), "doc_98sap");
        t.prejmi(new Tretja.Asistent(), "as_ezQXk");
        t.prejmi(new Tretja.Docent(), "doc_jubWj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_e2A4W");
        t.prejmi(new Tretja.Profesor(), "prof_peSmH");
        t.prejmi(new Tretja.Docent(), "doc_YTPvS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_B7zzt");
        t.prejmi(new Tretja.Asistent(), "as_IPvDU");
        t.prejmi(new Tretja.Docent(), "doc_B3Nhw");
        t.prejmi(new Tretja.Asistent(), "as_Ar5LE");
        t.prejmi(new Tretja.Profesor(), "prof_avxzv");
        t.prejmi(new Tretja.Docent(), "doc_dinxv");
        t.prejmi(new Tretja.Profesor(), "prof_NZUfV");
        t.prejmi(new Tretja.Asistent(), "as_ua36W");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_5AYBp");
        t.prejmi(new Tretja.Asistent(), "as_Q1KYY");
        t.prejmi(new Tretja.Profesor(), "prof_ucQlu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_eAKLI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_7Jx9U");
        t.prejmi(new Tretja.Docent(), "doc_pUqYT");
        t.prejmi(new Tretja.Asistent(), "as_eLDDI");
        t.prejmi(new Tretja.Asistent(), "as_8xujQ");
        t.prejmi(new Tretja.Docent(), "doc_hkdpO");
        t.prejmi(new Tretja.Docent(), "doc_iRwbD");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_pFW6l");
        t.prejmi(new Tretja.Docent(), "doc_XPIIF");
        t.prejmi(new Tretja.Docent(), "doc_9g07a");
        t.prejmi(new Tretja.Docent(), "doc_oiYI2");
        t.prejmi(new Tretja.Docent(), "doc_XnY2t");
        t.prejmi(new Tretja.Asistent(), "as_fLHfp");
        t.prejmi(new Tretja.Asistent(), "as_zWAWp");
        t.prejmi(new Tretja.Asistent(), "as_xoETX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_rhCeN");
        t.prejmi(new Tretja.Asistent(), "as_Kgsi7");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_cbnK5");
        t.prejmi(new Tretja.Asistent(), "as_AXiGe");
        t.prejmi(new Tretja.Asistent(), "as_PJtCv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_3yqUW");
        t.prejmi(new Tretja.Profesor(), "prof_9NM0O");
        t.prejmi(new Tretja.Docent(), "doc_yFEGW");
        t.prejmi(new Tretja.Profesor(), "prof_S6ViT");
        t.prejmi(new Tretja.Profesor(), "prof_XLfJZ");
        t.prejmi(new Tretja.Profesor(), "prof_HGmUA");
        t.prejmi(new Tretja.Profesor(), "prof_3MKax");
        t.prejmi(new Tretja.Profesor(), "prof_LguLW");
        t.prejmi(new Tretja.Docent(), "doc_aFkC2");
        t.prejmi(new Tretja.Docent(), "doc_k8oiB");
        t.prejmi(new Tretja.Asistent(), "as_6cmQh");
        t.prejmi(new Tretja.Docent(), "doc_kAZUD");
        t.prejmi(new Tretja.Profesor(), "prof_DN6Iy");
        t.prejmi(new Tretja.Asistent(), "as_0ZMra");
        t.prejmi(new Tretja.Profesor(), "prof_vnBcw");
        t.prejmi(new Tretja.Profesor(), "prof_jRYDn");
        t.prejmi(new Tretja.Docent(), "doc_iFdMn");
        t.prejmi(new Tretja.Docent(), "doc_71Vxu");
        t.prejmi(new Tretja.Asistent(), "as_Qwqrh");
        t.prejmi(new Tretja.Asistent(), "as_OXd7y");
        t.prejmi(new Tretja.Docent(), "doc_1Ovb1");
        t.prejmi(new Tretja.Asistent(), "as_URdiK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_MzrT6");
        t.prejmi(new Tretja.Profesor(), "prof_GGmeX");
        t.prejmi(new Tretja.Asistent(), "as_3RqZh");
        t.prejmi(new Tretja.Docent(), "doc_tfDze");
        t.prejmi(new Tretja.Profesor(), "prof_bS5oU");
        t.prejmi(new Tretja.Docent(), "doc_cULn3");
        t.prejmi(new Tretja.Asistent(), "as_ZXzhe");
        t.prejmi(new Tretja.Asistent(), "as_2KleP");
        t.prejmi(new Tretja.Asistent(), "as_NyjOm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Ybyhi");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_qWzjZ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Wn1Qw");
        t.prejmi(new Tretja.Profesor(), "prof_ZmIEH");
        t.prejmi(new Tretja.Profesor(), "prof_oIQtc");
        t.prejmi(new Tretja.Profesor(), "prof_ml1Ai");
        t.prejmi(new Tretja.Profesor(), "prof_1GpJa");
        t.prejmi(new Tretja.Asistent(), "as_aDIAq");
        t.prejmi(new Tretja.Profesor(), "prof_HoQXf");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Zx3OW");
        t.prejmi(new Tretja.Asistent(), "as_5BYfX");
        t.prejmi(new Tretja.Profesor(), "prof_jx0EI");
        t.prejmi(new Tretja.Asistent(), "as_8P7Zf");
        t.prejmi(new Tretja.Profesor(), "prof_QETh7");
        t.prejmi(new Tretja.Docent(), "doc_09Eli");
        t.prejmi(new Tretja.Profesor(), "prof_O4H5c");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_CfXRL");
        t.prejmi(new Tretja.Profesor(), "prof_gfU5M");
        t.prejmi(new Tretja.Docent(), "doc_doTvN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_hdznJ");
        t.prejmi(new Tretja.Asistent(), "as_l1tXV");
        t.prejmi(new Tretja.Asistent(), "as_UigPa");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_a6k9n");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_jch6X");
        t.prejmi(new Tretja.Asistent(), "as_cu20s");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_iielQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_7ptXq");
        t.prejmi(new Tretja.Docent(), "doc_q6del");
        t.prejmi(new Tretja.Asistent(), "as_t75DE");
        t.prejmi(new Tretja.Docent(), "doc_innHC");
        t.prejmi(new Tretja.Asistent(), "as_wI8rC");
        t.prejmi(new Tretja.Asistent(), "as_NDZvu");
        t.prejmi(new Tretja.Docent(), "doc_ZHlkb");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_XqYTf");
        t.prejmi(new Tretja.Docent(), "doc_VrOU3");
        t.prejmi(new Tretja.Docent(), "doc_MyWn3");
        t.prejmi(new Tretja.Docent(), "doc_1Ta7R");
        t.prejmi(new Tretja.Asistent(), "as_unLMq");
        t.prejmi(new Tretja.Docent(), "doc_Joncb");
        t.prejmi(new Tretja.Profesor(), "prof_qMixU");
        t.prejmi(new Tretja.Profesor(), "prof_Vv2vT");
        t.prejmi(new Tretja.Docent(), "doc_SVuQq");
        t.prejmi(new Tretja.Docent(), "doc_XnsKL");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_URS1G");
        t.prejmi(new Tretja.Docent(), "doc_zcG5o");
        t.prejmi(new Tretja.Profesor(), "prof_7LmG0");
        t.prejmi(new Tretja.Profesor(), "prof_5aGnt");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Dk2I9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_XXOY3");
        t.prejmi(new Tretja.Asistent(), "as_T8YnS");
        t.prejmi(new Tretja.Docent(), "doc_RPyVX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_ob0Fr");
        t.prejmi(new Tretja.Asistent(), "as_YGY94");
        t.prejmi(new Tretja.Docent(), "doc_seyU3");
        t.prejmi(new Tretja.Asistent(), "as_d2Y6j");
        t.prejmi(new Tretja.Profesor(), "prof_3WB0g");
        t.prejmi(new Tretja.Docent(), "doc_KGq9O");
        t.prejmi(new Tretja.Docent(), "doc_hXp55");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_9wZ5m");
        t.prejmi(new Tretja.Docent(), "doc_zfa9Y");
        t.prejmi(new Tretja.Profesor(), "prof_RXyQY");
        t.prejmi(new Tretja.Asistent(), "as_60TeA");
        t.prejmi(new Tretja.Asistent(), "as_m5jjH");
        t.prejmi(new Tretja.Asistent(), "as_5qKXs");
        t.prejmi(new Tretja.Docent(), "doc_bFXmN");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_kguca");
        t.prejmi(new Tretja.Profesor(), "prof_NoLRY");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_nU9bX");
        t.prejmi(new Tretja.Profesor(), "prof_8zVbk");
        t.prejmi(new Tretja.Docent(), "doc_2tIsg");
        t.prejmi(new Tretja.Asistent(), "as_pPa7p");
        t.prejmi(new Tretja.Asistent(), "as_4v95Z");
        t.prejmi(new Tretja.Docent(), "doc_Lhqx6");
        t.prejmi(new Tretja.Docent(), "doc_SLdnx");
        t.prejmi(new Tretja.Profesor(), "prof_aWIX1");
        t.prejmi(new Tretja.Asistent(), "as_srcsU");
        t.prejmi(new Tretja.Profesor(), "prof_3buYB");
        t.prejmi(new Tretja.Profesor(), "prof_T0fuo");
        t.prejmi(new Tretja.Asistent(), "as_6R3T6");
        t.prejmi(new Tretja.Asistent(), "as_MytGE");
        t.prejmi(new Tretja.Docent(), "doc_Mb19k");
        t.prejmi(new Tretja.Docent(), "doc_wyuD3");
        t.prejmi(new Tretja.Asistent(), "as_Os6ZZ");
        t.prejmi(new Tretja.Asistent(), "as_Axngg");
        t.prejmi(new Tretja.Docent(), "doc_6ioh2");
        t.prejmi(new Tretja.Profesor(), "prof_sylrT");
        t.prejmi(new Tretja.Asistent(), "as_5dEGp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_tYAgK");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_PhRpN");
        t.prejmi(new Tretja.Docent(), "doc_1BOwf");
        t.prejmi(new Tretja.Asistent(), "as_Vykrx");
        t.prejmi(new Tretja.Docent(), "doc_MjU0E");
        t.prejmi(new Tretja.Docent(), "doc_avUPt");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_cFJVL");
        t.prejmi(new Tretja.Profesor(), "prof_WIicu");
        t.prejmi(new Tretja.Docent(), "doc_QrEF2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_eZoxD");
        t.prejmi(new Tretja.Asistent(), "as_kwxH6");
        t.prejmi(new Tretja.Profesor(), "prof_i6M4w");
        t.prejmi(new Tretja.Docent(), "doc_H3Pmc");
        t.prejmi(new Tretja.Asistent(), "as_3EaGh");
        t.prejmi(new Tretja.Profesor(), "prof_qARNn");
        t.prejmi(new Tretja.Profesor(), "prof_Jsi1f");
        t.prejmi(new Tretja.Profesor(), "prof_3SfHS");
        t.prejmi(new Tretja.Profesor(), "prof_UQfgs");
        t.prejmi(new Tretja.Docent(), "doc_87Tvo");
        t.prejmi(new Tretja.Asistent(), "as_LPWW7");
        t.prejmi(new Tretja.Asistent(), "as_ZPbbM");
        t.prejmi(new Tretja.Asistent(), "as_vh8FT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_jo0CB");
        t.prejmi(new Tretja.Asistent(), "as_iw049");
    }
}
