
public class Test29 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_lno7s");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_8JHD1");
        t.prejmi(new Tretja.Asistent(), "as_qkH1Q");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_DgPgA");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_YRRrj");
        t.prejmi(new Tretja.Docent(), "doc_jrB6c");
        t.prejmi(new Tretja.Profesor(), "prof_tjjTw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_hO31B");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_D0xS2");
        t.prejmi(new Tretja.Docent(), "doc_UtSA5");
        t.prejmi(new Tretja.Asistent(), "as_GMFwN");
        t.prejmi(new Tretja.Docent(), "doc_TGijz");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_3rFGP");
        t.prejmi(new Tretja.Asistent(), "as_1rgiJ");
        t.prejmi(new Tretja.Profesor(), "prof_UXFc6");
        t.prejmi(new Tretja.Profesor(), "prof_NF05o");
        t.prejmi(new Tretja.Docent(), "doc_bxjIA");
        t.prejmi(new Tretja.Asistent(), "as_QA6Hb");
        t.prejmi(new Tretja.Profesor(), "prof_2kNBM");
        t.prejmi(new Tretja.Docent(), "doc_srDTi");
        t.prejmi(new Tretja.Asistent(), "as_1itUK");
        t.prejmi(new Tretja.Asistent(), "as_EFgGB");
        t.prejmi(new Tretja.Docent(), "doc_m6yCN");
        t.prejmi(new Tretja.Docent(), "doc_aPoIF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_wWvbo");
        t.prejmi(new Tretja.Docent(), "doc_Ujgkk");
        t.prejmi(new Tretja.Asistent(), "as_oN00h");
        t.prejmi(new Tretja.Asistent(), "as_5M5Wt");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_Ak9tn");
        t.prejmi(new Tretja.Asistent(), "as_LMZdu");
        t.prejmi(new Tretja.Docent(), "doc_JLfsZ");
        t.prejmi(new Tretja.Asistent(), "as_ybnWe");
        t.prejmi(new Tretja.Profesor(), "prof_kCz7X");
        t.prejmi(new Tretja.Asistent(), "as_zHrmB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_wJHab");
        t.prejmi(new Tretja.Asistent(), "as_mXlxi");
        t.prejmi(new Tretja.Asistent(), "as_eDQvJ");
        t.prejmi(new Tretja.Profesor(), "prof_cGWwq");
        t.prejmi(new Tretja.Docent(), "doc_ZCuya");
        t.prejmi(new Tretja.Asistent(), "as_TBN2u");
        t.prejmi(new Tretja.Asistent(), "as_JkIBq");
        t.prejmi(new Tretja.Profesor(), "prof_PantJ");
        t.prejmi(new Tretja.Asistent(), "as_rTtDz");
        t.prejmi(new Tretja.Asistent(), "as_j0hJN");
        t.prejmi(new Tretja.Profesor(), "prof_RE5Uy");
        t.prejmi(new Tretja.Docent(), "doc_tqEfR");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_deGCZ");
        t.prejmi(new Tretja.Profesor(), "prof_qVMXz");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_oTT8o");
        t.prejmi(new Tretja.Docent(), "doc_WkzmR");
        t.prejmi(new Tretja.Asistent(), "as_n7hqr");
        t.prejmi(new Tretja.Docent(), "doc_19c6H");
        t.prejmi(new Tretja.Profesor(), "prof_qSXft");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_4DLK6");
        t.prejmi(new Tretja.Profesor(), "prof_acPl6");
        t.prejmi(new Tretja.Asistent(), "as_Umg00");
        t.prejmi(new Tretja.Asistent(), "as_3b4my");
        t.prejmi(new Tretja.Docent(), "doc_O4BtN");
        t.prejmi(new Tretja.Asistent(), "as_NlSq5");
        t.prejmi(new Tretja.Asistent(), "as_D8lVb");
        t.prejmi(new Tretja.Docent(), "doc_b6Cin");
        t.prejmi(new Tretja.Profesor(), "prof_ctrzY");
        t.prejmi(new Tretja.Asistent(), "as_NYx6A");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_nbpPr");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_mq8WW");
        t.prejmi(new Tretja.Docent(), "doc_7BkoS");
        t.prejmi(new Tretja.Asistent(), "as_1Z57F");
        t.prejmi(new Tretja.Profesor(), "prof_Pau8I");
        t.prejmi(new Tretja.Profesor(), "prof_Fhm4x");
        t.prejmi(new Tretja.Docent(), "doc_yiHPz");
        t.prejmi(new Tretja.Docent(), "doc_3aSWZ");
        t.prejmi(new Tretja.Docent(), "doc_AuRZG");
        t.prejmi(new Tretja.Docent(), "doc_OtX0e");
        t.prejmi(new Tretja.Asistent(), "as_ybpk1");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_RRoos");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_vkdgu");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_PpP6I");
        t.prejmi(new Tretja.Asistent(), "as_jNX8o");
        t.prejmi(new Tretja.Docent(), "doc_k958t");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_lU8GH");
        t.prejmi(new Tretja.Asistent(), "as_0x9Oo");
        t.prejmi(new Tretja.Docent(), "doc_p57vB");
        t.prejmi(new Tretja.Docent(), "doc_ttj7R");
        t.prejmi(new Tretja.Asistent(), "as_Vl9BJ");
        t.prejmi(new Tretja.Profesor(), "prof_WqDxW");
        t.prejmi(new Tretja.Docent(), "doc_A2BdJ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_8Tdke");
        t.prejmi(new Tretja.Docent(), "doc_9VyLE");
        t.prejmi(new Tretja.Docent(), "doc_1z0Ga");
        t.prejmi(new Tretja.Docent(), "doc_MGHAP");
        t.prejmi(new Tretja.Asistent(), "as_dH8sH");
        t.prejmi(new Tretja.Docent(), "doc_8HIDd");
        t.prejmi(new Tretja.Asistent(), "as_pq5Fu");
        t.prejmi(new Tretja.Docent(), "doc_Ywb29");
        t.prejmi(new Tretja.Profesor(), "prof_k9p7j");
        t.prejmi(new Tretja.Docent(), "doc_UgZFF");
        t.prejmi(new Tretja.Profesor(), "prof_DOzIc");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_HebH5");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_GZ214");
        t.prejmi(new Tretja.Profesor(), "prof_WZt6d");
        t.prejmi(new Tretja.Docent(), "doc_JQerj");
        t.prejmi(new Tretja.Docent(), "doc_e7Q5E");
        t.prejmi(new Tretja.Asistent(), "as_4ea0E");
        t.prejmi(new Tretja.Asistent(), "as_UA22S");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_mcNBa");
        t.prejmi(new Tretja.Asistent(), "as_L08pY");
        t.prejmi(new Tretja.Asistent(), "as_LKxyV");
        t.prejmi(new Tretja.Docent(), "doc_KlE5G");
        t.prejmi(new Tretja.Docent(), "doc_BwxKP");
        t.prejmi(new Tretja.Profesor(), "prof_dFTeb");
        t.prejmi(new Tretja.Profesor(), "prof_AWnND");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_fTfeV");
        t.prejmi(new Tretja.Docent(), "doc_OaV9v");
        t.prejmi(new Tretja.Profesor(), "prof_vtLpI");
        t.prejmi(new Tretja.Asistent(), "as_fwaSg");
        t.prejmi(new Tretja.Docent(), "doc_XUUkq");
        t.prejmi(new Tretja.Asistent(), "as_UqAgx");
        t.prejmi(new Tretja.Docent(), "doc_QV4le");
        t.prejmi(new Tretja.Docent(), "doc_sICNn");
        t.prejmi(new Tretja.Profesor(), "prof_DcCdu");
        t.prejmi(new Tretja.Profesor(), "prof_Ty0Vy");
        t.prejmi(new Tretja.Asistent(), "as_OkhSD");
        t.prejmi(new Tretja.Docent(), "doc_oXOns");
        t.prejmi(new Tretja.Docent(), "doc_LCDOI");
        t.prejmi(new Tretja.Docent(), "doc_kLHx0");
        t.prejmi(new Tretja.Asistent(), "as_kQDEV");
        t.prejmi(new Tretja.Asistent(), "as_CNwjE");
        t.prejmi(new Tretja.Profesor(), "prof_Nl55C");
        t.prejmi(new Tretja.Asistent(), "as_RBZOH");
        t.prejmi(new Tretja.Docent(), "doc_FQNzs");
        t.prejmi(new Tretja.Asistent(), "as_RZtPI");
        t.prejmi(new Tretja.Docent(), "doc_fiUHo");
        t.prejmi(new Tretja.Asistent(), "as_9ZtTx");
        t.prejmi(new Tretja.Profesor(), "prof_2MZs3");
        t.prejmi(new Tretja.Asistent(), "as_UbNr4");
        t.prejmi(new Tretja.Docent(), "doc_9uIq9");
        t.prejmi(new Tretja.Docent(), "doc_OtKIj");
        t.prejmi(new Tretja.Asistent(), "as_NgFwH");
        t.prejmi(new Tretja.Docent(), "doc_gGJVX");
        t.prejmi(new Tretja.Profesor(), "prof_CAtvT");
        t.prejmi(new Tretja.Docent(), "doc_LBLYL");
        t.prejmi(new Tretja.Profesor(), "prof_8DogO");
        t.prejmi(new Tretja.Profesor(), "prof_mvE58");
        t.prejmi(new Tretja.Docent(), "doc_sYBm5");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_gYpt5");
        t.prejmi(new Tretja.Docent(), "doc_F0Hou");
        t.prejmi(new Tretja.Profesor(), "prof_PhrtG");
        t.prejmi(new Tretja.Docent(), "doc_jy0WY");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_luGkB");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_MbrPu");
        t.prejmi(new Tretja.Asistent(), "as_Phg5q");
        t.prejmi(new Tretja.Docent(), "doc_aMxix");
        t.prejmi(new Tretja.Profesor(), "prof_63QEg");
        t.prejmi(new Tretja.Asistent(), "as_DddOA");
        t.prejmi(new Tretja.Asistent(), "as_tiDLH");
        t.prejmi(new Tretja.Asistent(), "as_F3JgC");
        t.prejmi(new Tretja.Asistent(), "as_WHCwa");
        t.prejmi(new Tretja.Docent(), "doc_BsyLC");
        t.prejmi(new Tretja.Profesor(), "prof_y89au");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_aBTfB");
        t.prejmi(new Tretja.Profesor(), "prof_4JAuS");
        t.prejmi(new Tretja.Docent(), "doc_KtglW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_tyqbC");
        t.prejmi(new Tretja.Asistent(), "as_jAauZ");
        t.prejmi(new Tretja.Profesor(), "prof_CbhDe");
        t.prejmi(new Tretja.Asistent(), "as_7n5Gl");
        t.prejmi(new Tretja.Profesor(), "prof_oTSVt");
        t.prejmi(new Tretja.Asistent(), "as_5vDO0");
        t.prejmi(new Tretja.Docent(), "doc_FmN85");
        t.prejmi(new Tretja.Profesor(), "prof_pUPT9");
        t.prejmi(new Tretja.Asistent(), "as_NK3pa");
        t.prejmi(new Tretja.Asistent(), "as_zdb0f");
        t.prejmi(new Tretja.Profesor(), "prof_JItpZ");
        t.prejmi(new Tretja.Docent(), "doc_awY6o");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_7eTTf");
        t.prejmi(new Tretja.Docent(), "doc_4zvfJ");
        t.prejmi(new Tretja.Profesor(), "prof_Yv1E7");
        t.prejmi(new Tretja.Profesor(), "prof_nQeyw");
        t.prejmi(new Tretja.Profesor(), "prof_mLhxM");
        t.prejmi(new Tretja.Docent(), "doc_inImk");
        t.prejmi(new Tretja.Asistent(), "as_koLRn");
        t.prejmi(new Tretja.Profesor(), "prof_gl0gO");
        t.prejmi(new Tretja.Asistent(), "as_96bwM");
        t.prejmi(new Tretja.Profesor(), "prof_QGVRs");
        t.prejmi(new Tretja.Asistent(), "as_aO6FD");
        t.prejmi(new Tretja.Docent(), "doc_nrNK8");
        t.prejmi(new Tretja.Asistent(), "as_KWlz6");
        t.prejmi(new Tretja.Docent(), "doc_WlUut");
        t.prejmi(new Tretja.Profesor(), "prof_WBCHH");
    }
}
