
public class Test49 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_CIu00");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_euBR6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_PZgpb");
        t.prejmi(new Tretja.Docent(), "doc_hhQzT");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7oIgC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ZL6dq");
        t.prejmi(new Tretja.Asistent(), "as_tGdQx");
        t.prejmi(new Tretja.Docent(), "doc_uozs0");
        t.prejmi(new Tretja.Asistent(), "as_55dGi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_pyaOg");
        t.prejmi(new Tretja.Docent(), "doc_8KvQ8");
        t.prejmi(new Tretja.Profesor(), "prof_l2DYF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hISUu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_XSde2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_pjWtV");
        t.prejmi(new Tretja.Asistent(), "as_OWEMN");
        t.prejmi(new Tretja.Asistent(), "as_UY8kF");
        t.prejmi(new Tretja.Asistent(), "as_qaYLm");
        t.prejmi(new Tretja.Profesor(), "prof_BfSPu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_lzDDp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_stuCQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Kn4jP");
        t.prejmi(new Tretja.Docent(), "doc_tdJW5");
        t.prejmi(new Tretja.Asistent(), "as_H4U8z");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_qaOWG");
        t.prejmi(new Tretja.Profesor(), "prof_uMN6Y");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_tRtZm");
        t.prejmi(new Tretja.Profesor(), "prof_0ZhRc");
        t.prejmi(new Tretja.Docent(), "doc_VXrHc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_jVGYL");
        t.prejmi(new Tretja.Docent(), "doc_b1wNs");
        t.prejmi(new Tretja.Profesor(), "prof_pIu7Y");
        t.prejmi(new Tretja.Docent(), "doc_KcS6b");
        t.prejmi(new Tretja.Docent(), "doc_CCDn6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_rPPae");
        t.prejmi(new Tretja.Profesor(), "prof_ikIdo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_20nQJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ecSFK");
        t.prejmi(new Tretja.Docent(), "doc_Gl3C5");
        t.prejmi(new Tretja.Profesor(), "prof_XCgSa");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_h09Uu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wVIa9");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_05XGQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4mpO9");
        t.prejmi(new Tretja.Asistent(), "as_PPiRH");
        t.prejmi(new Tretja.Docent(), "doc_JZyx6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HwDip");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Wj4z6");
        t.prejmi(new Tretja.Docent(), "doc_fmxnj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_EXhI0");
        t.prejmi(new Tretja.Docent(), "doc_hoyU3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_IWbiv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TjWaY");
        t.prejmi(new Tretja.Profesor(), "prof_cDtv8");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5BN15");
        t.prejmi(new Tretja.Asistent(), "as_nxr8E");
        t.prejmi(new Tretja.Profesor(), "prof_ENrS5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_B0zcP");
        t.prejmi(new Tretja.Asistent(), "as_BslTL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_XKmOX");
        t.prejmi(new Tretja.Docent(), "doc_lAbID");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_z13i0");
        t.prejmi(new Tretja.Asistent(), "as_jyHhF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_5WdHH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_DQ51s");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Ceyhr");
        t.prejmi(new Tretja.Docent(), "doc_U42Zy");
        t.prejmi(new Tretja.Profesor(), "prof_k6VO3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pjfL3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_sVBFL");
        t.prejmi(new Tretja.Profesor(), "prof_EuGHU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_DjaD4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_71hab");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_zChuz");
        t.prejmi(new Tretja.Docent(), "doc_ltZ0T");
        t.prejmi(new Tretja.Asistent(), "as_j8n4c");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ybgIP");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_WIxKZ");
        t.prejmi(new Tretja.Profesor(), "prof_OswQr");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_gFDgq");
        t.prejmi(new Tretja.Docent(), "doc_2wBbV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_3XXox");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zaCIr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_bUy8K");
        t.prejmi(new Tretja.Profesor(), "prof_p2h9Z");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_b9F6o");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_T7Dgn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_L0BCI");
        t.prejmi(new Tretja.Profesor(), "prof_SoB5n");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JrsQz");
        t.prejmi(new Tretja.Profesor(), "prof_iAyik");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TLbFx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Sp8v6");
        t.prejmi(new Tretja.Asistent(), "as_2kGsv");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_CB8hT");
        t.prejmi(new Tretja.Docent(), "doc_b2tPg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rdZNJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XXx4c");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tbb0e");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_hOZLb");
        t.prejmi(new Tretja.Docent(), "doc_1vexX");
        t.prejmi(new Tretja.Profesor(), "prof_bNVp3");
        t.prejmi(new Tretja.Asistent(), "as_AZFGq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_psqlC");
        t.prejmi(new Tretja.Profesor(), "prof_IVuY2");
        t.prejmi(new Tretja.Docent(), "doc_3IyNa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_INdhg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_GPw33");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ugiYN");
        t.prejmi(new Tretja.Asistent(), "as_zoe16");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_zXmro");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_U3RLJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Te0ME");
        t.prejmi(new Tretja.Docent(), "doc_0Bs3m");
        t.prejmi(new Tretja.Profesor(), "prof_wsT7O");
        t.prejmi(new Tretja.Profesor(), "prof_mKC4s");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Y2UFY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_wvpOQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_3SKqt");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_uHd3A");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_xDpkJ");
        t.prejmi(new Tretja.Profesor(), "prof_pq4Kp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_2J6mR");
        t.prejmi(new Tretja.Profesor(), "prof_smjFV");
        t.prejmi(new Tretja.Asistent(), "as_ligdV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_UQs42");
        t.prejmi(new Tretja.Profesor(), "prof_WwVwx");
        t.prejmi(new Tretja.Docent(), "doc_0NzNx");
        t.prejmi(new Tretja.Asistent(), "as_fCgmH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_GEGRy");
        t.prejmi(new Tretja.Docent(), "doc_uapzr");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_QnLDx");
        t.prejmi(new Tretja.Docent(), "doc_3L05U");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xedzC");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Nkyeh");
        t.prejmi(new Tretja.Docent(), "doc_pLo42");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_AYAxW");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_FQfVt");
        t.prejmi(new Tretja.Profesor(), "prof_zaUBh");
        t.prejmi(new Tretja.Docent(), "doc_2QrUv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ugW7w");
        t.prejmi(new Tretja.Profesor(), "prof_o4LU2");
        t.prejmi(new Tretja.Asistent(), "as_1DaN4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_qRXpa");
        t.prejmi(new Tretja.Profesor(), "prof_wJ7o4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_qCQ81");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_R4IWV");
        t.prejmi(new Tretja.Docent(), "doc_y55uj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iHgjq");
        t.prejmi(new Tretja.Docent(), "doc_xMYAG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XtNvy");
        t.prejmi(new Tretja.Docent(), "doc_UUMno");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0I9PL");
        t.prejmi(new Tretja.Profesor(), "prof_mWQ3u");
        t.prejmi(new Tretja.Profesor(), "prof_6wp1Y");
        t.prejmi(new Tretja.Profesor(), "prof_MVXH8");
        t.prejmi(new Tretja.Docent(), "doc_3yoXQ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_w03YK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MQy1C");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JKJCM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_KfJv9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lmmUj");
        t.prejmi(new Tretja.Profesor(), "prof_2v7f2");
        t.prejmi(new Tretja.Profesor(), "prof_NM00J");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SaUp1");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_LyZco");
        t.prejmi(new Tretja.Docent(), "doc_9F5ku");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_SFMkQ");
        t.prejmi(new Tretja.Docent(), "doc_xO5o0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_EyfP2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_KFLrp");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wY9Os");
        t.prejmi(new Tretja.Docent(), "doc_hh3Gv");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_9a39I");
        t.prejmi(new Tretja.Docent(), "doc_BtOqJ");
        t.prejmi(new Tretja.Profesor(), "prof_Kx2XD");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7xLYu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_C64Jj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_oTWQd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_uamWn");
        t.prejmi(new Tretja.Asistent(), "as_N0tZ0");
        t.prejmi(new Tretja.Docent(), "doc_hlFtu");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_0KvQB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_zYwpo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_dx7ne");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_WV6Ch");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_tFKTn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_M3xmo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_CUJLK");
        t.prejmi(new Tretja.Profesor(), "prof_zMajj");
        t.prejmi(new Tretja.Asistent(), "as_m9Yqz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Bf3Du");
        t.prejmi(new Tretja.Asistent(), "as_OmoOI");
        t.prejmi(new Tretja.Profesor(), "prof_ZwNTP");
        t.prejmi(new Tretja.Asistent(), "as_pMx0y");
        t.prejmi(new Tretja.Asistent(), "as_RlUlk");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_hag0O");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_EQz9f");
        t.prejmi(new Tretja.Profesor(), "prof_8A09Z");
        t.prejmi(new Tretja.Asistent(), "as_KFJek");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_pY9cu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aT7RJ");
        t.prejmi(new Tretja.Docent(), "doc_AKHKq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_oSxnN");
        t.prejmi(new Tretja.Profesor(), "prof_8UHTw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ARssC");
        t.prejmi(new Tretja.Asistent(), "as_InaMd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_vnHCj");
        t.prejmi(new Tretja.Asistent(), "as_mCFj8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ENf0v");
        t.prejmi(new Tretja.Docent(), "doc_L0HWd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_GCXfH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hWL7K");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_I4AYe");
        t.prejmi(new Tretja.Profesor(), "prof_JeZ1N");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IY2qa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_9HZ6Z");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_sYvmc");
        t.prejmi(new Tretja.Docent(), "doc_xLfr0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_mWV0a");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_x3IHw");
        t.prejmi(new Tretja.Profesor(), "prof_X7PJ5");
        t.prejmi(new Tretja.Asistent(), "as_Twn5p");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_88sUX");
        t.prejmi(new Tretja.Profesor(), "prof_m64n0");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_M5TUB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_THiZg");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_UceBV");
        t.prejmi(new Tretja.Docent(), "doc_MzYw4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_h1ooB");
        t.prejmi(new Tretja.Docent(), "doc_pne9b");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_lq9xK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TVky2");
        t.prejmi(new Tretja.Profesor(), "prof_8XhsH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_NvsmH");
        t.prejmi(new Tretja.Asistent(), "as_5C4Mc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4AHUn");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QaTEY");
        t.prejmi(new Tretja.Docent(), "doc_JqsWO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_o3PMT");
        t.prejmi(new Tretja.Docent(), "doc_zRzU2");
        t.prejmi(new Tretja.Asistent(), "as_u1cxk");
        t.prejmi(new Tretja.Asistent(), "as_AIGPM");
        t.prejmi(new Tretja.Docent(), "doc_zzavw");
        t.prejmi(new Tretja.Profesor(), "prof_LA1mD");
        t.prejmi(new Tretja.Asistent(), "as_bemNZ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_jONeT");
        t.prejmi(new Tretja.Docent(), "doc_7tINS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RspnL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_w35Gu");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_n0dTy");
    }
}
