
public class Test24 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_CQZTj");
        t.prejmi(new Tretja.Asistent(), "as_XH9PH");
        t.prejmi(new Tretja.Asistent(), "as_yMVnx");
        t.prejmi(new Tretja.Asistent(), "as_AAmYp");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_iN270");
        t.prejmi(new Tretja.Docent(), "doc_l1H4q");
        t.prejmi(new Tretja.Profesor(), "prof_3Gif8");
        t.prejmi(new Tretja.Asistent(), "as_oSJQ4");
        t.prejmi(new Tretja.Asistent(), "as_DHj2J");
        t.prejmi(new Tretja.Asistent(), "as_Jc935");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_NLGw5");
        t.prejmi(new Tretja.Asistent(), "as_oxvOO");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_Yne28");
        t.prejmi(new Tretja.Profesor(), "prof_o0qfv");
        t.prejmi(new Tretja.Profesor(), "prof_J5wL4");
        t.prejmi(new Tretja.Docent(), "doc_uYTPG");
        t.prejmi(new Tretja.Profesor(), "prof_H4cga");
        t.prejmi(new Tretja.Docent(), "doc_i6Inz");
        t.prejmi(new Tretja.Asistent(), "as_ECiJG");
        t.prejmi(new Tretja.Profesor(), "prof_O262X");
        t.prejmi(new Tretja.Profesor(), "prof_ATtyF");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_BWTOk");
        t.prejmi(new Tretja.Asistent(), "as_FI5WD");
        t.prejmi(new Tretja.Profesor(), "prof_R39nN");
        t.prejmi(new Tretja.Asistent(), "as_8o5Ab");
        t.prejmi(new Tretja.Profesor(), "prof_GSlVW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_RFYEj");
        t.prejmi(new Tretja.Profesor(), "prof_CKGJK");
        t.prejmi(new Tretja.Profesor(), "prof_6U6MX");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_1371e");
        t.prejmi(new Tretja.Docent(), "doc_HVLkZ");
        t.prejmi(new Tretja.Docent(), "doc_N8L7S");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_iSuvb");
        t.prejmi(new Tretja.Docent(), "doc_ZZWBZ");
        t.prejmi(new Tretja.Asistent(), "as_YGVNk");
        t.prejmi(new Tretja.Profesor(), "prof_oqIoA");
        t.prejmi(new Tretja.Asistent(), "as_Lxn3g");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_MIYIY");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_k58eT");
        t.prejmi(new Tretja.Asistent(), "as_VUPEZ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_5L0si");
        t.prejmi(new Tretja.Profesor(), "prof_Xtcy2");
        t.prejmi(new Tretja.Docent(), "doc_kVQKl");
        t.prejmi(new Tretja.Docent(), "doc_uUl5h");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_LOX34");
        t.prejmi(new Tretja.Docent(), "doc_XLPkM");
        t.prejmi(new Tretja.Asistent(), "as_6IreJ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_mVU7Y");
        t.prejmi(new Tretja.Asistent(), "as_Ga4Ls");
        t.prejmi(new Tretja.Profesor(), "prof_snW5R");
        t.prejmi(new Tretja.Asistent(), "as_6jw1d");
        t.prejmi(new Tretja.Profesor(), "prof_iWCCc");
        t.prejmi(new Tretja.Asistent(), "as_JNImF");
        t.prejmi(new Tretja.Docent(), "doc_vMnKW");
        t.prejmi(new Tretja.Profesor(), "prof_u2sQV");
        t.prejmi(new Tretja.Docent(), "doc_DaoRo");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_RUayR");
        t.prejmi(new Tretja.Profesor(), "prof_Ypueg");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_Q0Ym8");
        t.prejmi(new Tretja.Asistent(), "as_hfBRj");
        t.prejmi(new Tretja.Docent(), "doc_d9Y4Z");
        t.prejmi(new Tretja.Docent(), "doc_6ZGaF");
        t.prejmi(new Tretja.Profesor(), "prof_VczWL");
        t.prejmi(new Tretja.Profesor(), "prof_lLRaW");
        t.prejmi(new Tretja.Profesor(), "prof_RHACy");
        t.prejmi(new Tretja.Profesor(), "prof_0lh5M");
        t.prejmi(new Tretja.Asistent(), "as_1pOj4");
        t.prejmi(new Tretja.Asistent(), "as_9ZPXF");
        t.prejmi(new Tretja.Docent(), "doc_yhSX2");
        t.prejmi(new Tretja.Profesor(), "prof_udtOa");
        t.prejmi(new Tretja.Asistent(), "as_lsGL5");
        t.prejmi(new Tretja.Profesor(), "prof_r4asy");
        t.prejmi(new Tretja.Asistent(), "as_vCzWu");
        t.prejmi(new Tretja.Asistent(), "as_x5Pdt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_fp7PX");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_1HwMP");
        t.prejmi(new Tretja.Docent(), "doc_o5myU");
        t.prejmi(new Tretja.Profesor(), "prof_Dxfln");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_o3s6z");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_9lmqk");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_rKtKI");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_36m4j");
        t.prejmi(new Tretja.Asistent(), "as_ZYoo1");
        t.prejmi(new Tretja.Docent(), "doc_XfoJ6");
        t.prejmi(new Tretja.Profesor(), "prof_fkMmE");
        t.prejmi(new Tretja.Profesor(), "prof_aKrCU");
        t.prejmi(new Tretja.Docent(), "doc_OYkyT");
        t.prejmi(new Tretja.Asistent(), "as_GdEqn");
        t.prejmi(new Tretja.Asistent(), "as_qEwz5");
        t.prejmi(new Tretja.Docent(), "doc_hLBEt");
        t.prejmi(new Tretja.Asistent(), "as_PgBs3");
        t.prejmi(new Tretja.Profesor(), "prof_W9fMj");
        t.prejmi(new Tretja.Docent(), "doc_YeVvh");
        t.prejmi(new Tretja.Docent(), "doc_QhBTh");
        t.prejmi(new Tretja.Docent(), "doc_82AGY");
        t.prejmi(new Tretja.Asistent(), "as_BQVJJ");
        t.prejmi(new Tretja.Asistent(), "as_QhgFv");
        t.prejmi(new Tretja.Asistent(), "as_2xiU4");
        t.prejmi(new Tretja.Profesor(), "prof_RnkxP");
        t.prejmi(new Tretja.Docent(), "doc_k4xrd");
        t.prejmi(new Tretja.Profesor(), "prof_4RyMq");
        t.prejmi(new Tretja.Docent(), "doc_GDchw");
        t.prejmi(new Tretja.Profesor(), "prof_EOJfX");
        t.prejmi(new Tretja.Asistent(), "as_JXi2g");
        t.prejmi(new Tretja.Asistent(), "as_s1QRF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_moRKR");
        t.prejmi(new Tretja.Docent(), "doc_GKGf4");
        t.prejmi(new Tretja.Docent(), "doc_0JP9C");
        t.prejmi(new Tretja.Profesor(), "prof_Bo2qo");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_jGju4");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_MeiuI");
        t.prejmi(new Tretja.Asistent(), "as_x4Bis");
        t.prejmi(new Tretja.Docent(), "doc_0Poeh");
        t.prejmi(new Tretja.Asistent(), "as_88HXm");
        t.prejmi(new Tretja.Asistent(), "as_pN3H0");
        t.prejmi(new Tretja.Asistent(), "as_JOcLn");
        t.prejmi(new Tretja.Profesor(), "prof_73lkY");
        t.prejmi(new Tretja.Docent(), "doc_PMtLQ");
        t.prejmi(new Tretja.Profesor(), "prof_aQD5Q");
        t.prejmi(new Tretja.Asistent(), "as_kDLkQ");
        t.prejmi(new Tretja.Asistent(), "as_PdQjr");
        t.prejmi(new Tretja.Docent(), "doc_N0VdP");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_MaC5N");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_sAy4M");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_SZDL7");
        t.prejmi(new Tretja.Profesor(), "prof_uhqlb");
        t.prejmi(new Tretja.Asistent(), "as_sAwOC");
        t.prejmi(new Tretja.Asistent(), "as_SJoSn");
        t.prejmi(new Tretja.Asistent(), "as_y5tJC");
        t.prejmi(new Tretja.Asistent(), "as_dwoVP");
        t.prejmi(new Tretja.Docent(), "doc_PiOo5");
        t.prejmi(new Tretja.Profesor(), "prof_txOHG");
        t.prejmi(new Tretja.Profesor(), "prof_BCsib");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_NpoFN");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_C9531");
        t.prejmi(new Tretja.Docent(), "doc_zNync");
        t.prejmi(new Tretja.Profesor(), "prof_KSevT");
        t.prejmi(new Tretja.Asistent(), "as_Hws70");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_OlrmI");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_T9lFA");
        t.prejmi(new Tretja.Asistent(), "as_A4irX");
        t.prejmi(new Tretja.Profesor(), "prof_9tmOA");
        t.prejmi(new Tretja.Profesor(), "prof_9JFKN");
        t.prejmi(new Tretja.Docent(), "doc_umNb4");
        t.prejmi(new Tretja.Profesor(), "prof_eJIMW");
        t.prejmi(new Tretja.Docent(), "doc_zJhBu");
        t.prejmi(new Tretja.Docent(), "doc_8p1aB");
        t.prejmi(new Tretja.Asistent(), "as_qQQJH");
        t.prejmi(new Tretja.Profesor(), "prof_amUcB");
        t.prejmi(new Tretja.Profesor(), "prof_3DOZf");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_ww4s6");
        t.prejmi(new Tretja.Docent(), "doc_nXQMu");
        t.prejmi(new Tretja.Profesor(), "prof_emRFE");
        t.prejmi(new Tretja.Profesor(), "prof_g7lqn");
        t.prejmi(new Tretja.Docent(), "doc_O2no2");
        t.prejmi(new Tretja.Profesor(), "prof_n2HeH");
        t.prejmi(new Tretja.Asistent(), "as_VDjpF");
        t.prejmi(new Tretja.Profesor(), "prof_x8dEX");
        t.prejmi(new Tretja.Profesor(), "prof_cMoFq");
        t.prejmi(new Tretja.Docent(), "doc_HkEzq");
        t.prejmi(new Tretja.Asistent(), "as_XGvAj");
        t.prejmi(new Tretja.Docent(), "doc_eDZVv");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_2XJux");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_uvLYC");
        t.prejmi(new Tretja.Docent(), "doc_c7JtY");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_I7kkG");
        t.prejmi(new Tretja.Profesor(), "prof_L3Xvz");
        t.prejmi(new Tretja.Docent(), "doc_RdKkl");
        t.prejmi(new Tretja.Docent(), "doc_KOd3s");
        t.prejmi(new Tretja.Profesor(), "prof_WHZ6m");
        t.prejmi(new Tretja.Profesor(), "prof_THE7T");
        t.prejmi(new Tretja.Asistent(), "as_6805C");
        t.prejmi(new Tretja.Asistent(), "as_DLs5S");
        t.prejmi(new Tretja.Docent(), "doc_sWErE");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_f1M8V");
        t.prejmi(new Tretja.Asistent(), "as_Bt0iF");
        t.prejmi(new Tretja.Asistent(), "as_qEah7");
        t.prejmi(new Tretja.Profesor(), "prof_a6PtI");
        t.prejmi(new Tretja.Asistent(), "as_fdgc6");
        t.prejmi(new Tretja.Asistent(), "as_AjQ6k");
        t.prejmi(new Tretja.Docent(), "doc_sR1dl");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_YKhMV");
        t.prejmi(new Tretja.Profesor(), "prof_52tyu");
        t.prejmi(new Tretja.Profesor(), "prof_iIYNE");
        t.prejmi(new Tretja.Profesor(), "prof_MMkqx");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_RYysS");
        t.prejmi(new Tretja.Docent(), "doc_7f8Pa");
        t.prejmi(new Tretja.Docent(), "doc_YrL0R");
        t.prejmi(new Tretja.Docent(), "doc_YluDp");
        t.prejmi(new Tretja.Profesor(), "prof_zfH5W");
        t.prejmi(new Tretja.Asistent(), "as_8OPG5");
        t.prejmi(new Tretja.Profesor(), "prof_wON9z");
        t.prejmi(new Tretja.Asistent(), "as_iLrX9");
        t.prejmi(new Tretja.Docent(), "doc_pv6Z3");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_Ddlgf");
    }
}
