
public class Test50 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_jOfgB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_PsDXs");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_e6llG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_zG2nK");
        t.prejmi(new Tretja.Asistent(), "as_tHWBm");
        t.prejmi(new Tretja.Docent(), "doc_XseVa");
        t.prejmi(new Tretja.Asistent(), "as_PnfpW");
        t.prejmi(new Tretja.Profesor(), "prof_jNseJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_L6uSp");
        t.prejmi(new Tretja.Profesor(), "prof_pWILb");
        t.prejmi(new Tretja.Asistent(), "as_lPzQb");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_UXjhv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_aX9TB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ji7tg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ovAsf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_E78Jl");
        t.prejmi(new Tretja.Asistent(), "as_Kb8ma");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IUgyB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_rFx3H");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Kp8wW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_xbOqN");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_M9Tpk");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_oMenR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_UXyc1");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_A2cRq");
        t.prejmi(new Tretja.Docent(), "doc_hG2C3");
        t.prejmi(new Tretja.Docent(), "doc_YcjQY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Fw9g7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ddOka");
        t.prejmi(new Tretja.Docent(), "doc_BLhDG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JU8c2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_FKGWj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8cSXY");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_2u5tY");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_0Mq4p");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_xmlA4");
        t.prejmi(new Tretja.Docent(), "doc_iGfvx");
        t.prejmi(new Tretja.Asistent(), "as_IOW7M");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_mwvqg");
        t.prejmi(new Tretja.Asistent(), "as_l3gYM");
        t.prejmi(new Tretja.Profesor(), "prof_BDS2O");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_R8agR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_5SOnc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_HsiDM");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_omPOr");
        t.prejmi(new Tretja.Profesor(), "prof_6ziVs");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_EEe1X");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_i3SA9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7LTuh");
        t.prejmi(new Tretja.Profesor(), "prof_vFP3Z");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kxnYp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_pYPqm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_by72B");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ZOz1h");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_2hupl");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_F8q8p");
        t.prejmi(new Tretja.Docent(), "doc_8xO27");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_SD6Ss");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TXrci");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_BRHMb");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_6Jp5x");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_RJbXO");
        t.prejmi(new Tretja.Docent(), "doc_3d9L4");
        t.prejmi(new Tretja.Docent(), "doc_RkgQ9");
        t.prejmi(new Tretja.Asistent(), "as_wbv4Q");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Jjxpz");
        t.prejmi(new Tretja.Asistent(), "as_wuBb6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_jdNwF");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_a8API");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_lmv8k");
        t.prejmi(new Tretja.Docent(), "doc_ATm76");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ym1BD");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_n8XDp");
        t.prejmi(new Tretja.Docent(), "doc_HF0gz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_akjb4");
        t.prejmi(new Tretja.Docent(), "doc_h9SNW");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_oDfsH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_RH1bc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_M7Jdb");
        t.prejmi(new Tretja.Asistent(), "as_jJt9i");
        t.prejmi(new Tretja.Asistent(), "as_c6E90");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_qP4AP");
        t.prejmi(new Tretja.Asistent(), "as_nNQpO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_GLCX4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_LtHec");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_CC9AR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ljI0l");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_aB8gu");
        t.prejmi(new Tretja.Profesor(), "prof_5EMmK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hQ6O1");
        t.prejmi(new Tretja.Profesor(), "prof_5JkZo");
        t.prejmi(new Tretja.Docent(), "doc_FfFM9");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iiZBe");
        t.prejmi(new Tretja.Docent(), "doc_DpPbv");
        t.prejmi(new Tretja.Profesor(), "prof_taydr");
        t.prejmi(new Tretja.Asistent(), "as_JGAtr");
        t.prejmi(new Tretja.Asistent(), "as_JPhva");
        t.prejmi(new Tretja.Docent(), "doc_w53Yx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_qzoup");
        t.prejmi(new Tretja.Profesor(), "prof_VixoF");
        t.prejmi(new Tretja.Docent(), "doc_Bg685");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_g89VJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_cH49c");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_AIHWu");
        t.prejmi(new Tretja.Docent(), "doc_SBQMN");
        t.prejmi(new Tretja.Asistent(), "as_sQ6dp");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JkEyy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_D5pJk");
        t.prejmi(new Tretja.Docent(), "doc_nYDUM");
        t.prejmi(new Tretja.Asistent(), "as_5oysi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vNvqo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_asHch");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_WHdfZ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_5oQ6c");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_rmXuV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ZtmE0");
        t.prejmi(new Tretja.Profesor(), "prof_ZgJST");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MggDS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_WnUr6");
        t.prejmi(new Tretja.Profesor(), "prof_kVZOh");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_DOYLc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XMqxt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_61txY");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_V2GPK");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_7iyHM");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TY6nW");
        t.prejmi(new Tretja.Docent(), "doc_tu0E8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_TMU50");
        t.prejmi(new Tretja.Profesor(), "prof_W6wBj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_6KM9d");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_30p0P");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tKKQk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_iiMqD");
        t.prejmi(new Tretja.Asistent(), "as_VQ0T3");
        t.prejmi(new Tretja.Profesor(), "prof_q4Iah");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_odcoK");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_ZX68O");
        t.prejmi(new Tretja.Asistent(), "as_ajY9p");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rjWuK");
        t.prejmi(new Tretja.Asistent(), "as_tdaxn");
        t.prejmi(new Tretja.Profesor(), "prof_m7DxW");
        t.prejmi(new Tretja.Profesor(), "prof_qWmTJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_i8hIm");
        t.prejmi(new Tretja.Profesor(), "prof_RL079");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_5BokG");
        t.prejmi(new Tretja.Docent(), "doc_564um");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_haDN5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_BaQw2");
        t.prejmi(new Tretja.Profesor(), "prof_vkDT8");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_cVLja");
        t.prejmi(new Tretja.Asistent(), "as_pqT9r");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_tN59P");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_sDSeN");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_QU9qT");
        t.prejmi(new Tretja.Profesor(), "prof_BSrJN");
        t.prejmi(new Tretja.Asistent(), "as_9wkML");
        t.prejmi(new Tretja.Profesor(), "prof_qckjP");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_d48C3");
        t.prejmi(new Tretja.Profesor(), "prof_IzbVS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TXkoy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ErCHR");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kkiqC");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_mtPcF");
        t.prejmi(new Tretja.Profesor(), "prof_R4rJE");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_QviXD");
        t.prejmi(new Tretja.Asistent(), "as_hhdHd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_OlvRW");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Zramc");
        t.prejmi(new Tretja.Profesor(), "prof_SDqE5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_F14VV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NQwQd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_cSnDs");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_OVpnS");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_6EQs1");
        t.prejmi(new Tretja.Profesor(), "prof_KV74G");
        t.prejmi(new Tretja.Asistent(), "as_XQhfj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_XX5dq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_yy4e7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NgpIF");
        t.prejmi(new Tretja.Docent(), "doc_mrzXd");
    }
}
