
public class Test05 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_8GmZx");
        t.prejmi(new Tretja.Asistent(), "as_lQF8H");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_pIfc4");
        t.prejmi(new Tretja.Asistent(), "as_KMz8g");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_i3TP7");
        t.prejmi(new Tretja.Profesor(), "prof_l7mv7");
        t.prejmi(new Tretja.Docent(), "doc_IdjTg");
        t.prejmi(new Tretja.Asistent(), "as_up88p");
        t.prejmi(new Tretja.Docent(), "doc_m9MC0");
        t.prejmi(new Tretja.Profesor(), "prof_Iyf8J");
        t.prejmi(new Tretja.Profesor(), "prof_kxTDa");
        t.prejmi(new Tretja.Asistent(), "as_W5BfA");
        t.prejmi(new Tretja.Asistent(), "as_LOibw");
        t.prejmi(new Tretja.Docent(), "doc_9hwzq");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_GfmeV");
        t.prejmi(new Tretja.Asistent(), "as_NumjO");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_5USi8");
        t.prejmi(new Tretja.Asistent(), "as_kRkm9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_mBL32");
        t.prejmi(new Tretja.Profesor(), "prof_e6BFU");
        t.prejmi(new Tretja.Profesor(), "prof_SEbML");
        t.prejmi(new Tretja.Asistent(), "as_UVS9h");
        t.prejmi(new Tretja.Profesor(), "prof_55B3j");
        t.prejmi(new Tretja.Asistent(), "as_yg8yz");
        t.prejmi(new Tretja.Profesor(), "prof_xKiwt");
        t.prejmi(new Tretja.Profesor(), "prof_b5z1X");
        t.prejmi(new Tretja.Docent(), "doc_dGcit");
        t.prejmi(new Tretja.Asistent(), "as_u4gHT");
        t.prejmi(new Tretja.Docent(), "doc_gNyia");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_iKmkM");
        t.prejmi(new Tretja.Profesor(), "prof_uYiJj");
        t.prejmi(new Tretja.Docent(), "doc_p0IJ7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_7GPpy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_JW5SU");
        t.prejmi(new Tretja.Profesor(), "prof_ePul6");
        t.prejmi(new Tretja.Asistent(), "as_qGnPj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_O5vW8");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_5Elsp");
        t.prejmi(new Tretja.Profesor(), "prof_8xXiV");
        t.prejmi(new Tretja.Profesor(), "prof_3jQt3");
        t.prejmi(new Tretja.Profesor(), "prof_6jBB8");
        t.prejmi(new Tretja.Docent(), "doc_hHfyz");
        t.prejmi(new Tretja.Docent(), "doc_ooAAV");
        t.prejmi(new Tretja.Profesor(), "prof_i1xIl");
        t.prejmi(new Tretja.Docent(), "doc_2tcPI");
        t.prejmi(new Tretja.Profesor(), "prof_fX4jK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_t4fmp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_OlQU4");
        t.prejmi(new Tretja.Docent(), "doc_rZMG0");
        t.prejmi(new Tretja.Docent(), "doc_TtO9c");
        t.prejmi(new Tretja.Profesor(), "prof_7eVEG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_QIdk4");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ANEdj");
        t.prejmi(new Tretja.Docent(), "doc_XVvLa");
        t.prejmi(new Tretja.Profesor(), "prof_KlXSa");
        t.prejmi(new Tretja.Profesor(), "prof_Fa7CK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_S0Bow");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_V7Jnn");
        t.prejmi(new Tretja.Asistent(), "as_vf9xw");
        t.prejmi(new Tretja.Profesor(), "prof_Pq1GH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_37QUW");
        t.prejmi(new Tretja.Docent(), "doc_FaSdp");
        t.prejmi(new Tretja.Docent(), "doc_Ng7qp");
        t.prejmi(new Tretja.Profesor(), "prof_aigH9");
        t.prejmi(new Tretja.Docent(), "doc_otx5W");
        t.prejmi(new Tretja.Profesor(), "prof_Myr1X");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_DBlmF");
        t.prejmi(new Tretja.Docent(), "doc_Op4K7");
        t.prejmi(new Tretja.Asistent(), "as_kw9bs");
        t.prejmi(new Tretja.Asistent(), "as_hexQy");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_ML3Md");
        t.prejmi(new Tretja.Profesor(), "prof_xSL4j");
        t.prejmi(new Tretja.Profesor(), "prof_FotdU");
        t.prejmi(new Tretja.Docent(), "doc_XC4Fy");
        t.prejmi(new Tretja.Docent(), "doc_zbrY1");
        t.prejmi(new Tretja.Docent(), "doc_n4msZ");
        t.prejmi(new Tretja.Asistent(), "as_L4GIK");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Kd85h");
        t.prejmi(new Tretja.Asistent(), "as_49ypN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_i1QQj");
        t.prejmi(new Tretja.Asistent(), "as_aZ1Tl");
        t.prejmi(new Tretja.Profesor(), "prof_sWtWb");
        t.prejmi(new Tretja.Docent(), "doc_I3Ngs");
        t.prejmi(new Tretja.Asistent(), "as_wUeiS");
        t.prejmi(new Tretja.Profesor(), "prof_auvLr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_YZXgQ");
        t.prejmi(new Tretja.Asistent(), "as_hPLSQ");
        t.prejmi(new Tretja.Profesor(), "prof_zyuyV");
        t.prejmi(new Tretja.Asistent(), "as_eJyAv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_s5KTd");
        t.prejmi(new Tretja.Asistent(), "as_G2fIz");
        t.prejmi(new Tretja.Profesor(), "prof_32ReV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JCHhp");
        t.prejmi(new Tretja.Docent(), "doc_aobO7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_azLqV");
        t.prejmi(new Tretja.Docent(), "doc_xKZrr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_FngeE");
        t.prejmi(new Tretja.Asistent(), "as_lCCb9");
        t.prejmi(new Tretja.Asistent(), "as_xymZE");
        t.prejmi(new Tretja.Asistent(), "as_T2SNg");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_UkJS6");
        t.prejmi(new Tretja.Docent(), "doc_iwkQA");
        t.prejmi(new Tretja.Docent(), "doc_44aNe");
        t.prejmi(new Tretja.Asistent(), "as_zAW0p");
        t.prejmi(new Tretja.Profesor(), "prof_c6eKd");
        t.prejmi(new Tretja.Profesor(), "prof_QKPDU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_40F04");
        t.prejmi(new Tretja.Profesor(), "prof_MCNTX");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_VmhUA");
        t.prejmi(new Tretja.Asistent(), "as_gLcXE");
        t.prejmi(new Tretja.Docent(), "doc_PMhCy");
        t.prejmi(new Tretja.Profesor(), "prof_mlA7b");
        t.prejmi(new Tretja.Asistent(), "as_Krc7p");
        t.prejmi(new Tretja.Profesor(), "prof_Pwcwf");
        t.prejmi(new Tretja.Docent(), "doc_tTILU");
        t.prejmi(new Tretja.Asistent(), "as_DF9PL");
        t.prejmi(new Tretja.Docent(), "doc_3uXhQ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_4s0Ms");
        t.prejmi(new Tretja.Profesor(), "prof_nHEs3");
        t.prejmi(new Tretja.Asistent(), "as_OTtbH");
        t.prejmi(new Tretja.Docent(), "doc_rwC8t");
        t.prejmi(new Tretja.Profesor(), "prof_uK4mj");
        t.prejmi(new Tretja.Docent(), "doc_JRCXC");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_7SduK");
        t.prejmi(new Tretja.Asistent(), "as_xwKyU");
        t.prejmi(new Tretja.Profesor(), "prof_i2b5d");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_xGZrQ");
        t.prejmi(new Tretja.Profesor(), "prof_QPEPV");
        t.prejmi(new Tretja.Asistent(), "as_G19uT");
        t.prejmi(new Tretja.Profesor(), "prof_EzNII");
        t.prejmi(new Tretja.Docent(), "doc_zGQx7");
        t.prejmi(new Tretja.Profesor(), "prof_cHbbh");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_TcI0L");
        t.prejmi(new Tretja.Profesor(), "prof_q98jv");
        t.prejmi(new Tretja.Asistent(), "as_QFnOn");
        t.prejmi(new Tretja.Profesor(), "prof_eJRV0");
        t.prejmi(new Tretja.Asistent(), "as_zeA9y");
        t.prejmi(new Tretja.Asistent(), "as_8W1xC");
        t.prejmi(new Tretja.Profesor(), "prof_iI50P");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_XnBIj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_O9dV0");
        t.prejmi(new Tretja.Profesor(), "prof_vVxkY");
        t.prejmi(new Tretja.Asistent(), "as_vYhAf");
        t.prejmi(new Tretja.Asistent(), "as_RL7hN");
        t.prejmi(new Tretja.Docent(), "doc_bUV8J");
        t.prejmi(new Tretja.Asistent(), "as_3Md0g");
        t.prejmi(new Tretja.Profesor(), "prof_RiOYe");
        t.prejmi(new Tretja.Asistent(), "as_Kt7j0");
        t.prejmi(new Tretja.Docent(), "doc_cSXKi");
        t.prejmi(new Tretja.Asistent(), "as_X501z");
        t.prejmi(new Tretja.Docent(), "doc_Gbsko");
        t.prejmi(new Tretja.Profesor(), "prof_GR1e8");
        t.prejmi(new Tretja.Asistent(), "as_FIOui");
        t.prejmi(new Tretja.Profesor(), "prof_Qs5AW");
        t.prejmi(new Tretja.Asistent(), "as_3SB0b");
        t.prejmi(new Tretja.Asistent(), "as_swW6g");
        t.prejmi(new Tretja.Profesor(), "prof_wxbVW");
        t.prejmi(new Tretja.Docent(), "doc_PxmTH");
        t.prejmi(new Tretja.Asistent(), "as_YWzZQ");
        t.prejmi(new Tretja.Docent(), "doc_ezV6r");
        t.prejmi(new Tretja.Docent(), "doc_QoX0V");
        t.prejmi(new Tretja.Asistent(), "as_vNirK");
        t.prejmi(new Tretja.Profesor(), "prof_85GNk");
        t.prejmi(new Tretja.Profesor(), "prof_U29QO");
        t.prejmi(new Tretja.Docent(), "doc_JcXfa");
        t.prejmi(new Tretja.Docent(), "doc_ALE7L");
        t.prejmi(new Tretja.Profesor(), "prof_jwY4x");
        t.prejmi(new Tretja.Asistent(), "as_oU25A");
        t.prejmi(new Tretja.Profesor(), "prof_vdxli");
        t.prejmi(new Tretja.Profesor(), "prof_TCszp");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_LzQtk");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_SJVqz");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_AgyIG");
        t.prejmi(new Tretja.Profesor(), "prof_LafKy");
        t.prejmi(new Tretja.Profesor(), "prof_AkN8O");
    }
}
