
public class Test48 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_wVloc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_sBugz");
        t.prejmi(new Tretja.Asistent(), "as_8SNOU");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_b0Qzk");
        t.prejmi(new Tretja.Profesor(), "prof_WlenA");
        t.prejmi(new Tretja.Asistent(), "as_A2zET");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_hgKd4");
        t.prejmi(new Tretja.Profesor(), "prof_zcnef");
        t.prejmi(new Tretja.Asistent(), "as_wfgAU");
        t.prejmi(new Tretja.Profesor(), "prof_DLBxu");
        t.prejmi(new Tretja.Docent(), "doc_wjRPP");
        t.prejmi(new Tretja.Docent(), "doc_4xi5Z");
        t.prejmi(new Tretja.Asistent(), "as_6N8vm");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_wSM04");
        t.prejmi(new Tretja.Docent(), "doc_t30Vi");
        t.prejmi(new Tretja.Docent(), "doc_4yxpN");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_mPhO1");
        t.prejmi(new Tretja.Profesor(), "prof_z1owx");
        t.prejmi(new Tretja.Asistent(), "as_iwGMq");
        t.prejmi(new Tretja.Asistent(), "as_OOu8y");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_a29Cr");
        t.prejmi(new Tretja.Profesor(), "prof_Riyum");
        t.prejmi(new Tretja.Profesor(), "prof_iXS0N");
        t.prejmi(new Tretja.Asistent(), "as_AjgtB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_bwGQm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_KbPak");
        t.prejmi(new Tretja.Asistent(), "as_xUbqK");
        t.prejmi(new Tretja.Asistent(), "as_7uoDk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Xf7lL");
        t.prejmi(new Tretja.Asistent(), "as_Pb7ee");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_oDHc4");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MsC1c");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Kl4rZ");
        t.prejmi(new Tretja.Docent(), "doc_O4pvc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_NTKRw");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_dDxN7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_jTfZx");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_aphSg");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_LyafE");
        t.prejmi(new Tretja.Docent(), "doc_vTAib");
        t.prejmi(new Tretja.Profesor(), "prof_ZvZf2");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vcXDi");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_h7CYH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RaFX3");
        t.prejmi(new Tretja.Profesor(), "prof_PHJdw");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zlKhO");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XnvoL");
        t.prejmi(new Tretja.Asistent(), "as_Dy1Sq");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_vIv1r");
        t.prejmi(new Tretja.Profesor(), "prof_BHpx3");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_JtVAW");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_CYKOZ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XHyoa");
        t.prejmi(new Tretja.Docent(), "doc_rFdW8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_fdHw7");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_nCsKe");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Npluv");
        t.prejmi(new Tretja.Profesor(), "prof_dsQ2T");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_DKcug");
        t.prejmi(new Tretja.Profesor(), "prof_lcsSB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uRBo4");
        t.prejmi(new Tretja.Docent(), "doc_2DMV4");
        t.prejmi(new Tretja.Asistent(), "as_JPYCg");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_fnzey");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Vwo94");
        t.prejmi(new Tretja.Asistent(), "as_ww0H6");
        t.prejmi(new Tretja.Docent(), "doc_mJrYi");
        t.prejmi(new Tretja.Profesor(), "prof_skZO0");
        t.prejmi(new Tretja.Asistent(), "as_X1COH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_hE04I");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5e13O");
        t.prejmi(new Tretja.Docent(), "doc_pX3Oq");
        t.prejmi(new Tretja.Docent(), "doc_ZltPV");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_5lPZa");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_sHCwH");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_vQupz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_eaZdV");
        t.prejmi(new Tretja.Asistent(), "as_eokZJ");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_92iHp");
        t.prejmi(new Tretja.Asistent(), "as_XJY0t");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_f1X5D");
        t.prejmi(new Tretja.Docent(), "doc_MGlkX");
        t.prejmi(new Tretja.Profesor(), "prof_mIjNA");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_8A8Ur");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_U7X1k");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NvlFg");
        t.prejmi(new Tretja.Docent(), "doc_2Auzi");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ggT2o");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_8JMvH");
        t.prejmi(new Tretja.Asistent(), "as_Ft82Z");
        t.prejmi(new Tretja.Docent(), "doc_HwrjB");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_UAu7E");
        t.prejmi(new Tretja.Docent(), "doc_UPqfJ");
        t.prejmi(new Tretja.Docent(), "doc_B2P81");
        t.prejmi(new Tretja.Asistent(), "as_AhRCj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_nKTDK");
        t.prejmi(new Tretja.Docent(), "doc_1mXhX");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_y1CcX");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_gAHEo");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Ec2Jv");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_nqReg");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_eYqnO");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_neI22");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_AgPeN");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_9yAX6");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_2TWIg");
        t.prejmi(new Tretja.Asistent(), "as_0ejuz");
        t.prejmi(new Tretja.Asistent(), "as_zyrje");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_pgECG");
        t.prejmi(new Tretja.Docent(), "doc_NXehc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_zU93y");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_p1oTt");
        t.prejmi(new Tretja.Asistent(), "as_YoPCT");
        t.prejmi(new Tretja.Docent(), "doc_BoXIz");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_frFtL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_gLHGG");
        t.prejmi(new Tretja.Asistent(), "as_Tfd8F");
        t.prejmi(new Tretja.Profesor(), "prof_vx8f4");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_rkqFs");
        t.prejmi(new Tretja.Profesor(), "prof_nPr8b");
        t.prejmi(new Tretja.Docent(), "doc_hpHkG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Elcs0");
        t.prejmi(new Tretja.Profesor(), "prof_UD69T");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_XJqKt");
        t.prejmi(new Tretja.Asistent(), "as_URA2Y");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_1KFrQ");
        t.prejmi(new Tretja.Asistent(), "as_Ph0AG");
        t.prejmi(new Tretja.Asistent(), "as_M3NUf");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_bmltR");
        t.prejmi(new Tretja.Docent(), "doc_242a2");
        t.prejmi(new Tretja.Docent(), "doc_K9uc6");
        t.prejmi(new Tretja.Profesor(), "prof_SuGXJ");
        t.prejmi(new Tretja.Profesor(), "prof_QD9sL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_LUeRm");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_RXkXF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kc7fl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_MORMz");
        t.prejmi(new Tretja.Asistent(), "as_5ZV7A");
        t.prejmi(new Tretja.Docent(), "doc_FhTKk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_4WOIU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_LBjQr");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_uWerd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_kxpuN");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_W3qO0");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_JWabR");
        t.prejmi(new Tretja.Profesor(), "prof_zK9Wd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_l5ilA");
        t.prejmi(new Tretja.Profesor(), "prof_KB5vT");
        t.prejmi(new Tretja.Docent(), "doc_dirwz");
        t.prejmi(new Tretja.Profesor(), "prof_XsFKy");
        t.prejmi(new Tretja.Docent(), "doc_H6FGx");
        t.prejmi(new Tretja.Profesor(), "prof_Dltco");
        t.prejmi(new Tretja.Docent(), "doc_mVy0p");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_GV7a8");
        t.prejmi(new Tretja.Asistent(), "as_shpso");
        t.prejmi(new Tretja.Profesor(), "prof_MQPHI");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_qVdXV");
        t.prejmi(new Tretja.Asistent(), "as_W4PbX");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_mgPf5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_go2Xt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4LqNb");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_h5bsi");
        t.prejmi(new Tretja.Docent(), "doc_h3HNb");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_30UcG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_IyN4X");
        t.prejmi(new Tretja.Asistent(), "as_kBH7n");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_84lOI");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_r3pgB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_CRIq7");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_KFqnT");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_kXGKN");
        t.prejmi(new Tretja.Profesor(), "prof_cVNL7");
        t.prejmi(new Tretja.Profesor(), "prof_6BAD4");
        t.prejmi(new Tretja.Profesor(), "prof_WJBn5");
        t.prejmi(new Tretja.Docent(), "doc_LcVtD");
        t.prejmi(new Tretja.Docent(), "doc_B6SFC");
        t.prejmi(new Tretja.Docent(), "doc_Mw9hd");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_RCa9f");
        t.prejmi(new Tretja.Docent(), "doc_LEj2X");
        t.prejmi(new Tretja.Asistent(), "as_yOjx0");
        t.prejmi(new Tretja.Docent(), "doc_k7OQ6");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_GkRNF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_TTRor");
        t.prejmi(new Tretja.Docent(), "doc_iiqok");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_aGNt3");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_GmhfT");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_uBrH2");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_AT3oE");
        t.prejmi(new Tretja.Docent(), "doc_cFTsz");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_W0cUJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_iXCNj");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_hAIqc");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_ejQL5");
        t.prejmi(new Tretja.Asistent(), "as_Cms6Q");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_gZeGP");
        t.prejmi(new Tretja.Asistent(), "as_9Q5j4");
        t.prejmi(new Tretja.Asistent(), "as_oU3dg");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_6uP05");
        t.prejmi(new Tretja.Asistent(), "as_qFymh");
        t.prejmi(new Tretja.Profesor(), "prof_yEDoZ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_41xfl");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_DcjuV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_ztjgG");
        t.prejmi(new Tretja.Profesor(), "prof_Z8J7Z");
        t.prejmi(new Tretja.Asistent(), "as_jZdzc");
        t.prejmi(new Tretja.Asistent(), "as_HXnPW");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_mIssJ");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_OAxIG");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_iTmDH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_VpKlu");
        t.prejmi(new Tretja.Asistent(), "as_kQpxA");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_HCn2b");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_y34n5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_wzDkm");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NwQji");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_yRSep");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_4tMPd");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_z5cdI");
        t.prejmi(new Tretja.Docent(), "doc_2zcov");
        t.prejmi(new Tretja.Asistent(), "as_dtUik");
        t.prejmi(new Tretja.Docent(), "doc_vOoYd");
        t.prejmi(new Tretja.Asistent(), "as_A1lfF");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_uVZR5");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_sxP2f");
        t.prejmi(new Tretja.Asistent(), "as_7W9eG");
        t.prejmi(new Tretja.Profesor(), "prof_8UjqB");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_y3Tpt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_jUMtv");
        t.prejmi(new Tretja.Docent(), "doc_PvXmR");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_Pn2AW");
        t.prejmi(new Tretja.Profesor(), "prof_Pl7Ff");
        t.prejmi(new Tretja.Profesor(), "prof_YKxsL");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_Gm6ta");
        t.prejmi(new Tretja.Docent(), "doc_pshY8");
    }
}
