
public class Test06 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_xbYNV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_LLuav");
        t.prejmi(new Tretja.Profesor(), "prof_HMksV");
        t.prejmi(new Tretja.Profesor(), "prof_MfOvt");
        t.prejmi(new Tretja.Profesor(), "prof_77Tpq");
        t.prejmi(new Tretja.Profesor(), "prof_VoPz5");
        t.prejmi(new Tretja.Profesor(), "prof_ayAk7");
        t.prejmi(new Tretja.Profesor(), "prof_TrXXK");
        t.prejmi(new Tretja.Profesor(), "prof_uN4id");
        t.prejmi(new Tretja.Asistent(), "as_x39HV");
        t.prejmi(new Tretja.Docent(), "doc_REOpD");
        t.prejmi(new Tretja.Asistent(), "as_8naiN");
        t.prejmi(new Tretja.Profesor(), "prof_i4vJt");
        t.prejmi(new Tretja.Asistent(), "as_ZukOG");
        t.prejmi(new Tretja.Docent(), "doc_b5AyP");
        t.prejmi(new Tretja.Asistent(), "as_dEZmK");
        t.prejmi(new Tretja.Profesor(), "prof_BfED7");
        t.prejmi(new Tretja.Asistent(), "as_YOli1");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_KJ1C6");
        t.prejmi(new Tretja.Profesor(), "prof_5PhyX");
        t.prejmi(new Tretja.Profesor(), "prof_KyFkJ");
        t.prejmi(new Tretja.Profesor(), "prof_ROS6H");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_iSgkf");
        t.prejmi(new Tretja.Asistent(), "as_G3jfJ");
        t.prejmi(new Tretja.Asistent(), "as_rETRS");
        t.prejmi(new Tretja.Docent(), "doc_pHIBh");
        t.prejmi(new Tretja.Docent(), "doc_oxLJ8");
        t.prejmi(new Tretja.Profesor(), "prof_dN9WC");
        t.prejmi(new Tretja.Asistent(), "as_zx7a4");
        t.prejmi(new Tretja.Profesor(), "prof_Sfvul");
        t.prejmi(new Tretja.Docent(), "doc_fpVqk");
        t.prejmi(new Tretja.Asistent(), "as_nHzJm");
        t.prejmi(new Tretja.Docent(), "doc_edOff");
        t.prejmi(new Tretja.Asistent(), "as_9fC0C");
        t.prejmi(new Tretja.Docent(), "doc_bJoAJ");
        t.prejmi(new Tretja.Profesor(), "prof_1jraa");
        t.prejmi(new Tretja.Docent(), "doc_UgTY8");
        t.prejmi(new Tretja.Docent(), "doc_Pu6Jd");
        t.prejmi(new Tretja.Profesor(), "prof_U6GBm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_dJWbV");
        t.prejmi(new Tretja.Profesor(), "prof_eDUyu");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_334RP");
        t.prejmi(new Tretja.Asistent(), "as_GB5yO");
        t.prejmi(new Tretja.Asistent(), "as_Uvntk");
        t.prejmi(new Tretja.Profesor(), "prof_9RRrG");
        t.prejmi(new Tretja.Profesor(), "prof_9uuEL");
        t.prejmi(new Tretja.Docent(), "doc_7clWi");
        t.prejmi(new Tretja.Profesor(), "prof_mJuAY");
        t.prejmi(new Tretja.Profesor(), "prof_ggyOF");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_4c5MS");
        t.prejmi(new Tretja.Docent(), "doc_VyxlE");
        t.prejmi(new Tretja.Docent(), "doc_5Fr7W");
        t.prejmi(new Tretja.Asistent(), "as_Thjwb");
        t.prejmi(new Tretja.Profesor(), "prof_7yzZw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_bsS4i");
        t.prejmi(new Tretja.Asistent(), "as_qz3KF");
        t.prejmi(new Tretja.Profesor(), "prof_2qusB");
        t.prejmi(new Tretja.Asistent(), "as_8pXak");
        t.prejmi(new Tretja.Profesor(), "prof_WJ5AE");
        t.prejmi(new Tretja.Docent(), "doc_QtfWx");
        t.prejmi(new Tretja.Docent(), "doc_ypSKC");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ot5ds");
        t.prejmi(new Tretja.Asistent(), "as_U3vMw");
        t.prejmi(new Tretja.Docent(), "doc_jaqS5");
        t.prejmi(new Tretja.Asistent(), "as_hgYIP");
        t.prejmi(new Tretja.Profesor(), "prof_7g4yP");
        t.prejmi(new Tretja.Profesor(), "prof_NVTE9");
        t.prejmi(new Tretja.Docent(), "doc_SRsll");
        t.prejmi(new Tretja.Docent(), "doc_vrPJV");
        t.prejmi(new Tretja.Asistent(), "as_HJl6n");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_vbMIE");
        t.prejmi(new Tretja.Profesor(), "prof_mksLE");
        t.prejmi(new Tretja.Docent(), "doc_vxdmL");
        t.prejmi(new Tretja.Profesor(), "prof_0BTAq");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_kfwaz");
        t.prejmi(new Tretja.Asistent(), "as_IOCk0");
        t.prejmi(new Tretja.Asistent(), "as_86y9M");
        t.prejmi(new Tretja.Asistent(), "as_a6lZt");
        t.prejmi(new Tretja.Asistent(), "as_cLZwT");
        t.prejmi(new Tretja.Profesor(), "prof_6zBnH");
        t.prejmi(new Tretja.Profesor(), "prof_nYVSF");
        t.prejmi(new Tretja.Profesor(), "prof_q4CUO");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_2avHV");
        t.prejmi(new Tretja.Docent(), "doc_Z6tTJ");
        t.prejmi(new Tretja.Asistent(), "as_R32q4");
        t.prejmi(new Tretja.Profesor(), "prof_ostLS");
        t.prejmi(new Tretja.Asistent(), "as_G0nty");
        t.prejmi(new Tretja.Asistent(), "as_YGMUb");
        t.prejmi(new Tretja.Asistent(), "as_I7mtw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_j3xJH");
        t.prejmi(new Tretja.Asistent(), "as_50Bmj");
        t.prejmi(new Tretja.Docent(), "doc_LcBYR");
        t.prejmi(new Tretja.Profesor(), "prof_zoe3d");
        t.prejmi(new Tretja.Docent(), "doc_2SelT");
        t.prejmi(new Tretja.Docent(), "doc_PwQ3i");
        t.prejmi(new Tretja.Profesor(), "prof_3DFvb");
        t.prejmi(new Tretja.Asistent(), "as_lUqe0");
        t.prejmi(new Tretja.Profesor(), "prof_U0lxl");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_GR005");
        t.prejmi(new Tretja.Profesor(), "prof_d9h1u");
        t.prejmi(new Tretja.Docent(), "doc_AuHnZ");
        t.prejmi(new Tretja.Docent(), "doc_cAfTs");
        t.prejmi(new Tretja.Docent(), "doc_SGwqy");
        t.prejmi(new Tretja.Profesor(), "prof_k9Lim");
        t.prejmi(new Tretja.Docent(), "doc_zFFmO");
        t.prejmi(new Tretja.Asistent(), "as_izMa9");
        t.prejmi(new Tretja.Docent(), "doc_6pamM");
        t.prejmi(new Tretja.Asistent(), "as_YFT3a");
        t.prejmi(new Tretja.Profesor(), "prof_fhzed");
        t.prejmi(new Tretja.Docent(), "doc_v3l1a");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Kt0Q9");
        t.prejmi(new Tretja.Docent(), "doc_yIFb4");
        t.prejmi(new Tretja.Profesor(), "prof_FIMO4");
        t.prejmi(new Tretja.Profesor(), "prof_ubi0m");
        t.prejmi(new Tretja.Profesor(), "prof_wFidx");
        t.prejmi(new Tretja.Docent(), "doc_gaOEa");
        t.prejmi(new Tretja.Profesor(), "prof_YCPeN");
        t.prejmi(new Tretja.Asistent(), "as_gjDVS");
        t.prejmi(new Tretja.Asistent(), "as_WgxN9");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Dw8Qj");
        t.prejmi(new Tretja.Asistent(), "as_mtPRH");
        t.prejmi(new Tretja.Docent(), "doc_5hqm3");
        t.prejmi(new Tretja.Docent(), "doc_utMi0");
        t.prejmi(new Tretja.Profesor(), "prof_La75o");
        t.prejmi(new Tretja.Asistent(), "as_WqXQu");
        t.prejmi(new Tretja.Asistent(), "as_rgY2f");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_gXs1f");
        t.prejmi(new Tretja.Profesor(), "prof_jIoK8");
        t.prejmi(new Tretja.Asistent(), "as_yPpVe");
        t.prejmi(new Tretja.Profesor(), "prof_jaRqW");
        t.prejmi(new Tretja.Profesor(), "prof_qy3Oa");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_2WMon");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_9zRmB");
        t.prejmi(new Tretja.Profesor(), "prof_ghIGw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_7cPBw");
        t.prejmi(new Tretja.Asistent(), "as_rztpv");
        t.prejmi(new Tretja.Docent(), "doc_XlK5G");
        t.prejmi(new Tretja.Asistent(), "as_0SgGF");
        t.prejmi(new Tretja.Profesor(), "prof_70RdZ");
        t.prejmi(new Tretja.Profesor(), "prof_cQLt4");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_A4nZj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_eZuCs");
        t.prejmi(new Tretja.Profesor(), "prof_LmiNn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_9eVhX");
        t.prejmi(new Tretja.Asistent(), "as_RSMs8");
        t.prejmi(new Tretja.Asistent(), "as_Hv7SV");
        t.prejmi(new Tretja.Profesor(), "prof_1pUBT");
        t.prejmi(new Tretja.Docent(), "doc_oRfsD");
        t.prejmi(new Tretja.Profesor(), "prof_bEZyF");
        t.prejmi(new Tretja.Profesor(), "prof_NyKki");
        t.prejmi(new Tretja.Docent(), "doc_ecjRn");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_aZ0Pq");
        t.prejmi(new Tretja.Asistent(), "as_wIoFL");
        t.prejmi(new Tretja.Asistent(), "as_cJuyU");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_a8COn");
        t.prejmi(new Tretja.Asistent(), "as_nP6d4");
        t.prejmi(new Tretja.Docent(), "doc_TM6L4");
        t.prejmi(new Tretja.Asistent(), "as_lHVkO");
        t.prejmi(new Tretja.Asistent(), "as_Rg11R");
        t.prejmi(new Tretja.Asistent(), "as_1zOB7");
        t.prejmi(new Tretja.Profesor(), "prof_gbs1F");
        t.prejmi(new Tretja.Asistent(), "as_Shz4E");
        t.prejmi(new Tretja.Asistent(), "as_kicDo");
        t.prejmi(new Tretja.Profesor(), "prof_dKrwD");
        t.prejmi(new Tretja.Docent(), "doc_UFmDP");
        t.prejmi(new Tretja.Profesor(), "prof_1l3JC");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JLWv0");
        t.prejmi(new Tretja.Asistent(), "as_JuqvF");
        t.prejmi(new Tretja.Asistent(), "as_lwsZC");
        t.prejmi(new Tretja.Docent(), "doc_3Sibz");
        t.prejmi(new Tretja.Docent(), "doc_fIKxf");
        t.prejmi(new Tretja.Profesor(), "prof_fNpFh");
        t.prejmi(new Tretja.Asistent(), "as_7M62L");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_aDVF8");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_JZCWh");
        t.prejmi(new Tretja.Profesor(), "prof_irojj");
        t.prejmi(new Tretja.Docent(), "doc_6r7bi");
        t.prejmi(new Tretja.Docent(), "doc_ypFKC");
        t.prejmi(new Tretja.Docent(), "doc_ihu4f");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_narTy");
        t.prejmi(new Tretja.Asistent(), "as_B3cVS");
        t.prejmi(new Tretja.Profesor(), "prof_tkMc3");
        t.prejmi(new Tretja.Docent(), "doc_GTIn1");
        t.prejmi(new Tretja.Asistent(), "as_RlAy1");
        t.prejmi(new Tretja.Profesor(), "prof_7NPjC");
        t.prejmi(new Tretja.Docent(), "doc_J7fCe");
        t.prejmi(new Tretja.Profesor(), "prof_AB7zg");
        t.prejmi(new Tretja.Docent(), "doc_vU4Na");
        t.prejmi(new Tretja.Profesor(), "prof_8YuVt");
        t.prejmi(new Tretja.Asistent(), "as_YynRX");
        t.prejmi(new Tretja.Docent(), "doc_pNNeT");
        t.prejmi(new Tretja.Docent(), "doc_kboXW");
        t.prejmi(new Tretja.Asistent(), "as_vR5bj");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_ZSLdU");
        t.prejmi(new Tretja.Profesor(), "prof_qLsEr");
        t.prejmi(new Tretja.Docent(), "doc_5XsWo");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_DeMLf");
        t.prejmi(new Tretja.Profesor(), "prof_1tqj5");
        t.prejmi(new Tretja.Profesor(), "prof_nUF2Q");
        t.prejmi(new Tretja.Asistent(), "as_metrV");
        t.prejmi(new Tretja.Docent(), "doc_l2Ba6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_8gGZY");
        t.prejmi(new Tretja.Asistent(), "as_GNMFx");
        t.prejmi(new Tretja.Docent(), "doc_14l3E");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Agx81");
        t.prejmi(new Tretja.Profesor(), "prof_AtAlP");
        t.prejmi(new Tretja.Profesor(), "prof_SWCBx");
        t.prejmi(new Tretja.Asistent(), "as_T0pYP");
        t.prejmi(new Tretja.Asistent(), "as_rAeJe");
        t.prejmi(new Tretja.Asistent(), "as_drNrd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_CCJjO");
        t.prejmi(new Tretja.Profesor(), "prof_SkqKe");
        t.prejmi(new Tretja.Profesor(), "prof_PE0Jr");
        t.prejmi(new Tretja.Profesor(), "prof_dp9Rr");
        t.prejmi(new Tretja.Profesor(), "prof_xWxPv");
        t.prejmi(new Tretja.Asistent(), "as_HMM8t");
        t.prejmi(new Tretja.Docent(), "doc_dEDcA");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_0FAcU");
        t.prejmi(new Tretja.Docent(), "doc_5ouoq");
        t.prejmi(new Tretja.Profesor(), "prof_tJIzm");
        t.prejmi(new Tretja.Asistent(), "as_YaJQd");
        t.prejmi(new Tretja.Profesor(), "prof_rKdC2");
        t.prejmi(new Tretja.Profesor(), "prof_dILOe");
        t.prejmi(new Tretja.Profesor(), "prof_tJllC");
        t.prejmi(new Tretja.Asistent(), "as_xjigq");
        t.prejmi(new Tretja.Docent(), "doc_3SAAM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_D30Jz");
        t.prejmi(new Tretja.Docent(), "doc_Y0fom");
        t.prejmi(new Tretja.Profesor(), "prof_JlsIg");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_fYDZO");
        t.prejmi(new Tretja.Profesor(), "prof_h6qJZ");
        t.prejmi(new Tretja.Asistent(), "as_ax1Js");
        t.prejmi(new Tretja.Asistent(), "as_5kttt");
        t.prejmi(new Tretja.Profesor(), "prof_smNnb");
        t.prejmi(new Tretja.Docent(), "doc_3RfUV");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_m86VH");
        t.prejmi(new Tretja.Docent(), "doc_RpVPh");
        t.prejmi(new Tretja.Docent(), "doc_PWa62");
        t.prejmi(new Tretja.Profesor(), "prof_0GM0k");
        t.prejmi(new Tretja.Asistent(), "as_8n4KB");
        t.prejmi(new Tretja.Profesor(), "prof_hNril");
        t.prejmi(new Tretja.Docent(), "doc_zPLQW");
        t.prejmi(new Tretja.Profesor(), "prof_FVZFT");
        t.prejmi(new Tretja.Docent(), "doc_bvrMv");
        t.prejmi(new Tretja.Profesor(), "prof_QU4Vu");
        t.prejmi(new Tretja.Profesor(), "prof_LtPcP");
        t.prejmi(new Tretja.Profesor(), "prof_2Olmt");
        t.prejmi(new Tretja.Asistent(), "as_oZZzG");
        t.prejmi(new Tretja.Profesor(), "prof_lSHyU");
        t.prejmi(new Tretja.Docent(), "doc_wlEeD");
        t.prejmi(new Tretja.Profesor(), "prof_VWG6w");
        t.prejmi(new Tretja.Docent(), "doc_m0Nba");
        t.prejmi(new Tretja.Docent(), "doc_4cGIs");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_xcjLj");
        t.prejmi(new Tretja.Docent(), "doc_IOW7u");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_A9Ih2");
        t.prejmi(new Tretja.Docent(), "doc_go3nx");
        t.prejmi(new Tretja.Docent(), "doc_tdg0j");
        t.prejmi(new Tretja.Docent(), "doc_RZurz");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_Zp0tN");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_sQNG4");
        t.prejmi(new Tretja.Docent(), "doc_xnyyF");
        t.prejmi(new Tretja.Asistent(), "as_PQdDU");
        t.prejmi(new Tretja.Profesor(), "prof_WssuB");
        t.prejmi(new Tretja.Docent(), "doc_zwITg");
        t.prejmi(new Tretja.Asistent(), "as_6W4Fp");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_hRo8M");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_9fqVu");
        t.prejmi(new Tretja.Profesor(), "prof_8nZY0");
        t.prejmi(new Tretja.Profesor(), "prof_6fTp3");
        t.prejmi(new Tretja.Profesor(), "prof_vgpEz");
        t.prejmi(new Tretja.Asistent(), "as_PAUVI");
        t.prejmi(new Tretja.Asistent(), "as_ZCYVT");
        t.prejmi(new Tretja.Docent(), "doc_aeKVn");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_J4zBp");
        t.prejmi(new Tretja.Asistent(), "as_4vthN");
        t.prejmi(new Tretja.Asistent(), "as_e1H0F");
        t.prejmi(new Tretja.Docent(), "doc_uuOEr");
        t.prejmi(new Tretja.Asistent(), "as_ln2r5");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_6VFlA");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_yCvRy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_oXi1E");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_lm2Z3");
        t.prejmi(new Tretja.Profesor(), "prof_4ay6T");
        t.prejmi(new Tretja.Asistent(), "as_KH8W7");
        t.prejmi(new Tretja.Profesor(), "prof_N2OK8");
        t.prejmi(new Tretja.Docent(), "doc_2VuT5");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_qZedd");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_GQfSm");
        t.prejmi(new Tretja.Docent(), "doc_zZIEB");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_K8uz0");
        t.prejmi(new Tretja.Profesor(), "prof_miBpt");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Z9wku");
        t.prejmi(new Tretja.Docent(), "doc_4av9C");
        t.prejmi(new Tretja.Docent(), "doc_xIczI");
        t.prejmi(new Tretja.Profesor(), "prof_vPFTX");
        t.prejmi(new Tretja.Asistent(), "as_tvADD");
        t.prejmi(new Tretja.Docent(), "doc_Ssgdy");
        t.prejmi(new Tretja.Profesor(), "prof_Cwn9i");
        t.prejmi(new Tretja.Docent(), "doc_aJchZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_yVbvD");
        t.prejmi(new Tretja.Docent(), "doc_yf5tO");
        t.prejmi(new Tretja.Docent(), "doc_dvTj8");
        t.prejmi(new Tretja.Asistent(), "as_Cn8FG");
        t.prejmi(new Tretja.Profesor(), "prof_tKkJr");
        t.prejmi(new Tretja.Docent(), "doc_ImPwv");
    }
}
