
public class Test21 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_TWAZm");
        t.prejmi(new Tretja.Profesor(), "prof_d7zmr");
        t.prejmi(new Tretja.Profesor(), "prof_1jKEd");
        t.prejmi(new Tretja.Docent(), "doc_6cPhx");
        t.prejmi(new Tretja.Asistent(), "as_hGmT4");
        t.prejmi(new Tretja.Asistent(), "as_kNB46");
        t.prejmi(new Tretja.Asistent(), "as_6RH4c");
        t.prejmi(new Tretja.Docent(), "doc_arEbL");
        t.prejmi(new Tretja.Profesor(), "prof_NbLWL");
        t.prejmi(new Tretja.Profesor(), "prof_oRPc4");
        t.prejmi(new Tretja.Profesor(), "prof_cyHqf");
        t.prejmi(new Tretja.Docent(), "doc_w4GwE");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_dkY5p");
        t.prejmi(new Tretja.Docent(), "doc_8xZvD");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_J1Of8");
        t.prejmi(new Tretja.Profesor(), "prof_fe2oc");
        t.prejmi(new Tretja.Docent(), "doc_fh4vb");
        t.prejmi(new Tretja.Asistent(), "as_Ut4cM");
        t.prejmi(new Tretja.Docent(), "doc_pAD7r");
        t.prejmi(new Tretja.Profesor(), "prof_ucfyz");
        t.prejmi(new Tretja.Profesor(), "prof_CzWfh");
        t.prejmi(new Tretja.Profesor(), "prof_KVCmh");
        t.prejmi(new Tretja.Profesor(), "prof_RWAc8");
        t.prejmi(new Tretja.Asistent(), "as_wqS72");
        t.prejmi(new Tretja.Docent(), "doc_6PgcU");
        t.prejmi(new Tretja.Profesor(), "prof_7SQ2v");
        t.prejmi(new Tretja.Asistent(), "as_DPyxf");
        t.prejmi(new Tretja.Profesor(), "prof_jXdAc");
        t.prejmi(new Tretja.Docent(), "doc_tlwlx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_UZXo6");
        t.prejmi(new Tretja.Docent(), "doc_sDO5W");
        t.prejmi(new Tretja.Asistent(), "as_cXNTB");
        t.prejmi(new Tretja.Profesor(), "prof_5vUjK");
        t.prejmi(new Tretja.Asistent(), "as_K3ECd");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_c9g9C");
        t.prejmi(new Tretja.Asistent(), "as_HmmGQ");
        t.prejmi(new Tretja.Profesor(), "prof_KJjsZ");
        t.prejmi(new Tretja.Profesor(), "prof_TKlRS");
        t.prejmi(new Tretja.Asistent(), "as_7fgUy");
        t.prejmi(new Tretja.Docent(), "doc_e0IpA");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_v4IdD");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_70MOk");
        t.prejmi(new Tretja.Asistent(), "as_K55wH");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_aTBZk");
        t.prejmi(new Tretja.Docent(), "doc_qyiYu");
        t.prejmi(new Tretja.Profesor(), "prof_YW1tV");
        t.prejmi(new Tretja.Docent(), "doc_mdjrY");
        t.prejmi(new Tretja.Docent(), "doc_iVYn8");
        t.prejmi(new Tretja.Docent(), "doc_da4KS");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_AHwkV");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_vsPfr");
        t.prejmi(new Tretja.Profesor(), "prof_E5GW0");
        t.prejmi(new Tretja.Asistent(), "as_ME5RB");
        t.prejmi(new Tretja.Docent(), "doc_uCvgb");
        t.prejmi(new Tretja.Docent(), "doc_hHn0U");
        t.prejmi(new Tretja.Asistent(), "as_LMKff");
        t.prejmi(new Tretja.Profesor(), "prof_7Pqyd");
        t.prejmi(new Tretja.Docent(), "doc_Pl4kv");
        t.prejmi(new Tretja.Profesor(), "prof_Wmo8k");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_22CQq");
        t.prejmi(new Tretja.Asistent(), "as_BsJSH");
        t.prejmi(new Tretja.Profesor(), "prof_zA39N");
        t.prejmi(new Tretja.Asistent(), "as_KFINV");
        t.prejmi(new Tretja.Docent(), "doc_vB0ho");
        t.prejmi(new Tretja.Asistent(), "as_e2Ebp");
        t.prejmi(new Tretja.Profesor(), "prof_mpT0F");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_UJKLl");
        t.prejmi(new Tretja.Asistent(), "as_mtsn1");
        t.prejmi(new Tretja.Profesor(), "prof_D64Ue");
        t.prejmi(new Tretja.Docent(), "doc_Uuhi4");
        t.prejmi(new Tretja.Asistent(), "as_XBsjZ");
        t.prejmi(new Tretja.Profesor(), "prof_qF9Bh");
        t.prejmi(new Tretja.Docent(), "doc_ZRpZN");
        t.prejmi(new Tretja.Profesor(), "prof_aemVu");
        t.prejmi(new Tretja.Docent(), "doc_6izst");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_pX7KS");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_0wZ3B");
        t.prejmi(new Tretja.Docent(), "doc_hcvUP");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_aFwWa");
        t.prejmi(new Tretja.Asistent(), "as_YfBZh");
        t.prejmi(new Tretja.Docent(), "doc_dZYSn");
        t.prejmi(new Tretja.Profesor(), "prof_xwYuL");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_L0jiY");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_5FGjN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_2zzf3");
        t.prejmi(new Tretja.Profesor(), "prof_yQCHB");
        t.prejmi(new Tretja.Asistent(), "as_hYqI4");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_9CXnx");
        t.prejmi(new Tretja.Asistent(), "as_lbY0l");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_oIvdm");
        t.prejmi(new Tretja.Docent(), "doc_UkVg1");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_qvG9j");
        t.prejmi(new Tretja.Docent(), "doc_r7FYE");
        t.prejmi(new Tretja.Asistent(), "as_iUZvp");
        t.prejmi(new Tretja.Asistent(), "as_MHJH3");
        t.prejmi(new Tretja.Profesor(), "prof_DmSvs");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_enva6");
        t.prejmi(new Tretja.Asistent(), "as_m01CW");
        t.prejmi(new Tretja.Asistent(), "as_rSz9Q");
        t.prejmi(new Tretja.Docent(), "doc_ejUvw");
        t.prejmi(new Tretja.Profesor(), "prof_6p9po");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_lfPRj");
        t.prejmi(new Tretja.Profesor(), "prof_nmteW");
        t.prejmi(new Tretja.Asistent(), "as_RKeNc");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_PcIG7");
        t.prejmi(new Tretja.Docent(), "doc_8EvP2");
        t.prejmi(new Tretja.Profesor(), "prof_8kzx7");
        t.prejmi(new Tretja.Profesor(), "prof_yr2Ly");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_H8hdB");
        t.prejmi(new Tretja.Docent(), "doc_8Hnxe");
        t.prejmi(new Tretja.Docent(), "doc_H0KKW");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_izBQu");
        t.prejmi(new Tretja.Asistent(), "as_NugbV");
        t.prejmi(new Tretja.Profesor(), "prof_kJWgZ");
        t.prejmi(new Tretja.Asistent(), "as_OJZRO");
        t.prejmi(new Tretja.Asistent(), "as_7tU6Y");
        t.prejmi(new Tretja.Profesor(), "prof_NbQwK");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_d3shY");
        t.prejmi(new Tretja.Profesor(), "prof_bxFWy");
        t.prejmi(new Tretja.Profesor(), "prof_HqgLc");
        t.prejmi(new Tretja.Asistent(), "as_wvFCR");
        t.prejmi(new Tretja.Asistent(), "as_MQXJ3");
        t.prejmi(new Tretja.Docent(), "doc_hGcjK");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_PMTFe");
        t.prejmi(new Tretja.Docent(), "doc_7Zmkq");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_9kE7c");
        t.prejmi(new Tretja.Docent(), "doc_qc7Nb");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_q7DBr");
        t.prejmi(new Tretja.Profesor(), "prof_N5sik");
        t.prejmi(new Tretja.Docent(), "doc_SdvP2");
        t.prejmi(new Tretja.Docent(), "doc_s76gQ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_wxShQ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_brvVC");
        t.prejmi(new Tretja.Docent(), "doc_U4GWh");
        t.prejmi(new Tretja.Profesor(), "prof_gx1kl");
        t.prejmi(new Tretja.Profesor(), "prof_NZ6Ez");
        t.prejmi(new Tretja.Profesor(), "prof_CKZIQ");
        t.prejmi(new Tretja.Asistent(), "as_sSHrX");
        t.prejmi(new Tretja.Profesor(), "prof_8zR5n");
        t.prejmi(new Tretja.Docent(), "doc_s3Jb6");
        t.prejmi(new Tretja.Docent(), "doc_hbLcs");
        t.prejmi(new Tretja.Asistent(), "as_QgHoa");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_7sc7d");
        t.prejmi(new Tretja.Docent(), "doc_U3DQR");
        t.prejmi(new Tretja.Docent(), "doc_NxNCL");
        t.prejmi(new Tretja.Profesor(), "prof_1ff8z");
        t.prejmi(new Tretja.Asistent(), "as_K8G65");
        t.prejmi(new Tretja.Asistent(), "as_0qr1V");
        t.prejmi(new Tretja.Profesor(), "prof_JMHYX");
        t.prejmi(new Tretja.Profesor(), "prof_o1I5K");
        t.prejmi(new Tretja.Asistent(), "as_jyolC");
        t.prejmi(new Tretja.Asistent(), "as_MVsna");
        t.prejmi(new Tretja.Profesor(), "prof_XqSI3");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_ACdU1");
        t.prejmi(new Tretja.Docent(), "doc_WIFRr");
        t.prejmi(new Tretja.Asistent(), "as_tXqpc");
        t.prejmi(new Tretja.Docent(), "doc_4uFIF");
        t.prejmi(new Tretja.Asistent(), "as_4jA2h");
        t.prejmi(new Tretja.Asistent(), "as_uvvxq");
        t.prejmi(new Tretja.Docent(), "doc_m1EBG");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_M1xBh");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_5t2lI");
        t.prejmi(new Tretja.Docent(), "doc_U9m1Q");
        t.prejmi(new Tretja.Profesor(), "prof_LNVEJ");
        t.prejmi(new Tretja.Docent(), "doc_ozkgS");
        t.prejmi(new Tretja.Profesor(), "prof_NRFsF");
        t.prejmi(new Tretja.Profesor(), "prof_UEl3F");
        t.prejmi(new Tretja.Asistent(), "as_ZIuRk");
        t.prejmi(new Tretja.Profesor(), "prof_6Gy2U");
        t.prejmi(new Tretja.Profesor(), "prof_BQ346");
    }
}
