
public class Test31 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_k3DNE");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_kZoqb");
        t.prejmi(new Tretja.Profesor(), "prof_mWk1w");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_50Igp");
        t.prejmi(new Tretja.Profesor(), "prof_lIs0x");
        t.prejmi(new Tretja.Docent(), "doc_djocE");
        t.prejmi(new Tretja.Docent(), "doc_ZGR7d");
        t.prejmi(new Tretja.Asistent(), "as_n3WVq");
        t.prejmi(new Tretja.Asistent(), "as_4piRj");
        t.prejmi(new Tretja.Profesor(), "prof_MuKxb");
        t.prejmi(new Tretja.Asistent(), "as_zRvxD");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_qYFWl");
        t.prejmi(new Tretja.Docent(), "doc_6Eowk");
        t.prejmi(new Tretja.Asistent(), "as_GyBUk");
        t.prejmi(new Tretja.Profesor(), "prof_9FrIS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_yd9lA");
        t.prejmi(new Tretja.Profesor(), "prof_euWEA");
        t.prejmi(new Tretja.Docent(), "doc_j2iPu");
        t.prejmi(new Tretja.Asistent(), "as_SlUsU");
        t.prejmi(new Tretja.Asistent(), "as_xgMxO");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_fR8uI");
        t.prejmi(new Tretja.Profesor(), "prof_e7jMv");
        t.prejmi(new Tretja.Docent(), "doc_IXCEL");
        t.prejmi(new Tretja.Profesor(), "prof_eiAze");
        t.prejmi(new Tretja.Docent(), "doc_T4O1N");
        t.prejmi(new Tretja.Asistent(), "as_kljPM");
        t.prejmi(new Tretja.Profesor(), "prof_NiwJN");
        t.prejmi(new Tretja.Profesor(), "prof_bEAsH");
        t.prejmi(new Tretja.Profesor(), "prof_NR8OH");
        t.prejmi(new Tretja.Asistent(), "as_bhNpv");
        t.prejmi(new Tretja.Docent(), "doc_cK0oD");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_8AOsU");
        t.prejmi(new Tretja.Asistent(), "as_CWvCw");
        t.prejmi(new Tretja.Docent(), "doc_ZwLAJ");
        t.prejmi(new Tretja.Docent(), "doc_iu9qR");
        t.prejmi(new Tretja.Profesor(), "prof_AGP1a");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_NnLnd");
        t.prejmi(new Tretja.Docent(), "doc_uX7k7");
        t.prejmi(new Tretja.Docent(), "doc_suTt1");
        t.prejmi(new Tretja.Docent(), "doc_TUnY8");
        t.prejmi(new Tretja.Profesor(), "prof_6YOlP");
        t.prejmi(new Tretja.Asistent(), "as_PSfWt");
        t.prejmi(new Tretja.Docent(), "doc_hQY40");
        t.prejmi(new Tretja.Asistent(), "as_uv4Bb");
        t.prejmi(new Tretja.Asistent(), "as_MVKMj");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_VtoBL");
        t.prejmi(new Tretja.Profesor(), "prof_vZjkM");
        t.prejmi(new Tretja.Profesor(), "prof_fals1");
        t.prejmi(new Tretja.Docent(), "doc_ikOoy");
        t.prejmi(new Tretja.Asistent(), "as_CmRZ4");
        t.prejmi(new Tretja.Profesor(), "prof_ooYyu");
        t.prejmi(new Tretja.Docent(), "doc_IO4Lv");
        t.prejmi(new Tretja.Asistent(), "as_IkJDZ");
        t.prejmi(new Tretja.Asistent(), "as_Qtb4X");
        t.prejmi(new Tretja.Docent(), "doc_S2QLl");
        t.prejmi(new Tretja.Asistent(), "as_8cVkR");
        t.prejmi(new Tretja.Asistent(), "as_JpYLK");
        t.prejmi(new Tretja.Profesor(), "prof_sDwUq");
        t.prejmi(new Tretja.Asistent(), "as_sJpje");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_qWItF");
        t.prejmi(new Tretja.Asistent(), "as_uFRdu");
        t.prejmi(new Tretja.Docent(), "doc_uhfgi");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_x6GtD");
        t.prejmi(new Tretja.Profesor(), "prof_pd5fT");
        t.prejmi(new Tretja.Asistent(), "as_pNXF2");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_SDgd6");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_OhvfW");
        t.prejmi(new Tretja.Asistent(), "as_kA5Pf");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_2qDOd");
        t.prejmi(new Tretja.Docent(), "doc_d5dxI");
        t.prejmi(new Tretja.Asistent(), "as_dOpvz");
        t.prejmi(new Tretja.Asistent(), "as_8DXKD");
        t.prejmi(new Tretja.Profesor(), "prof_A3leC");
        t.prejmi(new Tretja.Docent(), "doc_P3rjl");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_Shhuh");
        t.prejmi(new Tretja.Asistent(), "as_6uFuH");
        t.prejmi(new Tretja.Asistent(), "as_C2ail");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_T1Lf7");
        t.prejmi(new Tretja.Asistent(), "as_c8XKF");
        t.prejmi(new Tretja.Docent(), "doc_8Y6rT");
        t.prejmi(new Tretja.Profesor(), "prof_3FZT2");
        t.prejmi(new Tretja.Profesor(), "prof_dINHV");
        t.prejmi(new Tretja.Asistent(), "as_U7Y20");
        t.prejmi(new Tretja.Docent(), "doc_GPwEZ");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_32sXh");
        t.prejmi(new Tretja.Profesor(), "prof_tpobx");
        t.prejmi(new Tretja.Docent(), "doc_fElsK");
        t.prejmi(new Tretja.Docent(), "doc_kGMXJ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_83U9z");
        t.prejmi(new Tretja.Profesor(), "prof_fGFgt");
        t.prejmi(new Tretja.Asistent(), "as_ZVWhu");
        t.prejmi(new Tretja.Docent(), "doc_whnru");
        t.prejmi(new Tretja.Asistent(), "as_ZOERd");
        t.prejmi(new Tretja.Profesor(), "prof_TMM6w");
        t.prejmi(new Tretja.Docent(), "doc_C3xCm");
        t.prejmi(new Tretja.Profesor(), "prof_Sjomg");
        t.prejmi(new Tretja.Asistent(), "as_C9L5D");
        t.prejmi(new Tretja.Asistent(), "as_amc0O");
        t.prejmi(new Tretja.Profesor(), "prof_RvraC");
        t.prejmi(new Tretja.Profesor(), "prof_vXrVD");
        t.prejmi(new Tretja.Docent(), "doc_unIU8");
        t.prejmi(new Tretja.Docent(), "doc_l2up6");
        t.prejmi(new Tretja.Asistent(), "as_qmgdD");
        t.prejmi(new Tretja.Docent(), "doc_4iQ2e");
        t.prejmi(new Tretja.Docent(), "doc_RwUJ6");
        t.prejmi(new Tretja.Docent(), "doc_u5SgS");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_ZCoGe");
        t.prejmi(new Tretja.Asistent(), "as_toXnd");
        t.prejmi(new Tretja.Asistent(), "as_qsgHp");
        t.prejmi(new Tretja.Asistent(), "as_FvluZ");
        t.prejmi(new Tretja.Profesor(), "prof_MK0ml");
        t.prejmi(new Tretja.Docent(), "doc_G9cKF");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_p9ieX");
        t.prejmi(new Tretja.Profesor(), "prof_3RE0Z");
        t.prejmi(new Tretja.Profesor(), "prof_yH5HM");
        t.prejmi(new Tretja.Profesor(), "prof_gS6nj");
        t.prejmi(new Tretja.Profesor(), "prof_V2rzs");
        t.prejmi(new Tretja.Asistent(), "as_TBrXr");
        t.prejmi(new Tretja.Docent(), "doc_CEytS");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_f3maX");
        t.prejmi(new Tretja.Profesor(), "prof_fXlir");
        t.prejmi(new Tretja.Asistent(), "as_QhgZw");
        t.prejmi(new Tretja.Docent(), "doc_hl3aH");
        t.prejmi(new Tretja.Profesor(), "prof_MmMeF");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_cbqUb");
        t.prejmi(new Tretja.Docent(), "doc_SWpvq");
        t.prejmi(new Tretja.Docent(), "doc_EUk4g");
        t.prejmi(new Tretja.Docent(), "doc_jOmo9");
        t.prejmi(new Tretja.Docent(), "doc_GfXTv");
        t.prejmi(new Tretja.Docent(), "doc_AEDsV");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_W24Sv");
        t.prejmi(new Tretja.Asistent(), "as_zTghN");
        t.prejmi(new Tretja.Profesor(), "prof_C8sL3");
        t.prejmi(new Tretja.Asistent(), "as_IFw8N");
        t.prejmi(new Tretja.Profesor(), "prof_LuGYq");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_fsGeW");
        t.prejmi(new Tretja.Docent(), "doc_UZvJP");
        t.prejmi(new Tretja.Asistent(), "as_Mt5n2");
        t.prejmi(new Tretja.Asistent(), "as_xichr");
        t.prejmi(new Tretja.Profesor(), "prof_CPUZW");
        t.prejmi(new Tretja.Asistent(), "as_Agiov");
        t.prejmi(new Tretja.Asistent(), "as_oDZiW");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_qLBhb");
        t.prejmi(new Tretja.Docent(), "doc_QaCvz");
        t.prejmi(new Tretja.Docent(), "doc_84kZC");
        t.prejmi(new Tretja.Asistent(), "as_qjBaX");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_hnADN");
        t.prejmi(new Tretja.Docent(), "doc_rzZ9d");
        t.prejmi(new Tretja.Asistent(), "as_hPbsO");
        t.prejmi(new Tretja.Asistent(), "as_xcd5j");
        t.prejmi(new Tretja.Docent(), "doc_tJyyX");
        t.prejmi(new Tretja.Asistent(), "as_KKlyP");
        t.prejmi(new Tretja.Profesor(), "prof_QHnCc");
        t.prejmi(new Tretja.Asistent(), "as_hSdZW");
        t.prejmi(new Tretja.Profesor(), "prof_akRmI");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_ODl52");
        t.prejmi(new Tretja.Profesor(), "prof_46moP");
        t.prejmi(new Tretja.Docent(), "doc_MhXfG");
        t.prejmi(new Tretja.Profesor(), "prof_y6Z71");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_UYC9Q");
        t.prejmi(new Tretja.Asistent(), "as_o9Mmm");
        t.prejmi(new Tretja.Asistent(), "as_NaBZh");
        t.prejmi(new Tretja.Docent(), "doc_WH9Sd");
        t.prejmi(new Tretja.Docent(), "doc_sjV8V");
        t.prejmi(new Tretja.Profesor(), "prof_LqNba");
        t.prejmi(new Tretja.Docent(), "doc_5tWEF");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_HrqbO");
        t.prejmi(new Tretja.Asistent(), "as_NhMGH");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_CV9T4");
        t.prejmi(new Tretja.Docent(), "doc_dlJYj");
        t.prejmi(new Tretja.Profesor(), "prof_c6sj0");
        t.prejmi(new Tretja.Asistent(), "as_td58I");
        t.prejmi(new Tretja.Asistent(), "as_PL4rI");
        t.prejmi(new Tretja.Asistent(), "as_Qhp5i");
        t.prejmi(new Tretja.Asistent(), "as_rJxkK");
        t.prejmi(new Tretja.Docent(), "doc_4YZ9v");
        t.prejmi(new Tretja.Profesor(), "prof_abMeN");
        t.prejmi(new Tretja.Docent(), "doc_zx8P1");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_65lIp");
        t.prejmi(new Tretja.Asistent(), "as_q0sLA");
        t.prejmi(new Tretja.Profesor(), "prof_tFp3i");
        t.prejmi(new Tretja.Docent(), "doc_wy4J1");
        t.prejmi(new Tretja.Docent(), "doc_bfiJ2");
        t.prejmi(new Tretja.Asistent(), "as_GSoDN");
        t.prejmi(new Tretja.Docent(), "doc_jBgjN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_AOgDQ");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_USRrB");
        t.prejmi(new Tretja.Docent(), "doc_Yh57Z");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_QnVHr");
        t.prejmi(new Tretja.Docent(), "doc_10MZ4");
        t.prejmi(new Tretja.Asistent(), "as_53nzP");
        t.prejmi(new Tretja.Asistent(), "as_cwCI8");
        t.prejmi(new Tretja.Profesor(), "prof_zcjex");
        t.prejmi(new Tretja.Docent(), "doc_krTFr");
        t.prejmi(new Tretja.Profesor(), "prof_MjaQm");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_MKblX");
        t.prejmi(new Tretja.Profesor(), "prof_W6Vo0");
        t.prejmi(new Tretja.Docent(), "doc_kQZr4");
        t.prejmi(new Tretja.Docent(), "doc_Hlxj6");
        t.prejmi(new Tretja.Profesor(), "prof_ElICr");
        t.prejmi(new Tretja.Profesor(), "prof_vc7z9");
        t.prejmi(new Tretja.Profesor(), "prof_WA05O");
        t.prejmi(new Tretja.Docent(), "doc_eqkT0");
        t.prejmi(new Tretja.Asistent(), "as_eIsmt");
        t.prejmi(new Tretja.Profesor(), "prof_miE4s");
        t.prejmi(new Tretja.Docent(), "doc_fDQTN");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_IfeBa");
        t.prejmi(new Tretja.Profesor(), "prof_1L7xm");
        t.prejmi(new Tretja.Asistent(), "as_QXc9o");
        t.prejmi(new Tretja.Profesor(), "prof_zO7cm");
        t.prejmi(new Tretja.Profesor(), "prof_r3x0F");
        t.prejmi(new Tretja.Profesor(), "prof_AsZ6d");
        t.prejmi(new Tretja.Asistent(), "as_y8PbY");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_9exek");
        t.prejmi(new Tretja.Profesor(), "prof_wYIXN");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_LQONj");
        t.prejmi(new Tretja.Docent(), "doc_pe176");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_wSotQ");
        t.prejmi(new Tretja.Asistent(), "as_fTzr5");
        t.prejmi(new Tretja.Profesor(), "prof_ty7zx");
        t.prejmi(new Tretja.Docent(), "doc_NYVqZ");
        t.prejmi(new Tretja.Docent(), "doc_3l7mG");
        t.prejmi(new Tretja.Docent(), "doc_DNMZK");
        t.prejmi(new Tretja.Asistent(), "as_xiGFe");
        t.prejmi(new Tretja.Docent(), "doc_xhFAq");
        t.prejmi(new Tretja.Docent(), "doc_PD4KW");
        t.prejmi(new Tretja.Docent(), "doc_QZOhj");
        t.prejmi(new Tretja.Docent(), "doc_vaNWx");
        t.prejmi(new Tretja.Docent(), "doc_w3WyJ");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_utWa9");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_LScE9");
        t.prejmi(new Tretja.Profesor(), "prof_lPYdd");
        t.prejmi(new Tretja.Docent(), "doc_ZtIi6");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_hbPHs");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_zZGHq");
        t.prejmi(new Tretja.Asistent(), "as_hVsO4");
        t.prejmi(new Tretja.Asistent(), "as_gI0hG");
        t.prejmi(new Tretja.Profesor(), "prof_yfEvm");
        t.prejmi(new Tretja.Profesor(), "prof_B6Snl");
        t.prejmi(new Tretja.Profesor(), "prof_7c3aX");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_TAPwj");
        t.prejmi(new Tretja.Asistent(), "as_C85DD");
        t.prejmi(new Tretja.Asistent(), "as_KrhL2");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_znlyR");
        t.prejmi(new Tretja.Docent(), "doc_jR9iY");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_OeRI7");
        t.prejmi(new Tretja.Asistent(), "as_iAAlG");
        t.prejmi(new Tretja.Docent(), "doc_So4Ou");
        t.prejmi(new Tretja.Docent(), "doc_VOXRq");
        t.prejmi(new Tretja.Asistent(), "as_rP1fj");
        t.prejmi(new Tretja.Docent(), "doc_WyLS6");
        t.prejmi(new Tretja.Profesor(), "prof_x7d9A");
        t.prejmi(new Tretja.Docent(), "doc_NAG6x");
        t.prejmi(new Tretja.Docent(), "doc_k6CsN");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_RyODR");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_gPWTV");
        t.prejmi(new Tretja.Docent(), "doc_1XfcX");
        t.prejmi(new Tretja.Docent(), "doc_7GLnk");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_IMElN");
        t.prejmi(new Tretja.Asistent(), "as_OEWO9");
        t.prejmi(new Tretja.Docent(), "doc_eKyLl");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_vZyNe");
        t.prejmi(new Tretja.Profesor(), "prof_Nlfmi");
        t.prejmi(new Tretja.Profesor(), "prof_7pj3q");
        t.prejmi(new Tretja.Docent(), "doc_VMIvT");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_s0n0r");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_JY0EC");
        t.prejmi(new Tretja.Docent(), "doc_73mez");
        t.prejmi(new Tretja.Docent(), "doc_cNAvq");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_qUA5T");
        t.prejmi(new Tretja.Profesor(), "prof_rmYg5");
        t.prejmi(new Tretja.Asistent(), "as_OEbEY");
        t.prejmi(new Tretja.Profesor(), "prof_PpDhT");
        t.prejmi(new Tretja.Asistent(), "as_j2523");
        t.prejmi(new Tretja.Asistent(), "as_hzL7Y");
        t.prejmi(new Tretja.Docent(), "doc_Bzc4v");
        t.prejmi(new Tretja.Profesor(), "prof_MmhJz");
        t.prejmi(new Tretja.Asistent(), "as_tySBw");
        t.prejmi(new Tretja.Docent(), "doc_FX0FQ");
        t.prejmi(new Tretja.Asistent(), "as_w2s0o");
        t.prejmi(new Tretja.Profesor(), "prof_bF7P3");
        t.prejmi(new Tretja.Profesor(), "prof_wOMN3");
        t.prejmi(new Tretja.Asistent(), "as_6BWKT");
        t.prejmi(new Tretja.Docent(), "doc_4CSZO");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_ZGFqc");
        t.prejmi(new Tretja.Docent(), "doc_HXH9I");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_JTynr");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
    }
}
