
public class Test37 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Profesor(), "prof_muViu");
        t.prejmi(new Tretja.Docent(), "doc_ENSAB");
        t.prejmi(new Tretja.Asistent(), "as_zJEhB");
        t.prejmi(new Tretja.Asistent(), "as_IXi72");
        t.prejmi(new Tretja.Profesor(), "prof_ULSb2");
        t.prejmi(new Tretja.Docent(), "doc_4rFxW");
        t.prejmi(new Tretja.Profesor(), "prof_q5D9t");
        t.prejmi(new Tretja.Profesor(), "prof_00wP1");
        t.prejmi(new Tretja.Asistent(), "as_RgM1K");
        t.prejmi(new Tretja.Docent(), "doc_iVCR8");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_JaifV");
        t.prejmi(new Tretja.Profesor(), "prof_3zJWg");
        t.prejmi(new Tretja.Asistent(), "as_Sn52y");
        t.prejmi(new Tretja.Docent(), "doc_VBXR6");
        t.prejmi(new Tretja.Profesor(), "prof_mQl1k");
        t.prejmi(new Tretja.Profesor(), "prof_K2h85");
        t.prejmi(new Tretja.Profesor(), "prof_rP7tR");
        t.prejmi(new Tretja.Profesor(), "prof_uwSgS");
        t.prejmi(new Tretja.Asistent(), "as_bKOxV");
        t.prejmi(new Tretja.Profesor(), "prof_YVGwN");
        t.prejmi(new Tretja.Asistent(), "as_zl7aL");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_TKxfD");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_PNZVh");
        t.prejmi(new Tretja.Profesor(), "prof_Tpquu");
        t.prejmi(new Tretja.Docent(), "doc_H1kjg");
        t.prejmi(new Tretja.Docent(), "doc_SGZXE");
        t.prejmi(new Tretja.Docent(), "doc_WVBta");
        t.prejmi(new Tretja.Profesor(), "prof_qjrBc");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_SZmLo");
        t.prejmi(new Tretja.Asistent(), "as_VmF5N");
        t.prejmi(new Tretja.Docent(), "doc_z1020");
        t.prejmi(new Tretja.Asistent(), "as_d9oF2");
        t.prejmi(new Tretja.Asistent(), "as_ZSmlh");
        t.prejmi(new Tretja.Profesor(), "prof_oBbPs");
        t.prejmi(new Tretja.Docent(), "doc_HBwbb");
        t.prejmi(new Tretja.Asistent(), "as_FNMCw");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_pU1Y3");
        t.prejmi(new Tretja.Docent(), "doc_IOveG");
        t.prejmi(new Tretja.Profesor(), "prof_31luk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_69c9s");
        t.prejmi(new Tretja.Asistent(), "as_d01DU");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_0EVcD");
        t.prejmi(new Tretja.Asistent(), "as_K5Zqq");
        t.prejmi(new Tretja.Docent(), "doc_a9ZU9");
        t.prejmi(new Tretja.Asistent(), "as_08FcQ");
        t.prejmi(new Tretja.Asistent(), "as_0r0c8");
        t.prejmi(new Tretja.Asistent(), "as_J6V8I");
        t.prejmi(new Tretja.Asistent(), "as_we5pI");
        t.prejmi(new Tretja.Docent(), "doc_mVlrI");
        t.prejmi(new Tretja.Profesor(), "prof_kpAC3");
        t.prejmi(new Tretja.Profesor(), "prof_tmldG");
        t.prejmi(new Tretja.Profesor(), "prof_Wc6iE");
        t.prejmi(new Tretja.Profesor(), "prof_LjLOe");
        t.prejmi(new Tretja.Asistent(), "as_T8VQD");
        t.prejmi(new Tretja.Asistent(), "as_R7qE8");
        t.prejmi(new Tretja.Profesor(), "prof_oDV1H");
        t.prejmi(new Tretja.Asistent(), "as_enP62");
        t.prejmi(new Tretja.Profesor(), "prof_arIqe");
        t.prejmi(new Tretja.Asistent(), "as_iplEj");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_rCFtD");
        t.prejmi(new Tretja.Asistent(), "as_M9VYL");
        t.prejmi(new Tretja.Docent(), "doc_ExbLi");
        t.prejmi(new Tretja.Docent(), "doc_mxwty");
        t.prejmi(new Tretja.Docent(), "doc_J9SCD");
        t.prejmi(new Tretja.Profesor(), "prof_zJDwb");
        t.prejmi(new Tretja.Asistent(), "as_i6nxb");
        t.prejmi(new Tretja.Asistent(), "as_Uaibq");
        t.prejmi(new Tretja.Asistent(), "as_T8FRF");
        t.prejmi(new Tretja.Docent(), "doc_09dk2");
        t.prejmi(new Tretja.Profesor(), "prof_rOhkm");
        t.prejmi(new Tretja.Asistent(), "as_ivrLG");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_wj9vN");
        t.prejmi(new Tretja.Asistent(), "as_yhS67");
        t.prejmi(new Tretja.Profesor(), "prof_2Wy07");
        t.prejmi(new Tretja.Docent(), "doc_En6op");
        t.prejmi(new Tretja.Asistent(), "as_RBqcb");
        t.prejmi(new Tretja.Asistent(), "as_XFFdr");
        t.prejmi(new Tretja.Asistent(), "as_6EnX4");
        t.prejmi(new Tretja.Docent(), "doc_pOFYJ");
        t.prejmi(new Tretja.Profesor(), "prof_mxu9Q");
        t.prejmi(new Tretja.Profesor(), "prof_atRFp");
        t.prejmi(new Tretja.Docent(), "doc_R4wrt");
        t.prejmi(new Tretja.Asistent(), "as_n16Dv");
        t.prejmi(new Tretja.Docent(), "doc_Ksky9");
        t.prejmi(new Tretja.Asistent(), "as_oyDBE");
        t.prejmi(new Tretja.Profesor(), "prof_sIRrp");
        t.prejmi(new Tretja.Asistent(), "as_n6k90");
        t.prejmi(new Tretja.Asistent(), "as_rZWI8");
        t.prejmi(new Tretja.Docent(), "doc_VvZv3");
        t.prejmi(new Tretja.Docent(), "doc_4p2eS");
        t.prejmi(new Tretja.Docent(), "doc_UnQGj");
        t.prejmi(new Tretja.Asistent(), "as_LNt4I");
        t.prejmi(new Tretja.Asistent(), "as_VHxjn");
        t.prejmi(new Tretja.Profesor(), "prof_MqjH3");
        t.prejmi(new Tretja.Docent(), "doc_Zow2R");
        t.prejmi(new Tretja.Docent(), "doc_efv5r");
        t.prejmi(new Tretja.Docent(), "doc_JQf3J");
        t.prejmi(new Tretja.Docent(), "doc_XPyla");
        t.prejmi(new Tretja.Profesor(), "prof_YASBp");
        t.prejmi(new Tretja.Profesor(), "prof_x53pR");
        t.prejmi(new Tretja.Docent(), "doc_TIxsB");
        t.prejmi(new Tretja.Profesor(), "prof_AWP2N");
        t.prejmi(new Tretja.Asistent(), "as_FuKD4");
        t.prejmi(new Tretja.Profesor(), "prof_vnxZI");
        t.prejmi(new Tretja.Docent(), "doc_LlfzC");
        t.prejmi(new Tretja.Docent(), "doc_oLCal");
        t.prejmi(new Tretja.Docent(), "doc_8CQth");
        t.prejmi(new Tretja.Asistent(), "as_OWo72");
        t.prejmi(new Tretja.Profesor(), "prof_j8eVN");
        t.prejmi(new Tretja.Profesor(), "prof_F7h9U");
        t.prejmi(new Tretja.Docent(), "doc_aAuxH");
        t.prejmi(new Tretja.Docent(), "doc_4vd5f");
        t.prejmi(new Tretja.Asistent(), "as_VTP1N");
        t.prejmi(new Tretja.Asistent(), "as_Ge4uE");
        t.prejmi(new Tretja.Docent(), "doc_1exxv");
        t.prejmi(new Tretja.Asistent(), "as_0HHoo");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_d74t1");
        t.prejmi(new Tretja.Docent(), "doc_CKiaX");
        t.prejmi(new Tretja.Profesor(), "prof_rioYX");
        t.prejmi(new Tretja.Asistent(), "as_nBwN0");
        t.prejmi(new Tretja.Asistent(), "as_bpvJt");
        t.prejmi(new Tretja.Profesor(), "prof_KxrXN");
        t.prejmi(new Tretja.Asistent(), "as_HaAwy");
        t.prejmi(new Tretja.Profesor(), "prof_BmruS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_PWSDI");
        t.prejmi(new Tretja.Asistent(), "as_H6KyX");
        t.prejmi(new Tretja.Docent(), "doc_FLfGC");
        t.prejmi(new Tretja.Profesor(), "prof_gNG0e");
        t.prejmi(new Tretja.Asistent(), "as_ULWwY");
        t.prejmi(new Tretja.Asistent(), "as_JiNak");
        t.prejmi(new Tretja.Profesor(), "prof_CCnGR");
        t.prejmi(new Tretja.Docent(), "doc_CBMCL");
        t.prejmi(new Tretja.Asistent(), "as_vZcK8");
        t.prejmi(new Tretja.Profesor(), "prof_O3dUt");
        t.prejmi(new Tretja.Profesor(), "prof_MNPk2");
        t.prejmi(new Tretja.Asistent(), "as_wMKMg");
        t.prejmi(new Tretja.Docent(), "doc_UjOhk");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_Hoolx");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_7RIIC");
        t.prejmi(new Tretja.Asistent(), "as_VZgwj");
        t.prejmi(new Tretja.Docent(), "doc_zPIiI");
        t.prejmi(new Tretja.Asistent(), "as_8QgPS");
        t.prejmi(new Tretja.Docent(), "doc_Cmszq");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_kuc3g");
        t.prejmi(new Tretja.Docent(), "doc_UdYH4");
        t.prejmi(new Tretja.Asistent(), "as_5rD7q");
        t.prejmi(new Tretja.Profesor(), "prof_5TBSS");
        t.prejmi(new Tretja.Docent(), "doc_s9f5K");
        t.prejmi(new Tretja.Profesor(), "prof_WDVH1");
        t.prejmi(new Tretja.Profesor(), "prof_PKCQS");
        t.prejmi(new Tretja.Profesor(), "prof_JhZFx");
        t.prejmi(new Tretja.Docent(), "doc_iwTrl");
        t.prejmi(new Tretja.Asistent(), "as_0jG6v");
        t.prejmi(new Tretja.Profesor(), "prof_db86B");
        t.prejmi(new Tretja.Docent(), "doc_BUHdy");
        t.prejmi(new Tretja.Asistent(), "as_jGxhh");
        t.prejmi(new Tretja.Profesor(), "prof_brCwh");
        t.prejmi(new Tretja.Asistent(), "as_5yNSV");
        t.prejmi(new Tretja.Profesor(), "prof_OlVAx");
        t.prejmi(new Tretja.Docent(), "doc_i2dxQ");
        t.prejmi(new Tretja.Profesor(), "prof_xQTrk");
        t.prejmi(new Tretja.Asistent(), "as_fqg33");
        t.prejmi(new Tretja.Asistent(), "as_7RC6P");
        t.prejmi(new Tretja.Asistent(), "as_zD3eH");
        t.prejmi(new Tretja.Profesor(), "prof_sTXt9");
        t.prejmi(new Tretja.Docent(), "doc_PShaa");
        t.prejmi(new Tretja.Docent(), "doc_jMFUX");
        t.prejmi(new Tretja.Docent(), "doc_yHRiD");
        t.prejmi(new Tretja.Docent(), "doc_jMZPU");
        t.prejmi(new Tretja.Profesor(), "prof_4rg01");
        t.prejmi(new Tretja.Profesor(), "prof_J8vnE");
        t.prejmi(new Tretja.Docent(), "doc_FoYGw");
        t.prejmi(new Tretja.Docent(), "doc_B5OCA");
        t.prejmi(new Tretja.Docent(), "doc_bNK9r");
        t.prejmi(new Tretja.Docent(), "doc_lSDmE");
        t.prejmi(new Tretja.Asistent(), "as_Ny3kN");
        t.prejmi(new Tretja.Asistent(), "as_1SzrS");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_4FE8j");
        t.prejmi(new Tretja.Docent(), "doc_GCP5X");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_dLgxX");
        t.prejmi(new Tretja.Profesor(), "prof_oQTqN");
        t.prejmi(new Tretja.Docent(), "doc_x8Rfh");
        t.prejmi(new Tretja.Profesor(), "prof_UPH5r");
        t.prejmi(new Tretja.Docent(), "doc_u5DJ8");
        t.prejmi(new Tretja.Docent(), "doc_w6vXS");
        t.prejmi(new Tretja.Asistent(), "as_NNf4X");
        t.prejmi(new Tretja.Profesor(), "prof_8dasZ");
        t.prejmi(new Tretja.Profesor(), "prof_wFjun");
        t.prejmi(new Tretja.Asistent(), "as_4ABAM");
        t.prejmi(new Tretja.Docent(), "doc_GE9Gy");
        t.prejmi(new Tretja.Profesor(), "prof_uVpdr");
        t.prejmi(new Tretja.Docent(), "doc_bplyu");
        t.prejmi(new Tretja.Docent(), "doc_TKp2K");
        t.prejmi(new Tretja.Asistent(), "as_CJlMT");
        t.prejmi(new Tretja.Profesor(), "prof_05fhB");
        t.prejmi(new Tretja.Asistent(), "as_Id1BY");
        t.prejmi(new Tretja.Profesor(), "prof_jrrfy");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_yLDIu");
        t.prejmi(new Tretja.Docent(), "doc_UypPK");
        t.prejmi(new Tretja.Profesor(), "prof_MR7bS");
        t.prejmi(new Tretja.Asistent(), "as_dQbt9");
        t.prejmi(new Tretja.Profesor(), "prof_X5bNn");
        t.prejmi(new Tretja.Profesor(), "prof_jkd6q");
        t.prejmi(new Tretja.Docent(), "doc_1H1mH");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Docent(), "doc_kmyXA");
        t.prejmi(new Tretja.Docent(), "doc_uTrsf");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_KAsU3");
        t.prejmi(new Tretja.Profesor(), "prof_cMMSQ");
        t.prejmi(new Tretja.Profesor(), "prof_LCCYV");
        t.prejmi(new Tretja.Docent(), "doc_wl8ml");
        t.prejmi(new Tretja.Profesor(), "prof_qwdLc");
        t.prejmi(new Tretja.Asistent(), "as_TjyCQ");
        t.prejmi(new Tretja.Profesor(), "prof_OsqvL");
        t.prejmi(new Tretja.Profesor(), "prof_PgM0E");
        t.prejmi(new Tretja.Profesor(), "prof_RTSFT");
        t.prejmi(new Tretja.Asistent(), "as_0Cnr9");
        t.prejmi(new Tretja.Docent(), "doc_yCbnV");
        System.out.println(t.natisni());
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Profesor(), "prof_NFob5");
        t.prejmi(new Tretja.Profesor(), "prof_o3UgW");
        t.prejmi(new Tretja.Profesor(), "prof_xniu7");
        t.prejmi(new Tretja.Docent(), "doc_Sod4o");
        t.prejmi(new Tretja.Asistent(), "as_a7m2X");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_PtvgJ");
        t.prejmi(new Tretja.Profesor(), "prof_AZL2s");
        t.prejmi(new Tretja.Asistent(), "as_yek4N");
        t.prejmi(new Tretja.Docent(), "doc_zchKn");
        t.prejmi(new Tretja.Profesor(), "prof_mRmUt");
        System.out.println(t.natisni());
        t.prejmi(new Tretja.Asistent(), "as_4vG68");
        t.prejmi(new Tretja.Profesor(), "prof_anfqW");
        t.prejmi(new Tretja.Profesor(), "prof_WlOGW");
        t.prejmi(new Tretja.Docent(), "doc_XQ1Ov");
        t.prejmi(new Tretja.Docent(), "doc_jOKyl");
        t.prejmi(new Tretja.Profesor(), "prof_KuGfm");
        t.prejmi(new Tretja.Asistent(), "as_shipV");
        t.prejmi(new Tretja.Asistent(), "as_LCblD");
        t.prejmi(new Tretja.Docent(), "doc_iHtKv");
        t.prejmi(new Tretja.Docent(), "doc_iB810");
        t.prejmi(new Tretja.Asistent(), "as_W7eKr");
        t.prejmi(new Tretja.Asistent(), "as_c0CFW");
        t.prejmi(new Tretja.Asistent(), "as_psDSr");
        t.prejmi(new Tretja.Asistent(), "as_qj3id");
        t.prejmi(new Tretja.Docent(), "doc_9YUsX");
        t.prejmi(new Tretja.Docent(), "doc_ZArlX");
        t.prejmi(new Tretja.Asistent(), "as_CcQeD");
    }
}
