
public class Test04 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Asistent(), "as_Hwdou");
        t.prejmi(new Tretja.Docent(), "doc_3FAi1");
        t.prejmi(new Tretja.Asistent(), "as_Iwx2s");
        t.prejmi(new Tretja.Asistent(), "as_0X4NB");
        t.prejmi(new Tretja.Profesor(), "prof_6ClYw");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_TUXeF");
        t.prejmi(new Tretja.Profesor(), "prof_Ct8Fv");
        t.prejmi(new Tretja.Asistent(), "as_YAU4D");
        t.prejmi(new Tretja.Asistent(), "as_mV4e5");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_UNvXj");
        t.prejmi(new Tretja.Profesor(), "prof_6EeTG");
        t.prejmi(new Tretja.Asistent(), "as_2Cd9m");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_R6env");
        t.prejmi(new Tretja.Profesor(), "prof_vTw0q");
        t.prejmi(new Tretja.Asistent(), "as_TDlsg");
        t.prejmi(new Tretja.Docent(), "doc_xZHPQ");
        t.prejmi(new Tretja.Docent(), "doc_WE3Dh");
        t.prejmi(new Tretja.Asistent(), "as_JiLLL");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_JGrwq");
        t.prejmi(new Tretja.Docent(), "doc_xwF4z");
        t.prejmi(new Tretja.Profesor(), "prof_Z4Nkr");
        t.prejmi(new Tretja.Docent(), "doc_SUMDE");
        t.prejmi(new Tretja.Profesor(), "prof_Q5VnX");
        t.prejmi(new Tretja.Docent(), "doc_q9Leg");
        t.prejmi(new Tretja.Docent(), "doc_aokue");
        t.prejmi(new Tretja.Profesor(), "prof_qvqfE");
        t.prejmi(new Tretja.Docent(), "doc_1jyxs");
        t.prejmi(new Tretja.Asistent(), "as_l1V9g");
        t.prejmi(new Tretja.Asistent(), "as_c8g1U");
        t.prejmi(new Tretja.Docent(), "doc_aVp8G");
        t.prejmi(new Tretja.Asistent(), "as_MC7u4");
        t.prejmi(new Tretja.Docent(), "doc_kxRNg");
        t.prejmi(new Tretja.Profesor(), "prof_O5rJZ");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_1Fqnq");
        t.prejmi(new Tretja.Docent(), "doc_KbMaD");
        t.prejmi(new Tretja.Asistent(), "as_vyDb8");
        t.prejmi(new Tretja.Profesor(), "prof_heQxf");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_qmmWe");
        t.prejmi(new Tretja.Asistent(), "as_pqZYv");
        t.prejmi(new Tretja.Docent(), "doc_GLhF6");
        t.prejmi(new Tretja.Profesor(), "prof_IzPol");
        t.prejmi(new Tretja.Docent(), "doc_d40F7");
        t.prejmi(new Tretja.Profesor(), "prof_69385");
        t.prejmi(new Tretja.Profesor(), "prof_qtvvf");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_hel6C");
        t.prejmi(new Tretja.Docent(), "doc_jFlOA");
        t.prejmi(new Tretja.Profesor(), "prof_hseM4");
        t.prejmi(new Tretja.Profesor(), "prof_CWa9g");
        t.prejmi(new Tretja.Profesor(), "prof_09fmS");
        t.prejmi(new Tretja.Profesor(), "prof_fV5xb");
        t.prejmi(new Tretja.Asistent(), "as_TcbHa");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_S6Nlp");
        t.prejmi(new Tretja.Asistent(), "as_6iLi5");
        t.prejmi(new Tretja.Docent(), "doc_hCIvA");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_RGgMc");
        t.prejmi(new Tretja.Asistent(), "as_X1Bhe");
        t.prejmi(new Tretja.Docent(), "doc_Y9qME");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_aL9ab");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_Hjocb");
        t.prejmi(new Tretja.Profesor(), "prof_0JSXf");
        t.prejmi(new Tretja.Docent(), "doc_Qwpjr");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_owuKM");
        t.prejmi(new Tretja.Docent(), "doc_tYZwv");
        t.prejmi(new Tretja.Docent(), "doc_JcVg2");
        t.prejmi(new Tretja.Docent(), "doc_oZxHy");
        t.prejmi(new Tretja.Profesor(), "prof_m3Mob");
        t.prejmi(new Tretja.Docent(), "doc_EGv1U");
        t.prejmi(new Tretja.Asistent(), "as_cjv05");
        t.prejmi(new Tretja.Docent(), "doc_fJuAJ");
        t.prejmi(new Tretja.Asistent(), "as_CetqL");
        t.prejmi(new Tretja.Asistent(), "as_wD8uj");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_WK4ng");
        t.prejmi(new Tretja.Profesor(), "prof_wp8on");
        t.prejmi(new Tretja.Docent(), "doc_UmwA1");
        t.prejmi(new Tretja.Asistent(), "as_QffVH");
        t.prejmi(new Tretja.Docent(), "doc_GVpGc");
        t.prejmi(new Tretja.Docent(), "doc_jp5fU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_wZswD");
        t.prejmi(new Tretja.Docent(), "doc_1BOw7");
        t.prejmi(new Tretja.Docent(), "doc_xNbrY");
        t.prejmi(new Tretja.Docent(), "doc_brYNU");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_4Oxo4");
        t.prejmi(new Tretja.Profesor(), "prof_ElrN5");
        t.prejmi(new Tretja.Docent(), "doc_sIgHi");
        t.prejmi(new Tretja.Docent(), "doc_8uSgs");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_lLHHQ");
        t.prejmi(new Tretja.Docent(), "doc_8gXal");
        t.prejmi(new Tretja.Docent(), "doc_FN7Ib");
        t.prejmi(new Tretja.Asistent(), "as_2rL70");
        t.prejmi(new Tretja.Docent(), "doc_lXuLe");
        t.prejmi(new Tretja.Docent(), "doc_2wz6P");
        t.prejmi(new Tretja.Profesor(), "prof_2RJ8D");
        t.prejmi(new Tretja.Docent(), "doc_5I66K");
        t.prejmi(new Tretja.Docent(), "doc_PMpTZ");
        t.prejmi(new Tretja.Asistent(), "as_rqBmW");
        t.prejmi(new Tretja.Asistent(), "as_lJiDm");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_TdjEK");
        t.prejmi(new Tretja.Docent(), "doc_V8gRu");
        t.prejmi(new Tretja.Asistent(), "as_M9qWq");
        t.prejmi(new Tretja.Asistent(), "as_lwUNq");
        t.prejmi(new Tretja.Asistent(), "as_NjoOy");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_py9cY");
        t.prejmi(new Tretja.Profesor(), "prof_ft1bh");
        t.prejmi(new Tretja.Docent(), "doc_3esLy");
        t.prejmi(new Tretja.Docent(), "doc_ZeiO2");
        t.prejmi(new Tretja.Asistent(), "as_e010l");
        t.prejmi(new Tretja.Asistent(), "as_0p3Se");
        t.prejmi(new Tretja.Asistent(), "as_hK5AJ");
        t.prejmi(new Tretja.Asistent(), "as_swbIc");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_qANnE");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_Jdmys");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_N1zXu");
        t.prejmi(new Tretja.Profesor(), "prof_vMpXy");
        t.prejmi(new Tretja.Asistent(), "as_0z5WG");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_w7ACt");
        t.prejmi(new Tretja.Asistent(), "as_0yEyQ");
        t.prejmi(new Tretja.Docent(), "doc_UvQUa");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_XZW9L");
        t.prejmi(new Tretja.Profesor(), "prof_7VSXB");
        t.prejmi(new Tretja.Docent(), "doc_XIDMH");
        t.prejmi(new Tretja.Docent(), "doc_eztEH");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_QnbRS");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_CwUu6");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_eG7Rr");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_dqZ4r");
        t.prejmi(new Tretja.Asistent(), "as_EyF3p");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_40MvK");
        t.prejmi(new Tretja.Asistent(), "as_Y9QbJ");
        t.prejmi(new Tretja.Asistent(), "as_WeBNj");
        t.prejmi(new Tretja.Docent(), "doc_zfiPE");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_zQWRj");
        t.prejmi(new Tretja.Docent(), "doc_9tIqJ");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_eQkM4");
        t.prejmi(new Tretja.Asistent(), "as_rh0RT");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_i6GpN");
        t.prejmi(new Tretja.Profesor(), "prof_pwxzL");
        t.prejmi(new Tretja.Profesor(), "prof_vOQtH");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_2UVnc");
        t.prejmi(new Tretja.Docent(), "doc_tDpHI");
        t.prejmi(new Tretja.Profesor(), "prof_8aVBi");
        t.prejmi(new Tretja.Profesor(), "prof_Zxp3t");
        t.prejmi(new Tretja.Profesor(), "prof_LqS7c");
        t.prejmi(new Tretja.Docent(), "doc_HoiN0");
        t.prejmi(new Tretja.Profesor(), "prof_nwHtx");
        t.prejmi(new Tretja.Docent(), "doc_7h2O2");
        t.prejmi(new Tretja.Profesor(), "prof_GiScG");
        t.prejmi(new Tretja.Asistent(), "as_qdBit");
        t.prejmi(new Tretja.Profesor(), "prof_9EBhX");
        t.prejmi(new Tretja.Docent(), "doc_Zjrbf");
        t.prejmi(new Tretja.Asistent(), "as_CmvdD");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_lbouj");
        t.prejmi(new Tretja.Docent(), "doc_ngUk2");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_zBHmJ");
        t.prejmi(new Tretja.Asistent(), "as_Ji9w1");
        t.prejmi(new Tretja.Asistent(), "as_Ihf7B");
        t.prejmi(new Tretja.Asistent(), "as_TVZZC");
        t.prejmi(new Tretja.Asistent(), "as_c8Rc4");
        t.prejmi(new Tretja.Docent(), "doc_QrkLW");
        t.prejmi(new Tretja.Profesor(), "prof_PyUmz");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_wB4nH");
        t.prejmi(new Tretja.Asistent(), "as_qRdu1");
        t.prejmi(new Tretja.Profesor(), "prof_qgnSl");
        t.prejmi(new Tretja.Asistent(), "as_0UQTN");
        t.prejmi(new Tretja.Asistent(), "as_yaCXR");
        t.prejmi(new Tretja.Asistent(), "as_q7g2D");
        t.prejmi(new Tretja.Docent(), "doc_p9ijv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_1oV2y");
        t.prejmi(new Tretja.Profesor(), "prof_5tsgI");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_fhHCv");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_41rZS");
        t.prejmi(new Tretja.Profesor(), "prof_RWVwW");
        t.prejmi(new Tretja.Asistent(), "as_SoVXH");
        t.prejmi(new Tretja.Asistent(), "as_sdcEx");
        System.out.println(t.dolzinaVrste());
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_5Ttmu");
        t.prejmi(new Tretja.Profesor(), "prof_JJrxC");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Profesor(), "prof_fcIuM");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Asistent(), "as_oQ8at");
        t.prejmi(new Tretja.Docent(), "doc_1cqTC");
        t.prejmi(new Tretja.Asistent(), "as_iraZV");
        t.prejmi(new Tretja.Asistent(), "as_0W9pI");
        t.prejmi(new Tretja.Asistent(), "as_bpnDD");
        t.prejmi(new Tretja.Docent(), "doc_cdoyc");
        t.prejmi(new Tretja.Profesor(), "prof_iSOJS");
        t.prejmi(new Tretja.Profesor(), "prof_TH6Z9");
        t.prejmi(new Tretja.Profesor(), "prof_GGiGK");
        t.prejmi(new Tretja.Docent(), "doc_6Wph9");
        t.prejmi(new Tretja.Asistent(), "as_YjEsZ");
        t.prejmi(new Tretja.Asistent(), "as_bvGmY");
        t.prejmi(new Tretja.Docent(), "doc_noUIS");
        t.prejmi(new Tretja.Docent(), "doc_RGAh7");
        System.out.println(t.dolzinaVrste());
        t.prejmi(new Tretja.Docent(), "doc_5gLpV");
        t.prejmi(new Tretja.Docent(), "doc_oHUxf");
        t.prejmi(new Tretja.Docent(), "doc_X73uB");
        t.prejmi(new Tretja.Profesor(), "prof_8ww7a");
        t.prejmi(new Tretja.Asistent(), "as_tiHao");
        t.prejmi(new Tretja.Profesor(), "prof_8luJ4");
        t.prejmi(new Tretja.Asistent(), "as_HAKFK");
        t.prejmi(new Tretja.Asistent(), "as_urAl7");
    }
}
