
public class Test33 {

    public static void main(String[] args) {
        Tretja.Tiskalnik t = new Tretja.Tiskalnik();
        t.prejmi(new Tretja.Docent(), "doc_uS2b9");
        t.prejmi(new Tretja.Profesor(), "prof_7BUUg");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_czHEJ");
        t.prejmi(new Tretja.Profesor(), "prof_p7R3P");
        t.prejmi(new Tretja.Profesor(), "prof_4dzyI");
        t.prejmi(new Tretja.Docent(), "doc_NWYb0");
        t.prejmi(new Tretja.Asistent(), "as_ibApg");
        t.prejmi(new Tretja.Docent(), "doc_L5IMw");
        t.prejmi(new Tretja.Docent(), "doc_SWqap");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_ztjTY");
        t.prejmi(new Tretja.Profesor(), "prof_5lx8M");
        t.prejmi(new Tretja.Profesor(), "prof_7DYVb");
        t.prejmi(new Tretja.Asistent(), "as_4GDpn");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_PligO");
        t.prejmi(new Tretja.Profesor(), "prof_iEXir");
        t.prejmi(new Tretja.Asistent(), "as_XzX2j");
        t.prejmi(new Tretja.Profesor(), "prof_3BblQ");
        t.prejmi(new Tretja.Docent(), "doc_fDN3m");
        t.prejmi(new Tretja.Profesor(), "prof_FHd90");
        t.prejmi(new Tretja.Profesor(), "prof_S00Lk");
        t.prejmi(new Tretja.Docent(), "doc_ll5NF");
        t.prejmi(new Tretja.Profesor(), "prof_sLNiB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_KGRvN");
        t.prejmi(new Tretja.Asistent(), "as_bcKuf");
        t.prejmi(new Tretja.Docent(), "doc_x2s5Y");
        t.prejmi(new Tretja.Profesor(), "prof_6nzbH");
        t.prejmi(new Tretja.Docent(), "doc_Ff0bG");
        t.prejmi(new Tretja.Asistent(), "as_pos9o");
        t.prejmi(new Tretja.Docent(), "doc_yxVUw");
        t.prejmi(new Tretja.Asistent(), "as_0I8it");
        t.prejmi(new Tretja.Profesor(), "prof_IOqh2");
        t.prejmi(new Tretja.Asistent(), "as_6lYYF");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_3MyKw");
        t.prejmi(new Tretja.Docent(), "doc_i5673");
        t.prejmi(new Tretja.Profesor(), "prof_NHsan");
        t.prejmi(new Tretja.Docent(), "doc_VLMns");
        t.prejmi(new Tretja.Profesor(), "prof_6Eqjd");
        t.prejmi(new Tretja.Asistent(), "as_S2iMC");
        t.prejmi(new Tretja.Profesor(), "prof_0CBE1");
        t.prejmi(new Tretja.Profesor(), "prof_zfY2U");
        t.prejmi(new Tretja.Asistent(), "as_KltPn");
        t.prejmi(new Tretja.Docent(), "doc_s0ly7");
        t.prejmi(new Tretja.Docent(), "doc_r7cuG");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_aPgvS");
        t.prejmi(new Tretja.Profesor(), "prof_6Ueqi");
        t.prejmi(new Tretja.Asistent(), "as_Ez0Ot");
        t.prejmi(new Tretja.Asistent(), "as_tKiP2");
        t.prejmi(new Tretja.Docent(), "doc_LemXD");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_7AbYl");
        t.prejmi(new Tretja.Asistent(), "as_wtyqh");
        t.prejmi(new Tretja.Asistent(), "as_UzOvP");
        t.prejmi(new Tretja.Docent(), "doc_5tI18");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_3n2ht");
        t.prejmi(new Tretja.Docent(), "doc_61gPZ");
        t.prejmi(new Tretja.Profesor(), "prof_9FO5J");
        t.prejmi(new Tretja.Profesor(), "prof_FBtpQ");
        t.prejmi(new Tretja.Docent(), "doc_4ty7w");
        t.prejmi(new Tretja.Profesor(), "prof_ietjZ");
        t.prejmi(new Tretja.Profesor(), "prof_qx0Um");
        t.prejmi(new Tretja.Asistent(), "as_dJGAL");
        t.prejmi(new Tretja.Profesor(), "prof_OTxBf");
        t.prejmi(new Tretja.Profesor(), "prof_LfxMf");
        t.prejmi(new Tretja.Asistent(), "as_TW3Ey");
        t.prejmi(new Tretja.Docent(), "doc_dirIF");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_rwLCs");
        t.prejmi(new Tretja.Docent(), "doc_58lC5");
        t.prejmi(new Tretja.Asistent(), "as_6CK1M");
        t.prejmi(new Tretja.Asistent(), "as_Rxwcm");
        t.prejmi(new Tretja.Docent(), "doc_rSk7p");
        t.prejmi(new Tretja.Asistent(), "as_btSWJ");
        t.prejmi(new Tretja.Asistent(), "as_qY5kD");
        t.prejmi(new Tretja.Profesor(), "prof_x10Tt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_HL7aI");
        t.prejmi(new Tretja.Docent(), "doc_VFNFz");
        t.prejmi(new Tretja.Docent(), "doc_aBNgV");
        t.prejmi(new Tretja.Asistent(), "as_Bd8w2");
        t.prejmi(new Tretja.Asistent(), "as_G87PC");
        t.prejmi(new Tretja.Profesor(), "prof_VCdzG");
        t.prejmi(new Tretja.Docent(), "doc_iI8FG");
        t.prejmi(new Tretja.Profesor(), "prof_R9PaV");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_7SXtr");
        t.prejmi(new Tretja.Asistent(), "as_e6Yo1");
        t.prejmi(new Tretja.Asistent(), "as_GQP8m");
        t.prejmi(new Tretja.Docent(), "doc_iDIel");
        t.prejmi(new Tretja.Asistent(), "as_aWzCa");
        t.prejmi(new Tretja.Profesor(), "prof_TS9YS");
        t.prejmi(new Tretja.Docent(), "doc_fi1XP");
        t.prejmi(new Tretja.Profesor(), "prof_MBq1U");
        t.prejmi(new Tretja.Docent(), "doc_snOqn");
        t.prejmi(new Tretja.Asistent(), "as_fQ36N");
        t.prejmi(new Tretja.Asistent(), "as_wsGBS");
        t.prejmi(new Tretja.Profesor(), "prof_CzBLr");
        t.prejmi(new Tretja.Docent(), "doc_qKsjB");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_44EcI");
        t.prejmi(new Tretja.Docent(), "doc_p6Ehr");
        t.prejmi(new Tretja.Asistent(), "as_3wZ1q");
        t.prejmi(new Tretja.Docent(), "doc_VRcDR");
        t.prejmi(new Tretja.Docent(), "doc_vZrvz");
        t.prejmi(new Tretja.Docent(), "doc_g2bFI");
        t.prejmi(new Tretja.Asistent(), "as_DEBic");
        t.prejmi(new Tretja.Asistent(), "as_3uZmW");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_ptJ20");
        t.prejmi(new Tretja.Docent(), "doc_iFFTk");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_OVTOe");
        t.prejmi(new Tretja.Docent(), "doc_VXtV3");
        t.prejmi(new Tretja.Profesor(), "prof_AKyfn");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_16aI0");
        t.prejmi(new Tretja.Docent(), "doc_mGPHC");
        t.prejmi(new Tretja.Profesor(), "prof_QGK1r");
        t.prejmi(new Tretja.Asistent(), "as_rUTLN");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_16JIw");
        t.prejmi(new Tretja.Docent(), "doc_MrGyw");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_StVnc");
        t.prejmi(new Tretja.Profesor(), "prof_ui01x");
        t.prejmi(new Tretja.Asistent(), "as_waeZr");
        t.prejmi(new Tretja.Profesor(), "prof_M5vKf");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_kpTN6");
        t.prejmi(new Tretja.Docent(), "doc_IF6YG");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_WCBHX");
        t.prejmi(new Tretja.Docent(), "doc_z6VUq");
        t.prejmi(new Tretja.Docent(), "doc_nWO3h");
        t.prejmi(new Tretja.Profesor(), "prof_9cJFj");
        t.prejmi(new Tretja.Profesor(), "prof_QCdDX");
        t.prejmi(new Tretja.Asistent(), "as_7QTUo");
        t.prejmi(new Tretja.Docent(), "doc_GRfYt");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_nP2Ab");
        t.prejmi(new Tretja.Asistent(), "as_dodM1");
        t.prejmi(new Tretja.Asistent(), "as_WFktl");
        t.prejmi(new Tretja.Docent(), "doc_Qn84j");
        t.prejmi(new Tretja.Profesor(), "prof_mqdS4");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_d30yt");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_TRU0c");
        t.prejmi(new Tretja.Profesor(), "prof_Bk1CM");
        t.prejmi(new Tretja.Docent(), "doc_BHHs7");
        t.prejmi(new Tretja.Docent(), "doc_7oEtX");
        t.prejmi(new Tretja.Docent(), "doc_IgCWx");
        t.prejmi(new Tretja.Profesor(), "prof_hTKaq");
        t.prejmi(new Tretja.Asistent(), "as_8U5ax");
        t.prejmi(new Tretja.Asistent(), "as_qCmVV");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_e4o9G");
        t.prejmi(new Tretja.Asistent(), "as_7JaYG");
        t.prejmi(new Tretja.Asistent(), "as_8fVlo");
        t.prejmi(new Tretja.Docent(), "doc_HKnZv");
        t.prejmi(new Tretja.Docent(), "doc_gdwqM");
        t.prejmi(new Tretja.Docent(), "doc_Mv4rw");
        t.prejmi(new Tretja.Docent(), "doc_OdX4f");
        t.prejmi(new Tretja.Asistent(), "as_GGXG7");
        t.prejmi(new Tretja.Docent(), "doc_frrwI");
        t.prejmi(new Tretja.Docent(), "doc_XOOSM");
        t.prejmi(new Tretja.Docent(), "doc_KkXFm");
        t.prejmi(new Tretja.Asistent(), "as_nV7G4");
        t.prejmi(new Tretja.Docent(), "doc_LIWN9");
        t.prejmi(new Tretja.Docent(), "doc_xVbZN");
        t.prejmi(new Tretja.Asistent(), "as_AT8X9");
        t.prejmi(new Tretja.Docent(), "doc_3DZ0A");
        t.prejmi(new Tretja.Profesor(), "prof_OEwIm");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_EnB57");
        t.prejmi(new Tretja.Asistent(), "as_3AS8s");
        t.prejmi(new Tretja.Asistent(), "as_JAnP5");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_SOJab");
        t.prejmi(new Tretja.Profesor(), "prof_aee9e");
        t.prejmi(new Tretja.Docent(), "doc_Zkjoe");
        t.prejmi(new Tretja.Docent(), "doc_RJskt");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_zCKsh");
        t.prejmi(new Tretja.Profesor(), "prof_MJawE");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_STT48");
        t.prejmi(new Tretja.Profesor(), "prof_GnXkM");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_3gW8s");
        t.prejmi(new Tretja.Asistent(), "as_rCbv4");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_S3nY5");
        t.prejmi(new Tretja.Asistent(), "as_SGKBo");
        t.prejmi(new Tretja.Docent(), "doc_HS5Yy");
        t.prejmi(new Tretja.Profesor(), "prof_aKx82");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_tVpY4");
        t.prejmi(new Tretja.Docent(), "doc_Ci3cc");
        t.prejmi(new Tretja.Asistent(), "as_S8xEz");
        t.prejmi(new Tretja.Profesor(), "prof_Umv5q");
        t.prejmi(new Tretja.Profesor(), "prof_wDH5e");
        t.prejmi(new Tretja.Profesor(), "prof_KdFqQ");
        t.prejmi(new Tretja.Docent(), "doc_vMLhx");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_Y3xhD");
        t.prejmi(new Tretja.Docent(), "doc_Lc16M");
        t.prejmi(new Tretja.Docent(), "doc_j1cTW");
        t.prejmi(new Tretja.Profesor(), "prof_IpO54");
        t.prejmi(new Tretja.Profesor(), "prof_Q6gpW");
        t.prejmi(new Tretja.Docent(), "doc_IszCg");
        t.prejmi(new Tretja.Profesor(), "prof_zSQ9M");
        t.prejmi(new Tretja.Asistent(), "as_MwvGM");
        t.prejmi(new Tretja.Profesor(), "prof_pbJkJ");
        t.prejmi(new Tretja.Docent(), "doc_yUTQI");
        t.prejmi(new Tretja.Asistent(), "as_9AoHQ");
        t.prejmi(new Tretja.Profesor(), "prof_m7Kka");
        t.prejmi(new Tretja.Profesor(), "prof_MrADE");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_0eMDI");
        t.prejmi(new Tretja.Docent(), "doc_dqGwm");
        t.prejmi(new Tretja.Docent(), "doc_O0eXW");
        t.prejmi(new Tretja.Profesor(), "prof_07Rm5");
        t.prejmi(new Tretja.Docent(), "doc_oeqOy");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_rnkrL");
        t.prejmi(new Tretja.Profesor(), "prof_mt9vm");
        t.prejmi(new Tretja.Docent(), "doc_NBLlL");
        t.prejmi(new Tretja.Profesor(), "prof_9ihTe");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_lqGB9");
        t.prejmi(new Tretja.Docent(), "doc_buiBt");
        t.prejmi(new Tretja.Docent(), "doc_4QFlb");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_egpg9");
        t.prejmi(new Tretja.Profesor(), "prof_huiQg");
        t.prejmi(new Tretja.Docent(), "doc_BDt83");
        t.prejmi(new Tretja.Docent(), "doc_iURVg");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Asistent(), "as_OUzWv");
        t.prejmi(new Tretja.Docent(), "doc_qSZuM");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Docent(), "doc_AMR6w");
        t.prejmi(new Tretja.Asistent(), "as_euN1l");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_ay2Sp");
        t.prejmi(new Tretja.Asistent(), "as_QYIl6");
        t.prejmi(new Tretja.Profesor(), "prof_AEiai");
        t.prejmi(new Tretja.Profesor(), "prof_65u2S");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_hG22O");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Profesor(), "prof_laVyv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_9yrrD");
        t.prejmi(new Tretja.Asistent(), "as_h7ahw");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_wXuSO");
        t.prejmi(new Tretja.Profesor(), "prof_8Desf");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Asistent(), "as_aKxZh");
        System.out.println(t.steviloDokumentov(new Tretja.Docent()));
        t.prejmi(new Tretja.Docent(), "doc_anhGA");
        t.prejmi(new Tretja.Asistent(), "as_Gjevv");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Docent(), "doc_gLlwt");
        t.prejmi(new Tretja.Asistent(), "as_0tzqT");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Asistent(), "as_k5sSI");
        System.out.println(t.steviloDokumentov(new Tretja.Asistent()));
        t.prejmi(new Tretja.Profesor(), "prof_03onl");
        t.prejmi(new Tretja.Asistent(), "as_XCm59");
        t.prejmi(new Tretja.Profesor(), "prof_3N28N");
        t.prejmi(new Tretja.Profesor(), "prof_n3fCV");
        t.prejmi(new Tretja.Asistent(), "as_sFeXc");
        t.prejmi(new Tretja.Asistent(), "as_To1CW");
        t.prejmi(new Tretja.Asistent(), "as_NhqwY");
        t.prejmi(new Tretja.Docent(), "doc_Kl7mz");
        t.prejmi(new Tretja.Asistent(), "as_yxYBw");
        t.prejmi(new Tretja.Docent(), "doc_QUfB2");
        t.prejmi(new Tretja.Profesor(), "prof_sFiaQ");
        t.prejmi(new Tretja.Asistent(), "as_NgwSP");
        System.out.println(t.steviloDokumentov(new Tretja.Profesor()));
        t.prejmi(new Tretja.Profesor(), "prof_mbtkB");
        t.prejmi(new Tretja.Profesor(), "prof_X5AOP");
        t.prejmi(new Tretja.Asistent(), "as_ZOUyO");
        t.prejmi(new Tretja.Docent(), "doc_dnnr4");
        t.prejmi(new Tretja.Profesor(), "prof_zhw7g");
        t.prejmi(new Tretja.Docent(), "doc_fiKdT");
        t.prejmi(new Tretja.Asistent(), "as_0H8Q4");
        t.prejmi(new Tretja.Docent(), "doc_iFuAq");
        t.prejmi(new Tretja.Docent(), "doc_DtJuQ");
    }
}
