
public class Test04 {

    public static void main(String[] args) {
        Vektor<Lik> liki = new Vektor<>();
        liki.dodaj(new Krog(20));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(16));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Krog(16));
        liki.dodaj(new Pravokotnik(4, 20));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Kvadrat(3));
        liki.dodaj(new Pravokotnik(3, 20));
        liki.dodaj(new Krog(19));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Pravokotnik(11, 6));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Pravokotnik(7, 8));
        liki.dodaj(new Pravokotnik(8, 10));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Pravokotnik(9, 6));
        liki.dodaj(new Pravokotnik(4, 13));
        liki.dodaj(new Pravokotnik(4, 8));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Krog(19));
        liki.dodaj(new Pravokotnik(16, 20));
        liki.dodaj(new Pravokotnik(10, 3));
        liki.dodaj(new Pravokotnik(8, 11));
        liki.dodaj(new Pravokotnik(15, 7));
        liki.dodaj(new Pravokotnik(17, 12));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(19));
        liki.dodaj(new Krog(16));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Kvadrat(12));
        liki.dodaj(new Kvadrat(9));
        liki.dodaj(new Krog(10));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Pravokotnik(20, 19));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Pravokotnik(17, 1));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Pravokotnik(13, 2));
        liki.dodaj(new Kvadrat(1));
        liki.dodaj(new Pravokotnik(14, 19));
        liki.dodaj(new Pravokotnik(7, 13));
        liki.dodaj(new Pravokotnik(18, 13));
        liki.dodaj(new Pravokotnik(2, 10));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Pravokotnik(9, 5));
        liki.dodaj(new Pravokotnik(13, 17));
        liki.dodaj(new Pravokotnik(8, 10));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Pravokotnik(16, 12));
        liki.dodaj(new Pravokotnik(16, 8));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Pravokotnik(12, 1));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Pravokotnik(18, 4));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Kvadrat(12));
        liki.dodaj(new Pravokotnik(13, 2));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Pravokotnik(6, 8));
        liki.dodaj(new Pravokotnik(4, 6));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Kvadrat(1));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(20, 19));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Pravokotnik(14, 12));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(1));
        liki.dodaj(new Pravokotnik(1, 5));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Pravokotnik(18, 19));
        liki.dodaj(new Pravokotnik(20, 8));
        liki.dodaj(new Pravokotnik(1, 15));
        liki.dodaj(new Pravokotnik(15, 12));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Pravokotnik(14, 9));
        liki.dodaj(new Pravokotnik(7, 15));
        liki.dodaj(new Pravokotnik(12, 16));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Krog(16));
        liki.dodaj(new Pravokotnik(3, 8));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Pravokotnik(3, 4));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Krog(6));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Pravokotnik(8, 11));
        liki.dodaj(new Pravokotnik(3, 20));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Pravokotnik(4, 11));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Pravokotnik(11, 1));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Pravokotnik(12, 12));
        liki.dodaj(new Pravokotnik(19, 5));
        liki.dodaj(new Pravokotnik(10, 13));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Pravokotnik(6, 9));
        liki.dodaj(new Pravokotnik(12, 18));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Pravokotnik(5, 12));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Pravokotnik(15, 19));
        liki.dodaj(new Kvadrat(16));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Pravokotnik(5, 15));
        liki.dodaj(new Pravokotnik(10, 1));
        liki.dodaj(new Pravokotnik(2, 10));
        liki.dodaj(new Pravokotnik(12, 9));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(12));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Pravokotnik(12, 5));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Pravokotnik(15, 12));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Pravokotnik(3, 5));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Pravokotnik(12, 2));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Pravokotnik(1, 8));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Pravokotnik(3, 9));
        liki.dodaj(new Pravokotnik(17, 10));
        liki.dodaj(new Pravokotnik(12, 18));
        liki.dodaj(new Kvadrat(16));
        liki.dodaj(new Pravokotnik(19, 13));
        liki.dodaj(new Pravokotnik(16, 2));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Pravokotnik(19, 17));
        liki.dodaj(new Pravokotnik(8, 3));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Pravokotnik(6, 18));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Pravokotnik(13, 11));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Pravokotnik(9, 5));
        liki.dodaj(new Pravokotnik(19, 19));
        liki.dodaj(new Pravokotnik(7, 20));
        liki.dodaj(new Kvadrat(16));
        liki.dodaj(new Pravokotnik(18, 16));
        liki.dodaj(new Pravokotnik(14, 12));
        liki.dodaj(new Krog(14));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Pravokotnik(11, 2));
        liki.dodaj(new Pravokotnik(12, 18));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Pravokotnik(13, 4));
        liki.dodaj(new Pravokotnik(4, 12));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Pravokotnik(16, 13));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(10, 17));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(15, 12));
        liki.dodaj(new Pravokotnik(12, 19));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Pravokotnik(14, 1));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Pravokotnik(7, 11));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Pravokotnik(10, 19));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Pravokotnik(18, 9));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Pravokotnik(17, 18));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(16));
        liki.dodaj(new Kvadrat(3));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(18, 17));
        liki.dodaj(new Pravokotnik(14, 8));
        liki.dodaj(new Pravokotnik(16, 8));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Pravokotnik(14, 3));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Pravokotnik(11, 14));
        liki.dodaj(new Pravokotnik(19, 8));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(11, 20));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Pravokotnik(17, 7));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Pravokotnik(18, 17));
        liki.dodaj(new Krog(19));
        liki.dodaj(new Krog(6));
        liki.dodaj(new Pravokotnik(16, 17));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Pravokotnik(14, 13));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Krog(16));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Kvadrat(12));
        liki.dodaj(new Pravokotnik(9, 7));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Pravokotnik(9, 15));
        liki.dodaj(new Pravokotnik(1, 8));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(1, 5));
        liki.dodaj(new Pravokotnik(17, 1));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Pravokotnik(14, 13));
        liki.dodaj(new Pravokotnik(7, 9));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Pravokotnik(12, 16));
        liki.dodaj(new Pravokotnik(10, 8));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(12, 14));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Pravokotnik(10, 11));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Pravokotnik(2, 18));
        liki.dodaj(new Pravokotnik(8, 1));
        liki.dodaj(new Pravokotnik(5, 3));
        liki.dodaj(new Pravokotnik(16, 6));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(12, 14));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Krog(10));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Pravokotnik(11, 20));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Pravokotnik(1, 13));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Pravokotnik(11, 18));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Kvadrat(12));
        liki.dodaj(new Pravokotnik(9, 5));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Kvadrat(16));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(9));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Pravokotnik(7, 11));
        liki.dodaj(new Pravokotnik(1, 19));
        liki.dodaj(new Pravokotnik(7, 20));
        liki.dodaj(new Pravokotnik(3, 6));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(19, 14));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(12, 19));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(17, 12));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Pravokotnik(16, 13));
        liki.dodaj(new Pravokotnik(4, 11));
        liki.dodaj(new Pravokotnik(6, 16));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(7, 4));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Krog(2));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(18, 3));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Pravokotnik(16, 6));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Pravokotnik(20, 7));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(1));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Pravokotnik(3, 4));
        liki.dodaj(new Krog(8));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Krog(3));
        liki.dodaj(new Pravokotnik(2, 16));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(9));
        liki.dodaj(new Krog(10));
        liki.dodaj(new Pravokotnik(14, 12));
        liki.dodaj(new Pravokotnik(19, 16));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Pravokotnik(17, 4));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Pravokotnik(9, 12));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Pravokotnik(1, 14));
        liki.dodaj(new Kvadrat(7));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Pravokotnik(1, 15));
        liki.dodaj(new Pravokotnik(12, 1));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Pravokotnik(10, 2));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Pravokotnik(2, 15));
        liki.dodaj(new Pravokotnik(2, 1));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Pravokotnik(10, 18));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Krog(13));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Pravokotnik(7, 8));
        liki.dodaj(new Krog(6));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(11, 7));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Pravokotnik(19, 7));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Kvadrat(9));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Krog(18));
        liki.dodaj(new Kvadrat(1));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Pravokotnik(15, 3));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Krog(10));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(13));
        liki.dodaj(new Pravokotnik(17, 8));
        liki.dodaj(new Pravokotnik(2, 11));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(9, 15));
        liki.dodaj(new Pravokotnik(5, 11));
        liki.dodaj(new Pravokotnik(15, 12));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Krog(4));
        liki.dodaj(new Pravokotnik(5, 10));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(17));
        liki.dodaj(new Kvadrat(10));
        liki.dodaj(new Pravokotnik(9, 5));
        liki.dodaj(new Pravokotnik(2, 1));
        liki.dodaj(new Pravokotnik(18, 3));
        liki.dodaj(new Krog(15));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Pravokotnik(19, 3));
        liki.dodaj(new Pravokotnik(17, 8));
        liki.dodaj(new Pravokotnik(16, 20));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Krog(11));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Pravokotnik(5, 9));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Kvadrat(17));
        liki.dodaj(new Pravokotnik(6, 5));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Pravokotnik(20, 2));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Kvadrat(15));
        liki.dodaj(new Pravokotnik(3, 13));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Kvadrat(20));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(18));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Krog(5));
        liki.dodaj(new Kvadrat(19));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Pravokotnik(3, 9));
        liki.dodaj(new Pravokotnik(1, 18));
        liki.dodaj(new Pravokotnik(15, 3));
        liki.dodaj(new Kvadrat(2));
        liki.dodaj(new Kvadrat(3));
        liki.dodaj(new Kvadrat(8));
        liki.dodaj(new Kvadrat(4));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(9));
        liki.dodaj(new Pravokotnik(12, 20));
        liki.dodaj(new Kvadrat(6));
        liki.dodaj(new Krog(12));
        liki.dodaj(new Pravokotnik(19, 19));
        liki.dodaj(new Krog(7));
        liki.dodaj(new Krog(1));
        liki.dodaj(new Kvadrat(14));
        liki.dodaj(new Krog(6));
        liki.dodaj(new Kvadrat(11));
        liki.dodaj(new Krog(20));
        liki.dodaj(new Kvadrat(5));
        liki.dodaj(new Kvadrat(12));

        Skupno.uredi(liki, Lik.poObsegu());
        Lik.izpisi(liki);
    }
}
